[translation]
"10026035-2-コハル" = "はあ、はあ……はあ……。"
"10026035-3-コハル" = "もう、何なのよ、あいつら……！#nなんでここに居るの！？"
"10026035-4-コハル" = "それに……どうしてあんな格好を……！？"
"10026035-5-コハル" = "うぅっ……ビックリして腰が抜けちゃった……"
"10026035-6" = "[s1] \"コハル、大丈夫？\"\n[s2] \"どこも怪我してない？\""
"10026035-9-コハル" = "う、うん……とりあえず、何とか……"
"10026035-13-コハル" = "ひいいぃっ！！む、無理！やっぱり無理っ！"
"10026035-14" = "[s3] \"それじゃ……はい。\"\n[s4] \"しっかり掴まっててね。\""
"10026035-20-コハル" = "……せ、先生！？"
"10026035-22-ウイ" = "……結局、不審な点は見つかりませんでしたね。#nこの場所は、何に使われていたのでしょう……？"
"10026035-23-ウイ" = "……ところで、遅いですね……あの二人。#nひょっとして、道に迷ったとか……"
"10026035-24-ハナコ" = "かなりの広さでしたからね。"
"10026035-25-ヒナタ" = "そんな……私が探しに行ってみましょうか？"
"10026035-26-ウイ" = "いえ、それはやめておきましょう。闇雲に探しては、ミイラ取りがミイラになるようなものです。探しに行くとしても、何か事前に対策を……"
"10026035-27-ハナコ" = "……あ、来ましたよ。"
"10026035-37" = "[ns5] \"やっと戻ってこられた……。\"\n[ns6] \"本当にビックリしたね。\""
"10026035-40-ハナコ" = "良かったです、先生。無事に戻ってきてくださって、一安心です。"
"10026035-41-ハナコ" = "ちょうど、お二人を探しにいこうかと話し合っていたところでした。"
"10026035-42-ハナコ" = "え？私たちは、特に何もありませんでしたが……"
"10026035-43-ハナコ" = "……それは本当ですか？"
"10026035-44-ハナコ" = "水着を着た[ruby=ミメシス]複製[/ruby]が……？"
"10026035-45-ヒナタ" = "み、ミメシスですか！？"
"10026035-46-ハナコ" = "あら、なるほど……"
"10026035-47-ハナコ" = "たしかに、あり得ない話ではありませんね。ここは聖徒会の遺跡ですし。"
"10026035-48-ウイ" = "ど、どうして誰も、水着にはツッコまないんですか……？"
"10026035-49-ハナコ" = "ふふっ……水着かどうかなんて、些細な問題ですから。"
"10026035-50-ハナコ" = "……ところで。"
"10026035-51-ハナコ" = "私も予想外のことがあったのですが……♡"
"10026035-52" = "[s7] \"……予想外？\"\n[s8] \"ハナコたちも何か見つけたの？\""
"10026035-55-ハナコ" = "先生……"
"10026035-56-ハナコ" = "まずは、おんぶしている人を降ろしてからお話をしましょう。"
"10026035-57" = "[s] \"…………？\""
"10026035-59" = "[ns] \"…………。\""
"10026035-60-ハナコ" = "……コハルちゃん♡"
"10026035-61-ハナコ" = "私たちが居ない間に、お二人ともそれはそれは熱い時間を過ごしてきたんですね♡"
"10026035-62-コハル" = "ほ、本当にすごかったんだから！ハナコも絶対、驚くわよ！"
"10026035-63-コハル" = "……って、ん？"
"10026035-64-コハル" = "な、なに言ってんの！？"
"10026035-65-ハナコ" = "何か間違っていましたか？"
"10026035-66-ハナコ" = "先生の背中に、そんな風にぎゅうっと抱きついて……♡"
"10026035-71-コハル" = "……？"
"10026035-72-コハル" = "えっと……その、これは……"
"10026035-77-コハル" = "い、いや！いやいやいやいやいやいや！！！違うから、信じて！！！#n本当に違うって、そうじゃないの！"
"10026035-78-コハル" = "こっ、これは、ただ腰が抜けちゃって……！"
"10026035-79-ハナコ" = "……あら♡"
"10026035-80-コハル" = "違うってば！違うの！！違うから！！！#nそういうんじゃないから！！！"
"10026035-82-コハル" = "本当に違うんだってばっ！！！！！"
