[translation]
"33095-2-ヒナ" = "はぁ、はぁ……はぁ……"
"33095-3-ヒナ" = "くっ……"
"33095-7" = "[ns] \"ヒナっ！！\""
"33095-12-ミサキ" = "ゲヘナの風紀委員長、ようやく倒れた。"
"33095-13-ヒヨリ" = "や、やっとですか……痛かったですよねぇ、よくあの傷でここまで……。"
"33095-14-アツコ" = "……。"
"33095-15-サオリ" = "トリニティとゲヘナの主要人物は全部片付いた。残りはもう貴様だけだ、シャーレの先生。"
"33095-16" = "[s] \"……君たちが、アリウススクワッド？\""
"33095-17-サオリ" = "……。"
"33095-18-ミサキ" = "ふぅ……。"
"33095-19-ヒヨリ" = "えへへ……。"
"33095-20-アツコ" = "……。"
"33095-24-サオリ" = "……ああ、そうだ。私たちが「アリウススクワッド」。ようやく会えたな、先生。"
"33095-25" = "[s] \"……！\""
"33095-26-サオリ" = "アズサが世話になったと聞いた。あいつには今から会いに行く予定だ。"
"33095-27-サオリ" = "……我々はトリニティに代わり、この「通功の古聖堂」で条約に調印した。"
"33095-28-アツコ" = "……。"
"33095-29" = "[s] \"……どういう意味？\""
"33095-30-サオリ" = "私たち「アリウススクワッド」が、楽園の名の下に条約を守護する新たな武力集団……「[ruby=ETO]エデン条約機構[/ruby]」になったということだ。"
"33095-31" = "[s] \"！？\""
"33095-32-サオリ" = "これは元々、私たちの義務だった。本来ならば第一回公会議の時点で、私たちが行使すべき当然の権利。"
"33095-33-サオリ" = "だがそれを、トリニティが踏みにじった。私たちを紛争の原因、すなわち「鎮圧対象」として定義し、徹底的に弾圧を行った。"
"33095-34-サオリ" = "……これからは「アリウススクワッド」が[ruby=ETO]エデン条約機構[/ruby]としての権限を行使し、「鎮圧対象」を定義し直す。"
"33095-35-サオリ" = "ゲヘナ、そしてトリニティ。この両校こそエデン条約に反する紛争要素であり、排除すべき鎮圧対象だ。"
"33095-36" = "[s] \"それは、つまり……。\""
"33095-37-サオリ" = "トリニティとゲヘナを、キヴォトスから消し去る。文字通りにな。"
"33095-44-サオリ" = "……この条約の戒律、その守護者たちと共に。"
"33095-45-サオリ" = "貴様らは第一回公会議以来、数百年に渡って積み上げられてきた恨み……私たちの憎悪を確認することになるだろう。"
"33095-46-サオリ" = "……だがその前に、貴様を処理しておくとしようか。"
"33095-50" = "[ns] \"（銃口が……）\""
"33095-51-サオリ" = "シャーレの先生……貴様が計画の一番の支障になりそうだと、彼女は言っていたからな。"
"33095-54-ヒナ" = "ああぁあぁぁぁっ！！！"
"33095-60-サオリ" = "……っ！まだ動けるのか、空崎ヒナ！"
"33095-61-ヒナ" = "セナっ！ こっち！！"
"33095-65-ヒヨリ" = "救急車……！？"
"33095-74-セナ" = "先生！手を！"
"33095-78-サオリ" = "逃すかっ！！"
"33095-82-ヒヨリ" = "ま、まだそんな力が……。"
"33095-89-ミサキ" = "……逃げられた。"
"33095-90-サオリ" = "まあ良い。空崎ヒナに妨害はされたが、銃弾は当たっている。"
"33095-91-サオリ" = "あれはキヴォトスの外の者だ。ヘイローは壊れ……いや、死ぬはずだ。"
"33095-92-サオリ" = "しかし、あの様子……あの先生が、そんなに大事な存在なのか。"
"33095-93-アツコ" = "……。"
"33095-94-ヒヨリ" = "「あの人がいなかったら、全て計画通りになったはず」……？そ、そうなんですか姫ちゃん？え、「それにアズサもきっと……」？"
"33095-95-アツコ" = "……。"
"33095-98" = "[ns] \"（お腹が熱い……）\""
"33095-99-セナ" = "よく聞いてください先生、あなたは銃で撃たれました。"
"33095-100-セナ" = "奇跡的に急所は避けていますが、この出血は放っておけません。"
"33095-101-セナ" = "これより応急処置に入ります。痛かったら悲鳴を上げてください。"
"33095-102-セナ" = "死なせはしません。私は、救急医学部ですから。"
"33095-106" = "[ns] \"（意識に、靄が……）\""
"33095-108-アツコ" = "……。"
"33095-109-サオリ" = "……ここでお前が出てくるのか。"
"33095-110-ミサキ" = "まさか姿を現すとはね……そのまま逃げ出しても良かったのに。"
"33095-111-ヒヨリ" = "えへへ、お久しぶりですね……"
"33095-117-アズサ" = "はぁ、はぁ、はぁ……。"
"33095-118-サオリ" = "……どうだ、アズサ。"
"33095-119-アズサ" = "どうして、どうして……"
"33095-120-サオリ" = "私の言った通りだっただろう。トリニティにも、シャーレにも、お前の居場所は無い。"
"33095-121-サオリ" = "私たちみたいな「人殺し」を受け入れてくれる場所なんて、この世界には無いんだよ。"
"33095-122-アズサ" = "どうして、先生を……！"
"33095-123-サオリ" = "そんな場所があるように見えても、全ては儚く消える……さっきの「先生」とやらのようにな。"
"33095-124-サオリ" = "……全ては無駄だ。それなのにどうして足掻くんだ、白洲アズサ。"
"33095-125-アズサ" = "サオリいぃぃぃぃっ！！！！"
"33095-132-サオリ" = "まだ甘い夢に酔っているのか……仕方ない、手伝ってやろう。"
"33095-133-サオリ" = "何度でも、その夢から目を覚まさせてやる。"
"33095-134-サオリ" = "来い。"
"33095-138" = "[ns] \"ここは……。\""
"33095-139-セイア" = "……初めましてかな、先生。"
"33095-140-セイア" = "私の名前は[ruby=ゆりぞの]百合園[/ruby]セイア。"
"33095-141-セイア" = "そしてここは君の夢の中だ……或いは、私の夢の中かもしれないがね。"
"33095-142" = "[s] \"セイア……。\""
"33095-143-セイア" = "おっと、もしかして「初めまして」ではないのかな？"
"33095-144-セイア" = "これは失敬。今の私にとって、時間の流れは少しばかり捻じれていてね。"
"33095-145-セイア" = "しかし先生、大事なのはそこではなく、君と私がこうして会えているということだ。"
"33095-150-セイア" = "さあ……では、お話を紐解いていくとしよう。"
"33095-152" = "次回;甘い嘘"
