[translation]
"33140-1" = "第14話;暗闇の中で"
"33140-5-？？？" = "ウォォォォォォン――――"
"33140-10-ヒヨリ" = "か、確認しました……あれが、例の……。"
"33140-11-サオリ" = "「戦術兵器」か……ただの化け物だな。"
"33140-12-アツコ" = "（スッ、ススッ……）"
"33140-13-ミサキ" = "「太古の教義」をもとに作られた、失敗作……？あの人形、失敗したってこと？"
"33140-14-アツコ" = "（ふるふる）"
"33140-15-アツコ" = "（スッ、ススッ、スーッ、ススッ……）"
"33140-16-ミサキ" = "難しいことはよく分からないけど……失敗作ではありつつも、「戦術兵器」であることに違いは無い？"
"33140-17-ミサキ" = "なら良いけど……そろそろバレる頃合いじゃないの？「ユスティナ聖徒会」にせよ、この「戦術兵器」にせよ、それから私たちの次の目標にせよ。"
"33140-22-サオリ" = "……どのみち、もう手遅れだ。"
"33140-23-サオリ" = "待機中の部隊に連絡を。"
"33140-24-サオリ" = "これより、トリニティへの進撃を開始する。"
"33140-26" = "トリニティ自治区・捨てられた遺跡地帯"
"33140-31" = "トリニティ自治区・カタコンベ"
"33140-36" = "トリニティ自治区・地下水路"
"33140-41-サオリ" = "よし、では命令を――"
"33140-42-サオリ" = "……。"
"33140-43-ミサキ" = "リーダー？"
"33140-44-ヒヨリ" = "ど、どうかされましたか？"
"33140-45-サオリ" = "……私たちがここを空けていたのは、どれくらいだ？"
"33140-46-ヒヨリ" = "3時間くらい、ですかね……。"
"33140-47-サオリ" = "……。"
"33140-48-サオリ" = "……あいつがいる。"
"33140-50-ミサキ" = "あいつ？"
"33140-51-アツコ" = "（スッ、ススッ……）"
"33140-52-ヒヨリ" = "あ、アズサちゃん、ですか？"
"33140-56-ヒヨリ" = "ひっ、ひいいいぃぃっ！？"
"33140-57-ミサキ" = "ブービートラップ、いつの間に……！？"
"33140-58-ヒヨリ" = "あ、こっ、こっちにも！？"
"33140-62-アツコ" = "……！！"
"33140-68-サオリ" = "動くなっ！！"
"33140-69-ミサキ" = "……っ！"
"33140-70-ヒヨリ" = "！！"
"33140-71-アツコ" = "……。"
"33140-72-サオリ" = "この狙いは私たちの動揺だ。私たちの隙を突くためのもの。"
"33140-73-サオリ" = "相変わらず、そういう手法だけは上手い。しかし逆に冷静に対処すれば……"
"33140-77-ヒヨリ" = "いえこの感じ、恐らくまだ周囲にもありますよ！？早く出ないと……！"
"33140-81-サオリ" = "ヒヨリ！"
"33140-85-ミサキ" = "くっ……！"
"33140-86-ヒヨリ" = "く、苦しいですね、痛いですね……どうして人生は、こんなに……"
"33140-91-ミサキ" = "……。"
"33140-92-サオリ" = "……。"
"33140-93-アツコ" = "……。"
"33140-94-ミサキ" = "明らかにヒヨリから狙った。狙撃手から処理したってことは……。"
"33140-95-サオリ" = "……接近戦に持ち込む気か？"
"33140-99" = "（ガチャッ）"
"33140-100-アツコ" = "！！"
"33140-102-ミサキ" = "上っ、手榴弾！"
"33140-106-サオリ" = "[ruby=しらす]白洲[/ruby]アズサっ！！"
"33140-113-サオリ" = "逃がすか！！"
"33140-114-ミサキ" = "リーダー。追いかけたら、それこそ思う壺……"
"33140-118-ミサキ" = "……まあ、仕方ないか。姫、ヒヨリの状態は？"
"33140-119-アツコ" = "（スッ、ススッ、スーッ……）"
"33140-120-ミサキ" = "そっか。"
"33140-121-アツコ" = "（ススッ、スッ……）"
"33140-122-ミサキ" = "……長期戦になる？まあ、アズサが本気になったら確かに……"
"33140-129-ミサキ" = "……リーダーの銃声。追いついたかな。"
"33140-133-アツコ" = "……。"
"33140-134-ミサキ" = "仕方ない。私たちも行こう、姫。"
"33140-135-アツコ" = "……。"
"33140-140-サオリ" = "そっちか！！"
"33140-144-サオリ" = "判断は悪くないな、アズサ！お前では正面から私に勝てない！"
"33140-145-サオリ" = "そうやって逃げて……"
"33140-149-サオリ" = "私の隙を狙うしかないだろうっ！！"
"33140-151-アズサ" = "はぁっ、はぁっ……角を曲がって、次……！"
"33140-158-アズサ" = "っ！？"
"33140-159-アツコ" = "（カチャッ）"
"33140-163-アズサ" = "……っ！"
"33140-164-アツコ" = "……。"
"33140-165-アズサ" = "アツコ……。"
"33140-166-アツコ" = "（スッ、ススッ……）"
"33140-167-アズサ" = "……断る。"
"33140-172" = "ドカアアァァァン！！！"
"33140-173-アツコ" = "……！？"
"33140-177-サオリ" = "アズサっ！！"
"33140-178-ミサキ" = "待って、リーダー。このままじゃキリがない。"
"33140-179-ミサキ" = "ユスティナ聖徒会を呼んだら？"
"33140-180-サオリ" = "……。"
"33140-181-アツコ" = "（ふるふる）"
"33140-182-サオリ" = "聖徒会は、トリニティとゲヘナの紛争にしか介入しない……それにアズサは、トリニティの生徒ではないと解釈される可能性もある。"
"33140-183-ミサキ" = "……ふうん、結構面倒な構造だね。"
"33140-184-アツコ" = "（こくこく）"
"33140-185-サオリ" = "それどころか、アズサが「アリウススクワッドだ」と解釈されたら……"
"33140-186-ミサキ" = "……まあ、戒律も結局は解釈次第ってことだね。確かに元々そうやって手に入れた力だし、制約やらペナルティがあるのも当然かもしれない。"
"33140-187-サオリ" = "ああ。だからこそ、こうするしかない。"
"33140-188-サオリ" = "あいつの戦い方、考え方……それらは全て基本的に、私が教えたものだ。私じゃないと倒せない。"
"33140-189-サオリ" = "追うぞ。"
"33140-193-ミサキ" = "……じゃあ、私は反対の方から。姫は他の道からよろしく。"
"33140-194-アツコ" = "……。"
"33140-195" = "（ゴゴゴゴゴゴゴ……）"
"33140-196-ミサキ" = "何これ、地震……？いや、まさか……"
"33140-197-ミサキ" = "このフロア、全体に……？"
"33140-198" = "ゴゴゴゴゴ……！"
"33140-199-ミサキ" = "くっ、いつの間にこんな……！まずい、上の階が崩れる。走って！"
"33140-201" = "ドカアアアアアァァァァァン！！！"
"33140-203-ミサキ" = "げほっ、げほっ……あー……。"
"33140-204-ミサキ" = "動けないな、これ……。"
"33140-205-サオリ" = "アズサあああぁぁっ！！！"
"33140-210-ミサキ" = "……げほっ。"
"33140-228-サオリ" = "チェックメイトだ、アズサ。"
"33140-229-アズサ" = "……くっ。"
"33140-232-サオリ" = "……お前にしては良くやった。それでも無駄だ。お前の考え方、思考、それらは最初から全てお見通し……。"
"33140-233-サオリ" = "最初から、無駄な抵抗だったんだよ。"
"33140-234-アズサ" = "いつから……？"
"33140-235-サオリ" = "？"
"33140-238-アズサ" = "いつからアリウスは、巡航ミサイルなんて物を……？"
"33140-239-アズサ" = "それにいつの間に、あんな不思議な力を操れるようになったんだ……？"
"33140-240-アズサ" = "……「ヘイローを壊す爆弾」も。"
"33140-241" = "一体、いつから……。"
"33140-244-サオリ" = "……。"
"33140-245-サオリ" = "アズサ、どうしてお前が勝てないのか分かるか？"
"33140-246-サオリ" = "弱いからだ。"
"33140-247-アズサ" = "……。"
"33140-248-サオリ" = "何が人を「人殺し」にすると思う？"
"33140-249-サオリ" = "それは「殺意」の有無。"
"33140-251-サオリ" = "経典に出てくる最初の「人殺し」は、たったひとつの石ころで人を殺めたそうだ。"
"33140-252-サオリ" = "そういうことなんだよ、アズサ。意志さえあれば、道具は関係ない。重要なのはただそこに込められた「意志」だけ。"
"33140-253-サオリ" = "ミサイルを含め、それ以外の手段や何やらは、私たちの恨みを証明する道具でしかない……それ以上でも、それ以下でも無いのさ。"
"33140-256-アズサ" = "サオリ……"
"33140-257-アズサ" = "もう一度聞く、「いつから」だ？"
"33140-258-サオリ" = "……！？"
"33140-259-アズサ" = "その恨み、私はあの時ただあそこで「習った」だけだ……その恨みは、一体誰の――"
"33140-260-サオリ" = "虚しい。"
"33140-265-サオリ" = "弱いな、白洲アズサ。その弱さはお前を縛り付けているんだ。"
"33140-269-サオリ" = "そう、こんな状況でも離そうとしないその人形のように。"
"33140-270-アズサ" = "！！"
"33140-271-サオリ" = "初めてお友達がくれたプレゼント、か？"
"33140-273-サオリ" = "虚しいな。"
"33140-320-サオリ" = "虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい"
"33140-354-サオリ" = "虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい"
"33140-387-サオリ" = "虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい、虚しい"
"33140-388-アズサ" = "ぐっ、あぁぁっ！？"
"33140-389-サオリ" = "虚しいな、アズサ。"
"33140-390-サオリ" = "友情か……ならばその無駄で虚しいものから壊してやろう。たしかヒフミ、だったか？"
"33140-395-アツコ" = "（ふるふる）"
"33140-396-サオリ" = "……姫。"
"33140-397-サオリ" = "……心配しなくても、手加減はしてる。こいつのことなら、よく分かって――"
"33140-407-サオリ" = "アズサ、また逃げるのか！"
"33140-412-アツコ" = "……。"
"33140-413-サオリ" = "……相変わらず逃げ足の速い。"
"33140-417-サオリ" = "まあ良い、どうせあいつはまたやって来る。"
"33140-418-アツコ" = "……？"
"33140-424-サオリ" = "なにせ、この大事な「友情の証」とやらを落としていってしまったからな。"
"33140-425-アツコ" = "……。"
"33140-426-サオリ" = "あいつは必ず、これを取り戻しに来るだろう。"
"33140-427-アツコ" = "（スッ、ススッ……）"
"33140-428-サオリ" = "……闇の中で光を見つけた虫は、もうそれ無しでは生きられない。"
"33140-429-サオリ" = "こんなつまらない物が、アズサの心を支える[ruby=希望]光[/ruby]なんだろう。"
"33140-430-サオリ" = "あいつはこれを諦められない、絶対に戻ってくる。"
"33140-431-サオリ" = "その時にまた捕まえて、あらためてこの世界の真実を教えてやる。"
"33140-433-サオリ" = "そう、無理やりにでも……"
"33140-438-サオリ" = "……ん？"
"33140-439-サオリ" = "何だ、中に……"
"33140-446-サオリ" = "……っ！！"
"33140-447-サオリ" = "これは、セイア襲撃の時に渡した……！"
"33140-448-サオリ" = "逃げろ、姫っ！！！"
"33140-449-アツコ" = "……っ！"
"33140-461-アズサ" = "……。"
"33140-462-アズサ" = "…………。"
"33140-463-アズサ" = "うっ……。"
"33140-464-アズサ" = "うっ、ううっ……。"
"33140-465-アズサ" = "ごめん、ヒフミ……ごめん……。"
"33140-466-アズサ" = "私は……もうこれで、二度と……うっ、ううっ……。"
"33140-468-アズサ" = "ごめん、ごめん、みんな……うっ、うぅぅっ……！！ああぁっ……！！！"
"33140-471" = "次回;五つ目の古則への答え"
