[translation]
"1000120-1" = "熱風"
"1000120-2" = "（エイミに誘われて、ミレニアム近くの砂漠を調べに来た）"
"1000120-3" = "（……かなり長い時間をかけて調べたが、特に何も見つからなかった）"
"1000120-8-エイミ" = "……うーん……。"
"1000120-13-エイミ" = "うーーーん……。"
"1000120-14" = "[s1] \"……エイミ？\"\n[s2] \"大丈夫？疲れてない……？\""
"1000120-17-エイミ" = "……あ。"
"1000120-18-エイミ" = "ううん、気にしないで。"
"1000120-19-エイミ" = "こういうの、よくあることだから。"
"1000120-25-エイミ" = "ここには異常がないと分かっただけでも、ちゃんとデータが取れてるよ。"
"1000120-26-エイミ" = "それに、こういう長時間の外出も慣れてるし。"
"1000120-27-エイミ" = "私より先生のほうがちょっと心配だけど……。"
"1000120-28-エイミ" = "先生、大丈夫？#nちょっと疲れてるように見える。"
"1000120-29" = "[s3] \"うーん、そうだね……。\"\n[s4] \"疲れというより、暑いかな。\""
"1000120-32-エイミ" = "たしかに、こんな天気だしね。"
"1000120-33-エイミ" = "風もないし、休める日陰もない……。"
"1000120-34-エイミ" = "水はたくさん持ってきたけど、それでも炎天下で疲れやすい状況だから。"
"1000120-35-エイミ" = "私も、暑いのは慣れてるけど……#nもう全身汗だくになってしまった……。"
"1000120-36-エイミ" = "本当は……すぐにでも脱いで涼みたいところだけど……。"
"1000120-40-エイミ" = "……知ってる。脱ごうとしたら先生は止めるよね。#n流石に分かってるよ。"
"1000120-41-エイミ" = "だから、ちゃんと今回は対策してきてるんだよ。"
"1000120-42-エイミ" = "言ったよね、「こういう時のために、準備しておいた」って。"
"1000120-43-エイミ" = "えっと……。"
"1000120-50" = "[ns5] \"小型扇風機？\"\n[ns6] \"意外とかわいい……。\""
"1000120-54-エイミ" = "……外見で判断しちゃダメだよ、先生。"
"1000120-55-エイミ" = "これは、見た目以上にしっかりしてるんだから。"
"1000120-56-エイミ" = "小型で持ち運びやすい上に……ちょっとした改造をお願いしてるから――"
"1000120-57-エイミ" = "スイッチをオンにすると――ほら。"
"1000120-62" = "[ns7] \"なっ、何？すごい風が……！？\"\n[ns8] \"ちょっとしたどころじゃなくない！？\""
"1000120-65-エイミ" = "こういう状況を打開するなら、それなりの出力は必要。"
"1000120-66-エイミ" = "長く風に当たっている余裕がない分、短時間で素早く体温を下げる対策だよ。この出力なら、手早く涼めるでしょ？"
"1000120-67-エイミ" = "さて、と……。"
"1000120-71-エイミ" = "そういう事だから先生、こっちに来て。"
"1000120-75-エイミ" = "高出力とはいえ小型の扇風機だから、風の範囲はそんなに広くないよ。"
"1000120-76-エイミ" = "先生と私の体温を効率的に下げるためにも、今はくっつかないと。"
"1000120-77-エイミ" = "つまり、できる限り体を密着させる必要があるということ。#nわかるよね？"
"1000120-81-エイミ" = "……？#n先生？"
"1000120-82-エイミ" = "そこに突っ立ってても暑いだけでしょ？#n早く来て。"
"1000120-83-エイミ" = "遠慮する……？"
"1000120-84-エイミ" = "あまり体をくっつけるのは良くない？#nどうして？"
"1000120-85-エイミ" = "……理屈がわからないよ先生。#n今私と離れている理由はない。効率を優先しないと。"
"1000120-86-エイミ" = "……うーん。"
"1000120-87-エイミ" = "こっちに来てってば。"
"1000120-92-エイミ" = "……先生。"
"1000120-94" = "（…………）"
"1000120-95" = "（その後、エイミとぴったりくっついて扇風機の風を一緒に浴びながら涼んだ）"
"1000120-96" = "（しかし、エイミの体から放出される熱で扇風機の風も熱風に変わり果ててしまった……）"
