[translation]
"10047070-1" = "第7話;伝説の証明"
"10047070-2" = "（寮に戻って、みんなと頑張って掃除した）"
"10047070-6" = "[ns] \"……これは？\""
"10047070-7" = "（黒い布をかぶせられたキャンバスが、部屋の隅にいくつも積まれていた）"
"10047070-11-カノエ" = "それは……見ない方がいいよぉ。"
"10047070-12-カノエ" = "エリちゃんの……昔の絵だから。"
"10047070-13-カノエ" = "そっとしといてねぇ……。"
"10047070-14" = "[ns] \"ずっと持ってるんだね。\""
"10047070-15-カノエ" = "自分の歩みを……振り返りたいんだって。"
"10047070-16-カノエ" = "未熟な、過去の自分と向き合うのは……つらいはずなのに……。"
"10047070-17-カノエ" = "私たちのなかで一番の……努力家さん。"
"10047070-23" = "[ns] \"……夢を追う少女、か。\""
"10047070-24-エリ" = "マスター？ここで何をされているのですか？"
"10047070-25" = "[s] \"あっ、え、えっと……！\""
"10047070-26-カノエ" = "……前世の話。"
"10047070-27-カノエ" = "先生は……私とのこと、覚えてないんだって……。"
"10047070-28-エリ" = "えっ！まさか、先輩が言ってた前世の絆って……！"
"10047070-30" = "[ns] \"わ、私は何も知らないよ……！\""
"10047070-32" = "（……カノエの機転のおかげで、会話の内容はバレなかった）"
"10047070-37" = "[ns] \"エリの夢、か……。\""
"10047070-38" = "（そんなことを考えつつ、掃除を続けた）"
"10047070-41-エリ" = "にゅふふ。原状回復完了、です！"
"10047070-42-レナ" = "はぁ……次こんなことしたら、タダじゃおかないからね……。"
"10047070-43-エリ" = "おおっ！では、趣向を変えた儀式ならば……。"
"10047070-44-レナ" = "ちょっとは反省してっ！"
"10047070-45-カノエ" = "たしかに、爆発が少し強かったからねぇ……。"
"10047070-46-カノエ" = "やっぱり、安全にやるなら……外かな……。"
"10047070-47-ツムギ" = "ですが、敷地内は寮監隊が目を光らせています。"
"10047070-48-エリ" = "答えが出ない……こんな時こそ……。"
"10047070-49-エリ" = "アルカナの魔法！タロットカードの出番です！"
"10047070-53-レナ" = "……そうくると思った。"
"10047070-54-エリ" = "まず、失敗した原因を分析してみましょうか？"
"10047070-58-エリ" = "マスター。この中から3枚選んで、テーブルに伏せてください。"
"10047070-59" = "[ns] 慎重にカードを選び、テーブルに伏せる。"
"10047070-64-エリ" = "では、見てみますね。"
"10047070-68-エリ" = "ふむ、これは……。"
"10047070-69-エリ" = "……火力不足、でしょうか。"
"10047070-74-カノエ" = "イヒッ……寮ごと、吹き飛ばすべきだったかなぁ……。"
"10047070-75-ツムギ" = "なるほど。悪魔は刺激的な相手にしか会ってくれないのですね。"
"10047070-76-レナ" = "……寮を吹き飛ばしたら、「退学」って悪魔と会えたかもね。"
"10047070-77-エリ" = "うーん、この場合の「火力」は、抽象的な意味のようです。"
"10047070-78-エリ" = "それにこれは……古い歴史という意味もあります。"
"10047070-79-エリ" = "うーーーん……。"
"10047070-83-エリ" = "マスター、すみません。#nもう一枚選んでもらえませんか？"
"10047070-84" = "[ns] 頷いてカードを選ぶ。"
"10047070-92-エリ" = "これは……正位置の魔術師？"
"10047070-93" = "[s1] \"それって……。\"\n[s2] \"良いの？悪いの？\""
"10047070-96-エリ" = "魔術師のカードはいろいろな解釈ができまして……。"
"10047070-97-エリ" = "素晴らしい能力を持ちながら、予測不可能な一面があります。"
"10047070-98-レナ" = "それ、先輩たちと一緒じゃん。"
"10047070-99-エリ" = "私たちと……一緒？"
"10047070-106-エリ" = "それですよ！"
"10047070-107-エリ" = "ありがとうございますレナちゃん！さすがオカ研の一員です！"
"10047070-108-レナ" = "なっ、なに？急に不安になってきたんだけど。"
"10047070-109-エリ" = "これは、古い歴史を参考にし、変革を目指せ――という意味です。#nそれも、魔法関連の！"
"10047070-110-エリ" = "みなさん！#nワイルドハントの魔法にまつわる話を覚えてますか？"
"10047070-111-カノエ" = "もしかして……アレ……？"
"10047070-112-ツムギ" = "なるほど。"
"10047070-113-ツムギ" = "語り継がれる存在を、現代に蘇らせる……それもまた芸術です。"
"10047070-114-レナ" = "何なの！？勝手に盛り上がってないで、教えてよ！"
"10047070-115-エリ" = "巨大魔法陣ですよ！"
"10047070-116-エリ" = "満月の夜！#n学院の重要施設を繋げて巨大な魔法陣を描くと、#nすごいことが起こるという伝説！"
"10047070-117" = "[s] \"結局、それってどんなことが起きるの？\""
"10047070-118-カノエ" = "言い伝えだから……詳しくはわからないけど……。"
"10047070-119-カノエ" = "なんでも、「願い」が叶うらしいよぉ……。"
"10047070-120-エリ" = "にゅふふ、ドキドキしませんか？"
"10047070-121-レナ" = "本気？"
"10047070-122-レナ" = "真夜中に寮を出て、学院全体に絵を描くの……？"
"10047070-123-レナ" = "寮監隊に捕まっちゃったら、どうするつもり！？"
"10047070-124-カノエ" = "イヒッ、レナちゃん……よく聞いてぇ。"
"10047070-129-カノエ" = "バレなきゃ、いいんだよぉ？"
"10047070-130-ツムギ" = "ふふ、芸術は、冒険から生まれるものですから。"
"10047070-131-エリ" = "言い伝え通りなら、私の夢も叶うはず……！"
"10047070-132-エリ" = "……それはそれとして、面白そうですし！"
"10047070-133-レナ" = "シャーッ！そんなことだろうと思った！#n先生も見てないで止めて！"
"10047070-137" = "[ns3] \"エリの夢が叶えられるなら、助けになりたい。\"\n[ns4] \"もちろん、やりすぎない範囲でね。\""
"10047070-140-ツムギ" = "私も賛成です。お互いの夢を応援し合う関係。#nそれが――"
"10047070-145-カノエ" = "――仲間ぁ。"
"10047070-146-エリ" = "……ですから！"
"10047070-147-レナ" = "ううう……！"
"10047070-148-レナ" = "あーもー！勝手にすれば！？#nその代わり、私は絶対助けないからね！"
"10047070-149-エリ" = "大丈夫です！レナちゃんの心配もわかってますから。"
"10047070-150-エリ" = "決して、迷惑をかけないようにします。"
"10047070-151-レナ" = "ふんっ、言うのは簡単だけどさ……。"
"10047070-153-カノエ" = "それじゃ……まずは調査だねぇ……。"
"10047070-154-カノエ" = "この学院に隠れる……巨大な魔法陣の正体を――"
"10047070-155-エリ" = "みんなで芸術情報館に行って、施設を確認しましょう！"
"10047070-159-ツムギ" = "……レナちゃん、ご一緒にどうですか？"
"10047070-160-レナ" = "私は先輩たちがまたやらかさないか、監視するだけ。"
"10047070-161-レナ" = "ほんっと～……に！深い意味はないからね！"
"10047070-162-ツムギ" = "ふふ、わかっていますよ。"
"10047070-164" = "ワイルドハントの芸術情報館"
"10047070-189" = "（調査は思ったよりも難航し……）"
"10047070-194" = "（思うような成果は得られなかった）"
"10047070-195" = "（どの施設を繋いでも、#nへんてこな魔法陣が現れるだけだった……）"
"10047070-204" = "（さらに調査が続き……）"
"10047070-209-エリ" = "……ようやく、見つけました。"
"10047070-210-エリ" = "これが！学院に隠された、巨大な魔法陣の正体……です！"
"10047070-217-レナ" = "ほ、本物……？昔の地図にそれっぽく描いたんじゃないの？"
"10047070-218-エリ" = "にゅふふっ、本物です。"
"10047070-219-エリ" = "今の学院基準で考えていたのが間違いだったんです。"
"10047070-220-エリ" = "設立初期にあった建物を繋いでみると……#n完璧な対称の魔法陣になりました。"
"10047070-221-エリ" = "それも、数字を利用した……いわば「魔方陣」です！"
"10047070-222-エリ" = "こちらの、線で結んだ各施設。#nその住所に着目して、末尾の数字を足すと……。"
"10047070-223-エリ" = "見てください！合計が26になる線が6本できました！"
"10047070-224-エリ" = "これは100％意図された構造！#n学院の創立に、オカルトの影響があったのは本当でした！"
"10047070-225-レナ" = "うそでしょ……。"
"10047070-226-ツムギ" = "まるで、誰かに見つけてもらうのを待っていたかのような……。"
"10047070-227-ツムギ" = "疑う余地のない、本物の魔法陣ですね……#n完成したら、一体なにが起きるのでしょう。"
"10047070-231-カノエ" = "……でも、一つ、問題があるよぉ。"
"10047070-236-カノエ" = "これは現在の学院の地図……昔とは全然違う。"
"10047070-237-カノエ" = "取り壊された建物はもちろん……新しく建てられた建物も……。"
"10047070-238-カノエ" = "問題はここ……魔法陣の線の上にできた建物。"
"10047070-242-エリ" = "はっ！まさかこれは……！？"
"10047070-243-ツムギ" = "あら。"
"10047070-244-カノエ" = "そう……この地図通りに、魔法陣を完成させるには……。"
"10047070-246" = "[log=카노에]寮監隊の宿舎を通らないといけないんだぁ。[/log]"
