[translation]
"31070-1" = "第7話;試験勉強"
"31070-2" = "（放課後の自習時間）"
"31070-3-アズサ" = "ハナコ、この問題はどう解けば良い？"
"31070-4-ハナコ" = "どれですか？ああ、なるほど。こういう時はですね、倍数判定法を用いてこのように……。"
"31070-5-アズサ" = "なるほど……うん、理解した。"
"31070-6-ヒフミ" = "……。"
"31070-9-コハル" = "……？"
"31070-10-ハナコ" = "えっと、コハルちゃん？何か分からない問題でもありましたか？"
"31070-11-コハル" = "いっ、いやっ！別に！？"
"31070-12-ハナコ" = "ちなみに今見てるそのページは、今回のテスト範囲ではありませんよ。"
"31070-13-コハル" = "えっ、うそっ！？"
"31070-14-コハル" = "やっ、ちが……っ！し、知ってるし！今回の範囲は余裕だから、先のところを予習してただけ！"
"31070-15-ヒフミ" = "あ、あはは……。"
"31070-18-アズサ" = "ハナコ、この文章は何？"
"31070-19-ハナコ" = "古い叙事詩の冒頭部分ですね。「怒りを歌え、神性よ――」という……"
"31070-20-アズサ" = "ああ、あれか。理解した。"
"31070-25-ヒフミ" = "……。"
"31070-28-アズサ" = "ハナコ、これは……。"
"31070-29-ハナコ" = "これは古代語を重訳したものですね。原文を理解するには辞書が無いと……ちょっと待っていてくださいね。"
"31070-30-アズサ" = "ああ、なるほど。なら、これはおそらく「Gaudium et Spes」……喜びと希望、か。"
"31070-31-ハナコ" = "えっと……はい、そうみたいですね。これは第二回公会議における……いえそれよりも、アズサちゃんは古代語が読めるんですね？"
"31070-32-アズサ" = "ああ、昔習った。"
"31070-37-ヒフミ" = "……。"
"31070-39" = "[ns] \"良い感じみたいだね。\""
"31070-40-ヒフミ" = "はい！ハナコちゃんが何だかとってもすごくって……！それにアズサちゃんも学習意欲たっぷりです！"
"31070-41-ヒフミ" = "コハルちゃんは実力を隠していたそうですし……。"
"31070-42-ヒフミ" = "これならもしかして、余裕で合格できてしまうかもしれません……！"
"31070-43-ヒフミ" = "本当に良かった……実はすっごく心配してたんです……。"
"31070-44-ヒフミ" = "実は、「もし1次試験で不合格者が出てしまったら、合宿をしてください」とティーパーティーから言われてまして……。"
"31070-45" = "[s] \"合宿？\""
"31070-46-ヒフミ" = "はい、そうなんです……それに、もし3次試験まで全て落ちてしまったら……あうう……。"
"31070-47" = "[s] \"何か、マズいことに……？\""
"31070-48-ヒフミ" = "な、なんでもありません……！心配は杞憂で終わりそうですし、暗い話はこの辺りにして……。"
"31070-49-ヒフミ" = "とにかく、試験は問題無さそうです！"
"31070-53-ヒフミ" = "ハナコちゃんはどうやらすごく勉強ができる感じなのですが、どうして落第してしまったんでしょう……？私みたいにテストを受けられなくてとか、何か事情があったんでしょうか……？"
"31070-55" = "第1次特別学力試験、当日"
"31070-58-コハル" = "……っ。"
"31070-59-ヒフミ" = "うぅ……。"
"31070-63-ハナコ" = "ふふっ。"
"31070-64-アズサ" = "……。"
"31070-67" = "[ns] \"みんな、落ち着いて頑張ってね。\""
"31070-68-コハル" = "え、エリートの力を見せてやるんだから！"
"31070-69-ヒフミ" = "あ、あはは……頑張ります。"
"31070-70-ハナコ" = "ふふっ、はい。"
"31070-71-アズサ" = "準備は完璧。"
"31070-76" = "次回;第1次特別学力試験"
