[translation]
"10051110-1" = "エピローグ;元の場所へ"
"10051110-2" = "（翌日……）"
"10051110-4" = "シャインキャットのオフィス"
"10051110-5-シャインキャット" = "昨日はありがとう。"
"10051110-6-シャインキャット" = "ショーは台無しになったけど……君のせいじゃないことは理解してるよ。"
"10051110-7-シャインキャット" = "むしろ、君たちとシャーレの先生のおかげで、被害を最小限に抑えられた。"
"10051110-8-シャインキャット" = "……で、そんなことはいいんだ。#n君、忍術研究部に戻りたいんだって？"
"10051110-9-ツクヨ" = "……はい。"
"10051110-10-シャインキャット" = "ふむ。"
"10051110-11-シャインキャット" = "そう。それならそれでいいよ。#n自分の道は、自分で決めるべきだ。"
"10051110-12-シャインキャット" = "……私もそうだったから。"
"10051110-16-シャインキャット" = "話が長くなったね。#nさて、業務の後片づけだけは、付き合ってもらおうか。"
"10051110-17-シャインキャット" = "君が破った私のドレス、どうするつもりかな？"
"10051110-18-ツクヨ" = "そ、それは……！"
"10051110-19-シャインキャット" = "ぷっ、あははっ！冗談さ。"
"10051110-20-シャインキャット" = "はい、これ。"
"10051110-21-ツクヨ" = "箱……？"
"10051110-25-ツクヨ" = "こ、これは……！"
"10051110-26-シャインキャット" = "そう。あのドレス、昨夜徹夜して修繕しておいたんだ。"
"10051110-28-シャインキャット" = "私からのプレゼントだよ。"
"10051110-29-ツクヨ" = "……！"
"10051110-30-シャインキャット" = "勘違いしないでほしい。#n新年早々、ゲストを手ぶらで帰らせるのは、私の流儀に反するってだけだ。"
"10051110-31-シャインキャット" = "今年は良い1年になるといいな。"
"10051110-32-ツクヨ" = "そ、そんな……！"
"10051110-33-シャインキャット" = "もう行きなさい。私は忙しいんだ。"
"10051110-38-ツクヨ" = "……ありがとうございました！#n明けまして、おめでとうございます！"
"10051110-40" = "シャインキャットのオフィス前"
"10051110-42-ミチル" = "ツクヨ……遅いな……。"
"10051110-43" = "[s] \"入ってまだ5分も経ってないけど……。\""
"10051110-44-ミチル" = "そ、そうだっけ……？"
"10051110-48-イズナ" = "あっ！ツクヨ殿が出てきました！"
"10051110-49-ミチル" = "ツクヨ！"
"10051110-54-ツクヨ" = "ぶ、部長！イズナちゃん！それに……先生！？"
"10051110-55" = "[s] \"ちゃんと、決心できた？\""
"10051110-56-ツクヨ" = "はい！私、やっぱり――"
"10051110-57-ツクヨ" = "――忍術研究部が好きです！"
"10051110-58-ミチル" = "いええええええええい！！！"
"10051110-59-イズナ" = "ツクヨ殿！お帰りなさい！"
"10051110-60-ツクヨ" = "あの、でも……なんでカメラが……？"
"10051110-61" = "[s] \"仲間が帰ってきたんだから、みんなに知らせなきゃ！\""
"10051110-62-ツクヨ" = "えっ！？"
"10051110-63-ミチル" = "今回はカメラのセッティングも完璧だから！"
"10051110-64-イズナ" = "撮影が終わったら、みんなでラーメンを食べに行きましょう！ニンニン！"
"10051110-65-ツクヨ" = "ラーメン……！"
"10051110-70-ミチル" = "さぁ、それじゃあ「少女忍法帖ミチルっち」――！"
"10051110-78-一同" = "始まります！"
"10051110-82" = "不忍ノ道～ファッションショー警護任務！の巻～"
