[translation]
"10051005-1" = "プロローグ;ラーメンと陰謀"
"10051005-3" = "[log]忍者たる者、忘るべからず。[/log]"
"10051005-6" = "[log]麺は極太！[/log]"
"10051005-8" = "[log]背脂追加！[/log]"
"10051005-12" = "[log]仕上げにラー油を一回し！[/log]"
"10051005-15" = "百鬼夜行某所のラーメン屋"
"10051005-16-ミチル" = "これぞ忍者流！ラーメンを嗜む新作法！"
"10051005-17-ツクヨ" = "し、「新・忍者定食」です！"
"10051005-18-イズナ" = "みなさん、お待たせしました！ニンニン！"
"10051005-19-イズナ" = "「少女忍法帖ミチルっち」！忍者とラーメン編！"
"10051005-20-一同" = "始まります！！！"
"10051005-21-ミチル" = "……あっ、ちょっと待った！"
"10051005-22-ミチル" = "カメラ、なんか傾いてない？"
"10051005-23-ミチル" = "三脚のせいかな……？"
"10051005-24-ツクヨ" = "えっ！？ご、ごめんなさい……。#n私がもっと、気をつけておけば……。"
"10051005-25-ミチル" = "いやいや、セッティングしたのは私なんだから。"
"10051005-26-イズナ" = "心配ご無用！もう一度撮り直せば大丈夫です！"
"10051005-27-イズナ" = "それでは気を取り直して――"
"10051005-29" = "ガシャーン！"
"10051005-32-ラーメン同好会のメンバーA" = "店長！このスープどうなってんの！？#nゆるすぎて麺に絡まないだろ！"
"10051005-33-ラーメン同好会のメンバーB" = "麺の茹で加減も足りないな！"
"10051005-34-ラーメン同好会のメンバーA" = "麺とスープの一体感が失われてるじゃんか！"
"10051005-35-店長" = "いや、ウチのラーメンはもう何年もこのレシピで……。"
"10051005-36-店長" = "ってそれより！#n味が気に入らないからって、テーブルをひっくり返されては困ります！"
"10051005-37-店長" = "他のお客様にもご迷惑ですから！"
"10051005-42-イズナ" = "らっ……ラーメンが直撃して、カメラが……！"
"10051005-43-ツクヨ" = "うっ……うぅっ……。"
"10051005-44-ミチル" = "終わった……！"
"10051005-45-ツクヨ" = "ぶ、部長……これからどうすれば……。"
"10051005-46-ミチル" = "……。"
"10051005-50-ミチル" = "（ああ、もうっ！！あの厄介客め……！このまま引き下がるわけには――）"
"10051005-51-ミチル" = "（でも……私、あいつらに勝てるのかな？）"
"10051005-55-ミチル" = "（いや、私は1人じゃない……）"
"10051005-56-ミチル" = "（ツクヨとイズナがいる……！）"
"10051005-57-ミチル" = "……忍者たる者、いかなる窮地にあっても――"
"10051005-58-ミチル" = "不義に背を向けることはない……！"
"10051005-59-ラーメン同好会のメンバーA" = "お？なんだぁ？"
"10051005-60-ツクヨ" = "部長……？"
"10051005-64-ミチル" = "くらえ！忍法・キラキラファイアーの術！"
"10051005-72-ラーメン同好会のメンバーA" = "ぐあああっ……あ？何とも……ない？"
"10051005-73-ラーメン同好会のメンバーB" = "……花火？"
"10051005-74-ラーメン同好会のメンバーA" = "なんか……ピカピカするだけで痛くもかゆくもないし？"
"10051005-75-ラーメン同好会のメンバーB" = "なんにせよ、ケンカを売ってきたってことだよな……！"
"10051005-76-ラーメン同好会のメンバーA" = "てか、忍法って何なんだ？"
"10051005-77-ラーメン同好会のメンバーB" = "それはわから――"
"10051005-85-ツクヨ" = "後ろに下がっていて……ください！"
"10051005-86-店長" = "あ、ありがとうございます！"
"10051005-95-ラーメン同好会のメンバーA" = "ぐぅっ……！"
"10051005-96-ラーメン同好会のメンバーB" = "注意を逸らしておいて、後ろから不意打ちとは卑怯な……。"
"10051005-101-ミチル" = "ふっふっふ、相手の注意を引いて、背後を取る。これこそが――"
"10051005-102-ミチル" = "『忍法・キラキラファイアーの術！』の真の使い方！"
"10051005-103-イズナ" = "さすが部長！#n「忍者三人寄れば虎をも制す」戦略とはこれなのですね！"
"10051005-104-ミチル" = "もっちろん！"
"10051005-105-ミチル" = "……あれ、そうだっけ？"
"10051005-106-ツクヨ" = "あ、あの……。"
"10051005-107-ミチル" = "ツクヨ？どうしたの？"
"10051005-108-ツクヨ" = "かかったスープは、拭き取ったんですが……。"
"10051005-110-ツクヨ" = "カメラの電源が……入りません……！"
"10051005-111-ミチル" = "……。"
"10051005-112-イズナ" = "……。"
"10051005-114-一同" = "えええぇぇぇっ！？"
"10051005-118-ニヤ" = "ふむ……。"
"10051005-119-ニヤ" = "機敏で無駄のない動き……さらに店主の安全にまで気を使える……。"
"10051005-120-ニヤ" = "にゃはは。これなら、護衛任務も任せられるかもしれませんねぇ……。"
"10051005-121-ニヤ" = "前々から忍術研究部の腕前は存じておりましたが……まだ新たな発見があるとは。"
"10051005-122-ニヤ" = "……これなら。"
"10051005-123-ニヤ" = "「あの任務」に抜擢するのも……悪くないかも？"
