[translation]
"10051045-2-ヘルメット団幹部" = "くっ……悔しい……！"
"10051045-7-ミチル" = "やった……。"
"10051045-8-ミチル" = "ふふふ……見よ、すべての者たちよ……！#n最後まで立っていられるのは――忍者なのだ！！"
"10051045-9-イズナ" = "お疲れさまでした！ニンニン！"
"10051045-10" = "[s] \"怪我はない？\""
"10051045-11-ツクヨ" = "先生のおかげで、みんな無事、です……！"
"10051045-12-ミチル" = "まぁ、あっちは無事じゃなさそうだけど……。"
"10051045-13-ミチル" = "それにしても、こんなに大勢で衣装を盗みに来るなんて、すごい執念だよね……。"
"10051045-14-イズナ" = "部長！まずは衣装を回収しましょう！"
"10051045-15-ミチル" = "あっ、そうだった！そのために探してたんだもんね。"
"10051045-17-ツクヨ" = "ふ、服は、あのバッグの中、だと思います……。#n最後まで、大切そうに抱えてた、ので……。"
"10051045-18-ミチル" = "えーっと……おっ！カバンは無事みたいだね。"
"10051045-19-ミチル" = "これで目的の物は確保完りょ――"
"10051045-20-ミチル" = "……あれ？#n地面に倒れてるこの人……誰？"
"10051045-24-正体不明の生徒" = "……。"
"10051045-25-ツクヨ" = "せ、戦闘が始まったときには、いなかったような……？"
"10051045-26-イズナ" = "イズナも心当たりはありません！"
"10051045-27-ミチル" = "なんだろ、戦闘に巻き込まれた一般人かな？"
"10051045-28-ミチル" = "とりあえず手当てを――"
"10051045-33-シャインキャット" = "ちょっと、私の作品は見つかったの？"
"10051045-34-ミチル" = "あ、うん。ちゃんと取り返したよ。"
"10051045-35-シャインキャット" = "よくやってくれた。これで一件落着だね。"
"10051045-36-シャインキャット" = "カバンの中身は……うん？#nちょっと待って……そこに倒れてるのって……。"
"10051045-40-シャインキャット" = "そ、そんな……!"
"10051045-41-シャインキャット" = "そんなあああぁぁぁ――――！！！"
