[translation]
"10018030-1" = "第3話;これで勝ったと思うなよ！"
"10018030-2-グルメヘルメット団C" = "はぁ、はぁ……！お前ら、いったい何なんだよ！"
"10018030-3-ハルナ" = "それについては、私がお答えいたしましょう。"
"10018030-4-ハルナ" = "我々は美食の極意を求めて旅する孤独な巡礼者。EAT or DIE。"
"10018030-6-ハルナ" = "おいしいものを食べるためであれば、どんな苦難も乗り越えてみせる――それが私たち、ゲヘナの美食研究会ですわ。"
"10018030-12-グルメヘルメット団C" = "美食研究会だって！？嘘だろ！？"
"10018030-13-グルメヘルメット団D" = "食べ物のためなら火の海にだって飛び込むとかいう、ヤバい連中じゃん！？"
"10018030-15-ハルナ" = "！？"
"10018030-17-グルメヘルメット団C" = "いや、違うって。"
"10018030-18-グルメヘルメット団C" = "火の海だって食べ尽くすって話だよ！"
"10018030-25-グルメヘルメット団D" = "それならブラックホールの胃袋を持つって話も納得だな……。"
"10018030-27-アカリ" = "！？"
"10018030-29-グルメヘルメット団C" = "食べ過ぎの呪いで、肝心な時に食べられないみたいな話も聞いたような。"
"10018030-35-グルメヘルメット団D" = "というか、"
"10018030-36-グルメヘルメット団D" = "どうしてそんなテロリスト集団の美食研究会がスズメ亭なんかにいるんだ？"
"10018030-37-ジュンコ" = "何よ、テロリストだなんて！失礼しちゃう！"
"10018030-38-ジュンコ" = "私たちはただグルメ巡りをしているだけなんだから！#n途中でたまに問題が起こるだけよ！"
"10018030-39-グルメヘルメット団D" = "美食研究会には良心の欠片もないって噂はどうやら本当のようだな。#n恐ろしい連中め……。"
"10018030-40-グルメヘルメット団C" = "とにかく！お前たちがあたしらの邪魔をする権利はないからな！"
"10018030-41-グルメヘルメット団D" = "そうだ、そうだ！もう女将は契約書にサインしてるんだからな！"
"10018030-42-グルメヘルメット団C" = "あたしらは約束の期日が近づいてる事を伝えに来ただけなんだけど？"
"10018030-43-グルメヘルメット団D" = "一体、どこが問題だって言うんだ？"
"10018030-44-グルメヘルメット団C" = "だよね？あたしたちは親切心で、確認に来てあげたんだから！"
"10018030-46-ハルナ" = "面白いことを仰いますね。"
"10018030-47-ハルナ" = "何故、親切だと自負しているのにヘルメットで顔を隠し、店主を脅しているのでしょう？"
"10018030-48-グルメヘルメット団D" = "な、何か文句でもあるのかよ！"
"10018030-49-ハルナ" = "それに――なぜ、スズメ亭とニャオフードのトラブルに、グルメヘルメット団が介入してくるのですか？"
"10018030-50-ハルナ" = "ニャオフードとグルメヘルメット団の間に、何らかの関係があるのでしょうか？"
"10018030-54-グルメヘルメット団D" = "えっ……もしかしてあたしら、やらかした？"
"10018030-55-グルメヘルメット団C" = "や、やっちまった……まずい、これが上層部に知られたらあたしらは……！"
"10018030-56-グルメヘルメット団D" = "いや、まだ大丈夫だ。目撃者がいなけりゃ何も問題ない。"
"10018030-57-グルメヘルメット団C" = "そうか！誰も見てなかったことにすればいいのか！"
"10018030-58-ハルナ" = "いよいよ現実を受け入れることさえできなくなったようですわね。"
"10018030-59-ハルナ" = "先ほどから私たちに指一本触れられなかったというのに……一体、何を言っているのでしょう？"
"10018030-60-グルメヘルメット団C" = "へっへっへ。急に態度変えたのには、それ相応の理由があるってことだ！"
"10018030-61-ハルナ" = "理由……？"
"10018030-62-グルメヘルメット団D" = "そうだ！お前たち、今度こそ無事でいられると思うなよ！"
"10018030-71-グルメヘルメット団A" = "急にどうしたんだ？緊急の呼び出しなんて驚いたぞ。"
"10018030-72-グルメヘルメット団B" = "呼ばれたから来たけど……早く片付けて帰ろうよ。"
"10018030-74-ハルナ" = "なるほど、"
"10018030-75-ハルナ" = "増員ですか……。"
"10018030-77-グルメヘルメット団C" = "ようやく自分の立場を理解したのか？"
"10018030-78-グルメヘルメット団C" = "でも遅かったな！#nグルメヘルメット団に歯向かったらどうなるのか思い知るといい！"
"10018030-80-ハルナ" = "いいえ――"
"10018030-81-ハルナ" = "理解したのは、あなた方も美食を汚すような方々と一緒だということですわ！"
