[translation]
"10020035-19-ホシノ" = "ぐっ……！！"
"10020035-20-ホシノ" = "と、止まって！……君は、一体誰？"
"10020035-21-アヤネ" = "また、逃げてしまいました……。"
"10020035-26-セリカ" = "ほ、ホシノ先輩……今のって……。 "
"10020035-27-ノノミ" = "私たちの知るシロコちゃんじゃないとは、一体どういう意味ですか……？"
"10020035-29-ホシノ" = "……。"
"10020035-30-ホシノ" = "シロコちゃんは……あんな目をしない。"
"10020035-31-ホシノ" = "アレは……"
"10020035-40-ユウカ" = "待たせたわね！ヒマリ先輩のおかげで、第4エリアの通信網をハッキングできたわよ！"
"10020035-41-アヤネ" = "第4エリアは、たしか……。"
"10020035-42-ユウカ" = "「[ruby=彼女]シロコ[/ruby]」の信号を捉えた位置よ。#n画面を映すから待ってちょうだい。"
"10020035-52-アヤネ" = "こ、ここは……。"
"10020035-62-アヤネ" = "し、シロコ先輩！？"
"10020035-63-ノノミ" = "シロコちゃん……？"
"10020035-64-シロコ" = "ん。やっと見つけてくれた。#n先生、みんな……待ってた。"
"10020035-65" = "[ns] \"シロコ、大丈夫！？怪我はない！？\""
"10020035-68-シロコ" = "ん、大丈夫。#n自転車に乗って学校に向かってたら、拉致されただけ。"
"10020035-69-シロコ" = "人質になるのはセリカみたいな子だと思ってたから、油断してた。ごめん。 "
"10020035-70-セリカ" = "な、なっ！？ちょっとシロコ先輩？どういう意味！？"
"10020035-71-シロコ" = "でも、助けに来てくれるって分かってたから……大丈夫。#nちょっと体の節々が痛いだけ。"
"10020035-72-シロコ" = "それに……危害を加えてこないから、身代金目的みたい。"
"10020035-73-ホシノ" = "いやぁ、それにしてもシロコちゃん。人質なのにその格好はどうしたのさ？"
"10020035-74-シロコ" = "ん、これは……いつもバッグに入れてるから。#nチャンスは、準備された者に訪れるもの。"
"10020035-75-シロコ" = "少し前から、ここが襲撃を受けてるみたいだったから……#n脱出する時、隙を見て高そうな物を――"
"10020035-80-セリカ" = "こんな状況なのに……そんな計画を……"
"10020035-81-シロコ" = "う……んん……。 "
"10020035-82-ホシノ" = "うへ～……シロコちゃんは本当に、ピンチからチャンスを生み出す天才だねぇ。 "
"10020035-83-ホシノ" = "……でもさ、シロコちゃん。#nおじさん言ったでしょ。"
"10020035-94-シロコ" = "ん……。 "
"10020035-95-シロコ" = "「こんな方法に慣れちゃうと……ゆくゆくは、きっと平気で同じことをするようになる」……"
"10020035-96-シロコ" = "「そうやって学校を守ったって、何の意味があるのさ」って……言ってた。 "
"10020035-98-アヤネ" = "……。"
"10020035-99-ノノミ" = "……シロコちゃん。"
"10020035-100-セリカ" = "シロコ先輩……本当に、シロコ先輩だ……"
"10020035-101-ホシノ" = "うへ～、よく覚えてるね。 "
"10020035-102-ホシノ" = "そこでじっとしてるんだよ？#nすぐ助けに行くから。"
"10020035-103-シロコ" = "ん。"
"10020035-104-ホシノ" = "積もる話は後で、ね。#nシロコちゃんが居ない間、本当いろんなことがあったんだよ？ほんっと、涙なしでは聞けないような話がいっぱいあるからさ……"
"10020035-105-シロコ" = "ん、待ってる。 "
"10020035-106-シロコ" = "ホシノ先輩、みんな、先生……#n助けに来てくれるって、知ってた。"
"10020035-107" = "[s] \"…………うん、当たり前だよ。\""
"10020035-108-シロコ" = "それじゃ――ここで――――ってるから―― "
"10020035-112-ホシノ" = "……。"
"10020035-113-ノノミ" = "シロコちゃん……。"
"10020035-114-ホシノ" = "……それじゃ、ちゃちゃっと次のエリアに行こっか。"
"10020035-115-ホシノ" = "――シロコちゃんがいる、第4エリアに。"
"10020035-116-アヤネ" = "はい！まだ、何が何だか分かりませんが…… "
"10020035-117-ノノミ" = "ですが、状況を理解するよりも、シロコちゃんを助ける方が先決です！"
"10020035-119-セリカ" = "待ってて、シロコ先輩……すぐに行くから！！"
"10020035-121-リン" = "残るはあと1つ――箱舟の最終エリア、中心部の第4エリアです。"
"10020035-122-アユム" = "あとは、ここを占領すれば……箱舟の管制システムを掌握できます。"
"10020035-123-モモカ" = "これで「アトラ・ハシースの箱舟」もおしまいってわけ！#nとっとと自爆シーケンスを稼働させちゃお！"
"10020035-128-ヒマリ" = "本物のシロコさんがいる場所は、第4エリアの閉鎖されたセクションです。"
"10020035-129-ヒマリ" = "ですが、ここへ通じるゲートを開くには、箱舟の上層階に存在する「特別エリア」――その中にある制御室を破壊しなくてはなりません。"
"10020035-130-アヤネ" = "「特別エリア」……。"
"10020035-131-ヒマリ" = "はい。特別エリアは、物理的に箱舟と離れているため、ハッキングの影響を受けないのです。"
"10020035-132-ノノミ" = "つまり……誰かが「特別エリア」の制御室を破壊しなければ、シロコちゃんのいる部屋に辿り着けないのですね。"
"10020035-133-ヒマリ" = "ええ。破壊に成功すれば、シロコさんのいる第4エリアが開放されるでしょう。"
"10020035-137-ホシノ" = "……ま、それならやっぱり私たちの出番かな。"
"10020035-138-ホシノ" = "先生はその間に「次元エンジン」を破壊して、第4エリアの占領をお願いね。"
"10020035-139-ホシノ" = "シロコちゃんがちゃんと脱出できるよう、周りを綺麗にしておかないと。"
"10020035-140" = "[s] \"了解。みんな気を付けてね。\""
"10020035-142-ノノミ" = "はい、任せてください！"
"10020035-143-セリカ" = "「次元エンジン」は頼んだわよ！"
"10020035-144-ホシノ" = "んじゃ、私たちは「特別エリア」に行ってくるね。#nまた後で～"
"10020035-148-リン" = "さあ――「アトラ・ハシースの箱舟」占領戦、最後の戦いです。 "
"10020035-149-アユム" = "これが……本当に最後の戦いになるんですね。"
"10020035-150-モモカ" = "それなんだけどさぁ……敵さんもこれが「最後」だって分かってるみたいだよ？"
"10020035-151-アユム" = "……？"
"10020035-156-モモカ" = "うわぁ……ものすごい数の敵がこっちに向かってきてる。 "
"10020035-157-アユム" = "はっ、はい！？ "
"10020035-159-リン" = "……もう一度、船の防衛が必要そうですね。"
"10020035-163-ハルナ" = "ふふっ。心配はご無用です。"
"10020035-165-ハルナ" = "ここの防衛は、私たちが担当いたします。"
"10020035-166-ジュンコ" = "ここまで来ちゃったんだし、しょうがないわね。"
"10020035-167-アカリ" = "ええ、派手にいきましょうか★"
"10020035-168-イズミ" = "ところで、宇宙食はいつになったら食べれるの～？"
"10020035-170-ユズ" = "こっちは、わたし達がなんとか守ります……！"
"10020035-171-アリス" = "はい。ここはアリスたちに任せてください、先生。 "
"10020035-172-ミドリ" = "アリスちゃん……体は大丈夫？"
"10020035-174-アリス" = "はい。まだHP全快とまではいきませんが、みんなと一緒なら戦えます！"
"10020035-175-モモイ" = "でも無理はしないでね、アリス！ "
"10020035-177-アリス" = "はい！"
"10020035-179-リン" = "先生……では、最後の占領戦もよろしくお願いします。"
