[translation]
"70015020-1" = "イブキ家出事件（２）"
"70015020-4-アコ" = "……。"
"70015020-8-アコ" = "つまり……。"
"70015020-9-アコ" = "そちらのタヌキがイブキちゃんのプリンを食べたせいで……。"
"70015020-10-イロハ" = "はい……。"
"70015020-11-アコ" = "イブキちゃんは出ていってしまい……。"
"70015020-12-アコ" = "挙句所在がつかめなくなり、私たちに助けを求めにきた……ということですね？"
"70015020-13-イロハ" = "情けないお話ですが、その通りです……。"
"70015020-14-イオリ" = "どうしてそうなったんだ……。"
"70015020-15-アコ" = "あれだけ風紀委員会を目の敵にしておいて、こんな時だけ助けて欲しいって……。#nいくらなんでも、都合が良すぎるとは思わないんですか？"
"70015020-16-イロハ" = "弁解の余地もありません……。"
"70015020-17-ヒナ" = "……分かった。私たちも手伝うわ。"
"70015020-21-ヒナ" = "イブキはまだ小さい……道に迷っているのなら、きっと不安になってるわ。"
"70015020-22-イロハ" = "風紀委員長……。"
"70015020-23-アコ" = "……委員長のおっしゃる通りです。イブキちゃんのために、今回は協力しましょう。"
"70015020-24-イオリ" = "これからパトロールだから、私も探してみるよ。"
"70015020-25-イロハ" = "ありがとうございます……。"
"70015020-26-アコ" = "一応確認ですが……。#nこれ、風紀委員会を牛耳るための手の込んだ作戦とかじゃないですよね？"
"70015020-27-イロハ" = "そんなことを考える余裕はないかと……。"
"70015020-29-マコト" = "イブキィー！私が悪かった！！帰ってきてくれー！！！"
"70015020-31-アコ" = "……。"
"70015020-32-アコ" = "はあ……。"
"70015020-33-アコ" = "かれこれ数時間は探していますが……。#nイブキちゃん本人はおろか、手がかりすら見つかりませんね……。"
"70015020-34-アコ" = "一体どこに行ってしまったんでしょうか……。"
"70015020-38-アコ" = "あれは……。"
"70015020-40-イブキ" = "わ～！すごい、すごい！たか～い！"
"70015020-46-イブキ" = "ハルカおねえちゃん、シーソー上手だね！"
"70015020-47-ハルカ" = "えへへ……楽しんでくれて何よりです……。"
"70015020-48-ハルカ" = "次は、ブランコに乗ってみましょうか？"
"70015020-49-イブキ" = "うん！イブキ、ブランコ大好き！"
"70015020-50-ムツキ" = "くふふっ。イブキちゃんとハルカちゃん、すっかり仲良しだね～"
"70015020-51-カヨコ" = "うん。ハルカは面倒見いいからね。"
"70015020-52-アル" = "……。"
"70015020-53-ムツキ" = "どうかした～？アルちゃん。"
"70015020-54-アル" = "いえ……このままでいいのかなと思って……。"
"70015020-55-ムツキ" = "たしかに、イブキちゃんは万魔殿の子だもんね。#nあいつらが乗り込んできたらどうしようって、ビビっちゃってるんだ？"
"70015020-56-アル" = "べ、別にビビってなんかいないわよ！"
"70015020-57-アル" = "私たちは不認可の部活だし、もし会ったらバツが悪いと思ったの！"
"70015020-58-アル" = "ただそれだけ！"
"70015020-59-カヨコ" = "……実際、今頃向こうもイブキのこと探してるだろうね。"
"70015020-60-ムツキ" = "私たちはイブキちゃんを保護してるようなものじゃん！心配し過ぎだって。"
"70015020-61-アル" = "そ、そうよね？"
"70015020-62-ムツキ" = "お菓子もいっぱいあげてるし、むしろ感謝されてもいいくらいじゃない？"
"70015020-63-アル" = "え、ええ！そうよ！"
"70015020-64-カヨコ" = "大丈夫。私たちがイブキを誘拐したとは思われないよ……多分。"
"70015020-65-アル" = "……！！"
"70015020-66-アル" = "ゆ、ゆゆ、誘拐って！そんな物騒なこと……！"
"70015020-67-アル" = "でも私たちはハードボイルドでアウトローな便利屋68……。#nそう判断されたとしても不思議じゃないわ……！！"
"70015020-68-カヨコ" = "いや、落ち着いて社長。仮にそうなっても、イブキがちゃんと説明してくれるよ。"
"70015020-69-アル" = "え、ええ……そうね。"
"70015020-70-アル" = "ふぅ……。もちろん、そんなことは分かっているわ。"
"70015020-71-ムツキ" = "くふふっ。やっぱアルちゃんって面白ーい。"
"70015020-72-カヨコ" = "問題は、イブキをいつ帰すかだけど……。"
"70015020-73-カヨコ" = "向こうが先にこっちを見つけるってパターンも……。"
"70015020-78-アコ" = "……。"
"70015020-79-カヨコ" = "……あ。"
"70015020-80-アコ" = "……どういう状況か、説明してくれますか？"
"70015020-82-イブキ" = "――ってことがあったんだよ！"
"70015020-83-アコ" = "……なるほど。イブキちゃんは……。#nこの人たちに遊んでもらって、お菓子も買ってもらったと。つまりこれは――"
"70015020-84-アコ" = "誘拐です！"
"70015020-85-アル" = "やっぱり！？"
"70015020-86-イブキ" = "ううん、違うよ。イブキが勝手に出ていったの。"
"70015020-87-イブキ" = "このおねえちゃんたちは、イブキと遊んでくれてただけ。とってもいい人たちだよ！"
"70015020-88-アコ" = "……それなら良いんですが……。"
"70015020-89-ハルカ" = "い、イブキ。迎えが来たので、もう帰らないとですね……。"
"70015020-90-ハルカ" = "一緒に遊べて楽しかったです。向こうでも元気でいてください……。"
"70015020-91-アコ" = "……そうですね。帰りましょう、イブキちゃん。今万魔殿は――"
"70015020-92-イブキ" = "やだ！まだ帰りたくない！"
"70015020-96-アコ" = "ど、どうしてですか？まだ怒ってます？"
"70015020-97-イブキ" = "……ううん。もうおこってないけど……。"
"70015020-98-イブキ" = "まだ帰りたくないんだもん。"
"70015020-99-イブキ" = "イブキ、おねえちゃんたちともっといたい！"
"70015020-103-ハルカ" = "えへへ……そ、そうですか。私も、イブキともっと一緒にいたいです。"
"70015020-104-イブキ" = "うん！そうする！！"
"70015020-110-ハルカ" = "あ、アル様……。"
"70015020-111-アル" = "うーん……。"
"70015020-112-アコ" = "はあ……。"
"70015020-114-アル" = "それなら……私たちの事務所に、来る？"
