[translation]
"104040-1" = "第4話;抵抗（３）"
"104040-2-チヒロ" = "まずい、「抑制」時間の減少がまた加速してる……！"
"104040-3-コタマ" = "先程よりも速いです……！"
"104040-4-マキ" = "4分58秒……4分11秒……3分19秒……！#nちょ、ちょっと速すぎない！？"
"104040-9-チヒロ" = "残り、60秒――！！"
"104040-10-ヒマリ" = "加速している、ということは……"
"104040-11-リオ" = "……トキ！！"
"104040-14-トキ" = "はぁ……はぁ……"
"104040-15-トキ" = "くっ……！"
"104040-24-トキ" = "はぁ、はぁ……。"
"104040-29-リオ" = "「箱舟」との連結さえ解除できれば、抑制状態を維持できる……#n早くしないと……トキが……！！"
"104040-30-フウカ" = "到着したわよ！#n今、「セキュリティシステム」の前！！"
"104040-31-アコ" = "美食研究会……お願いします！！"
"104040-32-ハルナ" = "さあ皆さん、セキュリティシステムの「解除装置」を破壊してくださいな！"
"104040-33-アヤネ" = "ホシノ先輩、今です！！"
"104040-34-ユウカ" = "ゲーム開発部、今よ……！"
"104040-37-ホシノ" = "了解～、待ってました！"
"104040-38-ノノミ" = "はい！東側の解除装置、破壊完了です☆"
"104040-41-アリス" = "光よ――――！"
"104040-46-ユズ" = "に、西側の解除装置も、破壊完了です……！"
"104040-51-ハルナ" = "うふふっ、セキュリティシステムが開きました。"
"104040-52-イズミ" = "わわっ、アレを壊せばいいんだよね？"
"104040-53-ジュンコ" = "急ぐわよ！！これ、5秒で閉まっちゃうんだからね！？"
"104040-54-ハルナ" = "では、フィナーレをお願いします、アカリさん。"
"104040-55-アカリ" = "ふふっ。ついにドッカ～ン★をする時間ですね。"
"104040-56-チヒロ" = "急いで……！#n時間がもう――"
"104040-57-コタマ" = "「多次元解釈」の抑制終了まで残り、9秒……！"
"104040-58-マキ" = "うう……。"
"104040-59-ハレ" = "早く……！"
"104040-63-アカリ" = "装填完了、 照準合わせます……！"
"104040-64-アカリ" = "スペシャルな一発、行きます！"
"104040-65-コタマ" = "……残り7秒！"
"104040-73-ジュンコ" = "きた！端末、破壊！！"
"104040-74-アカリ" = "熱いうちに召し上がれ～"
"104040-75-イズミ" = "うああ、熱すぎるよ～！？"
"104040-76-ユウカ" = "連結を解除して！！"
"104040-77-コタマ" = "……1秒！！"
"104040-78-チヒロ" = "連結、解除！！"
"104040-85-カヨコ" = "連結解除、承認！！"
"104040-86-リオ" = "……！#n「抑制」が安定化したわ！！"
"104040-90-シロコ" = "……。"
"104040-98-アユム" = "……どう、なったのでしょうか？"
"104040-99-モモカ" = "い、イケた？"
"104040-100-リン" = "……はい。成功しました。"
"104040-101-ユウカ" = "やったわ！！連結解除、完了よ！！！"
"104040-102-アコ" = "ふぅ……。"
"104040-103-アヤネ" = "はぁ……。"
"104040-104-モモカ" = "ひゃー……10年くらい、寿命縮んだ……。"
"104040-110" = "次回;安易な解"
