[translation]
"104100-1" = "第10話;エピローグ（２）"
"104100-3-ヒフミ" = "みなさん、ファイトです……！"
"104100-4-コハル" = "うう……ぜ、全然わかんない……"
"104100-5-ハナコ" = "ふふっ。みなさん今回の活躍もありましたし、試験勉強はできませんでしたからね。"
"104100-6-アズサ" = "ああ。知っている問題が一つも無い。だが、たとえ虚しいことであっても――"
"104100-7-コハル" = "いや、抵抗したって意味ないからっ！？#nこれ記述式だからね！？"
"104100-8-アズサ" = "……うん。"
"104100-9-ハナコ" = "うふふ♡そうですね。#n「補習授業部」は、まだまだ続きそうですね。"
"104100-10-ヒフミ" = "あ、あうう……。"
"104100-12-アツコ" = "それじゃ、気をつけていってらっしゃい。サッちゃん。"
"104100-13-サオリ" = "だ、だが……。"
"104100-14-ミサキ" = "そりゃそうでしょ。「自分探し」にリタイアなんてあり得ないから。"
"104100-15-ヒヨリ" = "へへっ……そうですね。途中で諦めるものじゃ、ないです。"
"104100-16-サオリ" = "……。"
"104100-17-アツコ" = "大丈夫……サッちゃんにはまだやりたいことも、見たいものも、たくさんあるでしょ。"
"104100-21-アツコ" = "私たちはもう、あの時みたいな子どもじゃないから……大丈夫だよ。"
"104100-22-サオリ" = "……分かった。"
"104100-28-サオリ" = "……雇い主か？……ああ、私だ。"
"104100-29-悪徳業者" = "おい、ヘルメット団！！早く集合しろ！！"
"104100-30-悪徳業者" = "アイツ……アイツらを懲らしめに行くぞ！！#n今回欠勤した分、きっちり56時間無給で働いてもらうからな！！"
"104100-31-サオリ" = "なっ……！"
"104100-32-悪徳業者" = "便利屋のヤツらが今ここ――ぐ、ぐはぁあっ！？"
"104100-33-悪徳業者" = "なっ、何だアレは！？は、早くこっちに来い！#nアイツらを追い出せば最低時給くらいは考慮してやる！！"
"104100-34-悪徳業者" = "今後も仕事が欲しけりゃ急ぐんだな！！ぐはっ！？"
"104100-35-サオリ" = "……了解。今向かう。"
"104100-39-サオリ" = "みんな……それじゃ。"
"104100-40-ミサキ" = "……なんだかんだ忙しそうだね、よかった。"
"104100-41-ヒヨリ" = "た、たまには連絡してくださいね、リーダー……。"
"104100-42-アツコ" = "いってらっしゃい、サッちゃん。"
"104100-43-サオリ" = "……うん。"
"104100-45-アツコ" = "……。"
"104100-49-ミサキ" = "……身体には気をつけてね、リーダー。"
"104100-51-ホシノ" = "うへ～、セリカちゃん、おかわりおねがーい。"
"104100-52-セリカ" = "えっ、また！？"
"104100-53-ノノミ" = "うんうん！それに、頑張ったシロコちゃんには、たくさん栄養を摂ってもらわないと！"
"104100-54-シロコ" = "もう、お腹いっぱい……。"
"104100-56-ホシノ" = "い～や！シロコちゃんはもっと食べれるでしょ。#n大変な思いをしたばっかりなんだから、食べれる時にたくさん食べないと。"
"104100-57-アヤネ" = "あ、あはは……。"
"104100-58-セリカ" = "何でもいいけど、ラーメン代はちゃんと払えるのよね！？#nあっ、ノノミ先輩のカードは無しだからね！"
"104100-59-ホシノ" = "……セリカちゃんの時給から天引きとか、どう？"
"104100-60-セリカ" = "なっ何言ってるの！？バカ言わないでよ！！"
"104100-61-ホシノ" = "マスター、もう一杯よろしく～。"
"104100-66-柴大将" = "はぁ……今回は店からの奢りだ。みんなお疲れさん。"
"104100-67-柴大将" = "それじゃ、お嬢ちゃんたちに、#nジャンボラーメンもう一丁！"
"104100-68-セリカ" = "たっ、大将！？それじゃ赤字になっちゃうでしょ！？"
"104100-69-ホシノ" = "いやぁさすが大将。太っ腹だねぇ～。"
"104100-70-ノノミ" = "わあ～いただきます☆#nもちろんお代は出させてもらいますね！"
"104100-72-柴大将" = "まぁまぁ気にすんな。こんな時くらい、ちゃんと食べておかないとな！"
"104100-76-アヤネ" = "あはは……それでは、ありがたくいただきます。"
"104100-77-シロコ" = "ん……。"
"104100-78-ホシノ" = "セリカちゃんもこっち座って一緒食べようよ～#nセリカちゃんがいないなんて、おじさん寂しくなっちゃうな～。"
"104100-79-セリカ" = "変なこと言わないでよ！？私まだバイト中なんだけど！？"
"104100-80-柴大将" = "大丈夫だよ、セリカちゃん。今日はどのみち暇だからさ。"
"104100-81-セリカ" = "……そ、そう？じゃあ、まあ……たまには……"
"104100-82-ノノミ" = "はい、セリカちゃん。こっちにどうぞ☆"
"104100-83-シロコ" = "ん、私の横も空いてる。"
"104100-87-ホシノ" = "うへ～……セリカちゃん、どっち座る？シロコちゃんの隣？#nそれともノノミちゃんの隣？"
"104100-88-ホシノ" = "これ……実は超重要かもよ？慎重にねぇ～"
"104100-93-ホシノ" = "おじさんの膝の上、は予想外だったな～"
"104100-94-セリカ" = "うるさいわね！今回はホシノ先輩もちゃんと反省しなさいよ！"
"104100-95-ホシノ" = "ひどいなぁ～おじさんの腰のことも考えてくれないと……"
"104100-96-アヤネ" = "あはは……じゃ、じゃあ私もホシノ先輩の隣に……。"
"104100-97-ノノミ" = "わぁ☆じゃあ私はホシノ先輩の前にくっついちゃいます☆"
"104100-98-シロコ" = "ん、私は後ろ。"
"104100-99-ホシノ" = "前後左右……だ、誰かたすけて。おじさん、女子高生に囲まれちゃった……"
"104100-100-ホシノ" = "このままじゃ、おじさん……うへぇ～～～"
"104100-103-アロナ" = "よし、到着しましたね！プラナちゃん。"
"104100-104-アロナ" = "ここがこれからプラナちゃんが過ごす、おうちです！"
"104100-105-プラナ" = "えっと……はい。"
"104100-106-プラナ" = "では……よろしくお願いします、アロナ先輩。"
"104100-107-アロナ" = "違いますプラナちゃん！ここは、あの台詞ですよ！"
"104100-108-プラナ" = "……あの台詞。"
"104100-109-アロナ" = "はい！！あの台詞の出番です！プラナちゃんもよく知ってるはずですよ！"
"104100-110-プラナ" = "……やらなければ、なりませんか？"
"104100-111-アロナ" = "（じーーーっ）"
"104100-112-プラナ" = "……分かりました。"
"104100-118-アロナ" = "おかえりなさい、プラナちゃん。"
"104100-123-プラナ" = "……ただいま、アロナ先輩。"
"104100-128-アユム" = "お疲れ様でした……リン先輩。"
"104100-129-リン" = "お疲れ様でした、調停室長。"
"104100-130-アユム" = "はい……ええっと、その……"
"104100-131-リン" = "……大丈夫ですよ、アユム。私の再信任投票が終わるまでは、静かに過ごすのが得策かと。アユムにまた迷惑をかけるわけにはいきませんから。"
"104100-132-アユム" = "また、だなんて、そんな……。"
"104100-134-モモカ" = "そうだよリン先輩。私たち、宇宙まで一緒に行ってきた仲じゃん？"
"104100-135-リン" = "……モモカ。"
"104100-136-モモカ" = "まあ……今回もバックレよっかなって思ったけど……#nここまで来たからには、リン先輩の面倒を見ないとな～って。"
"104100-137-アユム" = "ふふっ……はい、私もです。"
"104100-138-リン" = "……アユム、モモカ。#nそういえば、あなた達に伝えていないことがありました。"
"104100-143-リン" = "……私と、一緒にいてくれて、ありがとう。"
"104100-144-アユム" = "……！！"
"104100-145-モモカ" = "う、うわあ……！？リン先輩が頭を下げる日がくるなんて……"
"104100-146-モモカ" = "これは何かが起きる予兆だよ……きっと明日は槍が降るんだ……"
"104100-147-アユム" = "も、モモカちゃん……。"
"104100-149-リン" = "……そして、これからもお世話になります。#n何卒よろしくお願いしますね。"
"104100-150-アユム" = "……はい！こちらこそ、よろしくお願いいたします。"
"104100-151-モモカ" = "はいはい。まあ仕方ないよね……よろしく～"
"104100-153-アユム" = "あ……そういえば。#n先輩宛てに手紙が届いていました。"
"104100-154-リン" = "……手紙、ですか？"
"104100-155-アユム" = "はい。机の上に置いておいたのですが……"
"104100-156-アユム" = "差出人は書かれていませんでした……念のため軽くチェックしましたが、#n普通の手紙のようです。あっ、内容は見ていません！"
"104100-157-リン" = "……分かりました、確認します。"
"104100-159-ニヤ" = "にゃは～。先生、お久しぶりです。"
"104100-160" = "[s] \"ニヤ！\""
"104100-161-ニヤ" = "いやぁ、涙なしには見られない大活躍っぷりでした。#n本当にもう、胸がいっぱいで！"
"104100-162" = "[s] \"ありがとうニヤ。ニヤもお疲れさま。\""
"104100-163-ニヤ" = "それで、なんですが……先生。"
"104100-164-ニヤ" = "その……私にとってかなり面白――いえ、重要なお話なのですが……"
"104100-165" = "[s] \"ん？どうしたの？\""
"104100-166-ニヤ" = "……裸で野原を駆け回った、というのは事実なのですか？"
"104100-170" = "[ns1] \"……………………。\"\n[ns2] \"違う、本当に、誤解だから。\""
"104100-173-ニヤ" = "……あれ～？おっかしいですねぇ。正確には……裸で埃まみれ、片手にはタブレット、そして、とびっきりの笑顔を浮かべて生徒の元に駆け寄った――という目撃情報が……"
"104100-174" = "[s] \"………………。\""
"104100-175-ニヤ" = "コホン……まぁ、先生の立場もありますし？これ以上追及はしないでおきますね。"
"104100-176" = "[s] \"……それを聞くために連絡したの？\""
"104100-177-ニヤ" = "いえ。実は忍術研究部から連絡がありまして。"
"104100-178-ニヤ" = "ああ、ちなみにあの子たちは無事帰還しています。"
"104100-179-ニヤ" = "まず、百花繚乱の副委員長と会えたことは確認できました。#nですが、クズノハの実在までは確認できませんでしたが……"
"104100-180-ニヤ" = "自称クズノハからの手紙を預かっております。"
"104100-181-ニヤ" = "それも――「シャーレの先生」宛てのものを。#nまあ、それが真実かはさておき。"
"104100-182-ニヤ" = "内容は分かりませんが、取り急ぎデータを送りますね。"
"104100-183" = "[s] \"ありがとう、ニヤ。\""
"104100-184-ニヤ" = "にゃはは。力になれたらいいのですが～"
"104100-185-ニヤ" = "今度、百鬼夜行自治区にも一度いらしてください。#n近々面白い祭りが開かれますので。"
"104100-191" = "[ns] （ニヤから貰った手紙を読み上げる）"
"104100-194-クズノハ" = "ふむ、[USERNAME]先生が妾を探していると小耳に挟んでな。#n……いや、探す[ruby=・]予[/ruby][ruby=・]定[/ruby]と云うべきか。"
"104100-195-クズノハ" = "兎も角、結論を先に伝えるべきじゃな――"
"104100-196-クズノハ" = "「色彩」によって反転した者を元に戻す方法など、存在せぬ。"
"104100-197-クズノハ" = "其れは――死者が生き返らないのと同様に。#nこの世界の絶対的なルールである。"
"104100-198-クズノハ" = "だがそれでも……助けたい者が居ると申すのなら、"
"104100-203-クズノハ" = "――妾を訪ねてくりゃれ。"
"104100-208-リン" = "……こちら、ですか。"
"104100-210-リン" = "差出人は書かれてない……。"
"104100-211-リン" = "内容は――"
"104100-215" = "「リンちゃんへ」"
"104100-216-リン" = "これは……"
"104100-217-リン" = "この、筆跡……"
"104100-218-リン" = "……。"
"104100-222-リン" = "連邦生徒会長……？"
