[translation]
"63070-1" = "第7話;試み"
"63070-2-スバル" = "……。"
"63070-3-スバル" = "慣れませんね……。"
"63070-7-セリナ" = "こんにちは、スバルさん！午後の検診に来ました。"
"63070-11-セリナ" = "ごめんなさい、午前中は授業があってどうしても……。"
"63070-12-スバル" = "授業、ですか。"
"63070-13-スバル" = "それが、[ruby=・]普[/ruby][ruby=・]通[/ruby]なんでしょうね。"
"63070-14-セリナ" = "……。"
"63070-18-セリナ" = "救護騎士団の病室は、ご不便ないですか？"
"63070-19-スバル" = "……ええ。こんなに整った設備は見たこともありません。"
"63070-20-スバル" = "おかげで、皆さんの回復も早いようです。"
"63070-21-アリウスの生徒たち" = "体がウズウズしてきたな〜"
"63070-22-アリウスの生徒たち" = "もう退院していいんじゃない……？"
"63070-23-ハナエ" = "ダメですよ！治りかけが危ないんですから！"
"63070-24-ハナエ" = "団長の許可が出るまでは我慢です！"
"63070-25-スバル" = "ああやって言ってくれますし。"
"63070-26-セリナ" = "……。"
"63070-30-セリナ" = "あの、スバルさん？"
"63070-31-スバル" = "はい？"
"63070-32-セリナ" = "私たちのこと……憎んでいたり、しませんか？"
"63070-33-スバル" = "急にどうしたんですか？#nこうして治療をしていただいて、感謝こそすれ……。"
"63070-34-スバル" = "……。"
"63070-35-スバル" = "そういうこと、ですか。"
"63070-36-セリナ" = "はい……。"
"63070-38-スバル" = "（あの日）"
"63070-39-スバル" = "（天使のラッパが止まった、あの日）"
"63070-40-スバル" = "（多くの生徒が、アリウス分校を訪れた）"
"63070-41-スバル" = "（ゲヘナの救急医学部、トリニティの救護騎士団。その他にもたくさん）"
"63070-64-スバル" = "（私たちは、救護騎士団の本館に搬送された）"
"63070-65-スバル" = "（今に至るまで、ここで治療を受けながら回復を待っている）"
"63070-67-スバル" = "……トリニティやゲヘナの助けを受けたという事実に、まだ戸惑っている生徒もいます。"
"63070-68-スバル" = "助けてもらっておいて何を。という話ではあるのですが……。"
"63070-69-スバル" = "もう少しだけ、気持ちを整理する時間をいただけるとありがたいです。#nすみません。"
"63070-73-セリナ" = "いえ！むしろ私たちの方こそ……。"
"63070-74-スバル" = "はい……。"
"63070-75-スバル" = "それはそれとして。"
"63070-76-スバル" = "私たちを看てくださったことについては、感謝しています。"
"63070-80-セリナ" = "いえいえ！とんでもないです！"
"63070-82-ミネ" = "容体の方は？"
"63070-83-スバル" = "私は平気です。ですがミネさんこそ……。"
"63070-84-ミネ" = "ご心配なく。非力ではありますが、これでも救護騎士団の団長ですので。"
"63070-85-スバル" = "……あの日、ミネさんに何があったのですか？"
"63070-86-ミネ" = "はい？"
"63070-87-ミネ" = "ああ、私が倒れた日のことですね。"
"63070-88-ミネ" = "……。"
"63070-89-ミネ" = "私はただ、皆さんを守っただけです。"
"63070-90-ミネ" = "こうして元気にお話しできて、良かった。"
"63070-91-ミネ" = "スバルさんは……どうお考えですか……？#nこれまでと、これからのアリウスのことを……。"
"63070-92-スバル" = "心に何の感情も湧かないかと言えば、嘘になります。"
"63070-93-ミネ" = "……。"
"63070-94-スバル" = "ですが……この気持ちを抱えたままでも、生きていこうと思います。"
"63070-95-スバル" = "この感情が膨れ上がるかもしれないし、少しずつ沈んでいくかもしれない。#nあるいは燃え尽きて、灰だけが残るかもしれない。"
"63070-96-スバル" = "……それでも、生きていかなければならないのですから。"
"63070-97-ミネ" = "……そうですか。その強い覚悟、私も学ばせていただきます。"
"63070-98-ミネ" = "ええ、学び――"
"63070-103-ミネ" = "ここからは試験勉強の時間です！！！"
"63070-104-スバル" = "はい！？"
"63070-105-ミネ" = "気を引き締めてください！試験まで、残された時間はわずかです！"
"63070-106-ミネ" = "心身が落ち着いたのなら、この機会に試験勉強に集中するべきです。#nそれこそが、生徒として正しい在り方ではありませんか！"
"63070-107-ミネ" = "私たち救護騎士団も、それは変わりません。"
"63070-108-ミネ" = "救護と学業の両立！救護騎士団の在り方を示すのです！"
"63070-109-ミネ" = "そうですよね、皆さん！"
"63070-110-救護騎士団員" = "はい、団長！"
"63070-111-ミネ" = "ふふっ、良い返事です。"
"63070-112-ミネ" = "では、スバルさん。そしてアリウスの皆さんも。"
"63070-113-ミネ" = "試験、頑張ってくださいね。"
"63070-117-スバル" = "良い話だったはずが……なぜこんな結論に……。"
"63070-118-アリウスの生徒たち" = "勉強かぁ……。"
"63070-119-アリウスの生徒たち" = "やっぱりやりたくないなぁ……。"
"63070-120-スバル" = "……正直、私もです。"
"63070-121-マイア" = "私は頑張りたいです！"
"63070-122-スバル" = "やる気があるのは良いことですね……。#n今回は、私がマイアさんから学ぶ番かもしれません……。"
"63070-128-スバル" = "おや？アレは……？"
"63070-137-編入したアリウスの生徒A" = "はい、ここま[ruby=アリウス式近接戦闘射撃術]で。CQBの基[/ruby]礎はこんなところです。"
"63070-138-編入したアリウスの生徒B" = "近接戦闘に持ち込まれないのが一番ですが、現場では何が起きるか分かりませんから。"
"63070-139-トリニティの生徒A" = "す、すごい……。"
"63070-140-トリニティの生徒B" = "かっこいい……！"
"63070-144-編入したアリウスの生徒A" = "えぇ……？こんなに拍手をもらえるなんて……。"
"63070-145-編入したアリウスの生徒B" = "アリウスじゃ、覚えて当然だったのに……。"
"63070-146-トリニティの生徒A" = "あ、あのっ！その……近接？戦闘射撃術？私たちにも教えてもらえませんか？"
"63070-147-編入したアリウスの生徒A" = "えっ？でも皆さんは別に……。"
"63070-148-トリニティの生徒B" = "おっしゃったではありませんか。何があるか分かりませんから！"
"63070-150-トリニティの生徒B" = "私たちにだって、護身術は必須の時代だと思います！"
"63070-152-トリニティの生徒A" = "そう！淑女たるもの――"
"63070-153-トリニティの生徒A" = "自分の身は自分で守って、無礼な相手には礼儀を教えて差し上げませんと！"
"63070-154-トリニティの生徒B" = "はい！その通りです！"
"63070-158-編入したアリウスの生徒A" = "トリニティ、大丈夫なのかな……。"
"63070-159-編入したアリウスの生徒B" = "もしかして、とんでもないものを目覚めさせちゃった……？"
"63070-160-トリニティの生徒A" = "そうです！CQB研究部を創設いたしましょう！"
"63070-161-トリニティの生徒B" = "いいですね！では、部長と副部長は……。"
"63070-162-トリニティの生徒A" = "もちろん、専門家の方々にやってもらうべきですよね！"
"63070-166-トリニティの生徒B" = "異議無しです！よろしくお願いします！"
"63070-171-編入したアリウスの生徒A" = "私たちですか！？でもそんな大役、とても……。"
"63070-172-編入したアリウスの生徒B" = "ひ、ひゃああ……。"
"63070-173-トリニティの生徒A" = "大丈夫ですよ！慣れないことがあったら、何でもお手伝いしますから！"
"63070-174-トリニティの生徒B" = "では皆さん！もう一度拍手をお願いします！"
"63070-178-編入したアリウスの生徒A" = "よ、よろしくお願いします……。"
"63070-179-編入したアリウスの生徒B" = "どうしてこんなことに……。"
"63070-181-マイア" = "あの……先輩？"
"63070-182-スバル" = "はい？どうかしましたか？"
"63070-183-マイア" = "……。"
"63070-184-マイア" = "私たちにも、できるでしょうか……？"
"63070-185-マイア" = "今までとは、色んなことが違うかもしれませんが……。"
"63070-190-マイア" = "新しい巣を、自分たちで作れると思いますか？"
"63070-191-スバル" = "……。"
"63070-192-スバル" = "やってみましょう。"
"63070-194-スバル" = "私は、何がしたかったんでしょうか。"
"63070-195" = "アリウスを、懸命に守ろうとしてたよ。"
"63070-197-スバル" = "こんな結末なら、何もしないほうがよかった……。"
"63070-198" = "そんなことない。"
"63070-199" = "やってみたことに、意味があるんだよ。"
"63070-201" = "たしかに、努力しても変わらないことはある。"
"63070-202" = "失敗するかもしれない。今よりも悪くなるかもしれない。"
"63070-203" = "でも、考えてみて？"
"63070-204" = "今が底辺なら、上がるしかないよね？"
"63070-206-スバル" = "結果が、どうであっても。"
"63070-208" = "次回;ティータイム"
