[translation]
"70009020-1" = "されど寮監隊は走り続ける（２）"
"70009020-3-寮監隊員" = "はぁ……ただいま。"
"70009020-7-寮監隊員" = "つ、疲れた～"
"70009020-8-寮監隊員" = "寮監隊長のおかげでなんとかなったけど……。#nもし間に合わなかったら……うぅ。"
"70009020-13-寮監隊員" = "あ、そうだ。課題も進めないと……。"
"70009020-17-寮監隊員" = "……明日でいいや～"
"70009020-21-寮監隊員" = "ふあぁ……ベッド最高。"
"70009020-25-寮監隊員" = "……最後に絵を描いたの、いつだっけ？"
"70009020-26-寮監隊員" = "やめやめ、早く寝よう。"
"70009020-27-寮監隊員" = "ふぁあ……おやすみなさ～い。"
"70009020-32" = "ババババ～ン！！ババババ～ン！！"
"70009020-33-寮監隊員" = "うわっ！？な、なんだ！？"
"70009020-34-寮監隊員" = "こんな時間に路上ライブをやるような奴らといえば……。"
"70009020-35-怒っている生徒A" = "またかよ！！こっちは寝不足なんだ！！"
"70009020-36-怒っている生徒B" = "誰か！背景音楽部を止めて！！"
"70009020-40-アナウンス" = "総員起床！5分以内に廊下へ整列せよ！#n繰り返す！総員起床！5分以内に廊下へ整列せよ！"
"70009020-41-寮監隊員" = "はあああああ……。"
"70009020-42-寮監隊員" = "……仕方ないな。"
"70009020-49-寮監隊の幹部" = "……およそ7分前、学院のフェンスを越える自由外出部の姿が目撃された。"
"70009020-50-寮監隊員A" = "もう！また自由外出部かよ。"
"70009020-51-寮監隊員B" = "今月でもう4回目……いつ寝てんだよ、あいつら。"
"70009020-55-寮監隊の幹部" = "現時刻をもって、脱走の阻止を最優先任務とする。#nまた、自由外出部の部長は発見次第身柄を確保せよ。以上、質問は？"
"70009020-56-真面目な寮監隊員" = "あの……一ついいですか。"
"70009020-57-真面目な寮監隊員" = "外の背景音楽部は放っておいていいんでしょうか。#n各寮からいっぱい苦情が来てて……。"
"70009020-58-寮監隊の幹部" = "ふむ、背景音楽部はそのままでいい。#nまだ逮捕命令が下りていない。"
"70009020-59-真面目な寮監隊員" = "ですが、生徒の安眠が……。"
"70009020-60-寮監隊の幹部" = "仮にだ。オーケストラの奏者が指揮を無視し、#n勝手に音を奏でだしたらどうなる？"
"70009020-61-真面目な寮監隊員" = "え？#n……[ruby=めちゃくちゃ]不協和音[/ruby]になりますね。"
"70009020-62-寮監隊の幹部" = "その通り。寮監隊長が逮捕命令を出していないのなら、我々が動く必要はない。#n大事なのは、「背景音楽部は今回の対象ではない」ということだけだ。"
"70009020-63-寮監隊の幹部" = "命令は頭で理解せず……心で感じるんだ！"
"70009020-64-真面目な寮監隊員" = "な、なるほど……！"
"70009020-66-寮監隊員" = "（……早く終わらないかなあ）"
"70009020-72-寮監隊の幹部" = "では、総員出動せよ！全速前進！"
"70009020-74" = "ワイルドハント学院のフェンス近所"
"70009020-76-寮監隊員" = "はぁ、はぁ……。"
"70009020-77-寮監隊員" = "なんでこんな夜中に……でも、あとちょっとだ……。"
"70009020-86-寮監隊の幹部" = "はい！？い、いえ、承知しました。"
"70009020-91-寮監隊の幹部" = "総員、止まれ！"
"70009020-95-寮監隊員" = "……？"
"70009020-96-寮監隊の幹部" = "これより、背景音楽部の逮捕に向かう！"
"70009020-97-寮監隊員" = "……え？"
"70009020-99-寮監隊員B" = "自由外出部はどうするんです？ここまで来たんですよ……？"
"70009020-100-寮監隊員C" = "っていうか、背景音楽部の逮捕はさっきできましたよね？#n私たちが行進してるとき、応援歌を演奏してたし……。"
"70009020-102-寮監隊の幹部" = "これは寮監隊長の命令だ！#n生徒の安眠のため、背景音楽部の逮捕を最優先とする！"
"70009020-103-寮監隊の幹部" = "……だが、不満を持つのもわかる。"
"70009020-104-寮監隊員" = "……おお？"
"70009020-105-寮監隊の幹部" = "ここまで来て引き返せと言われても、納得できないだろう。"
"70009020-107-寮監隊員" = "（今さら……？）"
"70009020-108-寮監隊員" = "（いやでも……あなたなら、この状況をきっと……！）"
"70009020-110-寮監隊の幹部" = "だが……そこにこそ、寮監隊長の真意が秘められているのだ！"
"70009020-111-寮監隊の幹部" = "総員、引き返すぞ！全速前進！"
"70009020-116-寮監隊員" = "ああ……！"
"70009020-117-寮監隊員" = "もうー！！！"
"70009020-121-寮監隊員" = "なんなんだよ、この学院は～～～！！！"
"70009020-125" = "されど寮監隊は走り続ける"
