[translation]
"2004505-1" = "ガイド残侠伝"
"2004505-2" = "（早速、映画村にやってきた）"
"2004505-3" = "（フィーナを見つけるのはそれほど難しくなかった）"
"2004505-7-フィーナ" = "皆サン、今日のガイドを務めさせていただくフィーナデス。"
"2004505-8-フィーナ" = "今回ご覧いただくのは、傑作映画「任侠ニャンニャン伝」を舞台化した作品デス。"
"2004505-9-フィーナ" = "娯楽作として公開サレながらも、その鋭いテーマと繊細な演出が評価され、数々の賞を受賞した本作は、舞台上でも輝きを放ちマス！"
"2004505-10-フィーナ" = "舞台演出の枠の中で創意工夫を凝ラシ、数々の名シーンを忠実に再現した力作デス！"
"2004505-11-観光客A" = "なるほどなあ。"
"2004505-12-観光客B" = "なんだか期待しちゃう！"
"2004505-13-観光客A" = "すごい本格的な解説だね！"
"2004505-14-フィーナ" = "……百聞は一見に如かずデス！百鬼夜行が誇る「任侠ニャンニャン伝」、ドウゾ心ゆくまでお楽しみクダサイ！"
"2004505-18" = "[ns1] \"フィーナ、本当にカッコいいよ！\"\n[ns2] \"クールに説明するフィーナも素敵だね！\""
"2004505-23-フィーナ" = "あっ！センセイ！"
"2004505-24-フィーナ" = "……エヘへ。お恥ずかしい限りデス。 "
"2004505-25-フィーナ" = "ホントは、任侠物のタイトルを見るだけでフィーナの心が熱くなるんデスガ……！"
"2004505-26-フィーナ" = "お客様をガイドするには、クールさも大事だと学びマシタ！"
"2004505-27-フィーナ" = "だから今日は、徐かなること林の如く、動かざること山の如く――任侠物の二枚目俳優を意識しておりマス！"
"2004505-28" = "[s] \"かっこいい……！\""
"2004505-29-フィーナ" = "エヘヘ……センセイに褒められると、やっぱり嬉しいデス！"
"2004505-30-フィーナ" = "あっ、もうすぐ始まりマス！楽しんでクダサイね！"
"2004505-32" = "（公演が始まり、観客席が静まり返った）"
"2004505-33" = "（厳かな雰囲気の中、物語が幕を開ける……！）"
"2004505-35-観光客A" = "うーん……さっきから何度も出てくる「盃」ってどういう意味なんだろう……。"
"2004505-36-フィーナ" = "「盃」というのはデスネ、任侠の世界で血縁関係を結ぶための大切な儀式デス。#nあの二人は、今まさに義の契りを結ぼうとしてるんデス。"
"2004505-37-観光客A" = "へぇ、ただの宴会とは違うんだね……。"
"2004505-38-観光客A" = "解説ありがとう……！"
"2004505-43-観光客B" = "あの、ガイドさん。ドスってどういう意味ですか？"
"2004505-44-フィーナ" = "それはデスね――"
"2004505-49" = "[ns3] （観劇の邪魔にならないように、的確に説明してる……） \n[ns4] （フィーナ、素敵な仕事ぶりだ！） "
"2004505-53-劇団員B" = "俺ぁ「尻拭いをした」ってのに、なんだこの仕打ちは……！"
"2004505-54-観光客A" = "し、尻拭い……？"
"2004505-55-フィーナ" = "他人の失敗の後始末のことデス！"
"2004505-56-観光客A" = "えっ！？"
"2004505-57-フィーナ" = "ニャン助は代わりに頭を下げ、ケジメをつけたんです……な、なのに……！"
"2004505-58-フィーナ" = "なのに見捨てるだなんて……#n三千世界のドコだろうと、そんな道理は通りマセン！"
"2004505-59-観光客A" = "お、教えてくれてありがとう……？"
"2004505-61" = "（物語はついにクライマックスを迎え――）"
"2004505-63-フィーナ" = "こ……この……。"
"2004505-64-フィーナ" = "裏切りやがったな、このどチンピラが！"
"2004505-65-観光客一同" = "！？"
"2004505-66-フィーナ" = "ニャン助！そこです！やっちまえデス！！"
"2004505-70" = "[ns5] \"ちょっと、フィーナ！？\"\n[ns6] \"こ、声が大きいよ……！\""
"2004505-73-フィーナ" = "仁義を通す者が負けるなんてダメデス！！"
"2004505-77" = "[ns] （まずい……お客さんたち、びっくりしちゃうんじゃ……！？）"
"2004505-78-観光客A" = "……な、何が始まったの？"
"2004505-79-観光客B" = "静かだったのに、クライマックスになった途端……。"
"2004505-80-観光客A" = "こ、これは……そうだ！"
"2004505-81-観光客A" = "巷で流行りの「[ruby=イマーシブシアター] 体験型演劇[/ruby]」だよ……！"
"2004505-85-観光客B" = "ああ！初見の人のために、ガイドさんが率先して……！"
"2004505-86-観光客A" = "一度やってみたいと思ったんだ！"
"2004505-87-観光客B" = "行けーっニャン助！負けるなーっ！"
"2004505-88-観光客A" = "二人は「サケズキ」でしょ！ケジメつけろーっ！"
"2004505-89-フィーナ" = "Yes！ニャン助、いけ！頑張れ！デス！！"
"2004505-96-フィーナ" = "も、も、申し訳ございませんデシター！！"
"2004505-97-フィーナ" = "舞台でも熱い「任侠ニャンニャン伝」を観て、つい……！"
"2004505-98-フィーナ" = "これではガイド失格デス……もう破門デス！"
"2004505-99-フィーナ" = "このオトシマエどうつければ……！エ、エンコ詰めマスカ……！"
"2004505-100" = "[s7] \"フィーナ、少し落ち着いて……。\"\n[s8] \"何か損害がありましたら、責任は私が……。\""
"2004505-103-劇団員A" = "ハッハッハ！俺らもそこそこ舞台に上がってるが、観客席にビビらされたのは初めてだよ、お嬢ちゃん！"
"2004505-104-劇団員A" = "心配すんな、みんな楽しんでたみたいだしよ。"
"2004505-105-フィーナ" = "で、ですがフィーナのせいで、せっかくの舞台が……。"
"2004505-106-劇団員B" = "たしかに、いつもの公演とはちょっと違ったけどな。"
"2004505-107-劇団員B" = "けど、こういうのも悪くないさ。"
"2004505-108-劇団員B" = "若い頃やってた、ヒーローショーを思い出したよ。"
"2004505-109-劇団員B" = "お嬢ちゃんや観客のみんなに、元気を貰った気がするな。"
"2004505-110-劇団員A" = "みんながあそこまで熱くなるなんてな……ありがとう、お嬢ちゃん。"
"2004505-111-フィーナ" = "ううっ……感謝感激雨あられデス……！"
"2004505-116-観光客C" = "あのー……役者さんと写真が撮れるんですか……？"
"2004505-117-観光客C" = "超面白かったから、ぜひ記念写真を撮りたくて！"
"2004505-118-劇団員A" = "おお、大歓迎だ！嬢ちゃんもどうだい？"
"2004505-119-フィーナ" = "……フィーナもデスか！？"
"2004505-123-劇団員B" = "さ、遠慮すんなって！"
"2004505-129" = "（こうして舞台は無事に終わりを迎えた）"
"2004505-130" = "（少し照れくさそうにしながらも、ホッとした表情を浮かべるフィーナを見て、一日が幕を閉じた）"
