[translation]
"1012702-1" = "獄中執筆記"
"1012702-2" = "シャーレ・オフィス"
"1012702-3" = "（翌日）"
"1012702-7" = "[ns] \"どうぞ。\""
"1012702-10-ミヨ" = "お、おはようございます……。"
"1012702-11-ミヨ" = "[ruby=さくらい]桜井[/ruby]ミヨ、#n今日はシャーレの当番を担当いたします。"
"1012702-12" = "[s1] \"いらっしゃい、ミヨ。\"\n[s2] \"シャーレへようこそ！\""
"1012702-15-ミヨ" = "こ、こちらこそ……呼んでくださりありがとうございます、先生。"
"1012702-16-ミヨ" = "貴重な外に出るチャンスをもらえて、嬉しいです……。"
"1012702-17-ミヨ" = "ふぅ……ひさしぶりの外出……自由だ……。"
"1012702-18" = "[s] \"ワイルドハントは外出許可がなかなか下りないんだっけ。\""
"1012702-19-ミヨ" = "ええ。私みたいな文学を専攻する生徒には特に……。"
"1012702-20-ミヨ" = "極端な話、小説は独房でも書けますし。"
"1012702-21-ミヨ" = "実際、獄中で書かれた名作も少なくないですからね。"
"1012702-22-ミヨ" = "……いっそ、私も部のことを自白して投獄されたほうがいいんでしょうか？"
"1012702-23" = "[s3] \"気分転換したいってことだね……。\"\n[s4] \"それなら私に任せて！\""
"1012702-26-ミヨ" = "えっ？"
"1012702-27-ミヨ" = "せ、先生？なにを……！？"
"1012702-31" = "シャーレ・休憩室"
"1012702-32-ミヨ" = "ここは……休憩室？"
"1012702-33-ミヨ" = "えっ……ゆっくり執筆していい、んですか……？"
"1012702-34-ミヨ" = "お、お菓子やジュースも食べ放題！？"
"1012702-35-ミヨ" = "で、でも、当番なのに……#nサボっていいんでしょうか……？"
"1012702-36-ミヨ" = "小説家は書くのが仕事……？"
"1012702-37-ミヨ" = "そ、そうですけど……。"
"1012702-38" = "[s5] \"お菓子はたくさんあるから……。\"\n[s6] \"じっくり執筆に集中して！\""
"1012702-43-ミヨ" = "……ありがとうございます、先生。"
"1012702-45" = "（自分の仕事をするために、休憩室を後にした）"
"1012702-47-ミヨ" = "うーん……。"
"1012702-48-ミヨ" = "ええと……ここは主人公の不治の病の場面だから――"
"1012702-49-ミヨ" = "そうだ、二人の仲を引き裂くために……#n相手の組織に戦車部隊を動員させて……。"
"1012702-50-ミヨ" = "ここのセリフは……っと。"
"1012702-54-ミヨ" = "「ああ！なぜ運命は我らを巡り合わせたのか……！」"
"1012702-55-ミヨ" = "「希望を捨ててはなりません！私たちにはまだ200発の対戦車ロケットが……！」"
"1012702-56-ミヨ" = "ふふっ……これにしよう。"
"1012702-57-ミヨ" = "次のシーンは……。"
"1012702-63-ミヨ" = "……先生、どうしてここに？"
"1012702-64" = "[s] \"えっと……お土産でもらったお菓子を持ってきたんだ……。\""
"1012702-65-ミヨ" = "……聞いてました？"
"1012702-66" = "[s] \"な、なんのことやら……。\""
"1012702-67-ミヨ" = "聞いたんですね？"
"1012702-68" = "[s] \"……ちょっとだけ。\""
"1012702-69-ミヨ" = "どこからですか？"
"1012702-70" = "[s] \"……不治の病のところから？\""
"1012702-71-ミヨ" = "最初からじゃないですか……！"
"1012702-72-ミヨ" = "ふぁぁあああぁ……！"
"1012702-77" = "（ミヨは頬を赤らめ、風のようにシャーレを飛び出していった……）"
