[translation]
"1008506-1" = "デカフェ"
"1008506-2" = "ミレニアム近郊・キャンプ場"
"1008506-5-ハレ" = "あ、先生。こっち。"
"1008506-6-ハレ" = "先に着いてたから、もう椅子とテーブルは組み立ててあるよ。"
"1008506-7" = "[s1] \"遅くなってごめんね、ところでこれ……キャンプ用品？\"\n[s2] \"カフェインの摂取を減らす話だったんじゃ……？\""
"1008506-10-ハレ" = "まあ確かにキャンプセットなんだけど……どこから説明しようかな。"
"1008506-11-ハレ" = "この前、屋外で仕事をしたことがあったでしょ？"
"1008506-12-ハレ" = "結果的には失敗だったけど……"
"1008506-13-ハレ" = "でもあの時、エナドリの摂取量は少なかった。"
"1008506-14-ハレ" = "そもそも持っていった本数が少なかったとはいえ……"
"1008506-15-ハレ" = "つまるところ物理的にカフェインを摂取できない状況なら、自然と我慢できるんじゃないかなって。"
"1008506-16" = "[s3] \"なるほど。でも、あんまり無理はしないでね。\"\n[s4] \"効果があると良いけど……。\""
"1008506-19-ハレ" = "うん、だからこそ先生を呼んだの。"
"1008506-20-ハレ" = "コンビニや冷蔵庫が遠い場所とはいえ、意志の強さには限界があるから……。"
"1008506-26-ハレ" = "私が作業してるところを、先生に見守っててほしいなって。"
"1008506-27" = "[s5] \"そういうことか。\"\n[s6] \"よし、じゃあ一緒に頑張ろう！\""
"1008506-30-ハレ" = "よろしくね、先生。"
"1008506-36" = "（そして1時間後……）"
"1008506-41-ハレ" = "……。"
"1008506-42-ハレ" = "集中できない……。"
"1008506-43-ハレ" = "いつもの簡単な作業なのに、何でか気が散る……。"
"1008506-44-ハレ" = "これは間違いなく、禁断症状……。"
"1008506-45" = "[s] \"早かったね……。\""
"1008506-46-ハレ" = "エナドリが無いって思うと、逆に気になっちゃって……。"
"1008506-47-ハレ" = "でも、作業がノってくれば忘れられるはず。"
"1008506-48-ハレ" = "もう少しの辛抱……。"
"1008506-50" = "（しかし時間が経つにつれて、症状は徐々に酷くなり……）"
"1008506-54" = "（……遂には、心ここにあらずという状態に）"
"1008506-56-ハレ" = "う、うぅぅ……"
"1008506-57-ハレ" = "カフェイン……カフェインが、足りない……"
"1008506-58-ハレ" = "カフェイン以外、何も考えられない……。"
"1008506-59-ハレ" = "カフェイン、じゃなくて先生……"
"1008506-60-ハレ" = "どうしよう……このままじゃ、誰かのコーヒーを無理やり奪いかねない……。"
"1008506-61" = "[s] \"それは困る……。\""
"1008506-63" = "[ns] \"ちょっと待ってて。\""
"1008506-71" = "[ns] ポットで淹れたコーヒーを差し出す。"
"1008506-75-ハレ" = "あ、ありがとう……。"
"1008506-80-ハレ" = "ふぅ、生き返ったぁ……。"
"1008506-81-ハレ" = "疲れた体にカフェインが染み渡る……。"
"1008506-82-ハレ" = "……ごめん、恥ずかしいところを見られちゃったね。"
"1008506-83-ハレ" = "もう少し何とかなると思ったんだけど……。"
"1008506-84-ハレ" = "やっぱりカフェインを断つのは、無理なのかな。"
"1008506-85" = "[s] \"そんなことないよ。\""
"1008506-87" = "[ns] \"それ、「デカフェ」のコーヒーだから。\""
"1008506-91-ハレ" = "えっ……じゃあ、カフェイン入ってないの？"
"1008506-92-ハレ" = "でもさっき、飲んだら頭がスッキリして……。"
"1008506-96-ハレ" = "……気持ちの問題、ってことなのかな。"
"1008506-97-ハレ" = "先生がくれたコーヒーだから……？"
"1008506-98" = "[s] \"口に合わなかった？\""
"1008506-102-ハレ" = "そ、そんなことは……！"
"1008506-103-ハレ" = "むしろ、すごく美味しいから……。"
"1008506-104-ハレ" = "……先生。また私の集中が切れたら、その時は……。"
"1008506-110-ハレ" = "また……先生がコーヒー、淹れてくれる？"
