[translation]
"2300720-1" = "掴みどころのない女の子"
"2300720-2" = "（トリニティでの仕事を終えた帰り道……）"
"2300720-3-？？？" = "……あら。"
"2300720-4-？？？" = "本当、こんなに偶然出会うこともあるのですね。"
"2300720-5" = "[s1] \"この声は……ハナコ？\"\n[s2] 足音がした方に振り向く。"
"2300720-9-ハナコ" = "お仕事が終わった後でしょうか？#nもう少しこちらの用事が長引けば#nお会いできなかったかもしれませんね。"
"2300720-10-ハナコ" = "どんな用事か、ですか？#nいえ、大したことではなく……"
"2300720-16-ハナコ" = "没収されていたこちらの本を取りに行っていただけですよ。"
"2300720-17" = "[s3] \"……そ、それは！！！\"\n[s4] \"まさかその本は……！！\""
"2300720-20-ハナコ" = "ふふっ、どうしてそんな反応を？"
"2300720-21-ハナコ" = "女の子が大切に抱えている本が気になるのですか？#n内容が、でしょうか？それとも何が書かれているのか、ですか？ "
"2300720-22-ハナコ" = "何なら、今ここで読み上げましょうか？"
"2300720-23-ハナコ" = "聞きやすいように「ゆっくりはっきり」、ね……？"
"2300720-24-ハナコ" = "……はい？"
"2300720-25-ハナコ" = "大丈夫？そうですか、残念です。"
"2300720-26" = "[s5] \"ここにいるとわかって来たの？\"\n[s6] \"まさかまた何かを企んで……！？\""
"2300720-29-ハナコ" = "あら……？"
"2300720-30-ハナコ" = "ふふっ、そう解釈されるのですね？"
"2300720-31-ハナコ" = "いつも思っているのですが……#nどうやら先生の反応は、私にとってとても刺激的なようです。"
"2300720-32-ハナコ" = "ですので、つい癖になってしまいそうで……#nいえ、もうなってしまったというか……。"
"2300720-36-ハナコ" = "……ふふっ。"
"2300720-37-ハナコ" = "まあ、今日はこの辺にしておきましょうか。#n機会はこの先いくらでもありますし……。"
"2300720-38-ハナコ" = "先生は時々なら受け入れてくださると仰っていましたが、#nそれは同時に、あまりやり過ぎないようにという意味でもあるでしょうから。"
"2300720-39-ハナコ" = "それは、私も理解しています。"
"2300720-40-ハナコ" = "その代わり……という訳ではないのですが、#n見送りくらいはさせていただければと思いまして……。"
"2300720-41-ハナコ" = "それでしたら、大丈夫ですよね？"
"2300720-42-ハナコ" = "……ふふっ、決まりです。"
"2300720-43-ハナコ" = "では行きましょうか？"
"2300720-48" = "（その後、ハナコと一緒にトリニティ近郊のバス停まで歩いた）"
"2300720-49" = "（色々と話したけれど、ハナコの言葉通り困るような話題はなかった）"
"2300720-51-ハナコ" = "……着きましたね。"
"2300720-52-ハナコ" = "ですが……やはり少し、物足りないような気がします。"
"2300720-53-ハナコ" = "先生は、退屈されていないでしょうか？"
"2300720-54-ハナコ" = "せっかく遠路はるばる来てくださったのですし、#n少しは刺激を期待していらっしゃったのではと思いまして……。"
"2300720-55-ハナコ" = "だとすれば私は、空気を読めずに#nつまらない見送りをしてしまったのではないかと……。"
"2300720-56" = "[s7] \"いやいや、そんなことはないよ。\"\n[s8] \"むしろ今日みたいな感じが丁度いいと思う！\""
"2300720-59-ハナコ" = "ふふふ……そうですか。"
"2300720-60-ハナコ" = "ところで先生……本当に気になりませんか？#n私がずっと持っているこの本のこと。"
"2300720-61-ハナコ" = "先生が何を想像しているのかは#nなんとなく見当がつきますが……。"
"2300720-62-ハナコ" = "もしかすると、実はそのような内容の本ではないかもしれませんよ？"
"2300720-63-ハナコ" = "この手の本は、どれも表紙が似ていますからね。"
"2300720-64-ハナコ" = "日記帳……悩みを綴ったノート……。#nエッセイのようなものかもしれません。"
"2300720-65-ハナコ" = "それよりももっと、私的で率直な内容が#n書かれているかもしれませんよ……？"
"2300720-69" = "[ns9] \"そういう内容なら、なおさら見れないよ。\"\n[ns10] \"秘密のままで大丈夫。\""
"2300720-75-ハナコ" = "……あ。"
"2300720-76-ハナコ" = "……今回は私のミスですね。#n例えが悪かったといいますか。"
"2300720-77-ハナコ" = "あの問いかけであれば、#n先生なら絶対に今のような返事をするとわかっていたはずなのに。"
"2300720-78-ハナコ" = "……ふふっ。"
"2300720-79-ハナコ" = "わかりました。では、ここまでにしましょう。"
"2300720-80-ハナコ" = "あ。ですが今日会ったのは本当に偶然ですよ。#nいたずらではありませんから。"
"2300720-81-ハナコ" = "ですので今日、私は先生に「何もしなかった」ということで。"
"2300720-82-ハナコ" = "……はい。"
"2300720-83-ハナコ" = "「いたずら」をするのはまたの機会に、ですね♡"
"2300720-85" = "（その後、明るい笑顔のハナコに見送られながらバスに乗った）"
