[translation]
"211010-1" = "第1話;ゲヘナは今日も平和なり"
"211010-3" = "[ns] \"今日も今日とて――\""
"211010-4-ゲヘナの生徒A" = "だ～か～ら～さ～！！"
"211010-6" = "ゲヘナ広場"
"211010-11-ゲヘナの生徒B" = "も～、埒が明かない！#nやっぱ解決するならこれでしょ！"
"211010-24" = "[ns] \"――ゲヘナだなぁ。\""
"211010-32-イオリ" = "そこまでだ！"
"211010-36-ゲヘナの生徒B" = "風紀委員会！？"
"211010-37-ゲヘナの生徒A" = "ちょっちょっちょ、待って待って！#nこれには理由があって……！"
"211010-38-イオリ" = "……何だ？"
"211010-39-ゲヘナの生徒A" = "あそこにドラム缶あるでしょ？#nあれ、私の作品[ruby=・]だ[/ruby][ruby=・]っ[/ruby][ruby=・]た[/ruby]の！"
"211010-40-イオリ" = "それで？"
"211010-41-ゲヘナの生徒A" = "私は、最高にイカした「爆炎の塔」を作ろうとしてたわけよ。#nドラム缶を1個ずつ積み上げて、一気に爆発させるの。"
"211010-42-ゲヘナの生徒A" = "なのに、こいつ何したと思う！？#n私より先に撃っちゃったんだよ！？ありえなくない！？"
"211010-43-ゲヘナの生徒B" = "つい撃ちたくなっちゃって……。#nってか、あんな「撃ってください」って標的作るほうが悪いじゃん。"
"211010-44-ゲヘナの生徒A" = "だ、か、ら！私が！撃とうとしてたの！#nなんで私の楽しみ奪うのさ！"
"211010-48-イオリ" = "そもそも、広場にドラム缶を積むのも、爆破するのも禁止だ。#n公共の場で騒ぎ起こすのは控えろと言ってるだろ！"
"211010-53-ゲヘナの生徒A" = "ちぇっ、厳しすぎなんだよ。"
"211010-54-ゲヘナの生徒B" = "なんか息苦しいっていうか……。"
"211010-55-イオリ" = "暴れなくたって息はできるだろ？"
"211010-56-ゲヘナの生徒A" = "こんな窮屈な空気じゃ窒息するっての！"
"211010-60-イオリ" = "何を言ってるんだ……。"
"211010-67-アコ" = "いったい何の騒ぎですか！"
"211010-68-アコ" = "[ruby=パンデモニウム・ソサエティー]万魔殿の対応だ[/ruby]けでも面倒なのに、揉め事を起こさないでください。"
"211010-69-イオリ" = "また何か言われたの？"
"211010-70-チナツ" = "風紀委員会の装備を明日までに全数調査することになりました。#n過剰戦力だから、9mm弾を超える威力の弾薬は返納しろ、と。"
"211010-71-アコ" = "今に始まったことではないですが……まったく、話になりません。"
"211010-72-イオリ" = "呆れた……。"
"211010-77-ゲヘナの生徒A" = "気になってたんだけどさ。"
"211010-81-ゲヘナの生徒A" = "なんで万魔殿の言いなりなの？"
"211010-82-アコ" = "言いなり！？なんてことを言うんですか！！"
"211010-83-ゲヘナの生徒A" = "やろうと思えば、風紀委員長がどうとでもできるでしょ？#nなのに、どうして従ってるのかな、って。"
"211010-84-アコ" = "はぁ……。"
"211010-88-アコ" = "力で覆して、どうするんですか？"
"211010-92-ゲヘナの生徒A" = "え？"
"211010-93-アコ" = "倒して、[ruby=・]そ[/ruby][ruby=・]の[/ruby][ruby=・]後[/ruby]は？"
"211010-94-ゲヘナの生徒A" = "その後って……。"
"211010-95-ゲヘナの生徒B" = "勝ったら勝ちでしょ？#n好き放題できるってことじゃないの？"
"211010-96-ゲヘナの生徒A" = "そうそう！めっちゃ最高じゃん？"
"211010-100-アコ" = "では……力に任せて、何でも好き放題にして良いと？"
"211010-101-アコ" = "ゲヘナを風紀委員会の思うままにしたら、皆さんにも影響が及ぶかもしれませんよ？"
"211010-102-ゲヘナの生徒A" = "ど、どういうこと？"
"211010-103-アコ" = "例えば……委員長が「制服の着崩し禁止」と仰ったら？"
"211010-104-アコ" = "ネクタイをきちんと締めて、シャツは全部入れて、上着を必ず羽織らなければならなくなります。"
"211010-105-アコ" = "これも、力ある者が好き放題した結果です。それでも素晴らしいと思えますか？#nもちろん、委員長はそんな方ではありませんけど。"
"211010-106-ゲヘナの生徒A" = "あんま良くないかも……。"
"211010-107-ゲヘナの生徒B" = "それは嫌だなぁ……。"
"211010-108-チナツ" = "力があっても、勝手はしない。"
"211010-109-チナツ" = "力があっても、守るべき一線を守る。"
"211010-110-チナツ" = "――力があるからこそ、守るべき一線を守る。"
"211010-111-チナツ" = "それが風紀委員会の方針です。"
"211010-112-？？？" = "チナツの言う通り。"
"211010-119-イオリ" = "委員長……！"
"211010-120-チナツ" = "すみません……出過ぎた真似を……。"
"211010-121-ヒナ" = "なぜ？私とアコがいつも言っていることじゃない。"
"211010-122-ヒナ" = "覚えていてくれて嬉しいわ。"
"211010-123-チナツ" = "委員長……。"
"211010-124-チナツ" = "ありがとうございます。"
"211010-125-ヒナ" = "とにかく。"
"211010-126-ヒナ" = "力があるからって好き放題するのは許さない。"
"211010-127-ヒナ" = "でも、過剰に規制するつもりもない。"
"211010-128-ヒナ" = "自由な――"
"211010-129-ヒナ" = "これからも自由であるはずのゲヘナが、一線を越えないように見守ること。#nそれが風紀委員会の役割。"
"211010-133-ヒナ" = "……私の約束でもあるから。"
"211010-138-ゲヘナの生徒A" = "わ、分かった……。"
"211010-139-ゲヘナの生徒B" = "カッコいい……私も入ろっかな？"
"211010-140-ゲヘナの生徒A" = "えっ、あんたみたいなサボり魔が？"
"211010-141-ゲヘナの生徒B" = "はぁ！？出来ないって言いたいの！？"
"211010-142-イオリ" = "風紀委員会はいつでも歓迎してる。#n申請書を書いて持ってこい。"
"211010-143-ゲヘナの生徒B" = "えー、やっぱめんどくさいからいいや……。"
"211010-144-イオリ" = "じゃあ最初から言うな！！"
"211010-145-？？？" = "キシシッ、相変わらず滑稽だな。"
"211010-149-アコ" = "あなたは……！"
"211010-156-イロハ" = "はぁ……やっぱり素通りはできないんですね。"
"211010-157-マコト" = "どれほど格好つけようと、お前たちには限界がある。"
"211010-158-マコト" = "すぐ暴力に頼るからな。それでは心まで従わせることはできない。"
"211010-159-マコト" = "このマコト様とは器の広さが違うのだ！"
"211010-160-アコ" = "いつもの言いがかりでしたか……。"
"211010-161-アコ" = "そもそも、あなたに「器」を語る資格はないでしょう？"
"211010-162-アコ" = "今回の命令だってそうです。#nあれこれと理由をつけて、風紀委員会の予算を削減する。#nそのくせ、活動費の決裁は先延ばしじゃないですか！"
"211010-163-マコト" = "そんなことに構っている暇などない！！"
"211010-164-アコ" = "あなた達がやらないで誰がやるんですか！？"
"211010-165-マコト" = "ええい！万魔殿は忙しいんだ！風紀委員会のことなど後回しだ！"
"211010-171-ヒナ" = "……本当にそれが理由なら、見過ごすわけにはいかない。"
"211010-181-ゲヘナの生徒C" = "うわ、ケンカしてら。"
"211010-182-ゲヘナの生徒D" = "いつものことじゃん。"
"211010-190-？？？" = "待った！！"
"211010-194" = "[ns] \"？？？\""
"211010-199" = "次回;ゲヘナ再興委員会"
