[translation]
"10037105-3-カグヤ" = "う、ぐっ……！？"
"10037105-9-チェリノ" = "うむ、ご苦労様だった！トモエ秘書室長、マリナ委員長！"
"10037105-10-トモエ" = "ありがとうございます、書記長。"
"10037105-11-トモエ" = "先生、お怪我はございませんか？"
"10037105-12" = "[s] \"うん。トモエとマリナのおかげで無事だったよ。\""
"10037105-13-マリナ" = "うむ、無事なら構わん。"
"10037105-14-マリナ" = "ふんっ、軟弱なやつらめ……私だったら、もっとうまく――"
"10037105-15-トモエ" = "マリナ委員長。#nトイレ掃除、まだやりたいですか？"
"10037105-19-マリナ" = "い、いいえ！とんでもありません、トモエ秘書室長！"
"10037105-20-トモエ" = "念のため、お聞きしましょうか。#nレッドウィンター連邦学園ではよくある事ですが……それでも予防はできます。#nさて――その方法は何だと思いますか？"
"10037105-21-マリナ" = "チェリノ会長より偉大な者を、全員227号特別クラスへ送り込むことです！"
"10037105-22-トモエ" = "ご名答――では、チェリノ書記長より偉大な生徒とは？"
"10037105-23-マリナ" = "もちろん、誰ひとり存在しませんっ！"
"10037105-24-トモエ" = "はい、よくできました。"
"10037105-31-ミナ" = "玄龍門、集合！"
"10037105-36-玄龍門の構成員A" = "！？"
"10037105-37-玄龍門の構成員B" = "ミナ執行部長……！"
"10037105-43-ミナ" = "京劇部……お前たちが何を企んでいたのかは、今は追及しないでおこう。#nひとまず、この場を整理しなければ……。"
"10037105-44-ミナ" = "さあ！京劇部を連行し、門主様と訪問客を[ruby=りくわかく]六和閣[/ruby]まで案内せよ！"
"10037105-49-玄龍門の構成員A" = "は、はいっ！"
"10037105-50-玄龍門の構成員B" = "かしこまりました！"
"10037105-54-玄龍門の構成員A" = "（でも……今までの門主様の意向は一体……）"
"10037105-55-玄龍門の構成員B" = "（今までは、こんな事、思わなかったのに……）"
"10037105-62-カグヤ" = "（この身が捉えられる程度、[ruby=さまつ]瑣末[/ruby]な事だ）"
"10037105-63-カグヤ" = "（忠義の道に、成功も失敗も無い）"
"10037105-64-カグヤ" = "（門主様……どうか、目をお覚ましください……）"
