[translation]
"10037110-1" = "エピローグ;別れし友を懐かしむ"
"10037110-2-チェリノ" = "もう別れの時間とはな……あっという間だったな。"
"10037110-3-トモエ" = "ふふ、今回の交流会、とても満足だったようですね。チェリノ書記長。"
"10037110-5-キサキ" = "それは良いことじゃ。我ら山海経は……どうだったかの？"
"10037110-9-チェリノ" = "うむ、山海経は――"
"10037110-14-チェリノ" = "大冒険だったな！"
"10037110-15-チェリノ" = "不思議な光景に、初めて食べるもの――パンダに京劇……すべて楽しいものばかりだった！"
"10037110-17-キサキ" = "京劇部の件で、色々と苦労をかけて面目ない。"
"10037110-18-チェリノ" = "キサキ門主よ、何度言ったら分かるのだ？"
"10037110-19-チェリノ" = "謙遜も謝罪も、度が過ぎればかえって逆効果になる。いいな？"
"10037110-20-チェリノ" = "おいら、レッドウィンターの書記長はそんな些細なことなど、気にしないのだ！"
"10037110-21-キサキ" = "……そうか。"
"10037110-23-マリナ" = "はい、門主様。チェリノ会長は寛大なお方ですから！"
"10037110-24-マリナ" = "カグヤと京劇部の者は今頃、2～3週間のトイレ掃除を言い渡されているのでしょう！#nそれで良いではありませんか！"
"10037110-30-キサキ" = "（……つくづく思うのじゃが……山海経の法度と、レッドウィンターの校則には……ずいぶんと相違点があるようじゃ）"
"10037110-31-トモエ" = "とても自然体で行われるキサキ門主の人心掌握術が、印象的でした。"
"10037110-32-トモエ" = "私のプロパガンダにも……失礼、人を説得する方法の参考になりそうです。"
"10037110-33-キサキ" = "……ふ、ふむ。そうかの？"
"10037110-35-チェリノ" = "しかし、顔色が悪いようだなキサキ門主。何かあったのか？"
"10037110-36-キサキ" = "[ruby=わらわ]妾は[/ruby]健康じゃぞ？"
"10037110-37-チェリノ" = "そうか……？"
"10037110-38-キサキ" = "さて……この場を記念し、小さな贈り物を用意した。#nどうか受け取ってはくれぬか？"
"10037110-44-チェリノ" = "これは……パンダ？"
"10037110-45-キサキ" = "3色の玉で作ったパンダの模型じゃ。#nつまらぬものじゃが、山海経を覚えていてほしくてのう。"
"10037110-46-マリナ" = "す、凄いです、門主様！#nパンダの白黒模様がこうも完璧に描かれているとは……！#nあの可愛げな風格まで再現されていて……！"
"10037110-47-マリナ" = "まるで、本物のパンダを見ているような気分です！"
"10037110-48-キサキ" = "ふふ、喜んでもらえて何よりじゃ。"
"10037110-50-チェリノ" = "礼を言う！おいらの執務室に飾っておくとしよう！#nいつか、キサキ門主を我がレッドウィンターに招待したいな！"
"10037110-51-キサキ" = "ああ、その時を期待しておるぞ。チェリノ書記長。"
"10037110-60-キサキ" = "ふぅ……ようやく、帰ってこられたのう。"
"10037110-61-キサキ" = "見送りには香主……広報部長をつけておったし、上手く対応してくれるはずじゃ。"
"10037110-65-キサキ" = "……。"
"10037110-66-キサキ" = "……心配じゃ。"
"10037110-74-キサキ" = "此度の京劇部事件をきっかけに、また新たな「変化」が生じるのではなかろうか。"
"10037110-75-キサキ" = "カグヤが根源ではない。すべて、妾が始めたこと。"
"10037110-78-キサキ" = "いいや……山海経の中で何が起きようと――"
"10037110-79-キサキ" = "花が散ろうと、洪水になろうと、雷が落ちようと――すべては妾の責。"
"10037110-80-キサキ" = "――それが、門主としての責務。"
"10037110-85-キサキ" = "じゃが、今は……"
"10037110-87-キサキ" = "少しだけ、休息がほしい。"
"10037110-95-ミナ" = "……居心地はどうだ、カグヤ部長。"
"10037110-96-カグヤ" = "ああ、おかげさまで大変寛がせてもらってるよ。ミナ執行部長。"
"10037110-97-ミナ" = "心にもないことを……。"
"10037110-98-カグヤ" = "虚勢には目を瞑るのが礼儀というものではないか？"
"10037110-102-ミナ" = "どうだっていいだろう。#n単刀直入に聞こう――何故こんな事を？"
"10037110-103-カグヤ" = "……。"
"10037110-104-カグヤ" = "忠義の為――ただそれだけだ。"
"10037110-105-ミナ" = "レッドウィンターからの訪問客と玄龍門が集まった場で、#nあのような京劇を披露した挙句、#n門主様に危害を加えようとした！それが忠義だと！？"
"10037110-106-ミナ" = "お前が犯した罪は、今すぐ退学処分になってもおかしくないのだぞ！？"
"10037110-107-カグヤ" = "相変わらず愚鈍な忠僕だな、ミナ執行部長。"
"10037110-108-カグヤ" = "門主様が誤った判断を下した時に、諫言をするのが誠の忠義であろう！"
"10037110-109-ミナ" = "……誤った判断とは、レッドウィンターの生徒を招いたことか？"
"10037110-110-ミナ" = "騒動を起こしたのは、お前ら京劇部だというのに？"
"10037110-111-カグヤ" = "門主様の行動は、天の道理に反している。#nそれなのに愚直に従うのは、決して正しい忠義の道ではない。"
"10037110-112-カグヤ" = "ああ、門主はたしかに聡明なお方だ。#n――しかし、恣意的に事を解決しようとする傾向がある。"
"10037110-114-ミナ" = "なんだと！？"
"10037110-115-カグヤ" = "貴殿も知っているはずだ。[ruby=しんたに]申谷[/ruby]カイの処分を。"
"10037110-120-ミナ" = "何を……？"
"10037110-126-カイ" = "ああ、そうだったな。#n錬丹術研究会と山海経の事情は……いや、今の君に聞いたところで、意味はないか。"
"10037110-127-錬丹術研究会員" = "……錬丹術研究会の内部では、すでに捜索が始まっております。"
"10037110-128-錬丹術研究会員" = "私は、身を隠すしかありません。"
"10037110-129-カイ" = "今ここで行方を[ruby=くら]晦[/ruby]ましてしまえば、犯人だと言っているようなものじゃないのかね？"
"10037110-130-錬丹術研究会員" = "致し方ありません。どうせ今の錬丹術研究会に期待することなどありませんので。"
"10037110-131-カイ" = "ククッ……カグヤも、君も本当に……。#nここには一本槍のやつしか居ないようだ。"
"10037110-132-錬丹術研究会員" = "カイ様。あの日、京劇部の部長と何のお話をされていたのか、お聞きしてもよろしいでしょうか。"
"10037110-133-カイ" = "ああ、大したことではないよ。"
"10037110-135-カイ" = "カグヤが錬丹術研究会に私を復帰させてやると言ったくらいさね。"
"10037110-139-錬丹術研究会員" = "……！？"
"10037110-142-ミナ" = "……申谷カイを錬丹術研究会に復帰させるべき、だと？"
"10037110-143-ミナ" = "自分が何を言っているのか分かっているのか！？"
"10037110-145-カグヤ" = "それこそが道理である！"
"10037110-146-カグヤ" = "そもそも、申谷カイを退学させた一件は、あまりにも性急だった！#n何一つ、慣例に従っていなかったというのに！"
"10037110-150-ミナ" = "……！"
"10037110-151-カグヤ" = "適切な手続きを踏まず、即座に退学処分を命じていた。#nさらには、申谷カイに関する記録をすべて抹消し……！"
"10037110-152-ミナ" = "あれは山海経の治安を憂慮しての判断だった！"
"10037110-153-ミナ" = "手続きを踏んでいれば、申谷カイの退学は1年以上遅れていたはずだ！"
"10037110-154-ミナ" = "その間にどれほどの被害者が出たと思う！？"
"10037110-155-カグヤ" = "仮にそうだとしても、全ての物事は手順通りに執り行わなければならない！"
"10037110-156-カグヤ" = "いくら門主様とはいえ、山海経の校則を恣意的に破ってはならないのだ！"
"10037110-157-カグヤ" = "校則が意味を為さなくなれば、門主様本人も、山海経を治める大義名分が無くなってしまうというのに！"
"10037110-160-カイ" = "大した内容ではなかったが、面白い話はできたよ。"
"10037110-161-カイ" = "私を錬丹術研究会に復帰させた後、適切な手続きを踏んで再び退学させ――"
"10037110-162-カイ" = "皆にその記録と事実を公表し、見せしめにすべきだと言っていたからねぇ。"
"10037110-163-錬丹術研究会員" = "……さすがは、京劇部長らしいお考えですね。"
"10037110-164-錬丹術研究会員" = "その提案を……受け入れるおつもりで？"
"10037110-165-カイ" = "さてね。まあでも、私を錬丹術研究会に復帰させるという話には興味をそそられたよ。"
"10037110-166-カイ" = "カグヤに新しい京劇のネタをあげた程度にはね。"
"10037110-170-ミナ" = "そんな理由で、申谷カイを復帰させ、再び退学させろ……だと？"
"10037110-174-ミナ" = "馬鹿か！そんな事できると思っているのか！？#nそもそも、申谷カイが大人しく帰ってくるとでも！？"
"10037110-175-カグヤ" = "申谷カイもまた、山海経の生徒だ。断る理由など無い！#nいいや、そうしなければならない！"
"10037110-176-ミナ" = "自分勝手も大概にしろ！"
"10037110-178-カグヤ" = "仮に申谷カイが復帰を拒むのであれば、無理やりにでも復帰させてみせる！"
"10037110-179-カグヤ" = "玄龍門の門主に与えられた力は、何の為に存在するのか！"
"10037110-180-カグヤ" = "他学園の生徒会長より、玄龍門の門主の権限が強いのは、何の為なのか！"
"10037110-181-カグヤ" = "ああ……！すべては、山海経の法に則って統治する為なのだ！"
"10037110-187-ミナ" = "（私も周りからは堅物だと言われているが……）"
"10037110-188-ミナ" = "（こいつは、本当に次元そのものが違う……）"
"10037110-192-カイ" = "錬丹術研究会に復帰した後の話は？#nもちろん、すべて無視するさ。"
"10037110-193-カイ" = "適切な手続きを踏んで再度退学だなんて、私がそんな話に乗るとでも？"
"10037110-194-錬丹術研究会員" = "しかし、それは……裏切りになりませんか？"
"10037110-195-カイ" = "今更それを私に問うのかね？"
"10037110-196-錬丹術研究会員" = "……。"
"10037110-197-カイ" = "長い時を待った――かつては矯正局に収監されたこともあったが……"
"10037110-198-カイ" = "――ついに、この時がきた。"
"10037110-199-カイ" = "私は、私のものを取り戻す。#n誰にも邪魔させないよ。"
"10037110-204-カイ" = "皆に伝えろ――"
"10037110-207-カイ" = "私が――帰ってきた、と。"
"10037110-208" = "月華夢騒"
