[translation]
"10053110-1" = "後日談その2;オカルトなんてない！"
"10053110-3-レナ" = "……。"
"10053110-8-ツバサ" = "レナ君、熱心にスマホをいじっているようだが、急用かね？"
"10053110-9-レナ" = "あ、寮の先輩たちにモモトーク送ってて……。"
"10053110-10-レナ" = "そういえば結局、私の言った通りだったでしょ？#nツチノコなんて、やっぱり存在しなかった。\r\n"
"10053110-11-ツバサ" = "いいや、ちゃんと存在していたよ。ツチノコは、我々の心の中に――\r\n"
"10053110-12-レナ" = "そういうの求めてない！！本物のツチノコの話だから！！\r\n"
"10053110-13-ツバサ" = "あぁ、そういう意味ならばたしかに。\r\n"
"10053110-14-ツバサ" = "結局ツチノコの目撃談は、外で橋を直しているあの子たちのデマだったわけだ。"
"10053110-15-レナ" = "そうそう！だから調査の結論を先輩たちに教えてあげたの。"
"10053110-16-ツバサ" = "……うん？\r\n"
"10053110-17-レナ" = "オカルトがインチキだって、これで少しは分かってもらえるはず。\r\n"
"10053110-18-ツバサ" = "……いや、それは完全に逆効果では？\r\n"
"10053110-19-レナ" = "あ、返信きた。ほら見て。"
"10053110-22-ツムギ" = "あら。\r\n\r\n\r\n\r\n\r\n"
"10053110-23-エリ" = "にゅふふ。\r\n\r\n\r\n\r\n\r\n"
"10053110-24-カノエ" = "イヒヒッ……。\r\n\r\n\r\n"
"10053110-27-レナ" = "な、なんでそんな反応なの？"
"10053110-30-ツムギ" = "レナちゃんが友達と旅行に行くって聞いて、何かと思えば。\r\n\r\n\r\n\r\n\r\n"
"10053110-31-エリ" = "まさかそんなに遠くまで行って、ツチノコというオカルトを証明しようとしていただなんて。\r\n\r\n\r\n\r\n\r\n"
"10053110-32-カノエ" = "やっぱり……レナちゃんは立派なオカ研の一員だねぇ……。\r\n\r\n\r\n"
"10053110-35-レナ" = "いやいや！！なんで全部そういう方向に解釈するわけ！？\r\n"
"10053110-36-レナ" = "違うから！！別にツチノコなんか全然興味――\r\n"
"10053110-43-レナ" = "シャーッ！違うって言ってるでしょ！！\r\n\r\n"
"10053110-44-ツバサ" = "だから言っただろう、逆効果だと……。\r\n\r\n"
"10053110-45-ツバサ" = "……おっと、忘れていた。我々も外へ行こうか。もう全員そろっている。\r\n"
"10053110-46-レナ" = "え、外？\r\n\r\n\r\n\r\n"
"10053110-47-レナ" = "……もう夕方だけど？\r\n\r\n\r\n"
"10053110-48-ツバサ" = "せっかくこんな山奥まで来たんだ。"
"10053110-53-ツバサ" = "夜にやることなんて1つしかないじゃないか。"
"10053110-58-ツバサ" = "コスモスコスモ――アリヤアリアリ――"
"10053110-59-ツバサ" = "どうか我らの呼びかけに応えたまえ。\r\n"
"10053110-60-コノカ" = "コスモスコスモ――\r\n"
"10053110-61-ミライ" = "アリヤアリアリ――\r\n"
"10053110-63-レナ" = "……？？？\r\n"
"10053110-64-レナ" = "……何してるの？"
"10053110-66-ツバサ" = "私語は慎みたまえ。#n雑念が混ざると、宇宙の暗黒エネルギーに遮断されてしまうのだよ！\r\n\r\n"
"10053110-67-ツバサ" = "銀河の彼方の存在たちよ！我らの声に応えたまえーッ！\r\n\r\n"
"10053110-72-レナ" = "……なんとかしてよ。後輩でしょ？\r\n\r\n\r\n"
"10053110-73-ミライ" = "そうなんですけど……ああなったツバサを止めるのは難しくて……。\r\n\r\n\r\n\r\n\r\n"
"10053110-74-ミライ" = "あれですよ。#n子どもに「サンタはいない」って教える役回り、やったことあります？\r\n\r\n\r\n\r\n"
"10053110-75-コノカ" = "あー……ね。\r\n\r\n\r\n\r\n\r\n"
"10053110-76-レナ" = "言いたいことは何となく分かるけどさ……。\r\n\r\n\r\n"
"10053110-78-ツバサ" = "そこ！呪文が止まっている！交信が弱まっているぞ！\r\n"
"10053110-83-レナ" = "アリヤアリアリ――\r\n"
"10053110-84-ツバサ" = "もっと心を込めて！！\r\n"
"10053110-85-レナ" = "コスモスコスモ――"
"10053110-87-ツバサ" = "もっとぉぉぉぉぉぉぉぉぉ！！！！\r\n\r\n"
"10053110-89-レナ" = "アリヤアリアリ――！！\r\n\r\n\r\n"
