[translation]
"10053070-1" = "第7話;最後の怪談"
"10053070-3-ツバサ" = "あっ、コノカ君、先生。\r\n"
"10053070-4-レナ" = "何かあったの？もう少し遅かったら探しに行くところだったんだけど……。"
"10053070-5-レナ" = "って、ちょっと！？2人してなんでそんな汗だくなの！？本当に何があったの！？\r\n\r\n"
"10053070-10-コノカ" = "あ～その～……本気で話したくない……不吉すぎて……。\r\n"
"10053070-11" = "[ns1] \"何もなかったよ……。\"\r\n[ns2] \"色々とね……。\""
"10053070-16-レナ" = "まぁ、何かあったんだね。\r\n"
"10053070-18" = "（2人に電話ボックスで起こったことを説明した）"
"10053070-19" = "（結局、前日に見た怪しいバスや石像のことまで話が及んだ）"
"10053070-22-コノカ" = "えっ！？あのバス、幽霊だったの！？なんで言ってくれなかったのさ！\r\n\r\n"
"10053070-23-レナ" = "だって、言ったら怖がるの目に見えてたし……。\r\n"
"10053070-24-コノカ" = "塩だ！塩撒いとけ！\r\n"
"10053070-25-コノカ" = "はっ！汗も塩ですけど……これでも効果あるっすかね！？"
"10053070-27" = "[ns3] \"グレーゾーン……かな……？\"\r\n[ns4] \"とりあえず、戻ったらまずシャワーを浴びよう……。\""
"10053070-32-ツバサ" = "いま聞いた話が全部本当なら、2人が体験したのはポルターガイスト現象だろうね。"
"10053070-33-ツバサ" = "一般的には幽霊が物を動かす現象として知られているけれど、#n不自然で急激な温度変化も代表例の1つだからね。\r\n"
"10053070-37-ツバサ" = "だが、どうもおかしい。それなりにこの界隈は長いと自負しているが……。"
"10053070-38-ツバサ" = "今まで体験してきた心霊現象の合計より、ここへ来てからのほうが圧倒的に多い。#n頻度が異常な程に高いんだ。\r\n"
"10053070-42-レナ" = "ツバサもそう思ってたんだ。"
"10053070-43-レナ" = "やっぱり、誰かが裏で仕組んでるってことかな？"
"10053070-44-ツバサ" = "え？いや……吾輩は単に、この辺りは超常現象の密度が高いという話をしただけだ。"
"10053070-45-ツバサ" = "もしかすると、ここの地下には古代文明の遺跡が眠っているか、#n宇宙人の極秘実験施設があるのかもしれない。\r\n"
"10053070-46-レナ" = "それ本気で言って……るんだよね、うん。\r\n"
"10053070-50-レナ" = "……七囚人なんじゃない？\r\n"
"10053070-51-レナ" = "常識的に考えても、不可解なことが次々起こるなんて変だし。#n誰かが意図的にやってるって考えたほうがまだ現実的でしょ？"
"10053070-52-レナ" = "その7人の中に、こういうことを起こせそうなやつとかいないの？"
"10053070-57-コノカ" = "う～ん、あたしは幽霊じゃなければ何でもいいんだけど……。\r\n"
"10053070-58-コノカ" = "1人、ここまでのことを仕込んでてもおかしくないやつがいる。"
"10053070-59-レナ" = "この前言ってたのと同じ人？\r\n"
"10053070-60-コノカ" = "……困ったことにそうなんだよ。"
"10053070-61-コノカ" = "うぅ……なんでよりによって、こんな場所にツチノコがいるんだよ……。\r\n"
"10053070-62-コノカ" = "いや逆か？こんな場所だからツチノコがいるのか！？"
"10053070-68-レナ" = "あ、タクシー来た！"
"10053070-72-レナ" = "とりあえず山小屋に戻って、それから改めて考えを――\r\n"
"10053070-76-レナ" = "……？\r\n"
"10053070-79-レナ" = "……？？？？"
"10053070-81-公衆電話？" = "おいコラてめえらァ！もう辛抱ならねぇ！\r\n"
"10053070-82-ツバサ" = "なんだか……色んなのが混ざっていないか？"
"10053070-83-レナ" = "ここまで来ると、怖いっていうより呆れちゃうんだけど……。"
"10053070-84-公衆電話？" = "乗らねぇのに切符切るって脅かしやがって！！\r\n"
"10053070-85-公衆電話？" = "気に入らねぇとすぐ銃ぶっ放して壊すし！！\r\n"
"10053070-86-公衆電話？" = "常識的に考えて、8メートルも掘って埋める奴がどこにいるんだ！！\r\n"
"10053070-89-ツバサ" = "なんだか、ものすごくご立腹のようだ……。\r\n\r\n"
"10053070-90-レナ" = "どの口で常識とか言ってるの？\r\n\r\n\r\n"
"10053070-91-レナ" = "いくらコノカでも、さすがに怖がるよりも――\r\n\r\n\r\n\r\n"
"10053070-93-コノカ" = "うわあああっ！？なんだよあれ！？\r\n\r\n\r\n\r\n"
"10053070-94-レナ" = "あ、違った。終わった。\r\n\r\n\r\n"
"10053070-96-公衆電話？" = "全部あの灰色頭……！あいつのせいだ……！"
"10053070-97-公衆電話？" = "今から本物の恐怖を見せてやる！！"
"10053070-99-ツバサ" = "コノカ君！危ない！\r\n"
"10053070-101-コノカ" = "うわぁぁぁぁぁ！！\r\n\r\n"
"10053070-103-レナ" = "ダメ！完全にパニックになってる！\r\n\r\n"
"10053070-104-レナ" = "怪談なら怪談らしく怖さで勝負しなさいよ！物理で殴るなー！！\r\n\r\n\r\n\r\n"
"10053070-106-公衆電話？" = "「最後の怪談」とは――自らが怪談になることだ！！"
"10053070-107-レナ" = "嘘つけ！！怪談でも何でもないでしょ！？\r\n"
"10053070-108-コノカ" = "ヒッ……。\r\n\r\n"
"10053070-110-公衆電話？" = "怖すぎて声も出ねぇか！これで終わりだぁぁ！！"
"10053070-111-ツバサ" = "マズい！このままではコノカ君が轢かれてしまう！ひいっ！\r\n\r\n"
"10053070-112-レナ" = "先生！！\r\n\r\n\r\n"
"10053070-113" = "[ns5] \"大丈夫、ここは私に任せて！\"\r\n[ns6] \"2人ともコノカを連れて逃げ……！\""
"10053070-119-コノカ" = "…………。\r\n"
"10053070-124-コノカ" = "きゃああああああああ！！\r\n\r\n\r\n\r\n\r\n"
"10053070-129-レナ" = "…………。"
"10053070-132-コノカ" = "…………。\r\n"
"10053070-136-コノカ" = "痛ぁぁぁぁぁぁぁっ！！\r\n\r\n\r\n"
"10053070-137-コノカ" = "もうなんなんだよ！これ硬すぎでしょ！！\r\n"
"10053070-141-レナ" = "え……？今の……何？\r\n\r\n\r\n\r\n"
"10053070-142-レナ" = "何が起きたの？\r\n\r\n\r\n"
"10053070-143" = "[s7] \"拳で粉砕した……。\"\r\n[s8] \"実に見事な正拳突きでした。\""
"10053070-146-公衆電話？" = "ま、待て……。どうして、最後まで……。"
"10053070-147-公衆電話？" = "こんなのありえ……。"
"10053070-148-公衆電話？" = "（ザザー……）"
"10053070-149-レナ" = "ツバサ？ねぇ、ツバサ？\r\n\r\n\r\n"
"10053070-155-レナ" = "先生、この子気絶してる！！"
"10053070-157-コノカ" = "あぁ～もう最悪だ～家に帰りたい～\r\n\r\n"
"10053070-159" = "（……こうして、怪談事件は何ひとつ解明されないまま幕を閉じた……はずだった）"
"10053070-163" = "（そしてその夜――）"
"10053070-166-ツバサ" = "あのような状況で気絶するとは……。調査班のリーダーとして面目ない。\r\n"
"10053070-167-ツバサ" = "それはそうと、あの場をどうやって切り抜けたんだ？"
"10053070-173-コノカ" = "えっと……まあ、その……どうにか……。\r\n\r\n\r\n\r\n"
"10053070-174-レナ" = "魔法以上に不思議なことって起こるんだね……#nあ、いや、この世に魔法なんてないけど……。\r\n\r\n"
"10053070-176-ツバサ" = "……？\r\n"
"10053070-177-ツバサ" = "要領を得ないが、解決したということでいいのかな？"
"10053070-178-レナ" = "解決……解決ねぇ……。\r\n\r\n"
"10053070-179-レナ" = "正直何がどうなったのか、私は全然わかってないんだけど……先生はどう？"
"10053070-180" = "[s9] \"少なくとも、普通の状況じゃないのは確かだね。\"\r\n[s10] \"これ以上ここにいるのは、ちょっと危ない気がする。\""
"10053070-183-レナ" = "やっぱそうだよね。"
"10053070-184-コノカ" = "いやいやいや、ツチノコはどうするんすか！？\r\n"
"10053070-185-レナ" = "まだツチノコを追いかける気なの……？\r\n\r\n\r\n"
"10053070-186-コノカ" = "元々あたしの厄が幽霊を呼び寄せてるんだから！#nツチノコ見つけて厄払いしないと解決できないって！"
"10053070-188-ツバサ" = "意見が割れたな……。"
"10053070-189-ツバサ" = "とはいえ今日はもう遅い。今から別の場所に移動するのは難しいだろう。"
"10053070-190-ツバサ" = "ひとまずは休んで、明日の朝に今後のことを決めよう。"
"10053070-191-レナ" = "その案には賛成だけど……そういえば、なんでツバサが仕切ってるのよ。\r\n"
"10053070-196-コノカ" = "――せい。"
"10053070-201-コノカ" = "先生。"
"10053070-202" = "[s11] \"コノカ？\"\r\n[s12] \"眠れないの？\""
"10053070-208-ツバサ" = "……しーっ。"
"10053070-209-ツバサ" = "窓の外に、誰かいる。"
"10053070-210" = "[s13] \"えっ？\"\r\n[s14] \"いつから？\""
"10053070-213-コノカ" = "それは分からないっす。あたしも所長も、さっき気づいたところで。"
"10053070-214-ツバサ" = "正確には、コノカ君が起きたことで気づいたんだが……。"
"10053070-215-コノカ" = "誰かは知らないっすけど、こんな時間まで外から見張ってるってことは、#nこの騒動の黒幕である可能性が高いっすね。\r\n"
"10053070-221-コノカ" = "もしもあたしの推測通りなら、七囚人の一人――\r\n"
"10053070-222-コノカ" = "[ruby=みつい]密井[/ruby]キョウコっす。\r\n"
"10053070-227-ツバサ" = "コノカ君。頼まれていたカメラはセットしておいたよ。すぐに撮影できる状態だ。"
"10053070-228-コノカ" = "よし……それじゃあ、3つ数えたら仕留めるから。"
"10053070-229-コノカ" = "いち――にの――\r\n"
"10053070-230-コノカ" = "いくぞぉぉぉおおお！！\r\n\r\n"
"10053070-239-レナ" = "ふにゃぁっ！？なっ、なに！？\r\n"
"10053070-245-コノカ" = "確かにいたはずなのに……どこに消えたんだ？\r\n"
"10053070-246-コノカ" = "2人も見ましたよね？"
"10053070-247-ツバサ" = "ああ。コノカ君が窓を開けるまでは確かにいた。それは断言できる。"
"10053070-248-コノカ" = "それが消えた……？まるで最初から存在しなかったみたいに……。"
"10053070-249-コノカ" = "あ、そうだ。所長、写真は？\r\n"
"10053070-250-ツバサ" = "今から確認するが、あまり期待しないでほしい。"
"10053070-251-ツバサ" = "3つ数えたらと言っていた気がするんだけどな……。\r\n\r\n"
"10053070-257-レナ" = "ちょっと！何の話？みんな何してるの？"
"10053070-258" = "[s15] \"誰かが外にいたみたい。\"\r\n[s16] \"たぶん今回の事件の黒幕だと思う。\""
"10053070-261-レナ" = "外？窓の外に……？"
"10053070-262-レナ" = "……？\r\n"
"10053070-263-コノカ" = "どうした？まだ寝ぼけてる？"
"10053070-264-レナ" = "いや、おかしくない？\r\n"
"10053070-269-レナ" = "だってここ、2階なんだよ？"
