[translation]
"2005703-1" = "踏み出す一歩"
"2005703-2-アカネ" = "……最後に、改めて確認させていただいてもよろしいでしょうか。"
"2005703-3-アカネ" = "C&C用の超小型無線機を装着し、私は教室に入ります。"
"2005703-4-アカネ" = "そして……クラスの子たちに歩み寄って会話を試みます。"
"2005703-5-アカネ" = "昨夜、二人でシミュレーションした通りに……。"
"2005703-6-アカネ" = "先生はその様子を装置越しに聞きながら、アドバイスをくださる。#nその流れで大丈夫でしょうか？"
"2005703-7-アカネ" = "「親しくなろう：アバター訓練」です。"
"2005703-11-アカネ" = "……。"
"2005703-12-アカネ" = "本当に、大丈夫でしょうか……？"
"2005703-13" = "[s1] \"当たって砕けろともいうし……。\"\n[s2] \"ここまで来たら、やるしかないよ！\""
"2005703-16-アカネ" = "そうですね。先生、何卒よろしくお願いします。"
"2005703-21" = "（とは言ったものの……私にできるのだろうか）"
"2005703-22" = "（若い子同士の会話、うまくアドバイスできるだろうか……）"
"2005703-37-ミレニアムの生徒A" = "あれ、アカネさん。"
"2005703-38-ミレニアムの生徒B" = "お、おはよう……アカネ、さん。"
"2005703-45-アカネ" = "二人とも、おはよう！#nアカネ[ruby=・]さ[/ruby][ruby=・]ん[/ruby]じゃなくて呼び捨てでいいよ！"
"2005703-47-ミレニアムの生徒A" = "……！？"
"2005703-48-ミレニアムの生徒B" = "……！？！？！？"
"2005703-50-アカネ" = "（……本当にこれで大丈夫なのでしょうか）"
"2005703-51" = "[s] （大丈夫だと信じよう……！）"
"2005703-52-アカネ" = "（そう、ですね……）"
"2005703-55-ミレニアムの生徒A" = "き、今日はなんかいつもと違う感じがするね？#nアカネ……さん？"
"2005703-56-ミレニアムの生徒B" = "そ、そそ、そうだね。メガネを外しているのも初めて見るし。"
"2005703-58-アカネ" = "ちょっとイメチェンしてみようかなって思って。コンタクトにしてみたんだけど、どうかな？"
"2005703-59-アカネ" = "それにアカネ[ruby=・]さ[/ruby][ruby=・]ん[/ruby]って……ちょっと寂しいな。"
"2005703-64-ミレニアムの生徒A" = "えっと……生活健康部から何かもらったりした？"
"2005703-65-ミレニアムの生徒A" = "新しいホルモン剤とか……ほら、ホルモンバランスで性格って変わるっていうし……。"
"2005703-66-ミレニアムの生徒A" = "今までよりパワフルになるって聞いたりもしたような……あはは。"
"2005703-67-ミレニアムの生徒B" = "……そこまでいくと、ちょっと疑似科学部みたいな胡散臭さがあるような。"
"2005703-68-ミレニアムの生徒A" = "いやでもほら……生活健康部の子たちって本当に、人を変えちゃうじゃん。 "
"2005703-69-ミレニアムの生徒B" = "あー、まぁそっちのほうがタチ悪いかも。"
"2005703-74-アカネ" = "（先生と二人で練りに練った台本だったのに……）"
"2005703-75-アカネ" = "（すみません。やはり、私には向いていないのだと改めて実感してしまいました……）"
"2005703-76" = "[s] （いや……アカネは悪くないよ。私が若い子のことよく分かっていなかったから……）"
"2005703-77-アカネ" = "（ですが……これからどうすれば良いのでしょう……？）"
"2005703-78" = "[s] （そうだね……例えば、こういうのを提案してみるとか？）"
"2005703-83-アカネ" = "も、もしよかったら！放課後、春葉原に行かない？"
"2005703-84-アカネ" = "コラボイベントやってるんだって！"
"2005703-86-ミレニアムの生徒A" = "春葉原……？"
"2005703-87-ミレニアムの生徒B" = "コラボイベント……？"
"2005703-89-アカネ" = "（……）"
"2005703-90-アカネ" = "（やっぱり……これも無理があるのかもしれません……）"
"2005703-96-ミレニアムの生徒A" = "えー！アカネさんも春葉原行くんだね！"
"2005703-97-ミレニアムの生徒B" = "誘ってくれて嬉しい！？いこいこ！ "
"2005703-99-アカネ" = "……。"
"2005703-100-アカネ" = "はい！"
"2005703-106-ミレニアムの生徒A" = "あ……そろそろ席に戻らなきゃ。"
"2005703-107-ミレニアムの生徒B" = "終わったらすぐ行こ！春葉原久しぶりだ！？"
"2005703-108-ミレニアムの生徒A" = "え、2週間前も行ってたじゃん……。"
"2005703-109-ミレニアムの生徒B" = "2週間前は久しぶりじゃない？"
"2005703-111" = "（アカネと一緒に安堵のため息を吐いた）"
"2005703-112" = "（若者の会話を大人が予測しようなんて土台無理な話だったのだと痛感した……）"
"2005703-122-ミレニアムの生徒B" = "春葉原と～ちゃ～く！"
"2005703-123-ミレニアムの生徒A" = "どこ行く？"
"2005703-124-ミレニアムの生徒B" = "ゲーセン行きたい！今度こそランキングを更新してやる！"
"2005703-125-ミレニアムの生徒A" = "ランキングの更新は一人の時にやりなよ……。#nアカネ……さんは？コラボイベントってどこでやってるの？"
"2005703-130-アカネ" = "（せ、先生？こういうときは、どうしたらいいのでしょう……？）"
"2005703-131" = "[s] （そういう時は……）"
"2005703-135-アカネ" = "ここでコラボフードが出てて……行ってもいいかな？"
"2005703-137-ミレニアムの生徒A" = "あ、いいね！ドリンクも手伝えるよ！"
"2005703-138-ミレニアムの生徒B" = "お昼ご飯、結構ガッツリ食べちゃったんだけど……まあいっか！"
"2005703-147-ミレニアムの生徒B" = "来たぞ！ゲーセン！"
"2005703-148-ミレニアムの生徒A" = "本当にやるの……？"
"2005703-149-ミレニアムの生徒B" = "当たり前でしょ！UZQueenだか何だか知らないけど、ずーっと1位を取られ続けてるんだよ！？#n今日こそ引きずり下ろしてやる！"
"2005703-150-ミレニアムの生徒A" = "え？"
"2005703-151-アカネ" = "あ……。"
"2005703-157-ミレニアムの生徒A" = "……アカネさんもUZQueenのこと知ってるの？"
"2005703-161-アカネ" = "色々ありまして……？"
"2005703-162-ミレニアムの生徒A" = "まあ……挑戦は自由だけどさ……。"
"2005703-163-ミレニアムの生徒A" = "はあ……絶対無理なのに……こういうのって止めたほうがいいのかなぁ……。"
"2005703-164-アカネ" = "あははは……。"
"2005703-179-ミレニアムの生徒B" = "エネルギー補給が必要……脳が糖分を欲してる……。#nあ！このプリン食べよ！新商品だって！"
"2005703-180-ミレニアムの生徒A" = "キャラメルしそ味……？これ、本当に大丈夫なの？ヤバそうじゃない？"
"2005703-182-アカネ" = "（これは……「変な味で味覚テロ疑惑」として[ruby=・]お[/ruby][ruby=・]掃[/ruby][ruby=・]除[/ruby]の依頼を受けていた時の……）"
"2005703-183-アカネ" = "（あの工場の社長に悪気はなく、ただしそに身を捧げた方だったということで終結したはず……）"
"2005703-184-アカネ" = " （本当にあの社長の情熱は、お見事でしたね……）"
"2005703-190-ミレニアムの生徒A" = "……。"
"2005703-191-ミレニアムの生徒B" = "……。"
"2005703-196-アカネ" = "へ、変だった……かな？"
"2005703-198-ミレニアムの生徒A" = "アカネちゃん、歌超うまーい！"
"2005703-199-ミレニアムの生徒B" = "耳が幸せだった……。"
"2005703-201-アカネ" = "も、もう！照れるよ……。"
"2005703-205-アカネ" = "パーソナルカラー的に、この色がいいんじゃないかな。#nここにニュアンスで入れてみたら……ほら。"
"2005703-206-ミレニアムの生徒B" = "ほんとだ……すごい！顔に陰影がついた！"
"2005703-207-ミレニアムの生徒A" = "アカネちゃん、すごい！詳しいんだね！"
"2005703-208-アカネ" = "（任務で変装してたのが役立って良かった……）"
"2005703-215-ミレニアムの生徒A" = "あー楽しかった！"
"2005703-216-ミレニアムの生徒B" = "いっぱい遊んだね。#nでも……。"
"2005703-217-ミレニアムの生徒A" = "……。"
"2005703-219-アカネ" = "……？"
"2005703-221-ミレニアムの生徒A" = "アカネちゃん、もう大丈夫だよ。"
"2005703-222-ミレニアムの生徒B" = "今日一日、無理してたよね？"
"2005703-227-アカネ" = "あ……。"
"2005703-228-アカネ" = "……全部、分かっていたんですか？"
"2005703-230-ミレニアムの生徒A" = "そりゃ普通に分かるよ。"
"2005703-231-ミレニアムの生徒B" = "何か事情があるのかなって思いもしたけど……。"
"2005703-233-アカネ" = "……。"
"2005703-234-アカネ" = "ちょっと待ってくださいね。#nコンタクトレンズが少しずれて……外しますね。"
"2005703-239-ミレニアムの生徒A" = "いつものアカネちゃんに戻ったね。メガネかけてないのも新鮮だったけど。"
"2005703-240-ミレニアムの生徒B" = "でもこっちが私たちが知ってるアカネちゃんって感じ。"
"2005703-241-ミレニアムの生徒B" = "それで……どうして急に？"
"2005703-243-アカネ" = "！？"
"2005703-244-ミレニアムの生徒A" = "あ、言いにくいなら別に大丈夫だよ。#n楽しかったし。"
"2005703-245-アカネ" = "その……実は――"
"2005703-246-アカネ" = "……。"
"2005703-247-アカネ" = "先生のお話を聞いて、皆さんと……。"
"2005703-248-アカネ" = "いつも以上に一歩、歩み寄りたい……と思ったんです。"
"2005703-250-ミレニアムの生徒B" = "なーんだ……そうだったんだ。"
"2005703-255" = "（アカネの楽しそうな声を聞きながら、静かに無線機の電源を切った）"
"2005703-256" = "（そして……）"
"2005703-260" = "（「若者日常会話シミュレーション」みたいなことは、当分しないと誓った……）"
