[translation]
"2005702-1" = "これが私の日常"
"2005702-4-ミレニアムの生徒A" = "あ、先生！"
"2005702-5-ミレニアムの生徒B" = "こんにちは、先生！さっき後ろで見てました？"
"2005702-6-ミレニアムの生徒A" = "先生の視点からみて、どうでした？"
"2005702-7" = "[s] \"結構高度な話をしていて……ちょっと難しいかも。\""
"2005702-8-ミレニアムの生徒B" = "そんなに難しくはないですよ！今度一緒に研究してみませんか？"
"2005702-22-ミレニアムの生徒A" = "あっ、アカネ……。"
"2005702-23-ミレニアムの生徒A" = "……さん。"
"2005702-25-アカネ" = "あら、こんにちは。 "
"2005702-26-アカネ" = "……。"
"2005702-27-アカネ" = "[ruby=・]先[/ruby][ruby=・]生[/ruby]とこんなふうにお会いできて、とても嬉しいです。"
"2005702-29-ミレニアムの生徒B" = "アカネ……さんも一緒にお話する？"
"2005702-31-アカネ" = "……。"
"2005702-32-アカネ" = "お誘いはありがたいのですが……。"
"2005702-33-アカネ" = "ふふ。皆さんのお邪魔になってしまいそうなので私は遠慮しておきますね。"
"2005702-34-アカネ" = "私はこれで。"
"2005702-38" = "[ns] \"アカネ……？\""
"2005702-39-ミレニアムの生徒A" = "行っちゃった……。"
"2005702-40-ミレニアムの生徒B" = "別に邪魔だなんてそんなことないのに……。"
"2005702-41-ミレニアムの生徒B" = "アカネって……ちょっと距離があるっていうか、壁みたいなものを感じるんだよね。"
"2005702-44-ミレニアムの生徒A" = "そうなんだよね。"
"2005702-45-ミレニアムの生徒B" = "まあ、C&Cで忙しいみたいだから仕方ないか。"
"2005702-48-ミレニアムの生徒A" = "なんかちょっと不思議だよね？#nアカネが秘密組織のエージェントだなんて。"
"2005702-49-ミレニアムの生徒B" = "あのくらいのほうがC&Cでは強みになるんじゃないかな。"
"2005702-50-ミレニアムの生徒A" = "お願いしたこと全部やってくれるし、丁寧だし。#n強いし……完璧超人って感じ？"
"2005702-51-ミレニアムの生徒A" = "だからなのかなぁ？"
"2005702-52-ミレニアムの生徒B" = "それはあるかも？ちょっと近寄りがたいっていうか。"
"2005702-57" = "[ns] （……）"
"2005702-59" = "[ns] （アカネの様子が気になる）"
"2005702-69-アカネ" = "もうお戻りになるんですか？"
"2005702-70" = "[s] \"アカネ！\""
"2005702-72" = "[ns] \"もしかして、待っててくれたの？\""
"2005702-73-アカネ" = "ええ。先生がこうしていらしてくださったのですから。#nご主人様のメイドとして、出迎えるのは当然です。"
"2005702-74-アカネ" = "それでは、お気をつけてお帰りください。#n私はここで失礼します。"
"2005702-75" = "[s] \"え、ええ……？\""
"2005702-78-ミレニアムの生徒B" = "アカネって……ちょっと距離があるっていうか、壁みたいなものを感じるんだよね。"
"2005702-79-ミレニアムの生徒A" = "そうなんだよね。"
"2005702-80-ミレニアムの生徒A" = "お願いしたこと全部やってくれるし、丁寧だし。#n強いし……完璧超人って感じ？"
"2005702-81-ミレニアムの生徒B" = "それはあるかも？ちょっと近寄りがたいっていうか。"
"2005702-83" = "[ns] \"待って！\""
"2005702-85-アカネ" = "どうかなさいましたか？"
"2005702-86-アカネ" = "一緒に……帰る？"
"2005702-90-アカネ" = "……。"
"2005702-91-アカネ" = "かしこまりました、[ruby=・]ご[/ruby][ruby=・]主[/ruby][ruby=・]人[/ruby][ruby=・]様[/ruby]。"
"2005702-92-アカネ" = "送ってくださり、ありがとうございます。"
"2005702-93-アカネ" = "あら……そうですか。分かりました。"
"2005702-94-アカネ" = "そうですね……制服を着ているのですから。#n……先生。"
"2005702-95-アカネ" = "それでは少しの間、よろしくお願いします。"
"2005702-103" = "（アカネと一緒に、夕暮れの道を歩いた）"
"2005702-104" = "（なんともいえない沈黙が続く……）"
"2005702-107" = "[ns] \"あのさ……。\""
"2005702-108-アカネ" = "はい、どうかされましたか？"
"2005702-109-アカネ" = "私の様子が、普段と違う気がする……？"
"2005702-110-アカネ" = "それは……。"
"2005702-111-アカネ" = "……失礼しました、先生。"
"2005702-112-アカネ" = "学園にいる間は、いつもこうなのですが……。"
"2005702-113" = "[s1] \"そ、そうなんだね……。\"\n[s2] \"あの子たちとは、どんな関係なの？\""
"2005702-116-アカネ" = "あの子たちですか？"
"2005702-117-アカネ" = "教室でたまに会話するくらい……でしょうか。[ruby=・]部[/ruby][ruby=・]の[/ruby][ruby=・]活[/ruby][ruby=・]動[/ruby]がある時はそちらを優先していますが……。"
"2005702-118-アカネ" = "よくお話させていただいています。"
"2005702-120" = "（再び、なんともいえない沈黙が続いた……）"
"2005702-123-アカネ" = "先生？"
"2005702-124" = "[s] \"う、うん？\""
"2005702-125-アカネ" = "やはり、気になりますか？"
"2005702-126" = "[s] \"うん……。\""
"2005702-127-アカネ" = "……。"
"2005702-131-アカネ" = "そうですね。私はいつもこうなのです。"
"2005702-132-アカネ" = "C＆Cでも……同様に。"
"2005702-133-アカネ" = "部長はあれでいて周囲に気を使われる方ですし、良くも悪くも人に好かれます。"
"2005702-134-アカネ" = "アスナ先輩も……むしろ、先輩は誰とでもすぐに仲良くなるタイプ、ですね。"
"2005702-135-アカネ" = "カリンは……ふふ。ミレニアムでは珍しい数学が苦手な子たちと、同志のように仲良く過ごしているようです。"
"2005702-136-アカネ" = "トキちゃんは……。"
"2005702-137-アカネ" = "……。"
"2005702-138-アカネ" = "ふふっ。トキちゃんは、なんだか手を差し伸べてあげたくなりませんか？"
"2005702-139-アカネ" = "……。"
"2005702-140-アカネ" = "ですが、私は違います。全くお話ができないわけではないのですが。"
"2005702-141-アカネ" = "言い換えれば誰とも……一定の距離以上近づくことがないのです。"
"2005702-145-アカネ" = "先生のそんな表情、なんだか初めて見ますね。ふふ。"
"2005702-146-アカネ" = "やっぱり先生も、人と仲良くした方が良い、とお思いですか？"
"2005702-147" = "[s] \"うーん……。そうは思わないよ。\""
"2005702-148-アカネ" = "えっ……？"
"2005702-149-アカネ" = "本当に、直さなくて良いと……？"
"2005702-150" = "[s3] \"うん。アカネがそれで良いなら、別にいいと思う。\"\n[s4] \"世の中にはそういう人だっているし。\""
"2005702-153-アカネ" = "人と距離を置きつづけることは、良くないのでは？"
"2005702-154-アカネ" = "誰とでも深い仲になれる方が、物事が円滑に進むのではないかと。"
"2005702-155" = "[s5] \"だけど、それを――\"\n[s6] \"押し付けのように感じる人も、いるんじゃないかな？\""
"2005702-158-アカネ" = "……。"
"2005702-159-アカネ" = "大切なのは自分の感情、だと。"
"2005702-160-アカネ" = "私がどう感じるのか……なるほど。"
"2005702-161" = "[s7] \"うん。それで良いと思う。\"\n[s8] \"これは私がそう思っている、ってだけだけどね。\""
"2005702-180-アカネ" = "あら……？"
"2005702-183" = "[ns] \"アカネ？\""
"2005702-184-アカネ" = "いえ。"
"2005702-185-アカネ" = "すみません。"
"2005702-189-アカネ" = "……。"
"2005702-190-アカネ" = "私……本当は。"
"2005702-191-アカネ" = "少しだけ、かもしれませんが。"
"2005702-193-アカネ" = "寂しかった、みたいです。"
"2005702-194-アカネ" = "大丈夫だと思っていたのですが。"
"2005702-195-アカネ" = "すみません、先生。"
"2005702-196-アカネ" = "本当に……申し訳ありません。"
"2005702-199" = "[ns] \"大丈夫。\""
"2005702-201" = "[ns] \"アカネが頑張りたいなら、応援するよ。\""
"2005702-206-アカネ" = "……はい。"
