[translation]
"10028010-1" = "第1話;3時10分、ゲヘナ行き"
"10028010-50-ハスミ" = "――どうぞ。"
"10028010-57-イチカ" = "失礼します、ハスミ先輩。お呼びっすか？"
"10028010-58-ハスミ" = "はい、イチカ。お待ちしておりました。"
"10028010-59-ハスミ" = "朝早くに呼び出してしまって申し訳ありません。#nよく眠れましたか？"
"10028010-60-イチカ" = "はい、睡眠はたっぷり取ってるんで大丈夫っすよ！へへっ。"
"10028010-61-イチカ" = "……こんな時間に呼び出すってことは、何かあったんすよね？"
"10028010-62-ハスミ" = "事件とまではいきませんが……そうですね。"
"10028010-63-ハスミ" = "ツルギとも話してみましたが、やはりこの件はイチカが適任だと思いまして。"
"10028010-64-イチカ" = "へっ？ツルギ先輩との話し合い……？#n私が「適任」……？"
"10028010-65-イチカ" = "いったい何があったんすか……"
"10028010-66-ハスミ" = "ああ、プレッシャーをかけるつもりはありません。#n危険でも難しい内容でもありません。"
"10028010-67-ハスミ" = "……カバンを今日中にティーパーティーに持って行ってほしいのです。"
"10028010-68-ハスミ" = "また、カバンはトリニティ自治区から離れた場所にあるため……"
"10028010-69-ハスミ" = "他の自治区の生徒とも仲の良い、イチカに任せようかと。"
"10028010-70-ハスミ" = "私やツルギが行くよりは、そちらの方がつつがなく事が運ぶでしょう。"
"10028010-71-イチカ" = "あーなるほど、そういうことなんすね。#n要は、[ruby=・   ・   ・]お使い[/ruby]みたいな感じっすよね？"
"10028010-72-ハスミ" = "そうですね……お使いではありますが、カバンには重要な遺物が入っています。"
"10028010-73-ハスミ" = "ティーパーティーだけでなく、トリニティ全体にとって大切なものなのです。"
"10028010-75-ハスミ" = "そう――これはティーパーティーのナギサ様からの依頼。"
"10028010-76-ハスミ" = "つまり――"
"10028010-83-ハスミ" = "「ティーパーティーの政治的立場に影響を与える」レベルの重要な遺物と言えるでしょう。"
"10028010-88-イチカ" = "なるほど……おつかいって言ってすみませんでした。"
"10028010-89-ハスミ" = "……それと。"
"10028010-90-ハスミ" = "もう一点……"
"10028010-91-ハスミ" = "例のカバンと同じくらい重要な事が――"
"10028010-95-ハスミ" = "カバンの回収を終えたら、先生が同じ列車に乗る手はずとなっています。"
"10028010-96-ハスミ" = "そこで……先生のサポートをお願いできますでしょうか？"
"10028010-97-ハスミ" = "先生は遺物の発掘作業に、同行してくださったのです。"
"10028010-98-ハスミ" = "私個人の希望ではありますが……#nせめて、列車移動の間だけでも、ゆっくりしていただきたいと思いまして。"
"10028010-102-イチカ" = "……ん？"
"10028010-103-イチカ" = "先生がカバン持ってるんすか？"
"10028010-104-ハスミ" = "そうです。もちろん、これは指示ではありません。#n正義実現委員会からの指示は、カバンを届けることだけ。"
"10028010-105-ハスミ" = "カバンの回収に影響が出るようであれば、気にしないでいただいて結構です。"
"10028010-111-ハスミ" = "どうでしょう。受けていただけますでしょうか……？"
"10028010-112-イチカ" = "……んー。"
"10028010-113-イチカ" = "とりあえず、任務について了解っす。"
"10028010-114-イチカ" = "……先生……先生、か……"
"10028010-115-イチカ" = "カバン、列車……先生……"
"10028010-116-イチカ" = "……へへっ。"
"10028010-117-イチカ" = "いいっすよ。帰り道に話し相手ができるってことですし、前から先生とはちゃんと話してみたかったんで。"
"10028010-118-イチカ" = "まっ、なんてことないっす。"
"10028010-119-イチカ" = "カバンを取りに行くだけですし。"
"10028010-125-イチカ" = "任せてください！"
"10028010-127-イチカ" = "――というのが、今朝のやり取りっす。"
"10028010-128-イチカ" = "よいっ……しょっと。"
"10028010-185-イチカ" = "ふぅ……"
"10028010-186-イチカ" = "これで最後の荷物っすね！久々にいい汗かいたっす。"
"10028010-187-イチカ" = "先生もお疲れ様でした。#n正義実現委員を……いや、トリニティを代表してお礼を申し上げるっす。"
"10028010-188-イチカ" = "いつもなら代表なんて縁遠い言葉っすけど、今日は状況が違うので！"
"10028010-189-イチカ" = "いいとこ見せないとっすよね！へへっ。"
"10028010-190" = "[s1] \"イチカもお疲れ様。\"\n[s2] \"ここまで遠かったし、移動も大変だったでしょ。\""
"10028010-193-イチカ" = "一番大変だったのは、先生と発掘チームの皆さんっすよ！"
"10028010-194-イチカ" = "私は後片付けをちょっと手伝っただけっすから！"
"10028010-195-イチカ" = "にしても不思議っすね……#nティーパーティーの一番最初の会合で使われたティーセット……"
"10028010-196-イチカ" = "これって超重要な[ruby=こうほう]校宝[/ruby]じゃないすか。#nよく今になって見つかったっすね。"
"10028010-197-イチカ" = "それも、トリニティ自治区からこんなに離れた場所で。"
"10028010-198-イチカ" = "……え？"
"10028010-199-イチカ" = "大事なティーカップというのは知ってたけど、その理由までは知らなかったんすか……？"
"10028010-200-イチカ" = "まったく……こんな大事な依頼をお願いしておきながら、説明もしてなかったんすか……"
"10028010-201-イチカ" = "ま、別に機密情報でもないし……アレっすよ、アレ。"
"10028010-202-イチカ" = "……「正統性」ですね。"
"10028010-203-イチカ" = "ご存じの通り、最近いろんなことがあった関係で……#nティーパーティーの方々が、救護騎士団とかシスターフッドと対等に話せず頭を悩ませているんだとか。"
"10028010-204-イチカ" = "そんな状況でこの遺物を発見したのは大きいと思います。#n「我々は由緒正しい存在」「トリニティの祖」だとアピールできるので。"
"10028010-205-イチカ" = "だからティーパーティーも、先生に発掘作業を手伝ってもらおうと思ったんじゃないんすかね。"
"10028010-206-イチカ" = "私がここに送られたのも、先生をサポートするためっすから。"
"10028010-207-イチカ" = "……つまり！"
"10028010-208-イチカ" = "今日は1日……私が先生のお願いを何でも聞くっすよ！"
"10028010-209-イチカ" = "いいっすか、超レアっすからね？#n頼み事があるなら何でも言ってください。"
"10028010-210-イチカ" = "私は、先生のためにここにいるっすから！！"
"10028010-211" = "[s3] \"イチカは頼もしいね、ありがとう。\"\n[s4] \"お世話になるよ、よろしくね。\""
"10028010-214-イチカ" = "先生からそう言われると嬉しいっすね。#n来て良かったです、へへっ。"
"10028010-215-イチカ" = "一度、ご一緒してみたくて……"
"10028010-216-イチカ" = "ツルギ先輩とかハスミ先輩……それにマシロも、よく先生の話をしてるから。"
"10028010-217-イチカ" = "……あっ。いい話しか聞いてないんで、心配はいらないっすよ。"
"10028010-218-イチカ" = "「良い人だ」とか「一緒にいると落ち着く人だ」とか、まぁそんなとこっすね。"
"10028010-219-イチカ" = "だから、先生に興味が湧くのは、自然な流れというか……"
"10028010-220-イチカ" = "実際、私は担当業務的にお会いする機会はほとんどなかったすけど……"
"10028010-221-イチカ" = "……ん？"
"10028010-222-イチカ" = "いつでも連絡して大丈夫……？"
"10028010-223-イチカ" = "……ふふ、それは嬉しいっすね。"
"10028010-224-イチカ" = "でも、あんまりお手間をかけたくはないというか。"
"10028010-225-イチカ" = "先生は気にされないとしても、やはり周囲の目は違いますから。"
"10028010-226-イチカ" = "……「手のかかる子」にはなりたくない、という話っす。"
"10028010-227-イチカ" = "ただ、今回みたいな機会があるのなら……"
"10028010-228-イチカ" = "ちょっとだけ、プライベートな話もできたらなと。"
"10028010-232-イチカ" = "……はは、変なこと言っちゃったっすね。"
"10028010-233-イチカ" = "それじゃ、残りの荷物も片付けますか。"
"10028010-238-イチカ" = "えーと、装備はだいたい終わりで……"
"10028010-239-イチカ" = "……ん？"
"10028010-240-イチカ" = "ああ、ティーセットっすか。あの白いカバンに入ってたアレっすね。"
"10028010-241-イチカ" = "それなら大丈夫っす！片付け始める前に、念のため確認しておいたんで。"
"10028010-242-イチカ" = "貨物車両にちゃんとあったっすよ。#n後は片付けが終わったら、列車に乗るだけっすね。"
"10028010-247-イチカ" = "……ん？"
"10028010-251-イチカ" = "何で車両にって……"
"10028010-252-イチカ" = "列車に乗って帰るんじゃなかったんすか？"
"10028010-253-イチカ" = "……ん？"
"10028010-254-イチカ" = "3時間後の列車……？"
"10028010-255-イチカ" = "6時10分の列車すか……？"
"10028010-260-イチカ" = "今、3時っすね……？"
"10028010-261-イチカ" = "あれ、もしかして……"
"10028010-262-イチカ" = "時刻表が合ってるなら、もう出発時間……"
"10028010-266-イチカ" = "じゃあ、あのカバンは……？"
"10028010-267-イチカ" = "……っと、今はこんなことを考えてる場合じゃないっすね。#n急いで取りに行かないと。"
"10028010-272-アナウンス" = "ご案内いたします。"
"10028010-273-アナウンス" = "まもなく「特急・ゲヘナ行き」の列車が発車いたします。"
"10028010-274-アナウンス" = "ご利用のお客様は、ご着席いただきますようお願い申し上げます。"
"10028010-275-アナウンス" = "繰り返します。まもなく「特急・ゲヘナ行き」の列車が――"
"10028010-280-イチカ" = "えっ……と。"
"10028010-282-イチカ" = "「ゲヘナ行き」……？"
