[translation]
"10028080-1" = "エピローグ;護送車両"
"10028080-3" = "風紀委員会・特殊護送車両の内部"
"10028080-7-？？？" = "指名手配犯が到着した！鎖をつけろ！"
"10028080-15-風紀委員A" = "さっさと入れ！悪足掻きはするなよ。"
"10028080-20-風紀委員B" = "……よし、止まれ！#nゲヘナに着くまでおとなしくしてろ。いいな！"
"10028080-21-風紀委員A" = "鎖、足枷の固定完了！"
"10028080-26-風紀委員B" = "他の奴らは全員もう一つのトラックか？#nギャング団の奴ら、結構いたよな？"
"10028080-27-風紀委員B" = "この車両には1名しか乗ってないが……本当に合ってるのか？"
"10028080-28-風紀委員A" = "まあ、トラックなら何台もあるからな。#nそれにこいつは……ちょっと特別だ。"
"10028080-29-風紀委員A" = "イオリ先輩が「要注意人物だから特に注意しろ」と言ってたんだ。"
"10028080-30-風紀委員B" = "要注意人物ね……噂には聞いてたけど、そんな風には見えないな。"
"10028080-31-風紀委員A" = "そう言ってると痛い目に合うぞ。護送チームのほとんどが保健室行きになった挙句、列車をひっくり返した怪物だ。どう見てもヤバい奴だろ。"
"10028080-32-風紀委員B" = "たしかに……他の先輩とか追跡チームからも散々話は聞いたし。"
"10028080-33-風紀委員A" = "けど、それも今日で終わり。#n風紀委員会の本部……絶対に脱出不可能な部屋に入るんだし。"
"10028080-34-？？？" = "…………。"
"10028080-35-風紀委員B" = "……にしてもコイツ、本当に一言も喋らないな。ちょっと気味が悪くないか？"
"10028080-36-風紀委員A" = "放っとけ、私たちは自分の仕事をやればいい。#nもう夜だ、日が昇るまでには終わらすぞ。"
"10028080-37-風紀委員B" = "ドアを閉めろ！出発用意！#n――全員、中に移動して座れ！！"
"10028080-38-風紀委員C" = "あとは持ち場で待機！到着するまで、現状を維持しろ！！"
"10028080-44-風紀委員A" = "……出発する！"
"10028080-50-？？？" = "…………。"
"10028080-51-？？？" = "…………♪"
"10028080-56-？？？" = "……なあ、知ってるか？"
