[translation]
"10028050-1" = "第5話;地獄行き特急列車"
"10028050-10-イオリ" = "えっと……その、さ。"
"10028050-11-イオリ" = "まさかとは、思うけど……"
"10028050-12-イオリ" = "その、まさか……"
"10028050-13-イオリ" = "まさか先生とトリニティの正義実現委員が……"
"10028050-14-イオリ" = "「テロリストの交渉に応じる」なんてこと……ないよな？そうだよな？"
"10028050-15-カスミ" = "ハーハッハッハ！！イ～オ～リ～ちゃん！"
"10028050-16-カスミ" = "君はこのカバンの中身が何か知ってるかい？"
"10028050-17-カスミ" = "これは……「トリニティ学園の[ruby=こうほう]校宝[/ruby]」だぞ？"
"10028050-18-カスミ" = "それも……"
"10028050-32-カスミ" = "あの学園の政治に、影響を与えるほどの。"
"10028050-33-イオリ" = "ん……？トリニティの、校宝……？"
"10028050-34-イオリ" = "何でそんな代物がここに……"
"10028050-35-カスミ" = "さあさっ！だから、これ以上複雑に考えることないって。"
"10028050-36-カスミ" = "こうなったからには、みんな正直になろうじゃあないか！#n希望に満ちた結末は意外と近くにあるかもしれないぞ？"
"10028050-37-カスミ" = "まずイオリは、列車を止めて車内の乗務員やギャング団を捕まえたいはずだ。それが最初の目標だっただろう。"
"10028050-38-カスミ" = "私なんて、今日じゃなくてもいいだろう？#nいや、むしろ普段は私を追うのが楽しみなはずだ！"
"10028050-39-カスミ" = "で、トリニティのお嬢ちゃんはこのカバンだよな！#nこれを持って次の停車駅で降りればいいだけ。"
"10028050-40-カスミ" = "私は～……"
"10028050-41-カスミ" = "まあ、みんなが無視してくれれば勝手に消えるさ。"
"10028050-42-カスミ" = "だから要は！我々がここでゴタゴタする必要はないってことだ！#nそうだろう？"
"10028050-43-カスミ" = "偶然同じ列車に乗り合わせた私の存在に目をつむる……それだけのこと！"
"10028050-44-カスミ" = "完璧じゃないか？別に初めてでもないだろ？"
"10028050-45-カスミ" = "みんなも、ある程度世の仕組みも分かってるはずだろうに。"
"10028050-46-カスミ" = "どうだい、イオリ！今日はこの辺で解散といこうじゃないか。"
"10028050-47-カスミ" = "考えてみれば……"
"10028050-48-カスミ" = "そう悪い話じゃないと思うぞ？"
"10028050-49-イオリ" = "ふざけるな！！指名手配犯を目の前にして引き下がれると思うか！？"
"10028050-50-イオリ" = "それに、トリニティの件は私の仕事とは関係ない！！#n私は今、私のやるべきことをやる！！"
"10028050-54-イチカ" = "…………。"
"10028050-55-イチカ" = "……ふっ。"
"10028050-56" = "[s1] \"……？\"\n[s2] \"イチカ……？\""
"10028050-60-カスミ" = "へぇ……？"
"10028050-61-カスミ" = "それこそ、イオリちゃんの独断じゃないのかい？#n勝ち目は薄いだろう？"
"10028050-62-カスミ" = "なんたって、カバンは私の手にある。"
"10028050-63-カスミ" = "つまりトリニティの子と先生は、私の言いなりになるしかない。#nなあ、そこのお嬢ちゃん？"
"10028050-64-イチカ" = "…………。"
"10028050-65-イオリ" = "だから、同じことを何回も言わせるな！#nそれはそれ、これはこれと言ってるだろ！！"
"10028050-66-イオリ" = "なにも監禁するわけじゃない。#n事情を調べたいだけだというのに、何がそんなに不満なんだよ！"
"10028050-67-イチカ" = "…………。"
"10028050-68-カスミ" = "まあ、見てみなって。あのお嬢ちゃんがどんな選択をするか……#nこのカバンを取り戻すためにイオリちゃんを撃つはずさ。"
"10028050-69-カスミ" = "なあ？正義実現委員の……ええと。"
"10028050-70-カスミ" = "……ニカちゃん？"
"10028050-71-カスミ" = "そうだろ？この中身、割れたらまずいんだろう？"
"10028050-72-イチカ" = "…………。"
"10028050-73-イオリ" = "あーーっもう！！さっきからカバン、カバン、カバンってもう……！！！"
"10028050-74-イチカ" = "…………。"
"10028050-75-イオリ" = "たかがカバン1つでぐだぐだと――"
"10028050-86-カスミ" = "……おっ？"
"10028050-87-カスミ" = "ハハッ……！"
"10028050-88-カスミ" = "あは！あはははっ！！"
"10028050-89-カスミ" = "ハーハッハッハッハ！！！"
"10028050-90-カスミ" = "ほら、だから言っただろう！？"
"10028050-91-カスミ" = "イオリちゃんよぉ～……"
"10028050-92-カスミ" = "何でわざわざ勝ち目のない勝負に出るのさ？"
"10028050-93-カスミ" = "こちらの勝ちは目に見えていたじゃないか～まったく。"
"10028050-94-カスミ" = "お嬢ちゃんは、こちらにカバンがある以上絶対――"
"10028050-100-カスミ" = "……ごふっ！？"
"10028050-112" = "[ns] \"……えっ。\""
"10028050-114" = "[ns] \"……！？！？！？\""
"10028050-118-イチカ" = "…………あ。"
"10028050-119-イチカ" = "……撃っちゃったっす。"
"10028050-120-イチカ" = "……ははっ。"
"10028050-121-イチカ" = "……カッとなって、つい。ごめんっす！"
"10028050-122-イチカ" = "ん～"
"10028050-126-イチカ" = "……あははっ！"
"10028050-127" = "[ns3] \"イ、イチカ！？！？！？\"\n[ns4] \"カ、カバンが……！！\""
"10028050-130-イチカ" = "ははっ、そうっすね……落ちちゃったっす！"
"10028050-131-イチカ" = "でもまあ……"
"10028050-132-イチカ" = "やっちゃったもんは仕方ないっす。中身は後で確認しましょうか。"
"10028050-133-イチカ" = "けど……終わりっすね、たぶん。"
"10028050-134-イチカ" = "ま、こうなったからには……"
"10028050-135-イチカ" = "私だけってのもアレなんで。"
"10028050-145-イチカ" = "……全員で地獄に行くっすよ。"
"10028050-154-イチカ" = "あはっ……あはは……！アハハハハハハハッ！！！！"
"10028050-155-ヘルメット団" = "な、何だアイツ……！#n……う、うわぁあああ！！"
"10028050-156-風紀委員" = "だ、誰か止めろ！！"
"10028050-157-スケバン" = "ぎゃぁぁあっ！！！イカレてる！！！！！"
