[translation]
"10030070-1" = "第7話;初めての景色"
"10030070-5-マキ" = "ん……ううっ……"
"10030070-9-チヒロ" = "マキ、そろそろ起きて。"
"10030070-10-チヒロ" = "今日は早起きして、みんなで初日の出を見るって言ったでしょ。"
"10030070-16-マキ" = "……あと10分……だめ……？"
"10030070-17-チヒロ" = "ダメ、今から出発してもギリギリだから。"
"10030070-18-チヒロ" = "早く起きて支度して。身体を冷やさないように、しっかり着込んでね。"
"10030070-19-マキ" = "うん……"
"10030070-25" = "[ns1] \"おはよう、マキ。\"\n[ns2] \"あけましておめでとう、マキ。\""
"10030070-26-マキ" = "おはよ、せんせ……"
"10030070-27-マキ" = "先生も、あけましておめでと……"
"10030070-28-マキ" = "……そういや今日って元日なんだよね。"
"10030070-29-マキ" = "いつも正月は朝に寝てたから、この時間に起きてるのが変な感じで……"
"10030070-30-マキ" = "あれ、そもそも今まで早寝早起きしてこなかったかも……"
"10030070-36-ハレ" = "マキも起きたんだ。"
"10030070-37-コタマ" = "おはようございます、先生。"
"10030070-38" = "[s] \"おはよう。ハレ、コタマ。\""
"10030070-39-ハレ" = "ふあぁ……ねむい……"
"10030070-40-ハレ" = "こういうときこそ、高カフェインのエナドリを一気飲みしたくなるのに……"
"10030070-41-コタマ" = "私も、今はエナドリの気分です……"
"10030070-46-チヒロ" = "エナジードリンクは無いけど、コーヒーなら下で淹れてきたのがあるよ。"
"10030070-50-チヒロ" = "はい、これ。食欲は無いかもしれないけど、チョコバーくらい食べておいて。#n山登りはエネルギーを消耗するから。"
"10030070-51-チヒロ" = "それと、もし体調に違和感があったらすぐに言って。いいね？"
"10030070-56-一同" = "は～い。"
"10030070-58" = "（身支度を済ませ、初日の出を拝むまでの長い道のりが始まった）"
"10030070-63-ハレ" = "ぜぇ……ぜぇ……"
"10030070-64-コタマ" = "もう……体力の、限界が……"
"10030070-65-マキ" = "づかれたよぉ……"
"10030070-66-マキ" = "せんぱい～、山頂まで後どんくらい……？"
"10030070-71-チヒロ" = "半分くらい来たから、もうちょっと頑張ろう。"
"10030070-75-チヒロ" = "……それより、天気が怪しい。"
"10030070-76-チヒロ" = "このままじゃ、山頂に着いても初日の出が見られるか……"
"10030070-83-マキ" = "あれ？今そこの草むらが揺れなかった？"
"10030070-84-コタマ" = "ま、まさか昨日みたいに、クマが出てきたり……"
"10030070-85-ハレ" = "ひっ……"
"10030070-101-スミレ" = "あれ、またヴェリタスの皆さん、それにトレーナー……"
"10030070-108-マキ" = "あ、スミレ先輩！やっほ～！"
"10030070-110-スミレ" = "おはようございます、またお会いできるとは思っていませんでした。"
"10030070-111-スミレ" = "皆さん、あけましておめでとうございます。"
"10030070-112" = "[s] \"スミレ、あけましておめでとう。\""
"10030070-114" = "[ns] \"昨日はよく眠れた？\""
"10030070-118-スミレ" = "いえ……久しぶりの野外合宿で興奮しているのか、あまり眠れませんでした。"
"10030070-119-スミレ" = "それで身体の緊張をほぐすために、朝の軽い運動にトレイルランニングを行なっていたのです。"
"10030070-120-スミレ" = "少し身体を動かしたおかげで、調子が戻ってきた気がします。"
"10030070-121-レイ" = "「少し」どころじゃなかったですけどね！？"
"10030070-122-レイ" = "昨日の疲れが取れてすらないのに、未舗装の道をひたすら全力疾走……！"
"10030070-123-レイ" = "スミレ先輩の体力は、一体どうなってるんですか！？"
"10030070-124-スミレ" = "ふふっ、身体は使えば使うほど強くなると言いますから。"
"10030070-125-スミレ" = "レイさんも一緒にトレーニングを続ければ、来シーズンの二打席連続ホームランも夢じゃないはず。"
"10030070-129-レイ" = "……二打席連続ホームランのためなら、仕方ない……のかな？"
"10030070-130-スミレ" = "それにしても皆さん揃って、こんな朝早くから登山とは。"
"10030070-131-スミレ" = "……もしかして、今年は心機一転、運動を始めたのですか？"
"10030070-133-ハレ" = "始めたというか……"
"10030070-134-コタマ" = "副部長の誘いで、初日の出を見るために山頂を目指しているところです。"
"10030070-136-スミレ" = "なるほど、初日の出ですか……"
"10030070-140-スミレ" = "残念ですが、今回の日の出は諦めた方がいいかもしれません。"
"10030070-144-マキ" = "なんでっ！？"
"10030070-145-スミレ" = "まだ日は昇っていませんが、今もかなり雲が多いので。"
"10030070-146-スミレ" = "このような天気では日が昇っても、完全な日の出は鑑賞できない可能性が高いかと……"
"10030070-147-スミレ" = "楽しみにしてここまで来たのに、がっかりする羽目になるかもしれません。"
"10030070-149-チヒロ" = "天気予報では晴れると言ってたけど……。"
"10030070-150" = "[s] \"どうしよっか……。\""
"10030070-155-チヒロ" = "……みんな、どうする？"
"10030070-156-チヒロ" = "私が提案しておいてなんだけど、天気が伴わない以上、無理して登頂する必要はないからね。"
"10030070-165-ハレ" = "……登山を続ける。"
"10030070-166-チヒロ" = "そうだね。そう言うと思っ……"
"10030070-170-チヒロ" = "……え？続ける？"
"10030070-171-ハレ" = "んーせっかく外に出たしね。"
"10030070-173-コタマ" = "ここまで来たのですから、登頂できずに帰る方が気になってしまいそうです。"
"10030070-174-マキ" = "周回プレイは好きじゃないけど……"
"10030070-175-マキ" = "ボス戦の前に、コントローラーを投げ出すわけにはいかない！"
"10030070-177-チヒロ" = "でも頂上までにあと半分はあるけど……"
"10030070-178-チヒロ" = "あんた達……成果の出ない作業は嫌いじゃなかった？"
"10030070-180-マキ" = "ま、たしかに山頂まで登ったのに初日の出が見られなかったら残念だけど……"
"10030070-181-コタマ" = "日の出なら、部室に帰ってからモニターで見られますからね。"
"10030070-182-ハレ" = "でも、山頂まで登る道のりは自分でしか味わえないから。"
"10030070-188-チヒロ" = "……今年の初日の出は、西から昇るかもしれないね。"
"10030070-189-スミレ" = "素晴らしい心意気です！"
"10030070-190-スミレ" = "皆さん見落としがちですが、トレーニングの真の価値は美しい肉体を作ることよりも、そこに至るまでの過程にありますから！"
"10030070-191-スミレ" = "登山もそうです。山頂までの道のりにこそ、真の価値があるはず！"
"10030070-193-スミレ" = "私も強く共感しました！トレーニング部も、ぜひ山頂までご一緒させてください！"
"10030070-194-スミレ" = "レイさん！ではこれより、山頂までの道を全力疾走します！"
"10030070-198-レイ" = "えっ！？先輩、今日のトレーニングは中腹で行うって言ってたじゃないですか！？"
"10030070-206-レイ" = "そんなぁ――！"
"10030070-211-チヒロ" = "それじゃ、みんなで山頂まで頑張ろっか？"
"10030070-212-チヒロ" = "もうあまり時間も無いし、急ごう。"
"10030070-228-チヒロ" = "……着いた。"
"10030070-229-チヒロ" = "ここ[ruby=ひがしだけさん]が東丈山の[/ruby]頂上。"
"10030070-233-マキ" = "わっ！風がすごい！"
"10030070-234-コタマ" = "開けた場所だからか、さっきよりも寒いですね……"
"10030070-235-ハレ" = "雲のせいかな。よく見えない……"
"10030070-238-スミレ" = "そうですね、あまり見えません……"
"10030070-242-レイ" = "あっ……明るくなってきましたよ。"
"10030070-243-マキ" = "そろそろかな？"
"10030070-253-一同" = "あ……！"
"10030070-254-ハレ" = "……きれい。"
"10030070-255-レイ" = "一瞬で空が、陽の光でいっぱいに……"
"10030070-256-マキ" = "映像では何度も見たけど、やっぱり自分の目で見ると違う……"
"10030070-257-コタマ" = "きれいで……そして、まぶしくて。"
"10030070-258-ハレ" = "……すごく温かい。"
"10030070-262-スミレ" = "苦労の先に見る景色は、何事にも代えがたい刺激となるものです。"
"10030070-263-チヒロ" = "……やっぱり、見にきて良かったんじゃない？"
"10030070-268-ハレ" = "……うん。"
"10030070-269-ハレ" = "……ありがとう、先輩。"
"10030070-270-マキ" = "最初は初日の出のためだけにキャンプなんて、正直面倒だったけど……"
"10030070-271-コタマ" = "今は副部長が私たちを連れてきた理由も、何となく分かった気がします。"
"10030070-273-チヒロ" = "そう思ってもらえたなら、私も嬉しいよ。"
"10030070-277-チヒロ" = "……世の中には、実際に体験してみないと実感できないことがたくさんあるから。"
"10030070-283-マキ" = "今の音って……"
"10030070-288-スミレ" = "レイさん、もしかしてお腹が空いたんですか？"
"10030070-289-レイ" = "え、えっと……その……"
"10030070-290-レイ" = "仕方ないじゃないですか！#n朝早くから走ってたので！"
"10030070-292-チヒロ" = "それじゃ、キャンプに戻ってみんなでごはんにしない？"
"10030070-293-チヒロ" = "朝ごはん用にパンを持ってきたんだ。"
"10030070-298" = "[ns] \"ジャムとバターもあるよ。\""
"10030070-300-マキ" = "あっ、あたしはそれでパンに何か描いて食べよーっと！"
"10030070-301-コタマ" = "私は一切れで大丈夫です。"
"10030070-302-ハレ" = "パンもいいけどコーヒーが飲みたい……"
"10030070-305-スミレ" = "プロテインのお供に良さそうですね。"
"10030070-306-チヒロ" = "ふふ、そうだね。みんな好きなように食べよう。"
