[translation]
"10030075-18-ハレ" = "……あれ、何の音だろう。"
"10030075-19-マキ" = "初日の出を見てる間に、いっぱいテントが増えてるね。"
"10030075-20-コタマ" = "この数時間で、キャンプブームでも起きたのでしょうか……？"
"10030075-21" = "[s] \"どうだろうね……？\""
"10030075-26-マイ" = "クロノスチャンネルをご覧の皆さん、こんにちは！緊急編成でお送りします。「キヴォトスドラマチック」の進行を務める[ruby=かざまき]、風巻マ[/ruby]イです！"
"10030075-27-マイ" = "本日、私たちはここに新たな遺跡が発見されたとの報告を受け、取材に参りました！"
"10030075-28-マイ" = "すでにSNSで噂が広まり、元旦にもかかわらず山の麓には遺跡目当ての方が押し寄せています！"
"10030075-29-マイ" = "果たして今回発見された遺跡は、キヴォトスの考古学にどのような影響を与えるでしょうか！これより、私たちは――"
"10030075-33-マイ" = "おや？あちらに見えるのは……！"
"10030075-34-マイ" = "視聴者の皆さん！#n今まさに、キヴォトスで最も熱いあの方――「[USERNAME]先生」の姿を捉えました！"
"10030075-35-マイ" = "早速、シャーレの先生にインタビューを行ないたいと思います！"
"10030075-39-マイ" = "こんにちは、[USERNAME]先生！クロノスチャンネルです！"
"10030075-40" = "[s1] \"あけましておめでとうございます。\"\n[s2] \"今年もよろしくね、マイ。\""
"10030075-43-マイ" = "あけましておめでとうございます！#n新年早々こんな特ダネを……"
"10030075-44-マイ" = "……いえ、先生にお会いできて嬉しい限りです！"
"10030075-45-マイ" = "まさか[USERNAME]先生もいらっしゃるとは思いませんでした。"
"10030075-46-マイ" = "やはり今回発見された遺跡には、それほどの価値があると！"
"10030075-47" = "[s3] \"……新しい遺跡？\"\n[s4] \"何の話をしてるのか、よく分からないんだけど……\""
"10030075-50-マイ" = "あれ、ご存じないんですか？"
"10030075-51-マイ" = "ここの洞窟で、壁画が発見されたとのニュースがSNSでものすごい話題になっているのですが……"
"10030075-58-マイ" = "今まで発見されてきた採取や狩猟の様子とは異なり、何でも大きな塔や機械のようなオーパーツがいくつも描かれているのだとか！"
"10030075-62-マイ" = "それに、なんと塔の上に凶暴な怪物のようなものまで……"
"10030075-63-マイ" = "この絵を発見した方たちは、「終末の預言」だと騒ぎを起こし、D.U.でひと悶着があったそうです。"
"10030075-65-マイ" = "そこでなのですが……シャーレの先生はどうお考えでしょうか？"
"10030075-69" = "[ns] \"……マキ。\""
"10030075-73-マキ" = "あ、あ、あたしのせいじゃないよ！？"
"10030075-74-マキ" = "いや……壁画を描いたのはあたし、だけど……"
"10030075-75-チヒロ" = "昨日、キャンプ場に戻る前に綺麗にしておくよう言ったでしょ……"
"10030075-76-マキ" = "あ、あのときはコタマ先輩を探さなきゃと思って、ついうっかり……"
"10030075-77-マキ" = "というか、よくよく考えたらさ……"
"10030075-81-マキ" = "それだけあたしの絵がすごかったってことだよね！？"
"10030075-88-チヒロ" = "ちょっとは反省しなさい！！"
"10030075-90" = "（その後、集まっていた人たちに事情を説明するのは一苦労した……）"
