[translation]
"10030040-1" = "第4話;ダンス・ウィズ・ベア"
"10030040-3-コタマ" = "ふぅ……ここまで来れば大丈夫でしょう。"
"10030040-7-コタマ" = "では、そろそろ録音機の準備を……"
"10030040-11-コタマ" = "出発前に持ち物検査がありましたけど、まさか靴に小型録音機を仕込んでいるとは副部長も思わないでしょう。"
"10030040-12-コタマ" = "音質や感度は劣りますが、いくらでも小型化できるのが録音機の良いところですね……ふふっ。"
"10030040-13-コタマ" = "……先生と過ごす貴重な時間を、録音しないなんて選択肢、ありませんから。"
"10030040-21-コタマ" = "マイクの感度とノイズ抑制のセッティング完了。"
"10030040-22-コタマ" = "調整も終わりましたし、まずは環境音でも録ってみましょうか。"
"10030040-28-コタマ" = "音源でしか聞いたことのない自然の音を自分の耳で聞くのは、なんだか新鮮です……"
"10030040-33-コタマ" = "風が木々を通り抜ける音……"
"10030040-38-コタマ" = "草木が揺れる音や鳥のさえずり……"
"10030040-41-？？？" = "ぐおおお……"
"10030040-42-コタマ" = "ケモノの鳴き声……"
"10030040-47-コタマ" = "……ケモノの鳴き声？"
"10030040-52-？？？" = "ぅぉおおおっ――！"
"10030040-58-コタマ" = "ひ、ひぃっ……！？"
"10030040-62" = "[ns] \"……あっちからコタマの悲鳴が聞こえた！\""
"10030040-68-マキ" = "コタマ先輩、大丈夫！？"
"10030040-69-コタマ" = "え、えっと、あそこから……"
"10030040-70-マキ" = "あっち……？あっちで何が……？"
"10030040-75-コタマ" = "凶暴な、ケモノの声が聞こえました……！"
"10030040-80-チヒロ" = "ケモノ……？"
"10030040-83" = "[ns] \"まさか、あの影が……\""
"10030040-88-？？？" = "おおおおおっっ……！"
"10030040-94-スミレ" = "さあ！もっとお腹に力を入れて、大きな声で！"
"10030040-95-？？？" = "ううっ……"
"10030040-100-レイ" = "も、もう十分じゃないですか！？#n応援の時でも、ここまでの声を出したことないですよ！？"
"10030040-101-レイ" = "喉が痛いんですけど……"
"10030040-102-レイ" = "そもそも、声を出すのと野球に何の関係があるんですか！？"
"10030040-103-スミレ" = "いいえ、レイさん。"
"10030040-107-スミレ" = "大きな声を上げるには、十分な肺活量が必要です。"
"10030040-109-スミレ" = "そして、どんな運動にも優れた肺活量は必要不可欠！#n野球も例外ではありません！"
"10030040-110-スミレ" = "来シーズンではもっと良い成績を上げられるよう、今から心肺能力を鍛えていきましょう！"
"10030040-112-レイ" = "何度も言いましたけど、私は長打を打てるような筋力が欲しいのであって、心肺能力を鍛えたいわけじゃないんですって！"
"10030040-113-レイ" = "うっ……先輩たちが#n「トレーニング部に行けばもっとホームランが打てるようになる」って言ってたけど、信じなければ良かった……！"
"10030040-114-レイ" = "というか！こんな山奥まで来る必要ありませんでしたよね！？"
"10030040-115-レイ" = "今の時期、野生動物は冬眠してるはずですけど、もしクマが目を覚ましてしまったら……"
"10030040-116-スミレ" = "そのような些末な問題で、大切なトレーニングを中断するわけにはいきません。"
"10030040-117-スミレ" = "レイさんの野球にかける情熱は、その程度だったのですか？"
"10030040-118-レイ" = "それとこれは関係ないですよね！"
"10030040-119" = "[ns] \"……凶暴なケモノではなさそうだね。\""
"10030040-123-スミレ" = "あれ？トレーナー……それにヴェリタスの皆さんまで。"
"10030040-125-チヒロ" = "久しぶり、スミレ部長。"
"10030040-126-チヒロ" = "えっと……そちらは初めましてだよね？トレーニング部の新しい部員？"
"10030040-128-スミレ" = "はい、体験入部ではありますが。"
"10030040-130-マキ" = "あ、レイちゃんだ。"
"10030040-131-コタマ" = "良かった……ケモノではなく、レイの声だったのですね。"
"10030040-132-レイ" = "ヴェリタス……？こんなところで会えるなんて思ってなかった。"
"10030040-133" = "[s] \"みんなの知り合い？\""
"10030040-134-コタマ" = "はい、レイはミレニアム野球部のエースで4番です。"
"10030040-135-マキ" = "試合に出るたびにミレニアムの校内スポーツ掲示板を沸かせてるし、ミレニアム生で知らない人は居ないかな？"
"10030040-136-レイ" = "へへっ……そこまで言われると照れるなぁ。"
"10030040-137-コタマ" = "前シーズンは逆の意味で沸かせていましたが……"
"10030040-141-レイ" = "えっと……た、たしかに打率は低かったですけど……"
"10030040-142-レイ" = "今回の特訓を終えたら、来シーズンではサイクルヒットも夢じゃありません！"
"10030040-144-マキ" = "こんな寒い時期に特訓……すごい情熱だね。"
"10030040-145-コタマ" = "体育会系の考え方は、やはり私には合わなそうです……"
"10030040-147-レイ" = "というか、ヴェリタスの皆さんはこんな山奥で一体何を……？"
"10030040-148-レイ" = "普段は部室からもほとんど出てないですよね……？"
"10030040-150-チヒロ" = "私たちは初日の出を見ようと思って、キャンプに来たんだけど……"
"10030040-151-マキ" = "コタマ先輩が森に用事があるって言ってたから。"
"10030040-152-チヒロ" = "……もしかして、森で危ないことをしてたんじゃないんでしょうね？"
"10030040-157-コタマ" = "ち、違います！"
"10030040-158-コタマ" = "ただ録音機のテストついでに、環境音を録ろうと……"
"10030040-162-コタマ" = "……あ。"
"10030040-163-チヒロ" = "はぁ……隠し持ってるだろうなとは思ってたけど……"
"10030040-167-チヒロ" = "はい、出して。それは先生のプライバシーに関わるからダメ。"
"10030040-168-コタマ" = "うっ……冬の山を舞台にした[USERNAME]先生の新しいレコードを作るチャンスだったのに……"
"10030040-169" = "[s1] （新しいレコード……？）\n[s2] （何か怖い話が聞こえたような……）"
"10030040-173-スミレ" = "それにしても、部員みんなでキャンプだなんて、素晴らしい休日ですね。"
"10030040-174-スミレ" = "せっかくですし、お互い美しい大自然を堪能していきましょう。"
"10030040-176-マキ" = "はぁ……自然なんて屋内からでも楽しめると思うんだけどなぁ……"
"10030040-177-コタマ" = "そうです。立体音響対応のスピーカーを使えば、室内でも外の音をリアルに感じられますから。"
"10030040-178-マキ" = "部室からでも見られるんだから、外に出なくてもさぁ……"
"10030040-180-レイ" = "でも、外に居るからこそ楽しめるものだって、あると思いません？"
"10030040-181-レイ" = "早朝の冷たい風に耐えながら、山頂で迎える陽の光とか……"
"10030040-182-マキ" = "そういうのだって屋内で再現できるよ？"
"10030040-183-マキ" = "クーラーガンガンの部室で毛布にくるまって、登山ドキュメンタリーを観れば完璧じゃん？"
"10030040-184-コタマ" = "そこで食べるカップ麵も外せません。"
"10030040-185-レイ" = "う、うーん、そういうのとはちょっと違うというか……"
"10030040-190-スミレ" = "たしかに最近は、直接足を運べないような場所の風景も部屋で手軽に楽しめるような時代になりました。"
"10030040-191-スミレ" = "椅子を動かす必要もなく、いつだって好きなときに夕日を鑑賞できるようになったのです。"
"10030040-192-スミレ" = "しかし……自分の目で山頂から見る景色は、味わってみなければ分からないと思います。"
"10030040-193-マキ" = "え～？見てる場所が違うだけで、景色は同じでしょ？"
"10030040-194-スミレ" = "部屋で見る景色には、たどり着くまでの過程が含まれていませんから。"
"10030040-195-スミレ" = "運動においても言えますが、苦労せず手に入れた能力は簡単に失ってしまうものです。"
"10030040-196-スミレ" = "ゲームで例えると……チートで敵を倒したようなものでしょうか。"
"10030040-197-マキ" = "うーん……ちょっとは分かるような……"
"10030040-198-マキ" = "けど、その一瞬の景色のためにしんどい思いするのはやだなぁ。"
"10030040-199-コタマ" = "わざわざ無理しなくても、屋内には楽しいことがたくさんあります。"
"10030040-200-スミレ" = "たしかに……屋内には便利なものが多いです。"
"10030040-201-スミレ" = "ですが時には、休息が成長に繋がる場合もありますから。"
"10030040-202-スミレ" = "なので今回の特訓は、負荷の大きい筋トレではなく、軽めの有酸素運動を中心にメニューを組んでみました。"
"10030040-203-レイ" = "スミレ先輩の特訓に「軽め」なんて言葉ないですからね！？"
"10030040-216-チヒロ" = "話が盛り上がってるところ悪いんだけど、ここであまり騒がないほうがいいんじゃないかな……"
"10030040-217-チヒロ" = "近くでクマが出るって噂だし……起こしちゃったりしたら――"
"10030040-229-チヒロ" = "……あ。"
"10030040-230-マキ" = "……あ。"
"10030040-239-とても粗暴な熊" = "ぐおおおおお！"
"10030040-244" = "[ns] \"……く、クマだっ！！\""
"10030040-245-レイ" = "だから言ったじゃないですか、先輩！ここで騒いだらクマが出るって！"
"10030040-246-スミレ" = "……これは良い機会ですね。"
"10030040-250-スミレ" = "レイさん。あのクマを内野手に見立てて、走塁の訓練をするのはいかがでしょうか？"
"10030040-251-スミレ" = "全力で追いかけてくる相手から、タッチされないように逃げ切るのです！"
"10030040-253-マキ" = "それ、いいんじゃない？クマにタッチされたら、色んな意味でアウトだろうし。"
"10030040-254-チヒロ" = "冗談言ってる場合！？"
"10030040-260-とても粗暴な熊" = "ぐおおおおおっ！！"
"10030040-261-スミレ" = "さあレイさん、ラン・アンド・ヒットです！集中してください！"
"10030040-262-レイ" = "今回ばかりは本当に訓練って言ってる場合じゃないですよ！"
