[translation]
"101080-1" = "第8話;光の到来"
"101080-3-セリカ" = "シロコ先輩、早く！"
"101080-4-ホシノ" = "シロコちゃ～ん、早く出発しないと遅れちゃうよ。"
"101080-5-シロコ" = "もう着く。今、最高速度で向かってる。"
"101080-6-ノノミ" = "は～い。#nでも、事故に遭ったら危ないから自転車に乗りながらの通話は禁止です。"
"101080-7-シロコ" = "ん、分かった。じゃあ後で。"
"101080-11-アヤネ" = "あはは……何度申し入れをしても音沙汰がなかった、あの連邦生徒会が……#nついに、ですね……。"
"101080-12-ホシノ" = "そうだねぇ……#n昔、あまりにも頭にきて、連邦生徒会を襲撃しようと考えたこともあったなぁ～"
"101080-13-セリカ" = "連邦生徒会を……？#nいくらホシノ先輩でも、それは無理じゃ……"
"101080-14-ホシノ" = "今はもう無理だよ～#n身体も痛いし、昔みたいに動けなくなっちゃって……おじさんが若かった頃の話ね。"
"101080-15-アヤネ" = "あはは……年の差、あまりないんですけどね……。"
"101080-19-ノノミ" = "ホシノ先輩の頃と状況が変わりましたからね。今は先生もいますし。"
"101080-20-ホシノ" = "おじさんさ～、なんだか最近昔のことを思い出すんだよ。#nシロコちゃんに初めて会った時とか、ノノミちゃんが急に訪ねて来た時とか……"
"101080-21-セリカ" = "急に何言い出すのよ。本当に年寄りみたいな事を……。 "
"101080-22-アヤネ" = "シロコ先輩と初めて会った時、ですか？#n私、その話初めて聞きます。どんな感じだったんですか？"
"101080-23-ホシノ" = "あれ、話したことなかったっけ？"
"101080-24-ホシノ" = "シロコちゃん、初めて会った時は完全に野良猫みたいな感じでさ～#nノノミちゃんとおじさんで、シロコちゃんを捕獲するのにどれだけ苦労したことか……"
"101080-25-セリカ" = "なんで捕獲なのよ……"
"101080-27-ノノミ" = "ホシノ先輩、この話は……"
"101080-28-ホシノ" = "別に隠す必要もないんじゃない？"
"101080-33-ノノミ" = "そうですが……#nその……シロコちゃん、アビドスに来る前の記憶が無いんです。"
"101080-34-アヤネ" = "えっ？記憶喪失？"
"101080-35-セリカ" = "何それ、映画みたいな話じゃん！？"
"101080-36-ノノミ" = "それは……"
"101080-37-シロコ" = "……何か、ヘン。"
"101080-38-セリカ" = "えっ……？ "
"101080-39-アヤネ" = "シロコ先輩……？"
"101080-46-シロコ" = "……今まで見たことないくらい、PMCがたくさんいる。"
"101080-47-シロコ" = "トラックにタンク、兵士……みんな同じ方角に向かってる。"
"101080-48-シロコ" = "あっちは……アビドス砂漠……"
"101080-50-シロコ" = "……ちょっと、見に行ってくる。"
"101080-51-アヤネ" = "し、シロコ先輩……！？"
"101080-52-セリカ" = "なっ、何言ってんの！一人じゃ危ないでしょ！"
"101080-53-ホシノ" = "……シロコちゃん、危ないから帰っておいで。 "
"101080-54-シロコ" = "ん、危険なことはしない。遠くからちょっと見てくるだけ。すぐ戻る。"
"101080-55-シロコ" = "もしかしたら……今のこの状況は、先生が私たちを呼んだ事と、関係あるのかも。"
"101080-56-アヤネ" = "せ、先輩……"
"101080-57-シロコ" = "……ん？今、地面が…………地震……？ "
"101080-58-シロコ" = "……不思議な光が見える……黒……いや、虹……？"
"101080-60-ホシノ" = "……！！"
"101080-68-アヤネ" = "……！！？"
"101080-71" = "[ns] \"…………！！！\""
"101080-72-PMC兵士A" = "……ん？"
"101080-73-PMC兵士B" = "何をモタモタしてるんだ、その距離すら当てられないのか？"
"101080-74-PMC兵士A" = "あ、あれ……？#n銃身が……曲がった……？"
"101080-76-PMC兵士A" = "クソッ！こうして銃口を直接当てちまえば……"
"101080-81-PMC兵士A" = "……は、発射不良？#nい、一体どういうことだ！？"
"101080-82-PMC兵士B" = "このバカ！私がやる！"
"101080-83-PMC兵士A" = "ま、待て！#n殺すのはダメだって、ジェネラルから……"
"101080-87-PMC兵士A" = "……。"
"101080-88-PMC兵士B" = "……。"
"101080-89" = "[ns] \"…………。\""
"101080-90-PMC兵士A" = "あ、ありえない。どうして一発も……？#nい、一体何が……！？"
"101080-92-アロナ" = "私がいる限り、先生を傷つけることはできません！"
"101080-93-アロナ" = "先生の安全は、この私――#nシッテムの箱のOSであるスーパーアロナが守ってますから！"
"101080-94-アロナ" = "先生！この隙に早く……！！"
"101080-102-アロナ" = "……え？"
"101080-109-アロナ" = "これは……"
"101080-110-アロナ" = "何かが……近づいてきます……"
"101080-120-PMC兵士A" = "な、何だ今のは……！？"
"101080-121-PMC兵士B" = "地震か……？"
"101080-124" = "[ns1] （シッテムの箱の電源が……？）\n[ns2] （アロナ……！？）"
"101080-127" = "[ns] （あ、頭が……）"
"101080-130-PMC兵士A" = "ちっ……とにかく逃げられないようにすればいいんだろ。#nその辺に転がしておけ。"
"101080-131-PMC兵士A" = "急いで目標地点に移送するぞ。"
"101080-133-アヤネ" = "……！！"
"101080-134-ノノミ" = "こ、ここからでも感じられます！"
"101080-135-シロコ" = "これは……この色……"
"101080-136-ホシノ" = "シロコちゃん！！#n危ないから早く帰っておいで！"
"101080-144-ノノミ" = "シロコちゃん、電話に出てください……シロコちゃん！"
"101080-145-ホシノ" = "……。"
"101080-146-ノノミ" = "……ダメです、出ません……。"
"101080-147-セリカ" = "ちょっと……シロコ先輩一体何してるのよ！！"
"101080-148-アヤネ" = "あ……あう……えっと、こういう時、一体どうすれば……。"
"101080-149-ノノミ" = "……アヤネちゃんは先生に連絡してください！助けを求めましょう！"
"101080-150-アヤネ" = "は、はい……！#n先生に連絡、先生に……。"
"101080-155-アヤネ" = "ダメです、先生も……連絡が、取れません……。"
"101080-156-ホシノ" = "……。"
"101080-157-セリカ" = "せ、先生まで……！？#nど、どうして……"
"101080-161-ノノミ" = "あっ、出た……！？#nし、シロコちゃん、どこにいるんですか？"
"101080-162-アヤネ" = "シロコ先輩！？"
"101080-163-セリカ" = "先輩、聞こえてるなら答えて！#nねえ、大丈夫なの！？一体どうしたの！？"
"101080-164-ノノミ" = "シロコちゃん？答えてくださいシロコちゃん、いったい何が……！"
"101080-168-セリカ" = "また、切れた……？"
"101080-169-ノノミ" = "…………し、"
"101080-170-ノノミ" = "シロコちゃん――！！"
"101080-174" = "次回;衝突（１）"
