[translation]
"101030-1" = "第3話;日常の亀裂（１）"
"101030-2" = "アビドス砂漠・発掘区域"
"101030-5-PMC兵士" = "み、見つかりました！"
"101030-6-PMC幹部" = "見つかったのか？"
"101030-7-PMC兵士" = "は、はい！例の座標から、約135m×23m×13mの構造体を発見しました……！！ "
"101030-8-PMC幹部" = "間違いない……！至急、ジェネラルに報告せよ！大至急だ！"
"101030-9-PMC兵士" = "は、はい！！"
"101030-10-PMC幹部" = "あと、連邦生徒会の防衛室にも連絡しておけ。#nそちらは専用の通信網でな。"
"101030-11-PMC兵士" = "はい！"
"101030-16" = "アビドス市街地"
"101030-17-シロコ" = "……。"
"101030-23-PMC兵士A" = "急げ、移動するぞ！"
"101030-24-PMC兵士B" = "はっ！"
"101030-29-シロコ" = "カイザーPMC……。"
"101030-35-ホシノ" = "PMCの兵力が、砂漠の方に移動してた？"
"101030-36-シロコ" = "ん。今までとは全然規模が違った。 "
"101030-37-ホシノ" = "ふ～ん、何かあったのかな？#nあいつら最近静かだったのにね。"
"101030-38-アヤネ" = "ここ数日、あちこちでカイザーPMCが移動しているのを見ました……。"
"101030-39-セリカ" = "あいつら、他人の自治区で好き勝手して！ほんと許せない。"
"101030-40-ノノミ" = "アビドス砂漠で何かあったのでしょうか？"
"101030-41-シロコ" = "こっそり見に行ってみる？"
"101030-42-ノノミ" = "シロコちゃん、それはちょっと……"
"101030-43-ホシノ" = "あそこはカイザーの土地だから、勝手に行ったら怒られちゃうよ～。#n前もそれで揉めたじゃん？"
"101030-44-シロコ" = "ん……。"
"101030-45-ノノミ" = "そうだ、先生に相談してみましょう！"
"101030-49-アヤネ" = "そうしたいのはやまやまですが……最近、お忙しいみたいで……#n連絡したら、迷惑をかけてしまわないでしょうか？"
"101030-50-セリカ" = "迷惑かどうかは先生が決める事じゃないの？"
"101030-51-ノノミ" = "そうですよアヤネちゃん。連絡する前から決めてしまっては、先生も何もできませんし……それに、先生ならきっと手伝ってくれます☆"
"101030-52-シロコ" = "ん。それに、この間先生から連絡きたばっかだし。"
"101030-53-アヤネ" = "先生からですか？先輩に？"
"101030-54-セリカ" = "シロコ先輩がスタンプ爆撃でもしたからじゃないの？"
"101030-55-シロコ" = "いや、今回は違う。#n先生の方から。"
"101030-56-ホシノ" = "そりゃシロコちゃんだってスタ爆ばっかじゃないでしょ～"
"101030-60-セリカ" = "もう、先輩がそうやっていつも甘やかすから！"
"101030-61-ホシノ" = "うーん……そうかなぁ～？"
"101030-62-シロコ" = "んー……。"
"101030-63-ノノミ" = "まぁまぁ、シロコちゃんはそういう所が可愛いんですから☆"
"101030-64-アヤネ" = "あはは……それで、先生は何と？"
"101030-65-シロコ" = "特に何も……。#nただ、最近元気？とか、無事？とか……そんな感じの内容。"
"101030-66-ホシノ" = "へぇ……それはそれで、なんだか素っ気ないねぇ。"
"101030-67-アヤネ" = "とりあえず、私が先生に連絡してみますね。#n一度アビドスに来ていただけないか、と。"
"101030-68-ノノミ" = "そうですね☆アヤネちゃん、お願いします！"
"101030-73" = "ミレニアム・ゲーム開発部部室"
"101030-75-ミドリ" = "お姉ちゃん、これはダメだよ。"
"101030-76-モモイ" = "え、なんで！？"
"101030-77-ミドリ" = "私たちが作ってるのは「剣と魔法のRPG」でしょ？"
"101030-78-モモイ" = "そうだけど……それがどうしたの？"
"101030-79-ミドリ" = "どうしたの？じゃないよ……なんで主人公が宇宙戦艦に乗ってるの？"
"101030-80-モモイ" = "敵が宇宙海賊だからね！それなら主人公は宇宙戦艦に乗らないと！"
"101030-81-ミドリ" = "勇者が宇宙戦艦に乗ってどうするのさ……"
"101030-83-モモイ" = "なんで！宇宙勇者だよ！？良いじゃん！ "
"101030-87-モモイ" = "ユズはどう思う？"
"101030-88-ユズ" = "わ、わたしは……悪く、ないと思う……#n最近流行ってるダダイスムみたいな感じで……。"
"101030-89-モモイ" = "ほら！ユズもこれはイケるって！"
"101030-90-ミドリ" = "ええ……。"
"101030-95-アリス" = "「宇宙勇者」は素晴らしいと思います！"
"101030-96-ミドリ" = "アリスちゃん？"
"101030-97-モモイ" = "アリス！おかえり！大丈夫だった！？"
"101030-98-ユズ" = "エンジニア部はなんて……？"
"101030-99-アリス" = "簡単な身体検査とメディカルチェックをしましたが、特に異常はなかったそうです。"
"101030-100-アリス" = "それと、ヴェリタスのみなさんが、定期的に検査をしようと仰ってくださったので、そうすることになりました。"
"101030-101-ユズ" = "そ、そうなんだ……じゃあアリスちゃんは、もう大丈夫なんだね？"
"101030-102-モモイ" = "あの時の変なヤツ……何だっけ、ケイ……だっけ？#nあいつは？"
"101030-103-ミドリ" = "ケイじゃなくて「[ruby=キー]＜Key＞[/ruby]」じゃないかな、お姉ちゃん……。"
"101030-104-モモイ" = "名前なんて分かればなんでもいいよ！"
"101030-105-アリス" = "はい。「ケイ」は発見できませんでした。 "
"101030-106-ミドリ" = "結局「ケイ」でいくの？#n……まあ、いっか。"
"101030-107-アリス" = "今のエンジニア部の技術では「ケイ」が消えたのかどうか確認できないようです。#nなので、ヴェリタスと協力してみるそうです！"
"101030-109-ユズ" = "そっか……。"
"101030-110-モモイ" = "あいつ、アリスを勝手に王女だか何かにしようとして！も～！#n次会ったらタダじゃおかないんだから！"
"101030-111-ミドリ" = "アリスちゃんは、いいの……？"
"101030-112-アリス" = "はい、アリスは問題ありません。#n今度「ケイ」に会ったら300%……いや10万%ビーム砲を発射します！"
"101030-116-アリス" = "あと、アリスも宇宙勇者は素晴らしいと思います。#n宇宙戦艦に乗る勇者パーティー！素敵です！"
"101030-117-モモイ" = "でしょでしょ？こう、胸に響くものがあるよね。#nなんたって、宇宙戦艦はロマンだから！"
"101030-118-アリス" = "アリスもいつか、宇宙戦艦に乗ることができるでしょうか？"
"101030-119-ミドリ" = "そ、それはちょっと無理じゃないかな……。"
"101030-120-モモイ" = "えっ？でもなんかエンジニア部がそういうの作ってなかった？#nアリスのレールガンもその一つだったよね？"
"101030-121-ユズ" = "今の技術では、難しいよ……ロマンだから、みんな挑戦してるんだし……。"
"101030-122-モモイ" = "そうなの！？"
"101030-123-アリス" = "不可能に挑戦するのは素晴らしいです！#nそれが、ロマンなんですね！アリスは理解しました。"
"101030-124-モモイ" = "よし！そういうわけで、次回作は宇宙勇者パーティーのスペースオペラもので決まりっ！"
"101030-125-アリス" = "はい！素晴らしいです！"
"101030-126-ユズ" = "じゃ、じゃあ、ジャンルも弾幕シューティングに変えよっか……。#nすっごいハードな難易度で、コンティニューもスペシャルボムも無い――"
"101030-132-ミドリ" = "はぁ……やっぱりこうなっちゃった。"
"101030-135-Key" = "……。"
"101030-136-Key" = "「ケイ」……"
"101030-137-Key" = "王女よ……あなたは自分の存在理由である「王女」を否定し……#n私の存在理由である「鍵」をも否定するのですか。"
"101030-138-Key" = "存在理由を失った鍵は、もはや鍵ではない……そう呼ばれる必要もないように。"
"101030-142-ケイ" = "……分かりました。 "
"101030-143-ケイ" = "それならば、私はあなたを見守る事とします。#n王女……いえ、「アリス」。"
"101030-144-ケイ" = "しかし、誰も存在理由から逃れることはできません。#nアリス、それが私たちが迎える運命です。"
"101030-148-ケイ" = "そして然るべき時が来たら……私は――"
"101030-151" = "セミナー・執務室 "
"101030-153-ヒマリ" = "ふむ……。"
"101030-154-ヒマリ" = "――面倒事を全て私に押し付けるのですね、リオ。"
"101030-155-ヒマリ" = "「名もなき神」の遺産に手をつけた挙げ句、計画が破綻した途端、「後は頼む」――だなんて。"
"101030-156-ヒマリ" = "どのような事件を起こしたとしても、#n堂々としてこそ「ビッグシスター」の名に相応しいと思いますけど……"
"101030-157-ヒマリ" = "まあ……新雪のように高潔で、清水の如く透き通る私ですから、#nあなたのそんな我儘だって理解して差し上げましょう。"
"101030-158-ヒマリ" = "さて……あなたは、私に何を伝えたかったのでしょうか。"
"101030-159-ヒマリ" = "……。 "
"101030-160-ヒマリ" = "…………。"
"101030-161-ヒマリ" = "これは――"
"101030-162-ヒマリ" = "なるほど……仮説に推測を加えた解釈ではありますが……"
"101030-163-ヒマリ" = "これほどのデータを確保したのであれば……#nあなたのその偏執的とも言える妄想も、少しは理解できそうです。"
"101030-164-ヒマリ" = "さすがは、ビッグシスター、といったところでしょうか……"
"101030-165-ヒマリ" = "……まあ、だとしても「全知」と呼ばれる超天才病弱美少女の私の方が、優れているのですけどね。"
"101030-166-エイミ" = "それは部長が勝手に言ってるだけでしょ。"
"101030-170-ヒマリ" = "ひゃっ……！？#nエ、エイミ、いつから……"
"101030-171-エイミ" = "新雪がどうとか言ってた辺りから？"
"101030-172-ヒマリ" = "……。"
"101030-173-エイミ" = "特異現象捜査部は、元々リオ会長の直属組織でしょ。#n私もこの場所は知ってるよ。"
"101030-174-エイミ" = "それで、会長はなんて？"
"101030-175-ヒマリ" = "そうですね……重要な情報は厳重なセキュリティ下にあるので、確認に時間がかかるとは思いますが……"
"101030-176-ヒマリ" = "要約すると、「別の『特異現象』に備えろ」――と。"
"101030-177-エイミ" = "どういうこと？"
"101030-178-ヒマリ" = "――これはビッグシスターからの警告です。"
"101030-179-ヒマリ" = "近い将来――キヴォトスに未曾有の危機が訪れるでしょう。"
"101030-180-エイミ" = "……。"
"101030-182-トキ" = "――私は、何をすれば良いでしょうか？"
"101030-186-ヒマリ" = "ひゃあっ……！？い、いつから……！？"
"101030-187-エイミ" = "会長の専属メイドの……トキ……？ "
"101030-188-トキ" = "お二人がここにいらっしゃる少し前からです。#nここは隠れられる場所が多いので。"
"101030-189-エイミ" = "へえ、さすがはエージェント。全然気付かなかった。 "
"101030-190-エイミ" = "てっきり会長についていったんだと思ってたけど。"
"101030-191-トキ" = "いえ。会長は、私に「これからは自由に暮らしなさい」と残して去りました。"
"101030-192-トキ" = "ですが、何をどう自由にすればいいのか……私には分からず……"
"101030-193-トキ" = "そうして、会長と過ごしたこの場所にいたらお二人が現れたのです。"
"101030-194-ヒマリ" = "ふむ……。"
"101030-196-ヒマリ" = "元はC&Cの所属ですから、そちらに身を寄せることになったと聞きましたが……断られたのでしょうか？"
"101030-197-トキ" = "いえ、先輩方には良くしていただいております。"
"101030-198-ヒマリ" = "……？"
"101030-199-トキ" = "ですが……その、 "
"101030-200-トキ" = "……。"
"101030-201-ヒマリ" = "……なるほど。おおよその状況は理解できました。 "
"101030-203-エイミ" = "……。"
"101030-204-ヒマリ" = "意外と可愛いところがあるのですね、トキは。"
"101030-205-トキ" = "もしも……何か危機が迫っているのでしたら、私もお力になりたいです。#nそれがどのような事態であろうと。"
"101030-206-エイミ" = "……どうする、部長？"
"101030-207-ヒマリ" = "答えなど明白でしょう、エイミ？#n協力者は多ければ多いほど良いものですよ。"
"101030-208-トキ" = "……ありがとうございます。"
"101030-209-ヒマリ" = "さて、これからですが――"
"101030-210-ヒマリ" = "――まずは「シャーレ」の協力を仰ぎましょう。"
"101030-211-エイミ" = "やっぱ、そうだよね。"
"101030-212-トキ" = "……。"
"101030-214" = "次回;日常の亀裂（２）"
