[translation]
"101060-1" = "第6話;前兆"
"101060-7-？？？" = "リンちゃん、リンちゃーん。"
"101060-8-リン" = "誰が「リンちゃん」ですか。#nその呼び方は控えるようにと言ったでしょう？生徒会長。"
"101060-9-？？？" = "でも……リンちゃんはリンちゃんだもん……#nうーん、じゃあ何て呼べばいいのかな……。"
"101060-10-？？？" = "七神……様？"
"101060-11-リン" = "……。"
"101060-12-？？？" = "それか、リンさん？#nリン様？……リン殿？"
"101060-13-リン" = "……お好きなようにどうぞ。 "
"101060-14-リン" = "何でも構いません。#n私に対してそんな風に呼びかけるのは、きっと生徒会長だけですから。"
"101060-15-？？？" = "分かった、じゃあリンちゃんで！へへっ。"
"101060-16-？？？" = "……あれ～？#nもしかしてリンちゃん、今笑った？"
"101060-17-リン" = "……笑ってません。"
"101060-18-？？？" = "え～？私、見たよ？"
"101060-19-リン" = "……気のせいですよ。"
"101060-20-？？？" = "そうかなぁ？#n笑ってたと思うんだけどなぁ……。"
"101060-21-リン" = "……。"
"101060-22-リン" = "……本当に気のせいですよ。"
"101060-24-アユム" = "リン先輩……。"
"101060-25-リン" = "……！"
"101060-26" = "連邦生徒会室"
"101060-27-アユム" = "先輩、大丈夫ですか……？"
"101060-28-リン" = "アユム……？#n……すみません、少し眠っておりました。"
"101060-29-アユム" = "お疲れの所すみません。至急確認をお願いしたい事項が……"
"101060-30-リン" = "……ええ、大丈夫です。行きましょう。"
"101060-36-モモカ" = "お、リン先輩にアユム先輩。遅くまでお疲れ～。"
"101060-37-リン" = "モモカ。"
"101060-38-アユム" = "モモカちゃん……例のアレを……。"
"101060-39-モモカ" = "はーい、こっちこっち。"
"101060-45-リン" = "これは……？"
"101060-46-モモカ" = "これ、2時間前に検出したデータ。"
"101060-49-モモカ" = "キヴォトス全域で、超高濃度のエネルギー体がいくつか観測されたの。"
"101060-50-リン" = "……。"
"101060-51-モモカ" = "えーと……場所は、アビドス砂漠、D.U.近郊の廃墟化した遊園地、#nミレニアム郊外の閉鎖地域、トリニティとゲヘナの境界付近、ミレニアム近郊の新しい都市と……あと、[ruby= ・     ・     ・     ・     ・     ・     ・     ・     ・     ・     ・     ・     ・     ・ ]サンクトゥムタワーのど真ん中[/ruby]。"
"101060-53-リン" = "サンクトゥムタワーの真ん中、と言いますと…… "
"101060-54-モモカ" = "そう……私たちが今いる場所。#nここの真上。"
"101060-55-アユム" = "それを聞いて、外部カメラの映像を確認してみたのですが……#n何も見つける事ができず……。"
"101060-56-モモカ" = "そ。何も変わったところがなかったんだ。"
"101060-57-リン" = "……。"
"101060-58-モモカ" = "他の地域も一緒でね。"
"101060-59-モモカ" = "最初は超大型の台風でも来るのかと思ったんだけど、#n台風は質量を持ってないし……。"
"101060-60-リン" = "データとして観測はできるものの、実在しない……ということですか。"
"101060-61-モモカ" = "そういう事。#n――それなら残る可能性は一つ。機械の故障ってわけ！"
"101060-62-アユム" = "モモカちゃん……。"
"101060-63-リン" = "……。"
"101060-64-リン" = "実際に確認するしかなさそうですね。"
"101060-65-アユム" = "えっと……リン先輩、今なんと……？"
"101060-66-モモカ" = "えっ！？直接行くつもり？ドローンで見ても何もなかったのに？"
"101060-67-モモカ" = "特に異常報告が入ったわけでもないのに大袈裟な……。"
"101060-71-リン" = "――各自治区の生徒会代表を緊急招集します。"
"101060-72-アユム" = "……！？"
"101060-73-モモカ" = "えっ？"
"101060-74-リン" = "現在、連邦生徒会に対応する余力はありませんので。#n各自治区と協力して該当地域の分析を行います。"
"101060-75-リン" = "連邦生徒会長代行の権限により、緊急プロトコルを発動。#n――キヴォトス非常対策委員会を発足します。"
"101060-76-モモカ" = "非常対策委員会……？そ、そこまでする？#nただの機械の故障かもしれないよ？"
"101060-77-リン" = "……それならそれでいいのです。杞憂で済みますから。"
"101060-78-リン" = "ですが、本件の全貌が明らかになるまでは、全力で対応しなくてはなりません。"
"101060-79-リン" = "トリニティ、ゲヘナ、ミレニアム……そしてアビドス。#nそれだけでなく、連絡が取れるすべての自治区の責任者をこちらに招集します。"
"101060-80-アユム" = "……。"
"101060-81-モモカ" = "うわぁ……終わった。#nこれ、1週間は徹夜だよねぇ……。"
"101060-83-アユム" = "リン先輩……！#nその……本当に、大丈夫なのでしょうか？"
"101060-87-アユム" = "その……最近……リン先輩が、代行の権限を乱用しているという声が……#nあちこちから入ってきています……。"
"101060-88-アユム" = "各自治区の代表を招集するとなると、リン先輩ご自身の立場すら危うくなるかもしれません……#n特に今回は、防衛室の権限を侵害していると思われる可能性も……"
"101060-89-アユム" = "あっ、もちろん連邦生徒会長代行のご判断としては、適切だとは思いますが……#nですが、財務室からは……"
"101060-90-アオイ" = "……判断の一つ一つに、指摘を入れるでしょうね。"
"101060-93-アユム" = "あ、財務室長……！"
"101060-94-リン" = "――[ruby=おき]扇喜[/ruby]アオイ。 "
"101060-95-アオイ" = "リン行政官。"
"101060-97-モモカ" = "おっと……急用を思い出したので、私はここで失礼～。"
"101060-105-アユム" = "モモカちゃん、逃げないでください。"
"101060-106-モモカ" = "はっ、離してよ～アユム先輩！#nここにいたら息がつまりすぎて窒息死しちゃうって！"
"101060-109-アオイ" = "いつから統括室の行政官が、防衛室の権限まで持つようになったのかしら？"
"101060-110-リン" = "アオイ、これは……"
"101060-111-アオイ" = "説明は不要よ。この件については、既に把握済みだから。"
"101060-112-アオイ" = "キヴォトス中に、未曾有の異常現象が発生。 "
"101060-113-アオイ" = "兆候も、実害も特に無い――けれど、脅威がないことを立証するまでは、#nあらゆる手段を動員して、最高水準で対応すべき……その決定に異論は無いわ。"
"101060-114-アオイ" = "……そう決定したのが、[ruby=  ・    ・    ・    ・    ・    ・    ・    ・  ]連邦生徒会長なら[/ruby]、ね。"
"101060-115-リン" = "……。"
"101060-116-アオイ" = "でも、あなたは連邦生徒会長じゃない。行政官よ。#n代行の腕章をつけたからといって、あなたが彼女になるわけではない。"
"101060-117-アオイ" = "サンクトゥムタワーの行政権を失ったうえに、SRT特殊学園の閉鎖を決定……#n「シャーレ」という正体不明の組織の認可……"
"101060-118-アオイ" = "その上、これは一体どういう事？#n「シャーレ」の予言？終焉の予知夢……？そんな戯言に振り回されて……"
"101060-119-アオイ" = "いくら「代行」といえど、度を越しているわ。"
"101060-120-リン" = "アオイ、私のことが気に入らないのは分かりますが……"
"101060-121-アオイ" = "……私は今、私的な感情の話をしてはいないの。"
"101060-122-アオイ" = "私は、昔からあなたの能力を高く評価してきたわ。それは生徒会長も然り。#nあなたの能力は、誰よりもよく理解しているつもり。"
"101060-123-アオイ" = "でも、あなたが連邦生徒会長のような超人になれるわけではない。"
"101060-124-アオイ" = "あなたが代行になったのは、統括室の「行政官」だったからであって、#nあなたの能力が認められたのではなく、あくまで必要だったからに過ぎない。"
"101060-125-アオイ" = "その事実は、代行の腕章をつけている限り、あなたにつきまとうでしょうね。#nそれを念頭に置いて、判断をお願いしたいの――連邦生徒会長「代行」。"
"101060-126-リン" = "……。"
"101060-127-アオイ" = "それでも、あなたが非常対策委員会を設置するのであれば、#n防衛室の権限を侵害するに足るだけの根拠と正当性が必要よ。"
"101060-128-アオイ" = "せめて――私を説得できる程度のものを準備してから、発言してちょうだい。"
"101060-129-アオイ" = "それができないと言うのであれば――"
"101060-130-アオイ" = "……あなたの事を、生徒会長の失踪を理由に代行権限を振りかざして、#n連邦生徒会を私物化しようとしている存在として見る事になるわ。"
"101060-131-リン" = "……。"
"101060-132-リン" = "そのお言葉、留意いたします。"
"101060-133-アオイ" = "……そう。#nそれじゃ――"
"101060-138-アオイ" = "……あと、少しは寝なさい。"
"101060-139-アオイ" = "目の下のクマ、酷いわよ。綺麗な肌が台無しじゃない。"
"101060-145-リン" = "……。"
"101060-146-モモカ" = "ぷはー。"
"101060-147-モモカ" = "はぁ……はぁ……息が詰まって、死ぬかと思ったぁ。"
"101060-148-アユム" = "リン先輩……。"
"101060-149-リン" = "アユム、非常対策委員会の準備を。"
"101060-153-アユム" = "……！！"
"101060-154-モモカ" = "……。"
"101060-159-カヤ" = "あら、リン行政官……"
"101060-160-リン" = "カヤ……"
"101060-161-カヤ" = "ごめんなさいね。#n財務室長の声が大きくて……盗み聞きした形になってしまいました。"
"101060-162-リン" = "……非常対策委員会の件は、申し訳ありません。"
"101060-163-カヤ" = "いえ、代行ですから。#n当然の権限だと私は思っていますよ。"
"101060-164-リン" = "……。"
"101060-165-カヤ" = "行政官は精一杯務めを果たしているだけなのに……生徒会長の穴を埋めることは、容易ではありません。財務室長も、何もあそこまで言う事はないのに……。"
"101060-166-カヤ" = "ですが……あなたの権威を疑う人がいるのも事実……困りましたね。"
"101060-167-カヤ" = "そうですね……非常対策委員会にシャーレを同席させるのは、いかがでしょうか？"
"101060-168-リン" = "シャーレを……？"
"101060-169-カヤ" = "ええ。各学園代表を説得する際の一助になってくださるかもしれません。"
"101060-170-カヤ" = "各自治区からシャーレの活躍ぶりは聞き及んでいますから。#n警察学校の不法行為まで突き止めたとのことで……これは捜査部と呼んでも差し支えないかと。"
"101060-171-カヤ" = "先生が同席すれば、行政官の心配も少なくなるでしょうし。"
"101060-172-リン" = "……ありがとうございます。#nそうですね。ちょうど、シャーレに協力を要請しようかと思っていたところです。"
"101060-173-カヤ" = "……では、私の方で先生に連絡をしておきますね。"
"101060-174-カヤ" = "シャーレからここまで移動するのでしたら、警護も必要ですし……#nこちらはヴァルキューレにお願いするとしましょう。"
"101060-175-リン" = "ありがとうございます、カヤ。よろしくお願いします。"
"101060-176-カヤ" = "いえ、大変な時ですから。お互い助け合っていきましょう。"
"101060-177-リン" = "では、失礼しますね。"
"101060-182-カヤ" = "……。 "
"101060-187-カヤ" = "……ええ、進めてください。"
"101060-189" = "次回;非常対策委員会の招集"
