[translation]
"101145-2-ジェネラル" = "SOF、状況を報告せよ！SOF！！"
"101145-4-ジェネラル" = "どうなっている！！"
"101145-7-ジェネラル" = "おい、応答しろ！！"
"101145-9-カイザーの特殊部隊員A" = "ぐっ……なぜだ……PMCの精鋭部隊である、私たちが――"
"101145-14-ミヤコ" = "クラフトチェンバー、確保。"
"101145-18" = "[ns] \"リンちゃん！助けに来たよ！！\""
"101145-20-リン" = "……先生。"
"101145-21-リン" = "誰が「リンちゃん」ですか。"
"101145-22-リン" = "……でも今はそう呼ぶのは先生しかいませんし……良いのかもしれませんね。"
"101145-23-モモカ" = "先輩、大丈夫！？"
"101145-24-アユム" = "リン先輩……無事だったんですね……よかった。"
"101145-25-リン" = "皆さん……"
"101145-26-リン" = "申し訳ありません……私が力不足なばかりに、こんな事に……"
"101145-27-アユム" = "リン先輩……"
"101145-30-ジェネラル" = "くっ……！？"
"101145-31-ミヤコ" = "こちらロビー、敵指揮官を捉えました。"
"101145-32-サキ" = "お前がカイザーPMC指揮官か？#n諦めろ。お前らの計画はこれで終わりだ。"
"101145-34-ジェネラル" = "笑わせるな！"
"101145-38-サキ" = "起爆装置……！？"
"101145-39-ジェネラル" = "これを押したらどうなると思う？#nこの建物は一巻の終わりだ！下がれ！！"
"101145-40-サキ" = "なっ、何を……！"
"101145-41-ミヤコ" = "……RABBIT4、手に持ってる起爆装置を狙えますか？"
"101145-46-ジェネラル" = "ぐ、ぐぅっ……！？"
"101145-50-ミユ" = "う、うん……もう、撃っちゃったけど。"
"101145-52" = "次回;沈みゆく物語"
