[translation]
"10033050-1" = "第5話;花より団子より"
"10033050-2-ウミカ" = "時は楽しいほど、あっという間に過ぎ去るもの……。"
"10033050-3-ウミカ" = "しかし同時に腹が減っては戦はできぬ、です！"
"10033050-4-ウミカ" = "というわけで、お食事の時間ですよ！"
"10033050-6-ウミカ" = "百鬼夜行の伝統が詰まった美食、いかがでしたでしょうか！"
"10033050-11-ハルナ" = "ふふふっ……。"
"10033050-12-ハルナ" = "美食……シンプルかつ簡素にして、奥深い魔法の言葉ですね。"
"10033050-13" = "[ns] \"ハルナ！？\""
"10033050-14-フウカ" = "ちょっと！？#nここで変なこと言わないでよ！？"
"10033050-15-ハルナ" = "この食堂が素晴らしい場所であるということは、存分に分かりました。#nその点は大いに感謝しましょう。"
"10033050-16-ハルナ" = "ですが……決められた場所で、決められた振舞いを頂く。#nこれだけが本当の美食なのでしょうか？"
"10033050-17-ハルナ" = "美食とは受け身ではなく、積極的に手にすべきものではありませんか？"
"10033050-18" = "[s] \"それはつまり……？\""
"10033050-19-アカリ" = "つまりせっかくの百鬼夜行なのですから、#n美味しいものをもっともっと食べてみないと、というお話です★"
"10033050-20-イズミ" = "大賛成ー！#n私も行く！"
"10033050-24-ジュンコ" = "まぁ、言ってることは分かるかも？#nご馳走様！"
"10033050-29-ゲヘナの生徒A" = "あの子たち、またやってるね……。"
"10033050-30-ゲヘナの生徒B" = "でも、確かにまだ食べられるかも？"
"10033050-31-ゲヘナの生徒A" = "よし、「別腹」って言葉の意味を思い知らせてやるー！"
"10033050-32-ゲヘナの生徒B" = "乗ったぁ！"
"10033050-37-ウミカ" = "ちょ、ちょっと待ってください！#nこの後のスケジュールが、順番が……！"
"10033050-38-ウミカ" = "え、えぇと、どうしましょう先生ぇ！？"
"10033050-39" = "[s] \"どっちにせよ、みんなを呼び戻さないと……！\""
"10033050-42-ハルナ" = "ふむ、香しい醤油の香り……#n秘められた生姜がより鶏肉の旨味を引き立てていますね。#n何故か燃え盛ってますが。"
"10033050-43-イズミ" = "わ、饅頭なのに「もんじゃ」が入ってる！#nわさびとチリソースを足したらもっと美味しくなるかも！"
"10033050-44-アカリ" = "これは素晴らしいイカ焼き……#nダイオウイカを一匹丸ごとなんて、最高ですね★"
"10033050-45-アカリ" = "おや、「5分以内に10匹完食したら無料」……#n随分と控えめな目標設定ですねぇ？"
"10033050-46-ジュンコ" = "「この天ぷらはおにぎりの上に乗せて、一気に頬ばってください」……#nそれ、天ぷら丼じゃないの？"
"10033050-47-ジュンコ" = "まあ、一旦言われたとおりに……。"
"10033050-51-ジュンコ" = "[ruby=熱]あふ[/ruby]っ！！？！？"
"10033050-52-ハルナ" = "さて、この辺はおよそ制覇できましたね。"
"10033050-53-ハルナ" = "それでは皆さん、向こうの屋台へ向かいましょう！"
"10033050-54-ゲヘナの生徒たち" = "おー！"
"10033050-61-ツバキ" = "……見つけた。#n先生、あっち……。"
"10033050-62" = "[s] \"ありがとう、ツバキ！\""
"10033050-63-ウミカ" = "はぁ、はぁ……何なのですか、あの方々は……！？"
"10033050-64-フィーナ" = "食べながら動いてるのに、ワタシたちが走るよりも速いのデハ！？"
"10033050-66-カエデ" = "待ってー！#nこの格好ちょっと走りにくいよー！"
"10033050-67-ウミカ" = "急ぎましょう、皆さん……！"
"10033050-71-ハルナ" = "なるほど……#nこの辺りはまた、珍しいものが多いですね。"
"10033050-72-ハルナ" = "個性的な味、と申しましょうか……#n非常に辛い焼き鳥などはまだしも。"
"10033050-73-ハルナ" = "このりんご飴などは、#n甘さどころか渋みしか感じられないという魔訶不思議な……。"
"10033050-74-イズミ" = "え、何これ美味しー！#nこんなの食べたことないかも！"
"10033050-75-露店商人" = "（なっ、これを普通に食べるだと……！？ならば……！）"
"10033050-76-露店商人" = "さあお次はこいつだ！#n梅干しエキスを10倍に濃縮した、酸っぱすぎるおにぎり！"
"10033050-81-イズミ" = "うわぁ、すごい！#nなんか頭の中が痺れてる！"
"10033050-85-露店商人" = "（何だと！？ならば……！）"
"10033050-86-露店商人" = "なら次は、クサヤジャムたっぷりのトーストだ！"
"10033050-90-イズミ" = "魚特有の匂いが凝縮されて、その上良い感じに甘ったるくなってて……"
"10033050-91-イズミ" = "何枚でも食べられそう！おかわり！"
"10033050-92-露店商人" = "ハウカットルそば！"
"10033050-93-イズミ" = "良い香りー！"
"10033050-94-露店商人" = "シュールストレミングラーメン！"
"10033050-95-イズミ" = "コクがたまんないねー！"
"10033050-97-露店商人" = "……ならばこれだ！#nナマコたこ焼きバニラパフェ！"
"10033050-98-ウミカ" = "ちょっと、それは販売を許可していないはずです！"
"10033050-100-露店商人" = "ちぃっ……！"
"10033050-104-ハルナ" = "果たして本当にそうでしょうか？"
"10033050-105-ウミカ" = "……はい！？"
"10033050-106-ハルナ" = "許可というものは、あくまで受容する方々を慮ってのこと……#nそれ自体は感謝しましょう。"
"10033050-107-ハルナ" = "しかし私たちは美食研究会。#nそういった規制を超えて、新たな出会いを求める集団！#nせっかくの修学旅行で、おとなしくなどしてはいられません！"
"10033050-108-イズミ" = "そうだそうだー！このお店、何でも美味しいのに！"
"10033050-109-ジュンコ" = "ほぼあんたしか食べてないけどね！？"
"10033050-110-アカリ" = "まぁまぁ、旅にはハプニングが付きものですから★"
"10033050-112-フウカ" = "許可は許可、ダメなものはダメ！#n食品規制は大変なんだから、文句言わないの！"
"10033050-113-ハルナ" = "残念です、フウカさん……#nあなたは私たちの理念を理解してくださると思っていたのに。"
"10033050-114-フウカ" = "それはそれ、これはこれ！"
