[translation]
"10033055-3-ハルナ" = "ふぅ……仕方ありませんね。#nこの場は譲って、そちらの要求を呑むとしましょう。"
"10033055-4-ジュンコ" = "譲るも何も、やっぱり「ナマコたこ焼きバニラパフェ」はヤバいって……。"
"10033055-6-ウミカ" = "な、何とかなりましたか……#nそれはそうと、お店の営業は……あれっ？"
"10033055-7-ウミカ" = "（屋台自体が、跡形もなく消えて……？）"
"10033055-8" = "[ns] \"ウミカ？\""
"10033055-9-ウミカ" = "あ、いえ……。"
"10033055-10-フィーナ" = "ウミカ、そろそろ食堂に戻らねば！#n次のスケジュールが迫ってきてマス！"
"10033055-11-ウミカ" = "そ、そうですね！#nフィーナとカエデは、この辺りの皆さんの誘導をお願いします！#n食堂の方は私が！"
"10033055-18-ウミカ" = "（マズイ、マズイ……！）"
"10033055-19-ウミカ" = "（スケジュール、取り返すどころかどんどん遅れて……！）"
