[translation]
"10033095-2-アラタ" = "もおおぉぉっ！？"
"10033095-6-ウミカ" = "よ、良かった、これで何とか……。"
"10033095-7-ウミカ" = "（あとは、夜の打ち上げを待つだけ……）"
"10033095-12-魑魅一座A" = "り、リーダー！大変です！"
"10033095-13-魑魅一座B" = "先ほどの戦闘でその、花火が……。"
"10033095-15-アラタ" = "花火が何だよ今さらぁ……。"
"10033095-16-魑魅一座A" = "花火の束に、点火しました！"
"10033095-18-ウミカ" = "えぇっ！？"
"10033095-19" = "[ns] \"マズい……！？\""
"10033095-20-フィーナ" = "だ、大丈夫デス！#n神木祭で使う花火は超巨大！"
"10033095-21-フィーナ" = "ちょっとやそっとの火では、打ち上がりマセン！"
"10033095-22-ウミカ" = "で、ですが早く消さないと！#n全体に燃え移るのも時間の問題……！"
"10033095-24-魑魅一座C" = "さーせん遅れましたー。#nいやぁ、この燃え盛るファイヤー焼き鳥が美味そうで美味そうで……！"
"10033095-28-魑魅一座C" = "つい長蛇の列に……ってうわぁっ！？"
"10033095-32-魑魅一座C" = "いたたたた……ああもう、何すかこれ。#nって……花火？"
"10033095-36" = "[ns1] \"ちょっと待って、花火の上に……。\"\n[ns2] \"あの弾頭、火がついて……！？\""
"10033095-39-ウミカ" = "ダメぇぇっ！！！"
