[translation]
"10054060-1" = "第6話;幻の幼稚園児"
"10054060-4-？？？" = "では、先生……。"
"10054060-8-シュエリン" = "こんにちは、シュエリンです！"
"10054060-12-キキ" = "キキです！"
"10054060-13-シュエリン&キキ" = "お久しぶりです！"
"10054060-14" = "[s] \"う、うん……久しぶり、だね……。\""
"10054060-15-シュエリン&キキ" = "わ～い！"
"10054060-16-シュエリン" = "あれ？先生、顔色が悪いですよ？"
"10054060-17-キキ" = "ずっと水の中にいたからでしょうか……キキ、心配です……。"
"10054060-18" = "[s] \"あはは……心配ないよ……。\""
"10054060-19-シュエリン" = "今日はもう遅いですけど……。"
"10054060-20-シュエリン" = "先生と一緒に遊びたいです！"
"10054060-21-キキ" = "キキも～！"
"10054060-22" = "[s] \"また明日遊ぼうね……。\""
"10054060-23-シュエリン&キキ" = "わ～い！"
"10054060-25-？？？" = "……先生？"
"10054060-26-シュエリン" = "！？"
"10054060-27-キキ" = "！？"
"10054060-32-ココナ" = "今……ちょっといいですか……？"
"10054060-36-ココナ" = "って……あれ？あなたたち……。"
"10054060-37-ココナ" = "どうしてここに！？"
"10054060-38-シュエリン" = "えっと……。"
"10054060-39-キキ" = "そ、それが……。"
"10054060-40" = "[s1] \"さ、さっきシュンに頼まれたんだ。\"\n[s2] \"ピクニックの下見のために、って！\""
"10054060-43-ココナ" = "そうなんですか……？#nシュン姉さん、今度みんなをピクニックに連れてくるつもりなのかな……。"
"10054060-44-ココナ" = "怪しいですね……それなら私にも相談していたはず……。"
"10054060-45-ココナ" = "それにあなたたち、普段あんまり見かけないんだよね。#n隣のクラスだからかもだけど……。"
"10054060-46-シュエリン" = "そっ、それはっ！？"
"10054060-47-キキ" = "い、いきなり決まったんです！#n他の教官からも、せっかくだからって言われて……。"
"10054060-48-ココナ" = "ふーん……？"
"10054060-49-キキ" = "せ、先生……キキ、間違ってないですよね？"
"10054060-50" = "[s] \"う、うん！そう言われた！\""
"10054060-51-シュエリン" = "そうです！先生がいれば大丈夫って！"
"10054060-52-ココナ" = "ふーーん……？"
"10054060-53-キキ" = "そ、それに！頼もしいココナ教官も一緒ですし……。"
"10054060-54-キキ" = "困ったらココナ教官に相談するようにって言われました！"
"10054060-55-ココナ" = "ココナ[ruby=・]教[/ruby][ruby=・]官[/ruby]！？"
"10054060-56-ココナ" = "お姉さんたちが、私のことを……？"
"10054060-57-ココナ" = "こ、こほん。分かりました。ココナ教官に任せてください！#nせっかく来たんだし、いっぱい遊んでいってね！"
"10054060-58-ココナ" = "でも、深いところには行っちゃダメですよ？"
"10054060-59-シュエリン&キキ" = "は～い！"
"10054060-60-ココナ" = "……シュン姉さん、私に一言くらいあってもいいのに。"
"10054060-61-ココナ" = "これは後でバーゲンダッツ3つですね！"
"10054060-62-シュエリン" = "（拗ねちゃいましたね……）"
"10054060-64-ココナ" = "事情は分かったから、他のお姉さんにも伝えておくね。"
"10054060-65-ココナ" = "それと、ここでは教官って呼んじゃダメ。#nココナお姉ちゃんって呼んでね！"
"10054060-66-シュエリン&キキ" = "はい！ココナお姉ちゃん！"
"10054060-67-ココナ" = "こ、ココナお姉ちゃん……。"
"10054060-68-ココナ" = "えへっ、えへへっ……。"
"10054060-72-ココナ" = "……あ、先生。この子たち、どこで寝るんですか？"
"10054060-73-シュエリン" = "それは……。"
"10054060-75" = "[ns3] \"シュンとキサキが面倒を見るってさ。\"\n[ns4] \"迷惑はかけられないって言ってたよ。\""
"10054060-78-キキ" = "はい！そうなりました！"
"10054060-79-キキ" = "他のお姉ちゃんたちと一緒でも楽しそうでしたけどね！"
"10054060-80-ココナ" = "まあ、それであれば……。"
"10054060-81-ココナ" = "あれ？"
"10054060-86-ココナ" = "ということは、私はこの子たちの面倒をみなくても大丈夫ってこと？"
"10054060-87-ココナ" = "それは……ちょっとラッキーかも？#n思いっきり遊びたかったし。"
"10054060-93-シュエリン" = "（声に出てますよ……？）"
"10054060-98" = "[ns] \"ところで、何か用事だった？\""
"10054060-99-ココナ" = "え？"
"10054060-100-ココナ" = "あっ！！！"
"10054060-101-ココナ" = "えっと……その……。"
"10054060-102-ココナ" = "……。"
"10054060-103-ココナ" = "教官の姉さんたちも認めるくらい……わ、私は立派なレディーなので！"
"10054060-104-ココナ" = "で、ですから……その……。"
"10054060-105-ココナ" = "レディーのエスコートを……先生にお願いしようかと！#n……思いまして……。"
"10054060-106-シュエリン&キキ" = "！"
"10054060-107-ココナ" = "うぅぅ……言っちゃった……。"
"10054060-108" = "[ns] \"いいよ。ちょっと歩こうか。\""
"10054060-109-ココナ" = "ほんとですか！？"
"10054060-113-ココナ" = "……。"
"10054060-114-ココナ" = "ううん。やっぱり、またの機会にしましょう。今は2人もいますから。"
"10054060-115-キキ" = "（ほう……）"
"10054060-116-シュエリン" = "（ココナちゃん、偉いですね）"
"10054060-118" = "[ns] \"ココナちゃんとのお散歩楽しみだなぁ～\""
"10054060-119-ココナ" = "言いましたね！"
"10054060-120-ココナ" = "えへへ……。"
"10054060-121-ココナ" = "約束ですからね？"
"10054060-126-ココナ" = "ぜったい、2人きりですよ？ぜったい！"
"10054060-133-ココナ" = "では、先生！#nシュン姉さんと子供たちのこと、よろしくお願いしますね！"
"10054060-137-シュエリン&キキ" = "ふぅ……。"
"10054060-138" = "[s] \"誤魔化せた……。\""
"10054060-139-シュエリン" = "先生、嘘がお上手なんですね！すごいです！"
"10054060-140-キキ" = "キキなんてまだまだだなって思いました！"
"10054060-141" = "[s] \"こらこら、大人をからかわないの。\""
"10054060-142-シュエリン" = "きゃぁ～"
"10054060-143-キキ" = "怒った～！"
"10054060-148-シュエリン" = "いい時間ですし、私たちはそろそろ寝ますね！"
"10054060-149-キキ" = "ふわぁ～……子供の身体だからか、もう眠いです……。"
"10054060-150-シュエリン&キキ" = "おやすみなさい！"
"10054060-155-ルミ" = "話は聞いたよ。こっちはこっちのやるべきことをしようか。"
"10054060-156-ミナ" = "ああ、商店街の調査だな。"
"10054060-157-ココナ" = "山海経と、梅花園の園児たちのために……しゅっぱーつ！"
"10054060-159" = "（3人と一緒に商店街へ向かった）"
"10054060-162-キサキ" = "では、始めようかの。"
"10054060-163-シュン" = "はい。"
"10054060-165-渓谷の商人A" = "アクティビティのオススメ？#nうーん……。"
"10054060-166-渓谷の商人A" = "ラフティングは結構スリルがあるよ。"
"10054060-167-渓谷の商人A" = "川の上流の方から楽しめるんだ。"
"10054060-168-渓谷の商人A" = "でも、雨の日には乗れないのが注意点かな。"
"10054060-169-渓谷の商人A" = "川が増水して危ないんだよ。事故には気をつけないとね。"
"10054060-170-渓谷の商人A" = "……こんな話をするのも久しぶりだ。#n普通の観光客が来てくれるといいんだけど……。"
"10054060-171-ミナ" = "そ、そうか……。#nところで、上流まではどうやって行くんだ？"
"10054060-172-渓谷の商人A" = "景色を堪能したいならロープウェイかな。#n早く行きたい場合はバスがある。"
"10054060-173-渓谷の商人A" = "ただ……ロープウェイは、ちょっと……今はな。"
"10054060-174-ミナ" = "……。"
"10054060-175-ココナ" = "……。"
"10054060-177-キサキ" = "これが、例のホテルと繋がっているロープウェイかの。"
"10054060-178-キサキ" = "ふむ……趣きはあるが、些か古めかしい印象じゃな。"
"10054060-179-シュン" = "ルミさんの投資計画には、施設の補修や交換も盛り込まれていましたが……#n上手くいっていないようですね。"
"10054060-180-キサキ" = "資金をまともに活用できない状況じゃからの。"
"10054060-182-渓谷の商人B" = "ここの岩は水に溶けやすいんだ。#n長い時間をかけて、この渓谷はゆっくりと川に削られていった。"
"10054060-183-渓谷の商人B" = "そうして残った部分が、今の山の姿になってるってわけだ。すごいだろう？"
"10054060-184-渓谷の商人B" = "今でも、地下水には石灰の成分が含まれているんだ。"
"10054060-185-渓谷の商人B" = "だからって体に悪いってわけじゃないけどな。"
"10054060-186-渓谷の商人B" = "殺菌効果があるから、そこを考えれば普通の水よりいいかもしれないな。"
"10054060-187-ルミ" = "なるほど……味は？"
"10054060-188-渓谷の商人B" = "それは……あんまりよくはないかな。"
"10054060-189-渓谷の商人B" = "それでも、ここは川と山が大事な観光資源なんだ。#nなんてったって、こんな田舎にお客さんを連れてきてくれるんだからな。"
"10054060-190-渓谷の商人B" = "だからおすすめするなら、ボートツアーだね。#n朝、霧がかかっているときの眺めは絶景だよ。"
"10054060-191-ココナ" = "わあ、楽しみです！"
"10054060-192-渓谷の商人B" = "逆に霧が濃すぎると船を出せないから、そこは運次第だな。"
"10054060-193-ココナ" = "そうなんですね……。"
"10054060-196-キサキ" = "ホテルに直結されているという話だったと思うが……。"
"10054060-197-シュン" = "案内板を見る限り、ここから5分くらい歩くみたいです。"
"10054060-198-キサキ" = "ふむ……意外じゃな。"
"10054060-199-キサキ" = "性分を考えれば、この距離すら我慢できぬ連中じゃろうに。"
"10054060-200-シュン" = "子供は予測ができないですから。"
"10054060-201-シュン" = "……色々な意味で。"
"10054060-203-ルミ" = "あ……これ、美味しいですね！#n豚肉に、ピーナッツ……漬物も入ってるかな……。#nどうやってこの味を出してるんですか？"
"10054060-204-渓谷の商人C" = "ははっ、それは企業秘密ってやつさ。"
"10054060-205-ルミ" = "商売をするなら、自分だけのものを持っておくべきですもんね。"
"10054060-206-渓谷の商人C" = "まだ若いのに、よく分かってるじゃないか。#nでも、目先の利益にとらわれちゃダメだぞ？"
"10054060-207-ルミ" = "はい……商売は、利益と人、両方を得るべきものです。"
"10054060-211-キサキ" = "さて。ここかの。"
"10054060-212-シュン" = "では……。"
"10054060-213-キサキ" = "うむ。"
"10054060-214-キキ" = "ごめんくださ～い！誰かいませんかー？"
"10054060-215-シュエリン" = "すごい人がいるって聞いて来たんですけど～"
"10054060-225-スイコ" = "誰、あんたたち。"
