[translation]
"10054090-1" = "第9話;契約と移行"
"10054090-10-雇われのスケバンA" = "……。"
"10054090-11-雇われのスケバンB" = "……。"
"10054090-12-雇われのスケバンA" = "はあ……マジでやるのか……？"
"10054090-13-雇われのスケバンB" = "仕方ないだろ……金はもらってるし……。"
"10054090-14-雇われのスケバンA" = "でもよ、商店街を燃やすってのは……なぁ？"
"10054090-15-雇われのスケバンB" = "まぁなぁ……。#n依頼人、しっかりしてそうな大人だったのに。分かんねぇもんだな。"
"10054090-16-雇われのスケバンB" = "とりあえず行くかぁ。"
"10054090-23-スイコ" = "やっと来た！"
"10054090-24-ナゴミ" = "どれだけ待たせやがりますか！#n約束も守れないなんて、年上のくせにみっともねぇですわね。"
"10054090-25-ヨウコ" = "……で。これしか集まらなかったのですか？ガッカリです。"
"10054090-26-雇われのスケバンA" = "な、なんだ、このガキどもは。"
"10054090-27-雇われのスケバンB" = "依頼人が平謝りしてた理由はこれか……。"
"10054090-28-スイコ" = "まぁいいよ。今回は大目に見てあげる。#nうちらは心が広いからね。"
"10054090-29-スイコ" = "あんたたちの仕事は簡単！"
"10054090-30-スイコ" = "ここをめちゃくちゃにすればいいの！"
"10054090-31-雇われのスケバンA" = "えっと……理由だけ聞かせてもらってもいいか？"
"10054090-32-ナゴミ" = "お金もらってんですよね？#nなら言われた通り働きやがれってんですよ。"
"10054090-33-ナゴミ" = "もしかして……契約の意味すら分からない雑魚ってことです？"
"10054090-34-ナゴミ" = "はぁ……これ以上ガッカリさせねぇでほしいです。"
"10054090-35-雇われのスケバンB" = "ガキぃ……！"
"10054090-36-ヨウコ" = "あなた方に理由が必要なんですか？"
"10054090-37-ヨウコ" = "必要だとして、それはお金でしょう？#n本当に、お金さえあればなんでも解決できますね。"
"10054090-38-雇われのスケバンA" = "……。"
"10054090-39-雇われのスケバンB" = "……。"
"10054090-40-雇われのスケバンA" = "なんか嫌だな……。"
"10054090-41-雇われのスケバンB" = "まあ……間違いではないけど。"
"10054090-42-雇われのスケバンB" = "でも……はあ……。"
"10054090-49-シュエリン" = "おはようございます！#nごめんなさい……少し遅れました！"
"10054090-50-キキ" = "ふわぁ～……キキが寝坊しちゃって……ごめんなさい……。"
"10054090-51-スイコ" = "あっ、おはよう！#n子供は寝るのが大事なんだから。気にしないで！"
"10054090-52-ナゴミ" = "いま来たばっかであれだけど、危ないかもしれないから下がってて。#nあんまり前に出ないでね。"
"10054090-53-シュエリン" = "いいんですか？"
"10054090-54-ヨウコ" = "お二人は初めてですから。今回は試用期間ということで。"
"10054090-55-キサキ" = "（好都合じゃな。これなら加勢せずとも怪しまれない）"
"10054090-56-キキ" = "ありがとうございます！"
"10054090-57-スイコ" = "じゃあそろそろ……花火を始めるよ！"
"10054090-58-一同" = "おー！！"
"10054090-65-渓谷の商人A" = "本当に来やがった……！"
"10054090-66-渓谷の商人B" = "これまではやられっぱなしだったけど……！"
"10054090-67-渓谷の商人C" = "助けてくれた生徒たちのためにも、これ以上は我慢しない！"
"10054090-74-雇われのスケバンA" = "痛っ！？無抵抗なんじゃなかったのか？"
"10054090-75-雇われのスケバンB" = "こんなことされて黙ってるわけないだろ……。"
"10054090-76-雇われのスケバンA" = "う～ん……なあ、うちらって報酬分だけ働けばいいんだよな？"
"10054090-77-雇われのスケバンB" = "そりゃな。サービスしてやる義理もないし。#nん？ってことは――"
"10054090-81-雇われのスケバンA" = "なんだ。これでいいじゃん。"
"10054090-82-雇われのスケバンB" = "やっぱ、そうだよな？"
"10054090-85-雇われのスケバンA" = "あんまやる気も起きないし。そもそも具体的な指示もない。"
"10054090-86-雇われのスケバンB" = "となれば……戦ってるフリで！"
"10054090-87-雇われのスケバンA" = "日焼けすんのも嫌だしな。"
"10054090-89-スイコ" = "いけ！やっちゃえ！全部ぶっ壊せ！"
"10054090-93-スイコ" = "……あれ？"
"10054090-94-渓谷の商人A" = "いつまでもやられっぱなしじゃないからな！"
"10054090-100-ナゴミ" = "ど、どういうこと？#nくっ！雑魚大人のくせに……生意気！！"
"10054090-101-渓谷の商人B" = "ここは私たちの居場所だ！守るべきものがある！#n子供だからって、もう容赦しない……！！"
"10054090-102-ヨウコ" = "スケバンは何をしてるんですか！？#n契約通り働いてください！"
"10054090-103-雇われのスケバンA" = "あ、それだけどさ。#nこんなことになるって、契約書には書いてないじゃん？"
"10054090-104-雇われのスケバンB" = "そうそう。抵抗はない、って。#nでも、どうよこれ。うちら戦ってるんだけど。追加の手当が必要じゃない？"
"10054090-108-スイコ" = "こ、この――！"
"10054090-113-スイコ" = "きゃん！？"
"10054090-114-雇われのスケバンA" = "おっと、流れ弾か。#nお前ら、怪我したくなきゃ、適当に引っ込んでろよ。"
"10054090-115-ナゴミ" = "……雑魚のくせにバカにしやがって！"
"10054090-116-ヨウコ" = "結局、誰も信用できないってことですか。#nこうなったら、私たちが出るしかありません。"
"10054090-117-スイコ" = "覚悟しろ！！"
"10054090-127-ルミ" = "あの子たち、すっごい怒ってるね。"
"10054090-128-ミナ" = "こんな事態、予想もしなかっただろうからな。"
"10054090-129-ルミ" = "ちょっと子供相手にやり過ぎてる気もするけどね。"
"10054090-130-ココナ" = "何を言ってるんですか！#nこういう時こそ、ちゃんと叱らないとダメなんですよ！"
"10054090-131-ココナ" = "今度こそ厳しく言ってあげないと！"
"10054090-132-ルミ" = "あははっ、ココナ教官にそう言われちゃあ仕方ない。"
"10054090-133-ミナ" = "これが「槌と鉄床」か。さすが、先生の計画通りだ。"
"10054090-136-ルミ" = "鉄床戦術？"
"10054090-137-ミナ" = "聞いたことはある……戦術の始まりと終わりと呼ばれる概念だろ。"
"10054090-138-ミナ" = "「鉄床」を担当する部隊が敵の攻撃を防いでいる間、機動性に長けた「槌」の部隊が側面と背後を奇襲する戦術。"
"10054090-139-ミナ" = "あらゆる戦術の標準とも言える……。"
"10054090-140-ミナ" = "陣形や武器体形も結局、「槌と鉄床戦術を展開できるかどうか」が最大の要点だからな。"
"10054090-142" = "[ns] \"そう。今回は君たちが「槌」の役割を担うことになる。\""
"10054090-143-ルミ" = "あたしたちが……槌？それにここの地形に詳しい商人の方々が鉄床？でもそれは……。"
"10054090-144-渓谷の商人A" = "分かりました、先生。お任せください。"
"10054090-145-ミナ" = "い、いいのか？つまり、この街を戦場にするってことだが……。"
"10054090-146-渓谷の商人B" = "……だからこそだ。"
"10054090-147-渓谷の商人C" = "思えば、私たちは無力だった。こうやって生徒と先生の力を借りることになったのも、恥じ入ることだ。"
"10054090-148-渓谷の商人A" = "ああ……。ここはずっと私たちの居場所だったからな。#nようやく、目を覚ます時が来たってことだ。"
"10054090-149-渓谷の商人B" = "要は、この道を通さないようにすればいいのだろう？それぐらい、やってみるさ。"
"10054090-151-ルミ" = "じゃあ始めよっか。#n早く片づければ、それだけ被害を抑えられるよね？"
"10054090-152-ミナ" = "速戦即決か。悪くない。"
"10054090-156-ココナ" = "いたずらはここまでだからね！！"
