[translation]
"10054120-1" = "第12話;もうひとつだけ"
"10054120-5" = "[ns] \"みんな、楽しかった？\""
"10054120-6-ココナ" = "はい！とっても！"
"10054120-7-ルミ" = "忘れられない思い出になったね。"
"10054120-8-ミナ" = "一応、投資先の現地査察であったことを忘れないでほしいが……。"
"10054120-9-ミナ" = "それを含めても、楽しい時間ではあったな。"
"10054120-10-シュン" = "ありがとうございます、先生。私たちのために時間を作ってくれて。"
"10054120-11" = "[s] \"ううん。私もすごく楽しかったし。\""
"10054120-12-キサキ" = "ああ、何よりじゃ。"
"10054120-13-キサキ" = "しかし……山海経は何事もなかったかの？"
"10054120-14-ミナ" = "だと思います。カナエも、やる時はちゃんとやりますから。"
"10054120-15-ミナ" = "街の様子も、査察に出る前と同じように――"
"10054120-20-ミナ" = "う、うん……？"
"10054120-27-ミナ" = "なっ！？"
"10054120-28-キサキ" = "カナエ、何かあったのかえ？"
"10054120-29-カナエ" = "門主様……ミナちゃん……。"
"10054120-33-カナエ" = "私は、最善を尽くしました。"
"10054120-34-カナエ" = "本当に……頑張ったんです……。"
"10054120-35-カナエ" = "それだけは、信じてください……。"
"10054120-36-カナエ" = "ぽっくり。"
"10054120-41-ココナ" = "だ、大丈夫ですか！？"
"10054120-45-玄武商会のメンバーA" = "玄龍門め、いつもいつもうちらのことコケにしやがって。"
"10054120-46-玄武商会のメンバーB" = "もう限界！目にもの見せてやる！"
"10054120-52-玄龍門の構成員A" = "法と秩序のもと、今日こそあの高慢ちきを懲らしめてやろう！"
"10054120-53-玄龍門の構成員B" = "行くぞ！玄龍門、出動！！"
"10054120-55-梅花園の園児A" = "わあ！お姉ちゃんたちがいっぱい！"
"10054120-56-梅花園の園児B" = "教官のお姉ちゃんは梅花園から出るなって言ってたけど、やっぱり外って楽しいね！"
"10054120-57-梅花園の園児C" = "でも……玄武商会と玄龍門のお姉ちゃんたち、なんか怖いよ……？"
"10054120-58-梅花園の園児D" = "紛争とは重力のようなものだからね。#n誰かが少し押すだけで、どんどん下へと落ちていくの。"
"10054120-59-梅花園の園児D" = "そして喜ぶのは第三者。マスコミは視聴率を、企業は利益を得るんだよね。"
"10054120-60-梅花園の園児D" = "だからこの世には葛藤が絶えないんだ。"
"10054120-61-梅花園の園児A" = "なに言ってるか全然分かんない！"
"10054120-62" = "[ns1] \"結局……。\"\n[ns2] \"こうなってしまうのか……。\""
"10054120-65-キサキ" = "……ルミ。"
"10054120-66-ルミ" = "うん……分かってるよ。"
"10054120-67-キサキ" = "手間をかけるの。"
"10054120-68-ルミ" = "ううん、こちらこそ。"
"10054120-69-キサキ" = "さっそく一仕事じゃな。"
"10054120-70-ルミ" = "休んだ分、頑張ろっか。"
"10054120-75-ココナ" = "シュン姉さん……？私たちはどうすれば……。"
"10054120-76-シュン" = "とりあえず……園児たちを連れて帰りましょうか。"
"10054120-78" = "[ns3] \"本当に……。\"\n[ns4] \"訓育って難しいなぁ～\""
"10054120-82" = "嵐過天晴"
