[translation]
"10027070-1" = "第7話;歯車"
"10027070-2" = "レッドウィンター連邦学園・図書館"
"10027070-5-メル" = "あいつ、行った？"
"10027070-6" = "[s] \"うん。タカネは帰ったよ。\""
"10027070-7-メル" = "そう……そっか……。"
"10027070-13" = "[ns] \"メル！？\""
"10027070-14-メル" = "へーきへーき。眠くてちょっとふらついただけ。#n緊張が解けたらよくあることだから、気にしないで。"
"10027070-15-メル" = "漫画家も大変だって？#nへへ……先生にそう言ってもらえるの何か嬉しいな。"
"10027070-16-メル" = "じゃあ、私はちょっと寝るね……#nキヴォトスの終焉とかでもない限りはそっとしておいて……ほしいな……"
"10027070-21" = "（メルはそのまま倒れるように、再び眠りについた……）"
"10027070-27" = "（気を失ったメルをベッドに寝かせ、図書館の椅子にしばらく身を任せた）"
"10027070-34" = "[ns] \"電話……？誰だろ……。\""
"10027070-37" = "[ns] \"モミジ！？\""
"10027070-42" = "レッドウィンター連邦学園・山道"
"10027070-44-モミジ" = "こ、こんにちは。先生。お元気にしていましたか？"
"10027070-45-モミジ" = "はい。私はまあ……大丈夫です。元気です。"
"10027070-46-モミジ" = "……。"
"10027070-47-モミジ" = "ええと、先生。最近少し……悩みがありまして。#n先生にご相談したくて……。"
"10027070-48-モミジ" = "その……"
"10027070-49-モミジ" = "……。"
"10027070-50-モミジ" = "メル先輩に、ついての……"
"10027070-51" = "[s] \"メルとケンカした話？\""
"10027070-52-モミジ" = "は、はい！？ど、どうして先生がそれを……！？"
"10027070-53-モミジ" = "え？今もう……「知識解放戦線」の図書館にいらっしゃる！？#nど、どういうことですか！？"
"10027070-62-モミジ" = "そうだったんですね。#nメル先輩が……。"
"10027070-63-モミジ" = "えっと、先生……"
"10027070-64-モミジ" = "私も……メル先輩と仲直りしたい、です。"
"10027070-65-モミジ" = "もちろん、メル先輩は自己中で視野も狭いし、うるさいし、傍若無人なくせに変なところで臆病だけど……"
"10027070-66-モミジ" = "でも、根が悪い人では、ないですから……"
"10027070-67-モミジ" = "『ルナ』に関しても、ちょっと私が感情的になりすぎちゃっただけで……#n感想としては、そう思われる事もあるよな、という内容でした。"
"10027070-71-モミジ" = "メル先輩は……作家ですから。"
"10027070-72-モミジ" = "たぶん……作品への観点が違うのだと思います。"
"10027070-73-モミジ" = "ただ、作品を悪く言われたせいでカッとなってしまって……メル先輩に少しキツくあたってしまって……"
"10027070-74-モミジ" = "はは……それに、メル先輩は謝るの苦手なので、ここは私が先に謝ったほうがいいかもしれません。"
"10027070-78" = "[ns1] \"それなんだけどね、モミジ。\"\n[ns2] \"メルは今、『ルナ』最終巻の二次創作同人誌を描いているよ。\""
"10027070-82-モミジ" = "ええっ！？ど、どういう事ですか？"
"10027070-83-モミジ" = "私が「知識解放戦線」を離れている間に、一体何が……！？"
"10027070-85" = "（モミジに今まであったことを説明した……）"
"10027070-94-モミジ" = "……。"
"10027070-95-モミジ" = "…………。"
"10027070-96-モミジ" = "……………………。"
"10027070-97" = "[s] \"えっと、モミジ……？\""
"10027070-98-モミジ" = "こういう時、どんな反応をしたらいいのか、よく分かりません……。"
"10027070-99" = "[s] \"その気持ち、分かる気がする……。\""
"10027070-100-モミジ" = "メル先輩がそんな事を……先生はそれを全部見ていたんですよね？#n同人誌はもう半分くらい完成していて、期日まであと2日……？"
"10027070-101-モミジ" = "これ、現実なんですよね？#n私、何か変な夢とか見ているわけじゃないですよね？"
"10027070-102-モミジ" = "厳然たる事実、ですか？そんな……どうして現実というのはかくも辛く、私たちに厳しいのでしょう。"
"10027070-103-モミジ" = "というか、メル先輩も……誰もそこまでしろなんて言わなかったでしょうに……"
"10027070-104-モミジ" = "本当に、いつも思いますが……一度これと決めたら、誰が何と言っても止まらないんですよね……。"
"10027070-105" = "[s] \"でも、メルはモミジのためにその同人誌を描いたんだよ。\""
"10027070-106-モミジ" = "……はい。"
"10027070-107-モミジ" = "それは……分かります。へへ、なんだか変な気分です。"
"10027070-108-モミジ" = "他のことはわかりませんが……メル先輩の『ルナ』は、やっぱり一度読んでみたいですね。"
"10027070-112-？？？" = "それ……本当？"
"10027070-113-モミジ" = "！？"
"10027070-114" = "[s] \"！？\""
"10027070-119-メル" = "……。"
"10027070-120-モミジ" = "め、メル先輩！？"
"10027070-121-メル" = "いや、その。ちょっと目覚めちゃってさ。#nそしたら先生が急に図書館の外に出て行ったから……。"
"10027070-122-モミジ" = "じゃ、じゃあ私たちの会話、全部聞いちゃったんですか！？"
"10027070-123-メル" = "全部じゃないけど……ある程度は……。"
"10027070-125-モミジ" = "ふええええ……。"
"10027070-126-メル" = "うう……。"
"10027070-131" = "[ns] \"うううううーん……。\""
"10027070-132-モミジ" = "せ、先生！？せめて何か一言くらい……一緒に困らないでくださいよぉ！"
"10027070-133-メル" = "そ、そうだよ先生！この空気ちょっとどうにかしてよ！"
"10027070-134" = "[s] \"大人だからって、すべてのことに対処できるわけじゃないんだよ……。\""
"10027070-136-メル" = "そんな一般論で逃げてる場合じゃないでしょ！"
"10027070-142-モミジ" = "その……メル先輩、私……。"
"10027070-143-メル" = "う、うん。その……。"
"10027070-144-モミジ" = "……。"
"10027070-145-メル" = "……。"
"10027070-146" = "[s] \"直接会ってから考えるのはどうかな？\""
"10027070-147-モミジ" = "先生！？"
"10027070-148-メル" = "先生！？"
"10027070-149-モミジ" = "か……顔を見て話すのが大事……？"
"10027070-150-メル" = "で、でも、そんな急に……ほら、心の準備とかあるじゃん！？"
"10027070-151-モミジ" = "躊躇してたら進まないのは、そうかもしれませんが……"
"10027070-152-メル" = "……。"
"10027070-153-モミジ" = "……。"
"10027070-154-メル" = "ねぇ、モミジ……"
"10027070-155-モミジ" = "は、はい？"
"10027070-159-メル" = "とりあえず……会って、話そっか？"
"10027070-160-モミジ" = "そ、そう……しましょうか？"
