[translation]
"10031080-1" = "エピローグ;パーティー開始"
"10031080-2" = "（全ての問題が解決されると、パーティーを始めから仕切り直すことになった）"
"10031080-6-ヒナ" = "じゃあ、行ってくる。先生、アコ。"
"10031080-7-アコ" = "はい！が、頑張ってください！委員長！"
"10031080-13" = "[ns] \"いってらっしゃい、ヒナ。\""
"10031080-18-マコト" = "くっ！そ、[ruby=そらさき]空崎[/ruby]ヒナ……！風紀委員長め……！"
"10031080-19-マコト" = "この私の狙いが全て打ち砕かれるとは……！"
"10031080-20-イブキ" = "ヒナ先輩、かっこよかった～！"
"10031080-21-マコト" = "い、イブキ！？"
"10031080-27-イロハ" = "先輩、そろそろ認めましょうよ。#n今回も結局、万魔殿の……いえ、マコト先輩の負けだって。"
"10031080-33-チアキ" = "あははっ！イロハちゃん！直球すぎじゃない？"
"10031080-34-サツキ" = "まあ、いつも通りのマコトちゃんね。"
"10031080-36-マコト" = "いや！まだだ！まだ終わりじゃない……！"
"10031080-37-マコト" = "ここ数日、あれだけ忙しいなかロクに練習できたとは思えない！"
"10031080-38-マコト" = "自分から恥をかきに来たようなものだ！"
"10031080-39-イロハ" = "マコト先輩、その言葉はフラグなのでは……"
"10031080-41-ヒナ" = "…………。"
"10031080-43-ヒナ" = "（一生懸命、練習をしてきた……）"
"10031080-44-ヒナ" = "（他の誰でもない、あなたの期待に応えるため）"
"10031080-45-ヒナ" = "（だから私は、あなたを想って……）"
"10031080-48-ヒナ" = "……今の自分にできる全力を出すだけ。"
"10031080-60" = "#video;11003"
"10031080-74" = "[ns] \"……すごい。\""
"10031080-78-マコト" = "……ぐあぁっ！な、なんだと！？"
"10031080-79-マコト" = "こ、こんな演奏を披露するとは……！#n弾けないのではなかったか……！？"
"10031080-80-マコト" = "いや、まさか……#nあの情報は、最初からこちらを欺くために仕組まれていた……？"
"10031080-81-マコト" = "ふ、風紀委員会め……！#nいつまでこの私を邪魔すれば気が済むんだ……！"
"10031080-82" = "[s] \"この舞台を用意したのはマコトだよね……\""
"10031080-83-イロハ" = "はい、これもマコト先輩が自ら招いたんですよ。"
"10031080-84-マコト" = "……はっ！ぐあぁっ！！な、なんてことだ……！！"
"10031080-91-ヒナ" = "……ふぅ。"
"10031080-96-アコ" = "委員長！素晴らしい演奏でした！"
"10031080-102-イオリ" = "いつからそんなに上手に弾けるように！？"
"10031080-103-チナツ" = "すごく素敵な音……美しかったです。"
"10031080-108-ヒナ" = "あ、うん。みんな……ありがとう。"
"10031080-109-ヒナ" = "間に合って、良かったわ……"
"10031080-110" = "[s] \"お疲れ様。ヒナの演奏……しっかり胸に届いたよ。\""
"10031080-111-ヒナ" = "せ、先生……"
"10031080-112-ヒナ" = "……うん。#nあなたがそう言ってくれるなら……頑張った甲斐があった。"
"10031080-113-ヒナ" = "ありがとう、先生。"
"10031080-114" = "[s1] \"本当にお疲れ様。事件の解決も演奏の準備も……\"\n[s2] \"心配になるから、あまり無理はしないでね？\""
"10031080-117-ヒナ" = "ん？"
"10031080-118-ヒナ" = "いや、先生が言うほど無理なんてしてない。"
"10031080-119" = "[s] \"かなり大変だったと思うんだけど……\""
"10031080-120-ヒナ" = "ああ、マコト議長が企んでた一連の問題ね。"
"10031080-121-ヒナ" = "まあ、大変じゃなかったと言ったら嘘になるけど……"
"10031080-122-ヒナ" = "万魔殿が問題を起こすのは、いつものことだから。#n今回が特別大変だったとは感じてない。"
"10031080-123-アコ" = "はい。マコト議長の暴走は、いつものことです。#nもう慣れてしまいましたね。"
"10031080-124" = "[s] \"……こういう問題って、どのくらいの頻度で起きるの？\""
"10031080-125-ヒナ" = "数えてはいないけど、大体……"
"10031080-126-ヒナ" = "年に4回くらい……？"
"10031080-129-イオリ" = "ゲヘナでは、日常のようなものだからな。"
"10031080-130-チナツ" = "議長がジッとしていると、むしろ心配になってきますから。"
"10031080-131" = "[s] \"これが……ゲヘナの日常……！\""
"10031080-133-ヒナ" = "さあ、それよりもパーティーは始まったばかりでしょう？"
"10031080-134-ヒナ" = "先生……良かったら、エスコートしてくれる？"
"10031080-135" = "[s] \"私でよければ、喜んで。\""
"10031080-136-ヒナ" = "ふふっ、じゃあ……"
"10031080-142-ヒナ" = "――よろしくね、先生。"
"10031080-144" = "（こうして騒動が収束を迎えると、楽しいパーティーの時間が始まった）"
"10031080-145" = "陽ひらく彼女たちの小夜曲"
