[translation]
"10031020-1" = "第2話;準備開始"
"10031020-2" = "（ゲヘナのパーティーの準備を手伝うことになった翌日、マコトから連絡が来た）"
"10031020-7-マコト" = "クククッ。昨日も言ったように、今回のパーティー開催を記念し、我々万魔殿は新議事堂を建設した。"
"10031020-8-マコト" = "そこで先生には、新議事堂の竣工式に立ち会ってもらいたいのだ。"
"10031020-9" = "[s] \"分かったよ、これから向かうね。\""
"10031020-10-マコト" = "キキキッ。では、待っているぞ。"
"10031020-17-マコト" = "クククッ……"
"10031020-18-マコト" = "キキキキキキキキキッ！！！"
"10031020-19-マコト" = "これで[USERNAME]先生の協力は得られた。"
"10031020-20-マコト" = "ただ来てもらうだけではない……先生の手を借りねばならない状況を作り出し、我々万魔殿とシャーレの関係を誇示する映像を撮影するのだ。"
"10031020-21-マコト" = "クククッ。その映像をキヴォトス中で配信すれば、万魔殿とシャーレの協力関係を知らしめることができるだろう！"
"10031020-22-マコト" = "そうすれば、万魔殿の影響力はさらに強まるに違いない……！"
"10031020-27" = "[ns] \"えっと、マコト……まだ繋がってるよ。\""
"10031020-28-マコト" = "なっ…………"
"10031020-29-マコト" = "こ、これは……いや、違うのだ先生、その……"
"10031020-30" = "[s] \"撮影は断らせてもらうね。\""
"10031020-31-マコト" = "こ、この私の偉大な計画が…………！"
"10031020-32-マコト" = "ぐっっっ……！し、し、仕方ない……"
"10031020-33-マコト" = "ひとまず、ゲヘナで先生を待っている。"
"10031020-54" = "[ns] \"みんな、すごく忙しそうだね。\""
"10031020-57-マコト" = "キキキッ。それくらい今回のパーティーは重要な意味を持っているのだ。"
"10031020-58" = "[s] \"あ、マコト。\""
"10031020-59-マコト" = "歓迎する、先生。"
"10031020-60-マコト" = "約束したとはいえ、まさかここまで快く万魔殿に協力してくれるとは……#nあらためて感謝しよう、キキッ。"
"10031020-61" = "[s1] \"うん、協力するって約束したからね。\"\n[s2] \"もちろん、撮影は断らせてもらうけど。\""
"10031020-64-マコト" = "ぐっ……！そ、それは……！"
"10031020-65-マコト" = "…………と、とにかく重要なのは過去ではなく未来！"
"10031020-66-マコト" = "過ぎ去った出来事を振り返るよりも、これからの壮大な未来について語り合った方が建設的だろう。そうは思わないか、先生も！"
"10031020-67" = "[s] （思いっきり話を逸らされたような……）"
"10031020-71" = "[ns] \"議事堂の竣工式ってことは……議事堂を新しく建てたの？\""
"10031020-72-マコト" = "ああ、その通りだ。"
"10031020-73-マコト" = "パーティーを開くついでに、どうせなら施設を拡充しようと思ってな。"
"10031020-74-マコト" = "ちなみに今回のパーティー会場も議事堂内にあるぞ……クックック……"
"10031020-75" = "[s] \"だからこんなしっかりとした竣工式を……\""
"10031020-76-マコト" = "たとえばコンビニやゲームセンター、本屋、ネットカフェ、コインランドリーなどなど……"
"10031020-77-マコト" = "せっかくだから、風紀委員会の奴らが聞けば頭を悩ますような施設を作る予定だ！"
"10031020-78-マコト" = "今後、万魔殿の新議事堂は、ゲヘナの新たな文化的アイコンとして名を知られていくだろう！"
"10031020-79" = "[s] \"議事堂というよりも、大型ショッピングモールのような……？\""
"10031020-80-マコト" = "キキキッ！特にこの私が一番オススメする場所は……#n今回、最も多くの予算を投入した特別施設……"
"10031020-81-マコト" = "そう、「特別温泉」だ！#nこれはゲヘナの皆が使えるよう、議事堂の裏側に建設するよう命じておいた！"
"10031020-82" = "[s] \"そんなに大規模な施設を作ったんだね。\""
"10031020-83-マコト" = "キシシシッ！そうだ！！それだけこのマコト様は、今回の新議事堂建設に力を入れ、イロハやサツキ、チアキ、そしてイブキと共に準備をしてきた！"
"10031020-84-マコト" = "これを見た風紀委員会の奴らが、一体どんな顔をするのか楽しみでしかたない……#nキキキキキキッ！！！"
"10031020-85" = "[s] \"ちなみに温泉はどこに発注したの……？\""
"10031020-86-マコト" = "ん？それはもちろん……"
"10031020-87-マコト" = "ゲヘナの温泉開発部だが？"
"10031020-91" = "[ns] \"…………あっ。\""
"10031020-94-マコト" = "い、いきなり何事だ！？"
"10031020-98-万魔殿の部員A" = "た、大変です！議長……！"
"10031020-99-万魔殿の部員B" = "その、計画していた温泉の件なのですが……！"
"10031020-100-マコト" = "また何か問題か……？"
"10031020-107-マコト" = "なっ……！？"
"10031020-119-マコト" = "お、お前たちは……！"
"10031020-121-メグ" = "やっほ～！温泉開発部だよ～！"
"10031020-122-カスミ" = "ん？#n見覚えのある顔だと思ったら、先生じゃあないか。"
"10031020-123-カスミ" = "万魔殿の議長と一緒だなんて、これまた珍しい組み合わせだな。"
"10031020-124" = "[s] \"こんにちは。メグ、それにカスミも。\""
"10031020-125-メグ" = "やほやほ～先生！"
"10031020-126-カスミ" = "うむ。思いがけない出会いだな、先生。"
"10031020-127-カスミ" = "それはそうと……今回の依頼主のマコト議長とは、あなたで合っているか？"
"10031020-129-マコト" = "あ、ああ……そうだが？#n温泉の開発を依頼したはずなのに、なぜここで騒ぎを起こしているのだ？"
"10031020-130-マコト" = "こんなところに開発を依頼した覚えは無いぞ？#nどういうつもりだ、温泉開発部よ。"
"10031020-131-カスミ" = "なんだ、そんなことか。"
"10031020-132-カスミ" = "たしかに依頼されたのは、新議事堂の裏に新しい温泉施設を建てることだったが……"
"10031020-133-カスミ" = "なんと……！裏側ではなく駐車場に！"
"10031020-134-カスミ" = "もっっっと素晴らしい泉脈の気配を感じたのだ！"
"10031020-135" = "[s] \"えっと……ちなみに、その根拠は？\""
"10031020-136-カスミ" = "先生よ、今さらそんな質問をするのか？"
"10031020-137-カスミ" = "そりゃあ、私の勘に決まっているじゃあないか！"
"10031020-139-メグ" = "部長やみんなと話して……はいないけど！#nなんとなくビビッときたんだ！"
"10031020-140-カスミ" = "ただ依頼に従うだけでは、専門家を名乗っていられんと思ってな！"
"10031020-141-マコト" = "な、何を言っている！ここで間もなく竣工式を始めるところなのだが！？"
"10031020-142-カスミ" = "そうなのか？"
"10031020-143-カスミ" = "私たちには関係ない話だな。#n依頼されたのは、最高の温泉施設開発。"
"10031020-144-カスミ" = "となれば、その要望に最大限応えるのが我々温泉開発部の役目。"
"10031020-145-カスミ" = "まあ、場所なんて気にするな。"
"10031020-146-カスミ" = "ハーハッハッハッハ！いざ温泉が出来上がれば、マコト議長も喜ぶに違いない！#nここは温泉の専門家に任せておくといい！"
"10031020-147" = "[s] \"……こうなる気はしてたよ。\""
"10031020-148-カスミ" = "さあ！全員！掘って掘って掘りまくれ！#n温泉開発の時間だ！"
"10031020-154-メグ" = "みんな、掘るよ～！"
"10031020-160-マコト" = "くううっ！ほ、放っておくものか！#nこのマコト様の竣工式を邪魔しようとは、いい度胸だ！"
"10031020-161-マコト" = "お、お前たち！止めろ！"
"10031020-179" = "[ns] \"ちょ、ちょっと……みんな落ち着いて……\""
"10031020-185-カスミ" = "温泉ができれば、みんな落ち着く！"
"10031020-186-メグ" = "うんうん！温泉は心の糧？暗黒？安息をもたらしてくれるからね～！"
"10031020-191-マコト" = "く、くうううっ！！ど、どうしてこんな事態に……！#n私ともあろう者が、一体どこで間違えてしまったんだ～～！？"
"10031020-192" = "[s] \"……温泉開発部に依頼した時点じゃないかな？\""
"10031020-198-カスミ" = "ハーハッハッハッハ！！！温泉開発だ！爆破だ！全部キレイにして、ゲヘナの生徒全員に1人1温泉を……！"
"10031020-203-カスミ" = "…………………………………………。"
"10031020-211" = "[ns] \"い、今のは……！\""
"10031020-217-アコ" = "こちらでトラブルが発生しているとの通報を受けて来たのですが……"
"10031020-218-ヒナ" = "……これは一体どういう状況？"
"10031020-219" = "[s] \"ヒナ、アコ……！\""
"10031020-220-ヒナ" = "……先生？"
"10031020-221-アコ" = "えっ！？どうして先生がこんなところに……？"
"10031020-223-マコト" = "ええいっ！ヒナめ……！#n今日は我々万魔殿が建設した新しい議事堂の竣工式だというのに……！"
"10031020-224-マコト" = "まさか、お前……このマコト様の邪魔をしに来たのか……！"
"10031020-225" = "[s] \"むしろ助けに来てくれたような……？\""
"10031020-226-マコト" = "ええい！風紀委員長の助けなど要らない！"
"10031020-227-マコト" = "あいつに助けられるくらいなら、議事堂の駐車場に温泉ができるくらい……！"
"10031020-228-マコト" = "で、できるくらい……受け入、れ……う……"
"10031020-229-マコト" = "いや……やはり妥協などできん……！"
"10031020-230" = "[s] \"そこは譲れないんだね……\""
"10031020-235-アコ" = "私たちも別に万魔殿を助けたくて来たわけではありませんよ！？"
"10031020-236-ヒナ" = "あくまで、温泉開発部が暴れているという報告を受けて来ただけ。"
"10031020-242-アコ" = "いつものようにトラブルを対処するだけとはいえ……#n助ける相手が万魔殿なのは癪ですね……"
"10031020-243-ヒナ" = "まずは、この騒ぎを収めよう。#n先生、何か言うことはある？"
"10031020-244" = "[s] \"……ありません。\""
"10031020-245-ヒナ" = "分かった。"
"10031020-249-アコ" = "全員、準備をしてください！"
"10031020-252-風紀委員たち" = "はいっ……！"
"10031020-257-温泉部の部員A" = "……風紀委員会が戦闘態勢に入った！"
"10031020-259-メグ" = "うわあっ～！ど、どうしよう、カスミ部長！"
"10031020-263-カスミ" = "ひ、ひ、ひえええぇっ！！！"
"10031020-268-メグ" = "あっ！カスミ部長がパニックを起こしちゃったよ！"
"10031020-269-温泉部の部員B" = "風紀委員長が出てくると、部長はいつもこうだから……"
"10031020-270-メグ" = "緊急事態だよ！みんな、とりあえず応戦して！！"
"10031020-276-ヒナ" = "！！！！！"
