[translation]
"10031030-1" = "第3話;議長の要求"
"10031030-14-メグ" = "うーーーん！やっぱりダメだったね！#n風紀委員会だけで一苦労なのに、相変わらず強いね、ヒナ委員長！"
"10031030-15-カスミ" = "（ぶるぶるぶるぶる……）"
"10031030-22-温泉部の部員C" = "ど、どうすれば！"
"10031030-23-メグ" = "うーん、部長は大変な状態だし……"
"10031030-24-メグ" = "みんな、撤退～！逃げるよ～！"
"10031030-25-メグ" = "みんな、30分後にアジトで集まろう！"
"10031030-32-ヒナ" = "……！アコ、追いかけるよ。"
"10031030-36-アコ" = "はい！委員長……！"
"10031030-38-マコト" = "ちょっと待ちたまえええ！！"
"10031030-40-アコ" = "な、何ですか！？マコト議長！"
"10031030-42-マコト" = "周りをよく見ろ！#nお前たちが何をやらかしたのか……！"
"10031030-53" = "[ns] \"議事堂、壊れちゃったね……\""
"10031030-56-アコ" = "だからどうしたんですか？"
"10031030-57-マコト" = "だからどうした、だと……！？"
"10031030-58-マコト" = "お前たち風紀委員会が暴れたせいで、竣工式すらできずに壊れてしまったじゃないか！"
"10031030-59-マコト" = "どう責任を取ってくれるんだ！"
"10031030-60-アコ" = "はい？責任転嫁も程がありませんか！？"
"10031030-61-アコ" = "それは、あなたが温泉開発部になんか仕事を依頼したからでしょう？"
"10031030-62-マコト" = "それで？"
"10031030-63-アコ" = "はい……？"
"10031030-64-マコト" = "それはもう終わったことだろう！"
"10031030-65" = "[s] \"……うわぁ。\""
"10031030-66-マコト" = "とにかく風紀委員会のせいだ！#nまったく、シャーレの先生も立ち会うはずだったのにな！"
"10031030-71-マコト" = "こうなった以上、責任は取ってもらうぞ……風紀委員会！"
"10031030-72-マコト" = "いや！風紀委員長！[ruby=そらさき]空崎[/ruby]ヒナ！"
"10031030-73-マコト" = "お前も組織のリーダーとして、責任を取るべきだろう！"
"10031030-74-アコ" = "いえ、委員長！#nこんな戯言に耳を貸す必要はありません！"
"10031030-75" = "[s] \"マコト、いくら何でもそれは……\""
"10031030-78-ヒナ" = "……分かった。それで、あなたは私にどうしてほしいの？"
"10031030-79-アコ" = "委員長！？"
"10031030-83" = "[ns] \"ヒナ……？\""
"10031030-84-マコト" = "……ん？こうもすんなりと行くとは……"
"10031030-85-ヒナ" = "もちろん、意図したものではないけど、私たちのせいで被害が生じたのも事実だから。"
"10031030-86-ヒナ" = "しかも先生の仕事を邪魔することになったのだから……#n私にも責任はある。"
"10031030-87-ヒナ" = "それで、マコト議長……私にどう責任を取ってほしいの？"
"10031030-88-マコト" = "う、うーーん。そうだな……"
"10031030-90-マコト" = "（ヒナの奴、いつもと違ってこちらの要求をあっさり受け入れるとは……理由はよく分からないが……）"
"10031030-91-マコト" = "（これも良い機会だ……！今こそ万魔殿と風紀委員会の上下関係をはっきりさせてやろう！）"
"10031030-92-マコト" = "（どうすれば、風紀委員会の鼻をへし折って、このマコト様の威厳を知らしめられるのか……！）"
"10031030-93-マコト" = " （そういえば、今回のパーティーではピアノの演奏を予定していたな……）"
"10031030-94-マコト" = "（キキキッ！それなら……！）"
"10031030-96-マコト" = "ククッ……ククククッ……クククククッ！！！！"
"10031030-97" = "[s] \"すごく嫌な気配がするような……\""
"10031030-99-アコ" = "い、委員長！#nそんな簡単に約束をしては大変なことになるかもしれませんよ！？"
"10031030-100-ヒナ" = "いいの、アコ。もう決めたことだから。"
"10031030-101-アコ" = "し、しかし……！"
"10031030-107-ヒナ" = "……先生に迷惑をかけたくはないから。"
"10031030-108" = "[s] \"ひ、ヒナ……！\""
"10031030-109-アコ" = "そんな……委員長。"
"10031030-110-マコト" = "ククククッ！決めたぞ！"
"10031030-111-アコ" = "きっと、またとんでもない要求を……！"
"10031030-112-マコト" = "ああ、心配するな。私も馬鹿ではない。#nあくまで現実的な要求をするとしよう。"
"10031030-113-ヒナ" = "現実的な要求？"
"10031030-114-マコト" = "そうだ。#nお前には、このマコト様が用意しているパーティーを手伝ってもらおうじゃあないか！"
"10031030-115-アコ" = "パーティー……ああ、そういえば万魔殿が準備していると情報がありましたね。"
"10031030-116-アコ" = "何を企もうと勝手ですが……委員長のことを巻き込まないで頂けますか！？"
"10031030-117-マコト" = "はっ、何を言っている天雨アコ。私たちはただ素晴らしいパーティーを開こうとしているだけだ。"
"10031030-118-マコト" = "そこにいる、先生の協力を得た上でなぁ！キキキッ！"
"10031030-119-ヒナ" = "……先生、そうなの？"
"10031030-120" = "[s] \"う、うん。まあ成り行きで……\""
"10031030-121-マコト" = "ああ、進んで手伝ってくれているとも！しかも先生は、今回のパーティーをとても楽しみにしている！何せ、このマコト様のパーティーなのだからな！"
"10031030-122-ヒナ" = "先生が、パーティーを楽しみに……"
"10031030-123" = "[s] \"期待……してなくはない、かな……うん。\""
"10031030-124-マコト" = "そんなパーティーを台無しにするところだったのだ。#nだからお前には、この埋め合わせをしてもらう！"
"10031030-125-ヒナ" = "埋め合わせ、って……具体的には何をすれば？"
"10031030-132-マコト" = "（今こそ万魔殿のスパイが手に入れた情報を活用する時……！）"
"10031030-133-マコト" = "風紀委員長、空崎ヒナ！"
"10031030-134-マコト" = "お前には、オープニングのピアノ演奏を担当してもらおうじゃないか！"
"10031030-135-アコ" = "……はい？"
"10031030-136-ヒナ" = "ピアノ、演奏……？"
"10031030-137-マコト" = "クククッ！そうだ！演奏だ！"
"10031030-138-マコト" = "（どうやら風紀委員長は、泳げないうえにピアノを弾けないらしいからな！）"
"10031030-143-アコ" = "委員長のピアノ……！"
"10031030-144-アコ" = "たしかに、それなら私も撮影を……い、いえ！#nぜひ聴いてみたいですが！"
"10031030-145-アコ" = "しかし……そんな無茶はさすがに……！"
"10031030-146-マコト" = "一度承諾した以上、まさか断りはしないだろう？"
"10031030-147-ヒナ" = "…………。"
"10031030-148" = "[s] \"ヒナ、無理に受ける必要は無いからね。\""
"10031030-149-ヒナ" = "……先生。"
"10031030-150-ヒナ" = "気を遣ってくれてありがとう。でも、もう約束したから。"
"10031030-151-ヒナ" = "私が被害を与えたのは事実だし……#n先生もパーティーを楽しみにしているのなら……"
"10031030-152-ヒナ" = "私も、ゲヘナの風紀委員長として……えっと、その……"
"10031030-153-ヒナ" = "先生の期待には応えたい、から……"
"10031030-154-ヒナ" = "……分かった。#nマコト議長、あなたの要求を受け入れる。"
"10031030-155-マコト" = "ほ、本当か！？"
"10031030-156-マコト" = "うむ……"
"10031030-157-マコト" = "いや！もちろんそう言うと思っていた！#n風紀委員長に二言は無いからな！"
"10031030-158-マコト" = "では、引き受けたという認識で準備を進めておくとしよう！"
"10031030-163-ヒナ" = "じゃあ、まずは温泉開発部を追わせてもらう。"
"10031030-164-ヒナ" = "放っておくと、またトラブルを起こすだろうから。#n急いで仕事を終えて、早くピアノの練習を……"
"10031030-165-ヒナ" = "……アコ、行こう。"
"10031030-171-アコ" = "あ、えっと……い、委員長！？"
"10031030-177-マコト" = "……本当に引き受けるとはな。"
"10031030-178-マコト" = "……ふっ。"
"10031030-179-マコト" = "ふふふっ……クククッ、キキキキキッ！"
"10031030-180-マコト" = "これは良いものが見られそうだ……！"
"10031030-181-マコト" = "自分で言ったのだから、逃げるわけにはいかないだろう！#n風紀委員長、空崎ヒナ……！"
"10031030-184" = "[ns] \"……本当に大丈夫かな。\""
