[translation]
"2000315-1" = "過去から学ぶ真理"
"2000315-3" = "（トリニティ・スクエアを歩いている途中で、ベンチに座るマシロを見つけた）"
"2000315-4" = "[ns1] \"読書中かな……？\"\n[ns2]（ひとまず、挨拶することにした）"
"2000315-10" = "[ns] \"こんにちは、マシロ。\""
"2000315-12-マシロ" = "あっ、先生。"
"2000315-13-マシロ" = "トリニティにいらっしゃっていたのですね。#n言ってくだされば私からご挨拶に伺ったのに。"
"2000315-14-マシロ" = "まあ、こうして会えたので構いませんが。"
"2000315-15" = "[s3] \"会えてよかったよ。\"\n[s4] \"ところで、どんな本を読んでいたの？\""
"2000315-18-マシロ" = "あ、これですか？"
"2000315-19-マシロ" = "ええと、少しお恥ずかしいのですが……"
"2000315-25-マシロ" = "こういう本です……"
"2000315-26-マシロ" = "タイトル通り、色々なことわざや四字熟語の成り立ちが#n物語で紹介されていまして。"
"2000315-27-マシロ" = "……面白そう？"
"2000315-28-マシロ" = "……。"
"2000315-34-マシロ" = "ふふっ、そうです。とても面白いのです！"
"2000315-35-マシロ" = "あまりに面白くて、ハスミ先輩にもおすすめしました。"
"2000315-36-マシロ" = "……読んでくれそうには、なかったのですが。"
"2000315-37" = "[s] \"マシロはこういうのが好きなんだね。\""
"2000315-38-マシロ" = "はい。ことわざや四字熟語そのものも好きですが、#nなにより元になった物語に興味があるのです。"
"2000315-39-マシロ" = "そのような物語には、#n長い間受け継がれてきた教訓が込められていますから。"
"2000315-40-マシロ" = "「過去を見て未来を見据える」という言葉通り、#n昔話を学べば未来への道筋も見いだせますし。"
"2000315-41" = "[s] \"おお……！\""
"2000315-42-マシロ" = "そしてなんと言っても、ここに載っている昔話には――"
"2000315-43-マシロ" = "改邪帰正、勧善懲悪のメッセージが含まれているのです！！"
"2000315-44" = "[s] \"確かに、そういう話が多いよね。\""
"2000315-45-マシロ" = "ええ、まさに「正義は勝つ」という真理そのものです。"
"2000315-46-マシロ" = "なので昔から、ことわざや四字熟語に興味を持っていまして。"
"2000315-47" = "[s5] \"なるほどね。\"\n[s6] \"マシロがはまる理由がわかったよ。\""
"2000315-55-マシロ" = "私は普段の会話でもことわざなどを使っていますが……"
"2000315-56-マシロ" = "その度に、誰も理解してくれなかったり、#n考えが古い人扱いされたりするんです。"
"2000315-57-マシロ" = "けれど……先生は、わかってくださるのですね。"
"2000315-61-マシロ" = "……貸してほしい？この本をですか？"
"2000315-62-マシロ" = "もちろんです！是非読んでみてください！ "
"2000315-63-マシロ" = "ふふっ……"
"2000315-64-マシロ" = "私が好きなものに先生が興味を持ってくださるなんて。なんだか……"
"2000315-65-マシロ" = "……ええと……"
"2000315-66-マシロ" = "ふ、不思議な気持ちと、いいますか……"
"2000315-67-マシロ" = "……と、とにかく、そんな感じです！"
"2000315-69" = "（その後もマシロとことわざや昔話のことで盛り上がり、#nたくさん話をしてからシャーレに戻った）"
