[translation]
"1004302-1" = "ただあなた様のため"
"1004302-2" = "（本格的な季節の変化が訪れ、シャーレにも夏に関する様々な業務が舞い込んできた）"
"1004302-6" = "[ns] \"夏だからなのか、お祭り関連の仕事が多い気がする……。\""
"1004302-10" = "（地域の花火大会に向けて、住民への協力要請や、そのための段取り……お祭りで使用する各種備品の安全確認などなど……）"
"1004302-11" = "（シャーレに押し寄せてきたそれらの仕事を慌しく処理していた時だった）"
"1004302-15" = "[ns1] \"もうお昼か……。\"\n[ns2] \"ご飯でも買ってこようかな。\""
"1004302-22" = "[ns] \"……ん？入り口が騒がしいけど、なにかあったのかな……。\""
"1004302-24-通りすがりのおばさんA" = "往来のど真ん中で水着姿だなんて……。"
"1004302-25-通りすがりのおばさんB" = "もしかして、ドラマの撮影でもあるのかしら？"
"1004302-26-通りすがりのおばさんA" = "それにしてはカメラもスタッフも見当たらないわね……そういえばここ、シャーレの事務所前……ということは。"
"1004302-27-通りすがりのおばさんA" = "もしかして……シャーレの先生に呼び出されたのかしら？"
"1004302-28-通りすがりのおばさんB" = "あらまぁ……シャーレの先生にそんな趣味が……?"
"1004302-29" = "[s3] \"誤解です！\"\n[s4] \"なんでここにワカモが……！？\""
"1004302-34-ワカモ" = "あぁ……！先生……！"
"1004302-41-ワカモ" = "うふふっ……お待ちしておりました、あなた様。"
"1004302-42" = "[s5] \"ワカモ……どうして水着で……！？\"\n[s6] \"私何かワカモに悪いことした……？\""
"1004302-43-ワカモ" = "えっ……？"
"1004302-44-ワカモ" = "えっ……？"
"1004302-45-ワカモ" = "いえ、私はただ……。"
"1004302-46-ワカモ" = "こんな真夏の素晴らしい日が……。"
"1004302-47-ワカモ" = "身も心も熱く焦がしてしまいそうな、素敵な日が訪れたというのに、あなた様がずっとオフィスにいらっしゃると伺って……居ても立っても居られず……。"
"1004302-48" = "[s] \"居ても立っても居られず……？\""
"1004302-49-ワカモ" = "ええ。私とあなた様が出会ってから、こうして一緒に迎えることが叶った初めての夏ですから。私にとって、あまりにも特別なこの瞬間を……"
"1004302-50-ワカモ" = "あなた様をオフィスに一人残して過ごすだなんて……このワカモ、そんなことはできません。"
"1004302-51-ワカモ" = "時間はいつだって限られているのです。この季節がむなしく過ぎてしまえば、また次の夏を迎えるまで1年も待たなければなりません。"
"1004302-55-ワカモ" = "……もちろん、季節を指折り数えることもまた醍醐味ではあります……ですが。"
"1004302-56-ワカモ" = "それでも、まだこうして私の手があなた様に届くのであれば……。"
"1004302-57-ワカモ" = "何もせず、この季節を浪費するだなんて、そんなことはできません。"
"1004302-58-ワカモ" = "あなた様と私が一緒に過ごす時間は、毎秒輝かしいものであってほしいですから。"
"1004302-59-ワカモ" = "今日というこの日が、あなた様の思い出に残る一日になってほしいと願い……。"
"1004302-60-ワカモ" = "ええ。恥を忍んで……このように♡"
"1004302-61" = "[s] \"えっと……つまり、ワカモが水着なのは……。\""
"1004302-62-ワカモ" = "うふふっ……はい。あなた様に、忘れられない夏の思い出をプレゼントしようと思いまして♪"
"1004302-63" = "[s] \"忘れられない夏の思い出……。\""
"1004302-64-ワカモ" = "ええ……いかがでしょう、この水着。夏の思い出に相応しくはありませんか？"
"1004302-65-ワカモ" = "あなた様好みの一品を悩みぬいて選んだものです♡何卒、あなた様の口からお言葉をいただければと♡"
"1004302-66" = "[s] \"あ、うん……すごく綺麗だよ。ワカモによく似合ってる。\""
"1004302-70-ワカモ" = "っ……！？"
"1004302-71" = "[s] \"……ワカモ？\""
"1004302-72-ワカモ" = "あ、ああ……あなた様が口にしてくださるお言葉、甘やかな声。"
"1004302-73-ワカモ" = "い、いけません……そんな風にお言葉を頂いてしまったら、もう私……。"
"1004302-77-通りすがりのおばさんA" = "……先生は良いご趣味をなさっているのねぇ。"
"1004302-78-通りすがりのおばさんB" = "あらまあ……。"
"1004302-79" = "[s7] \"だから誤解です！\"\n[s8] \"ワカモ、とりあえず場所を移そう！\""
"1004302-80-ワカモ" = "は、はいっ……！？"
"1004302-81-ワカモ" = "は、はいっ……！？"
"1004302-87" = "（騒ぎが大きくなる前に、とりあえずワカモを連れてシャーレの休憩室に戻ることにした）"
"1004302-95-ワカモ" = "そんなに切羽詰った顔で、私をシャーレに連れてきてくださるなんて……。"
"1004302-101-ワカモ" = "そのお顔を、おそばで見つめていたい気持ちがむくむくと……。"
"1004302-102-ワカモ" = "うふふっ……これも全て、あなた様が私の気持ちを心から理解してくださったお陰なのでしょうか……?"
"1004302-103" = "[s] \"うん、ワカモが私のことを考えてくれる気持ちは伝わってるよ……色んな意味で。\""
"1004302-104-ワカモ" = "ああ、嬉しい……。"
"1004302-110-ワカモ" = "うふふ、それではこれから何を致しましょう……？"
"1004302-111-ワカモ" = "今日というこの日が「あなた様にとって完璧な夏の思い出」となるために、私にお手伝いできることを教えてくださいませ。"
"1004302-112-ワカモ" = "このワカモ、あなた様のためならどんなリクエストでも応じてみせましょう。"
"1004302-113" = "[s] \"あ、リクエスト制なんだ。\""
"1004302-114-ワカモ" = "ええ……あなた様のお手を煩わせないために、私の方で用意するというのも考えましたが……。"
"1004302-115-ワカモ" = "「あなた様にとって完璧な夏の思い出」を作れる確信がなかったと申しますか……。"
"1004302-116-ワカモ" = "せっかくこうしてお会いできるのですから、あなた様にとって最高の思い出を作っていただきたく、躊躇してしまったといいますか……。"
"1004302-117-ワカモ" = "ああ……"
"1004302-118-ワカモ" = "私ったら不束者で、面目ございません……。"
"1004302-119" = "[s9] \"ううん、むしろそこまで考えてくれてすごく嬉しいよ。\"\n[s10] （ワカモが計画を立てていたら、何が起こるか分からないし……）"
"1004302-120-ワカモ" = "それなら良かったのですが……。"
"1004302-121-ワカモ" = "それなら良かったのですが……。"
"1004302-122-ワカモ" = "さあ、それでは……あなた様のお望みは何でしょうか？何なりと仰ってください♡"
"1004302-123" = "[s] \"夏の日の思い出……かき氷を食べる、とか？"
"1004302-124-ワカモ" = "かき氷……?"
"1004302-125-ワカモ" = "なるほど……ええ、分かりました。"
"1004302-126-ワカモ" = "確かに……あなた様と味わうかき氷は極上の逸品となるでしょう……ええ。"
"1004302-127-ワカモ" = "お互いに氷を食べさせ合うことで舌先に広がるほろ苦い甘味と……ゆっくりと訪れる甘美な痛み。"
"1004302-128-ワカモ" = "……私がその痛みに戸惑っている様を、あなた様は目元を緩めて冗談を言い、気遣ってくださることでしょう……うふふっ。"
"1004302-129" = "[s11] \"そ、そうだね……？\"\n[s12] （絶賛妄想中なのかな……）"
"1004302-130-ワカモ" = "ええ……そして、こちらに来る途中で私、良いものを見つけたのです。"
"1004302-131-ワカモ" = "ええ……そして、こちらに来る途中で私、良いものを見つけたのです。"
"1004302-132" = "[s] \"有名なかき氷屋さんの露店とか？\""
"1004302-133-ワカモ" = "いえ、かき氷屋さんではないのですが……道すがら、このようなイベントを見かけまして。"
"1004302-137" = "（ワカモがスマホで見せてくれたのは、近所で行われているイベントの情報だった）"
"1004302-138" = "（そこには……）"
"1004302-139" = "[s] \"「レッドウィンター万年雪彫刻ショー」……？\""
"1004302-140-ワカモ" = "ええ、レッドウィンター連邦学園から取り寄せた特別な氷で作った彫刻を展示しているそうなんです。"
"1004302-141-ワカモ" = "特に、ひげで威厳を表現したとある彫刻が有名らしく……。"
"1004302-142" = "[s] \"ええと、それとかき氷に何の関係が……？\""
"1004302-143-ワカモ" = "展示されている彫像は、真夏でも溶けずに残っている北の地域の天然氷で作られているそうなのです。"
"1004302-144-ワカモ" = "それならば、その氷像の一部を削ってかき氷を作ることができれば……"
"1004302-145-ワカモ" = "あなた様の最高の日を彩るのに相応しい特別なかき氷が作れるはず……！"
"1004302-146" = "[s] \"ス、ストップ！かき氷はやめよう！\""
"1004302-147-ワカモ" = "ダメ、ですか……"
"1004302-148-ワカモ" = "ああ、そうですね。衛生的にも清潔ではありませんね。"
"1004302-149-ワカモ" = "このワカモ、あなた様のために特別なかき氷を用意したいという気持ちばかりが急いてしまって……"
"1004302-150-ワカモ" = "当たり前のことを見落としておりました。申し訳ございません。"
"1004302-151" = "[s] \"……水遊びとかはどうかな？"
"1004302-152-ワカモ" = "水遊び……ですか。"
"1004302-153-ワカモ" = "そうですね……夏に欠かせない素敵な営みですし、水着に似合うお誘いではありますが……。"
"1004302-154-ワカモ" = "シャーレの備品にビニールプールなどはありましたでしょうか？このワカモ、記憶になく……"
"1004302-155-ワカモ" = "そうなると、一体どこで水遊びを……。"
"1004302-159-ワカモ" = "……私、理解致しました。"
"1004302-160-ワカモ" = "あなた様のお言葉は、いつだってこのワカモに新しい気づきを与えてくださりますね。"
"1004302-161" = "[s] \"深い意味があったわけじゃないんだけど……って分かったって、何が！？\""
"1004302-162-ワカモ" = "うふふっ……あなた様は時に意地悪をなさります。"
"1004302-163-ワカモ" = "私のことを試しているのですよね？"
"1004302-164-ワカモ" = "そんなところも、お可愛らしい人……ですが、ええ。このワカモ、あなた様のことでしたらなんだってお見通しです。"
"1004302-165-ワカモ" = "このビルの屋上に給水タンクがございましたよね？"
"1004302-166" = "[s] \"あるけど……それがどうしたの？\""
"1004302-167-ワカモ" = "それを爆破すれば、ビル全体が浸水し……"
"1004302-168-ワカモ" = "プールの用意などせずとも、水遊びが可能になる……あなた様が仰りたいのはそういうことですよね？"
"1004302-169" = "[s13] \"そんな純真な目で見つめられると、心苦しいんだけど……\"\n[s14] \"そういう意図ではないんだ……！ごめん、それもストップで！\""
"1004302-172-ワカモ" = "そう……なのですか。"
"1004302-173-ワカモ" = "難しいですね……。"
"1004302-175" = "（その後も、ワカモと「完璧な夏の思い出」づくり計画を話し合った……）"
"1004302-178-ワカモ" = "ホタル観賞……きらめく火の粉が舞う姿……"
"1004302-179-ワカモ" = "うふふ、任せてください。"
"1004302-183-ワカモ" = "このワカモ、その程度でしたら……！"
"1004302-184-ワカモ" = "え？やめてほしい……？"
"1004302-185-ワカモ" = "……それでしたら、"
"1004302-186-ワカモ" = "このワカモが全てを薙ぎ払って……"
"1004302-187-ワカモ" = "ダメなのですか？"
"1004302-190-ワカモ" = "ああ、難しいですね……一体どうしたら良いのか……。"
"1004302-191-ワカモ" = "ですが、これも全てあなた様と私が同じ夢に向けて努力しているのだと思うと……。"
"1004302-192-ワカモ" = "心の奥底から幸せが……"
"1004302-193-ワカモ" = "ああ、溢れてしまいそう♡"
"1004302-194" = "[s] \"そ、そうだね……！\""
"1004302-195" = "（どんな提案をしてみても、どれも斜め上の解決策を返してくるワカモを前に頭を悩ませ続けていると……）"
"1004302-200" = "（急にアイデアが浮かんだ）"
"1004302-201" = "[s] \"……そういえば、ワカモと一緒にやりたいことがあるんだ。\""
"1004302-202-ワカモ" = "えっ……？"
"1004302-206-ワカモ" = "ここは……普段、あなた様がお仕事をされている……。"
"1004302-207-ワカモ" = "こんなところに二人きりで……一体何を……。"
"1004302-211-ワカモ" = "……ああっ！"
"1004302-212-ワカモ" = "うふふふっ……二人きりで、他人の目が及ばぬところで過ごす特別な夏……。"
"1004302-213-ワカモ" = "ええ、このワカモ、心の準備はとうの昔に済ませておりますとも。"
"1004302-214-ワカモ" = "さあ、何なりとご用命くださいませ……"
"1004302-220-ワカモ" = "あ・な・た・様♡"
"1004302-221" = "（何を提案しても暴走してしまうワカモにおとなしくしてもらうための苦肉の策……）"
"1004302-224" = "[ns] \"それは……夏の日の仕事漬け！\""
"1004302-228-ワカモ" = "…………えっ？"
"1004302-229" = "[s15] \"夏に親しい友達で集まって、一夜漬けをする事だよ。\"\n[s16] \"ちょうど仕事もたくさんあるし、これを一緒にこなすのはどうかな、と思って。\""
"1004302-232-ワカモ" = "え？その……えっ。"
"1004302-233-ワカモ" = "本当にそんなことで……大丈夫なのですか？"
"1004302-234-ワカモ" = "「あなた様にとって完璧な夏の思い出」となるのでしょうか……？"
"1004302-235" = "[s] \"もちろん。ワカモと二人きりでやる事に意味があるからね！\""
"1004302-239-ワカモ" = "私と、ふ、ふ、二人きりで……。"
"1004302-240-ワカモ" = "はい……はいっ！あ、あなた様がそう仰るのでしたら……！"
"1004302-246-ワカモ" = "うふふっ♡"
"1004302-248" = "（どうにかワカモと一緒に「完璧な夏の思い出」を作った）"
