[translation]
"70011010-1" = "監原ミスズの憂鬱（１）"
"70011010-3-更生した生徒" = "ありがとね、スズちゃん！"
"70011010-4-更生した生徒" = "おかげで私、頑張れる気がする！絶対また連絡するから！"
"70011010-5-ミスズ" = "といっても、それはあなたが努力したからですよ。"
"70011010-12-同級生" = "3か月連続で表彰！？すごいねスズちゃん！"
"70011010-13-同級生" = "ヴァルキューレ全体でもそうそうないよね！？"
"70011010-14-ミスズ" = "といっても、皆さんのご協力あってのものですよ。"
"70011010-21-先輩A" = "まぁ、スズちゃんしかいないよね。"
"70011010-22-先輩B" = "スズちゃん？ああ、[ruby=かんばら]監原[/ruby]ミスズ？#nあの性格で大丈夫なのかな……。"
"70011010-23-先輩A" = "でもほら、実績はあるし……。"
"70011010-24-ミスズ" = "（……ん？）"
"70011010-25-クロノス報道部の生徒" = "あっ、あちらに！こんにちは！監原ミスズさんですね？"
"70011010-32-クロノス報道部の生徒" = "次期矯正局長に選ばれたお気持ちをお聞かせください！"
"70011010-33-ミスズ" = "（どうして、こんなことになったのでしょう……）"
"70011010-34-ミスズ" = "（私はこんなこと……）"
"70011010-48-？？？" = "……ズちゃん。"
"70011010-50-収監中の生徒" = "スズちゃん。"
"70011010-51-ミスズ" = "ひあぁあっ！？"
"70011010-52-収監中の生徒" = "うわっ、ビックリしたぁ……大丈夫？"
"70011010-53-ミスズ" = "ごめんなさい……少し考え事をしていて……。"
"70011010-54-収監中の生徒" = "もー、ただでさえ普段ぽけーっとしてるんだから。しっかりしてよ？"
"70011010-55-ミスズ" = "えへへ……そうですね、気をつけないと。ご心配ありがとうございます。"
"70011010-56-収監中の生徒" = "……それで、お願いしてたやつなんだけど。"
"70011010-57-ミスズ" = "あ……これ、ですよね？"
"70011010-62-収監中の生徒" = "これこれぇ！これ無いとほんとに朝キツいんだよー。"
"70011010-63-収監中の生徒" = "ありがと！またお願いね！"
"70011010-64-ミスズ" = "あ、えっと……一応、外の物を何度も持ち込むのはルール的に……。"
"70011010-65-ミスズ" = "なので次はちょっと難しいかも……しれません……。"
"70011010-66-収監中の生徒" = "え？持ってきてくれたの、今日が初めてじゃないよね？"
"70011010-67-ミスズ" = "えっと……これまでは特例のようなもの、といいますか……。"
"70011010-68-収監中の生徒" = "じゃあ次も特例で頼むよ～"
"70011010-69-ミスズ" = "はいぃ……。"
"70011010-70-ミスズ" = "でも……少しずつ減らしてみてはいかがでしょう？#nあまり体に良いものでもありませんから。"
"70011010-71-収監中の生徒" = "んー……まぁ、そうだけど……。"
"70011010-72-矯正局の生徒A" = "……あれ？ちょっと。"
"70011010-77-収監中の生徒" = "げっ、看守！"
"70011010-78-矯正局の生徒A" = "だから看守じゃないって何回言えば……あー、もういいや。"
"70011010-79-矯正局の生徒A" = "で、何やらかしたんだ？"
"70011010-80-収監中の生徒" = "なんで決めつけるんだよ！"
"70011010-81-矯正局の生徒A" = "日頃の行いを振り返ってみろって。#nそれで……。"
"70011010-84-ミスズ" = "……。"
"70011010-88-矯正局の生徒A" = "ほら。ボディチェックされる前に自分から出しな。"
"70011010-89-収監中の生徒" = "チッ。"
"70011010-94-矯正局の生徒A" = "……なんだこれ？"
"70011010-95-収監中の生徒" = "見りゃ分かんだろ、抹茶ラテスティックだよ。カフェイン入ってるやつ。"
"70011010-96-矯正局の生徒A" = "カフェイン？それならインスタントコーヒーが支給されてるだろう？"
"70011010-97-収監中の生徒" = "あれ苦くてまずいもん。"
"70011010-98-矯正局の生徒A" = "はぁ……遊びに来てるんじゃないんだぞ……。"
"70011010-99-矯正局の生徒A" = "というかこれ、結構高いやつじゃなかったか？金はどうしてるんだ？"
"70011010-100-収監中の生徒" = "え？そうなの？"
"70011010-101-矯正局の生徒A" = "は？知らないのか？ってことはまさか……。"
"70011010-102-ミスズ" = "え、えへへ……それは私が選んだ物なのです。"
"70011010-103-ミスズ" = "ただでさえ窮屈な思いをされていますから……#nせめて食べ物くらい、美味しいものをと思って……えへへ……。"
"70011010-104-ミスズ" = "あっ、それに……収監されている生徒の体調管理は私たちの仕事ですし……。"
"70011010-105-矯正局の生徒A" = "局長。"
"70011010-106-ミスズ" = "あ、や、えっと……えへへ……。"
"70011010-107-矯正局の生徒A" = "はぁ……毎度これでは困ります。私たちの仕事が増えるんですよ？"
"70011010-108-ミスズ" = "ごめんなさい……。"
"70011010-109-収監中の生徒" = "おいおい、あんまスズちゃんを責めんなって。無理言ったのは私なんだから。"
"70011010-110-収監中の生徒" = "責めるなら私にしろ！！"
"70011010-114-矯正局の生徒A" = "いや、それはそうだろうよ……。"
"70011010-115-矯正局の生徒A" = "どうして私が悪者みたいになってるんだ……。"
"70011010-116-矯正局の生徒B" = "おい、何事だ？"
"70011010-120-矯正局の生徒A" = "あっ、先輩……。"
"70011010-121-矯正局の生徒B" = "あー……だいたい分かった。"
"70011010-122-矯正局の生徒B" = "お前は自分の部屋に戻れ。それも忘れずに持ってけよ。"
"70011010-123-収監中の生徒" = "こんなつもりじゃなかったんだけど……。"
"70011010-124-収監中の生徒" = "やっぱカフェイン減らすか……スズちゃん、ごめんな。"
"70011010-128-ミスズ" = "えへへ……お気をつけて。"
"70011010-129-矯正局の生徒B" = "では、私たちもこれで。持ち場に戻ります。"
"70011010-135-ミスズ" = "はい……引き続き、よろしくお願いします……。"
"70011010-137-矯正局の生徒A" = "こんなんでいいんですか？"
"70011010-138-矯正局の生徒B" = "局長の性格は知ってるだろ……うちらが合わせるしかない。"
"70011010-139-矯正局の生徒A" = "はぁ……ミスズさん、優しすぎますよ。"
"70011010-140-矯正局の生徒A" = "いや、良い人なのは分かるし、私も好きですけど……。"
"70011010-141-矯正局の生徒B" = "まぁ言いたいことは分かるよ。誰にだって向き不向きはある。でも――"
"70011010-143-矯正局の生徒B" = "矯正局長の振る舞いとしては、ちょっとな……。"
"70011010-150-ミスズ" = "今日もなんとか終わりました……。"
"70011010-154-ミスズ" = "局長室……私には広すぎますね。"
"70011010-155-ミスズ" = "といっても、局員の頃のデスクは狭くて不便でしたし……#n皆さんにスペースを分けてあげられたらいいのに……。"
"70011010-160-ミスズ" = "歴代の局長も、同じ思いだったのでしょうか……？#nそれとも……私が庶民的すぎるだけなのか……。"
"70011010-165-ミスズ" = "といっても、あまり悩んでいても仕方ありませんね。#nやめやめ。この辺にしておきましょう。"
"70011010-166-ミスズ" = "もっと良いことを考えないと。せっかく今日は仕事が早く終わったのですし。"
"70011010-167-ミスズ" = "これだって。多少無理はしましたが……なんとか間に合いそうで良かったです。"
"70011010-171-ミスズ" = "ふふっ。"
"70011010-172-ミスズ" = "編み物はいいですね……心が落ち着いて……。"
"70011010-173-ミスズ" = "このまま時間が止まればいいのに――"
"70011010-177-矯正局の生徒A" = "局長！"
"70011010-178-ミスズ" = "はひっ！？"
"70011010-183-矯正局の生徒A" = "夜分遅くに失礼します！これは早急に報告すべきと思い……！"
"70011010-184-ミスズ" = "は、はい、構いません。急務なら当然です。"
"70011010-185-ミスズ" = "それで、どうされましたか？"
"70011010-186-矯正局の生徒A" = "それが……囚人が脱獄を――"
"70011010-187-ミスズ" = "ええっ！？脱獄ぅ！？"
"70011010-188-ミスズ" = "いつ！？誰が！？ワカモですか！？1人で！？"
"70011010-189-矯正局の生徒A" = "あっ……違います。"
"70011010-190-ミスズ" = "1人じゃない！？"
"70011010-191-ミスズ" = "じゃあ何人のワカモが脱獄を！？"
"70011010-192-矯正局の生徒A" = "いや、そもそもワカモは1人しか……。"
"70011010-193-矯正局の生徒A" = "というか、ワカモはずっと前に脱獄したじゃないですか。"
"70011010-194-ミスズ" = "あ……そうでした。取り乱しました……。"
"70011010-195-矯正局の生徒A" = "ご安心ください。脱獄は阻止できています。"
"70011010-196-矯正局の生徒A" = "とはいえ事が事なので、処分についての判断をいただきたく。"
"70011010-197-矯正局の生徒A" = "脱獄を試みた生徒の身元はこちらです。"
"70011010-202-ミスズ" = "あぁ、それでしたら。"
"70011010-209-ミスズ" = "少し、時間をいただけますか？直接話をしてみようと思います。"
"70011010-210-矯正局の生徒A" = "つまり、取り調べですよね？"
"70011010-211-ミスズ" = "あまり好きな表現ではありませんが……そうなります。"
"70011010-212-矯正局の生徒A" = "ですが、わざわざ局長が危険人物と対面しなくても……。"
"70011010-213-ミスズ" = "矯正局は人手不足なのですから。"
"70011010-214-ミスズ" = "私にやらせてください。"
"70011010-215-矯正局の生徒A" = "……分かりました。準備に取り掛かります。"
"70011010-223-ミスズ" = "……昔なら、こういうこともなかったのですが。"
