[translation]
"1012906-1" = "追いかけた輝きは"
"1012906-2" = "（スズミが教えてくれた場所は……）"
"1012906-3" = "（トリニティ内にある、閑散とした遊園地だった）"
"1012906-6" = "（しばらくすると、スズミがやってきた）"
"1012906-10-スズミ" = "遅くなりました！"
"1012906-11-スズミ" = "お待たせしてしまい、申し訳ありません。"
"1012906-12" = "[s1] \"大丈夫！\"\n[s2] \"私もさっき着いたところだよ。\""
"1012906-15-スズミ" = "お気遣いくださりありがとうございます。"
"1012906-16-スズミ" = "お、遅れたのは……この格好が原因で。"
"1012906-17-スズミ" = "実は昨日――"
"1012906-18-スズミ" = "疲れていたのか、洋服と一緒に水性ペンを洗濯機にかけてしまい……。"
"1012906-19-スズミ" = "……無事なのは、この服だけでした。"
"1012906-20-スズミ" = "い、一応……遊園地の方には、事前に事情を説明し了承を得ています。"
"1012906-21-スズミ" = "今日は魔法少女のヒーローショーはないので、キャストに間違われることもないかと。"
"1012906-22" = "[s3] \"災難だったね……。\"\n[s4] \"落ち着いて対処できて、えらいよ！\""
"1012906-25-スズミ" = "事前確認は大事、ですから……。"
"1012906-26-スズミ" = "（先生にお会いできるチャンスを……）"
"1012906-27-スズミ" = "（見送りたくはなかったですし……）"
"1012906-28" = "[s5] \"やっぱりその服、似合ってるね！\"\n[s6] \"遊園地にもピッタリ！\""
"1012906-31-スズミ" = "そ、それは……良かったです。"
"1012906-33" = "（その後、スズミと一緒に遊園地を楽しんだ）"
"1012906-34" = "（スズミの服装は子供たちに大人気で、何度も声をかけられた）"
"1012906-38-劇団員A" = "食らえ！必殺、ギガライトニングッ！"
"1012906-39-劇団員B" = "くっ、また怪獣かっ……！キリがない！"
"1012906-40-スズミ" = "……何かの公演でしょうか。"
"1012906-41-スズミ" = "「怪獣軍団との大決戦」……なるほど、ヒーローショーですね。"
"1012906-42-スズミ" = "……。"
"1012906-44" = "（スズミはしばらくの間、ショーを眺めていた）"
"1012906-51-スズミ" = "あっ。"
"1012906-52-スズミ" = "失礼しました。つい見入ってしまって……。"
"1012906-53" = "[s] \"……スズミ、何か悩んでない？\""
"1012906-54-スズミ" = "悩み……とも言えるかもしれません。"
"1012906-55-スズミ" = "みなさんは……誰かを救うヒーローの物語がお好きなんですね。"
"1012906-56-スズミ" = "先ほどのヒーローも、この衣装の魔法少女も。#nそういう物語の人物です。"
"1012906-57-スズミ" = "みなさんが英雄の登場を望むのは、実在しないからこそ……。"
"1012906-58-スズミ" = "……そんなことを、考えていました。"
"1012906-59" = "[s7] \"英雄なら、いま私の目の前にいるよ。\"\n[s8] \"英雄の服を着て、英雄みたいに大活躍してた。\""
"1012906-64-スズミ" = "そう、なんですか？"
"1012906-65-スズミ" = "……。"
"1012906-66-スズミ" = "自分で英雄を名乗るのは、少し気後れしますが……。"
"1012906-67-スズミ" = "先生にそう呼んでいただけるのは……悪くないですね。"
"1012906-68-スズミ" = "いつも、まっすぐ向き合ってくださる――"
"1012906-69-スズミ" = "そんな先生の言葉だから、素直に嬉しく思えるのです。"
"1012906-70" = "[s9] \"スズミは本当にカッコいいからね！\"\n[s10] \"スズミは本当にイケてるからね！\""
"1012906-73-スズミ" = "ありがとうございます、先生。"
"1012906-74-スズミ" = "つまらない話を、ここまで聞いていただいて。"
"1012906-75-スズミ" = "……すっかり暗くなってしまいましたね。"
"1012906-81-スズミ" = "……今なら、ここからでも星を掴めてしまいそうです。"
