[translation]
"3502-1" = "プレゼント？"
"3502-3-メグ" = "うわぁ……あっつい～"
"3502-4-メグ" = "でも、ゴリゴリ君があるから大丈夫！"
"3502-5-メグ" = "食後のおやつに～ゴ～リゴ～リ～君～"
"3502-11-メグ" = "あれ……？"
"3502-12-メグ" = "……風紀委員長！？"
"3502-13-ヒナ" = "……？"
"3502-14-ヒナ" = "ああ、メグね。ここにはどんな用で……？"
"3502-18-ヒナ" = "……もしかして、温泉を掘りに？"
"3502-19-メグ" = "え？ううん、違うよ～！おやつにゴリゴリ君を買いにきたの！"
"3502-20-ヒナ" = "「ゴリゴリ君」……？"
"3502-21-ヒナ" = "ああ、そういえばそういった名前のアイスがあったわね。"
"3502-22-ヒナ" = "じゃあ、今日は温泉を掘るわけではないのね？"
"3502-23-メグ" = "えっとねぇ……"
"3502-24-メグ" = "……あ！そうだ！"
"3502-25-メグ" = "思い出した！カスミ部長が言ってた#n「風紀委員会かヴァルキューレに会った時の対処法」！#n相手はヒナ委員長だから……！"
"3502-26-ヒナ" = "……？"
"3502-27-メグ" = "……うーん、えっと。#nどうやるんだっけ……。"
"3502-31-ヒナ" = "その……。"
"3502-32-メグ" = "……あ！"
"3502-33-メグ" = "そうそう！まずはこれを出して……！"
"3502-38-メグ" = "じゃじゃーん！#nはい、どうぞ！"
"3502-44-メグ" = "そして――"
"3502-45-メグ" = "「いつもご苦労様です。ささやかながら心ばかりのプレゼントです。これからも何卒よろしくお願いいたします。」"
"3502-46-ヒナ" = "…………。"
"3502-47-ヒナ" = "……………………。"
"3502-48-メグ" = "……でいいんだよね？"
"3502-49-メグ" = "よし！完了！"
"3502-50-メグ" = "あ、さっき委員長が言っていた温泉についてだけど……私は分かんないや！#n多分そのうち部長が教えてくれると思う！"
"3502-51-ヒナ" = "なるほど……これが……。"
"3502-55-ヒナ" = "ふぅ……。"
"3502-56-ヒナ" = "……メグ。"
"3502-57-ヒナ" = "カスミから教わったこれ、他の人にもやったことある？"
"3502-58-メグ" = "……うん？まだだよ？"
"3502-59-メグ" = "実際に試したのはヒナ委員長が初めて！それがどうかしたの？"
"3502-60-ヒナ" = "そう……ならいいわ。"
"3502-61-ヒナ" = "一つ、頼みがあるのだけど。聞いてくれないかしら。"
"3502-62-メグ" = "頼み……？"
"3502-63-メグ" = "もちろん！なんでも言って！"
"3502-64-ヒナ" = "ありがとう。じゃあ……"
"3502-65-ヒナ" = "今から私がやることを、カスミにそのまま伝えてあげて。"
"3502-71-メグ" = "……はっ！？"
"3502-72-メグ" = "袋が、粉々に……！？"
"3502-73-ヒナ" = "彼女ならこれだけで十分伝わるはずよ。もしも上手くいかなかったら……"
"3502-74-ヒナ" = "「次にこのような行為が発覚したら、その時は確実に制裁を受けてもらう。」"
"3502-75-ヒナ" = "「ゲヘナでは、昔の悪癖は慎むように。」"
"3502-78-ヒナ" = "……と言ってあげて。"
"3502-79-メグ" = "プレゼントを渡したのに、それが壊されたと……部長に伝える……。"
"3502-80-メグ" = "うーん、よく分かんないけど……。"
"3502-81-メグ" = "ま、ヒナ委員長もカスミ部長も頭いいんだし、なにか理由があるんだよね！#nうん！分かった！"
"3502-82-ヒナ" = "ふふ、ありがとう。"
"3502-83-メグ" = "……あ、そうだ！"
"3502-84-メグ" = "ちょっと待っててね、風紀委員長！すぐ行ってくるから！！"
"3502-89-メグ" = "お待たせ！"
"3502-90-メグ" = "はい、これ！"
"3502-95-ヒナ" = "これは……アイス？"
"3502-96-ヒナ" = "……ゴリゴリ君を、私にくれるの？"
"3502-97-メグ" = "うん！いっぱい買って、みんなに分けようと思ってたんだ。#nヒナ委員長にも1個あげる！"
"3502-98-メグ" = "今日暑いし、こういう日はゴリゴリ君に限るよね！"
"3502-99-メグ" = "……あっ。"
"3502-100-メグ" = "そういえば、さっきプレゼント壊してたよね……もしかして、こういうのイヤだった？"
"3502-101-メグ" = "ご、ごめんね！ついクセで……。"
"3502-105-ヒナ" = "……ううん。違うわ。"
"3502-106-ヒナ" = "ありがとう、メグ。"
"3502-107-メグ" = "……うん？これはいいの？さっきと何が違うんだろう……？"
"3502-108-ヒナ" = "それはカスミに聞けば分かるはずよ。"
"3502-109-ヒナ" = "…………。"
"3502-110-ヒナ" = "……メグ。"
"3502-111-メグ" = "うん？"
"3502-112-ヒナ" = "あなたは今、3年生よね？#nカスミとは随分と仲良さそうだけど……。"
"3502-113-ヒナ" = "温泉開発部は以前から存在している部活……#n部員の数は今よりだいぶ少なくて、15名くらいだったはず。"
"3502-114-ヒナ" = "以前はメグが部長を務めていたと思うのだけど。#nカスミは後から入部したのよね？"
"3502-115-メグ" = "うん、そうだよ！カスミ部長が、自分が部長をやるって言ったから、お願いしたの。"
"3502-116-メグ" = "さすが風紀委員長！何でも知ってるんだね！"
"3502-117-ヒナ" = "何でもってわけじゃないわ……。"
"3502-118-ヒナ" = "……。"
"3502-119-ヒナ" = "じゃあ、カスミが先に「部長をやる」って言ったのね？"
"3502-120-メグ" = "うん。"
"3502-121-ヒナ" = "……そう。"
"3502-122-メグ" = "……あ、ちょっと違うかも？"
"3502-123-ヒナ" = "……？"
"3502-124-メグ" = "正確には「何がしたい？」って言われて、「温泉だけ掘ってたい！」って答えたの。"
"3502-125-メグ" = "そしたら、カスミ部長が「じゃあ、そうさせてやろう」って言ってくれて。"
"3502-126-メグ" = "その後からは、本当に温泉を掘るだけの仕事を任されたんだ！#n部員もいっぱい増えたよ！"
"3502-130-ヒナ" = "……そうなのね。"
"3502-131-ヒナ" = "だいたい予想通りだわ。[ruby=・]あ[/ruby][ruby=・]そ[/ruby][ruby=・]こ[/ruby]の連中は、そういった口約束を重視してきたもの。"
"3502-134-メグ" = "……うん？どういうこと？"
"3502-135-ヒナ" = "いえ、なんでもないわ。こっちの話。"
"3502-136-ヒナ" = "では先に失礼するわね。今日は暑いし、メグも熱中症には気をつけて。#nそれとカスミには……"
"3502-137-ヒナ" = "……あまり騒ぎを起こさないように、と伝えておいて。"
"3502-138-メグ" = "うん！分かった～！風紀委員長も気をつけてね！"
"3502-142-メグ" = "んじゃ、部長のところに帰ろっと。"
"3502-144-メグ" = "……って事があってね！"
"3502-145-メグ" = "あ、風紀委員長にこう言われたの。"
"3502-146-メグ" = "「次にこのような行為が発覚したら、その時は確実に制裁を与える。」"
"3502-147-メグ" = "「ゲヘナでは、昔の悪癖は慎むように。」――だって！"
"3502-151-カスミ" = "ひいいいいっ！！！"
"3502-152" = "プレゼント？"
