[translation]
"10034170-1" = "2日前：勝利に向かって"
"10034170-4-アイリ" = "もう残り2日……。"
"10034170-5-アイリ" = "そろそろ、通しで合わせてみない？"
"10034170-6-ヨシミ" = "そうね。ちょっと緊張するけど。"
"10034170-7-ナツ" = "緊張、それは努力の証。"
"10034170-8-ナツ" = "重ねてきた努力を裏切りたくないと思うからこそ、身体はどうしても強張る。"
"10034170-9-ナツ" = "過程より、思い出より……私たちは今、結果が欲しい。"
"10034170-10-ナツ" = "つまり我々はセムラを手に入れる！数多[ruby=しかばね]の屍を[/ruby]乗り越えてでも！！"
"10034170-12-カズサ" = "また何か始まった……。"
"10034170-13-ヨシミ" = "私たちが屍になる可能性のほうが高そうだけど……。"
"10034170-14-ヨシミ" = "ま、ナツの発言にしては悪くないね。"
"10034170-15-ヨシミ" = "さあ、全員で頑張るわよ！"
"10034170-17-ヨシミ" = "えいえい、おーっ！"
