[translation]
"10034120-1" = "6日前：王道の解決策"
"10034120-3-ヨシミ" = "……辛い。"
"10034120-4-ヨシミ" = "練習より、理論を勉強する方が遥かに辛い……。"
"10034120-5-カズサ" = "同感、しんどいねこれ……"
"10034120-9-アイリ" = "まあまあ……。"
"10034120-10-アイリ" = "でもほら、練習してても直らない部分だって、理論が分かればすんなり行くかもよ？"
"10034120-11-アイリ" = "だからまずは、教本に沿って基礎練をしてみよう！"
"10034120-12-ナツ" = "時には先人の道に従うこともまた近道……ってね。"
"10034120-13-カズサ" = "そりゃそうなんだけどさぁ……。"
"10034120-14-カズサ" = "まさか、ここに来て本を読まないといけないなんて……。"
"10034120-19-ヨシミ" = "な～に？その自信無さげな顔は？"
"10034120-20-カズサ" = "……先に不満の声を上げたのはそっちでしょ？"
"10034120-21-ヨシミ" = "うるさいわねっ！！"
"10034120-22-ヨシミ" = "ほら、さっさと始めるわよ！！"
