[translation]
"10034150-1" = "4日前：部のアイデンティティ"
"10034150-3-ヨシミ" = "……お腹空いた。"
"10034150-4-カズサ" = "まだ練習始まってすらないんだけど。"
"10034150-5-ヨシミ" = "しょうがないじゃん、お腹が空いたんだから。"
"10034150-6-カズサ" = "はぁ、まったく……。"
"10034150-10-ナツ" = "でも最近は練習ばっかりで、お菓子不足だったねぇ。"
"10034150-11-ナツ" = "車にも燃料が必要なように……私たちにもまた、スイーツが必要。"
"10034150-12-ナツ" = "特訓中とはいえ、部のアイデンティティを失うわけにもいかないし？"
"10034150-13-ヨシミ" = "アイデンティティって言うほどのもの？"
"10034150-14-カズサ" = "まあでも、いつも食べてるのは確かだし……。"
"10034150-15-カズサ" = "間違ってはないんじゃない？"
"10034150-20-アイリ" = "あはは……。"
"10034150-21-アイリ" = "じゃあみんなで、ちょっとお菓子食べてからにしよっか？"
