[translation]
"70012010-1" = "ON AIR：ゲヘナ（１）"
"70012010-5-キララ" = "足りない！"
"70012010-6-エリカ" = "何が？"
"70012010-7-キララ" = "キラキラが！"
"70012010-8-エリカ" = "またずいぶん漠然とした……。"
"70012010-9-エリカ" = "……要は「惹かれることがない」って解釈でいい？"
"70012010-10-キララ" = "さすがエリカちゃん！それそれ。"
"70012010-11-キララ" = "あんま面白いことがないっていうか……最近のゲヘナってなんか静かじゃない？"
"70012010-12-エリカ" = "そう……？先週も部室棟の本館が爆発してなかったっけ。"
"70012010-13-キララ" = "あれから1週間も経ってるんだよ？復旧だって終わってたし。"
"70012010-14-キララ" = "なーんかもうちょっと楽しくて、おもしろいことないかなー。"
"70012010-15-エリカ" = "キララちゃんをアゲてくれるようなネタは……なかなかねぇ。"
"70012010-19-キララ" = "おぉ？エリカちゃん、あれ見て。"
"70012010-20-エリカ" = "うん？なんかある？"
"70012010-26-イロハ" = "ですから、ただ座って話すだけで――"
"70012010-27-通りすがりの生徒" = "え、めんどくさ……。"
"70012010-28-通りすがりの生徒" = "悪いんだけど、カレー温めないとだから。それじゃ。"
"70012010-32-イロハ" = "めんどくさいって……。"
"70012010-33-イロハ" = "まあ……だから私も人を探しているわけですが。"
"70012010-37-イロハ" = "……ん？"
"70012010-38-イロハ" = "私は今、面倒ごとを避けるために面倒ごとを……？"
"70012010-39-イロハ" = "つまり、めんどくささはプラマイゼロ……？"
"70012010-40-イロハ" = "……。"
"70012010-41-イロハ" = "いや、これ以上考えるのはやめておきましょう。胃の調子が悪くなるだけですね……。"
"70012010-42-イロハ" = "にしても、どこで代わりを……。"
"70012010-43-イロハ" = "お礼で釣りたいところですが、用意できるのはマコト先輩のサインくらいですし……#n欲しがる人もいないでしょうね……。"
"70012010-47-キララ" = "ねえね[ruby=パンデモニウム・ソサエティー]え、万魔殿のイ[/ruby]ロハちゃん……だよね？"
"70012010-48-エリカ" = "なんか困ってるみたいだけど、どうしたの？"
"70012010-49-イロハ" = "あなた達は……。"
"70012010-50-イロハ" = "……。"
"70012010-51-イロハ" = "あっ！"
"70012010-52-イロハ" = "適任者、発見です。"
"70012010-54" = "少し前のこと……"
"70012010-55-マコト" = "キシシッ、そういうことだ。"
"70012010-56-イロハ" = "え、急にどうしたんですか？"
"70012010-57-マコト" = "ただ言いたかったのだ。そういう気分の時もあるだろう？"
"70012010-58-マコト" = "気分とは、イロハが思っているよりも重要なんだ。"
"70012010-59-イロハ" = "はいはい、そうですね……。"
"70012010-60-マコト" = "キシシッ。それはそうと、[ruby=われわれ]万魔殿[/ruby]の校内放送の準備は順調か？"
"70012010-61-マコト" = "ゲヘナ各地の出来事を紹介するコーナーもできたと聞いたぞ。"
"70012010-62-イロハ" = "ええ、まあ。"
"70012010-63-イロハ" = "というか、勝手に朗読コーナーを入れるなと言いましたよね？#n予算の浪費はしないようにと何度言えば……。"
"70012010-64-イロハ" = "そもそも、ちゃんと聞いてる人なんて居ないじゃないですか。"
"70012010-65-マコト" = "まだまだだな。だから良いのだよ。キシシッ！"
"70012010-66-イロハ" = "どういうことですか。"
"70012010-67-マコト" = "誰も興味がない……すなわち何をやっても良いということだ。"
"70012010-68-マコト" = "たとえば、決定した予算案のことを話しておけば……。"
"70012010-69-マコト" = "「風紀委員会の予算削減は公発表済み」――なんてことも言えるのだ！キキキッ。"
"70012010-70-イロハ" = "しょうもない理由ですね。"
"70012010-71-マコト" = "ともかく！誰も気に留めないのが校内放送のいいところだ。"
"70012010-76-万魔殿のメンバー" = "ご報告です！"
"70012010-77-万魔殿のメンバー" = "校内放送の担当が、突然辞退を申し出ました！"
"70012010-78-マコト" = "なにぃっ！？なぜだ！！？"
"70012010-79-万魔殿のメンバー" = "わ、わかりません……！#n引き留めたものの呆然とした様子で、一身上の都合とばかり……。"
"70012010-80-万魔殿のメンバー" = "急いで代わりを探していますが、未だ適切な人材が見つからず……。"
"70012010-81-マコト" = "どうしてこんなことに……！？"
"70012010-82-イロハ" = "はぁ……仕方ありません。今回の放送はお休みですね。"
"70012010-83-マコト" = "それは有り得ない！！"
"70012010-84-イロハ" = "はい？だって聞いている人がいるわけでもないじゃないですか。#nそれがいいところなのでしょう？"
"70012010-85-マコト" = "そういう問題ではない――！！"
"70012010-86-マコト" = "放送を休むというのはまた別の問題なのだ！"
"70012010-87-マコト" = "これは万魔殿……いいや、マコト様の威信に関わる重要案件だ！！"
"70012010-88-イロハ" = "誰もそんなこと気にしないと思いますけどね。"
"70012010-89-マコト" = "すぐに代わりを見つけてこい！！"
"70012010-90-イロハ" = "いや、ですから……話聞いてましたか？#n放送の経験者なんて早々見つからな――"
"70012010-91-マコト" = "この際だ。未経験でも構わん！！"
"70012010-92-マコト" = "なんとしてでも放送するのだ――！！"
"70012010-93-イロハ" = "ワガママもいい加減にしてください！！！"
"70012010-95-エリカ" = "そんなことが……。"
"70012010-96-イロハ" = "はあ……分かっていただけましたよね……徒労もいいところだって……。"
"70012010-97-キララ" = "超たのしそ～っ！！"
"70012010-98-イロハ" = "……。"
"70012010-99-イロハ" = "はい？"
"70012010-100-キララ" = "エリカちゃん、どうどう？せっかくだしやってみない？"
"70012010-101-エリカ" = "まあ、いい経験になりそうだよね。#n素人でもよければだけど……。"
"70012010-102-イロハ" = "本当ですか……？"
"70012010-103-キララ" = "うんっ！！何を準備したらいい！？"
"70012010-104-イロハ" = "あ……別にやることが決まっているわけではないので……。"
"70012010-105-イロハ" = "というか本当に……本気なんですよね……？"
