[translation]
"2601602-1" = "バカンスが始まると……"
"2601602-2-？？？" = "ふむふむ。見渡す限りの白い砂、果てしなくどこまでも続く水平線……。"
"2601602-4-チアキ" = "これは……海ですね！"
"2601602-5" = "[s] \"一目瞭然だね。\""
"2601602-6-チアキ" = "たしかに、誰が見てもそう感じると思います！"
"2601602-7-チアキ" = "ですが、取材は事実の積み重ねによってできていますから！"
"2601602-8-チアキ" = "くんくん、ここはスクープのニオイがしますよ！"
"2601602-9" = "[s] \"スクープってニオイがするものなの？\""
"2601602-10-チアキ" = "はい！まあ、全部がそうというわけではありませんが……。"
"2601602-11-チアキ" = "今回の特集記事は「告発！海岸の悪徳商人に迫る！」です。"
"2601602-12-チアキ" = "バカンスで浮かれている客を狙う、わる～いお店に潜入取材します！"
"2601602-13-チアキ" = "複数回の情報提供を受けているので、ほぼクロと言って間違いないでしょう！"
"2601602-14-チアキ" = "では行きますよー？いざ、突撃ー！"
"2601602-21-ぼったくられた観光客" = "何なんだ、この店は！値段の割に量が少なすぎるだろ！"
"2601602-22-ぼったくられた観光客" = "アジフライを頼んだのに、なんだこのちっこいのは！"
"2601602-23-ぼったくられた観光客" = "全部口コミに書くからな！"
"2601602-24-悪徳商人A" = "はっ！口コミくらい好きにしろよ。"
"2601602-25-悪徳商人B" = "こっちは営業妨害で訴えてやることもできるんだぜ？"
"2601602-26-ぼったくられた観光客" = "く、くそっ！もう二度と来ないからな！"
"2601602-30-悪徳商人A" = "へへっ、あざしたー。"
"2601602-31-悪徳商人B" = "デカい口叩きやがって。"
"2601602-32-悪徳商人A" = "口コミなんて書いたところで、広まる頃には店仕舞いしてるに決まってんだろ。"
"2601602-33-悪徳商人A" = "にしてもやるな。小魚を「特大アジフライ」って名前で売るなんて。"
"2601602-34-悪徳商人B" = "へへっ。こういうときにしっかり稼いどかねぇと！"
"2601602-35-悪徳商人B" = "メニュー表にだけ値段書いてすぐ回収すりゃ、確認できねえからな！"
"2601602-36-悪徳商人A" = "さて、次はどいつから搾り取ろうか……。"
"2601602-42-悪徳商人A" = "いらっしゃい！"
"2601602-43-悪徳商人B" = "空いてる席にどうぞ！"
"2601602-47-チアキ" = "おー！前評判よりは良いお店ですね！"
"2601602-48-悪徳商人A" = "！！！"
"2601602-49-悪徳商人A" = "あ、あいつは……！？"
"2601602-50-悪徳商人B" = "誰だ？"
"2601602-51-悪徳商人A" = "馬鹿野郎！例の週刊万魔殿の記者だよ！"
"2601602-52-悪徳商人B" = "言われてみれば……！それに、隣にいるのはシャーレの先生か？"
"2601602-53-悪徳商人A" = "なんでも、週刊万魔殿の記者は一度特ダネに食いついたら何が何でも放さないらしい。"
"2601602-54-悪徳商人A" = "しかも、読者層はあのゲヘナ生だ……！"
"2601602-55-悪徳商人B" = "たしか……さっき「前評判」がどうのこうのって言ってたよな……。"
"2601602-56-悪徳商人A" = "ど、どうする！？"
"2601602-57-チアキ" = "すみませーん！メニューお願いしまーす！"
"2601602-58-悪徳商人A" = "は、はい！ただいまお持ちします！"
"2601602-59-悪徳商人B" = "とりあえず、安くした値段書いて渡せ！"
"2601602-60-悪徳商人A" = "わ、分かった！そっちも料理ちゃんと作れよ！量も大盛りで！"
"2601602-61-チアキ" = "では、これをお願いします！"
"2601602-62-悪徳商人A" = "はい！少々お待ちください！"
"2601602-66-チアキ" = "おや？そんなに高くないですね。"
"2601602-67-チアキ" = "量が少ないって話もありましたし……料理が来たら検証してみましょう！"
"2601602-68-チアキ" = "では、先に準備を……！"
"2601602-72" = "[ns] \"チアキ？それは？\""
"2601602-73-チアキ" = "メジャーと計量器です！主観だけで記事は書けませんので！#nでないとまたスープみたいな雑誌とか言われてしまいます！"
"2601602-74-チアキ" = "主観が大事な時もありますが、今回ばかりは客観的事実が重要ですからね！"
"2601602-75-チアキ" = "ふふふ、1グラムの誤差も、見逃しませんよ～？"
"2601602-77-悪徳商人たち" = "！？"
"2601602-78-悪徳商人A" = "計量器だと！？"
"2601602-79-悪徳商人A" = "そんなもの使われたら言い逃れできないぞ！"
"2601602-80-悪徳商人B" = "そもそも、潜入取材ってこっそりするもんじゃないのか……？"
"2601602-81-悪徳商人A" = "どうする？特大どころか、普通サイズのアジもないが……。"
"2601602-85-悪徳商人A" = "……そ、そうだ！"
"2601602-88-悪徳商人A" = "ご、ご注文の「特大アジフライ」です！"
"2601602-92-チアキ" = "アジ……フライ？"
"2601602-93-チアキ" = "これ、マグロ？に見えますけど……。"
"2601602-94-悪徳商人A" = "い、今イベント中でして！アジの代わりに本マグロを提供しております！"
"2601602-95-悪徳商人A" = "本日限りの特別イベントです！"
"2601602-96-チアキ" = "なるほど！これはたしかにすごいですね！"
"2601602-97-チアキ" = "うーん……。値段も高くないし……。#n量にいたっては、お腹がパンパンになりそうなくらいある。"
"2601602-98-チアキ" = "どうにも悪徳商人って感じじゃありませんねぇ。#n情報提供者が間違えていたんでしょうか？"
"2601602-99" = "[s] \"悪い店じゃなかったのなら、いいことじゃない？\""
"2601602-100-チアキ" = "そうですね！むしろ褒めるべきです！"
"2601602-101-チアキ" = "これは嬉しい誤算ですね！少し待っててください！"
"2601602-109-悪徳商人A" = "な、何とか乗り切ったか……。"
"2601602-110-悪徳商人B" = "満足してるみたいだし、記事にされることはないだろう……。"
"2601602-111-悪徳商人A" = "これで今年も無事に――"
"2601602-120-生徒A" = "良かった！まだ席空いてるよ！"
"2601602-121-生徒B" = "急いで来た甲斐あったね！"
"2601602-123-悪徳商人A" = "な、なんだ！？この人数！？"
"2601602-124-チアキ" = "おお～！特集の効果はバッチリみたいですね！"
"2601602-125" = "[s] \"すごい数のお客さんが来てるけど！？\""
"2601602-126-チアキ" = "はい！安くて量も多い、最高のお店があるって――"
"2601602-127-チアキ" = "ついさきほど、「週刊万魔殿」のSNSに速報を出したんです！"
"2601602-128-生徒A" = "投稿通り、めちゃくちゃ安いね！"
"2601602-129-生徒A" = "チアキちゃんハロー！あっ、先生もこんにちは！"
"2601602-130-チアキ" = "ハローです！良心的なお店なので、たくさん頼んで応援しましょう！"
"2601602-132-生徒B" = "よーし！すみません！メニューのここからここまで、全部ください！"
"2601602-133-悪徳商人A" = "う、うわあああ！メニューの値段、安くしたままだぞ！"
"2601602-134-悪徳商人B" = "どうすんだ！今更変えられねぇぞ！"
"2601602-135-生徒Q" = "すみませーん！こっちも注文お願いしますー！"
"2601602-143-悪徳商人A" = "や、ヤバい！一気に注文が！"
"2601602-144-悪徳商人B" = "このままじゃ食材を全部持っていかれちまう！"
"2601602-145-悪徳商人A" = "す、すみませんお客さん！もう材料がなくなってしまいまして！"
"2601602-146-悪徳商人A" = "本日の営業は終了です！"
"2601602-148-生徒Q" = "え、本当に？もう残ってないの？"
"2601602-149-生徒R" = "まだ残ってるんじゃない？"
"2601602-151-悪徳商人A" = "はい！？"
"2601602-157-生徒Q" = "見て！こっちの冷蔵庫にまだたくさん残ってるよ！"
"2601602-158-悪徳商人A" = "そ、それは明日の食材で……！"
"2601602-159-生徒R" = "今日使い切ったら明日休めるでしょ！"
"2601602-160-悪徳商人B" = "か、勘弁してくれー！"
"2601602-161-チアキ" = "あははっ！良いお店を紹介するのは、なんだか気持ちがいいですね！"
"2601602-168-悪徳商人B" = "順番にお作りしているのでもう少々お待ちください！"
"2601602-170-悪徳商人A" = "もうおしまいだー！"
"2601602-173" = "[ns] \"店員さん、なんか泣いてない……？\""
"2601602-174-チアキ" = "あれが幸せの涙というものですね！#n「週刊万魔殿」が地域に貢献出来て、私も嬉しいです！"
"2601602-176" = "（その後も、噂を耳にしたお客さんが絶え間なく訪れた）"
"2601602-177" = "（お店をあとにすると、なぜか周りの人たちから拍手と激励を受けた）"
