[translation]
"10041060-1" = "第6話;ビッグシスタールーム"
"10041060-7-セイア" = "ビッグシスターアルゴリズム……。"
"10041060-9-リオ" = "……私の汚点よ。作ったことも、使ったことも。"
"10041060-10-ネル" = "汚点……？"
"10041060-11-ネル" = "お前の口からそんな言葉が出るとはな。"
"10041060-12-リオ" = "事実だもの。効率ばかりを追っていた、当時の私は迷わなかった。"
"10041060-13-リオ" = "……今なら、絶対にこんなもの作らないわ。"
"10041060-14-セイア" = "そうまで言いながら……システムを使うつもりなのかい？#n……そもそも、使用可能な状態で放置されているのなら、それはそれで問題だと思うのだが。"
"10041060-15-リオ" = "……ミレニアムを去る時に隔離したの。#n二度と使うことができないよう。"
"10041060-16-リオ" = "でも今は他に方法がない。解決するにはこれを使うしか……"
"10041060-17-リオ" = "これは……あくまで私の決定であり、私の責任よ。"
"10041060-22-リオ" = "だから二人は気にしなくていい。#nなんなら帰ってもらっても構わないわ。"
"10041060-27-ネル" = "……は？"
"10041060-28-ネル" = "待て、帰れって何だよ？"
"10041060-30-リオ" = "二人はこの「罪」と関係ない。私一人が背負うべきなのよ。"
"10041060-31-ネル" = "そんなことは聞いてねえ。あたしが帰ったらアレは誰が使うんだよ？"
"10041060-32-リオ" = "だから、ここからは私が……"
"10041060-33-ネル" = "自分で行くのか？あの場所に？"
"10041060-37-リオ" = "貴女のお陰で、最低限のルートは確保できたわ。不可能ではないはずよ。"
"10041060-38-リオ" = "それにビッグシスタールームに入るには、私の生体認証が必要よ。#n無理やり突破しようとすれば、厄介なことになるわ。"
"10041060-39-リオ" = "自分の認証を使う以上、記録は残るけれど……今はそれを懸念している場合かしら？"
"10041060-44-セイア" = "君が犯人と思われかねない。"
"10041060-45-リオ" = "ええ、でもそれは重要ではない。"
"10041060-46-セイア" = "重要だろう。"
"10041060-50-セイア" = "エンジニア部やゲーム開発部の件だってそうだ。#n君が怪しまれる状況となっている。"
"10041060-51-リオ" = "……でもこれは私の罪だわ。"
"10041060-52-リオ" = "これ以上他の人にリスクを負わせるわけにはいかないの。"
"10041060-57-ネル" = "ハハッ……！"
"10041060-62-リオ" = "……？"
"10041060-63-セイア" = "ガッカリだ。"
"10041060-64-リオ" = "……ガッカリ？"
"10041060-65-セイア" = "そうだ。またそういって私を除け者にするつもりかい？"
"10041060-66-セイア" = "私を思ってのことも一度までは許すが……"
"10041060-67-セイア" = "二度目についてはその限りでは無いのだよ。"
"10041060-68-リオ" = "私はそういうつもりじゃ……。"
"10041060-73-ネル" = "散々こき使っておいて、じゃあ一人で犠牲になりますってか？#nそういうとこがムカつくって言ってんだよ。"
"10041060-77-リオ" = "っ……。"
"10041060-79-セイア" = "我々の考えは同じなようだ。"
"10041060-80-ネル" = "ああ。こんな扱いをされちゃあな。"
"10041060-85-リオ" = "どういうことかしら。"
"10041060-86-セイア" = "率直に言う。"
"10041060-92-セイア" = "リオ、君を信用することはできない。"
"10041060-96-リオ" = "なっ……！？"
"10041060-97-リオ" = "信用できない……？"
"10041060-98-ネル" = "どうやったってお前には無理だろ、あそこに入るの。"
"10041060-99-ネル" = "あたしのルートを参考にするだぁ？道だけ覚えればいいと思ってんのか？"
"10041060-100-ネル" = "ぶっちゃけお前よりもこっちのお嬢ちゃん……えーっと。"
"10041060-101-セイア" = "百合園セイアだ。"
"10041060-102-ネル" = "セイアの方がよっぽど信用できるぞ。"
"10041060-104-リオ" = "そ、れは……。"
"10041060-106-セイア" = "君のために言う。"
"10041060-107-セイア" = "今、君は感情に振り回され作戦を台無しにしようとしている。#n潜入が目的ならば、君ではなく私たちがやるべきだ。"
"10041060-108-セイア" = "あの機械が君の作品とはいえ、私たちを外すべきではない。作戦とは無関係な事項だろう？"
"10041060-109-ネル" = "そう言うこった。"
"10041060-110-ネル" = "突撃はあたしが受け持つ。そんであいつらの位置を探る。"
"10041060-111-ネル" = "今度こそ、あの気味わりぃ機械をぶっ潰してやるよ。"
"10041060-112-ネル" = "そうすればあたしもセイアも……"
"10041060-116-ネル" = "お前も気が楽になるはずだ……だろ？"
"10041060-121-リオ" = "……！"
"10041060-122-セイア" = "この方法しかない。このままだと、君は今回の件が終わっても何も変わらないだろう。"
"10041060-123-セイア" = "……今日一日、君と話して分かったことがある。君は疲れる人だ。"
"10041060-124-セイア" = "私も大概面倒な性格だが……どうやら君は私の比ではないようだね。"
"10041060-126-ネル" = "見る目あるじゃねえか。"
"10041060-127-リオ" = "二人とも……。"
"10041060-128-セイア" = "時間がない。詳細は後にしよう。"
"10041060-129-ネル" = "いいねぇ、さっぱりしてて！本当はこういう性格だったのか？"
"10041060-130-セイア" = "期待に沿えなくて済まないが……もっと周りの居心地を悪くさせるような性格だよ。"
"10041060-131-セイア" = "……気になるなら、後で披露しようか。"
"10041060-132-ネル" = "面白い冗談だな！機会があったら見せてくれよ。"
"10041060-134-リオ" = "こんなはずでは……。"
"10041060-139-ネル" = "おい、何やってんだ。"
"10041060-145-ネル" = "道案内、するんだろ？"
