[translation]
"10041050-1" = "第5話;惑い"
"10041050-4" = "――1時間前。"
"10041050-7" = "セイアの出発後、リオの隠れ家にて。"
"10041050-12-リオ" = "……ネル。"
"10041050-17-ネル" = "あん？"
"10041050-18-リオ" = "一つ聞きたいことがあるの。"
"10041050-19-リオ" = "ただ、業務とは関係のない質問なのだけれど……。"
"10041050-23-ネル" = "何だよ。"
"10041050-24-リオ" = "この質問をした時、貴女がどういう反応をするか、#nこれまでの情報を鑑みればある程度は予想できる。でも、まだ確信が持てないの。"
"10041050-25-ネル" = "で？"
"10041050-26-リオ" = "これを聞いたらあなたは――"
"10041050-35-ネル" = "っとによぉ！？"
"10041050-36-ネル" = "いい加減にしろよな！？"
"10041050-37-ネル" = "言いたいことがあるなら早く言え！"
"10041050-43-リオ" = "……ごめんなさい。"
"10041050-44-リオ" = "……[ruby=ゆりぞの]百合園[/ruby]セイアの件よ。"
"10041050-45-ネル" = "何かトラブルでも起こしそうだからか？それとも情緒不安定に見えるからか？"
"10041050-46-リオ" = "いえ、彼女の能力は申し分ない。信頼に値するわ。"
"10041050-47-リオ" = "ただ……さっきのやり取りが。"
"10041050-48-ネル" = "……なんか言ってたか？"
"10041050-52-ネル" = "……ああ。そういえばちょっと言い争ってたな。"
"10041050-53-リオ" = "ええ。彼女はすぐに納得して、反省の言葉を口にした。"
"10041050-54-リオ" = "でも、他人に見せる姿と本音は違うのだと。#n私も最近理解し始めるようになったの。"
"10041050-55-リオ" = "だから……もし、彼女が……"
"10041050-59-リオ" = "私の発言で……気分を害していたりなどしていたら……と。"
"10041050-63-ネル" = "……は？"
"10041050-64-リオ" = "負の感情を抱いてはいないだろうか、という懸念よ。"
"10041050-65-リオ" = "よく理解できないというなら説明を変えるわ。彼女の内面と感情的な問題で――"
"10041050-66-ネル" = "いや、分からないとかじゃなくて。"
"10041050-67-ネル" = "つまり、嫌われてたらどうしよう？ってことだよな？"
"10041050-68-リオ" = "……そこまでは言ってないわ。"
"10041050-69-ネル" = "いや、そういうことだろ。"
"10041050-70-リオ" = "でも……あの時、私はああ言うしかなかった。"
"10041050-71-リオ" = "これは学園に関わる問題よ。自分の感情よりも遥かに重大だわ。"
"10041050-72-リオ" = "彼女を説得しなければならなかった。#n説得するには、全ての理由を挙げるしかなかった。"
"10041050-73-リオ" = "けれど、それはそれとして。#n彼女が私に否定的な眼差しを向けると考えると……"
"10041050-74-リオ" = "私は……"
"10041050-79-ネル" = "んっとによぉ！"
"10041050-80-ネル" = "気にするとこがそこかよ！？"
"10041050-81-ネル" = "その程度で嫌うならそもそも協力関係なんかになってねえだろ！？"
"10041050-82-ネル" = "あれはそういうのでもないことくらい、見りゃ分かんだろ。"
"10041050-83-ネル" = "それに、譲れねえラインだったんだろ？じゃあ仕方ないんじゃねえの？"
"10041050-88-ネル" = "つか、言いたい放題言った後で、うじうじ悩むなよ。"
"10041050-89-ネル" = "言った言葉の取り返しなんてつかねえんだから。"
"10041050-90-ネル" = "ってか、あたしのことはどうなんだ？"
"10041050-91-ネル" = "何であたしには聞いてこないんだ？"
"10041050-96-リオ" = "……美甘ネル。"
"10041050-97-リオ" = "貴女はその場で反論するもの。今までのデータがそれを証明しているわ。"
"10041050-98-リオ" = "私がどのように接しても、貴女は自分の感情と判断を優先する。違う？"
"10041050-99-ネル" = "それは単細胞って意味か？"
"10041050-100-リオ" = "別にそういう意味ではなかったのだけれど……。"
"10041050-104-リオ" = "理解を得るにあたって、その表現が分かりやすいと言うのであれば……そうね。そうとも言えるわ。"
"10041050-109-ネル" = "あたしが単細胞なのは認めるけど、言っていいことと悪いことがあるだろうがよ！#n今まで我慢してたけどもう無理だ！"
"10041050-115-リオ" = "ち、ちょっと……！今データ検索を……！ "
"10041050-122-リオ" = "……！！監視網に反応が！"
"10041050-123-リオ" = "ふぃ、フィットネスセンターよ！ここに向かってちょうだい、ネル！"
"10041050-124-ネル" = "あーもう！！！知るかよ！！"
