[translation]
"10041070-1" = "第7話;エピローグ"
"10041070-9-トキ" = "……ヴァルキューレへの引き渡し、完了しました。ミッションコンプリートです。ブイ。"
"10041070-11-カリン" = "すごい数だったな……ミレニアムEXPOが中止になっていてもおかしくなかった。"
"10041070-12-アスナ" = "楽しかったね～！トリニティ生たちもみんな「これぞミレニアム！」とか言ってさ！"
"10041070-13-カリン" = "ミレニアムのイメージは、少し歪んだ気もするが……。"
"10041070-15-アカネ" = "それでも事態の規模に比べれば、この程度で片を付けたのは上出来だと思いますよ。"
"10041070-16-ネル" = "……あの会計からは？なんか言われなかったか？"
"10041070-17-アカネ" = "もちろんお怒りの様子ですが……結果的には上手くいきましたので。#n先生との合同作戦でもありましたし。"
"10041070-18-カリン" = "次からは可能な限りの情報共有を、と。先生には一言あるらしい。だがそれくらいだな。"
"10041070-19" = "[s1] \"結局怒られるのは私なんだね……。\"\n[s2] \"ふ、ふふ……怒られるのは慣れてるから大丈夫。\""
"10041070-22-カリン" = "ちなみに、私たちからも言いたいことがある。"
"10041070-23-カリン" = "セミナーはともかく、せめて私たちには言って欲しかった。トリニティのVIPと組む作戦だと。"
"10041070-24-カリン" = "それも知らずに私たちは……。"
"10041070-29-セイア" = "済まない、それは私の都合だ。ネルや先生が判断できるものではなかった。"
"10041070-30-セイア" = "私の我儘を聞いてくれただけに過ぎない。 "
"10041070-31-セイア" = "この場を借りて、謝罪させてくれ。"
"10041070-35-カリン" = "あ、いや……。"
"10041070-36-カリン" = "そ、そういうつもりで言ったわけでは……！"
"10041070-37-アカネ" = "ふふっ。すごいじゃないですか。ティーパーティーから謝罪の言葉をいただくなんて。"
"10041070-38-ネル" = "あたしからも……悪かったな。こっちも頼まれて仕方なかったんだよ。"
"10041070-39-ネル" = "この件はまた今度埋め合わせするからよ。そんな怒んなって。"
"10041070-44-カリン" = "いやっ、だからそんなつもりじゃなくて……！"
"10041070-55-セイア" = "……先生。"
"10041070-56" = "[s3] \"大丈夫？怪我はない？\"\n[s4] \"どうだった？大丈夫だった？\""
"10041070-59-セイア" = "……本当に全部知っているのだな。"
"10041070-60-セイア" = "証明するため、と心に決めていたはずが……。"
"10041070-61-セイア" = "……いや。先生がいなければ、最悪の結末を迎えていたはずだ。"
"10041070-65-セイア" = "ありがとう、先生。"
"10041070-66-セイア" = "それに……勝手をして済まなかった。"
"10041070-67" = "[s5] \"まだだよ！\"\n[s6] \"帰るまでもう少し待って。\""
"10041070-72-セイア" = "それは構わないが……"
"10041070-73-セイア" = "私よりも構うべき相手がいるのではないかね。"
"10041070-74-セイア" = "先生は……あの子の元に行ってやらなくていいのかい？"
"10041070-75-セイア" = "まだ遅くないはずだ。今頃は荷物をまとめているところだろう。"
"10041070-76-セイア" = "……大丈夫？ "
"10041070-77-セイア" = "そうか。意外だな。"
"10041070-78" = "[s7] \"まだ大丈夫。\"\n[s8] \"言葉にもタイミングがあるから。\""
"10041070-81-セイア" = "……そうか。"
"10041070-82" = "[s9] \"それより、セイアのことを考えてみない？\"\n[s10] \"なぜここに来たのか、もう少し考えてみよう。\""
"10041070-85-セイア" = "……？"
"10041070-86-セイア" = "……ああ。"
"10041070-90-セイア" = "そうだな。"
"10041070-93" = "（一時間後）"
"10041070-100-セイア" = "来たよ、リオ。"
"10041070-101-ネル" = "こっちも大まかな整理が終わったぜ。そっちは――"
"10041070-111-セイア" = "……もう帰るのか。"
"10041070-112-ネル" = "まあ……だろうよ。最初からそのつもりだったし。"
"10041070-113-セイア" = "そうか……。"
"10041070-114-ネル" = "……へぇ。"
"10041070-115-ネル" = "なんだ？そのしけたツラは。らしくねぇ。"
"10041070-119-セイア" = "……いや。"
"10041070-123-セイア" = "……そうだな。正直残念に思う。"
"10041070-124-セイア" = "ただ……どこか気持ちが冴えない。そんなところだろうか。"
"10041070-125-ネル" = "冴えない？"
"10041070-126-セイア" = "ああ。私は……"
"10041070-127-セイア" = "リオが口にしていた「証明」について。実のところ必要ないと思っている。"
"10041070-128-セイア" = "本人こそ気づいてないものの、すでに周りは……"
"10041070-132-セイア" = "……？"
"10041070-136-ネル" = "……？何だよ！また言いかけてやめんのかよ！"
"10041070-137-セイア" = "すでに周りは、彼女のことを受け入れている。"
"10041070-138-セイア" = "受け入れられないのは……彼女自身だけだ。"
"10041070-142-セイア" = "……そうか。"
"10041070-143-セイア" = "……それで先生は、あの言葉を。"
"10041070-144-ネル" = "今度は自問自答かよ？リオに似てきてねえか？マジでイライラしてくるから勘弁してくれ。"
"10041070-145-セイア" = "……すまない。悪いクセでね。"
"10041070-146-セイア" = "……それより。"
"10041070-150-セイア" = "ネル、よければ最後にもう一つだけ、助力を乞いたい。"
"10041070-151-ネル" = "あん？なんだ？"
"10041070-152-セイア" = "それは……。"
"10041070-160-セイア" = "リオ、君に話がある。"
"10041070-165-リオ" = "何かしら？"
"10041070-170-セイア" = "もう1週間ほど、ミレニアムに逗留して欲しいのだよ。"
"10041070-171-セイア" = "私やネルも残る。"
"10041070-172-セイア" = "君が守り抜いたイベントを見届けてはくれまいか。"
"10041070-178-リオ" = "何を言うかと思えば……。"
"10041070-179-リオ" = "それは無理よ、終わった話だわ。私にEXPOを楽しむ資格など無いもの。"
"10041070-180-セイア" = "……これは資格の話ではない。"
"10041070-181-リオ" = "どういう意味かしら。"
"10041070-182-セイア" = "君はすべて無事に解決したと思っているようだが、EXPOはまだ一日目だ。"
"10041070-183-セイア" = "今後も問題に見舞われないという保証はない。大小に差こそあれ、何かしらは起きるだろう。"
"10041070-184-セイア" = "そのほとんどは、つつがなくセミナーが処理するはずだ。けれど全部がそうとは限らない。"
"10041070-185-セイア" = "往々にして、例外は発生しうるものだ。"
"10041070-186-セイア" = "君ができないと言うなら、結局はセミナーや……それこそ先生が担うのだろうが。"
"10041070-192-セイア" = "果たして、それを望むのかな？"
"10041070-193-リオ" = "それは……。"
"10041070-198-リオ" = "……どう思う？ネル。"
"10041070-203-ネル" = "あたしに振んのか？"
"10041070-204-ネル" = "ま、いいんじゃん？堂々と出歩かなければバレないだろ。"
"10041070-205-ネル" = "これも生徒会長としての仕事ってやつなんじゃねえの？知らねえけど。"
"10041070-207-リオ" = "はぁ……。"
"10041070-208-リオ" = "なんだか、乗せられている気がするけれど。"
"10041070-209-セイア" = "それは違う。"
"10041070-210-ネル" = "嫌なら無理強いはできねえよな。"
"10041070-215-リオ" = "い、いえ……嫌とは言ってないわ。"
"10041070-216-リオ" = "そう、ね……"
"10041070-221-リオ" = "ええ、わかったわ。"
"10041070-225-リオ" = "1週間だけ――イベントが終わればすぐに帰る。"
"10041070-226-セイア" = "それで十分だ。私たちも力を貸そう。"
"10041070-227-リオ" = "……荷を解いてくるわ。"
"10041070-231-セイア" = "……うまくいったようだ。"
"10041070-233-ネル" = "ハハッ！なかなかのやり手じゃんか。やっぱ今回の件で仲良くなったんだろ？"
"10041070-234-セイア" = "そうとも言えるだろうか。"
"10041070-235-セイア" = "彼女は、何かにかこつけないと納得できないタイプだ。"
"10041070-236-セイア" = "誰よりもよく知っている……鏡越しで見てきたのだからね。"
"10041070-237-ネル" = "ほんっと、めんどくせえ奴だよ。"
"10041070-238-セイア" = "……ふふ。"
"10041070-239-セイア" = "そうだな。"
"10041070-243-セイア" = "……めんどうなタイプさ。"
"10041070-244" = "Code:BOX　ミレニアムに迫る影"
