[translation]
"10041040-1" = "第4話;立場と行動"
"10041040-4-セイア" = "フィットネスセンター……次に問題が起こる場所。"
"10041040-5-セイア" = "わかった。すぐに向かう。"
"10041040-9-リオ" = "待ってちょうだい。"
"10041040-10-リオ" = "貴女には他の事をお願いしたいの。#nフィットネスセンターにはネルが行くわ。"
"10041040-14-セイア" = "……？"
"10041040-19-ネル" = "あん？あたし？"
"10041040-21-セイア" = "何故だ？君たちは人目に付くわけにはいかないだろう。"
"10041040-22-セイア" = "人の往来が激しく、開けた場所だ。"
"10041040-26-セイア" = "それこそ、私の役目なのでは？"
"10041040-27-リオ" = "その方が合理的だからよ。"
"10041040-29-ネル" = "……リオ？"
"10041040-31-リオ" = "安全上の問題。簡単な理由だわ。"
"10041040-32-セイア" = "安全？"
"10041040-36-リオ" = "計算が正しければ、向こうはまだフィットネスセンターで工作の最中。"
"10041040-37-リオ" = "つまるところ……交戦する可能性も十分あり得るわ。"
"10041040-38-リオ" = "文字通り、安全上の理由よ。"
"10041040-39-リオ" = "ミレニアムの生徒でもなく、ましてや一般生徒でもない貴女には頼めない。"
"10041040-40-リオ" = "いえ……言葉を選ばなければ、貴女では力にならないのよ。"
"10041040-46-セイア" = "……だから、守って、安全なところに置いておく、か。"
"10041040-47-ネル" = "おい、リオ。言いすぎじゃねーか？"
"10041040-48-セイア" = "……そうか。"
"10041040-49-セイア" = "ここでも、同じ扱いなのだね。"
"10041040-50-ネル" = "（……ここでも？）"
"10041040-52-リオ" = "残念ながら、これは外交問題に発展する懸念もある以上、こちらも譲歩することはできないの。"
"10041040-53-リオ" = "万が一貴女に何かあったとき、それは学園同士の問題になってしまう。"
"10041040-54-リオ" = "立場ある者ならば、それを理解しているのではなくて？"
"10041040-59-セイア" = "……。"
"10041040-60-セイア" = "場所の特定はするが、行ってはならない……。"
"10041040-61-セイア" = "お預けを食らっているようなものだと思うがね。"
"10041040-62-リオ" = "それとこれとは別の話よ。"
"10041040-63-リオ" = "怪しい物を探して欲しいとは言ったけれど、それと向き合うことまでは依頼していないわ。「発見したら教えて欲しい」そう言ったのだから。"
"10041040-64-セイア" = "……そうか。"
"10041040-65-リオ" = "協力には感謝しているわ。でも、最終的なゴールは貴女のためのものじゃない。"
"10041040-66-リオ" = "理解していると思ったけれど……もし呑めないと言うのなら、ここまでね。"
"10041040-71-セイア" = "……いや、理解した。 "
"10041040-72-セイア" = "また私が先走ってしまったようだ。"
"10041040-73-セイア" = "意地を張る部分ではなかったが……つい。済まない。"
"10041040-78-リオ" = "引き続き他の部分を当たってもらえると助かるわ。"
"10041040-79-リオ" = "今までと同様、調査内容はすべて私に報告すること。#nどんな場合であっても私の指示以外の動きはしないこと。これが協力の条件よ。"
"10041040-80-セイア" = "……ああ。わかった。"
"10041040-86-ネル" = "はぁ……。"
"10041040-88-セイア" = "……様子を確認して来よう。何かあれば連絡する。"
"10041040-89-リオ" = "ええ。こちらも分析を進めるわ。分かり次第共有させてもらうわね。"
"10041040-90-セイア" = "……ああ。"
"10041040-91-セイア" = "では、先に失礼するよ。"
"10041040-96-リオ" = "さて……"
"10041040-97-リオ" = "……急がなくては。"
"10041040-106-ネル" = "それは？"
"10041040-107-リオ" = "データセンターで手に入れたチップを分析しているの。"
"10041040-108-リオ" = "手当たり次第に会場を回るより、こちらで手掛かりを見つけた方が合理的でしょう？"
"10041040-109-ネル" = "……へえ？"
"10041040-110-ネル" = "なんだ？らしくねえじゃん。もしかして気にかけてやってんのか？"
"10041040-111-リオ" = "そういう訳ではないわ。"
"10041040-112-ネル" = "褒めてんだから素直に喜べよな……。"
"10041040-116-リオ" = "褒めてたのね？"
"10041040-117-ネル" = "はぁぁぁぁ……ったくお前はさぁ。"
