[translation]
"103055-2-アヤネ" = "例の座標はこちらです！"
"103055-3-セリカ" = "地下への入口があるわ！"
"103055-4-ノノミ" = "はい、かなり深そうです……"
"103055-5-ホシノ" = "うへ～、行ってみよっか。"
"103055-15-アヤネ" = "ここは……"
"103055-16-ノノミ" = "機械の、廊下……？"
"103055-17-ホシノ" = "……進もっか。"
"103055-24-アヤネ" = "……内部は綺麗ですね。"
"103055-25-セリカ" = "こっちに階段があるわよ！"
"103055-29-セリカ" = "なにこれ……"
"103055-30-ノノミ" = "これは……"
"103055-43-ヒマリ" = "ふむ……そうですね。"
"103055-44-ヒマリ" = "これが「宇宙戦艦」で間違いないかと。"
"103055-45" = "[s] \"中に入ってみようか。\""
"103055-46-ヒマリ" = "ええ。 "
"103055-48" = "次回;ウトナピシュティムの本船（１）"
