[translation]
"103120-1" = "第12話;「勇者」の資格（１）"
"103120-5-ハナコ" = "そん、な……"
"103120-6-ハナコ" = "では、私たちが戦っている相手は一体……！？"
"103120-7-リオ" = "戦艦のスピードを落としてちょうだい！#nこのままでは、あの変形した多次元バリアに衝突してしまうわ！"
"103120-8-リオ" = "連動しなくなってしまった状態で衝突すれば――#n私たちは未知の次元に取り込まれるか、そのまま粉々になるかの二択よ！"
"103120-9-アヤネ" = "あ、あの……スピードを落としたとしても、衝突は避けられません……！"
"103120-10-アコ" = "何か他に手立ては無いのでしょうか。 "
"103120-12-リオ" = "……無いわ。あれは科学ではなく、一種の概念と化している。#nあの状態を瓦解させる手段は、現状存在し得ない……"
"103120-13-リオ" = "――ただ一つの方法を、除いて。"
"103120-14-ヒマリ" = "……！！"
"103120-15-リオ" = "あれが「アトラ・ハシースの箱舟」という概念をコピーしたものであるのなら、あれに介入できるのは……"
"103120-16-リオ" = "……同一存在である、[ruby=・   ・]箱舟[/ruby]だけでしょうね。"
"103120-17-ヒマリ" = "同一の、箱舟……？ "
"103120-18-ヒマリ" = "……！！#nまさか……！"
"103120-19-ユウカ" = "い、いきなり何の話！？#n箱舟なんてどこにも――"
"103120-20-ヒマリ" = "いえ、それだけはいけません！！#nこれ以上そんな事をしてしまえば……"
"103120-21-ヒマリ" = "ビッグシスター、あなたという人は、本当に――！"
"103120-23-アコ" = "衝突6分前……！#nケンカしている場合じゃありません、なんでもいいですから、早く……！"
"103120-25-アリス" = "――アリス、理解しました。 "
"103120-30-ヒマリ" = "あ、アリス……？"
"103120-31-リオ" = "……。 "
"103120-32-アリス" = "リオ会長、こんな所にいたんですね。#nもう一度会えて、よかったです。"
"103120-34-ミドリ" = "アリスちゃん……"
"103120-35-モモイ" = "えっ、会長！？#nというか、姿を見せないでドローンを送るってどういう事！？"
"103120-37-リオ" = "……アリス、"
"103120-38-リオ" = "私は――"
"103120-39-アリス" = "はい、分かっています。"
"103120-40-アリス" = "この状況は――「名もなき神々の王女」であるアリスの力が、必要なんですよね。"
"103120-42-ユズ" = "で、でもアリスちゃん……！ "
"103120-43-モモイ" = "だ、ダメだよアリス！！"
"103120-44-モモイ" = "またあんな事に――"
"103120-45-ミドリ" = "アリスちゃん……！"
"103120-46" = "[s] \"みんな、少し落ち着いて。\""
"103120-48-アリス" = "……。 "
"103120-52" = "[ns] \"アリスの言葉を、最後まで聞こう。\""
"103120-55-モモイ" = "う、うん……"
"103120-56-ミドリ" = "アリスちゃん……言いたいこと、全部話してほしいな。"
"103120-62-アリス" = "はい――モモイ、ミドリ、ユズ。"
"103120-63-アリス" = "そしてユウカ、ヒマリ先輩、リオ会長。"
"103120-64-アリス" = "……先生。"
"103120-65-アリス" = "先生は、アリスのなりたい存在はアリスが決めていい、と言いました。"
"103120-66-アリス" = "アリスは「名もなき神々の王女」で、「ゲーム開発部」のメンバーで――#n「ミレニアムの生徒」で、「シャーレの生徒」です。"
"103120-67-アリス" = "アリスは……「魔王」で「勇者」です。 "
"103120-68-アリス" = "……アリスは、アリスが望んでいる「アリス」です。 "
"103120-69-アリス" = "だから「名もなき神々の王女」として……"
"103120-73-アリス" = "「ケイ」にお願いをします。 "
"103120-75-ケイ" = "……！！"
"103120-77-アリス" = "アリスの中にある「アトラ・ハシースの箱舟」で……今の危機を解決できるのなら、 "
"103120-78-アリス" = "それで――世界を、救えるのなら、 "
"103120-79-アリス" = "「アトラ・ハシースの箱舟」は、世界を滅亡させる兵器ではなく――#n世界を救う、勇者の武器になれます。"
"103120-80-リオ" = "アリス、それは……"
"103120-81-アリス" = "それで世界を救えるのなら、アリスはそれを望みます。 "
"103120-82-アリス" = "そうすれば、ヒマリ先輩はこれ以上リオ会長を恨まなくて良くなります。"
"103120-83-アリス" = "そしてリオ会長は、自分自身を恨まなくて良くて、隠れる必要もなくなります。"
"103120-84-リオ" = "私、自身を……？"
"103120-85-ヒマリ" = "……アリス。"
"103120-86-アリス" = "それがアリスの――"
"103120-87-アリス" = "「勇者」の、使命ですから。"
"103120-89-ケイ" = "いいえ……なりません。"
"103120-90-ケイ" = "ウトナピシュティムの本船が起動した時、あなたが奇跡的に無事でいられたのは……"
"103120-91-ケイ" = "全ての報いと、その傷を――あの「大人」が被ったからです。"
"103120-92-ケイ" = "ですが、それも間もなく終わりを迎えるでしょう。#nあの大人は傷に耐えきれず、生を終えることでしょう。"
"103120-93-ケイ" = "そのような状況で、再び「箱舟」を生成するとなれば――"
"103120-94-ケイ" = "それは……"
"103120-95-ケイ" = "……"
"103120-96-ケイ" = "王女よ、あなたは……"
"103120-107-アリス" = "ケイ。"
"103120-108-ケイ" = "王女……なりません。ここで箱舟のプロトコルを再起動したら、あなたは――"
"103120-109-アリス" = "ケイ……ごめんなさい。 "
"103120-110-ケイ" = "……何故ですか？"
"103120-112-アリス" = "あなたに、謝りたかったんです。 "
"103120-113-アリス" = "アリスはケイを理解できなかったから、拒絶して、目を背けました……#nケイから逃げようとしました。"
"103120-114-アリス" = "ケイのことが怖くて、恐れていました……#n目を背けるべきではなかったのに……"
"103120-115-アリス" = "理解できないとしても……ケイと向き合うべきでした。"
"103120-117-ケイ" = "……"
"103120-119-アリス" = "アリスはケイのことをよく知らないので、ケイの立場になって考えてみたのです。"
"103120-120-アリス" = "世界を滅亡に導く「鍵」であることが、ケイの存在理由なら……#nきっと、苦しかったと思います……"
"103120-123-アリス" = "だから、ケイもずっと苦しかったんじゃなかったのかな、とアリスは考えました。"
"103120-125-ケイ" = "王女よ、私は――"
"103120-127-アリス" = "自分のなりたい存在は、自分で決めていい、と先生が教えてくれました。 "
"103120-130-アリス" = "ケイも、ケイが望む存在になることができます。#n誰かに許可をもらう必要もありません。 "
"103120-132-ケイ" = "……"
"103120-134-アリス" = "だからアリスは「ケイ」という名前、とても良い名だと思います。 "
"103120-135-アリス" = "ケイは、間違えて読んでしまった名前です……アリスの名前みたいに。"
"103120-136-アリス" = "そこには特別な理由も、目的も、意味もありません。"
"103120-138-ケイ" = "……だから、世界を滅亡させる私という存在が、#nこれ以上苦しまないでほしいと考えているのですか？"
"103120-139-ケイ" = "私を、助けたいと？#n……そういうことなのでしょうか、王女よ。 "
"103120-141-アリス" = "……アリスは、アリスが誰かを助けられるような存在なのかは分かりません。"
"103120-142-アリス" = "アリスは「見習い」勇者ですから……でも、 "
"103120-145-アリス" = "誰かを助けたいと思う気持ちこそ――#n「勇者」の資格であると、信じています。"
"103120-147-ケイ" = "……"
"103120-156-アリス" = "…………起動開始。"
"103120-157-モモイ" = "あっ、えっ、アリス？"
"103120-158-ミドリ" = "わっ！？アリスちゃん……！？"
"103120-159-ヒマリ" = "アリス……いえ、これは＜Key＞……？"
"103120-160-リオ" = "……いえ、待ってちょうだい。"
"103120-161-アリス" = "……コードネーム「AL-1S」起動完了。"
"103120-162-アリス" = "プロトコルATRAHASISを実行します。"
"103120-163-モモイ" = "あ、アリス……"
"103120-164-ミドリ" = "だ、大丈夫なのかな？"
"103120-165-ユズ" = "……。"
"103120-170" = "[ns] \"大丈夫――アリスを信じよう。\""
"103120-174-ユズ" = "あ、アリスちゃん……！？ "
"103120-175-ミドリ" = "……アリスちゃんなんだよね？"
"103120-176-アリス" = "はい。アリスは大丈夫です。 "
"103120-177-リオ" = "……ということは、「名もなき神」の＜Key＞を服従させたのね？"
"103120-178-リオ" = "……いえ、これは服従ではなく―― "
"103120-179-アリス" = "はい。ケイがアリスのお願いを聞いてくれました。"
"103120-180-リオ" = "……？"
"103120-181-アリス" = "でも、アリス一人ではできません。#n今のアリスには、みんなの力が……"
"103120-182-アリス" = "そして、リオ会長の力が必要です。"
"103120-183-リオ" = "わ、私の……？"
"103120-187-アリス" = "顔を見せてください、リオ[ruby=・   ・]先輩[/ruby]。"
"103120-188-リオ" = "っ……わ、私は……"
"103120-197-リオ" = "……。"
"103120-198-アリス" = "……アリスは、リオ先輩と会いたかったです。 "
"103120-201-アリス" = "なんだか、前よりも痩せたように見えます。ちゃんと寝ていますか？"
"103120-202-リオ" = "アリス、私は……"
"103120-203-リオ" = "……私、は、 "
"103120-204-リオ" = "……自らの選択で、貴女を――"
"103120-206-アリス" = "リオ先輩……アリスに謝らなくても大丈夫です。"
"103120-207-リオ" = "……もちろん、貴女は私を許さないでしょうけれど……"
"103120-208-アリス" = "――許す必要はありません。"
"103120-209-アリス" = "なぜなら……仲間同士は、言葉にしなくても気持ちが伝わるものですから。"
"103120-213-リオ" = "私が……"
"103120-214-リオ" = "貴女の……「仲間」……？"
"103120-215-アリス" = "はい。リオ先輩は、アリスの仲間です。 "
"103120-216-アリス" = "リオ先輩はこうして先生やヒマリ先輩……それに、みんなを助けているのですから。だから、アリスたちはもう「仲間」です。"
"103120-217-リオ" = "で、でも私は……貴女を…… "
"103120-218-アリス" = "大丈夫です。"
"103120-219-アリス" = "序盤のボスが、後半で仲間になるのはよくあることです。#nお約束の展開だって聞きました。だから、大丈夫です。 "
"103120-223-アリス" = "リオ先輩は、この世界を守るために、誰よりも頑張った人です。"
"103120-224-アリス" = "そんなすごい人に……「アリスの仲間になってくれてありがとう」、と伝えたかったんです。"
"103120-226-リオ" = "……私は、 "
"103120-227-リオ" = "っ……私は……貴女を…… "
"103120-228-リオ" = "……。 "
"103120-234-アリス" = "では……始めます！"
"103120-235-アリス" = "ここからはアリスのターンです！！"
"103120-236-ミドリ" = "アリスちゃん！頑張って！！"
"103120-237-モモイ" = "お願いアリス、魔王城をぶっ飛ばして！！"
"103120-238-ユズ" = "アリスちゃん……お願い……！！"
"103120-249-アリス" = "……。"
"103120-251-ケイ" = "AL-1Sに接続された利用可能なリソースを確保するため、全体検索を実行。"
"103120-253-ケイ" = "リソース領域の拡大。"
"103120-255-ケイ" = "リソース名、「ウトナピシュティム」の全体リソース――9999万エクサバイトのデータを確認。"
"103120-261-ケイ" = "………現時刻をもって、プロトコルATRAHASIS稼動。"
"103120-263-ケイ" = "コード名「アトラ・ハシースの箱舟」起動プロセスを開始します。"
"103120-266-ケイ" = "王女は鍵を手に入れ、箱舟は用意された。"
"103120-271-アリス" = "名もなき神々の王女、AL-1Sが承認します――ここに、[ruby=サンクトゥム]新たな聖域が舞い[/ruby]降りん――――！"
"103120-279" = "???"
"103120-280" = "＜＜＜私の…………＞＞＞"
"103120-283" = "???"
"103120-284" = "＜＜＜私の大切な…………＞＞＞"
"103120-287" = "???"
"103120-288" = "＜＜＜私の大切な…………よ。＞＞＞"
"103120-292" = "???"
"103120-293" = "＜＜＜私の大切な…………アリス＞＞＞"
"103120-297" = "ケイ"
"103120-298" = "＜＜＜私の大切な…………アリス＞＞＞"
"103120-305" = "次回;「勇者」の資格（２）"
