[translation]
"10005030-1" = "第3話;無慈悲な尋問"
"10005030-2" = "（拠点にしていた客室へと戻り、まだ気絶している様子のバニーガールへと近づく）"
"10005030-7-バニーガール・ガード" = "んっ……んん……？"
"10005030-9-バニーガール・ガード" = "っ！？痛っ！？"
"10005030-10-バニーガール・ガード" = "口がひりひりする……って、え……？これは、どういう……？"
"10005030-12-ネル" = "おお、割とピンピンしてるじゃねぇか。見た目より根性あんな？"
"10005030-13-アカネ" = "たしかに、尋問したら喋ってくださるくらいの余力はありそうですね。"
"10005030-14-カリン" = "第一声で「尋問」とか言わなくても……。"
"10005030-15-カリン" = "あんまり心配しないで。質問に答えてくれれば、何も痛いことはしない。"
"10005030-17-バニーガール・ガード" = "気絶させて縛って監禁しておいて言う台詞かそれ！？もう十分してるじゃん！？"
"10005030-18-バニーガール・ガード" = "っていうか何なんだあんたたちは！何が目的だ！"
"10005030-19-バニーガール・ガード" = "そもそもこんなことをしておいて、ただで済むと思うなよ！あんたたちなんか、後でどうせ――"
"10005030-20-ネル" = "あぁん？"
"10005030-21-ネル" = "後でどうせ……何だ？どうなるってんだ？あん？"
"10005030-22-バニーガール・ガード" = "ひっ……！？"
"10005030-23-バニーガール・ガード" = "か、金が目的なら私を脅しても無駄だ！私はただの、一介の警備員で……そういうことには何も深く関与してない！"
"10005030-25-アカネ" = "そうでしたか、まあそれは大した問題ではありません。"
"10005030-26-アカネ" = "目的はお金ではありませんので。"
"10005030-27-アカネ" = "私たちは、とある人物を捜しに来たのです。"
"10005030-29-バニーガール・ガード" = "捜しに……？一体誰を……？"
"10005030-30-カリン" = "白……"
"10005030-31-カリン" = "じゃなかった、[ruby=くろさき]黒崎[/ruby]コユキ。まだこの船に来たばかりのはずだ、知らないか？"
"10005030-32-バニーガール・ガード" = "黒崎コユキ……？"
"10005030-33-ネル" = "しらを切るなんてこと考えるんじゃねーぞ、"
"10005030-34-ネル" = "その方が身のためだ。"
"10005030-35-バニーガール・ガード" = "いやいやいや！"
"10005030-36-バニーガール・ガード" = "本当に知らないんだって！嘘じゃない！"
"10005030-37-バニーガール・ガード" = "そもそもこの船の乗客が、全体でどれだけいると思う！？"
"10005030-38-バニーガール・ガード" = "数千を超えてるのに、そんな細かく名前なんて覚えてるわけないだろ！"
"10005030-39-ネル" = "万が一嘘だったら、てめぇ……"
"10005030-40-バニーガール・ガード" = "ひっ！"
"10005030-41-バニーガール・ガード" = "本当だ、いや、本当なんです！"
"10005030-42" = "[s1] \"本当に知らなさそうだね。\"\n[s2] \"ネル、その辺で良いんじゃない？\""
"10005030-43-ネル" = "ちっ……！"
"10005030-44-ネル" = "ちっ……！"
"10005030-45-ネル" = "はぁ……てめぇ、運が良かったな。"
"10005030-46-バニーガール・ガード" = "今日はもう十分運が悪いよ……うぅ……。"
"10005030-48-アカネ" = "なるほど、ではどうしましょう……この方には何の権限も無いみたいですし。"
"10005030-49-アカネ" = "別の方を捕まえても、乗客の名前をすべて把握している……なんて都合の良いことも無さそうです。"
"10005030-50-カリン" = "……参ったな。"
"10005030-51" = "[s3] \"名前じゃなくて、見た目は？\"\n[s4] \"目立つ子なんだし、見たことはあるかも。\""
"10005030-52-カリン" = "たしかに……一理ある。"
"10005030-53-カリン" = "たしかに……一理ある。"
"10005030-54-カリン" = "さすが先生、その可能性は大きいな。"
"10005030-55-カリン" = "静かにおとなしくしてるとは思えないし、どこにいても相当目立つ存在のはず。"
"10005030-56-ネル" = "っつーわけだ。ちょっと待ってろ。"
"10005030-57-ネル" = "余計な真似はすんなよ。それからもう一度言うが、知らねぇふりとかしやがったら……"
"10005030-59-バニーガール・ガード" = "ひいっ……！？"
"10005030-60-アカネ" = "脅すより、とりあえずは見てもらいましょうか。"
"10005030-64-アカネ" = "この子です、いかがですか？"
"10005030-65-アカネ" = "うるさくて派手なことが好きなので、一度会ったら結構印象に残ると思いますが。"
"10005030-66-カリン" = "結構失礼で、軽薄な子だ。何か無礼を働かれた記憶とかあったら、その子かもしれない。"
"10005030-70-バニーガール・ガード" = "……？"
"10005030-71-バニーガール・ガード" = "失礼で、軽薄な……。"
"10005030-75-バニーガール・ガード" = "……あ。"
"10005030-76-ネル" = "……「あ」？"
"10005030-77-バニーガール・ガード" = "はっ……！"
"10005030-78-ネル" = "おい、"
"10005030-79-ネル" = "今「あ」って言ったよな？"
"10005030-80-バニーガール・ガード" = "い、いや違う、気のせいだ！万が一知ってたとしても、顧客の情報を漏らすわけにはいかない！"
"10005030-81-ネル" = "ははっ、やっぱり知ってんじゃねえか！！"
"10005030-82-アカネ" = "反応を見る限り、そのようですね。"
"10005030-83-アカネ" = "では、後は教えてもらうだけですが……。"
"10005030-88-バニーガール・ガード" = "……っ！"
"10005030-89-バニーガール・ガード" = "やっ、やめろ！暴力反対！痛いのは好きじゃない！"
"10005030-90-ネル" = "さーて、ようやく始められんなー。"
"10005030-91-ネル" = "あー、別にさっさとゲロる必要はねぇぞ。つまんねぇから。"
"10005030-92-ネル" = "じっくり頑張れ、あとてめぇ自身を恨め。それでいて疲れたら吐け、OK？"
"10005030-97-カリン" = "……先生。"
"10005030-98" = "[s5] \"ネル、痛くない方法でね。\"\n[s6] \"頑張って説得してみたら？\""
"10005030-99-ネル" = "……はぁ？"
"10005030-100-ネル" = "……はぁ？"
"10005030-101-ネル" = "いや、ってかこいつに話を聞こうって言ったのは先生じゃねぇか？"
"10005030-102-ネル" = "それに、別にこれくらいならまだ平和的な方だ。"
"10005030-103-ネル" = "そもそもそれ以外に、方法も何もねぇだろ？"
"10005030-104-ネル" = "時間もそんなあるわけじゃねーし、さっさと……"
"10005030-105-カリン" = "……待って。"
"10005030-106-カリン" = "じゃあ、私がやる。"
"10005030-107-ネル" = "……あん？"
"10005030-108-アカネ" = "……え？"
"10005030-109" = "[s7] \"カリン？\"\n[s8] \"何か良い方法とかありそう？\""
"10005030-110-カリン" = "うん、この間思いついたんだ。"
"10005030-111-カリン" = "うん、この間思いついたんだ。"
"10005030-112-カリン" = "任せて、笑顔で解決してみせるから。"
"10005030-113-ネル" = "はぁ？笑顔で……？"
"10005030-114-アカネ" = "どういうことですか？"
"10005030-115-カリン" = "……先生、良い？"
"10005030-116" = "[s9] \"痛くないならぜひそれで。\"\n[s10] \"じゃあ笑顔で解決する方向で。\""
"10005030-117-カリン" = "分かった。"
"10005030-118-カリン" = "分かった。"
"10005030-123-バニーガール・ガード" = "な、何だ！何をする気だ！？"
"10005030-125-バニーガール・ガード" = "く、来るな！"
"10005030-126-バニーガール・ガード" = "何をされたって、"
"10005030-127-バニーガール・ガード" = "私はひと言も……！"
"10005030-128-カリン" = "……。"
"10005030-129-バニーガール・ガード" = "……んひっ！？"
"10005030-132-バニーガール・ガード" = "な、何を……！んっ、あひゃっ！？"
"10005030-133-バニーガール・ガード" = "ちょっ、やめっ……！あっ、ちょっ……！？だっ、ダメっ！"
"10005030-134-バニーガール・ガード" = "やめっ、頼む！あひゃひゃひゃひゃひゃひゃ！！ひっ、いぃっ……！？"
"10005030-135-バニーガール・ガード" = "あっ、ダメダメダメ！あっ！？んんっ！ちょっ、ひっ、ひぁっ！？"
"10005030-136-カリン" = "……まだまだ。"
"10005030-137-バニーガール・ガード" = "ふひひひひひひひひっ！？ちょっ、そこっ……！？あっ、はぅっ……！？かはっ、あひゃひゃひゃひゃひゃひゃ！！"
"10005030-142-アカネ" = "……あらあら。"
"10005030-143-アカネ" = "なるほど、そういうやり方もあるのですね。"
"10005030-144-アカネ" = "確かに、笑顔で解決できそうですが……。"
"10005030-145-ネル" = "何してんだ……。"
"10005030-147-バニーガール・ガード" = "やっ、やめっ！これ以上はもうっ……！あっ、あひゃひゃひゃひゃひゃひゃ！！！"
"10005030-148-カリン" = "……ここまで声が大きくなると、マズいな。"
"10005030-149-カリン" = "外に聞こえるのも良くないし、じゃあ……。"
"10005030-153-バニーガール・ガード" = "はーっ、はーっ、はーっ……ちょっ、今度は何！？えっ、まっ……んんっ！んむむむっ！？"
"10005030-154-カリン" = "うん、これで良いか。"
"10005030-155-ネル" = "……おい。"
"10005030-156-アカネ" = "えっと、カリン……？"
"10005030-157-バニーガール・ガード" = "んんっ！んんん－ーーっ！！んっ、むっ、んんん！！"
"10005030-158-バニーガール・ガード" = "んぅっ！？"
"10005030-159-バニーガール・ガード" = "んふふふふふふふふ！んんんっ、んんーーっ！んっ！んんんんっ！？"
"10005030-160-バニーガール・ガード" = "んむっ、んんんんんーーっ！？んっ、んんんっ！！"
"10005030-165-ネル" = "……待て待て待て。"
"10005030-166-ネル" = "いやいや、何で尋問なのに口を塞いでんだよ。何が目的だよこれ。"
"10005030-167-アカネ" = "もうこれは別種の暴力なのでは……？"
"10005030-168-ネル" = "っていうか……。"
"10005030-169-ネル" = "放置してて大丈夫か？あいつもう気ぃ失いそうじゃねぇか？"
"10005030-171-アカネ" = "そうですね、そろそろ止めましょうか。"
"10005030-172-アカネ" = "カリン。あれ、カリン……？"
"10005030-176-アカネ" = "カリン……もう耳に入ってないですね、こんなに真剣に……。"
"10005030-177-ネル" = "はぁ、何を夢中になってんだ……。"
"10005030-181-ネル" = "おい、カリン。そろそろやめとけ、目が危なくなってんぞ。"
"10005030-182-バニーガール・ガード" = "んっ、んんっ……！んんんんんんん－ーーっ！？んんっ！んむっ！んんんんっ！？"
"10005030-187-バニーガール・ガード" = "んんんんんっ！？んんっ、んっんんんんっ！？んんんんーーーっ！！！？"
"10005030-188-ネル" = "おい、カリン。"
"10005030-189-ネル" = "カリン！"
"10005030-190-カリン" = "っ！？"
"10005030-191-カリン" = "……リーダー、呼んだ？"
"10005030-192-ネル" = "呼んだっての、何度も何度も。"
"10005030-193-ネル" = "ってか口塞いで尋問ってこれ、何やってんだよ、聞き出そうにも聞き出せねぇだろうが。"
"10005030-194-ネル" = "これで気絶でもしたら――"
"10005030-195-カリン" = "あ、確かに……。"
"10005030-199-アカネ" = "あら、これはもしかしてもう……。"
"10005030-200" = "[s] \"……。\""
"10005030-204-カリン" = "えっと……。"
"10005030-205-カリン" = "やり過ぎたか……。"
