[translation]
"10005015-4-カリン" = "ふぅ……。"
"10005015-5-カリン" = "追っ手は？"
"10005015-9-アカネ" = "……いえ。"
"10005015-10-アカネ" = "大丈夫そうですね、上手く撒いたみたいです。顔も見られていませんし……。"
"10005015-11-アカネ" = "先生、大丈夫ですか？どこか痛いところなどはありませんか？"
"10005015-12" = "[s1] \"うん、大丈夫。ありがとう。\"\n[s2] \"膝が痛いけど、これは元からだから……。\""
"10005015-13-アカネ" = "それは良かったです。安心しました。"
"10005015-14-アカネ" = "あ、あはは……それはちょっと、コメントしにくいのですが……。"
"10005015-15-アカネ" = "あら、そういえば……。"
"10005015-16-アカネ" = "リーダー、その方は……？"
"10005015-18-ネル" = "……ん？あぁ、こいつか？"
"10005015-23-バニーガール・ガード" = "……う、ううん……？"
"10005015-24-バニーガール・ガード" = "こ、ここは……客室……？いったい何が……。"
"10005015-29-バニーガール・ガード" = "はっ！あ、あんたたちは……！"
"10005015-38-バニーガール・ガード" = "がっ！ぐはっ！？うぅ……。"
"10005015-44-カリン" = "わざわざ連れてきたのか……？"
"10005015-45-ネル" = "仕方ねーだろ、こいつ思いっきりあたしらの顔を見ちまったし。放っておいたら共有されちまうだろうが。"
"10005015-46-ネル" = "とりあえず、ひと段落するまでここで寝ててもらうか。"
"10005015-48-アカネ" = "確かに、仕方ありませんね。"
"10005015-49-アカネ" = "そうしましたら、手足を後ろ側で縛って……"
"10005015-53-カリン" = "目隠しも付けておこう。客室内にいることはバレたけど、それ以上の情報を渡すとどうなるか分からない。"
"10005015-54-ネル" = "起きて叫ばれると困っから、口にもなんか貼っとけ。"
"10005015-58" = "[ns] \"……。\""
"10005015-60" = "[ns3] \"これ、見た目がちょっと……。\"\n[ns4] \"容赦ないね……できればもう少し優しめに……。\""
"10005015-61-カリン" = "ん？何か変なところでもある？"
"10005015-62-カリン" = "ん？何か変なところでもある？"
"10005015-63-カリン" = "これくらいならいつものことだ。特に怪我もさせてないし、むしろ優しい方。"
"10005015-64-アカネ" = "そうですね。もし先生がいなかったら、リーダーが四肢を縛って海に投げ捨てたりしていたかもしれません。"
"10005015-65-ネル" = "るせぇぞアカネ！"
"10005015-66-カリン" = "まあとにかく、これで問題は無さそうだ。"
"10005015-67-カリン" = "アカネ、次は？"
"10005015-69-アカネ" = "では、拠点もできたことですし……。"
"10005015-70-アカネ" = "システムルームの掌握へ向かいたいところですが、その前にやらなくてはいけないことがありますね。"
"10005015-71-カリン" = "どういうことだ？"
"10005015-72-アカネ" = "先ほどリーダーが黙らせる前に、色々と言っていたじゃないですか。どうやらこの船には、特殊なルールがあるようです。"
"10005015-73-アカネ" = "このバニー姿の衣装が、まるでここでの通常の服装かのような言い方をしていました。先生はともかく、私たちは着替えた方が良さそうです。"
"10005015-74-カリン" = "ああ、そういえば……そんなことを言ってたな。"
"10005015-75-カリン" = "今まではメイド服でいれば、どこにでも潜入しやすかったけど……。"
"10005015-76-アカネ" = "ここにはここのルールがあるということですね、少し特殊ではありますが。"
"10005015-77-アカネ" = "ということで、円滑に動き回るためにも着替えた方が良さそうです。"
"10005015-79-ネル" = "めんどくせぇなぁ……？"
"10005015-80-アカネ" = "その方がきっと手間は減りますよ。そういうわけで、はい。先ほど拝借してきましたので。"
"10005015-85-アカネ" = "サイズも恐らく大丈夫かと。いつも見てましたし。"
"10005015-86-ネル" = "流石アカネ、手際が良いじゃねぇか？"
"10005015-91-カリン" = "……？"
"10005015-92-カリン" = "これはさっき、気絶させた彼女たちから脱がせたものだとして……。"
"10005015-93-カリン" = "よく考えると、サイズとかは一体……もしかして今言った「いつも見てました」って……？"
"10005015-94-アカネ" = "ふふっ、まあ細かいことは良いじゃないですか。"
"10005015-95-アカネ" = "とにかく、一旦着てみましょう？"
"10005015-96-アカネ" = "あ、リーダーはこちらへ。私が着せてあげます。"
"10005015-97-ネル" = "はぁ？"
"10005015-98-ネル" = "ガキ扱いしてんじゃねぇぞ？"
"10005015-99-アカネ" = "あら、着方分かるのですか？"
"10005015-100-ネル" = "分からん。"
"10005015-101-アカネ" = "ふふっ、では私がお手伝いしますので。"
"10005015-102-ネル" = "はぁ……。"
"10005015-105-カリン" = "アカネ、さっきの話がやっぱり気になるのだけど、なんでサイズが分かって……"
"10005015-109-アカネ" = "細かいことは気にしないでください。"
"10005015-110-アカネ" = "ね？"
"10005015-111-カリン" = "……。"
"10005015-112-カリン" = "まあ、今一番大事なのは任務の方か……。"
"10005015-113-ネル" = "おい、これどうやって着るんだよ。ってか何だこの形状、本当に服なのか？"
"10005015-114-アカネ" = "あらあら、ちょっと待っててくださいね。"
"10005015-115-アカネ" = "さて。着替えて、システムルームへ向かって、その後は……。"
"10005015-116-アカネ" = "……？"
"10005015-117-アカネ" = "先生、どうかされましたか？何か気になることでもありましたか？"
"10005015-118" = "[s5] \"今更だけど……。\"\n[s6] \"……アスナは？\""
"10005015-119-アカネ" = "……？"
"10005015-120-アカネ" = "……？"
"10005015-121-アカネ" = "あ、なるほど……そういうことでしたか。そういえば先生がしっかり私たちの作戦に同行するのは、初めてのことでしたね。"
"10005015-122-カリン" = "アスナ先輩については、気にしなくても大丈夫。元々そういうものというか……。"
"10005015-123-ネル" = "言ったところで、おとなしく聞くやつでもねぇしな。"
"10005015-124-アカネ" = "そうですね、遊撃隊とでも言いますか……アスナ先輩は、自由に動き回る方が向いているタイプでして。"
"10005015-125-アカネ" = "もちろん最初のブリーフィングで色々とお伝えはしますが、後は自由に動き回られます。いつものことなんです。"
"10005015-126-アカネ" = "ところで、その……。"
"10005015-127" = "[s] \"……？\""
"10005015-133-アカネ" = "何と言いますか……。"
"10005015-134-アカネ" = "いえその、このままでも構わないと言えば全然構わないのですが……。"
"10005015-135-アカネ" = "できれば、その……流石に、あまりそう凝視されたままですと……。"
"10005015-136-アカネ" = "ああでも、一緒に着替えていただくという手もありますね？"
"10005015-137" = "[s7] \"……ごめん。\"\n[s8] 静かに後ろを向く。"
"10005015-142" = "（そのまま、長いようで短い時間が経過した）"
