[translation]
"10005055-4-白兎" = "にはははは！いやー、生きてるとこんな日も来るんですねー！！"
"10005055-5-白兎" = "天下のC&Cが捕まっている様を、こうして見下ろす日が来るなんて！"
"10005055-6-白兎" = "いやー、やっぱ自由って良いなー！三十六計逃げるに如かずってね！"
"10005055-7" = "[s1] \"大集合だね。\"\n[s2] \"あとはアスナがいないけど……。\""
"10005055-8-白兎" = "あ、そういえば……。"
"10005055-9-白兎" = "あ、そういえば……。"
"10005055-10-白兎" = "アスナ先輩は、相変わらずどこへ行ったんでしょうね？"
"10005055-11-白兎" = "まあこの船の中にいるのは確かですし、警備の数を考えると捕まるのも時間の問題ですね、きっと！"
"10005055-12-白兎" = "にははは！もうちょっと待っててくださいね、仲良くみなさん一緒にしてあげますので！"
"10005055-13-白兎" = "その後はどうしましょうかね～、このままどこか無人島にでも行って降ろしてもらうとしましょうか。"
"10005055-14-白兎" = "ではでは～、もう二度と会えないかもしれませんがそれはそれで！！"
"10005055-18-白兎" = "おっ、このタイミングはまさか！？"
"10005055-19-白兎" = "これはもう流れ的に間違いありませんね、お疲れ様でしたー！"
"10005055-20-白兎" = "アスナ先輩ー、ひっさしぶりーー！！"
"10005055-29-アスナ" = "あ、コユキじゃん！"
"10005055-30-アスナ" = "ここにいたんだ？"
"10005055-32-白兎" = "にはははは！こんにちは、先輩！"
"10005055-33-白兎" = "そして警備のみなさんはお疲れ様でした！"
"10005055-39-白兎" = "さあさあどうぞ中へ！こうしてみなさん一緒ですので！"
"10005055-40-白兎" = "暴れても無駄ですよー、そもそもここはミレニアムじゃないんですから、そんなことしたら大問だ――"
"10005055-45-バニーガール・ガードA" = "……皆様。"
"10005055-46-白兎" = "……？"
"10005055-47-白兎" = "……皆様？私のことじゃなく？"
"10005055-48-バニーガール・ガードA" = "……お前じゃない。"
"10005055-49-バニーガール・ガードA" = "そちらの方々。"
"10005055-50-バニーガール・ガードA" = "……大変失礼いたしました、釈放です。"
"10005055-54-白兎" = "……へ？"
"10005055-56-ネル" = "……あん？"
"10005055-57-アカネ" = "これは……？"
"10005055-58-カリン" = "……釈放？どうして？"
"10005055-60-バニーガール・ガードA" = "アスナ[ruby=・]様[/ruby]のご命令ですから。"
"10005055-61-白兎" = "……[ruby=・]様[/ruby]？"
"10005055-62-バニーガール・ガードA" = "Sランクをお持ちのVIPであるアスナ様の指示に従い、皆様を釈放とさせていただきます。"
"10005055-63-バニーガール・ガードA" = "上でのお話合いがありまして……大変申し訳ないことに、先ほどまでの戦闘の被害額だけはご請求させていただきますが……それさえ清算できれば他のことについては、これまでのことを全て含めて不問となります。"
"10005055-64-バニーガール・ガードA" = "先ほどまでは違う状況だったとはいえ、大変失礼いたしました。それでは、ごゆっくり……。"
"10005055-71-アスナ" = "そういうことみたい！"
"10005055-72-アスナ" = "急に捕まえられちゃいそうになったんだけど、ゲームの画面を見たらなんかみんな手を止めちゃってさ？"
"10005055-73-アスナ" = "色々連絡してたみたいなんだけど、その後「何なりとご命令を」って言われたから、じゃあ好き放題させてもらおうかなって！"
"10005055-74-アスナ" = "っていうわけでちょっとお金を払わないといけないけど、もう私たちは自由だよ！！あとはいつも通り！"
"10005055-75" = "[s3] \"なんか、「S」って相当珍しいものみたいに言われてたけど……？\"\n[s4] \"さすがはアスナ。\""
"10005055-79-ネル" = "……ははっ。"
"10005055-80-ネル" = "そうかそうか……。"
"10005055-81-ネル" = "つまり、とりあえずてきとうにお金さえ払っとけば後は何をしても良い、と。"
"10005055-82-ネル" = "別に学校間の問題にもならない……そういうことで良いんだな？"
"10005055-83-ネル" = "はっ。"
"10005055-84-ネル" = "……良いじゃねぇか。"
"10005055-85-ネル" = "おい、白兎……早く逃げたらどうだ？10秒くらいなら待ってやんぞ？"
"10005055-87-白兎" = "……あはー。"
"10005055-88-ネル" = "ちったぁ頑張ってくれよ？"
"10005055-89-ネル" = "……さっさと終わったら、つまんねぇからなぁっ！！"
