[translation]
"90100112-3" = "連邦生徒会長執務室"
"90100112-5-矯正局の看守" = "囚人番号1192番をお連れしました。"
"90100112-6-連邦生徒会長" = "どうぞ、お入りください。"
"90100112-13-連邦生徒会長" = "お久しぶりですね、防衛室長。"
"90100112-14-連邦生徒会長" = "いえ……[ruby=しらぬい]不知火[/ruby]カヤ。"
"90100112-15-カヤ" = "あなたは……。"
"90100112-16-連邦生徒会長" = "私が不在だった間のことは、すべて報告を受けました。"
"90100112-17-連邦生徒会長" = "[ruby=なながみ]七神[/ruby]リン代行が失脚した隙を突いて、クーデターを試みたそうですね。"
"90100112-18-連邦生徒会長" = "キヴォトスが混乱に陥ったそもそもの原因は私にあります。#nとはいえ、あなたの行動は連邦生徒会を崩壊させかねないものでした。"
"90100112-19-連邦生徒会長" = "だからこそ裁判に先立って、あなたの証言を聞いておきたいのです。"
"90100112-20-連邦生徒会長" = "何故あなたは連邦生徒会長の座を狙ったのですか？"
"90100112-24-カヤ" = "………。"
"90100112-25-カヤ" = "いや、あなた……誰なんですか？"
"90100112-26-連邦生徒会長" = "……はい？"
"90100112-27-連邦生徒会長" = "私が……分からないのですか？"
"90100112-28-カヤ" = "分かるも何も、初対面ですよね？"
"90100112-29-カヤ" = "そんなことより、どうして連邦生徒会長の服を着てるんです？#nまさか、あなたもクーデターを――"
"90100112-33-連邦生徒会長" = "では、改めて自己紹介をさせてください。"
"90100112-34-連邦生徒会長" = "私は学園都市キヴォトスを管理する連邦生徒会の長――"
"90100112-35-カヤ" = "何を言ってるんですか！？"
"90100112-36-カヤ" = "私[ruby=連邦生徒会長]の超人は[/ruby]こんなのじゃない！！"
"90100112-40-カヤ" = "あなたにだって[ruby=・]そ[/ruby][ruby=・]れ[/ruby][ruby=・]な[/ruby][ruby=・]り[/ruby][ruby=・]の[/ruby][ruby=・]品[/ruby]はありますけど、比べるべくもありません！"
"90100112-41-カヤ" = "本物の連邦生徒会長はもっと優雅で、なのに親しみがあって……#nたまに抜けて見えることもあるけど、それも含めて完璧な――"
"90100112-42-矯正局の看守" = "お前！連邦生徒会長に向かって何て口のきき方だ！"
"90100112-43-カヤ" = "あなたもこの偽物に買収されたんですか？#n何もかもが違うじゃないですか！！"
"90100112-44-カヤ" = "本物が戻ってきたら、あなたも、シャーレの先生も、リンも、みんなただじゃ――"
"90100112-51-カヤ" = "ぐえっ！"
"90100112-52-矯正局の看守" = "申し訳ありません。長い収監生活で頭がおかしくなったようです。"
"90100112-53-連邦生徒会長" = "……いえ。カヤさんとの面談は日を改めましょう。"
"90100112-59-カヤ" = "次こそ失敗しないんだからぁぁぁぁ――！"
"90100112-64-連邦生徒会長" = "……私の印象、そんなに変わったんでしょうか。"
"90100112-66" = "ロア追跡編;To be Continued in Chapter 2"
