[translation]
"10004060-1" = "第6話;ドタバタ捕獲大作戦"
"10004060-2-サヤ" = "まずは第一の作戦……"
"10004060-3-サヤ" = "その名も「チーズ作戦」なのだ！"
"10004060-4" = "[s] \"チーズ作戦……？\""
"10004060-5-サヤ" = "そうなのだ。ネズミがチーズを見て素通りなんてできないように、子どもは飴とか甘いものを差し出されたら無視はできないはずだろう？"
"10004060-6-サヤ" = "だからこの解毒剤を塗った、特製キャンディを用意したのだ！"
"10004060-11-サヤ" = "幼くなったシュンにとって、これを無視することはできないはず！"
"10004060-12" = "[s] \"その作戦、サヤくらいしか釣られないんじゃ……？\""
"10004060-13-サヤ" = "うっ、うるさいうるさい！ぼく様だって、チーズだったら何でも口に入れるわけじゃないのだ！"
"10004060-14-サヤ" = "あ、この作戦を実行するには普段の服装だとダメだから、覆面も用意したのだ。はい、被ってみて！"
"10004060-20-サヤ" = "うん、完璧なのだ！誰が見ても先生だとは思えない！"
"10004060-21" = "[s] \"この覆面、なんだか……すごく、呼吸がしづらい……。\""
"10004060-22-サヤ" = "これも作戦のため、細かいことは気にしないのだ！"
"10004060-23-サヤ" = "さあ、作戦開始！"
"10004060-28-シュン" = "うぅ……あれではきっと、先生にもバレてしまいましたよね……。"
"10004060-29-シュン" = "今までの行いが全部私だったと知って、幻滅しているかもしれません……。"
"10004060-30" = "[s] \"はぁ、はぁ……えっと、そこの、お嬢ちゃん……。\""
"10004060-32-シュン" = "……え？"
"10004060-33-シュン" = "だ、誰ですか？どうしてそんな覆面をかぶって、息を荒げて……？"
"10004060-34" = "[s] \"はぁ、はぁ……良かったら、飴でも、どう……？\""
"10004060-40-シュン" = "……結構です。"
"10004060-41-シュン" = "知らない方から簡単に食べ物を受け取ってはいけないと、先生も言っていました。"
"10004060-42" = "[s1] \"大丈夫、何も変なことはしないよ……はぁ、はぁ……。\"\n[s2] \"お願いだからちょっとだけ、ペロっと、ね……？\""
"10004060-43-シュン" = "……嫌です。"
"10004060-44-シュン" = "……嫌です。"
"10004060-45-シュン" = "それ以上近づいたら、警察のお姉ちゃんを呼びますよ！"
"10004060-50-サヤ" = "……ダメか。"
"10004060-51" = "[s] \"……ダメだね。\""
"10004060-52-サヤ" = "ま、まあ大丈夫なのだ！どんな天才も最初から成功するわけではないからな！"
"10004060-53-サヤ" = "気を取り直して、次の作戦なのだ！"
"10004060-55-サヤ" = "二つ目の作戦は……"
"10004060-56-サヤ" = "その名も「トラップ作戦」なのだ！"
"10004060-57" = "[s] \"トラップ作戦？\""
"10004060-58-サヤ" = "うん。古典的ではあるけど、ネズミを捕まえるには何だかんだでネズミ捕りが一番なのだ。"
"10004060-59-サヤ" = "それと同じ考えに基づいてぼく様が作ったのが、この特製トラップ！"
"10004060-64-サヤ" = "これ踏むと強力な麻痺効果を持ったガスが出て、しばらく動けなくなるのだ。"
"10004060-65" = "[s] \"結構危なくない……？\""
"10004060-66-サヤ" = "大丈夫大丈夫。このガス、威力は強いけど、持続性が弱いからすぐに元通りになるのだ。"
"10004060-67-サヤ" = "……多分。"
"10004060-68" = "[s] \"多分！？\""
"10004060-69-サヤ" = "こ、細かいことは気にしないのだ！まずはシュンを捕まえるのが先決！"
"10004060-70-サヤ" = "じゃあ、まずは設置するとしようか？"
"10004060-76-サヤ" = "設置完了、後はシュンが来るのを待つのだ！"
"10004060-77" = "[s] \"もし麻痺が取れなくても、サヤならすぐ治せるんだよね……？\""
"10004060-78-サヤ" = "うん、大丈夫。なにせぼく様は天才なのだ。それにこれは、全部シュンのためなんだから！"
"10004060-79-サヤ" = "あっ、シュンが来たのだ！先生、隠れて！"
"10004060-86-シュン" = "別に私、そんなに悪いことはしてないはずなのですが……。"
"10004060-87-シュン" = "私はただ、梅花園の園児たちみたいに、自由に過ごしたいだけで……。"
"10004060-92-シュン" = "……？"
"10004060-93-サヤ" = "（踏む……っ！）"
"10004060-97-シュン" = "おっと、危ないところでした。足先に何か……高そうな機械が落ちてますね。"
"10004060-99-シュン" = "あら、こっちにも……？"
"10004060-102-シュン" = "こちらにも。"
"10004060-104-シュン" = "何だかたくさん落ちてますね、落とした方はよっぽど急いでたんでしょうか？"
"10004060-109-サヤ" = "ぐ、身体が小さいからか、かなり身軽なのだ……！"
"10004060-110-サヤ" = "ええい、こうなったら直接投擲するのだ！"
"10004060-111-サヤ" = "くらえっ！"
"10004060-121-シュン" = "……危ないですねー、誰ですか物を投げたのは。相手がケガをしたらどうするんですか！？"
"10004060-122-シュン" = "……出てきませんね、どこかに行っちゃったのでしょうか。全く、梅花園の子たちにも「こういうことはしちゃダメですよ」としっかり教えないとです……。"
"10004060-128-サヤ" = "投擲弾を空中で狙撃するなんて……中々やるのだ。"
"10004060-129" = "[s] \"さすが……。\""
"10004060-130-サヤ" = "とにかく、早く次の作戦に移るのだ！"
"10004060-131" = "[s3] \"ところでサヤ、多分これ私たちの身体が……。\"\n[s4] \"何だか手足が痺れて……。\""
"10004060-134-サヤ" = "ふーっふっふっふ……"
"10004060-135-サヤ" = "空中で爆破させただけなのに、こんなに身体が痺れるなんて……さすがはぼく様の発明品、素晴らしい麻痺効果なのだ！"
"10004060-136-サヤ" = "……本当にすごいな、身体がびくびくして動かないのだ。"
"10004060-137-サヤ" = "とりあえずこのまま痺れが取れるのを待つか……。"
"10004060-139-サヤ" = "やはり、幼くなっても梅花園の教官だな。"
"10004060-140-サヤ" = "ぼく様のアイデアが、こんなにも次々無力化されるなんて……。"
"10004060-141-サヤ" = "仕方ない、この方法は使いたくなかったけど……言うことを聞かない子には、最終的にはやはりこれしかないのだ。"
"10004060-142" = "[s5] \"そ、それって……？\"\n[s6] \"……ごくり。\""
"10004060-145-サヤ" = "言うことを聞かない子は……"
"10004060-146-サヤ" = "大人の力で押さえつけるのだ！"
"10004060-147-サヤ" = "いくらシュンとはいえ不意を突けば、これだけの体格差なんだし、一時的にでも動きを止められるんじゃないか？"
"10004060-148-サヤ" = "タイミングはぼく様が伝えるから、先生が少しでもシュンの動きを止めて、その隙にぼく様が無理やり薬を飲ませる……！"
"10004060-149" = "[s] \"そ、そこまでやる必要ある……？\""
"10004060-150-サヤ" = "やむを得ないのだ！これもすべてぼく様の研きゅ……"
"10004060-151-サヤ" = "いや、シュンのためだ！"
"10004060-152-サヤ" = "手遅れになる前に、とにかくありとあらゆる手段を試してみないと……！"
"10004060-153" = "[s] \"うーん、私の力で押さえつけられるかな……。\""
"10004060-154-サヤ" = "さあ、ぼく様が向こうで見張ってるから、先生はここに隠れて、合図と同時にシュンを襲うのだ！"
"10004060-156-シュン" = "……今日は何だか、変な方に会うことが多い気がします。身体が小さいと、変な方に会いがちなのでしょうか……気を付けないとです。"
"10004060-157-シュン" = "中でもさっきの覆面の方は、かなり危なそうでしたし……。"
"10004060-158-サヤ" = "今だ、先生！シュンを捕まえて！"
"10004060-164" = "[ns] \"やあ、シュン。\""
"10004060-165-シュン" = "せ、先生！？びっくりしました、急にどこから……？"
"10004060-166-シュン" = "あ、えっと、そういえばこの身体は、その……。"
"10004060-168-シュン" = "え、先生？どうして急に腕を……？"
"10004060-169" = "[s7] \"……元の身体に戻ろう？\"\n[s8] \"このままだともしかしたら副作用で……って力強っ！？\""
"10004060-170-シュン" = "ちょっ、えぇっ！？やっ、そのっ、それはどういう……！？"
"10004060-171-シュン" = "ちょっ、えぇっ！？やっ、そのっ、それはどういう……！？"
"10004060-173-サヤ" = "はーっはっはっ！よくやったのだ先生！この隙を逃してたまるか！"
"10004060-174-サヤ" = "今こそ薬を飲ませる時！さあ覚悟するのだ！"
"10004060-175-シュン" = "なっ、先生まさか……！先生のこと、信じてたのに！"
"10004060-176-シュン" = "い、嫌です！私は元の身体になんて戻りたくないんです！"
"10004060-177-サヤ" = "ちょっ、暴れるな！おとなしく口を開けるのだ！"
"10004060-178-シュン" = "うぅっ……だ、誰か……！"
"10004060-180-シュン" = "誰か、助けてくださいっっっっ！！！"
"10004060-182-？？？" = "……先生？"
"10004060-185-キリノ" = "どうして道のど真ん中で幼い少女の腕を掴んで、無理やり口を開けさせようと……？"
"10004060-186" = "[s9] \"ご、誤解なんだキリノ！\"\n[s10] \"いや、後半部分は私じゃなくてサヤが……。\""
"10004060-195-シュン" = "警察のお姉ちゃん！助けてください！！"
"10004060-199-キリノ" = "……だいたい状況は分かりました。"
"10004060-201-キリノ" = "詳しいお話は、署で聞かせていただきます！"
"10004060-202" = "[s] \"ちがっ、待って！？\""
"10004060-208" = "その後結局キリノに連行され、サヤ共々、正座で長い間お説教をされた。"
