[translation]
"13020-1" = "第2話;招かれざる客"
"13020-5-ハイランダーの生徒A" = "げほっ、げほっ。#nうぅ……"
"13020-6-ハイランダーの生徒B" = "ここで最後でしたっけ？"
"13020-7-ハイランダーの生徒A" = "あぁ、そのはず……"
"13020-8-ハイランダーの生徒A" = "でも、こんな時期に倉庫を移転するなんて一体……"
"13020-9-ハイランダーの生徒B" = "ここ、だいぶ長いこと放置されてたみたいですね……#n元々は何をする場所だったんでしょう？"
"13020-10-ハイランダーの生徒A" = "たしか学園の機密文書を保管してたとか、なんとか……"
"13020-11-ハイランダーの生徒B" = "……機密文書？"
"13020-12-ハイランダーの生徒B" = "とはいえ、もう要らないものなんでしょう。#nだからこそ処理が命じられたのでは？"
"13020-13-ハイランダーの生徒A" = "でも一応、書類に軽く目を通した方が良いんじゃ……？"
"13020-14-ハイランダーの生徒B" = "……いえ、破棄で良いでしょう。#n時間もあまり無いことですし。"
"13020-15-ハイランダーの生徒A" = "まあ、確かに……ん？"
"13020-20-ハイランダーの生徒A" = "っ！？"
"13020-21-ハイランダーの生徒B" = "どうした！？"
"13020-22-ハイランダーの生徒A" = "柱が……！逃げろっ！"
"13020-27-ハイランダーの生徒A" = "はぁ、はぁ……。#n……怪我は？"
"13020-28-ハイランダーの生徒B" = "だ、大丈夫です。#nまさか、ここまで老朽化が進んでるだなんて……。"
"13020-29-ハイランダーの生徒A" = "片付けようにも片付けられないな……#n一度、上に確認を……"
"13020-30-ハイランダーの生徒A" = "ん？何だこれ。"
"13020-34-ハイランダーの生徒B" = "何の書類ですか？"
"13020-35-ハイランダーの生徒A" = "どれどれ……"
"13020-36-ハイランダーの生徒A" = "「売買契約書――"
"13020-37-ハイランダーの生徒B" = "――アビドス高等学校」？"
"13020-53-ノノミ" = "失礼しまーす……"
"13020-59-ノノミ" = "あの方が、副生徒会長……"
"13020-60-ノノミ" = "……。"
"13020-61-ノノミ" = "どうして、一人でまだ……"
"13020-62-ホシノ" = "……ん？"
"13020-69-ホシノ" = "何か、視線が……"
"13020-70-ホシノ" = "……。"
"13020-71-ホシノ" = "……気のせいか。"
"13020-73-ノノミ" = "はぁ、はぁ……"
"13020-74-ノノミ" = "ビックリしました……"
"13020-75-ノノミ" = "あんなに距離があったのに……#n噂には、聞いていましたが……"
"13020-76-ホシノ" = "どんな噂？"
"13020-78-ノノミ" = "……え、あ、その。#nホシノ、さん……"
"13020-82-ノノミ" = "！？"
"13020-84-ホシノ" = "へぇ……私の名前、知ってるんだ？"
"13020-86-ノノミ" = "えっと、あの……"
"13020-87-ホシノ" = "誰？#n私に何か用？"
"13020-88-ノノミ" = "わ、私は……"
"13020-89-ホシノ" = "どこの生徒？#n所属と学年は？"
"13020-90-ホシノ" = "別に年上だったところで容赦しないけど。#nそれくらい知ってるでしょ。私のことを、調べてたなら。"
"13020-91-ノノミ" = "そ、そういう目的で来たわけでは……"
"13020-92-ホシノ" = "あれ、その校章……"
"13020-93-ノノミ" = "は、はい。#n私も、アビドス自治区の学生で……"
"13020-94-ノノミ" = "それと、まだ中学生です。#nもうすぐ卒業ですが……"
"13020-98-ホシノ" = "……ちゅ、中学生？#nそうか、私より先輩に見えるけど……"
"13020-99-ノノミ" = "あ、あはは……"
"13020-100-ホシノ" = "……思い出した。#nそれ、私立ネフティス中学校の校章だよね？"
"13020-101-ノノミ" = "あ、そ、それは……"
"13020-102-ホシノ" = "……でもおかしいな。#nネフティスの本社は自治区の外に移転してだいぶ経つし……#nたしか学校も廃校って……"
"13020-103-ノノミ" = "……。"
"13020-104-ノノミ" = "私が卒業したら……その後、廃校になります。"
"13020-108-ホシノ" = "……私立ネフティス中学校。"
"13020-109-ホシノ" = "ネフティス企業傘下の、超エリート校。"
"13020-110-ホシノ" = "ネフティスの後継者が残ってるとは聞いてたけど……#n……なるほどね。"
"13020-112-ノノミ" = "……。"
"13020-113-ホシノ" = "君だったんだね、[ruby=いざよい]十六夜[/ruby]ノノミさん？"
"13020-117-ホシノ" = "最後に物見遊山でもしにきたの？"
"13020-118-ホシノ" = "かの高名な悪徳企業「ネフティス」のお嬢さんが、私たちの学校に何の用？"
"13020-119-ノノミ" = "わ、私は……"
"13020-120-ホシノ" = "回答によっては……"
"13020-121-ノノミ" = "……！！？？"
"13020-122-ホシノ" = "ヘイローの無事は保障しないよ。"
"13020-123-ノノミ" = "ご、ごめんなさい、私は……"
"13020-124-ノノミ" = "私、は……"
"13020-135-ホシノ" = "……言い過ぎちゃったかな。"
"13020-137-ノノミ" = "……。"
"13020-138-アヤネ" = "ネフティス……"
"13020-139" = "[s] \"ネフティスグループといえば……。\""
"13020-140-セリカ" = "そのネフティスが、私たちの債権を買ったのよね？#n具体的にはそれで、何が問題なの？"
"13020-141-ノノミ" = "それは――"
"13020-142-ホシノ" = "セイント・ネフティスカンパニー。#nいわゆるネフティスグループは……"
"13020-144-ホシノ" = "アビドス土着の企業で、#n昔はキヴォトスの名だたる大企業と肩を並べてた。"
"13020-145-セリカ" = "そんな企業が、アビドスに……！？"
"13020-146-ホシノ" = "アビドスは元々、すごいところだったからね。"
"13020-148-ノノミ" = "かつてキヴォトスで最も長い歴史を誇り……"
"13020-149-ノノミ" = "その強大さ故に、ありとあらゆる学園から恐れられ、#n或いは羨まれていた学校……それがアビドスでした。"
"13020-150-ノノミ" = "……砂漠化が進んでしまう前の話、ですけれど。"
"13020-151-ノノミ" = "……セイント・ネフティスカンパニーは、そんなアビドスの全盛期を共に過ごした企業です。"
"13020-153-ノノミ" = "しかし砂漠化が進むにつれて、#nアビドスと同様にネフティスもまた没落していきました。"
"13020-155-ノノミ" = "さらには、砂漠横断鉄道の損失を取り戻そうと無理をした結果、破産直前にまで至り……"
"13020-158-ノノミ" = "事業は中断を余儀なくされました。#n当時は大企業だったため、アビドス全体に取り返しのつかない損害が及び……"
"13020-159-ノノミ" = "そうして一人、また一人と、住民がアビドスを離れていくと、#nネフティスも全ての事業を畳んで去っていきました。"
"13020-161-ノノミ" = "そんなアビドスをどうにか立て直すために、アビドス生徒会が借金を抱えることになり……"
"13020-162-ホシノ" = "……そんなところだね。#n私が1年生のときにはもう、自治区でネフティスを見ることはほとんどなかったよ。"
"13020-164-セリカ" = "つまりネフティスのせいで、私たちの自治区がこんなことになったってわけ！？"
"13020-165-ホシノ" = "それはちょっと言い過ぎかなー。#nネフティスはアビドスが没落した理由の一つでしかないから。"
"13020-166-ノノミ" = "ですが……ネフティスの失敗がなければ、#nアビドスが復興するチャンスはまだあったはずです。"
"13020-167-ノノミ" = "止めを刺したのは、間違いなくネフティスでした。"
"13020-168-ノノミ" = "ネフティスはアビドスにとって加害者なんです。#nそして――"
"13020-169-ノノミ" = "――私の家が、運営している会社です。"
"13020-174-セリカ" = "……えっ？#nそうなの！？"
"13020-175-ホシノ" = "……。"
"13020-176-ノノミ" = "……はい。#n私はネフティスグループの人間です。"
"13020-177" = "[s] \"ノノミ……\""
"13020-181-アヤネ" = "……やっぱり、そうなんですね。"
"13020-182-セリカ" = "やっぱり、って……アヤネちゃんは知ってたの？"
"13020-183-アヤネ" = "いえ、直接聞いていたわけでは……#nですが、ゴールドカードを持っている理由、それに……"
"13020-185-ノノミ" = "それに――あの鉄道こそが、アビドスの衰退に拍車をかけたきっかけですし……"
"13020-186-ノノミ" = "それが、世界を救うお役に立てるのなら……これ以上嬉しいことはないです。"
"13020-187-アヤネ" = "……。"
"13020-189-アヤネ" = "ノノミ先輩が砂漠横断鉄道のシステムにアクセスしているところを見て、#n多分そうなんじゃないかなって……"
"13020-190-セリカ" = "えっ、全然知らなかったのって私だけ！？#nホシノ先輩とシロコ先輩は？"
"13020-195-セリカ" = "……シロコ先輩は、知らなかったんだよね？"
"13020-196-シロコ" = "う、うん。"
"13020-197-セリカ" = "……ノノミ先輩、どうして隠してたの？"
"13020-199-ノノミ" = "そ、それは……"
"13020-200-セリカ" = "……ごめん。#nこうやって迫るようなことじゃないわよね。"
"13020-201-ノノミ" = "いえ……"
"13020-202-セリカ" = "でも、ネフティスがアビドスからいなくなっても……#n先輩は残ってくれて良かった。"
"13020-203-ノノミ" = "……。"
"13020-205-アヤネ" = "一度、状況を整理しましょう！"
"13020-206-アヤネ" = "本日カイザーコーポレーションが、アビドスの負債の内45％を売却しました。"
"13020-207-アヤネ" = "その際に新規債権者が殺到し、債権が暴騰……なんと元値の4～5倍以上の金額にまで跳ね上がりました。"
"13020-208-アヤネ" = "債権の購入者は――セイント・ネフティス。"
"13020-209-アヤネ" = "カイザーはこの取引で、莫大な利益を得たことでしょう。"
"13020-210-ノノミ" = "ですが、どうしてこんな取引をしたのか。#nその理由までは分かりません。"
"13020-211-ノノミ" = "アヤネちゃん、ネフティスが買収によって得た権利の詳細を確認してもらえますか？"
"13020-212-アヤネ" = "あ、はい……！"
"13020-216-アヤネ" = "この取引によって、ネフティスは……#nアビドス自治区内の特定施設及びインフラの所有権、そして開発権を得ています。"
"13020-217-ノノミ" = "土地の所有権を除いた全ての権利ですね。#nたしかに、土地は依然としてカイザーが……"
"13020-218-ノノミ" = "その「特定施設」というのは、どういったものが含まれていますか？"
"13020-219-アヤネ" = "物流を目的とした交通インフラと……#nそれに関連する施設、とあります。"
"13020-220-セリカ" = "交通インフラなんて、そんなの残ってたっけ？"
"13020-225-ノノミ" = "……「砂漠横断鉄道」。"
"13020-226-セリカ" = "ええっ！？"
"13020-227-ノノミ" = "該当するものは、それしかないはずです。"
"13020-228-セリカ" = "で、でもノノミ先輩。#nあれって工事途中で放置されてるはずじゃ……#nなのに、こんな高い値段で買ったの……？"
"13020-229-アヤネ" = "それにネフティスは、#nかつて自らが手放した事業を、再び買い直したことにもなります。"
"13020-230-シロコ" = "……何が目的？"
"13020-232-ノノミ" = "……私にも分かりません。#nいったい、どうして……"
"13020-233-セリカ" = "も、もしかして……！"
"13020-238-セリカ" = "石油でも見つかったとか！？"
"13020-243-ホシノ" = "いやー無いない。#nもしあったら、アビドスはこんな状態になってないでしょ。"
"13020-244-セリカ" = "じゃあ、大量のレアアースが検出されたとか……？#nゲルマニウム何とか……だっけ？"
"13020-245-ホシノ" = "うへ～、相変わらず可愛いねぇセリカちゃんは。#nお金になりそうなものは、おじさんが全部調査済みだよ。"
"13020-246-ホシノ" = "けど、何も出なかった。石油も希少鉱物も、なーんにもね。#n……というか、ゲルマニウムは安いやつじゃない？"
"13020-248-セリカ" = "そ、それは良いとして！#nなら、どうしてわざわざ権利を買ったのよ？"
"13020-249-ホシノ" = "それが分からないから、おじさんも困ってるんだよね～。"
"13020-254-シロコ" = "……敵？"
"13020-255-セリカ" = "な、何よ急に！？"
"13020-257-アヤネ" = "侵入者です！#n自治区で爆発反応を確認しました！"
"13020-258-シロコ" = "まさか、カイザーコーポレーションが……！？"
"13020-259-アヤネ" = "ですがこの爆発は、攻撃のためというよりも……"
"13020-260-ホシノ" = "んー……もしかして、発掘地帯の方じゃない？"
"13020-261-アヤネ" = "いえ、違うようです……！これは……"
"13020-265-アヤネ" = "……。"
"13020-266-アヤネ" = "なっ……誰かがこちらの方へ……？#n規模は数十人、初めて見る制服です！"
"13020-267-セリカ" = "一体何なの！？"
"13020-269-アヤネ" = "判明しました！#n彼女たちは……"
"13020-278-ノゾミ" = "あはははっ、良いね良いねぇ！"
"13020-280" = "次回;ハイランダー鉄道学園"
