[translation]
"13195-2-ホシノ" = "ノノミちゃん、大丈夫！？"
"13195-3-ノノミ" = "はい、大丈夫です……。"
"13195-4-ホシノ" = "そっか、良かった。"
"13195-11-シロコ" = "ホシノ先輩！？"
"13195-15-アヤネ" = "追いかけましょう！"
"13195-16-ノノミ" = "私も一緒に行きます！"
"13195-18" = "次回;宝探し"
