[translation]
"13220-1" = "第22話;暴走列車"
"13220-5-ノゾミ" = "残念なお知らせなんだけど、カイザーに追いつかれそうでさぁ。"
"13220-6-アヤネ" = "そんな……！"
"13220-7-ヒカリ" = "んー、無理かも。"
"13220-8" = "[s] \"どうしようか……。\""
"13220-9-ノゾミ" = "……仕方ないし、私らが足止めしてあげるよ。#n先に列車を降りて、目的地に向かいなって。"
"13220-10-ヒカリ" = "うぉー、必殺複線ドリフトのでばーん！"
"13220-12-アヤネ" = "で、ですが……。"
"13220-14-ノゾミ" = "セクター35-9なら、こっから1時間くらいで着くっしょ。#n私らのことは、別に心配しなくておっけー。"
"13220-15-ヒカリ" = "時間稼いだら白旗上げるしー。"
"13220-17-アヤネ" = "……はい、分かりました。"
"13220-18-ノノミ" = "助けていただいて、ありがとうございます。"
"13220-20-ノゾミ" = "あははっ！なんか正義の味方みたいじゃん。#nそんなキャラじゃないのにさ。"
"13220-21-ヒカリ" = "なに言ってるのさー、ノゾミ。#nヒーローで良いじゃーん。"
"13220-23-セリカ" = "……列車が止まった瞬間、走れば良いのよね？"
"13220-24-シロコ" = "ん、先生は私が守る。#nしっかり掴まってて。"
"13220-25" = "[s] \"ありがとう、シロコ。\""
"13220-31-ノゾミ" = "衝撃に備えなよ！"
"13220-32-ヒカリ" = "さーん、にー……。"
"13220-38-ヒカリ" = "どかーーーん！"
