[translation]
"13240-1" = "第24話;列車砲シェマタ"
"13240-10-スオウ" = "くっ！"
"13240-17-スオウ" = "……ここまでだとは。"
"13240-18-ホシノ" = "さっさと[ruby=ど]退[/ruby]いてもらって良いかな、眼帯ちゃん。"
"13240-19-ホシノ" = "後輩たちが来る前に、破壊したいんだよね。"
"13240-20-スオウ" = "ああ、そうだろうな。"
"13240-21-スオウ" = "……だが、まだ私は負けてなどいない！"
"13240-25-ホシノ" = "……邪魔だよ。"
"13240-27-スオウ" = "行かせるものか！"
"13240-37-地下生活者" = "……攻略は、いよいよ最終段階です。"
"13240-38-地下生活者" = "攻略法1つ目、「既に起きた出来事は変えられない」。"
"13240-39-地下生活者" = "2つ目、「肉体には物理的な限界がある」。"
"13240-40-地下生活者" = "3つ目、「心は予測も制御もできない」。"
"13240-45-地下生活者" = "そして4つ目、「小さな傷が致命傷となる」。"
"13240-46-地下生活者" = "これは欲望と罪悪に苛まれる過程で、心理を追求するキャンペーン。"
"13240-47-地下生活者" = "この混沌が終わりを迎えたその時、#n私は「六つ目の古則」に到達することでしょう。"
"13240-51-地下生活者" = "……ん？"
"13240-52-地下生活者" = "何かが……。"
"13240-59-セリカ" = "着いたのね……？"
"13240-60-シロコ" = "ん、ここにホシノ先輩がいるはず。"
"13240-61-ノノミ" = "スオウさんも、列車砲も……。"
"13240-63-アヤネ" = "あちらです、急ぎましょう！"
"13240-71-アヤネ" = "……。"
"13240-72-セリカ" = "なんか、想像と違うんだけど……？"
"13240-73-アヤネ" = "数百年前のアビドス生徒会が建てた展示館……#nのようなところだと聞いていましたが。"
"13240-74-セリカ" = "機関砲に対空砲まであるじゃない。"
"13240-75-シロコ" = "ゲヘナのマークがある。"
"13240-76-セリカ" = "ど、どうしてアビドス砂漠にゲヘナのマークが？"
"13240-77-ノノミ" = "……。"
"13240-82-シロコ" = "見て。"
"13240-83-セリカ" = "なっ。"
"13240-85-アヤネ" = "アレが……。"
"13240-88" = "[ns] \"アレが例の……。\""
"13240-89-ノノミ" = "列車砲……。"
"13240-90-セリカ" = "ま、待って。あんなに大きいとか聞いてないわよ。#n遠近感がおかしくなるんだけど！？"
"13240-91-アヤネ" = "……こ、こんなに大きいなんて。"
"13240-92-シロコ" = "ん……。"
"13240-95" = "[ns] \"なるほど、ゲヘナも……。\""
"13240-96-ノノミ" = "砂漠横断鉄道事業に入れ知恵した人物が、おそらくそうなのかと。"
"13240-97-アヤネ" = "でも、あの大きさは理解できません……。#nキヴォトスにこんな技術があるなんて……。"
"13240-99-セリカ" = "なら、どうやって作ったのかしら……。"
"13240-100-シロコ" = "……。"
"13240-102-アロナ" = "先生！"
"13240-105-アロナ" = "アレは現時点のキヴォトスに存在しない技術が使われています！"
"13240-106-アロナ" = "古代兵器、もしくはそれに並ぶ……！"
"13240-107-アロナ" = "まさか……！？"
"13240-108" = "[s] \"……ゲマトリアかもしれない。\""
"13240-109-アロナ" = "もう少し調べてみます！"
"13240-110-アロナ" = "うう……こういう時、プラナちゃんがいれば……。"
"13240-111" = "[s] \"プラナの調子はどう？\""
"13240-112-アロナ" = "まだ眠っています。#nなんだかすごく疲れているみたいで……。"
"13240-117-アロナ" = "ぷ、プラナちゃん！？"
"13240-118-プラナ" = "アロナ、先輩……先生。"
"13240-124-アロナ" = "プラナちゃん、大丈夫ですか？#nどこか痛みませんか！？"
"13240-125" = "[s] \"プラナ、大丈夫？\""
"13240-126-プラナ" = "……眠っている最中に、視線を感じました。"
"13240-127-アロナ" = "視線……？"
"13240-128-プラナ" = "……はい。#n今も私たちは、誰かに観測されています。"
"13240-129" = "[s] \"……。\""
"13240-130-アロナ" = "ええっ！？#nここには誰もいませんが……。"
"13240-131-アロナ" = "プラナちゃん……？"
"13240-132-プラナ" = "この視線は……。"
"13240-137-アロナ" = "プラナちゃん……！？"
"13240-146-アヤネ" = "これは……！？"
"13240-147-ノノミ" = "あっちです！"
"13240-148-シロコ" = "ホシノ先輩の銃声！"
"13240-149-セリカ" = "行くわよ！"
"13240-154-セリカ" = "先生も早く！"
"13240-155" = "[ns] \"……分かった！\""
