[translation]
"13260-1" = "第26話;最後の戦い（２）"
"13260-4" = "[ns] \"……！\""
"13260-5-シロコ" = "はぁ……はぁっ……。"
"13260-6-セリカ" = "つ、強すぎる……。"
"13260-7-ノノミ" = "これがホシノ先輩の本当の力……？"
"13260-9-アヤネ" = "ま、まだです……！"
"13260-11-ホシノ" = "いいや、ここまでだよ。"
"13260-16-アヤネ" = "足が、もう……。"
"13260-20-セリカ" = "ノノミ先輩、大丈夫！？"
"13260-21-ノノミ" = "わ、私も、動けないです……。"
"13260-22-セリカ" = "うぅ、正直限界ね……。"
"13260-27-シロコ" = "……はぁっ、はぁ。"
"13260-28-ホシノ" = "シロコちゃん、まだやるつもり？"
"13260-32-シロコ" = "……ん、勝負！"
"13260-33-ホシノ" = "もうやめよう。4対1でも勝てなかったんだから、#n一人で来たところで結果は分かってるでしょ。"
"13260-34-シロコ" = "私は自分より強い人の言葉しか聞かない。#nだから、勝負。"
"13260-35-ホシノ" = "……。"
"13260-36-シロコ" = "ん、今度こそ負けない。"
"13260-37-ホシノ" = "……そっか。"
