[translation]
"13300-1" = "第30話;手帳の存在"
"13300-3-ホシノ" = "もう、何やってるんですか！"
"13300-5-ユメ" = "ほ、ホシノちゃん、ごめんね。#n私のせいで……。"
"13300-6-ホシノ" = "ごめんじゃありません！#nなんで毎回毎回騙されるんですか！？"
"13300-7-ユメ" = "そ、それは……。"
"13300-8-ホシノ" = "こんな体たらくで「夢と希望に満ちたアビドス」なんて、よく言えたものですね……。#nはぁ、もう一人で勝手にやってください！"
"13300-9-ユメ" = "ほ、ホシノちゃん……？"
"13300-11-ホシノ" = "もう付き合ってられません！#n生徒会は終わりです！"
"13300-15-ホシノ" = "先輩なんて知りません！"
"13300-20-ユメ" = "……。"
"13300-22-ホシノ" = "違うんです、先輩。#nあれは、本心じゃなくて……。"
"13300-23-ホシノ" = "勢いで、ちょっと強く言ってしまっただけなんです。"
"13300-24-ホシノ" = "すぐ戻るつもりだったのに……。"
"13300-25-ホシノ" = "まさか……あれが最後になるとは、思わなくって。"
"13300-28-ホシノ" = "ユメ先輩、戻りましたよ。"
"13300-29-ホシノ" = "次は気をつければ良いですから。"
"13300-30-ホシノ" = "それより……。"
"13300-37-ホシノ" = "……ユメ先輩？"
"13300-38-ホシノ" = "どこ行ってるんだろう、帰ってきてると思ったのに。"
"13300-43-ホシノ" = "こんなメモ、あったかな……？"
"13300-47-ホシノ" = "「いつもありがとう、ホシノちゃん！！お元気でね！」……？"
"13300-50-ホシノ" = "……ユメ先輩？"
"13300-52-ホシノ" = "ユメ先輩……。"
"13300-54-ホシノ" = "ユメ先輩！"
"13300-56-ホシノ" = "ユメ先輩！？"
"13300-68-ユメ" = "ごめんね、ホシノちゃん#n電波がうまく@#$%"
"13300-69-ユメ" = "砂漠にいたら@#&%砂嵐に遭って&#@"
"13300-72-ユメ" = "ホシノちゃん……ごめんね"
"13300-73-ユメ" = "またコンパスを忘れちゃった"
"13300-74-ユメ" = "メモも残したけど、ここでも送るね#n#n私の手帳は、あそこにあるから"
"13300-75-ユメ" = "ホシノちゃんもよく知っている@$^$%@#$#n目立つ場所に置いたから、すぐわかると思う"
"13300-78-ユメ" = "ホシノちゃん、私は"
"13300-80-ホシノ" = "ユメ先輩……。"
"13300-81-ホシノ" = "どうして砂漠に行ったんですか……？"
"13300-82-ホシノ" = "……「用事」ってなんですか？#n私がいない間に何があったんですか……？"
"13300-83-ホシノ" = "……手帳はどこにあるんですか？"
"13300-84-ホシノ" = "手帳には……何が書かれているんですか？"
"13300-85-ホシノ" = "……私は……手帳を見れないんですか……？"
"13300-86-ホシノ" = "もう付き合ってられません！#n生徒会は終わりです！"
"13300-88-ホシノ" = "私のせいですよね？"
"13300-89-ホシノ" = "あの言葉が先輩を傷つけた……先輩を追いやった……。"
"13300-90-ホシノ" = "「ホシノちゃん、私は」 。"
"13300-91-ホシノ" = "あのメッセージの続きはなんだったんですか？"
"13300-92-ホシノ" = "私には……分からなくて……。"
"13300-93-ホシノ" = "……ユメ先輩。"
"13300-96-ホシノ" = "どうして、どうして私は……。"
"13300-103-ホシノ" = "……。"
"13300-104-ホシノ" = "あれ……。"
"13300-105-ホシノ" = "……風紀委員長ちゃんは！？"
"13300-110-ホシノ" = "たしか、一緒に落ちたはず……。 "
"13300-111-ホシノ" = "まあ、今は他人の心配をしてる場合じゃないか。"
"13300-114-ホシノ" = "……大オアシス駅から、そう離れてないはず。"
"13300-115-ホシノ" = "ユメ先輩と一緒に来たから、覚えてる。"
"13300-116-ホシノ" = "もう少し進めば、かつてのオアシスがあって……。"
"13300-117-ホシノ" = "そこに、列車砲があるはず。"
"13300-118-ホシノ" = "早く、破壊するんだ。"
"13300-119-ホシノ" = "じゃないと……。"
"13300-120-ホシノ" = "私は――"
"13300-133-ホシノ" = "そろそろオアシスが……。"
"13300-138-ヒナ" = "そこまでよ、小鳥遊ホシノ。"
"13300-139-ホシノ" = "……！？"
"13300-150-ホシノ" = "……ぐっ。"
"13300-151-ホシノ" = "ごほっ、ごほっ……！"
"13300-156-ホシノ" = "ゆ、ユメ先輩……。"
"13300-160-ヒナ" = "……。 "
"13300-161-ヒナ" = "[ruby=くちなし]梔子[/ruby]ユメ……アビドスの生徒会長ね。"
"13300-163" = "次回;唯一の真実（１）"
