[translation]
"13340-1" = "第34話;謝罪"
"13340-3-ユメ" = "……先生。"
"13340-4" = "[ns] \"……？\""
"13340-5-ユメ" = "ひぃん……ご、ごめんなさい。"
"13340-6-ユメ" = "そろそろ準備をしないと、ホシノちゃんが怒っちゃいそうで……。"
"13340-11-ホシノ" = "ユメ先輩、[USERNAME]先生、早く来てください！#nオアシスで宝探しをするんですよね！"
"13340-12-ホシノ" = "先に校門で待ってますよ！"
"13340-13-ホシノ" = "早く来ないと一人で行っちゃいますからね！？"
"13340-17-ユメ" = "ふふっ……すっごく楽しそう。 "
"13340-18-ユメ" = "ホシノちゃん、先生が来てから変わった気がするなぁ。#nあっ、もちろん良い意味で！"
"13340-19" = "[s] \"……。\""
"13340-20-ユメ" = "……先生？"
"13340-21" = "[s] \"ユメ……。\""
"13340-22-ユメ" = "そんなに悲しそうな顔して、どうされました？"
"13340-23-ユメ" = "怖い夢でも見た、とか……？"
"13340-24" = "[s] \"ごめん、ユメ。\""
"13340-25-ユメ" = "……？"
"13340-26" = "[s] \"ごめんね……私は、大人なのに。\""
"13340-27-ユメ" = "……。"
"13340-28" = "[ns] \"できることなら、私は……。\""
"13340-30" = "[ns] \"私は……。\""
"13340-32-ユメ" = "先生。"
"13340-33-ユメ" = "事情は分からないですけど……。"
"13340-34-ユメ" = "きっと、先生のせいじゃありません。"
"13340-35-ユメ" = "だから、謝る必要なんてないと思います。"
"13340-36" = "[ns1] \"私には、時間を巻き戻せない。\"\n[ns2] \"死を、なかったことにはできない。\""
"13340-39" = "[ns] \"……そんな力は、存在しない。\""
"13340-41" = "[ns] \"私は、ただの平凡な人間だから。\""
"13340-44" = "[ns3] \"目の前に苦しんでいる子がいたら……。\"\n[ns4] \"手を差し伸べるだけで、精一杯。\""
"13340-47-ユメ" = "……先生。"
"13340-48-ユメ" = "今は、それで十分だと思いますよ。"
"13340-49-ユメ" = "小さな積み重ねが、いつか大きな奇跡になりますから！"
"13340-50-ユメ" = "あっ、奇跡なんて簡単に言うと、#nまた怒られちゃうかもしれないけど……。"
"13340-51-ユメ" = "私は信じて……ううん、信じたいの。"
"13340-55" = "[ns] \"ユメのその言葉、忘れない。\""
"13340-56-ユメ" = "はぅ、そんなに深い意味は……。"
"13340-60-ユメ" = "……先生は、これから苦しんでいる子を助けに行くんですか？"
"13340-61" = "[s] \"手の届く子を、私は救いたいんだ。\""
"13340-62-ユメ" = "助けられるといいですね！"
"13340-63" = "[s] \"助け出してみせるよ。\""
"13340-73" = "[ns] \"はじめまして、で良いのかな。\" "
"13340-74-地下生活者" = "貴様は、[USERNAME]先生！？"
"13340-75-地下生活者" = "な、何故ここに……！"
"13340-76" = "[s] \"ようやく会えたね、地下生活者。\""
"13340-77-地下生活者" = "何のつもりだ！？"
"13340-78-地下生活者" = "小生の勝ちでゲームは終了したはずだ！#n負け犬が今更何をしにきた！？"
"13340-79" = "[s] \"……いいや。\""
"13340-80-地下生活者" = "何ィッ？"
"13340-81" = "[s] \"まだ終わりじゃないよ。\""
"13340-90-プラナ" = "座標確認。#n発現した「色彩」の力で、強制転移シーケンスを発動します。"
"13340-94" = "[ns] \"シロコ！シロコを止めて――！\""
"13340-101-シロコ" = "……！"
"13340-102-シロコ" = "そんなものに手を出しちゃダメ。"
"13340-103-シロコ" = "ど、どうしてここに……！？"
"13340-113-シロコ" = "[ruby=すなおおかみ]砂狼シ[/ruby]ロコ、あなたは強い。"
"13340-114-シロコ" = "だって、私だから。"
"13340-115-シロコ" = "ん……だから大丈夫。"
"13340-119" = "[ns] \"シロコ！\""
"13340-120-一同" = "ん。"
"13340-124-シロコ" = "助けが必要なんでしょ？"
"13340-125-シロコ" = "ホシ―― "
"13340-127-シロコ" = "――ホシノ先輩を放っておいたら、世界は破滅へと向かう。"
"13340-128-シロコ" = "う、うん……。 "
"13340-129-シロコ" = "私は知ってる。#nアレは、アビドスで始まってるから。"
"13340-137-シロコ" = "避けた……！？"
"13340-141-ホシノ" = "……分から、ない。"
"13340-142-ホシノ" = "他の人に、この苦しみは……。"
"13340-143-シロコ" = "ううん。"
"13340-144-シロコ" = "私も、よく知ってる。"
"13340-147-シロコ" = "勝負しようか、ホシノ先輩。"
"13340-148-シロコ" = "勝てるの？ "
"13340-149-シロコ" = "ん、戦い方は分かってる。"
"13340-158-シロコ" = "前に戦ってるから。負けない。"
"13340-160" = "次回;テラー VS テラー"
