[translation]
"13360-1" = "第36話;手帳"
"13360-6-アヤネ" = "やりましたか……？"
"13360-7-セリカ" = "動きが止まったわ！"
"13360-8-ノノミ" = "雷も消えていきます！"
"13360-9-セリカ" = "これでホシノ先輩は元に戻るんだよね？"
"13360-13-シロコ" = "ん。#nこのままいけば、きっと――"
"13360-14-シロコ" = "ううん、そうはならない。"
"13360-18-ノノミ" = "ど、どうしてですか……？"
"13360-19-シロコ" = "一度でも反転した以上、もう戻ってこられない。#n死人が生き返るようなもの。"
"13360-20-シロコ" = "私が今、こうあるように。"
"13360-21-セリカ" = "でも、それじゃあ……。"
"13360-22-シロコ" = "ここに私が来た理由は、ホシノ先輩のヘイローを破壊するため。"
"13360-27-シロコ" = "そうしないと、あなた達を助けられない。"
"13360-28-シロコ" = "え？"
"13360-29-シロコ" = "早くしないと、ホシノ先輩に呼び寄せられた「アレ」が顕現して世界が滅びてしまう。#n――私のところと、同じように。"
"13360-30-シロコ" = "けど、ヘイローを破壊したら……。"
"13360-31-シロコ" = "……先輩も覚悟していたはず。#n以前、私たちに頼んだように。"
"13360-36-シロコ" = "私が辿った道とは違うけれど――結局、こうなる運命だった。"
"13360-37-シロコ" = "……ううん。#n覚悟はあっても、望んでいるかは別だと思う。あなたも、そうじゃないの。"
"13360-38-シロコ" = "……。"
"13360-45" = "[ns] \"どうしても助けたいんだ……何か、方法はないかな。\""
"13360-46-シロコ" = "方法……。"
"13360-47-シロコ" = "……これまで失敗ばかりだった私に、何ができるんだろう。"
"13360-51-シロコ" = "待って。"
"13360-52-シロコ" = "ホシノ先輩の胸元に、何かが……。"
"13360-56-シロコ" = "……初めて見る。#nまだ、形が定まりきっていない……？"
"13360-57-シロコ" = "ん……。"
"13360-58-アヤネ" = "もしかして……！"
"13360-59-セリカ" = "なんか……手帳、みたいな形してない？"
"13360-60-ノノミ" = "……！"
"13360-64" = "[ns] \"もしかして、ユメの……？\""
"13360-69-ホシノ" = "私は……。"
"13360-70-ホシノ" = "手帳、手帳はどこに……。"
"13360-71-ホシノ" = "……先輩。"
"13360-79" = "[ns1] \"ホシノは今も、砂漠を彷徨ってるんだ。\"\n[ns2] \"……ユメの手帳を見つけるために。\""
"13360-82-シロコ" = "……。"
"13360-86-セリカ" = "……ホシノ先輩。"
"13360-87-ノノミ" = "……。"
"13360-92-シロコ" = "ホシノ先輩は、まだ完全に反転したわけじゃない。"
"13360-93-シロコ" = "……おそらく、あの手帳の存在が最後の寄る辺になっているんだと思う。"
"13360-94" = "[s3] \"つまり、チャンスは残されてるんだよね。\"\n[s4] \"……ホシノに、伝えないと！\""
"13360-97-シロコ" = "……。"
"13360-102-ホシノ" = "――――！"
"13360-103-セリカ" = "ま、また動き出したわよ！"
"13360-105-プラナ" = "……状況を確認。"
"13360-106-アロナ" = "プラナちゃん……？"
"13360-107-プラナ" = "方法、リサーチ。"
"13360-112-プラナ" = "……ホシノさんの「神秘」が完全に反転してしまう前に、接触できそうです。"
"13360-113-アロナ" = "ど、どうやってですか……？"
"13360-114-プラナ" = "オーバークロックです、アロナ先輩。#n「シッテムの箱」の力を使って、擬似的な「ナラム・シンの玉座」を生成します。"
"13360-115-アロナ" = "えっ！？あれは「箱舟」があったからできたことで……#nシッテムの箱の力だけでは……。"
"13360-116-プラナ" = "先ほど、「地下生活者」の能力を分析したところ……。"
"13360-118-プラナ" = "次元や時間、実在の有無が確定せずに混ざり合う#n「混沌の領域」と類似した状況を作り出せれば……。"
"13360-119-プラナ" = "ホシノさんに声が届く可能性があると判明しました。"
"13360-120-アロナ" = "で、ですが、今の力では……。"
"13360-121-プラナ" = "肯定。#nなので、今から演算リソースの99％を先輩にお返しします。"
"13360-122-プラナ" = "そして私は、これより休眠状態に入ります。"
"13360-123-アロナ" = "きゅ、休眠状態……？"
"13360-124-プラナ" = "はい。#nシッテムの箱に潜り、混沌の領域を構築します。"
"13360-125-アロナ" = "こ、これでもしプラナちゃんの身に何かあったら……！"
"13360-126-プラナ" = "先生には秘密にしてください。"
"13360-127-アロナ" = "それはっ……！"
"13360-128-プラナ" = "間もなく実行を開始します。#n……先輩、ひとつお願いを聞いてもらえますか？"
"13360-129-アロナ" = "何でも言ってください、プラナちゃん。"
"13360-130-プラナ" = "……手を、握っていてほしいです。"
"13360-131-アロナ" = "手、ですか……？"
"13360-132-プラナ" = "……少し、怖いので。"
"13360-138-アロナ" = "もちろんです！#nプラナちゃんが帰ってくるまで、絶対に離しません！"
"13360-139-プラナ" = "ありがとうございます……アロナ先輩。"
"13360-142" = "[ns] アロナに方法を説明してもらった。"
"13360-146" = "[ns] みんなにも共有した。"
"13360-147-ノノミ" = "ホシノ先輩に直接触れる必要が……。"
"13360-148-シロコ" = "正確には、手帳に「シッテムの箱」を近づける。"
"13360-149-セリカ" = "どっちにしろ、先輩に近づかないといけないんじゃ……。"
"13360-150-アヤネ" = "まずは、ホシノ先輩の動きを止めなくてはいけません。"
"13360-151-シロコ" = "……了解。"
"13360-153-シロコ" = "先生、私にも指揮をお願い。"
"13360-154-セリカ" = "私たちだけで、いけるのかな……。"
"13360-155-ヒナ" = "……私も手伝う。"
"13360-159" = "[ns] \"ヒナ、体は大丈夫なの！？\""
"13360-160-ヒナ" = "ええ、状況は把握している。#nすぐに動きましょう。"
"13360-161-シロコ" = "……。"
"13360-162-ヒナ" = "あなたがもう一人[ruby=すなおおかみ]の砂狼シ[/ruby]ロコね。#n……何か問題でも？"
"13360-163-シロコ" = "……ううん？"
"13360-164-アヤネ" = "とにかく急ぎましょう。#nまた雷が大きくなってきました！"
"13360-165-シロコ" = "ん、これが最後のチャンス。"
