[translation]
"13400-1" = "第40話;夢が残した足跡"
"13400-5-ノノミ" = "雷が……。"
"13400-6-シロコ" = "オアシス全体に……。"
"13400-10-ホシノ" = "ヒナちゃん、立てる？"
"13400-14-ヒナ" = "……ええ、大丈夫。"
"13400-23-アヤネ" = "これは……。"
"13400-24-ノノミ" = "……花火？"
"13400-25-ヒナ" = "雷に反応したのかな……。"
"13400-34-アヤネ" = "……これは。"
"13400-35-セリカ" = "アレ、魚の形してない？"
"13400-36-ノノミ" = "きれい……まるで海みたいです！"
"13400-39-ホシノ" = "……。"
"13400-40-ヒナ" = "もしかして……#n何らかの刺激が加わると、プラズマを発生する鉱物じゃないかしら。"
"13400-41-ヒナ" = "でも、超高価で希少な金属のはず。"
"13400-42-ホシノ" = "……。"
"13400-45-シロコ" = "（超高価……？）"
"13400-46-シロコ" = "……日が昇る。"
"13400-49-ホシノ" = "……先輩の言う通りでした。"
"13400-50-ホシノ" = "見つけましたよ、お宝。"
"13400-51-ホシノ" = "まさか、本当に見つけられるとは思いませんでしたけど。"
"13400-52-ホシノ" = "私が間違ってました……。"
"13400-55-ホシノ" = "……先輩。"
"13400-63-セリカ" = "う、うわっ！#nさっきより勢いが！"
"13400-64-ヒナ" = "……なるほど、100g1000万円の価値を持ってるだけあるわ。"
"13400-65-セリカ" = "へ！？"
"13400-66-シロコ" = "え？"
"13400-67-ヒナ" = "ここ二年くらいの間に、十倍くらい相場が上がったのよ。"
"13400-68-セリカ" = "ちょ、ちょっと、この連鎖どうにかして止めないと！#nダメ、お金がっ！"
"13400-69-セリカ" = "少しでも確保するわよ！#nアヤネちゃん、スコップは！？"
"13400-70-アヤネ" = "いきなり言われても……。"
"13400-71-セリカ" = "もう、ちゃんと持ってきておかないから！"
"13400-74-シロコ" = "いや、たぶんツルハシじゃないと――"
"13400-75-シロコ" = "この爆発を止める方法は？"
"13400-76-ヒナ" = "……無理じゃないかしら。#n連鎖反応は、一帯の鉱物が燃え尽きるまで続く。"
"13400-77-ノノミ" = "わあ！#n幻想的ですね～☆"
"13400-82-シロコ" = "シロコ、私があげた覆面を袋にしないで。"
"13400-83-シロコ" = "でも……。"
"13400-84-セリカ" = "シロコ先輩、呼び方が一緒だと混乱するんだけど、何とかならない？"
"13400-85-シロコ" = "じゃあ、私は「ちびシロコ」って呼ぶよ。"
"13400-86-シロコ" = "ん、すぐに大きくなる。"
"13400-87-シロコ" = "なら、「よわシロコ」。"
"13400-91-セリカ" = "ちょっと、危ないでしょ！"
"13400-92-シロコ" = "無駄だよ。私はあなたにはない事を経験し、知らないことを知っている。この差は――"
"13400-93-シロコ" = "ん、今度こそ負けない。"
"13400-96-アヤネ" = "もう、落ち着いてください！"
"13400-97-ノノミ" = "わあ～、そろそろフィナーレですかね？"
"13400-106-ホシノ" = "うーん……。"
"13400-107-ホシノ" = "……まぁ、いっか。"
"13400-110-ホシノ" = "おじさんがカッコつけようとすると、いつもこんな感じだよね～。"
"13400-111-ホシノ" = "……うへ～。"
"13400-113" = "次回;残されたもの"
