[translation]
"10009040-1" = "第4話;襲撃その四"
"10009040-2-ヴァルキューレの生徒A" = "やはり「悪い警官」戦術ではダメだな。"
"10009040-3-ヴァルキューレの生徒B" = "やはり学ぶべきは「北風と太陽」……「良い警官」戦術の方で行こう！"
"10009040-4-ヴァルキューレの生徒A" = "よし！"
"10009040-10-ヴァルキューレの生徒A" = "やあワカモ、先ほどは済まなかったな。"
"10009040-11-ヴァルキューレの生徒B" = "こちらも気が立っていてな……せっかくのバレンタインデーだ、お詫びも兼ねてマカロンでもどうだ？"
"10009040-12-ヴァルキューレの生徒A" = "お互いこれを食べて落ち着きながら……"
"10009040-16-ヴァルキューレの生徒B" = "……え？"
"10009040-21-ヴァルキューレの生徒たち" = "い、いないだと……！？どこへ行った！？"
"10009040-24" = "（気を取り直して、セナと一緒にパトロールを……）"
"10009040-25" = "[s] \"……ちょっと待って。\""
"10009040-26-セナ" = "はい？"
"10009040-27" = "[s] \"何だか嫌な気配が……。\""
"10009040-35-フブキ" = "先生！"
"10009040-36" = "[s] \"来ると思った！\""
"10009040-42-ワカモ" = "もう少し、もう少しです……もうすぐ、この手で……！"
