[translation]
"10035075-2-ウォーターパークのオーナー" = "あっ！逃げるな！"
"10035075-8-カンナ" = "プールのなかに逃げられたか……。"
"10035075-9-カンナ" = "はやく追わなければ。また騒ぎを起こしかねない！"
"10035075-10-ウォーターパークのオーナー" = "ええ！今すぐプールの水を抜きます！"
"10035075-11-ウォーターパークのオーナー" = "水がなくなれば、隠れる場所もなくなるでしょう！"
"10035075-12-ウォーターパークのオーナー" = "そこを狙って、捕獲すれば……！"
"10035075-13" = "[s] \"ありがとう。お願いします。\""
"10035075-14-ウォーターパークのオーナー" = "先ほどは、大変失礼しました……。"
"10035075-15-ウォーターパークのオーナー" = "まさか本当にワニがいたとは……。#n一体どこから入ってきたのやら。"
"10035075-16-ウォーターパークのオーナー" = "とにかく、すぐに捕獲作戦を開始します。"
"10035075-17-ウォーターパークのオーナー" = "ここはもう警備員だけで十分です。#nヴァルキューレの方々のお手を煩わせることはありません。"
"10035075-18-ウォーターパークのオーナー" = "どうぞ、屋内でお休みください。"
"10035075-19-フブキ" = "んじゃ、お言葉に甘えて～。"
"10035075-20-キリノ" = "でも、まだ危険ですよね。お任せして良いのでしょうか？"
"10035075-24-カンナ" = "捕獲作戦はウォーターパークの警備員に任せよう。"
"10035075-25-キリノ" = "しかし……！"
"10035075-26-カンナ" = "キリノ、私たちはライフセーバーだ。"
"10035075-27-カンナ" = "利用客の安全を守らなければならない。#n今はメカワニを捕獲するよりも重要なことがある。"
"10035075-28-カンナ" = "……この事件の犯人は屋内にいるはずだ。"
"10035075-30-キリノ" = "この事件の犯人が、ですか！？"
"10035075-31-フブキ" = "やっぱり、そうだよねー。"
"10035075-32-キリノ" = "え……？誰のことなんですか？"
"10035075-33" = "[s] \"何となく分かったかも。\""
"10035075-34-キリノ" = "ほ、本官にも教えてください！"
"10035075-38-ウォーターパークのオーナー" = "よし。この水位なら行けるぞ！"
"10035075-39-ウォーターパークのオーナー" = "捕縛作戦を開始する！必ず見つけ出せ！"
"10035075-40-ウォーターパークのオーナー" = "まったく！オープン初日に、こんなことになるなんて！"
"10035075-41-ウォーターパークのオーナー" = "メカワニだかなんだか知らないが！絶対に許さんっ……！"
"10035075-42-ウォーターパークの警備兵A" = "これは……！オーナー、来てください！"
"10035075-43-ウォーターパークのオーナー" = "なんだ！？ワニか？"
"10035075-47-ウォーターパークの警備兵A" = "ワニではありませんが、こちらに……。"
"10035075-48-ウォーターパークのオーナー" = "排水口じゃないか。これが何か……？"
"10035075-49-ウォーターパークのオーナー" = "まさか……！これは！？"
"10035075-50-ウォーターパークの警備兵A" = "はい。鉄網が破られて、大きな穴が空いています！"
"10035075-51-ウォーターパークの警備兵A" = "あのワニが出入りするのに、十分な大きさかと！"
"10035075-52-ウォーターパークのオーナー" = "やつはここを通って、侵入したのか！"
"10035075-53-ウォーターパークのオーナー" = "脱出した痕跡はないようだな。ということは……！"
"10035075-54-ウォーターパークのオーナー" = "ワニはまだウォーターパーク内にいる！探し出せ！"
"10035075-56-警備員たち" = "はいっ！"
