[translation]
"10035005-1" = "プロローグ"
"10035005-4-キリノ" = "失礼します！"
"10035005-5-キリノ" = "生活安全局の[ruby=なかつかさ]中務[/ruby]キリノ、[ruby=ねむがき]合歓垣[/ruby]フブキ、公安局長に用事があって参りました！"
"10035005-6-キリノ" = "入室してもよろしいでしょうか！"
"10035005-7-フブキ" = "そんな固くなる必要ないでしょ。"
"10035005-8-フブキ" = "普通に入ればいいじゃん。"
"10035005-9-キリノ" = "で、ですが、他の事務局に立ち入る際は、申告する規則ではありませんか！"
"10035005-10-カンナ" = "お前たち、何をしている。"
"10035005-11-カンナ" = "立ち話なら、中に入るか端に避けるかしろ。"
"10035005-12-キリノ" = "あっ！カンナ公安局長！"
"10035005-13-フブキ" = "お、噂をすればだねぇ。"
"10035005-14-フブキ" = "探す手間が省けたよ～"
"10035005-15-カンナ" = "ん？"
"10035005-16-カンナ" = "私に何か用が？"
"10035005-17-キリノ" = "はい！局長にお話がありまして！"
"10035005-18-フブキ" = "そうそう。約束してたマスタードーナッツの限定ボックス、#nいつ買ってくれるのかな～って。"
"10035005-19-キリノ" = "ええ！いつ買ってくださるのか――"
"10035005-20-キリノ" = "――ではなく！"
"10035005-21-フブキ" = "私はそれが気になったから、ついて来たんだけど？"
"10035005-22-キリノ" = "ドーナッツなら、さっき食べたばかりではありませんか！"
"10035005-23-カンナ" = "……公務に関係ない話なら、後でいいか？"
"10035005-24-カンナ" = "ドーナッツは、来週あたりにな。"
"10035005-25-キリノ" = "あっ！待ってください！#nちゃんとした用件があるのです！"
"10035005-26-キリノ" = "支援要請が届きまして！"
"10035005-27-カンナ" = "――公安局に？"
"10035005-28-カンナ" = "銃撃戦か？まだ報告は入っていないが。"
"10035005-29-キリノ" = "いえ、保安任務です！"
"10035005-30-フブキ" = "もうすぐ、「エーギル」ってウォーターパークがオープンするでしょ？"
"10035005-31-フブキ" = "で、どうもそこのライフセーバーが足りないらしくて。"
"10035005-32-フブキ" = "「フリーパスをあげるから、手伝ってほしい」って要請があったわけ。"
"10035005-34-カンナ" = "ライフセーバーか……。"
"10035005-35-カンナ" = "しかし、何故ヴァルキューレ警察学校が民間企業の支援に？"
"10035005-36-カンナ" = "人員が足りないなら、雇うかオープンを遅らせればいいだろうに……。"
"10035005-37-フブキ" = "まぁ、そこを気にしてもね。#nどうせ、上の話し合いで何かあったんでしょ。"
"10035005-38-フブキ" = "私たちからしても、悪いことはなさそうだし？"
"10035005-39-フブキ" = "炎天下でパトロールしたり、山積みになってる書類を片付けたり、#n窓口でクレームを聞いたり……。"
"10035005-40-フブキ" = "そんな事するより、ウォーターパークの方が絶対楽なんだからさ。"
"10035005-41-フブキ" = "プールで浮き輪に体を預けて波を楽しむ～みたいな？"
"10035005-42-フブキ" = "たまには、そういうのも大事だよね。"
"10035005-43-カンナ" = "……休暇ではないだろうに。"
"10035005-44-カンナ" = "まあ、正式な命令が下りているのなら、構わないが。"
"10035005-45-カンナ" = "何故、私のところに？"
"10035005-46-カンナ" = "所属も違うだろう？"
"10035005-47-カンナ" = "出向届けなら、生活安全局の局長にした方がいいぞ。"
"10035005-48-キリノ" = "その、実はですね……。"
"10035005-49-キリノ" = "出向届の提出はもう終わっておりまして……。"
"10035005-50-カンナ" = "ならば、なおさら私を訪ねる必要はないはずだが……"
"10035005-51-キリノ" = "違うんです。#nその……"
"10035005-52-キリノ" = "カンナ局長も、出向者のリストに入っているのです！"
"10035005-56-カンナ" = "……は？"
"10035005-57" = "#video;10035"
