[translation]
"10035010-1" = "第1話;ライフセーバー、任務開始！"
"10035010-2-キリノ" = "やってきましたよ！"
"10035010-3-キリノ" = "ここが、D.U.最大規模のウォーターパーク「エーギル」ですか！"
"10035010-4-キリノ" = "広すぎて迷ってしまいそうです！"
"10035010-5-フブキ" = "はあ、よりによって屋外かぁ……"
"10035010-6-フブキ" = "これじゃ、炎天下のパトロールと同じじゃん。"
"10035010-7-キリノ" = "何を言っているんですか！フブキ！"
"10035010-8-キリノ" = "我々の職務は、市民の皆さんの安全を守ることなんですよ？"
"10035010-9-キリノ" = "ちょっと暑いからといって、挫けるわけにはいきません！"
"10035010-10-キリノ" = "我々の努力あってこそ、皆さんが快適にプールで過ごせるのですから！"
"10035010-12-フブキ" = "市民を守る前に、干からびちゃいそうなんだけど。"
"10035010-13-フブキ" = "日焼け止めも塗ってないしさ～"
"10035010-14-フブキ" = "屋内プールに配属してほしかったなぁ。"
"10035010-15-フブキ" = "ねえ、局長もそう思うでしょ？"
"10035010-19-カンナ" = "はぁ……。"
"10035010-20-キリノ" = "局長？どうしました？"
"10035010-21-キリノ" = "顔色が悪いですよ。それに、いつもより少し覇気がないような……"
"10035010-22-キリノ" = "も、もしかして、熱中症の初期症状でしょうか！？"
"10035010-23-キリノ" = "大変です！フブキ！局長を涼しい場所に連れて行きましょう！#nライフセーバーも呼ばないと……！"
"10035010-24-キリノ" = "あっ、ラ、ライフセーバーは私でした！"
"10035010-26-カンナ" = "落ち着けキリノ。私は熱中症などではない。"
"10035010-27-カンナ" = "ただ……この状況に頭が追いついていないだけだ。"
"10035010-28-フブキ" = "まだ？もう諦めたほうが早いよ～"
"10035010-29-カンナ" = "そう単純な話ではない。"
"10035010-30-カンナ" = "そもそも、初めてなんだ。"
"10035010-31-カンナ" = "ウォーターパークに来るのも、こんなに布面積が少ない服を着るのも。"
"10035010-32-カンナ" = "それに……勤務中にプールに来るのも。"
"10035010-34-キリノ" = "そ、そうでしたか……。"
"10035010-35-キリノ" = "そもそも、どうして局長が出向することになったのでしょう？"
"10035010-36-フブキ" = "だよね。私とキリノは生活安全局だから分かるけどさ。"
"10035010-37-フブキ" = "公安局長が一緒に出向だなんて、絶対何か裏があるでしょ～"
"10035010-39-カンナ" = "ああ、それは――"
"10035010-47-カンナ" = "副局長！これは一体どういうことだ！"
"10035010-48-？？？" = "あ、来たんすね、姉御。"
"10035010-49-？？？" = "今、懸垂中なんで……これだけやらせてください……！"
"10035010-50-？？？" = "っしょ！"
"10035010-53-コノカ" = "ふぅ～スッキリした。#nそれで何か用っすか？姉御。"
"10035010-54-カンナ" = "局内で本格的な運動はするなと……"
"10035010-55-カンナ" = "まあ、いい。"
"10035010-56-カンナ" = "何故、私が出向することになっているんだ？"
"10035010-57-カンナ" = "このままでは生活安全局の臨時局員としてプール行きだ！"
"10035010-59-コノカ" = "はぁ、そんなことになってるんすか～"
"10035010-60-カンナ" = "シラを切るな！#n企んだのはお前だろう、副局長！"
"10035010-61-カンナ" = "リストにはお前のサインがあった。"
"10035010-62-カンナ" = "言い逃れはできないぞ。"
"10035010-66-コノカ" = "ふっ、ははっ！思った通りっすね。"
"10035010-67-コノカ" = "「企む」ってほど、大それたことはしてないっすよ……。"
"10035010-68-コノカ" = "まあ、リストに姉御を入れたのは、あたしですが。"
"10035010-69-コノカ" = "ちょうど姉御がいない時に、要請が届いたのでね。"
"10035010-70-カンナ" = "お前っ……！"
"10035010-71-コノカ" = "これは姉御のためなんすよ。"
"10035010-72-カンナ" = "はぁ？"
"10035010-73-コノカ" = "だって、毎日毎日、犯罪者の取り調べやデスクワークで、#nまともに休んでないじゃないっすか。"
"10035010-74-コノカ" = "このままじゃ、マジで体壊しちゃいますよ？"
"10035010-75-カンナ" = "だから……私をウォーターパークに送りつけると？"
"10035010-76-コノカ" = "そういうことっす！"
"10035010-77-コノカ" = "ライフセーバーも別に楽じゃないっすけど。#nどうせ外部の人間に重要な仕事はさせないと思うんすよ。"
"10035010-78-コノカ" = "ウォーターパーク側としては「ヴァルキューレ警察学校が協力している」っていう#n安心感を売りにしたいだけっすから。"
"10035010-79-コノカ" = "だから、この機にリフレッシュしてきてほしいっす！"
"10035010-80-コノカ" = "ああ！働きすぎの上司を思う部下の心遣い。#n感動で泣いてくれてもいいんすよ！"
"10035010-82-カンナ" = "……今すぐ取り消せ。"
"10035010-83-カンナ" = "私には、プールで休んでいる暇などない。"
"10035010-84-カンナ" = "生活安全局に増員を要請するように。"
"10035010-88-コノカ" = "ちょ、待ってくださいよ、姉御。"
"10035010-89-コノカ" = "ほんとにそれで後悔しないんすか？"
"10035010-90-カンナ" = "……何がだ？"
"10035010-91-コノカ" = "ぶっちゃけ……これ、姉御にも良い機会になると思うんすよ。"
"10035010-92-カンナ" = "……？"
"10035010-94-コノカ" = "姉御……入学した時は生活安全局に志願してたんすよね？"
"10035010-95-カンナ" = "お前っ、どうしてそれを！？"
"10035010-96-コノカ" = "姉御ほどじゃないっすけど、副局長にも書類の閲覧権限はありますからね。"
"10035010-97-コノカ" = "気になって、ちょいと調べてみたんすよ。"
"10035010-98-コノカ" = "姉御は、公安局に必要な人っすけど……。"
"10035010-99-コノカ" = "心残りがあるのなら、この機にやってみてもいいんじゃないかなって。"
"10035010-100-コノカ" = "市民対応の業務、ずっとやってみたかったんじゃないんすか？"
"10035010-104-カンナ" = "ふっ。"
"10035010-105-コノカ" = "？"
"10035010-106-カンナ" = "調子に乗るな、副局長。"
"10035010-107-コノカ" = "はぇ？"
"10035010-108-カンナ" = "たしかに生活安全局を志望していた時期もある。#nだが、もうとっくに踏ん切りがついているんだ。"
"10035010-109-カンナ" = "こんな[ruby=こわもて]強面[/ruby]が、まともに市民対応ができるわけないだろう。"
"10035010-110-カンナ" = "いまさら心残りなど無い。"
"10035010-111-カンナ" = "出向者については、再考するよう上に要請しておく。"
"10035010-112-カンナ" = "これ以上、お前が動く必要はない。"
"10035010-114-コノカ" = "でも……。"
"10035010-115-コノカ" = "その、もう終わってるんすよ。"
"10035010-116-カンナ" = "何がだ？"
"10035010-117-コノカ" = "申請も通って、予算まで下りちゃってるっす。"
"10035010-118-コノカ" = "それにほら。本日付けで人事通達まで！"
"10035010-119-カンナ" = "なっ……！"
"10035010-122-カンナ" = "それは……機密事項だ。"
"10035010-123-フブキ" = "なになに？言いかけてやめられたら気になるじゃん。"
"10035010-125" = "[ns1] \"そうだね。私も聞きたかったのに。\"\n[ns2] \"途中で止められると気になるよ。\""
"10035010-129-キリノ" = "あれ？先生じゃありませんか！"
"10035010-130-キリノ" = "このようなところでお会いするとは、奇遇ですね！"
"10035010-131-フブキ" = "いやぁー、それにしっかり水着だし。"
"10035010-132-フブキ" = "さては、先生も遊ぶ気満々だねー？"
"10035010-133" = "[s] \"こんにちは、キリノにフブキ。それとカンナも。\""
"10035010-134-カンナ" = "ど、どうして[USERNAME]先生が、こちらに……？"
"10035010-135-カンナ" = "今回の支援任務は、シャーレとは関係ないはずですが。"
"10035010-136" = "[s] \"みんなの様子を見てほしいと連絡があって。\""
"10035010-137-カンナ" = "（副局長……！）"
"10035010-138" = "[s] \"まあ、私のことは気にしないで。\""
"10035010-140" = "[ns] \"ただの利用客だと思ってほしいな。\""
"10035010-141-キリノ" = "はい！分かりました！"
"10035010-142-キリノ" = "もしも溺れそうになったら、ご一報ください！#n本官がすぐ助けに行きます！"
"10035010-143" = "[s] （溺れてる時に連絡する余裕あるかな……？）"
"10035010-144-フブキ" = "せっかく会えたんだし、一緒にプールで遊ぼうよ。#nまあ、パトロールもほどほどにしつつさ。"
"10035010-145-フブキ" = "まずはフードコートのドーナッツ屋に行こっか。小腹も空いてきたし。"
"10035010-146-キリノ" = "またサボるつもりですか、フブキ！"
"10035010-150-カンナ" = "はあ……。"
"10035010-151" = "[s] \"カンナ、何か心配事？\""
"10035010-152-カンナ" = "あ、いえ。"
"10035010-153-カンナ" = "その、[USERNAME]先生にここでお会いすると思っていなかったもので。"
"10035010-154-カンナ" = "すこし驚いただけです。"
"10035010-155" = "[s] \"ライフセーバーの水着、似合ってるよ。\""
"10035010-156-カンナ" = "……気にかけていただき、ありがとうございます。"
"10035010-157-カンナ" = "ですが、やはりこれは、私には不適切なものでしょう。"
"10035010-158-キリノ" = "不適切……？あっ、サイズのことでしょうか？"
"10035010-159-フブキ" = "たしかに、ちょっとキツそうだよね～"
"10035010-160-カンナ" = "そ、そういう話ではない！"
"10035010-164-自動音声" = "業務放送です。待機中のライフセーバーのみなさん――"
"10035010-165-アナウンス" = "ブリーフィングを行います。施設中央に集合してください。"
"10035010-170-キリノ" = "ついに任務開始ですね！#n張り切っていきましょう！"
