[translation]
"10035150-1" = "後日談その4;河駒風ラブのシークレットバカンス（２）"
"10035150-4-ジャブジャブヘルメット団A" = "こ、ここはウォーターパーク……？"
"10035150-5-ジャブジャブヘルメット団B" = "今日オープンの？まさか水遊びって、ここで……！？"
"10035150-7-ラブ" = "当ったり前じゃない！"
"10035150-8-ラブ" = "本部のやつら！団員を差別するなんて！"
"10035150-9-ラブ" = "もういいわ！そんな場所に行くのはお断りよ！"
"10035150-10-ラブ" = "ここで海辺のパーティなんてかすんじゃうくらい、楽しく遊べばいいの！"
"10035150-11-ラブ" = "うちだけ呼ばれて、部下が夏を満喫できないなんてあり得ないわ！"
"10035150-16-ジャブジャブヘルメット団A" = "隊長……！"
"10035150-17-ジャブジャブヘルメット団B" = "うちらのために……！"
"10035150-19-ラブ" = "ま、まあ！うちだってウォーターパークってとこ、一度は来てみたかったし！"
"10035150-20-ラブ" = "いいからっ、もう！とにかく入るわよ！"
"10035150-23-一同" = "はい！隊長！"
"10035150-31-ウォーターパークのスタッフ" = "いらっしゃいませ！何名様ですか？"
"10035150-33-ラブ" = "3名よ！"
"10035150-35-ウォーターパークのスタッフ" = "かしこまりました！#n3名様の入場チケット、合計18000円になります。"
"10035150-39-ラブ" = "げげっ！？"
"10035150-40-ラブ" = "高すぎじゃない？"
"10035150-42-ウォーターパークのスタッフ" = "こちらは通常料金になりまして……。"
"10035150-43-ウォーターパークのスタッフ" = "割引も可能ですよ。"
"10035150-44-ラブ" = "どれぐらい下がるのよ？"
"10035150-45-ウォーターパークのスタッフ" = "まず、学生割引があります。"
"10035150-46-ウォーターパークのスタッフ" = "どこの学園の生徒さんでも学生証のご提示で半額になります！"
"10035150-47-ラブ" = "え、えっと……。"
"10035150-49-ジャブジャブヘルメット団A" = "た、隊長、うちら中退してるから学生証なんて持ってないですよ？"
"10035150-51-ラブ" = "ほ、他の割引はないの！？"
"10035150-52-ウォーターパークのスタッフ" = "そうですね……。#nボランティア活動の証明書があれば、30％割引になります。"
"10035150-53-ジャブジャブヘルメット団B" = "そんなもん持ってるわけが……。"
"10035150-54-ウォーターパークのスタッフ" = "えっと……"
"10035150-55-ウォーターパークのスタッフ" = "それでは、午後4時以降のご入場で20％割引になりますが……。"
"10035150-57-ラブ" = "まだ朝でしょ！？"
"10035150-58-ラブ" = "ここで午後4時になるまで待てってこと？"
"10035150-64-ウォーターパークのスタッフ" = "はぁ……。"
"10035150-65-ウォーターパークのスタッフ" = "ご予算は、どれくらいですか？"
"10035150-66-ラブ" = "えっと……今持ってるお金は……"
"10035150-70-ラブ" = "1500円だけ……。"
"10035150-71-ラブ" = "一人500円にしてくれない？"
"10035150-73-ウォーターパークのスタッフ" = "申し訳ありませんが、料金表にない割引はできません。"
"10035150-77-ウォーターパークのスタッフ" = "では、お次にお並びの方、どうぞ！"
"10035150-78-ラブ" = "待って！"
"10035150-79-ラブ" = "ここまで来ておいて、引き返せるわけないでしょ！？"
"10035150-81-ジャブジャブヘルメット団A" = "そうだそうだ！"
"10035150-82-ジャブジャブヘルメット団B" = "せっかく隊長がここまで連れてきてくれたのに……！"
"10035150-84-ラブ" = "お願いよ、なんとかできないの？"
"10035150-85-ラブ" = "足りないお金は、身体で支払ってもいいわ！"
"10035150-86-ウォーターパークのスタッフ" = "はあ、普段ならお断りするしかないのですが……。"
"10035150-90-ウォーターパークのスタッフ" = "オープン初日で人手が足りていないそうなんです。#n連絡してみるのでお待ちください。"
"10035150-92-ラブ" = "あ、ありがとう！"
"10035150-93-ラブ" = "うちら頑張るから！"
"10035150-101-ラブ" = "まあ、プールの掃除なんて簡単よね！"
"10035150-102-ラブ" = "うちがブラシを持つなんて、そうそうないことだけど……！"
"10035150-103-ラブ" = "ま、生きてれば、こんなこともあるわ！"
"10035150-109-ジャブジャブヘルメット団A" = "隊長！こちらは終わりました！"
"10035150-110-ジャブジャブヘルメット団B" = "こっちもです！"
"10035150-112-ラブ" = "よし！そろそろね――"
"10035150-119-ウォーターパークの案内放送" = "ご案内致します。"
"10035150-120-ウォーターパークの案内放送" = "ただ今よりウォーターパークを開場致します。待機中のお客様はゲートからご入場ください。"
"10035150-121-ジャブジャブヘルメット団A" = "つ、ついに！"
"10035150-122-ジャブジャブヘルメット団B" = "時間ですよ！隊長！"
"10035150-124-ラブ" = "よっし！"
"10035150-125-ラブ" = "足りない分は労働で支払った！後は思いっきり遊ぶだけね！"
"10035150-126-ラブ" = "あんたら！"
"10035150-129-一同" = "はい、隊長！"
"10035150-131-ラブ" = "死ぬ気で遊びつくすわよ！"
"10035150-132-ラブ" = "今日だけは無防備になって！思いっきり夏を楽しもうじゃないの！"
"10035150-133-ジャブジャブヘルメット団A" = "ほ、本当に警戒を解いてもいいんですか！？"
"10035150-134-ラブ" = "心配ないわ！だって、人工のウォーターパークには――"
"10035150-136-ラブ" = "ワニなんか現れるはずないんだから！"
