[translation]
"10049075-2-ラブ" = "マスコットを攻撃するなんて、あんたら正気か！？"
"10049075-4-ジャブジャブヘルメット団A" = "それが……むしろ攻撃されるのが正しいと言いますか……。"
"10049075-5-ジャブジャブヘルメット団B" = "あの怖そうなやつは敵役なので……うわああっ！"
"10049075-11-ラブ" = "違うわよ！うちが言ってるのは魔法少女のほう！！"
"10049075-12-ラブ" = "仲間なのに攻撃してきてるじゃない！"
"10049075-17-ラブ" = "ぎゃあっ！"
"10049075-19-レイサ" = "テルミットホワイト！スタナグちゃんに回復魔法をかけてあげてください！"
"10049075-20-スズミ" = "わ、分かりました！"
"10049075-27-ラブ" = "回復魔法！？[ruby=えいこうだん]曳光弾[/ruby]とナパーム弾でしょうが！！"
"10049075-28-レイサ" = "安心してください！#n[ruby=回復魔法]スラッグ弾[/ruby]をありったけ撃ち込んであげますから！"
"10049075-29-子供A" = "がんばれ、スタナグちゃん！"
"10049075-36-ラブ" = "味方役なんじゃないの！？"
"10049075-38-エラ" = "これでとどめよ！！"
"10049075-39-レイサ" = "ヒーリングドラゴンブレス！"
"10049075-45-ラブ" = "ぐあっ……！"
"10049075-50-子供A" = "スタナグちゃん！！"
"10049075-51-子供B" = "大丈夫だよ！倒れたって……スタナグちゃんはすぐ立ち上がるもん！"
"10049075-52-子供A" = "そうそう！毎回ボコボコにされて、いっつも回復してもらってるよね！"
"10049075-54-ラブ" = "そんな……マスコット……いない、わよ……。"
"10049075-59-レイサ" = "マジカル・キュア・ロープで縛って――"
"10049075-63-レイサ" = "マジカル・キュア・テープで口を塞いでおきました！"
"10049075-64-レイサ" = "エラ！スタナグちゃんの仇は、必ず取ってみせます！"
"10049075-65-レイサ" = "――スタナグちゃんを治療したら、また戻ってきますからね！"
"10049075-69" = "[ns5] \"みんなー！休憩時間だよ！\"\n[ns6] （シミコもついて来てね！）"
"10049075-75-ラブ" = "結局あんたら、何のつもりなのよ。"
"10049075-76-ラブ" = "変な格好だし、うちらにこんなことして……。"
"10049075-85-ラブ" = "それ……車のバッテリーじゃないわよね！？"
"10049075-86-ジャブジャブヘルメット団A" = "隊長！うちら、もしかして……白状するまで電流を……！"
"10049075-87-ジャブジャブヘルメット団B" = "白状することもないのに！？"
"10049075-88-ラブ" = "待て待て待て待て！！"
"10049075-93-ラブ" = "ぎゃあああぁぁぁっ！！"
