[translation]
"10049010-1" = "第1話;自警団の資格"
"10049010-2" = "トリニティ付設幼稚園・旧校舎"
"10049010-3-スケバンA" = "お前だって、うちらと一緒じゃんか！"
"10049010-5-スズミ" = "え？"
"10049010-6-スケバンB" = "おいバカやめろ！また閃光弾投げられるぞ！"
"10049010-7-スズミ" = "いえ……既に無力化した相手にまで、わざわざ攻撃はしません。"
"10049010-8-スズミ" = "それより、今なんと？"
"10049010-9-スズミ" = "「うちらと一緒」……？"
"10049010-10-スケバンA" = "お前、あれだろ？"
"10049010-11-スケバンA" = "[ruby=・   ・   ・]自警団[/ruby]とかってやつの、「トリニティの走る閃光弾」。"
"10049010-16-スズミ" = "……そうとも呼ばれていますね。"
"10049010-17-スケバンA" = "お前にこんなことする資格あんのか？"
"10049010-18-スケバンA" = "黒くねぇってことは、正義実現委員会ってわけでもないみてぇだし。"
"10049010-19-スケバンA" = "自警団ってのも、勝手に名乗ってるだけなんだろ？"
"10049010-20-スズミ" = "たしかに、私は正義実現委員会ではありません。"
"10049010-21-スズミ" = "ですが、治安を守る行為に資格が必要なのですか？"
"10049010-22-スケバンA" = "だから、うちらと一緒だって言ってんだよ。"
"10049010-23-スケバンA" = "関係ねぇ事に首突っ込んで、暴力で邪魔をする。#nしかも、うちらと違って正義面してるだけ質が悪ぃ。"
"10049010-24-スケバンA" = "なんで自警団なんかやってんだ？誰も分かっちゃくれねぇだろ？"
"10049010-25-スケバンA" = "もしかして……#n入りたくても、正義実現委員会には入れなかったのか？"
"10049010-26-スズミ" = "！！"
"10049010-27-スケバンA" = "資格もねぇのに暴力を振るう……これって犯罪だと思うんだけどな。"
"10049010-28-スケバンA" = "まぁ、もういいよ。こんなとこ、二度と来ねぇから。"
"10049010-32-スケバンB" = "え？えぇ……？"
"10049010-36-スズミ" = "……。"
"10049010-41-スケバンB" = "お、おい。いいのか？あんなこと言っちゃって……。"
"10049010-42-スケバンA" = "気にするこたぁねぇ。"
"10049010-43-スケバンA" = "ほら、あれ見ろよ。"
"10049010-45-スズミ" = "……。"
"10049010-47-スケバンA" = "あいつにはもう、何もできやしねぇ。"
"10049010-48-スケバンA" = "図星ってことさ。うちの言葉、相当効いたみたいだぜ？"
"10049010-49-スケバンB" = "い、今のうちに逃げるぞ！"
"10049010-55-スズミ" = "誰も分かってくれない……。"
"10049010-56-スズミ" = "正義実現委員会に入れなかった……。"
"10049010-57-スズミ" = "今までやってきたことは、犯罪……。"
"10049010-58-スズミ" = "……そう、なんですか？#n私の行いは――"
"10049010-63" = "トリニティ旧図書館"
"10049010-64-シミコ" = "新刊はこっちで……。"
"10049010-65-シミコ" = "他の図書館に寄贈する本はこっち……。"
"10049010-70-シミコ" = "よし！これで整理は終わりですね！"
"10049010-71-シミコ" = "あっ、もうこんな時間……早く帰らないと。"
"10049010-75-シミコ" = "……あれ？話し声が……倉庫の裏手から……？"
"10049010-79-ジャブジャブヘルメット団A" = "じゃあ、今週末でいいんだな？"
"10049010-80-ジャブジャブヘルメット団B" = "ああ。その日にしようって、ラブ隊長が。"
"10049010-81-ジャブジャブヘルメット団A" = "集合場所は……「ボーダーランド遊園地」だっけ。"
"10049010-85-シミコ" = "（ヘルメット団？どうしてこんな場所に？）"
"10049010-86-シミコ" = "（そういえば……人通りが少ないから、密会に使われているって噂がありましたね）"
"10049010-87-シミコ" = "（バレないうちに退散しないと……）"
"10049010-89-ジャブジャブヘルメット団B" = "こりゃあ、遊園地がめちゃくちゃになりそうだな。"
"10049010-90-シミコ" = "！"
"10049010-94-ジャブジャブヘルメット団A" = "逃すわけにはいかないんだ。仕方ないさ。"
"10049010-95-ジャブジャブヘルメット団B" = "怪我人もそうとう出るだろうな。"
"10049010-96-ジャブジャブヘルメット団A" = "まあ、向こうの出方次第だろ。"
"10049010-98-シミコ" = "（怪我人？いったい何を企んでいるのでしょう……？）"
"10049010-99-ジャブジャブヘルメット団A" = "でも、うちらだけで足りるのか？"
"10049010-100-ジャブジャブヘルメット団B" = "他からも支援がくるって話だ。それもあわせれば十分じゃねぇかな。"
"10049010-101-ジャブジャブヘルメット団A" = "ならいい。#n……そろそろ行こう。誰かに聞かれちゃマズいしな。"
"10049010-103-シミコ" = "（こ、こっちに来る……！？）"
"10049010-104-シミコ" = "（早く逃げないと……！）"
"10049010-111-シミコ" = "はぁ……はぁ……。"
"10049010-112-シミコ" = "あの二人の話……本当なんでしょうか。"
"10049010-113-シミコ" = "今週末、「ボーダーランド遊園地」で……怪我人が出る……。"
"10049010-114-シミコ" = "ラブ隊長の指示……とも言っていましたし……。"
"10049010-115-シミコ" = "放っておくわけにはいきませんよね。まずは通報を……。"
"10049010-119-シミコ" = "ひゃうっ！"
"10049010-120-スズミ" = "……。"
"10049010-121-シミコ" = "すっ、すみません……って、スズミさん？"
"10049010-122-シミコ" = "ちょうどよかったです！"
"10049010-123-シミコ" = "旧図書館の倉庫裏で、ヘルメット団が悪巧みをしているんです！"
"10049010-124-シミコ" = "自警団にお願いできませんか？"
"10049010-125-スズミ" = "えっ？#n……あっ、はい。"
"10049010-126-スズミ" = "であれば――"
"10049010-130-スケバンA" = "だから、うちらと一緒だって言ってんだよ。"
"10049010-134" = "[log=불량배 스케반 A]もしかして……入りたくても、#n正義実現委員会には入れなかったのか？[/log]"
"10049010-137-スズミ" = "……。"
"10049010-138-シミコ" = "スズミさん？"
"10049010-139-スズミ" = "一緒に、通報しに行きましょうか。"
"10049010-140-スズミ" = "おそらくこれは……正義実現委員会の仕事ですから。"
"10049010-141-シミコ" = "え……？そう、なんですね……？"
"10049010-142-シミコ" = "わ、分かりました！行きましょうか。"
"10049010-143-スズミ" = "……。"
