[translation]
"10049050-1" = "第5話;追跡！ヘルメット団！"
"10049050-2-スズミ" = "……。"
"10049050-3-スズミ" = "はぁ……はぁ……。"
"10049050-7-マシロ" = "ステージから観客席を基準に2時の方向、見えますか？"
"10049050-8-マシロ" = "[ruby=こまかぜ]河駒風[/ruby]ラブを始め、ジャブジャブヘルメット団と推定される3人組を発見しました。"
"10049050-10-レイサ" = "！！"
"10049050-11-マシロ" = "身元の特定と、脅威の有無について確認をお願いします。"
"10049050-12-マシロ" = "現在は荷車を引きながら移動中です。"
"10049050-13-マシロ" = "積荷には……ポップコーンバケットと、手榴弾のようなものが見えます……！"
"10049050-15" = "[ns] \"手榴弾！？\""
"10049050-16-マシロ" = "ここからでは不明瞭で、たしかなことが言えません。"
"10049050-17-マシロ" = "接近し、現場での確認をお願いします。"
"10049050-21-ジャブジャブヘルメット団A" = "隊長、これで全部ですか？"
"10049050-22-ラブ" = "そんなわけないじゃない。やるからには徹底的にやるわよ。"
"10049050-23-ジャブジャブヘルメット団B" = "さすが隊長！これで大儲けですね！"
"10049050-24-ラブ" = "次はこの辺のはずだけど……なんか急に混んできてない？"
"10049050-25-ジャブジャブヘルメット団A" = "ですね。#n……おい、道を塞ぐなよ！"
"10049050-30-スズミ" = "あ……。"
"10049050-31-ラブ" = "え……？"
"10049050-32-ジャブジャブヘルメット団A" = "隊長？どうかしました？"
"10049050-33-ラブ" = "いや、その……。"
"10049050-34-ラブ" = "ステージに立ってる、あのピンク色の服を着たやつ。"
"10049050-35-ジャブジャブヘルメット団B" = "え？ただのキャストじゃないですか？子供向けのショーだし。"
"10049050-36-ラブ" = "たぶん会ったことはないんだけど……。"
"10049050-37-ラブ" = "ここからでも分かる。"
"10049050-38-ラブ" = "強いわね、あいつ。"
"10049050-45-ラブ" = "逃げろ！！"
"10049050-49-ジャブジャブヘルメット団A" = "はい！？"
"10049050-59-スズミ" = "河駒風ラブを確認しました！その他に、ヘルメット団が2名！"
"10049050-60-スズミ" = "ゲヘナエリアのほうへ逃走しました。追跡を開始します！"
"10049050-64-レイサ" = "スズ――テルミットホワイト！ショーはまだ……！"
"10049050-66-観客A" = "ステージから飛び降りた！？"
"10049050-67-観客B" = "どういうこと！？"
"10049050-69-子供A" = "テルミットホワイト！"
"10049050-70-観客A" = "こ、これも演出なのか！？"
"10049050-75" = "[ns] \"ついて行こう！\""
"10049050-76-レイサ" = "はい！"
"10049050-78-マシロ" = "スズミさん！確認だけで十分です！"
"10049050-79-マシロ" = "ゲヘナエリアに入られたら、正義実現委員会は支援をできません！"
"10049050-80-スズミ" = "分かっていますが……事態は一刻を争います。"
"10049050-81-スズミ" = "積荷に、大量の手榴弾……のような物が見えました。"
"10049050-82-スズミ" = "支援は大丈夫です。"
"10049050-83-スズミ" = "私が、なんとかします。"
"10049050-84-レイサ" = "ピンクもいますよ！"
"10049050-88-ジャブジャブヘルメット団A" = "ぜぇ……ぜぇ……！"
"10049050-89-ジャブジャブヘルメット団B" = "隊長！あいつら何者なんですか！？"
"10049050-90-ラブ" = "知らないわよ！でも、追ってくるってことは敵なんでしょ！"
"10049050-91-ジャブジャブヘルメット団A" = "ステージの上でショーをやってたみたいですし……。"
"10049050-92-ジャブジャブヘルメット団A" = "もしかして、これも演出なのかも……？"
"10049050-93-ラブ" = "そんな危ないこと、子供向けでやる！？"
"10049050-94-スズミ" = "止まってください。"
"10049050-100-ラブ" = "うわっ、いつの間に！？"
"10049050-101-ジャブジャブヘルメット団A" = "追い越されたってこと！？"
"10049050-103-レイサ" = "退路はテルミットピンクが塞ぎました！#n大人しくヘヴィキャリバーズに投降してください！"
"10049050-105-ラブ" = "ヘヴィキャリバーズ……？"
"10049050-106-ラブ" = "街の子供らが遊んでるおもちゃだっけ？"
"10049050-107-ラブ" = "あんたらって……あれなの？何かに熱中してる――"
"10049050-109-ジャブジャブヘルメット団A" = "マニアですよ。いや、オタク……かも？"
"10049050-110-ジャブジャブヘルメット団B" = "それより、なんでピンクなんだ？紫色だし、パープルじゃない？"
"10049050-112-レイサ" = "理由を説明したらネタバレになってしまいますので、本編を見るのをおすすめします！"
"10049050-113-スズミ" = "（私たちの正体には気づいていないようですね。それは助かりますが……）"
"10049050-117-観客A" = "あっ！イマーシブ・シアターが始まったみたい！"
"10049050-118-観客B" = "何それ？"
"10049050-119-観客A" = "ステージを飛び出して、色んな場所を舞台にするショーだよ！"
"10049050-120-子供A" = "あ！ピンクとホワイト！ここにいた！"
"10049050-121-子供B" = "悪いヤツとたたかってる！"
"10049050-125-スズミ" = "（困りました……観客がどんどん集まってきていますね……）"
"10049050-126-スズミ" = "（子供もいる状況では、閃光弾を使えません）"
"10049050-127-スズミ" = "（ひとまず、話し合いでなんとかするしか……）"
"10049050-128-スズミ" = "少々確認したいことがありますので、ご同行願えますか？"
"10049050-129" = "[s] \"ちょっとお話しない？\""
"10049050-131-ラブ" = "げっ、シャーレの先生！？"
"10049050-132-ラブ" = "そこまでして邪魔したいってこと？#nそれなら――"
"10049050-133-ラブ" = "お前ら！準備はいいか？"
"10049050-135-ジャブジャブヘルメット団A" = "はい！隊長！"
"10049050-136-ジャブジャブヘルメット団B" = "いつでも！"
"10049050-138-ラブ" = "じゃあ――"
"10049050-139-ラブ" = "攻撃、開始！"
