[translation]
"10049080-1" = "第8話;良いことをする資格"
"10049080-2-ラブ" = "わあぁ！う、うちらが悪かったから！！"
"10049080-3-ジャブジャブヘルメット団B" = "ゆ、許してぇ！隊長の弱点は全部言うからぁ！！"
"10049080-4-ジャブジャブヘルメット団A" = "た、隊長は握力が弱くて……瓶のフタを開けられないんだ！！"
"10049080-5-ジャブジャブヘルメット団B" = "あ、あと！二段ベッドの上だと怖くて眠れないんだ！！"
"10049080-6-ラブ" = "ちょっと！！！"
"10049080-14-レイサ" = "おぉー！"
"10049080-15-スズミ" = "ふぅ……。"
"10049080-16-スズミ" = "車のバッテリーがあって良かったです。"
"10049080-17-スズミ" = "まさか、電気が通っていないとは思いませんでした。"
"10049080-18-スズミ" = "……ところで、さっきは何のお話でしたか？"
"10049080-19" = "[s1] \"ラブは瓶の蓋を開けられないんだって。\"\n[s2] \"ラブは二段ベッドの上が怖いんだって。\""
"10049080-22-ラブ" = "先生！！！"
"10049080-23-スズミ" = "そうでしたか。"
"10049080-24-スズミ" = "とりあえず、情報を整理させてください。"
"10049080-25-スズミ" = "まずシミコさん、その格好は一体……？"
"10049080-26-シミコ" = "これは、魔法少女ヘヴィキャリバーの悪の幹部「エラ」です。"
"10049080-27-スズミ" = "たしかに……そのようですが……。"
"10049080-28-スズミ" = "今まで、どこにいらしたんですか？"
"10049080-29-シミコ" = "えっと……私は悪役ですよね？"
"10049080-30-スズミ" = "そうですね。"
"10049080-31-シミコ" = "だとすれば、最初から一緒では話がおかしくなってしまうので……タイミングを見計らっていました。"
"10049080-33-レイサ" = "なるほど！完璧な登場でしたよ！"
"10049080-34" = "[ns] \"思い返せばたしかに！\""
"10049080-36-スズミ" = "……。"
"10049080-37-スズミ" = "期せずして、奇襲に繋がりましたし……。"
"10049080-38-スズミ" = "一番必要なときに来てくれました。ありがとうございます。"
"10049080-42-スズミ" = "次は、[ruby=こまかぜ]河駒風[/ruby]ラブさん。"
"10049080-43-スズミ" = "ここまで長かったですが……やっとお話を聞けます。"
"10049080-44-スズミ" = "いくつか、伺いたいことがあります。"
"10049080-45-スズミ" = "この遊園地で何を企んでいたのですか？"
"10049080-46-ラブ" = "企む？だから何の話よ。"
"10049080-48-シミコ" = "3日前……トリニティの倉庫裏で話していましたよね？"
"10049080-49-シミコ" = "「遊園地がめちゃくちゃになって、怪我人が出る」って！"
"10049080-50-シミコ" = "現に、あんなにたくさんの手榴弾を持ち歩いていたわけですし。"
"10049080-52-ジャブジャブヘルメット団A" = "き、聞かれてたぁ！？"
"10049080-53-ジャブジャブヘルメット団B" = "だから、ああいうのはモモトークでって言ったのに！"
"10049080-55-ラブ" = "それ、どういうこと？"
"10049080-56-ラブ" = "遊園地をめちゃくちゃにする？怪我人を出す？"
"10049080-57-ラブ" = "うちはそんなこと指示してないわよ！？"
"10049080-59-ジャブジャブヘルメット団A" = "誤解です！そんなことするわけないじゃないですか！"
"10049080-60-ジャブジャブヘルメット団B" = "めちゃくちゃにできるだけの爆弾があるなら、撤去工事のバイトやってますって！"
"10049080-61-ジャブジャブヘルメット団A" = "ご飯もちゃんと食べれてないのに、そんな無茶できないですよ！"
"10049080-63-ラブ" = "じゃあ、あいつらが言ってるのは何なのよ？"
"10049080-65-ジャブジャブヘルメット団A" = "「ターゲット」のことを勘違いしてるんじゃないですか？"
"10049080-66-ジャブジャブヘルメット団B" = "たしか……ターゲットが抵抗したら戦闘になって、遊園地がめちゃくちゃになる……みたいな話はしたような……。"
"10049080-68-スズミ" = "待ってください。「ターゲット」とは誰ですか？"
"10049080-69-スズミ" = "誰を、なぜ狙っているのか。説明してください。"
"10049080-71-ラブ" = "教えてやれば、もう邪魔しないでくれるわけ？"
"10049080-72-スズミ" = "もちろんです。#n……悪いことをしているのでなければ、ですが。"
"10049080-74" = "[ns] \"私からも保証するよ。\""
"10049080-75-ラブ" = "ちっ、先生まで……。"
"10049080-76-ラブ" = "分かった、分かった。はぁ……。"
"10049080-77-ラブ" = "今のうちらは、取り締まりの手伝いをやってるの。"
"10049080-78-スズミ" = "ヘルメット団がですか？#nそれはまた、どういう権限で？"
"10049080-79-ラブ" = "別にいいでしょ？良いことするのに権限なんて要る？"
"10049080-83-ラブ" = "うちらだって、稼げるんだったら良い仕事がしたいのよ。"
"10049080-84-ラブ" = "ヴァルキューレも、風紀委員会も、正義実現委員会にも、面倒をかけない仕事をね。"
"10049080-85-ラブ" = "で、仕事の内容なんだけど……最近、変なパチモンが出回ってるらしいの。"
"10049080-86-ラブ" = "その犯人を捕まえれば、褒賞金が出るって話。"
"10049080-87-ラブ" = "だから、うちらもひと稼ぎさせてもらおうと思ったわけ。"
"10049080-89-スズミ" = "パチモン……ですか？"
"10049080-90-ラブ" = "そう。うちらの荷車に積んである手榴弾みたいにね。"
"10049080-91-ラブ" = "なんか……よく分からない謳い文句だったわよ。ゲルマニウム手榴弾だ、とか。安全ピンの形が三角形だからトライアングルフォースで健康にいい、とか……。"
"10049080-92-ラブ" = "他に、安っぽいガラクタもいっぱいあったわ。"
"10049080-93-ラブ" = "空気が抜ける風船とか、作りの甘いポップコーンバケットとか。"
"10049080-94-ラブ" = "手榴弾とポップコーンバケットは押収したけど、まだ犯人は捕まえられてない。"
"10049080-95-ラブ" = "遊園地は広いし……このまま取り逃がしそうだけどね……。"
"10049080-96-スズミ" = "空気が抜ける風船……作りが甘いポップコーンバケット……？"
"10049080-98-子供A" = "風船、つぶれちゃった……買ったばっかりなのに……。"
"10049080-99-子供B" = "うわぁーん！ポップコーンバケットの蓋……壊れちゃったぁー！"
"10049080-100-子供A" = "うわぁーん！"
"10049080-101-子供B" = "店員さん！これ！新しいのに交換してよぉー！"
"10049080-109-ラブ" = "何？縄解いてくれるの？"
"10049080-110-スズミ" = "……ヘルメット団の皆さん。"
"10049080-111-スズミ" = "私の勘違いで、ご迷惑をおかけしてすみませんでした。"
"10049080-113-ラブ" = "はぁ？ここまで邪魔しておいて、謝って済むとは思わ――"
"10049080-118-スズミ" = "本当に、申し訳ございませんでした。"
"10049080-122-ラブ" = "え、ええっ！？……ああ、そう？"
"10049080-123-ラブ" = "誰だって勘違いくらいするもんでしょ？"
"10049080-124-ラブ" = "ちゃんと謝ってもらったし。はい、終わり！"
"10049080-126-シミコ" = "誤解をしてしまい、私もすみませんでした。"
"10049080-127-レイサ" = "ど、どうやってお詫びすれば……！"
"10049080-129-ラブ" = "もういいからっ！！！"
"10049080-130-スズミ" = "……改めて、事情は分かりました。"
"10049080-131-スズミ" = "もしよければ、私たちにもお手伝いさせていただけないでしょうか？"
"10049080-132-ラブ" = "え？急にどうしたのよ。"
"10049080-133-スズミ" = "仕事を邪魔したことに対して、行動でお詫びしたいのです。"
"10049080-134-スズミ" = "……そのターゲットは正義に反していると、ラブさんは思いますか？"
"10049080-135-ラブ" = "少なくとも、良いヤツではないでしょ。うちが言うのもなんだけど。"
"10049080-136-スズミ" = "では、善良な市民に被害を与えたのも事実ですね？"
"10049080-137-ラブ" = "あんな物買わされたら、うちだって怒ると思うわよ？"
"10049080-138-スズミ" = "……分かりました。"
"10049080-139-スズミ" = "犯人がいるであろう場所に、目星はついています。"
"10049080-140-スズミ" = "ここからは、[ruby=・   ・   ・]自警団[/ruby]がお手伝いします。"
"10049080-142-レイサ" = "……！"
"10049080-143-レイサ" = "はい！"
"10049080-144-シミコ" = "図書委員会も、全力でサポートしますね！"
"10049080-146" = "[ns3] \"私も準備できたよ！\"\n[ns4] \"「シャーレの走る先生」も準備できたよ！\""
"10049080-150-ラブ" = "タダで手伝ってくれるっていうなら、断る理由はないわね。"
"10049080-151-ラブ" = "やつらの人数も分からないし。"
"10049080-155-ラブ" = "あんたら自警団と図書委員会だったの！？"
