[translation]
"10049070-1" = "第7話;スタナグちゃん頑張る"
"10049070-3-マシロ" = "35度の方向、ゆっくりと移動しています。"
"10049070-4-マシロ" = "推定相対距離は70ヤード。"
"10049070-5-マシロ" = "ターゲットの目印は黄色です。"
"10049070-7" = "[ns1] \"黄色？\"\n[ns2] \"ラブの服ってそんな色だったっけ？\""
"10049070-10-レイサ" = "う～ん……白と赤に、黒とグレーがちょっと混じった――"
"10049070-11-レイサ" = "いちご大福みたいな見た目でしたよね？"
"10049070-12-スズミ" = "それはこの目で確かめましょう。#n黄色……あの方ですね。"
"10049070-16-ジャブジャブヘルメット団A" = "隊長！またあいつらです！"
"10049070-17-ラブ" = "げっ、あんたらも懲りないわね……。"
"10049070-19-スズミ" = "……なぜそのような格好を？"
"10049070-20-ラブ" = "あんたらも大概だと思うけど！？"
"10049070-21-ラブ" = "ってか、これ知らないの……？"
"10049070-23-ジャブジャブヘルメット団B" = "おかしいですね……シリーズを間違えたかもしれません……。"
"10049070-24-レイサ" = "そ、それは……まほリバのマスコット、「スタナグちゃん」ですね！"
"10049070-25-レイサ" = "力は弱いけど、ホワイトとピンクを助ける優しい子です！"
"10049070-26-ラブ" = "ふっふっふ。その通りよ！"
"10049070-27-ラブ" = "あんたらがやってるショーの内容は調べさせてもらったわ！"
"10049070-28-ラブ" = "これでもう邪魔できないでしょ？#nまさか、仲間を攻撃したりしないわよね？"
"10049070-32-観客A" = "おっ、午後のショーが始まるみたいだよ！"
"10049070-33-観客B" = "なんか増えてない？"
"10049070-35-子供A" = "また会ったね！テルミットホワイト！ピンク！"
"10049070-36-子供B" = "スタナグちゃんもいる！"
"10049070-38-ラブ" = "これでもう、手も足も出ないでしょ？"
"10049070-39-ラブ" = "大人しく引っ込んでるのが身のためよ！"
"10049070-41-？？？" = "オーッホッホッホ！"
"10049070-42-？？？" = "ヘヴィキャリバーズと、その他の雑魚よ！"
"10049070-49-スズミ" = "この声……聞き覚えが――"
"10049070-50-レイサ" = "あるような気も……ないような気も……。"
"10049070-51" = "[ns] \"これは……？\""
"10049070-55-？？？" = "よくもまあ、好き勝手暴れてくれたわね。"
"10049070-56-ラブ" = "今度は何！？"
"10049070-58-スズミ＆レイサ" = "誰ですか！？"
"10049070-60" = "[ns3] \"あれは……！図書委員会のシミコ！\"\n[ns4] \"あれは……！悪の幹部、エラ！\""
"10049070-63-スズミ" = "シミコさん……なんですか！？"
"10049070-64-スズミ" = "今まで連絡も取れなかったのに……まさか、ここで！？"
"10049070-66-エラ" = "テルミットホワイト、テルミットピンク。それに……憎たらしいスタナグ。"
"10049070-67-エラ" = "全員同じ場所にいてくれて助かったわ。"
"10049070-68-エラ" = "この私――エラの力の前にひれ伏すがいい！"
"10049070-70-子供A" = "悪の幹部のエラだ！"
"10049070-71-子供B" = "ホワイトとピンク、勝てるかな……。"
"10049070-73-ラブ" = "悪の……幹部？"
"10049070-75-子供A" = "スタナグちゃん、今日もボコボコにされちゃうのかな……。"
"10049070-76-ラブ" = "え……？"
"10049070-77-ラブ" = "まさか……。"
"10049070-78-子供B" = "スタナグちゃん、がんばれー！"
"10049070-79-ラブ" = "冗談でしょ――"
"10049070-80-エラ" = "私の魔法と踊りなさい！"
"10049070-81-ラブ" = "どうしてこうなるのよ！！！"
