[translation]
"10000080-1" = "第8話;フィナーレまでもう少し！"
"10000080-3-イズナ" = "う、ぐうっ！"
"10000080-4-ニャテ・マサムニェ" = "啖呵を切った割には大したことないじゃないか、イズナ！"
"10000080-5" = "[s1] \"イズナ、大丈夫！？\"\n[s2] \"数が多すぎる！\""
"10000080-6-ニャテ・マサムニェ" = "くはは、街で暴れてくれていた間に、百鬼夜行の各地にいた魑魅一座にここへ戻ってくるよう伝えておいたのさ！"
"10000080-7-ニャテ・マサムニェ" = "くはは、街で暴れてくれていた間に、百鬼夜行の各地にいた魑魅一座にここへ戻ってくるよう伝えておいたのさ！"
"10000080-8-ニャテ・マサムニェ" = "さあ、この状況でも儂を裏切って、先生の方に付くつもりか？"
"10000080-9-ニャテ・マサムニェ" = "今ならまだ、水に流してやらんでもないぞ！しっかり考えたらどうだ、この愚か者め！"
"10000080-10-イズナ" = "愚かなどではありません！"
"10000080-11-イズナ" = "忍者は……イズナは……！"
"10000080-12-イズナ" = "イズナの夢を信じてくれた人のために、主殿のために戦うだけです！"
"10000080-14-イズナ" = "それこそが、イズナが信じる忍びの道だから！"
"10000080-15-ニャテ・マサムニェ" = "ふん、口だけは達者じゃないか！やれ、魑魅一座！"
"10000080-16-魑魅一座A" = "くらえ！"
"10000080-23" = "[ns] \"イズナ……っ！\""
"10000080-24-ニャテ・マサムニェ" = "ふん、本当に頑丈なやつだ。手こずらせてくれる。"
"10000080-25-イズナ" = "うっ……イズナがここで、倒れるわけ、には……。"
"10000080-26-イズナ" = "イズナは、主殿のことを、守らなきゃ……。"
"10000080-27-？？？" = "やるじゃん、忍者の子！あとは私たちに任せて！"
"10000080-28-ニャテ・マサムニェ" = "だ、誰だ！？"
"10000080-31-シズコ" = "先生！大丈夫ですか！？"
"10000080-32-フィーナ" = "お頭！お待たせしマシタ！"
"10000080-40-ニャテ・マサムニェ" = "お祭り運営委員会、それに修行部のやつらまで……！"
"10000080-41-シズコ" = "やっぱり、犯人はあなただったんですね！会長……いえ、ニャン天丸！"
"10000080-42-ニャテ・マサムニェ" = "ニャン天丸じゃない、マサムニェだ！"
"10000080-43-ニャテ・マサムニェ" = "それにしてもどうしてここに……！"
"10000080-44-ニャテ・マサムニェ" = "魑魅一座が誘拐してきた後、すぐに連絡手段は絶ったはず……！？"
"10000080-45-シズコ" = "これのおかげです！"
"10000080-47" = "（スッ）"
"10000080-48-ニャテ・マサムニェ" = "スマホ……？だから連絡手段は……いや、まさか！？"
"10000080-49-シズコ" = "先生があらかじめ、私にモモトークを送ってくれていましたから！"
"10000080-50-シズコ" = "「今から誘拐される予定だから、遅くなる前に助けに来てほしい」って！"
"10000080-52-ニャテ・マサムニェ" = "ぐっ、ここに来る前の段階で、すでに送っていただと……！？"
"10000080-54-ニャテ・マサムニェ" = "ということは……先生、おぬし攫われたのではなく、全部最初から分かってて……！"
"10000080-55" = "[s] 口笛を吹く。"
"10000080-56-ニャテ・マサムニェ" = "やはり侮れないやつめ……！それにしても……「やっぱり」、と言ったな。つまりは、儂の正体にも薄々気づいていたということか……！"
"10000080-57-ニャテ・マサムニェ" = "やるではないか。儂が魑魅一座を束ねているという真実にたどり着くまで、さぞかし多くの困難があっただろう……。"
"10000080-58-ニャテ・マサムニェ" = "お祭り運営委員会の委員長、[ruby=かわわ]河和[/ruby]シズコよ！"
"10000080-59-シズコ" = "え？いや、別に。"
"10000080-60-フィーナ" = "桜花祭に来ていた人たちに、怪しい人を見なかったか聞いてみたんデス！"
"10000080-61-シズコ" = "そしたら結構な人数が、会長と魑魅一座がこの商店街の裏路地を通って廃墟に入って行くのを見たと言ってたので、そりゃもうあっさりと。"
"10000080-62-ツバキ" = "そもそも魑魅一座も会長も、すごく目立つし……ふあぁ……。"
"10000080-63-ニャテ・マサムニェ" = "ぐぅっ、会長という役職が、裏目に出るとは……！"
"10000080-64-ニャテ・マサムニェ" = "ええいっ！もういい、この状況も計画の範疇だ！"
"10000080-65-ニャテ・マサムニェ" = "最初からおぬしらがここにたどり着く可能性くらい、予測してなかったとでも思うか！"
"10000080-66-ニャテ・マサムニェ" = "良いものを見せてやろう！"
"10000080-73-カエデ" = "うわわわっ！何これ！？"
"10000080-74-ツバキ" = "どんどん増えるね～。"
"10000080-75-ミモリ" = "なんだか、尋常ではない雰囲気になってきましたね。"
"10000080-77-シズコ" = "……うわあ。"
"10000080-82-フィーナ" = "フィーナ、『仁義なきニャンニャンパンチ』でこういうシーンも見たことありマス！"
"10000080-83-フィーナ" = "組織の全員を集めて、襲撃に向かおうとするところデシタ！"
"10000080-84-ニャテ・マサムニェ" = "正にその通りだ。魑魅一座をここに集めておいたのは、おぬしらを一網打尽にするためでもあったのさ。"
"10000080-85-ニャテ・マサムニェ" = "さあ、実は自分たちが罠にはめられていたと気づいた時の心地はどうだ！"
"10000080-86-ニャテ・マサムニェ" = "ふはは、覚悟しろ！"
"10000080-87-シズコ" = "うーん……どう考えても負けフラグな台詞。"
"10000080-88-フィーナ" = "サスガ委員長！いつも通り辛辣デス！"
"10000080-89-ツバキ" = "ふあぁ、とにかく荒らすのをやめるつもりがないなら～……"
"10000080-90-カエデ" = "素敵なレディーになるためにも！私たち修行部も相手するよ！"
"10000080-92-ミモリ" = "皆さん、行きましょう！"
