[translation]
"10042040-1" = "第4話;リリー・マルレーン"
"10042040-2" = "ゲヘナ学園・風紀委員会の教室"
"10042040-3-アコ" = "……。"
"10042040-4" = "[s1] \"えっと……。\"\n[s2] \"もう一度説明しようか？\""
"10042040-7-アコ" = "いえ、何度聞いたところで変わらないと思いますし。"
"10042040-8-アコ" = "この状況――つまり、風紀委員会の緊急連絡網を使ってまで呼び出したのは……。"
"10042040-9-アコ" = "……「家出したパンケーキ」のためなんですね？"
"10042040-10" = "[s] \"う、うん……。\""
"10042040-11-アコ" = "あの……私、三徹目の真っ最中なのですけど。"
"10042040-15-チナツ" = "行政官が多忙なのは知っています。#n私たちが出動したせいで余計に負担を増やしてしまっているのも……。"
"10042040-16-アコ" = "いえ、チナツを悪く言いたいわけでは……。"
"10042040-20-アコ" = "……はぁ。"
"10042040-21-アコ" = "誤解があったようですね。#n行政官として、やるべき仕事はやりますよ……。"
"10042040-22-アコ" = "ただ……この程度の事案、ゲヘナ中で起きているかと。"
"10042040-23-アコ" = "なので……そちらで処理してください。"
"10042040-24-アコ" = "……ちょうど先生も一緒にいるのでしょう？"
"10042040-25" = "[s3] \"たしかに、そうなんだけど……。\"\n[s4] \"状況が状況で……ちょっとアコにも見てほしいんだ。\""
"10042040-28-アコ" = "はぁ……？"
"10042040-29-アコ" = "なんだか拍子抜けしますね。#nなにか悪いものでも食べました？"
"10042040-30-アコ" = "いつもなら、「私に任せて！」とか仰るはずなのに……。"
"10042040-34-アコ" = "あぁ、もう！#n気になってしまうじゃないですか！"
"10042040-35-アコ" = "これ、ドッキリとかじゃないですよね？"
"10042040-36-アコ" = "私を驚かせるために一計を案じたとかじゃないんですよね！？"
"10042040-37" = "[s5] \"私がそんなことすると思う……？\"\n[s6] \"本当に大変な状況になってるんだ……。\""
"10042040-40-アコ" = "だから……！"
"10042040-44-アコ" = "……はぁ。"
"10042040-45-アコ" = "分かりました、分かりましたから。#n少し深呼吸させてください……。"
"10042040-46-アコ" = "今、神経質になっているのは……少し眠れていないからなので。"
"10042040-47-アコ" = "……より正確に言えば、そんな状況で誰かさんが「この程度の事案で緊急連絡をしてきたから」ですが。"
"10042040-48" = "[s7] \"本当にごめん。今度、美味しいスイーツでも奢るよ。\"\n[s8] \"うぅ、ひどいよ！あんまりだ！\""
"10042040-49-アコ" = "……なるほど。"
"10042040-50-アコ" = "つまり、エスコートしてくださる、と？"
"10042040-51-アコ" = "人のこと言えた立場ですか……。"
"10042040-52-アコ" = "とにかく、詳しい話は後で聞きますから！#nちゃんと時間を空けておいてくださいね！？"
"10042040-53" = "[s] \"セナが撮ってくれた証拠があるんだ。\""
"10042040-54-アコ" = "……ほう？"
"10042040-55-アコ" = "こちらで確認します。すぐ送ってください。"
"10042040-60-アコ" = "……コラ画像か何かです？"
"10042040-64-セナ" = "私がそのようなことをするとでも？"
"10042040-65-アコ" = "……いえ、失礼しました。#n少し驚きまして。"
"10042040-66-アコ" = "なるほど……そうですね。"
"10042040-67-アコ" = "先生はさておき……救急医学部長がそう仰るのであれば信用します。"
"10042040-68-アコ" = "いえ、むしろせざるを得ないというか……。"
"10042040-69" = "[s] \"……あんまりだ。\""
"10042040-70-アコ" = "あぁ、もう！#nまったく信用してないわけではありませんから！"
"10042040-71-アコ" = "とにかく、分かりました。"
"10042040-72-アコ" = "この証拠をもとに、こちら側も可能な限り協力いたします。#n後ほど私も現場へ向かいますので。"
"10042040-73-アコ" = "もし、本当にドッキリだったら……。"
"10042040-74-アコ" = "少なくとも、2日は風紀委員会に……いえ、私に付き合ってもらいますからね！"
"10042040-75-チナツ" = "……一体先生をどうするつもりですか？"
"10042040-76-アコ" = "まあ、終わってから話しましょう。"
"10042040-77-アコ" = "それ相応の対価を支払ってもらいます。"
"10042040-78" = "[s9] \"それ相応……？\"\n[s10] \"アコ……？\""
"10042040-81-アコ" = "それでは、準備がありますので。"
"10042040-82-アコ" = "……万全を期して臨まなくては。"
"10042040-83-チナツ" = "行政官……？"
"10042040-84-チナツ" = "アコ行政――"
"10042040-91-アコ" = "待機中の全風紀委員に命じます。"
"10042040-92-アコ" = "使用可能な88ミリFlaK36の対空砲をあるだけ用意してください！"
"10042040-93-風紀委員" = "対空砲、ですか？"
"10042040-94-アコ" = "はい、使えるアハト・アハトを全て！"
"10042040-95-風紀委員" = "そんなに大掛かりな事をするんですか……？"
"10042040-96-風紀委員" = "今朝までそんな話一切なかったのに……。"
"10042040-97-アコ" = "先生――シャーレの要請です。#nこれでご理解いただけたでしょうか。"
"10042040-98-風紀委員" = "せ、先生から！？"
"10042040-99-風紀委員" = "分かりました。すぐにご用意します！"
"10042040-103-アコ" = "……緊急連絡網を使うほどの事態。"
"10042040-104-アコ" = "それ相応の火力を用意して差し上げましょう。"
"10042040-105-アコ" = "ふふ……ここまで動かしたのです。高くつきますよ？"
"10042040-106-アコ" = "あとできっちりと返してもらいますからね！"
"10042040-108" = "ゲヘナ自治区通り"
"10042040-109" = "[ns] \"いったいどんな準備をするつもりなんだろう……。\""
"10042040-110-チナツ" = "おおかたの予想はついています。"
"10042040-111-チナツ" = "万全を期して、と言っていたので……おそらく88ミリ砲を持ってくるかと。"
"10042040-112-チナツ" = "ビルが壁として作用するこの地形において、あれがどれほど効力を発揮できるかは疑問ですが。"
"10042040-113-チナツ" = "ターゲットが建物間を素早く移動でもしたら、正確に狙うのは難しくなります。"
"10042040-114-チナツ" = "……もしもの時は、建物ごと撃つ可能性も。"
"10042040-115" = "[s] \"それってマズいんじゃない！？\""
"10042040-116-チナツ" = "どうでしょう、他の学園ならともかく。"
"10042040-117-チナツ" = "ゲヘナでは、ほぼ日常的に建物が倒壊していますから。"
"10042040-118-チナツ" = "ただ[ruby=パンデモニウム・ソサエティー]……万魔殿がど[/ruby]う出るかが気になるところです。"
"10042040-119" = "[s] \"……。\""
"10042040-120-チナツ" = "この件で何かしらの損害が発生した場合――"
"10042040-121-チナツ" = "マコト議長から一体どんな難癖をつけられるか、分かったものではありません。"
"10042040-122-チナツ" = "普段のアコ行政官なら、想定の上で対策しているでしょうが……。"
"10042040-123-チナツ" = "今は寝不足でまともな判断ができない可能性があります……。"
"10042040-124-ジュリ" = "すみません。#n私のせいで、皆さんにご迷惑を……。"
"10042040-125-セナ" = "……ご自身を責める必要はありません。#n事情が事情なのですから。"
"10042040-126-セナ" = "それに……。"
"10042040-127-セナ" = "どちらに転ぼうと、救急医学部に搬送される死体――"
"10042040-128-セナ" = "……いえ、負傷者が少し増えるだけに過ぎません。"
"10042040-129-フウカ" = "そ、それでいいの！？"
"10042040-130-セナ" = "愚問です。この程度の騒動、日常茶飯事ですから。"
"10042040-131-セナ" = "救急医学部のキャパを超えることはありません。"
"10042040-132-チナツ" = "部長が仰ることは分かりますが、それでは私たちの立場が……。"
"10042040-133-セナ" = "……失礼しました。"
"10042040-139-チナツ" = "先生、アコ行政官から連絡がありました。"
"10042040-140-チナツ" = "パンケーキの行方を追跡するように、と。"
"10042040-141-セナ" = "追跡なら、先ほどまでと変わりませんね。"
"10042040-142-セナ" = "では、行きましょう。"
