[translation]
"10008035-3-ヘルメット団A" = "ぐあぁぁっ……！？"
"10008035-4-ヘルメット団B" = "わ、我々の偉大な夢が、今年の初夢が……。"
"10008035-10-アル" = "ふう、しょうもないやつらね。"
"10008035-11-カヨコ" = "（……どうしてヘルメット団が賽銭箱を？それより、カイテンジャーの逃走ルートをどうやって……？）"
"10008035-12-カヨコ" = "（もしかしてこれ、思ったより複雑な……）"
"10008035-13-ムツキ" = "っていうか、早く追いかけた方が良くない？こうしてる間にもどんどん逃げられちゃうけど。"
"10008035-14-アル" = "そ、そうね！？"
"10008035-15-アル" = "ほら、早く行くわよ！"
"10008035-17-ハルカ" = "は、はいっ！"
