[translation]
"10008090-1" = "第9話;対策委員会、集結！"
"10008090-3-黒亀組の組員A" = "こ、こいつら、めちゃくちゃ強い……！？"
"10008090-4-ホシノ" = "うへ～、まあおじさんもこういう時はちょっとくらいね～？"
"10008090-5-黒亀組の組員B" = "ぐ、これでは足りない……！支援を要請する！"
"10008090-13-アル" = "これじゃあキリがないわよ……！？"
"10008090-15-？？？" = "大勢で寄ってたかってなんて、ズルいですねー。"
"10008090-17-アル" = "……！"
"10008090-25-黒亀組の組員たち" = "があっ！？"
"10008090-29" = "[ns] \"ガトリング砲ってことは……！\""
"10008090-32-セリカ" = "ノノミ先輩まで！"
"10008090-33-ノノミ" = "お待たせしましたセリカちゃん！それに先生、あけましておめでとうございます☆"
"10008090-34-セリカ" = "っていうことはもしかして……。"
"10008090-39-シロコ" = "セリカ、お待たせ。"
"10008090-40-セリカ" = "シロコ先輩！"
"10008090-42-アル" = "ど、どうしてここにあなたたちが……！？"
"10008090-43-ホシノ" = "それにしても、便利屋のみんながセリカちゃんと一緒だなんてねぇ。"
"10008090-44-ホシノ" = "その上先生まで。意外な組み合わせで、おじさんもびっくりだよ。あ、そういえばあけましておめでと～。"
"10008090-45" = "[s] \"あけましておめでとう……ってそれより、どうしてここが……？\""
"10008090-47-シロコ" = "セリカから連絡があったから。"
"10008090-48-セリカ" = "連絡、って……"
"10008090-49-セリカ" = "あっ！"
"10008090-52-セリカ" = "こうなったら、協力を要請して……！"
"10008090-58-カヨコ" = "ああ、メッセージ送ったって言ってたね。"
"10008090-59-ノノミ" = "用件とかは書かれてなかったんですけどね☆ちょうどセリカちゃんのバイト先が生中継で映ってたので、これはもしかして？と思いまして。"
"10008090-60-ホシノ" = "うん、巻き込まれてたら困るなぁって思ってさ～。"
"10008090-61-シロコ" = "セリカ、こういうのに巻き込まれがちなイメージだし。"
"10008090-63-セリカ" = "そ、そうなの！？"
"10008090-69-アル" = "全てが書かれていなくても、仲間を助けるために飛び出すだなんて……。"
"10008090-70-ムツキ" = "アルちゃん、すっごい感激してるじゃーん♪"
"10008090-71-アル" = "べ、別にそういうのじゃないわよ！？"
"10008090-73-シロコ" = "それに、賽銭箱の中身は早い者勝ちって聞いて。"
"10008090-80-セリカ" = "何で今それ持ってるの！？"
"10008090-81-シロコ" = "ちゃんと準備してきた。"
"10008090-82" = "[s] \"あっ、でもその件についてはその……。\""
"10008090-83-セリカ" = "シロコ先輩、その賽銭箱なんだけど……"
"10008090-84-アル" = "全部嘘だったわよ。"
"10008090-85-シロコ" = "……嘘？"
"10008090-88-ホシノ" = "なるほどね～。今回の騒ぎの主犯はカイテンジャーじゃなくって、黒亀組だったってことかー。"
"10008090-89-ホシノ" = "いやぁ、それは災難だったねぇ。大人の悪意は困ったもんだー。"
"10008090-90-ノノミ" = "そういうことだったんですか……みんなを騙してお金を奪おうだなんて、許せません！"
"10008090-91-ノノミ" = "ですよね、シロコちゃん！"
"10008090-95-シロコ" = "全部、嘘……。"
"10008090-96" = "[s] \"シロコ、大丈夫……？\""
"10008090-97-ホシノ" = "シロコちゃん、すっごい期待してたもんね～。"
"10008090-98-シロコ" = "最初から騙してたなんて、許せない。"
"10008090-100-アル" = "そうよ、許してはおけないわ。だからその大吉殿の管理人とやらに、今からでも一発食らわせてやらないと。"
"10008090-101-アル" = "そういうことで……"
"10008090-102-アル" = "手伝ってくれない？"
"10008090-103-ムツキ" = "あはっ、ここでもう一回共同戦線？"
"10008090-104-アル" = "ええ、相手は雑魚だけれど数が多い。私たちだけでは厳しいわ。"
"10008090-106-ホシノ" = "まあ、特に断る理由は無いかな？"
"10008090-107-ノノミ" = "はい！セリカちゃんと、落ち込んでしまったシロコちゃんのためにも！"
"10008090-113-シロコ" = "……別に落ち込んでない。"
"10008090-114-ホシノ" = "まあまあ、実際にやるのはダメだけど気持ちは分かるよ。"
"10008090-115-ホシノ" = "その分もやり返しに行こ、ね？おじさんも手伝うからさ？"
"10008090-117-アル" = "よし、そうと決まれば……！"
"10008090-125-アヤネ" = "みなさん無事ですか！？"
"10008090-126-アヤネ" = "すみません、何だか接続が不安定で……！あ、先生あけましておめでとうございます！"
"10008090-127-セリカ" = "アヤネちゃん……！って、何でアヤネちゃんまで覆面なの！？"
"10008090-128-アヤネ" = "こ、これはシロコ先輩が必要だからって……！"
"10008090-129-シロコ" = "もう要らなくなった。"
"10008090-130-アヤネ" = "そ、そうなんですか……？"
"10008090-132-ムツキ" = "あはははっ、メガネっ娘ちゃんまで！面白くなってきたねー！"
"10008090-133-ムツキ" = "さーて、じゃあもう一つ仕込んでおこっかな？"
"10008090-134" = "[s] \"ムツキ？\""
"10008090-135-ムツキ" = "全員で力を合わせて反撃！っていうのも勿論悪くないけどー。"
"10008090-141-ムツキ" = "せっかくだし、もうちょっと面白くしようかな～って♪"
"10008090-145-ムツキ" = "送信完了～！"
"10008090-146-カヨコ" = "ムツキ、今のってもしかして……。"
"10008090-147-ムツキ" = "こんな楽しいドタバタ劇、私たちだけで楽しむのはもったいないでしょ？"
"10008090-148-ムツキ" = "だからもっと面白くするためにも、ね？"
"10008090-149-黒亀組の組員たち" = "いたぞ、やつらをここで制圧しろ！"
"10008090-158-ムツキ" = "くふふっ♪さーて、じゃあお祭りを始めよっか？"
"10008090-159-ムツキ" = "ね、先生♡"
