[translation]
"10008125-3-カイテンイエロー" = "ははははははっ！やはりダメだったか！"
"10008125-4-カイテンレッド" = "うむ！まだ機体の調整が足りなかったな！"
"10008125-5-カイテンブラック" = "レッド！次は性能と出力をもっと変えよう！"
"10008125-10-カイテンピンク" = "……毎回思うんだけど、もしかして一生懸命なの私だけ？何かいっつもふざけてない？ねえ？"
"10008125-11-カイテングリーン" = "ところでレッド。そろそろ契約期間が終わりますが、延長しますか？"
"10008125-12-カイテンレッド" = "おっと困った！その金はもうMk.1に使ってしまったな、どうしたものか！"
"10008125-13-カイテンレッド" = "まあとにかくこの場は、撤退するとしよう！"
"10008125-14-カイテンレッド" = "しかしこれで終わりではないぞ！我々の戦いは、まだまだ続くのだからな！"
"10008125-16-カイテンレッド" = "回り続けるレールはやがて……正義の未来へと繋がる！"
"10008125-17-カイテンレッド" = "無限回転寿司戦隊・カイテンジャー、退場っ！"
"10008125-23-アル" = "これって、結局……"
"10008125-24-アル" = "わ、私たちのお金は、全部吹き飛んだってこと！？嘘でしょぉぉぉっ！？"
"10008125-25-ハルカ" = "あ、アル様！わ、私は大丈夫ですので！お金でしたら、また稼ぎますので！"
"10008125-26-カヨコ" = "はぁ、全く……。"
"10008125-28-ムツキ" = "あはっ！やっぱり最後はこんな感じだったね！"
"10008125-29-セリカ" = "……私、もう帰って良い？"
"10008125-30" = "[s] \"えっと……お疲れ様。\""
"10008125-32" = "（新年初日の大騒ぎは、こうして幕を閉じた）"
