[translation]
"221130-1" = "第13話;最後の航海"
"221130-2-マイ" = "クロノスチャンネルをご覧の皆さん、おはようございます！#nクロノス報道部の[ruby=かざまき]風巻[/ruby]マイです！"
"221130-3-マイ" = "未だ日も昇らぬ時間ですが、私は今、#nオデュッセイアの船団が停泊中のアオハマ港に来ています！"
"221130-4-マイ" = "クロノス報道部が極秘で入手した情報によると、#nオデュッセイアの生徒会――アイランドが単独で出航を準備しているとのことです！"
"221130-5-マイ" = "それを証明するかのように、旗艦オリュンポス号は[ruby=げんもん]舷門[/ruby]を撤去し[ruby=いかり]、錨を[/ruby]上げています！"
"221130-6-マイ" = "定期航海を終えたオデュッセイアの船団が、#nひと月も経たずに再び出航するのは前例がありません！"
"221130-7-マイ" = "SNSでは出航の理由をめぐって様々な憶測が飛んでいる模様です。"
"221130-8-マイ" = "先日オデュッセイアを特別訪問したシャーレの先生および連邦生徒会長と関係があるのでしょうか？"
"221130-9-マイ" = "まだ正式発表は出ていませんが、新しい情報が入り次第――"
"221130-10-クロノス報道部の生徒" = "先輩、速報です。"
"221130-11-マイ" = "あっ、ただいま速報が入りました！"
"221130-12-マイ" = "先ほど、オリュンポス号が港湾管理局に出航理由を通知したとのことです。"
"221130-13-マイ" = "出航の目的は「友を見送るため」とのことですが――"
"221130-14-マイ" = "うん？見送るって、どういう意味です？"
"221130-15-マイ" = "誰か、海に出る生徒でもいるんでしょうか……？"
"221130-16" = "アイランド旗艦「オリュンポス号」・第1艦橋"
"221130-17-オデュッセイアの生徒A" = "出航5分前！"
"221130-18-アミ" = "これより出航態勢に入る。#n艦内放送を舷門から艦橋へ切り替えて。"
"221130-19-オデュッセイアの生徒B" = "舷門、撤去完了しました！"
"221130-20" = "よし。総員、係留索回収。"
"221130-21-オデュッセイアの生徒A" = "総員、係留索回収！"
"221130-22-オデュッセイアの生徒A" = "出航！"
"221130-23-ミナト" = "やっぱり、防波堤を越えるだけでも海の色が変わるね。"
"221130-24-サミー" = "……にゃあ。"
"221130-25-ミナト" = "サミー、見える？"
"221130-26-ミナト" = "海だよ。君がずっと眺めていたキヴォトスの海。"
"221130-27-ミナト" = "今日は他の船がいないから、いつもとはちょっと違うけど……。"
"221130-28-ミナト" = "せめてもの贈り物だ。"
"221130-29-サミー" = "…………にゃぁ。"
"221130-30-ミナト" = "どうしたの？舷側の窓を開けたい？"
"221130-31-ミナト" = "あっちには何もないけ――"
"221130-32-ミナト" = "あれ？あの船は……。"
"221130-33-アミ" = "艦長、クルーズ運営部のゴールデンエリジウムから通信要請です！"
"221130-34-ミナト" = "許可する。"
"221130-35-アミ" = "……通信要請、許可。6番チャンネルへ接続します。"
"221130-36-ミツキ" = "こちらゴールデンエリジウム。#nクルーズ運営部部長、[ruby=せんごく]千石[/ruby]ミツキでございます。"
"221130-37-ミツキ" = "お話は聞かせてもらいました。#nサミーへ手向けを贈ろうとしているのですね？"
"221130-38-ミツキ" = "であれば、私たちもお供します。"
"221130-39-ミツキ" = "黄金色に輝くこの船が隣にいないと、サミーも寂しがるでしょう？"
"221130-40-ミツキ" = "つきましては……事後承諾となりますが、クルーズ運営部の出航許可を願います。"
"221130-41-ミナト" = "でも……クルーズ運営部はD.U.に戻ってこっちも営業中だったよね？"
"221130-42-ミナト" = "ゲストのスケジュールを確認せずに出航していいの？"
"221130-43-ミツキ" = "ちょっとだけです。#nそれに、サプライズならお客様も喜ばれるでしょうから。"
"221130-44-ミツキ" = "1件のクレームも出ないことにクルーズ運営部の今月分の部費を賭けます！"
"221130-45-ミナト" = "……許可する。"
"221130-46-アミ" = "艦長、続いてロードス号からも通信要請です。"
"221130-47-アミ" = "……8番チャンネルへ切り替えます。"
"221130-48-スミカ" = "こちらロードス！#nトライデントの通信当番、[ruby=こもり]小森[/ruby]スミカです！"
"221130-49-スミカ" = "勝手に割り込んですみません。#nトライデントからも、どうしてもお伝えしたいことがありまして……！"
"221130-50-トライデントの部員A" = "ひどいですよ艦長！サミーを見送るのに置いてくなんて！"
"221130-51-トライデントの部員B" = "私たちもオデュッセイアです！白と黒両方の制服が揃わなかったら、サミーが寂しがります！"
"221130-52-トライデントの部員B" = "今回の航海の安全も、トライデントにお任せください！"
"221130-53-スミカ" = "ちょ、ちょっと！みんな落ち着いてくださ～い！#n今日の通信当番は私なんですよ！？"
"221130-54-スミカ" = "えっと……艦長、ロードス号を含むトライデント巡視船にも出航許可をお願いします！"
"221130-55-ミナト" = "うん、一緒に行こう。"
"221130-56-アミ" = "……その他、複数の部活から続々と出航許可願が届いています。"
"221130-57-アミ" = "これで、サミーに[ruby=海]日常の風景[/ruby]を見せてあげられますね。"
"221130-58-ミナト" = "うん、よかった。"
"221130-59-ミナト" = "サミー、見える？#n君が愛する――君を愛する学園のみんなが。"
"221130-60-サミー" = "……にゃあ。"
"221130-61-ミナト" = "君の特等席はあっちだよね？行こう。"
"221130-62-ミナト" = "……海風だ。"
"221130-63-ミナト" = "朝日が昇り、気温が上がれば、君はここで風と共に学園を眺めてたよね。"
"221130-64-ミナト" = "どうかな、サミー。私たちのオデュッセイアは。"
"221130-65-サミー" = "…………。"
"221130-66" = "（その瞳に映るのは、船乗りの仲間たち）"
"221130-67" = "（サミーはいつもの場所で、見慣れた風景を眺めながら、友に囲まれて――）"
"221130-68" = "（――満ち足りた表情で、静かに目を閉じた）"
"221130-69" = "（……こうして、サミーの航海は幕を下ろした）"
"221130-70" = "次回;空席の存在感"
