[translation]
"10038090-1" = "第9話;すべての面倒事を"
"10038090-16-山海経の看守A" = "げ、玄龍門！それに門主様まで！？"
"10038090-17-山海経の看守B" = "どうしてこちらに……？"
"10038090-19-キサキ" = "[ruby=やくし]薬子[/ruby]サヤの釈放に来た。"
"10038090-21-山海経の看守A" = "さ、サヤ、とは……元錬丹術研究会長の？"
"10038090-22-山海経の看守B" = "それは、少し……！"
"10038090-24-キサキ" = "ほう。何か問題でもあるのかのう？"
"10038090-29-山海経の看守A" = "……。"
"10038090-30-山海経の看守B" = "その……錬丹術研究会から、強い要請がありまして……#n薬子サヤの身柄を、できるだけ長く拘束しておくように、と……"
"10038090-31-山海経の看守A" = "罪状は……錬丹術研究会の運営を放棄した罪、だと聞いております……"
"10038090-33-キサキ" = "ふむ。して、其方らは錬丹術研究会の要請が、門主の命より上にある、と？"
"10038090-34-ミナ" = "ふっ。門主様の命に従わないのであれば、処分が下っても文句は言えないぞ？"
"10038090-35-キサキ" = "ミナ、あまり脅すでない。執行部長である其方が言うと、言葉の重さが変わるであろう。"
"10038090-39-ミナ" = "し、失礼しました。門主様！"
"10038090-45-山海経の看守A" = "……門主様、どうかご理解を。"
"10038090-47-キサキ" = "聞こう。話すがよい。"
"10038090-49-山海経の看守A" = "その……山海経で流行っている、若返り現象に関して、です。"
"10038090-50-山海経の看守B" = "例の現象を生み出したのが……門主様もお察しの通り、例の人で……。"
"10038090-52-山海経の看守A" = "ですから……我々としても……その……。"
"10038090-57-山海経の看守B" = "錬丹術研究会が門主様の命より上にないことは承知しておりますが……。"
"10038090-58-山海経の看守A" = "従わなければ、薬を提供してもらえなくなってしまうのです……。"
"10038090-60-キサキ" = "……ふむ。"
"10038090-61-キサキ" = "あい分かった。であれば、これより玄龍門の名に於いて――薬子サヤの釈放を執行する。"
"10038090-66-山海経の看守A" = "え？ということは……！？"
"10038090-67-山海経の看守B" = "すべての責任を……！？"
"10038090-69-キサキ" = "ああ。すべての責任は玄龍門――ひいては門主である[ruby=りゅうげ]竜華[/ruby]キサキが負うこととする。"
"10038090-73-キサキ" = "門主とは本来、あれこれ面倒事を背負うために存在するものじゃからのう。"
