[translation]
"3301-1" = "全力で振り抜いて（１）"
"3301-3-ロボット審判" = "〈――プレイボール！〉"
"3301-5-ミレニアム野球部長" = "みんな、集まって！"
"3301-6-ミレニアム野球部長" = "今回は練習試合だから、緊張しなくても大丈夫。"
"3301-7-ミレニアム野球部長" = "対戦相手はエンジニア部が作ってくれたロボットだし……#nデッドボールを当ててしまってブーイングされる心配も無いからね。"
"3301-12-ミレニアム野球部員A" = "でも、エンジニア部のロボットってことは、別の危険があるんじゃ……？"
"3301-13-ミレニアム野球部員A" = "あのピッチングロボット、前にエンジニア部の人がテストしたとき、あり得ない剛速球を何度も投げたって……"
"3301-14-ミレニアム野球部員B" = "しかも、ボールを投げる前に挑発してくるんですよ！"
"3301-15-ミレニアム野球部長" = "たしかに前はそうだったかもしれないけど……"
"3301-16-ミレニアム野球部長" = "あれからセミナーが改善するよう言ったらしいから、今回は大丈夫なはず。"
"3301-17-ミレニアム野球部長" = "みんな、楽しんでいこう！"
"3301-27-ロボット審判" = "〈ストライクアウト！〉"
"3301-30-ミレニアム野球部員A" = "うぅ……こんなの当たりっこないよ。"
"3301-36-ミレニアム野球部員B" = "やっぱり、あんなに速かったら……"
"3301-45-ロボット審判" = "〈……4番、[ruby=のまさ]野正[/ruby]レイさん〉"
"3301-46-ミレニアム野球部員A" = "あの子……新入部員のレイちゃんだよね？"
"3301-47-ミレニアム野球部員B" = "らしいよ。なんと入部テストで打率0割8分を記録した期待の新人だって……"
"3301-48-ミレニアム野球部員A" = "そんな好記録を！？"
"3301-49-レイ" = "いやぁ～、先輩方にそうやって褒められたら照れちゃいますね。えへへ……"
"3301-50-ミレニアム野球部員A" = "レイちゃん、前！！"
"3301-54-ロボット審判" = "〈ピッチャー、大きく振りかぶって――〉"
"3301-55-レイ" = "来るっ……！"
"3301-67-ミレニアム野球部員A" = "打った――！"
"3301-68-ミレニアム野球部員B" = "あの剛速球を打ち返すなんて！？"
"3301-69-ミレニアム野球部員A" = "もしかして、行ったんじゃない……！？"
"3301-70-ミレニアム野球部員A" = "これでミレニアムも、ようやく今シーズン初のホームランを……"
"3301-74-ロボット審判" = "〈……アウト！〉"
"3301-76-レイ" = "はぁ…………"
"3301-77-ロボット審判" = "〈スリーアウト、チェンジ！〉"
"3301-80-ミレニアム野球部長" = "……みんな、お疲れ！"
"3301-82-一同" = "お疲れ様でした！"
"3301-83-ミレニアム野球部員A" = "レイちゃん、お疲れ！すごい活躍だったね！"
"3301-84-レイ" = "いえ、先輩もお疲れ様でした！"
"3301-85-ミレニアム野球部員A" = "本当に惜しかったね。#nあと少しでホームランだったのに……"
"3301-86-ミレニアム野球部員B" = "だよね！音を聞いた瞬間、これは越えるって思ったくらい！"
"3301-87-レイ" = "その、水を差すようで申し訳ないのですが……"
"3301-88-レイ" = "ボールが当たった瞬間、これは届かないなって思ったんです。"
"3301-89-ミレニアム野球部員A" = "……感覚で？"
"3301-90-レイ" = "まだホームランを打った経験は無いので、感覚というのも少し違うかもしれませんが……"
"3301-91-レイ" = "……芯を捉えた感触が無かったと言いますか……"
"3301-92-ミレニアム野球部員A" = "そうだったんだ？"
"3301-93-レイ" = "で、でも、次の試合もありますから。"
"3301-94-レイ" = "……それで相談なんですが、ホームランを打つためには、何をすれば良いと思いますか？"
"3301-99-ミレニアム野球部員A" = "……やっぱりバットをボールに当てる角度じゃないのかな？"
"3301-100-ミレニアム野球部員A" = "飛んでいくボールは垂直方向に等加速度運動を、水平方向には等速直線運動をするわけで、45度方向のときに最も飛距離が伸びるから……"
"3301-101-ミレニアム野球部員B" = "って、それは重力の影響だけを考えた真空下における方程式じゃん。"
"3301-102-ミレニアム野球部員B" = "物体に作用する力を正確に計算するには、抗力と揚力……#nそれにモーメントも考慮する必要があるよ。"
"3301-107-ミレニアム野球部員C" = "バットの材質も大事！#n軽くて反発力が高いほどいいに決まってる！"
"3301-108-ミレニアム野球部員C" = "新素材開発部が新しく作ったバットの研究結果によると、既存の素材よりも飛距離が――"
"3301-109-ミレニアム野球部員D" = "ここは効率的なバッティングフォームを――"
"3301-116-レイ" = "やはり、ホームランを打つためには……"
"3301-117-レイ" = "もっと筋肉をつける必要があるんじゃないかな、とも思ったんですが……"
"3301-121-ミレニアム野球部員A" = "き、筋トレを……？"
"3301-122-ミレニアム野球部員B" = "でも、運動は大変だし……"
"3301-127-ミレニアム野球部員C" = "そもそも、ミレニアム野球部は道具の改良とデータを重視する理論派集団の集まりで……"
"3301-128-ミレニアム野球部員D" = "……ホームランは打てなくても、安打で得点を稼げばいいんじゃないかな？"
"3301-129-レイ" = "もちろん、チームで勝つなら安打の方が大切かもしれません……"
"3301-134-レイ" = "でも、やっぱりホームランを打ちたいんです！"
"3301-138-ミレニアム野球部長" = "ごめんね、レイちゃん。ウチの野球部、トレーニングに詳しい人居ないんだ。"
"3301-139-ミレニアム野球部長" = "私も理論なら教えられるんだけど、トレーニングは苦手で……"
"3301-140-レイ" = "そう、ですか……"
"3301-141-ミレニアム野球部長" = "代わりに、専門家の紹介ならできるよ。"
"3301-142-ミレニアム野球部長" = "……トレーニング部って聞いたことある？"
"3301-143-レイ" = "トレーニング部、ですか……？"
"3301-145" = "ミレニアム・ジム"
"3301-148-スミレ" = "……遅いですね、会員の皆さん。"
"3301-149-スミレ" = "これでは、昨日せっかく鍛えた筋肉が……"
"3301-154-スミレ" = "……やはり、昨日のトレーニングが[ruby=こた]堪[/ruby]えてしまったのでしょうか。"
"3301-155-スミレ" = "部員が増える気配もありませんし、会員の数も……"
"3301-156-スミレ" = "こうなったら直接、新入部員を探しに――"
"3301-163-レイ" = "失礼します、トレーニング部はここですか？"
"3301-164-スミレ" = "そうですが……"
"3301-165-レイ" = "あ、自分は野球部の野正レイって言います！"
"3301-166-レイ" = "その、部長からトレーニングの方法が知りたかったら、ここに行くよう言われて……"
"3301-167-スミレ" = "そうでしたか、トレーニングに来たんですね。"
"3301-168-レイ" = "はい。ここなら、ホームランを打つための筋肉が鍛えられると聞きました！"
"3301-169-スミレ" = "……筋肉！"
"3301-170-レイ" = "自分だけじゃトレーニング方法が分からなくて……#nそれなら専門的な知識のある人に教わりたいと思ったんです。"
"3301-171-レイ" = "次の大会まで仮入部したいんですが……いいでしょうか？"
"3301-175-レイ" = "……すみません、急に来られても困りますよね。"
"3301-176-レイ" = "来週、返事を聞かせてもらえれば――"
"3301-178-スミレ" = "すぐに始めましょう！"
"3301-179-レイ" = "は、はい……？"
"3301-181-スミレ" = "トレーニングの成果は、向上心によって大きく変わります！"
"3301-182-スミレ" = "筋肉をつけたいと思ったのなら、1分1秒たりとも無駄にしてはなりません！"
"3301-183-スミレ" = "今！この瞬間にも！あなたの筋肉は少しずつ減っていますから！"
"3301-188-スミレ" = "さあ！早速スクワット10セットから始めましょう！"
"3301-189-レイ" = "ま、待ってください、先輩！#nまだ自分、着替えてすらないんですが！"
"3301-197" = "（……こうして、スミレによるレイの特別トレーニングは始まった）"
