[translation]
"10046030-1" = "第3話;ストーリーテラーのシナリオ"
"10046030-4-？？？" = "ナギサ、起きてくれ。"
"10046030-5-？？？" = "到着だ。"
"10046030-10-セイア" = "おや、先生。#n出迎えがあるとは思わなかった。"
"10046030-11-セイア" = "待たせて済まない。#nもっとスピードを出すべきだったな。"
"10046030-15-セイア" = "ナギサ、ナギサ。"
"10046030-19-ナギサ" = "う、うぅん……。#nもう陸地に着いたのですか……？"
"10046030-20-セイア" = "ずっと陸地を走っていたのだが……空を飛ぶ夢でも見ていたのかい？"
"10046030-21-ナギサ" = "いえ、そもそも眠ってなどいません……#nとにかく、今日からは動かない地面だけを陸地と呼ぶことにします。"
"10046030-29-セイア" = "ナギサ、地面は元々動かないものだよ。"
"10046030-35-ナギサ" = "セイアさん……運転のクセは、まだ直っていなかったのですね……。"
"10046030-36-セイア" = "まるで私が危険運転をしたかのような言い草だね。#n法定速度を遵守したつもりだが？"
"10046030-37-ナギサ" = "この辺りの道路には速度制限なんて無いではありませんか！！"
"10046030-41-ナギサ" = "……あ、先生。"
"10046030-42-ナギサ" = "到着早々、お見苦しい姿を……。"
"10046030-43-セイア" = "こんなビーチで、堅苦しい挨拶はいただけないな。"
"10046030-47-セイア" = "……ん？先生？"
"10046030-48-セイア" = "まるで不思議なものを見るかのような目をしているね。"
"10046030-49" = "[s1] \"二人とも……。\"\n[s2] \"……楽しむ気満々だね！\""
"10046030-54-セイア" = "当然だ。遊びに来ているのだから。"
"10046030-55-セイア" = "普段の生活を忘れ……僅かばかりの逸脱が許される日。#n変わらず無為に過ごすのは、勿体無いだろう？"
"10046030-56-ナギサ" = "私は違います。#nお二人があまりにも強く言うものですから……。"
"10046030-57-セイア" = "また始まったか。"
"10046030-58-セイア" = "今日はプライベートだろう？他人の目もない。#n好きに楽しむがいいさ。"
"10046030-63-ナギサ" = "失礼。"
"10046030-70-セイア" = "[ruby=ゆりぞの]百合園[/ruby]セイアだ。#n君はティーパーティーの……ああ、かけ間違いではない。"
"10046030-71-セイア" = "知っての通り、ナギサは休暇中だ。#n……そう。該当業務はすべて私のほうへ回してくれ。では。"
"10046030-76-ナギサ" = "セイアさん……？"
"10046030-77-セイア" = "約束を忘れるには些か早すぎるだろう。#nそれとも、端から守るつもりがなかったのかい？"
"10046030-78-セイア" = "すでにケリをつけた議題だ。#n今日の業務はすべて――"
"10046030-79-ナギサ" = "……セイアさんにお任せする。#nはい、たしかにそのように約束していました。"
"10046030-80-ナギサ" = "しかし、連絡手段を奪うのは流石に――"
"10046030-81-セイア" = "約束と関係ない、とは言うまいな？"
"10046030-85-セイア" = "敢えて遠方まで足を運び、バカンスを楽しむ理由は何か。"
"10046030-86-セイア" = "ルーチン化した日常生活から離れ、心身ともに休息できる環境をつくる。#nそれが、本来の目的だと理解しているがね。"
"10046030-87-セイア" = "それとも、私の理解に誤りでも？"
"10046030-88-ナギサ" = "……いえ。セイアさんのおっしゃる通りです。"
"10046030-89-セイア" = "では、このスマホは私が預かっておこう。"
"10046030-90-セイア" = "日常との連絡手段が残っていては、君を仕事から分離したとは言えないからね。"
"10046030-91-ナギサ" = "それは飛躍しすぎでは……。"
"10046030-92-セイア" = "まぁ、君がどんな選択をしようと、私は構わないさ。"
"10046030-93-セイア" = "だが、ミカはどう思うだろうね？"
"10046030-94-ナギサ" = "……！"
"10046030-99-セイア" = "ナギサは最初から約束を守るつもりがなかった……#nそれを知ってしまったミカは、果たしてどんな表情をするだろうか。"
"10046030-100-セイア" = "ふむ、俄然興味が湧いてきた。#nナギサは私の好奇心を満たしてくれるか否か、さあ楽しみだね。"
"10046030-101-ナギサ" = "くっ……！"
"10046030-106-ナギサ" = "はあ、分かりました。私のスマホはセイアさんにお預けします。"
"10046030-110-ナギサ" = "ミカさんだけで手一杯なのに……。"
"10046030-111-ナギサ" = "どうしてセイアさんまで……。"
"10046030-120-セイア" = "ふむ、あれでナギサは押しに弱いのか。"
"10046030-121-セイア" = "どうだい、先生。#nミカの真似事……我ながら、中々の出来だったと思うのだが。"
"10046030-122" = "[s3] \"今のって、ミカの真似だったの？\"\n[s4] \"似てる……かな？\""
"10046030-127-セイア" = "おや、冴えない反応だね。"
"10046030-128-セイア" = "まあいいさ。次また挑戦してみよう。#nまだ、ナギサの真似が残っているからね。"
"10046030-129-セイア" = "先生。"
"10046030-130-セイア" = "もしかすると……いや、確実に君は「特別な何か」を見ることになる。#n強いて言うならば……これはある種の前日譚。"
"10046030-134-セイア" = "「お姫様を乗せたカボチャの馬車。#n　その馬車引きネズミは、どこから来たのか」"
"10046030-135-セイア" = "そう、これはそういう物語だ。"
"10046030-139-セイア" = "……あぁ、つい悪い癖が出てしまったね。そう難しい話ではないのさ。"
"10046030-145-セイア" = "平たく言えば……。"
"10046030-146-セイア" = "すなわち……。"
"10046030-151-セイア" = "いや、やめておこう。"
"10046030-152" = "[s5] \"き、気になる！\"\n[s6] \"続き……続きは！？\""
"10046030-155-セイア" = "ふふ、ネタバレはよくないからね。"
"10046030-156-セイア" = "「先に知っている」ことほど、面白味に欠けるものもないさ。"
"10046030-157-セイア" = "……シリアスな話をするつもりはなかったんだ。"
"10046030-158-セイア" = "そう重く捉えないでくれ。#n無論、これを聞けば先生が戸惑うだろうことは、想定の範疇だがね。"
"10046030-159-セイア" = "この目で見たい……確かめたいという悪い癖は、中々治らないものだ。"
"10046030-163-セイア" = "……ん？何か言いたげな顔だね。"
"10046030-164-セイア" = "治すつもりなんて微塵もないくせに。#n君が考えているのはそんなところかな？"
"10046030-165-セイア" = "然らば、私からの返事は至ってシンプルだ。#n当然だろう？とね。"
"10046030-166-セイア" = "その「悪い癖」だって、今の百合園セイアを構成する一要素なのだから。"
"10046030-167-セイア" = "もしかすると、治すという表現自体、語弊があるのかもしれない。#nこれはより根深いところに作用する、根源的な変化の話だからね。"
"10046030-168-セイア" = "とはいえ、今日はさすがに自重しようか。"
"10046030-169-セイア" = "自己中心的で、後先考えないおてんば娘が、苦心の末に用意した一日だからね。"
"10046030-170-セイア" = "あくまで、同じティーパーティーの一員として――"
"10046030-171-セイア" = "いや、友人として、誠心誠意臨まなければ失礼だろうさ。"
"10046030-176" = "（ドサッ！バターン！）"
"10046030-180-セイア" = "今の音は？"
"10046030-181-セイア" = "砂浜のほうからだな。"
"10046030-182" = "[s7] \"あっ、そういえば……！\"\n[s8] （さっき押収した温泉開発部の資材がまだ……！）"
"10046030-191-ナギサ" = "ええと……。"
"10046030-192-ナギサ" = "これは……何でしょうか。"
"10046030-193-ナギサ" = "こんなものがあった記憶はないのですが……。"
"10046030-197-ミカ" = "な、ナギちゃん！？"
"10046030-198-ミカ" = "わ、私が全部説明するから！"
"10046030-199-ナギサ" = "いいえ、結構です。"
"10046030-203-ミカ" = "（ど、どうしよう……）"
"10046030-204-ミカ" = "（やっぱり怪しまれてる！）"
"10046030-205-ミカ" = "（このままだと……）"
"10046030-212-ナギサ" = "危険が潜む場所で、のんきに遊んでなどいられません。"
"10046030-213-ナギサ" = "より安全なところへ移動しましょう。"
"10046030-214-ナギサ" = "ここから一番近いセーフハウスは――"
"10046030-218-ミカ" = "じゃ、じゃあ、このバカンスは……？"
"10046030-222-ナギサ" = "もちろん、中止です。"
"10046030-228-ミカ" = "ダメぇぇぇぇーっ！！！"
"10046030-232-ナギサ" = "っ！？#nいきなり大声を出して、どうしたのですか？"
"10046030-236-ミカ" = "あ、ううん！ナギちゃん、これはね！"
"10046030-237-ナギサ" = "はぁ……大方予想がつきますが……#n困りましたね……。"
"10046030-238-ミカ" = "ちゃんと説明するから！"
"10046030-239-ナギサ" = "いえ、結構です。"
"10046030-240-ナギサ" = "この件に関しては、黙認することにいたしましょう。"
"10046030-244-ミカ" = "……え？"
"10046030-245-ナギサ" = "可能性の一つとして、想定はしていました。#n私たちの代になってからは、使ってこなかったのですから。"
"10046030-246-ナギサ" = "今さら、私有地だから荷物を除けろと言っても、近隣住民は納得しないでしょう。"
"10046030-247-ナギサ" = "……ですが、この量には少々驚きました。#nどこかで工事でも行われるのでしょうか？"
"10046030-248-ミカ" = "え……あれ？"
"10046030-249-ミカ" = "あ、あぁ～そういえば！今朝、工事の関係者さんが来たんだ！#nちょっとここに物を置かせてもらう、とか言ってたような～？"
"10046030-250-ミカ" = "報告するの忘れちゃってた☆"
"10046030-254-ナギサ" = "はい？#nそれは……そちらの方が問題かと。"
"10046030-255-ミカ" = "ごめんってば～準備で忙しかったんだよ～"
"10046030-259-ミカ" = "それよりさ、早くお昼食べない？私お腹空いちゃった！"
"10046030-264-ナギサ" = "まったく、あなたはいつもいつも……。"
"10046030-272-ミカ" = "…………。"
"10046030-273-ミカ" = "なんとか、誤魔化せたかな……？"
"10046030-278-セイア" = "ミカ。"
"10046030-282-ミカ" = "わっ、セイアちゃん！いたの？"
"10046030-283-セイア" = "ああ。楽しそうだったから、声をかけるのはためらわれてね。"
"10046030-287-セイア" = "良い演技だった。#nトリニティを欺いてみせただけのことはある。"
"10046030-288-ミカ" = "そ、その話するのあり！？"
"10046030-289-セイア" = "ふふ、すまない。#n君の慌てた様子を見ていると、つい意地悪を言いたくなってしまうんだ。"
"10046030-290-セイア" = "それより今日のナギサは……なるほど、やはり。"
"10046030-291-セイア" = "予想より早い気はするが、長らく多忙を極めていたからね。"
"10046030-292" = "[s9] \"やはりって？\"\n[s10] \"やっぱり気になる……！\""
"10046030-297-セイア" = "落ち着かない様子を見せる者はここにもいたか。"
"10046030-298-セイア" = "言うのは構わないが。"
"10046030-302-セイア" = "…………。"
"10046030-303-セイア" = "いや、ネタバレはよしておこう。"
"10046030-304-ミカ" = "セイアちゃんはす～ぐそういう言い方するんだから。"
"10046030-305-セイア" = "これが私の性分なものでね。#nむしろ、そろそろ君が汲み取れるようになって欲しいくらいだ。"
"10046030-306-ミカ" = "むっかぁ……！"
"10046030-307-ミカ" = "はぁ……ここは我慢しないと。"
"10046030-308-セイア" = "ふむ？"
"10046030-309-ミカ" = "計画は順調だし、別に怒る必要はないもんね！"
"10046030-310-ミカ" = "あとは材料さえ届けば、お昼のバーベキューを始められるし――"
"10046030-314-ミカ" = "あれ、今何時？"
"10046030-319-ミカ" = "12時40分……？"
"10046030-320-ミカ" = "う～ん……12時半には届くはずなのに……。"
"10046030-321-ミカ" = "なんか嫌な予感……。"
"10046030-325-ミカ" = "う、ううん！大丈夫！"
"10046030-326-ミカ" = "まさかトラブルなんて……。"
"10046030-335-ミカ" = "13時に……なっちゃった……。"
"10046030-336-ミカ" = "ちょっと電話してみるね。"
"10046030-344-ミカ" = "あ、もしもし？#n今日、バーベキ――"
"10046030-352-ミカ" = "えっ！？"
"10046030-353-ミカ" = "ま、待って。どういうこと？#n……え？"
"10046030-354-ミカ" = "トラックが襲撃されて……って、聞き間違いだよね……？"
"10046030-355-ミカ" = "え、ごめん、もうちょっと詳しく説明してくれる？"
"10046030-360-ミカ" = "うん、うん。"
"10046030-361-ミカ" = "配送してたトラックがジャックされて、失踪中……？"
"10046030-365-ミカ" = "どうしてそうなるの！？"
"10046030-366-ミカ" = "いやいや！運んでるのって、お金とか宝石じゃないんだよ？"
"10046030-367-ミカ" = "も、もちろん一番良いものではあるけど……食材だよ？"
"10046030-371-ナギサ" = "今、叫び声が聞こえたような……なにかトラブルでも？"
"10046030-375-ミカ" = "き、気のせいじゃないかな？#n大丈夫だから、ナギちゃんは休んでて！"
"10046030-376-イチカ" = "あの……何かあったんすか？"
"10046030-377-ミカ" = "い、イチカちゃん！？ならいっか……。"
"10046030-378-ミカ" = "えと……信じられないと思うんだけど……。"
"10046030-383-イチカ" = "うーん……食材目当てにトラックを襲いそうな集団っすか……。"
"10046030-384-イチカ" = "少なくとも、片手じゃ足りないくらいは思いつくっすね……。"
"10046030-385-ミカ" = "そんなに！？"
"10046030-386-イチカ" = "まあ……この仕事をしてると、色々あるんすよ。"
"10046030-387-イチカ" = "それより、どうするっすか？#n今から買い物に行くにしても、時間かかっちゃいますし……。"
"10046030-388-イチカ" = "あ。一応持ってきたパンとソーセージがあるっす。#n味気ないっすけど、お昼にはなると思うっすよ。"
"10046030-389-ミカ" = "それは……ダメ！"
"10046030-393-イチカ" = "どうしてっすか？"
"10046030-394-ミカ" = "お昼はバーベキューって、ナギちゃんに言っちゃったんだもん。"
"10046030-395-ミカ" = "なのにバーベキューじゃなかったら、バカンスはそこで終わりなんだよ！"
"10046030-396-イチカ" = "いや……それはちょっと飛躍しすぎじゃないっすか……？"
"10046030-397-ミカ" = "用意できなかった理由に、ナギちゃんが気づいたら……？"
"10046030-398-イチカ" = "あー……それは、ちょっとヤバいかもっすね。"
"10046030-399-ミカ" = "でしょ！？#nでも、いきなりバーベキューの準備なんてできないよ……。"
"10046030-404" = "[ns11] \"可能性が……あるかも、しれない。\"\n[ns12] \"でも、この手だけは……使いたくなかったのに……！\""
"10046030-409" = "[ns] \"使いたくなかったのにっ！！！\""
"10046030-410-ミカ" = "せ、先生！？大丈夫？"
"10046030-411-ミカ" = "えーと……その方法だと、先生が困ることになっちゃうの？"
"10046030-412-ミカ" = "無理はしなくていいんだよ？#nあくまで私たちの問題だからね。"
"10046030-413-ミカ" = "え？心配なのは……私？どういうこと？"
"10046030-418-ミカ" = "私のことなら、別に遠慮しなくていいよ。"
"10046030-419-ミカ" = "どんな方法かは知らないけど、今日のためなら何でもするって決めたからね！"
"10046030-423-？？？" = "……なるほど。事情は分かりました。"
"10046030-435-ハルナ" = "美食について私たちを頼ったのは――"
"10046030-440-ハルナ" = "良い選択と言えるでしょう。うふふっ。"
