[translation]
"10046025-3-カスミ" = "イチカちゃん……。#n君は、親しき仲にも礼儀ありという言葉を知らんのか？"
"10046025-4-イチカ" = "そんな仲になった覚えはないっすよ！"
"10046025-5-カスミ" = "ツレないねぇ～せっかく似た者同士だというのに。"
"10046025-6-イチカ" = "誰がっすか！！もう逃がさないっすよ！！"
"10046025-7-カスミ" = "ハハッ！威勢が良いじゃないか！"
"10046025-12-ハスミ" = "…………。"
"10046025-16-ハスミ" = "あ、すみません。目の前の光景が信じられなくて……。"
"10046025-17-ハスミ" = "あれほど感情を露わにするイチカは、初めて見ました。"
"10046025-18-ハスミ" = "よほど因縁でもあるのでしょうか？"
"10046025-19" = "[s1] \"話すと長くなるけど……。\"\n[s2] \"あはは……色々あったね……。\""
"10046025-24-ハスミ" = "そう、なのですね……？"
"10046025-30-カスミ" = "うーーん！やはり正面突破はまだ無理があったな！#n全員――撤収！"
"10046025-38-イチカ" = "逃がすかーっ！ハスミ先輩！私に追わせてほしいっす！"
"10046025-42-ハスミ" = "初めての合同作戦を思い出しますね。#nいいでしょう。撃ち漏らしは私が対応します。"
"10046025-47-？？？" = "二人ともストーップ！！"
"10046025-51-ハスミ" = "……ミカ様？"
"10046025-57-ミカ" = "ごめんね。温泉開発部を追うのは、もうやめてもらっていいかな。"
"10046025-58-ハスミ" = "それでは、結局……！"
"10046025-59-ミカ" = "うん、分かってるよ。"
"10046025-60-ミカ" = "でも、もうすぐナギちゃんたちが到着する時間なの。"
"10046025-64-ミカ" = "今回の目的は、ナギちゃんにゆっくり休んでもらうこと。"
"10046025-65-ミカ" = "戦ってるところとか、その痕跡とかをナギちゃんが見たら……。#nきっと不安がっちゃう。"
"10046025-66-ミカ" = "だから、あの子たちのことは後回し。"
"10046025-67-ミカ" = "今考えないといけないのは――"
"10046025-72-ミカ" = "騒ぎを起こさないこと……ナギちゃんに心配をかけないこと……。"
"10046025-73-ミカ" = "……。"
"10046025-74-ミカ" = "二人にも、先生にも迷惑をかけると思う。#nでも……そうさせてほしいんだ。"
"10046025-75" = "[s3] \"ミカは偉いね。\"\n[s4] \"私も全力で手伝うよ。\""
"10046025-82-ハスミ" = "……私たちこそ、申し訳ございません。#n目先に囚われ、大事を見落とすところでした。"
"10046025-83-ハスミ" = "今回のバカンスは、ナギサ様に休んでいただくためのもの……。"
"10046025-84-イチカ" = "もっと先にやるべきことがあるっすよね。面目ないっす。"
"10046025-88-ハスミ" = "証拠隠滅は手早く。もう時間がありません。"
"10046025-96-ハスミ" = "……凄まじい量ですね。"
"10046025-97-ハスミ" = "これだけあれば、建物の一つや二つ、簡単に建てられるでしょう……。#nここで一体何を企んでいたのでしょうか？"
"10046025-98-イチカ" = "温泉建設っすね。たぶん。"
"10046025-99-ハスミ" = "……温泉開発部の悪名は伊達ではないと。"
"10046025-100-ハスミ" = "とはいえ、これだけ押収しておけば、しばらくは静かになるでしょう。"
"10046025-101-ハスミ" = "活動が数日止まるだけで、十分なのですから。"
"10046025-102-ミカ" = "あはは……うん、そうだといいね。"
"10046025-103-ミカ" = "このバカンスさえ無事に終われば――"
"10046025-104-ミカ" = "あとは、どうなってもいいから。"
"10046025-108-ハスミ" = "ミカ様？"
"10046025-112-ミカ" = "ううん、なんでもない。"
"10046025-113-ミカ" = "ありがとね☆"
"10046025-115-イチカ" = "い、いえ！当然のことをしたまでっす！"
"10046025-117-ハスミ" = "ええ、イチカの言う通りです。#nこれが私たちの仕事ですから。"
"10046025-118-ミカ" = "それでも、お礼を言いたかったんだ。"
"10046025-119-ミカ" = "……えへへっ。"
"10046025-121-イチカ" = "ミカ様……？？"
"10046025-122" = "[s5] \"……ミカ？\"\n[s6] \"何か思いついたの……？\""
"10046025-127-ミカ" = "あ、ううん。ただ……。"
"10046025-128-ミカ" = "なんというか……今回はうまくいきそうな気がして！"
"10046025-129-ミカ" = "……うん！"
"10046025-130-ミカ" = "きっと大丈夫！"
