[translation]
"10023055-2-慈愛の怪盗" = "嗚呼、奇怪な格好なのになかなかどうして――やりますね。"
"10023055-3-トキ" = "ありがとうございます、[ruby=・   ・   ・]泥棒様[/ruby]。#nこれでよろしいのでしょう？"
"10023055-4-慈愛の怪盗" = "――「[ruby=・   ・]怪盗[/ruby]」ですよ、お嬢さん。"
"10023055-18-トキ" = "！？こんなところに罠が……？"
"10023055-26-慈愛の怪盗" = "次からは、足元にも気を配ったほうが良いですよ。#nせっかくのダンスが台無しになってしまいますから。"
"10023055-30-慈愛の怪盗" = "！？"
"10023055-31-モモイ" = "――させないよ！"
"10023055-32-ミドリ" = "……私たちも加勢します！"
"10023055-34-慈愛の怪盗" = "おや、可愛いメイドさんですね。"
"10023055-36-モモイ" = "か、可愛いだって！えへへ……"
"10023055-37-ミドリ" = "お姉ちゃん！喜んでる場合じゃないでしょ！？"
"10023055-38-ミドリ" = "ここで私たちが……あなたを止めます！"
"10023055-39-慈愛の怪盗" = "ふふ……その心意気も美しい。#n……でも、残念です。"
"10023055-45-慈愛の怪盗" = "……最初の一撃で仕留めるべきでしたね。"
"10023055-46-慈愛の怪盗" = "向こう見ずの勇気は美学から最も遠い存在ですよ、お嬢さん。#n――君は、弱いのだから。"
"10023055-48-モモイ" = "そうかも、しれないけど……！"
"10023055-50-ミドリ" = "あなたの相手は、私たちだけではありません！"
"10023055-51-慈愛の怪盗" = "……？"
"10023055-55-アリス" = "光よ！"
"10023055-60-慈愛の怪盗" = "くっ……！？"
"10023055-61-モモイ" = "ありがとう、アリス！"
"10023055-62-モモイ" = "えっと……周りに被害は出てないよね？"
"10023055-63-アリス" = "はい！今日のアリスは光属性単体アタッカーです！#nですので、一つの目標に全ての火力を集中させています！"
"10023055-65-慈愛の怪盗" = "……！"
"10023055-66-ミドリ" = "……まだ動けるんですね。"
"10023055-75-ユズ" = "――う、撃ちます……！"
"10023055-76-慈愛の怪盗" = "うっ！？"
"10023055-82-モモイ" = "今だ！捕まえて！"
"10023055-83-ミドリ" = "うん、お姉ちゃん！"
"10023055-91-モモイ" = "うわっ！？"
"10023055-92-ミドリ" = "きゃぁっ！"
"10023055-93-モモイ" = "ど、どうなってるの！？"
"10023055-94-ミドリ" = "見て、天井に！"
"10023055-96-慈愛の怪盗" = "――ふむ。先程までの言葉を撤回するとしましょう。"
"10023055-97-慈愛の怪盗" = "お嬢さん方は――もう相当な実力をお持ちのようだ。#nお名前は？"
"10023055-99-トキ" = "私はC&C所属、コールサインゼロフォー。[ruby=あすま]飛鳥馬[/ruby]トキと申します。"
"10023055-104-慈愛の怪盗" = "ふむ――あのC&Cが[ruby=どうだ]銅田[/ruby]に協力とは……。"
"10023055-105-慈愛の怪盗" = "一体、何故ですか？"
"10023055-107-モモイ" = "依頼の報酬で……新しいプライステーションPro7を買おうかなって……"
"10023055-108-慈愛の怪盗" = "……うん？"
"10023055-109-ミドリ" = "お姉ちゃん！本当に買うつもりだったの！？"
"10023055-110-ミドリ" = "いや！そうじゃなくて……！#n私たちは美術品を――"
"10023055-111-ミドリ" = "――怪盗から守りたくて！"
"10023055-115-慈愛の怪盗" = "……"
"10023055-116" = "[ns] \"どうして美術品を盗もうと思ったの……？\""
"10023055-117-慈愛の怪盗" = "貴方は……"
"10023055-118-慈愛の怪盗" = "嗚呼――記憶の澱に沈んでしまっていたけれど、その顔には見覚えがあります。"
"10023055-119-慈愛の怪盗" = "――シャーレの「先生」、ですね？"
"10023055-120-慈愛の怪盗" = "あの日――[ruby=わたくし] 私 [/ruby]たち七囚人が矯正局から解き放たれた記念すべき日に、キヴォトスに足を踏み入れたという――"
"10023055-121-慈愛の怪盗" = "なるほど……そういう事でしたか。"
"10023055-122-明太郎" = "「慈愛の怪盗」め！#nこの屋敷に忍び込んだが最後、そう簡単には抜け出せんぞ！"
"10023055-129-モモイ" = "ちょ、ちょっと！そんな無差別に撃ったら、私たちまで……！"
"10023055-130-ミドリ" = "あっ……！？"
"10023055-134-ユズ" = "ミドリ！？"
"10023055-137-ミドリ" = "（えっ……？）"
"10023055-138-ミドリ" = "（私、落ちてる……？）"
"10023055-140-慈愛の怪盗" = "ふふっ、お怪我はありませんか？お嬢さん。"
"10023055-146-アリス" = "……！「慈愛の怪盗」がミドリを助けてくれました！"
"10023055-147-モモイ" = "ミドリ、怪我は！？"
"10023055-148-ミドリ" = "う、うん……大丈夫。#nでも、どうして「慈愛の怪盗」が私を……？"
"10023055-149-ミドリ" = "（何でだろう……？）"
"10023055-153-慈愛の怪盗" = "なるほど、今宵の舞台は面白くなりそうですね――"
"10023055-154-慈愛の怪盗" = "一つ、お嬢さん方に伝えておきましょう。#n表面の事象に囚われていては、本質を見極める事など夢のまた夢ですよ。"
"10023055-155-慈愛の怪盗" = "――それでは、これにて失礼。……そう遠からず、またお会いする事になるでしょうけれど。その時まで、良い夢を。bye！"
"10023055-159-モモイ" = "逃げた！"
"10023055-160-ミドリ" = "お姉ちゃん、見てこれ！"
"10023055-161-ミドリ" = "「予告は実行されておりません」だって。"
"10023055-162-モモイ" = "ふん、あと一歩で捕まるところだったくせに！"
"10023055-163-ミドリ" = "今回は謎解き要素が無いね……#nというか、毎回いろんなパターンのヤツを持ち歩いてるのかな……。"
"10023055-167-明太郎" = "皆様……こちら、ご説明いただいても？"
"10023055-168-モモイ" = "わっ！？そ、それが……！"
"10023055-169" = "[s] \"全て我々が計画した陽動作戦です。\""
"10023055-170-ミドリ" = "先生！"
"10023055-171-明太郎" = "ほう……詳しくお伺いしても？"
"10023055-173-明太郎" = "なるほど……５人目のメンバーは遅れて合流する計画だった、と。"
"10023055-174-明太郎" = "作戦は成功しかけていたという事だったのですね。"
"10023055-175" = "[s] \"申し訳ありません、あと一歩のところで……\""
"10023055-176-明太郎" = "謝らないでください。何も盗まれてなどいないのですから……それに、あの「慈愛の怪盗」をあそこまで追い詰めたその手腕、流石と言わざるを得ません。"
"10023055-177-明太郎" = "取り逃がしこそしましたが……皆様の実力は怪盗に伝わったはず。#nもう二度と現れないかもしれません。"
"10023055-178-ミドリ" = "そ、それは流石に無いと思いますが……。"
"10023055-180-ゲストA" = "あの、[ruby=めいたろう]明太郎[/ruby]さん。これは一体どういうことなんですか？"
"10023055-181-ゲストB" = "まさか、「慈愛の怪盗」が現れるだなんて。#n事前に知っていたら、断っていたのに……"
"10023055-182-明太郎" = "さあさ皆様、落ち着いてください。#n「慈愛の怪盗」が来て、何か問題は発生しましたか？"
"10023055-183-明太郎" = "ご覧の通り、私たちは怪盗を退けました。#nそうですよね？"
"10023055-184-明太郎" = "それもそのはず。#nこの屋敷を警備しているのは、かの有名なC&Cなのですから！"
"10023055-186-ゲストA" = "C&C……噂に聞いた事がある。#n……ミレニアム最強のエージェントだとか。"
"10023055-187-ゲストB" = "それが本当なら、怪盗を追い払えたのも納得がいく。"
"10023055-189-明太郎" = "皆様、ご納得くださり、お礼を申し上げます。"
"10023055-190-明太郎" = "ひとまず今日のパーティーは、一度お開きにした方が良さそうですね。#nゲストの方々はお部屋までご案内いたしますので、こちらへ……"
"10023055-194-明太郎" = "では、C&Cの皆様もお疲れでしょうし、今日のところはごゆるりと。#n今後の計画は、それからでも構いません。"
"10023055-197-モモイ" = "……（な、なに、めっちゃ睨まれてるけど！？）"
"10023055-198-トキ" = "……"
"10023055-199-ミドリ" = "（先生……さっきからトキさんがこっちをずっと見ているんですが……）"
"10023055-200" = "[ns] \"えっと……トキ、まずは落ち着いて……\""
"10023055-201-モモイ" = "そ、そんな風に睨まれたって、全然怖くないんだからね！"
"10023055-202-モモイ" = "というか、協力したんだし……感謝の言葉くらいあってもいいんじゃないかな！"
"10023055-207-トキ" = "……そうですね。"
"10023055-208-トキ" = "ありがとうございます、ゲーム開発部の皆さん。"
"10023055-209-モモイ" = "え、え？ええっ？"
"10023055-210-ミドリ" = "えっ……！"
"10023055-214-トキ" = "いえ、助けていただいたのは事実ですので……#n伝えるのが遅くなり申し訳ありません。"
"10023055-215-モモイ" = "じゃ、じゃあ……なんで睨んでたの！？"
"10023055-216-トキ" = "あまりこういった事態に慣れておりませんので……#nどのように話を切り出せばいいのか、分からず……"
"10023055-217-ミドリ" = "つまり、トキさんは何を言えば良いのか分からなくて、こっちを見ていただけって事ですか……？"
"10023055-218-トキ" = "はい。先に話を切り出してくださり、ありがとうございます、モモイ。"
"10023055-219-トキ" = "そして、今後のことなのですが――"
"10023055-221-ミドリ" = "なるほど。トキさんの任務は、「慈愛の怪盗」を阻止することだったんですね……"
"10023055-222-トキ" = "はい、同時に別の任務も遂行中ではありますが。"
"10023055-223-モモイ" = "その……私たちが任務の足を引っ張った、とか……#nネル先輩に言ったりしないよね？"
"10023055-224-トキ" = "いえ、そのような事はいたしません。#nむしろ、ゲーム開発部の皆さんは最善を尽くしているかと。"
"10023055-225-トキ" = "……そうですね。#nここは一つ、C&Cとゲーム開発部の合同作戦……というのはどうでしょう。"
"10023055-226-ミドリ" = "その……本当に良いんですか？"
"10023055-227-トキ" = "大丈夫です。先輩方は居ませんし。"
"10023055-228-モモイ" = "そういう問題なのかな？"
"10023055-230-トキ" = "ええ、そういう問題です。"
"10023055-231-アリス" = "それでは、トキも仲間になるんですね？"
"10023055-232-トキ" = "……？"
"10023055-233-アリス" = "アリスはトキとパーティーを組みたいです。#n一緒にこのクエストを解決したいです！"
"10023055-234-トキ" = "な、仲間……ですか？"
"10023055-235-アリス" = "やっぱり、ダメですか……？"
"10023055-236-トキ" = "そういうわけではありませんが……#nそれに……先日、断ったりもしましたし……"
"10023055-237-アリス" = "大丈夫です。仲間は怖くありません！#nそれでは、今からトキとゲーム開発部は、仲間です！"
"10023055-238-トキ" = "あ、ありがとうございます。そう言って、くださって……"
"10023055-239-アリス" = "パンパカパーン！トキがパーティーに加わりました！"
"10023055-244-トキ" = "ひゃっ！？"
"10023055-245-トキ" = "い、いったい何を……？"
"10023055-249-トキ" = "……（なでなで）"
"10023055-250-トキ" = "（ちょうど良い位置に頭があって撫でやすいですね……なんだか、心が穏やかに……）"
"10023055-255-ミドリ" = "……大丈夫かな。"
"10023055-256-モモイ" = "アリスもああ言ってるし、心配いらないよ。"
"10023055-258-ユズ" = "良かったね、アリスちゃん。トキさんも……"
"10023055-260" = "（そうして、トキはゲーム開発部の仲間になった）"
"10023055-261" = "（めでたし、めでた……）"
"10023055-263" = "（続く！）"
