[translation]
"1601105-1" = "自己管理"
"1601105-3" = "（大運動会当日のお昼前）"
"1601105-4" = "（ベンチの片隅で、お弁当を食べているハスミを発見した）"
"1601105-8" = "[ns1] \"ハスミ？\"\n[ns2] \"あれ、一人で食べてるの？\""
"1601105-13-ハスミ" = "……ん？"
"1601105-14-ハスミ" = "あ、先生……こんにちは。"
"1601105-15-ハスミ" = "こんなところでお会いするとは……"
"1601105-16-ハスミ" = "私ですか？#nお昼休みに他の生徒を案内しなければならないので、少し早くご飯をいただいていたんです。"
"1601105-20-ハスミ" = "先生……？どうしたんですか……？"
"1601105-21-ハスミ" = "そんなに見つめて……えっ、お弁当の中身？"
"1601105-22-ハスミ" = "ご覧の通り、"
"1601105-26-ハスミ" = "サツマイモとゆで卵、トマトです。"
"1601105-27-ハスミ" = "ああ……えっと……。"
"1601105-28-ハスミ" = "もしかして、先ほど送ったモモトークの件を気になさってます？#nすみません、私が余計なことを言ってしまったので……。"
"1601105-29" = "[s3] \"これってもしかして、ダイエットメニュー？\"\n[s4] \"忙しそうなのに……これでご飯足りる？\""
"1601105-32-ハスミ" = "あ、その……カロリー的には大丈夫です。"
"1601105-33-ハスミ" = "むしろ、こういう日ですから、普段より効果があるのではと期待しているくらいです。"
"1601105-34-ハスミ" = "ただ……。"
"1601105-35" = "[s] \"ただ……？\""
"1601105-42-参加生徒A" = "わぁー！お腹空いた－！#nもうすぐお昼休みだね！"
"1601105-43-参加生徒A" = "早くお肉食べたい、お肉！"
"1601105-44-参加生徒B" = "あなたって本当にお肉好きね……"
"1601105-45-参加生徒B" = "せっかくだから私はスイーツをたくさん持ってきたんだ。"
"1601105-46-参加生徒A" = "えー！？どうしてスイーツ！？しかもすごい量！#nそんなんだから太るんだよ！"
"1601105-47-参加生徒B" = "いっぱい運動するんだからゼロカロリーだよ！"
"1601105-48-参加生徒B" = "運動する日こそ絶好のスイーツ日和じゃん！"
"1601105-49-参加生徒A" = "それだったらお肉のほうが良くない？"
"1601105-50-参加生徒B" = "スイーツ日和だよ！！"
"1601105-51-参加生徒A" = "お肉！！"
"1601105-52-参加生徒B" = "スイーツ！！"
"1601105-56-参加生徒A" = "お肉ー！焼肉でしょ！！"
"1601105-57-参加生徒B" = "スイーツ！スイーツ！パフェ！！"
"1601105-62-ハスミ" = "…………"
"1601105-63" = "[s5] \"こういう日だからって……そういう事か……。\"\n[s6] \"普段からいろんな誘惑があるんだね。\""
"1601105-66-ハスミ" = "も、もちろん周囲がどうであれ、これは自分自身との戦いですし……#nこの程度で決意が揺らぐなんて……恥ずかしい事ではありますが……。"
"1601105-67-ハスミ" = "まだまだ至らないようです……お恥ずかしい限りです。"
"1601105-68-ハスミ" = "……え？この間のレモンのはちみつ漬け、ですか？"
"1601105-69-ハスミ" = "あ、それは全部正義実現委員会の子たちの分で、自分で食べるつもりではなく……"
"1601105-70-ハスミ" = "それに、ご存知だとは思いますが、はちみつはカロリーがとても高くて……#nアレを食べてしまったらダイエットの意味が……。"
"1601105-71" = "[ns] \"……。\""
"1601105-78" = "[ns7] もらったレモンのはちみつ漬けを渡す。\n[ns8] \"少しだけ、一緒に食べない？\""
"1601105-83-ハスミ" = "！？せ、先生……！？#nそ、それは一体……。"
"1601105-84-ハスミ" = "……一つを二人で分けるなら、カロリーも半分だから……？"
"1601105-85-ハスミ" = "そ、それはそうかもしれませんが……。"
"1601105-86-ハスミ" = "これは先生に差し上げたもので……！"
"1601105-87-ハスミ" = "……い、いえ、決して嫌なわけではありませんが……！#nその……。"
"1601105-88-ハスミ" = "やはり、なんと言いますか……その……！"
"1601105-92-ハスミ" = "……はぁ。"
"1601105-93-ハスミ" = "何でもありません、また変なことを考えてしまっておりました……"
"1601105-94-ハスミ" = "すみません。"
"1601105-95-ハスミ" = "ありがとうございます。#nそれでは、少しだけ……"
"1601105-96-ハスミ" = "ほんの少しだけ……いただきますね。"
"1601105-105" = "[ns9] \"……ハスミ？\"\n[ns10] \"どうしたの……？\""
"1601105-108-ハスミ" = "ん……。"
"1601105-113-ハスミ" = "…………！！"
"1601105-114-ハスミ" = "ダイエット食ばかりだったので、急な甘味にお口がビックリしてしまって……！"
"1601105-115-ハスミ" = "この感覚、本当に久しぶりの……。"
"1601105-120-ハスミ" = "ああ……もう我慢できません……！！"
"1601105-128" = "[ns11] \"……ハ、ハスミ？大丈夫？\"\n[ns12] \"ハスミ、待って！そんなに食べたら……！\""
"1601105-139-ハスミ" = "……ふぅ。本当に……生き返った気分です……。"
"1601105-140-ハスミ" = "美味しかったです……ごちそうさまでした。"
"1601105-144-ハスミ" = "…………。"
"1601105-145-ハスミ" = "あれ……。"
"1601105-146-ハスミ" = "せ、先生……？あの……その……これは……。"
"1601105-147-ハスミ" = "美味しすぎて……つい、全部……たべて、しまって……。"
"1601105-151-ハスミ" = "ごめんなさい……。"
"1601105-153" = "（大丈夫だよ、とハスミを慰めたあと席を離れた）"
