[translation]
"1601703-1" = "I hate this world "
"1601703-2" = "（アオバが教えてくれた場所に向かった）"
"1601703-8" = "[ns]\"この辺だと思うけど……。\""
"1601703-12-？？？" = "あっ！せ、先生……！"
"1601703-17-アオバ" = "き、来てくださって、ありがとうございます……。"
"1601703-18-アオバ" = "ほ、ほんとに来てくれた……。"
"1601703-22-アオバ" = "えっと！きょ、今日お呼びした件は……ですね……。"
"1601703-23-アオバ" = "こ、この踏切の整備です……。ずっと点滅しちゃってて……。"
"1601703-24-アオバ" = "列車が通ってなくても作動するんです……。"
"1601703-28-アオバ" = "こ、こんな有様ですけど……。"
"1601703-29" = "[s] \"これは早く直したいね。\""
"1601703-30-アオバ" = "はい。ひとまず、診てみます……。"
"1601703-35-アオバ" = "うん、配線は大丈夫……。"
"1601703-36-アオバ" = "センサーかな……？"
"1601703-40-アオバ" = "な、なら……。"
"1601703-44-アオバ" = "え、えぇいっ……！"
"1601703-49-アオバ" = "も、もう一回……！"
"1601703-54" = "[ns] \"そ、それ、本当に大丈夫なの！？\""
"1601703-58-アオバ" = "ど、どうかしましたか！？"
"1601703-59" = "[s] \"パイプレンチで思いっきり叩いてるから……。\""
"1601703-60-アオバ" = "……？"
"1601703-64-アオバ" = "……あぁっ！"
"1601703-65-アオバ" = "……えっと。"
"1601703-66-アオバ" = "た、大抵の機械は、叩くと直るんですけど……。"
"1601703-67-アオバ" = "へへっ……今までも、こうしてきたので……。"
"1601703-68" = "[s] \"……そ、そうなんだ。\""
"1601703-69-アオバ" = "と、とにかく……これで直るはず……。"
"1601703-70-アオバ" = "もたもたしてると……次の列車が来ちゃいますね……。"
"1601703-71-アオバ" = "す、少しペースを上げます……。"
"1601703-78-アオバ" = "こ、これで終わり……！！"
"1601703-91-アオバ" = "……し、静かになりました。"
"1601703-92" = "[s] \"直った……かな？\""
"1601703-93-アオバ" = "す、少し様子を見ましょう。"
"1601703-96" = "（アオバと一緒にしばらく踏切を見守り……）"
"1601703-100" = "（列車が通る時にだけ、正常に作動することを確認した）"
"1601703-103-アオバ" = "……へへっ……よかった。"
"1601703-104" = "[s] \"その方法、本当に効くんだね……。\""
"1601703-105-アオバ" = "た、叩いてダメなら……プランBを試さなきゃだったのですが……。"
"1601703-106-アオバ" = "ぷ、プランAで済んでよかったです……ふぅ。"
"1601703-107-アオバ" = "先生もお疲れ様でした……。"
"1601703-108" = "[s1] \"私は特に手伝っていないけど……\"\n[s2] \"お役に立てたなら、よかったかな……？\""
"1601703-113-アオバ" = "そ、その件なんですが……。"
"1601703-114-アオバ" = "実は……。"
"1601703-115-アオバ" = "わ、私一人でも……多分できました……。"
"1601703-116-アオバ" = "で、でも、先生が、いつでも頼っていいと言ってくださったから……。"
"1601703-117-アオバ" = "だから……。"
"1601703-118-アオバ" = "ほ、ほんのちょっぴり……期待してみてもいいのかな……って……。"
"1601703-119-アオバ" = "き、来てくれて……びっくり、しました……。"
"1601703-120-アオバ" = "う、うう……。"
"1601703-121-アオバ" = "い、忙しいのにすみませんでしたぁ！ひぃやぁ……。"
"1601703-125" = "[ns3] \"呼んでくれてありがとう。\"\n[ns4] \"生徒のお願いには応えるのが先生だからね。\""
"1601703-130-アオバ" = "そ、そうですか……。"
"1601703-131-アオバ" = "先生は……応えてくれる……。"
"1601703-132" = "[s5] \"そ、そんな完璧じゃないよ！？\"\n[s6] \"私だって失敗くらいするし……。\""
"1601703-137-アオバ" = "へ、へへ……。"
"1601703-138-アオバ" = "せ、先生も……私たちと同じなんですね……。"
"1601703-139-アオバ" = "……あっ。きょ、今日はありがとうございました！#nまた……よかったら……。"
"1601703-140-アオバ" = "えへへ。"
"1601703-142" = "（アオバと、他愛ない話をしながら帰路についた）"
