[translation]
"2002205-1" = "連休最後のお出かけ"
"2002205-2" = "ゲヘナ学園・校庭"
"2002205-9-フウカ" = "すみません、お待たせしました……！"
"2002205-10" = "[s] \"ううん、今着いたところだよ。\""
"2002205-11-フウカ" = "約束通り着物で来ましたが……。"
"2002205-12-フウカ" = "えっと……何をするんでしょうか？"
"2002205-13" = "[s1] \"とりあえず、場所を移そうか？\"\n[s2] \"ゲヘナだと、フウカにとってはいつもの場所だろうし。\""
"2002205-16-フウカ" = "……？"
"2002205-17-フウカ" = "と、とりあえず、先生のこと信じてますよ……？"
"2002205-19" = "市内"
"2002205-20-フウカ" = "すごい高さで噂の、展望タワー……。"
"2002205-21-フウカ" = "な、何だか高速エレベーターで上がってきたせいか……"
"2002205-22-フウカ" = "ちょっとだけ、酔ってしまったかもです……。"
"2002205-26-フウカ" = "あっ、すごい……！ここから市内が一望できるんですね！"
"2002205-27-フウカ" = "と、ところで、どうして足元がガラスなんでしょう……？"
"2002205-28-フウカ" = "あ。足がガクガクして、動けません……。"
"2002205-29-フウカ" = "せ、先生、その……よろしければ、手を……。"
"2002205-35-フウカ" = "初めて地面のありがたみを実感しました……！"
"2002205-36-フウカ" = "展望台から見た景色は素敵でしたが、高いところはちょっと怖いですね……。"
"2002205-37-フウカ" = "……え、先生も怖かったんですか？"
"2002205-38-フウカ" = "この、わざわざ怖い思いをしようとする習性、一体何なんでしょうね……。"
"2002205-39-フウカ" = "次に行く場所、ですか？"
"2002205-40-フウカ" = "えっと、お任せしますが、その……いえ、展望タワーも良かったのですが……！"
"2002205-48" = "遊園地"
"2002205-50-フウカ" = "遊園地……話にはよく聞いていましたが……。"
"2002205-54-フウカ" = "……？停止状態から、1.56秒で180km/hまで加速……？"
"2002205-55-フウカ" = "それに加えて、コースの真ん中に直径39.7mの宙返りループ……？"
"2002205-56-フウカ" = "それ、本当に乗って大丈夫ですか！？みんな無事に帰ってこられますか！？"
"2002205-57" = "[s] \"も、もちろん無理強いはしないけど……。\""
"2002205-58-フウカ" = "うぅ……でも先生のオススメですし、せっかく二人で来たわけですし……。"
"2002205-59-フウカ" = "の、乗ります……こうなったら乗りましょう！"
"2002205-61-フウカ" = "きゃああああああああっ！"
"2002205-70-フウカ" = "ううぅ……本当に死ぬかと思いました……。"
"2002205-71-フウカ" = "えっ、もうすぐパレードが始まるんですか？"
"2002205-72-フウカ" = "あ、百鬼夜行連合学院の名前が書いてありますね。"
"2002205-73-フウカ" = "これが噂に聞く、百鬼夜行連合学院のお祭りの力……。"
"2002205-74-フウカ" = "あれ……？後ろに山海経の列も続いてますね？#nその後ろにはレッドウインターも？"
"2002205-75-フウカ" = "あ、なるほど……各学校の特徴をコンセプトにしたパレードなんですね？"
"2002205-76-フウカ" = "ということは、ゲヘナもあるんでしょうか？あ、トリニティが……！"
"2002205-78" = "商店街"
"2002205-83-フウカ" = "楽しかったですね、先生。"
"2002205-84-フウカ" = "少し歩き疲れましたし……お腹も空いたので、どこかお店に入りたいですね。"
"2002205-85-フウカ" = "え、直感で……え、えっと……では、あちらのお店なんてどうでしょう。"
"2002205-86-フウカ" = "な、何でも好きに注文……！？"
"2002205-87-フウカ" = "そ、それはちょっと恐れ多いと言いますか……。"
"2002205-88-フウカ" = "ですが、せっかくですし……て、適度に節度を持ったうえで……！"
"2002205-90" = "（フウカと一緒に、おいしい料理を楽しんだ）"
"2002205-92-フウカ" = "美味しかったです！"
"2002205-93-フウカ" = "そのお会計は大丈夫でしたか？いつの間にか払っていただいてましたが……"
"2002205-94-フウカ" = "い、いえ、気にしないのは流石に無理ですよ……！？"
"2002205-95" = "[s] \"フウカのためだったら、これくらいなんてこと無いから！\""
"2002205-96-フウカ" = "な、何だかすみません……。"
"2002205-97-フウカ" = "え、謝らないでほしい……？"
"2002205-98-フウカ" = "……ふふっ。確かに、言うべき言葉が違うかもしれません。"
"2002205-99-フウカ" = "ありがとうございます、先生！"
"2002205-100" = "[s] \"向こうの方に行こうと思うんだけど、疲れは大丈夫？\""
"2002205-101-フウカ" = "はい、もちろんです！"
"2002205-103" = "夜桜の道"
"2002205-108-フウカ" = "この辺りは静かですね。"
"2002205-109-フウカ" = "こんな夜遅くに外を出歩くのは、何だか久しぶりです。"
"2002205-110" = "[s] \"何だか、慌ただしい一日にしちゃったね……。\""
"2002205-111-フウカ" = "いえいえ、その分充実した一日でした。"
"2002205-112" = "[s] \"フウカに楽しんでもらえたなら良かった。\""
"2002205-113-フウカ" = "そ、それは……？"
"2002205-114-フウカ" = "どうして、急に……？"
"2002205-115" = "[ns] \"いつもゲヘナで頑張ってるから。\""
"2002205-117" = "[ns] \"たまには違うところで、色んな事を楽しんでもらえたらなって。\""
"2002205-121-フウカ" = "せ、先生……。"
"2002205-122-フウカ" = "そんな、閉じ込められてるみたいな……いえ、まあ全然違うというわけではないですが……。"
"2002205-123-フウカ" = "ですが……やっぱり私はただ、自分のやるべきことをやってるだけなので。"
"2002205-124" = "[ns] \"それがフウカだもんね。\""
"2002205-126" = "[ns] \"それでもたまには、良い連休で終わってほしいなって。\""
"2002205-127-フウカ" = "良い連休……。"
"2002205-128-フウカ" = "そう、ですね。先生と過ごせて、良い連休になりました。"
"2002205-131" = "[wa:1500]― 本当に……[wa:1700]嬉しいです。"
"2002205-134" = "[wa:1500]― いつも[wa:700]ありがとうございます、[wa:1200]先生。"
"2002205-137" = "[wa:2000]― 先生からは、[wa:1400]色々と[wa:400]いただいてばかりですね。"
"2002205-140" = "― 私の料理を、[wa:1200]誰よりも[wa:500]おいしく食べて[wa:500]くださるのは……"
"2002205-141" = "[wa:1300]― いつも[wa:300]先生で……。"
"2002205-144" = "[wa:1500]― それが……"
"2002205-145" = "[wa:1600]― 私にとって、[wa:1100]一番の[wa:400]プレゼントなんです。"
"2002205-148" = "[wa:1500]― なので、[wa:500]その……[wa:2000]先生。"
"2002205-149" = "[wa:2100]― これからも、[wa:1300]お願いしますね？"
"2002205-152" = "（夜も深まった頃、フウカを送り届ける帰り道の途中……）"
"2002205-153" = "ゲヘナ学園・校庭"
"2002205-161-フウカ" = "きゃっ！"
"2002205-166" = "[ns] \"フウカ！？\""
"2002205-167-フウカ" = "だ、大丈夫です。ちょっと足を……"
"2002205-168-フウカ" = "っ……！"
"2002205-169-フウカ" = "す、すみません、少し捻ってしまったみたいで……あっ……！"
"2002205-171" = "（ふらつくフウカを、しっかりと抱きとめる）"
"2002205-174-フウカ" = "せ、先生……！？"
"2002205-175-フウカ" = "……。"
"2002205-176-フウカ" = "そ、その……もう少しこのままでも、いいでしょうか……？"
"2002205-180-フウカ" = "（立てないほどじゃないけど……）"
"2002205-181-フウカ" = "（ごめんなさい……今だけはひとりで頑張りきれない、悪い子に……）"
"2002205-183" = "（その後フウカを支えたまま、帰路につくのだった）"
