[translation]
"1009803-1" = "ヒーロー、パトロール"
"1009803-4-ホシノ" = "あ、先生。こっち、こっち。"
"1009803-5-ホシノ" = "……あれ。#nなんか嬉しそうじゃん、何かあったの？"
"1009803-6" = "[s] \"だって、ホシノのヒーロー姿がまた見られるんでしょ！\""
"1009803-7-ホシノ" = "いや～ヒーローなんて言われても、おじさん変身できないよ？"
"1009803-8-ホシノ" = "ま、とりあえず準備はできた？"
"1009803-9-ホシノ" = "今日は砂に覆われてる場所もパトロールするからね。"
"1009803-10-ホシノ" = "下手したら、今日中には帰ってこられないかもしれないし。"
"1009803-11" = "[s] \"もちろん、準備万端だよ。\""
"1009803-12-ホシノ" = "それじゃ、行こっか。"
"1009803-18-ホシノ" = "相変わらず、人がいないねぇ。"
"1009803-19-ホシノ" = "ん～？#nどうしてこんな遠くまでパトロールするのかって？"
"1009803-20-ホシノ" = "そりゃ、先生を疲れさせるためかな。#nおじさんに変なこと言う体力がなくなるようにね。"
"1009803-21" = "[s] \"そうだったの！？\""
"1009803-22-ホシノ" = "冗談だよ、冗談。#n先生はリアクションが良いね。"
"1009803-23-ホシノ" = "本当は、この間のトラブルが気になったんだ。"
"1009803-24-ホシノ" = "ヘルメット団が学校の掲示板を盗もうとしてたでしょ？"
"1009803-25" = "[s] \"あの時のホシノ、本当にカッコ良かったよ！\""
"1009803-26-ホシノ" = "……それは置いといて、やけに良い装備をしてなかった？"
"1009803-27-ホシノ" = "いつもは大したことなかったのに……。"
"1009803-28-ホシノ" = "それで今日は遠くまでパトロールしようと思ったんだ。"
"1009803-29-ホシノ" = "先生も怪しいと思わなかった？"
"1009803-30" = "[s] \"たしかに、言われてみれば……。\""
"1009803-31-ホシノ" = "そうでしょ？#nじゃ、早く行こっか。"
"1009803-41-ホシノ" = "あれ？#nあの家、前に見た時は何ともなかったのに……。"
"1009803-42" = "[s] \"完全に埋れてるね。\""
"1009803-43-ホシノ" = "最近、砂嵐が多いからかな……。"
"1009803-48-？？？" = "はぁ。#nやっぱり、一人じゃ無理だ……。"
"1009803-55-市民" = "……仕方ない、もう諦めるとするか。"
"1009803-60-ホシノ" = "何か困ってるなら手伝おうか？"
"1009803-61-市民" = "……君は？"
"1009803-62-ホシノ" = "あ～、ただの通りすがりの生――"
"1009803-63" = "[s] \"通りすがりのヒーローです。\""
"1009803-67-ホシノ" = "ちょっ、先生……！"
"1009803-68-市民" = "……ヒーロー？"
"1009803-69-市民" = "よく分からないけど、手伝ってくれるなら助かるよ。"
"1009803-70-市民" = "ここには昔、住んでいてね。#n探しものがあって久しぶりに来たんだ。"
"1009803-71-市民" = "でも砂嵐のせいか、この有り様で……。"
"1009803-72-市民" = "砂をいくら退かしたところで、キリがないんだ。"
"1009803-74-ホシノ" = "たしかに、この量を一人で何とかするのは……。"
"1009803-78-ホシノ" = "んじゃ、ここはおじさんが一肌脱ごうかな。"
"1009803-79" = "[s] \"私も手伝うね。\""
"1009803-80-ホシノ" = "うへへ。ありがとう、先生。"
"1009803-88-ホシノ" = "ふぅ、これで大丈夫そうだね。"
"1009803-89-市民" = "す、すごい！#nあんな大量にあった砂が……！"
"1009803-91-市民" = "ありがとう、アビドスのヒーロー！"
"1009803-95-ホシノ" = "まったく、先生が余計なこと言うから……。"
"1009803-96" = "[s1] \"困っている人がいたら見過ごせない……。\"\n[s2] \"それが、ヒーローだよね。\""
"1009803-99-ホシノ" = "う、うへぇ～。"
"1009803-100-ホシノ" = "ほんと、先生は平気でそういうこと言うんだから……。"
"1009803-102" = "（その後も、ホシノと一緒にアビドス自治区のパトロールを続けた）"
"1009803-106-ホシノ" = "うーん。#nたしか、ここは通行路だったはずなのに。"
"1009803-107-ホシノ" = "いつの間にか、砂に埋もれちゃってるね。"
"1009803-108" = "[s] \"迂回する？\""
"1009803-109-ホシノ" = "……。"
"1009803-110-ホシノ" = "ん～。"
"1009803-111-ホシノ" = "せっかくだし、ここの砂も退かしちゃおっか。"
"1009803-117-ホシノ" = "うわぁ、砂埃で街灯がすごい汚れてるねぇ。"
"1009803-121-ホシノ" = "先生、そこに登ってから肩車してもらえる？"
"1009803-122-ホシノ" = "これじゃ、暗くなった時に困るしね。"
"1009803-137-ホシノ" = "うへ～。#nいつの間にか、こんなところまで来ちゃったね。"
"1009803-138" = "[s] \"いったん休憩しよっか。\""
"1009803-139-ホシノ" = "そうだね、ずっと動きっぱなしだったし。"
"1009803-140-ホシノ" = "……ねぇ先生。#nおじさんと一緒に来たこと、後悔してない？"
"1009803-141" = "[s] \"まったくしてないよ。\""
"1009803-143" = "[ns] \"アビドスを思うホシノの気持ちが、伝わってきたからね。\""
"1009803-144-ホシノ" = "うへ～、照れるねぇ。"
"1009803-145-ホシノ" = "でもおじさんが頑張れたのは、先生のおかげだよ。"
"1009803-146-ホシノ" = "私だけだったら、途中でバテちゃってたかも。"
"1009803-147-ホシノ" = "……だから、ありがとう先生。"
"1009803-148-ホシノ" = "うん？#nヒーローの役に立てて嬉しい、って？"
"1009803-149-ホシノ" = "ひ、ヒーローっていう設定、まだ続いてるんだ。"
"1009803-150-ホシノ" = "ま、おじさんがヒーローだとしたら……。"
"1009803-151-ホシノ" = "先生は「相棒」で良いんだよね？"
"1009803-152" = "[s] \"相棒？\""
"1009803-153-ホシノ" = "ヒーローと一緒に戦う存在だよ。"
"1009803-154-ホシノ" = "まぁ、悪役にやられて、#nヒーローが覚醒するきっかけになるのが定番だけどね。"
"1009803-155" = "[s] \"！？\""
"1009803-156-ホシノ" = "うへへ。冗談だよ、冗談。"
"1009803-160-ホシノ" = "とりあえず、これでも食べる？"
"1009803-161-ホシノ" = "ポケットに入れてたせいで、グチャってなってるけど……。"
"1009803-166-？？？" = "あ、あのぉ……。"
"1009803-174-アビドス市民A" = "噂に聞いたんですが、#nあなたが最近この辺りで人助けをしているヒーローの方ですか？"
"1009803-175-ホシノ" = "えぇ！？"
"1009803-176" = "[s] \"噂が広がってるんだ……。\""
"1009803-180-ホシノ" = "たぶん、その人で合ってると思うけど……。"
"1009803-181-ホシノ" = "何か頼み事でもあるの？"
"1009803-182-アビドス市民A" = "……忘れ物を探してほしいんです。"
"1009803-183-アビドス市民A" = "この前、郊外を散歩していたら砂嵐に遭いまして。"
"1009803-184-アビドス市民A" = "そこで放置されていた車両に身を隠した時までは、#n持っていたはずなんです。"
"1009803-185-アビドス市民A" = "探しに行こうにも、砂漠の中なので場所が分からず……。"
"1009803-187-アビドス市民A" = "大切な物なんです！#n必ずお礼をしますので、どうかお願いします！"
"1009803-193-ホシノ" = "仕方ないかぁ。"
"1009803-194-ホシノ" = "わざわざ探してくれたんだし、ちょうどパトロール中だしね。"
"1009803-195-ホシノ" = "先生も、それで良い？"
"1009803-196" = "[s] \"もちろん、相棒も付いていくよ！\""
"1009803-197-ホシノ" = "うへへ、元気いっぱいだね。"
"1009803-198-ホシノ" = "じゃあ、ざっくりとした方向で良いから教えてもらえるかな？"
"1009803-199-アビドス市民A" = "はい！"
"1009803-200-アビドス市民A" = "えっと、背中に朝日を浴びながら、町に戻っていたはずなので……。"
"1009803-201-ホシノ" = "それじゃ、東のほうだね。"
"1009803-205-ホシノ" = "行こうか、先生。"
"1009803-207" = "（忘れ物を探すため、ホシノと一緒にアビドスの郊外へ向かった）"
"1009803-216-ホシノ" = "うへ～、たぶんこれじゃないかな？"
"1009803-220-ホシノ" = "無事に見つかったし、あとは持ち主に返すだけだね。"
"1009803-221-ホシノ" = "先生もお疲れ様～。"
"1009803-222" = "[s] \"ホシノもお疲れ様。\""
"1009803-226-ホシノ" = "うへへ。"
"1009803-227-ホシノ" = "でも、ちょっと困ったね。"
"1009803-228-ホシノ" = "ほら……。"
"1009803-237" = "[ns] \"あ、もうこんな時間だったんだ……。\""
"1009803-238-ホシノ" = "そうなんだよねぇ。"
"1009803-239-ホシノ" = "移動途中で完全に日が落ちたら、迷うかもしれないし……。"
"1009803-240-ホシノ" = "……仕方ない。"
"1009803-241-ホシノ" = "今日はここで一晩過ごそっか。"
"1009803-242-ホシノ" = "先生も休も～。"
"1009803-249" = "[wa:660]― [log=호시노 무장 모드 4]いやー[wa:1210]もうこんな時間になっちゃったかぁ。[/log]"
"1009803-250" = "[wa:3320]― [log=호시노 무장 모드 4]こうなったら、[wa:980]朝まで待つしかないねぇ。[/log]"
"1009803-253" = "[ns] \"ホシノと一緒だったら、待ってる時間も楽しいよ。\""
"1009803-254" = "[wa:470]― [log=호시노 무장 모드 4]……へ？[/log]"
"1009803-255" = "[wa:2020]― [log=호시노 무장 모드 4]またまたぁ～[wa:1840]こんなおじさんといたって、[wa:1240]別に楽しくないでしょ～[/log]"
"1009803-258" = "[ns] \"ううん。だって、ホシノはヒーローだからね。\""
"1009803-259" = "[wa:550]― [log=호시노 무장 모드 4]う、[wa:380]うへぇ～……[/log]"
"1009803-260" = "[wa:1970]― [log=호시노 무장 모드 4]その設定、[wa:680]まだやるの……？[wa:1830]おじさんにはちょっと[wa:640]荷が重いかも～[/log]"
"1009803-263" = "[wa:1170]― [log=호시노 무장 모드 4]……[wa:740]まあ、[wa:690]先生が相棒役を買って[wa:1380]出てくれるのなら、[/log]"
"1009803-264" = "[wa:1030]― [log=호시노 무장 모드 4]合わせるけどさぁ。[/log]"
"1009803-267" = "[wa:280]― [log=호시노 무장 모드 4]んじゃ、[wa:600]ヒーローと相棒の[wa:800]質素な夕食にしよっか。[wa:2260]……非常食だけど。[/log]"
"1009803-270" = "[ns] \"これって、小さい子に人気のグミだよね？\""
"1009803-271" = "[wa:1270]― [log=호시노 무장 모드 4]それは、[wa:1320]そうだけどさぁ～……[/log]"
"1009803-272" = "[wa:5360]― [log=호시노 무장 모드 4]おじさんはこれが好きなんだ。[wa:2270]大目にみてよ～[/log]"
"1009803-276-ホシノ" = "うへへ。#nポケットに入れっぱなしだったみたい。"
"1009803-277-ホシノ" = "まあ、味は変わらないから安心して。"
"1009803-278-ホシノ" = "これで、とりあえず今晩は何とかなりそうだね。"
"1009803-279" = "[s] \"ホシノは、こういうことに慣れてるの？\""
"1009803-283-ホシノ" = "それなりじゃない？"
"1009803-284-ホシノ" = "おじさんは屋根がない場所でも野営してきたからね。"
"1009803-285-ホシノ" = "それと比べたら、ここは随分と快適じゃないかな？#n良かったねぇ、先生。"
"1009803-286" = "[s] \"そのセリフは、本当におじさんっぽいような……。\""
"1009803-287-ホシノ" = "ええっ……。"
"1009803-288-ホシノ" = "ま、まぁ、とにかく寝る準備しよっか。"
"1009803-293-ホシノ" = "その辺の枯れ木を集めて火をつければ……"
"1009803-301-ホシノ" = "うへ～、温かいね。"
"1009803-302-ホシノ" = "非常用毛布を敷けば、寝床の完成だよ。"
"1009803-303-ホシノ" = "夜の砂漠は冷えるし、体温を維持しないとね。"
"1009803-304-ホシノ" = "まだ眠くないなら、#nしばらく列車にもたれかかりながら話でもしようか？"
"1009803-305-ホシノ" = "……おじさんはどこで寝るのかって？"
"1009803-306-ホシノ" = "気にしなくて平気平気。"
"1009803-307-ホシノ" = "おじさんはどこでも寝られるからね～。"
"1009803-308" = "[s] \"ホシノもこっちにおいでよ。\""
"1009803-312-ホシノ" = "えっ。#nいやいや、それはさすがに……。"
"1009803-313" = "[s3] \"体温維持は大切なんでしょ？\"\n[s4] \"二人で毛布に包まれば、温かいと思うよ。\""
"1009803-318-ホシノ" = "うへぇ、たしかにそうだけど……。"
"1009803-319-ホシノ" = "……はぁ。"
"1009803-320-ホシノ" = "やっぱり先生って、平気でそういうこと言うよね。"
"1009803-326-ホシノ" = "……まあ、お言葉に甘えてちょっとだけご一緒させてもらおうかな。"
"1009803-328" = "（こうしてホシノと同じ毛布で、陽が昇るまで休憩した）"
