[translation]
"212020-1" = "第2話;チナツ"
"212020-3-チナツ" = "ほとんどの3年生が影響を受けている……委員長やアコ行政官のように……。"
"212020-4-チナツ" = "それなら、もしかすると……。"
"212020-5-チナツ" = "……確かめなければ。"
"212020-20-チナツ" = "セナ先輩、おはようございます。"
"212020-24-セナ" = "チナツ。"
"212020-25-セナ" = "久しぶりですね。"
"212020-26-チナツ" = "ご無沙汰になってしまい、すみません。"
"212020-27-セナ" = "忙しさは分かっています。こちらも似たようなものですよ。"
"212020-28-チナツ" = "そう、ですか……。"
"212020-33-チナツ" = "……救急医学部も、戦いの準備をしているんですね。"
"212020-34-セナ" = "もちろんです。"
"212020-35-セナ" = "これこそ、私たち全員の宿願ですから。"
"212020-36-チナツ" = "宿願……？"
"212020-37-セナ" = "……チナツも、そうでしょう？"
"212020-41-セナ" = "風紀委員会の力をゲヘナの外に示す時が来たのです。"
"212020-42-チナツ" = "私は……。"
"212020-43-セナ" = "チナツ。私は覚えています。"
"212020-44-チナツ" = "何を……ですか？"
"212020-45-セナ" = "チナツが風紀委員会へ行くと言った時のことです。"
"212020-46-チナツ" = "そ、それは……。"
"212020-47-セナ" = "理由は、「放っておけなくて」でしたよね。"
"212020-48-チナツ" = "そんなことまで……。"
"212020-49-セナ" = "もちろんです。チナツのことですから。"
"212020-53-チナツ" = "……はい？"
"212020-54-セナ" = "期待していましたから。#nいずれ、部長を任せられるかもしれない、と。"
"212020-55-チナツ" = "今まではそんな話、一度も……。"
"212020-56-セナ" = "それはそうでしょう。いま初めて言いましたから。"
"212020-57-チナツ" = "先輩がそこまで評価してくださっていただなんて……。"
"212020-58-セナ" = "だからこそ……部を移ると聞かされた時は衝撃を受けました。#n表に出さないよう取り繕ってはいましたが。"
"212020-59-チナツ" = "……。"
"212020-63-セナ" = "[ruby=ここ]救急医学部[/ruby]では望みを叶えてあげられなかったのだろうか？"
"212020-64-セナ" = "私たちに問題があったのだろうか？#nだとしたら、どうすれば解決できたのだろうか。"
"212020-65-セナ" = "当時は、そんなことをずいぶんと考えました。"
"212020-66-チナツ" = "そ、そんな……。"
"212020-67-チナツ" = "不満があったから部を移ろうとしたのではなくて……。"
"212020-68-チナツ" = "負傷者が出るたび、もっと早く対処できる方法を考えているうちに……。"
"212020-69-セナ" = "ふふ。#n……ええ、分かっています。"
"212020-70-チナツ" = "セナ先輩……。"
"212020-71-セナ" = "[ruby=・]私[/ruby][ruby=・]た[/ruby][ruby=・]ち[/ruby]では、チナツに最良な場所にはなれなかった。"
"212020-72-セナ" = "いろいろ理由はあるでしょう。ですが、あえて言葉にするような話でもありません。"
"212020-73-セナ" = "私たちは選択をし、それぞれの場所を得て。#nそして今、ここにいるのですから。"
"212020-74-セナ" = "私はチナツを誇りに思います。"
"212020-78-チナツ" = "……ありがとうございます。"
"212020-79-チナツ" = "ここで私が「申し訳ない」と言うのは……先輩に対する侮辱なのでしょうね。"
"212020-80-チナツ" = "先輩はいつだって最善を尽くして、自分にできることを懸命にやってきました。"
"212020-81-チナツ" = "私だって先輩を尊敬してきましたし、今も変わりません。"
"212020-82-セナ" = "私は良い後輩を持ちましたね。"
"212020-83-セナ" = "だから――"
"212020-89-セナ" = "これからも、どうぞよろしくお願いします。"
"212020-90-セナ" = "名実ともにゲヘナ最強の武力集団。風紀委員会の役割は大きいのですから。"
"212020-91-セナ" = "なにせ戦闘の継続は、チナツの働きにかかっています。"
"212020-92-セナ" = "風紀委員長も、チナツに期待しているでしょう。"
"212020-93-チナツ" = "先輩……。"
"212020-94-セナ" = "……不安ですか？"
"212020-98-チナツ" = "いえ……そうではなくて……。"
"212020-99-セナ" = "応急処置、簡易手術、患者の搬送、緊急時の対応と補給。#nどれも救急医学部で教えたことです。"
"212020-100-セナ" = "今はそこに、チナツ自身の経験も加わっている。"
"212020-101-セナ" = "ですから、私は心配していません。"
"212020-102-セナ" = "チナツを信じています。"
"212020-103-チナツ" = "…………。"
"212020-104-チナツ" = "セナ先輩。"
"212020-105-セナ" = "はい。"
"212020-106-チナツ" = "もしもゲヘナがキヴォトスを破壊するとして……。"
"212020-107-チナツ" = "それは……先輩が望むことなんですか？"
"212020-108-チナツ" = "先輩は、そんなゲヘナを誇れるんですか……？"
"212020-109-セナ" = "……偉大さには、犠牲が伴うものです。"
"212020-110-チナツ" = "きっと多くの負傷者が出ます。"
"212020-111-チナツ" = "ゲヘナだけじゃない。多くの市民まで傷つき、苦しむはずです。"
"212020-112-チナツ" = "先輩は……本当にそんなことを望んでいるんですか？"
"212020-116-セナ" = "そうですね……。"
"212020-117-チナツ" = "……。"
"212020-118-セナ" = "私個人としては、そういった事は好みません。"
"212020-119-セナ" = "ですが、個人の好き嫌いを越えて、[ruby=・]必[/ruby][ruby=・]要[/ruby][ruby=・]な[/ruby][ruby=・]こ[/ruby][ruby=・]と[/ruby]だと理解しています。"
"212020-120-チナツ" = "攻撃を行うことが、ですか？"
"212020-121-セナ" = "ええ。キヴォトスに対する医療行為ですから。"
"212020-122-チナツ" = "言っている意味が分かりません。"
"212020-123-セナ" = "キヴォトスは、乱立した学園秩序の上に成り立っています。#nこれを救急患者と呼ばずして何と呼びましょう。"
"212020-124-セナ" = "ゲヘナによる統一。#nそして強力な秩序の確立こそが、キヴォトスを治療する唯一の方法なのです。"
"212020-125-セナ" = "先ほど、負傷者の話をしましたね。それは手術中に起こる出血と同じです。"
"212020-126-セナ" = "出血が怖いからと手術を諦めれば、患者は取り返しのつかないことになる。#nチナツなら分かっていますよね？"
"212020-130-セナ" = "……よほど悩んでいるようですね。"
"212020-131-チナツ" = "先輩……。"
"212020-132-セナ" = "……。"
"212020-133-セナ" = "薬品整理が途中でした。"
"212020-134-セナ" = "今日のところはこれくらいで。……また次の機会に。"
"212020-135-チナツ" = "……はい。また伺います。"
"212020-141-セナ" = "チナツ。"
"212020-145-チナツ" = "はい？"
"212020-149-セナ" = "どうか、正しい道へ進めるよう願っています。"
"212020-153-チナツ" = "……ありがとうございます。"
"212020-155-チナツ" = "セナ先輩……。"
"212020-156-チナツ" = "私を信じてくださる、澄んだ瞳。あの目は変わっていないのに。"
"212020-160-チナツ" = "なのに……。"
"212020-162-チナツ" = "必ず……元に戻してみせます。"
"212020-164" = "次回;ゲヘナ再興委員会の反応"
