[translation]
"1010403-1" = "面倒見"
"1010403-2" = "玄武商会本店"
"1010403-4-レイジョ" = "お口に合いましたか、先生。"
"1010403-5" = "[s1] \"最高だったよ！\"\n[s2] \"今度はレイジョの料理も食べてみたいな。\""
"1010403-6-レイジョ" = "でしたら良かったです。"
"1010403-7-レイジョ" = "ぜひ、またいつでもお越しください"
"1010403-8-レイジョ" = "……私の料理、ですか？"
"1010403-9-レイジョ" = "たしかに、普段は会長の補佐をしていますが……。"
"1010403-10-レイジョ" = "いつか、先生に料理を振る舞うのも悪くありませんね。"
"1010403-15-玄武商会のメンバー" = "レイジョさん、食材が届いていない店舗があるようです！"
"1010403-16-レイジョ" = "む、どこのお店ですか？"
"1010403-17-玄武商会のメンバー" = "京華坊です！"
"1010403-18-レイジョ" = "……なるほど。"
"1010403-19-玄武商会のメンバー" = "ど、どうすれば？#nこのままではお昼の営業が……！"
"1010403-20-レイジョ" = "ひとまず、本店の倉庫から一部の食材を搬入しましょう。"
"1010403-21-レイジョ" = "それで数時間は持ち堪えられるはずです。"
"1010403-22-レイジョ" = "あとは虹正路3番街の天興楼からも、回してもらいましょうか。#nトラックを二台、飛ばしてください。"
"1010403-23-レイジョ" = "連絡は私が入れておきます。"
"1010403-24-レイジョ" = "食材の費用は、営業終了後に計算して報告してください。"
"1010403-25-玄武商会のメンバー" = "はい、分かりました！"
"1010403-27-レイジョ" = "ふぅ、何とかなりそうですね。"
"1010403-31-食堂の客" = "ここが噂の玄武商会……。"
"1010403-32-食堂の客" = "お～い、一番美味い料理を持ってきてくれ！"
"1010403-35-玄武商会のメンバー" = "えっと、それは……。"
"1010403-40-レイジョ" = "まずは席にご案内します、こちらへどうぞ。"
"1010403-42-レイジョ" = "ご来店ありがとうございます。"
"1010403-43-レイジョ" = "料理長のオススメ料理があるのですが、いかがでしょうか？"
"1010403-44-食堂の客" = "おお、そんなメニューが？"
"1010403-45-レイジョ" = "通常はお出ししていませんが、お客様には特別です。"
"1010403-46-玄武商会のメンバー" = "わ、私も初めて聞きましたが……。"
"1010403-47-レイジョ" = "……大丈夫です、合わせてください。"
"1010403-49-食堂の客" = "何か問題でも？"
"1010403-50-レイジョ" = "いえ、食材の在庫を確認したところ、問題なさそうです。#nでは、アワビ料理をコースでお出しします。"
"1010403-51-食堂の客" = "そいつは楽しみだ！"
"1010403-53-玄武商会のメンバー" = "ほ、本当に大丈夫ですか！？"
"1010403-54-レイジョ" = "一番美味しい料理、と言っていましたから。"
"1010403-55-レイジョ" = "それに、安い料理を出すと逆に腹を立てる方もいますし。"
"1010403-56-レイジョ" = "それでは、お客様……失礼いたします。"
"1010403-57-レイジョ" = "至急、厨房に伝えてください。"
"1010403-59-玄武商会のメンバー" = "はい、分かりました！"
"1010403-64-レイジョ" = "まったく……今日に限って、どうしてこう忙しいのか。"
"1010403-68-？？？" = "私は確かに支払いましたよ！"
"1010403-74-玄武商会のメンバー" = "ですが……。"
"1010403-75-食堂の客B" = "二重にお金を取るつもりだろう！？"
"1010403-82-レイジョ" = "どうされましたか、お客様？"
"1010403-83-食堂の客B" = "アプリで支払ったのに、決済できてないと言いがかりをつけてきたんだ！"
"1010403-84-食堂の客B" = "これが玄武商会のやり口か！"
"1010403-85-玄武商会のメンバー" = "いえ、お客様……。"
"1010403-87-レイジョ" = "私たちにミスがあったのなら、きちんとお詫びします。"
"1010403-88-レイジョ" = "ですが、その前にアプリの支払履歴と防犯カメラを確認してもよろしいでしょうか？"
"1010403-89-レイジョ" = "[ruby=・   ・   ・]手違い[/ruby]があってはいけませんから。"
"1010403-90-食堂の客B" = "なっ……。"
"1010403-91-レイジョ" = "明細なら、すぐお出ししていただけるかと。"
"1010403-92-レイジョ" = "監視カメラの映像も5分ほど時間を頂ければ、確認が終わるはずです。"
"1010403-96-食堂の客B" = "え～っと、たしかアレだ……ちゃんと支払えてなかったような気もするな。"
"1010403-97-食堂の客B" = "だ、だから監視カメラまで確認する必要は……。"
"1010403-98-レイジョ" = "いえ、誤りがあってはいけませんから。"
"1010403-99-レイジョ" = "それと……当然ですが、この会話もカメラで記録されています。"
"1010403-100-食堂の客B" = "ろ、録音だと！？"
"1010403-101-レイジョ" = "お客様、顔色が……どこか具合でも悪いのでしょうか？"
"1010403-102-食堂の客B" = "大丈夫だ、何でもないっ！"
"1010403-104-レイジョ" = "お騒がせして申し訳ありません、先生。"
"1010403-105" = "[s] \"手際が良くて驚いたよ。\""
"1010403-106-レイジョ" = "きゅ、急に褒めてどうされました？"
"1010403-107-レイジョ" = "もちろん、そう言っていただけるのは嬉しいのですが……。"
"1010403-108-レイジョ" = "この程度の問題は、よくありますから。"
"1010403-109-レイジョ" = "……ただ今日は、なぜかトラブルが多かったような気もしますね。"
"1010403-110-レイジョ" = "まだ大事なイベントは始まっていないというのに……。"
"1010403-111" = "[s] \"まだ何かあるの？\""
"1010403-112-レイジョ" = "その、実は……。"
"1010403-113-レイジョ" = "……このあと、梅花園の園児が団体で来る予定なんです。"
"1010403-114-レイジョ" = "自分で言うのも恥ずかしい限りですが……。"
"1010403-115-レイジョ" = "どのように子どもと接して良いのか分からず……。"
"1010403-116" = "[s] \"なかなか正解は見つからないよね。\""
"1010403-117-レイジョ" = "先生でもそうでしたか。"
"1010403-118-レイジョ" = "小さい子は可愛くて純粋ですが、#nその分、何が起こるか分からないですし……。"
"1010403-119-レイジョ" = "……えっ。#n先生も手伝ってくださるんですか？"
"1010403-120-レイジョ" = "なるほど……ここは素直に甘えさせていただきます。"
"1010403-121-レイジョ" = "ありがとうございます、先生。"
"1010403-123-梅花園の園児A" = "せんせー、このイカ、お花みたい！"
"1010403-124" = "[s] \"すごい不思議だね。\""
"1010403-125-梅花園の園児B" = "タコさんウィンナーってなにー？"
"1010403-126-梅花園の園児B" = "タコさんなの？ウィンナーなの？"
"1010403-127" = "[s] \"タコの形をしてるウィンナーだよ。\""
"1010403-128-梅花園の園児B" = "なら食べてみたい！"
"1010403-129-梅花園の園児B" = "この前ね、梅花園でね、ブロッコリーピーマンチャーハンが出てきて――"
"1010403-133-レイジョ" = "先生は子どもたちの対応に慣れているんですね……。"
"1010403-134-レイジョ" = "よろしければ、コツを聞いてもよろしいでしょうか？"
"1010403-135" = "[s3] \"コツってほどじゃないけど……。\"\n[s4] \"なにも問題を解決する必要はないんじゃないかな。\""
"1010403-138-レイジョ" = "あえて問題を解決しない、と……？"
"1010403-139-レイジョ" = "……たしかに、相談事でも聞くだけで良い場合はありますね。"
"1010403-140-レイジョ" = "参考になりました、先生。"
"1010403-141" = "[s] \"レイジョもやってみる？\""
"1010403-145-レイジョ" = "……はい、もとより、自分の仕事ですから。"
"1010403-151-梅花園の園児C" = "エビ餃子好きー！"
"1010403-152-梅花園の園児C" = "けど豚まんも好き！"
"1010403-153-梅花園の園児C" = "あとはー、焼き餃子も揚餃子も好きー！#nなんかいっぱい具が入ってる餃子も！"
"1010403-154-レイジョ" = "いろんな餃子が好きなんですね。"
"1010403-155-梅花園の園児C" = "あっ。でも、ワカメ餃子は嫌い……。"
"1010403-156-レイジョ" = "そ、それは餃子なんでしょうか……？"
"1010403-160-梅花園の園児D" = "……外食文化が広がるのは胸が痛みます。#nそれほどまでに、料理をする時間がなくなってしまったという証左なのです。"
"1010403-161-梅花園の園児D" = "時間の節約のために外食をしますが、そうして浮かせた時間を仕事のために使ってしまうのですから……。"
"1010403-162-梅花園の園児D" = "経営者だとしてもこの問題からは逃れられません……システム上どうしてもそうなってしまっているから……。"
"1010403-163-レイジョ" = "その、どうかしましたか……？"
"1010403-164-梅花園の園児D" = "いえ……何も問題がないことが、とても悲しいのです。"
"1010403-166-レイジョ" = "……無事、終わりましたね。"
"1010403-167-レイジョ" = "子どもたちにしがみつかれたり、#nお店でかくれんぼが始まろうとした時は戸惑いましたが……。"
"1010403-168" = "[s] \"それだけ仲良くなれたってことじゃないかな。\""
"1010403-169-レイジョ" = "……はい、また遊びにきたい、と言っていました。"
"1010403-170-レイジョ" = "何度聞いても、「また」と言ってもらえるのは嬉しいですね。"
"1010403-174-レイジョ" = "とても不思議な経験でした。"
"1010403-175-レイジョ" = "ありがとうございます。先生。"
"1010403-176" = "[s] \"私は特に何もしてないよ。\""
"1010403-177-レイジョ" = "先生にとっては、そうかもしれませんが……とても、助かりました。"
"1010403-178-レイジョ" = "これからも、ご指導をよろしくお願いいたします。"
