[translation]
"1010406-1" = "主体と客体"
"1010406-2" = "シャーレ・オフィス"
"1010406-5" = "[ns] \"レイジョ、ごめん！\""
"1010406-6-レイジョ" = "どうされましたか、先生？"
"1010406-7" = "[s] \"それが、その……。\""
"1010406-8-レイジョ" = "……なるほど、急に外回りの仕事が入ったのですね。"
"1010406-9-レイジョ" = "せっかく来てくれたのに、置き去りにするのが申し訳ない、と。"
"1010406-10-レイジョ" = "分かりました。"
"1010406-11-レイジョ" = "でしたら、私も一緒に行きましょう。"
"1010406-12" = "[s] \"良いの……？\""
"1010406-13-レイジョ" = "もちろんです。"
"1010406-14-レイジョ" = "今日の私は、シャーレ当番ですから。"
"1010406-15-レイジョ" = "先生の仕事を手伝うのは、当たり前でしょう。"
"1010406-16-レイジョ" = "それでは……。"
"1010406-17-レイジョ" = "今日一日、先生の護衛はお任せください。"
"1010406-29" = "[ns] \"やっと終わった……。\""
"1010406-30-レイジョ" = "お疲れ様でした、先生。"
"1010406-31-レイジョ" = "シャーレの仕事は、本当に様々なのですね。"
"1010406-32-レイジョ" = "……なるほど。"
"1010406-33-レイジョ" = "どれだけ忙しくても、生徒のために頑張る、と……。"
"1010406-34-レイジョ" = "……先生は、武道についてどう思っていますか？"
"1010406-35-レイジョ" = "急な話で困惑させてしまい、申し訳ありません。"
"1010406-36-レイジョ" = "ですが、私はこう思うのです。#n武道とは、自分を見つめ直すためのものだと。"
"1010406-37-レイジョ" = "体を鍛えることで、精神的にも成長できるはずですから。"
"1010406-38" = "[s] \"そうだね。\""
"1010406-39-レイジョ" = "そして、武道に身を置く一人として……。"
"1010406-40-レイジョ" = "強き者は弱き者を守り、使命を果たす必要があると思います。"
"1010406-41-レイジョ" = "これは，玄龍門が掲げている義と侠に通じているかもしれませんね。"
"1010406-42" = "[s] \"たしかに……。\""
"1010406-43-レイジョ" = "ですから……。"
"1010406-44-レイジョ" = "先生には、私を守る義務があります。"
"1010406-45" = "[s] \"たしかに……って、なんで！？\""
"1010406-46-レイジョ" = "先生は、大人でもあり教育者でもありますから。"
"1010406-47-レイジョ" = "どれだけ忙しくても、生徒のために頑張ると言っていましたし。"
"1010406-48" = "[s1] \"それは、その……！\"\n[s2] \"もちろん、放ってはおけないけど……！"
"1010406-51-レイジョ" = "そう言ってくださると思っていました。"
"1010406-52-レイジョ" = "では、今日一日、先生に守っていただきましょう。"
"1010406-54-？？？" = "……あん？#nお前、プルプル派の連中だろ？"
"1010406-59-チンピラ２" = "誰かと思ったら、プニプニ派じゃねぇか！#nなんか文句あんのか？"
"1010406-60-チンピラ１" = "なんも言ってねーだろ、あぁ！？"
"1010406-61-チンピラ２" = "そっちが最初に突っかかってきたんだろうが！#nぐだぐだプニプニうるせえなぁ！！"
"1010406-67-レイジョ" = "先生……！"
"1010406-68" = "[s3] \"こういう時は……！\"\n[s4] \"とりあえず、逃げよう！\""
"1010406-73-レイジョ" = "先生の判断のおかげで、何とか巻き込まれずに済みましたね。"
"1010406-78-レイジョ" = "どんどん激しくなっているようですが……。"
"1010406-79-レイジョ" = "……先生。"
"1010406-80-レイジョ" = "私を守ってくれるのではなかったのですか？"
"1010406-81" = "[s] \"よく聞いて、レイジョ――\""
"1010406-82-レイジョ" = "……なるほど。"
"1010406-83-レイジョ" = "必ずしも守る方法はひとつではない、と。"
"1010406-84-レイジョ" = "水の流れに逆らわず、待つことも大事なのですね。"
"1010406-85-レイジョ" = "これが、先生の強さ……。"
"1010406-86-レイジョ" = "……よく分かりました。"
"1010406-87-レイジョ" = "私も、ここは流れに身を任せてみようと思います。"
"1010406-92" = "[ns] \"れ、レイジョ！？\""
"1010406-93-レイジョ" = "どうしましたか、先生？"
"1010406-94-レイジョ" = "こうして体をくっつけていたほうが、#n見つかる可能性を下げられるかと。"
"1010406-95" = "[s] \"それは、そうなんだけど……。\""
"1010406-96-レイジョ" = "でしょう？"
"1010406-97-レイジョ" = "……落ち着いてきましたね。"
"1010406-98-レイジョ" = "何だか、先生に守られている実感が湧いてきました。"
"1010406-105-レイジョ" = "……まだ辺りは騒がしいですが。"
"1010406-106-レイジョ" = "先生と一緒だからでしょうか。"
"1010406-107-レイジョ" = "こういう時間も、悪くありません。"
"1010406-110" = "（銃撃戦は、その後も続いたが……）"
"1010406-111" = "（しばらくしてヴァルキューレ警察学校がやって来ると、事態は収束した）"
"1010406-113-レイジョ" = "もう、こんな時間になってしまいましたね……。"
"1010406-114" = "[s] \"仕事は終わってるから安心して。\""
"1010406-115-レイジョ" = "ですが……。"
"1010406-116-レイジョ" = "申し訳ありません、先生。"
"1010406-117-レイジョ" = "私がワガママを言ったせいで……。"
"1010406-118-レイジョ" = "……先生の時間を奪ってしまいました。"
"1010406-119-レイジョ" = "ただ、一度くらい守られる側になってみたかったのです。"
"1010406-120" = "[s] \"大丈夫だよ、レイジョ。\""
"1010406-121-レイジョ" = "しかし……。"
"1010406-122" = "[s5] \"今日は、まだ終わってないから！\"\n[s6] \"山海経に着くまで守ってあげる！\""
"1010406-125-レイジョ" = "……。"
"1010406-126-レイジョ" = "そうですね……。"
"1010406-127-レイジョ" = "では、お言葉に甘えて……。"
"1010406-133" = "（突然、体を寄せてきたレイジョに戸惑っていると……）"
"1010406-134" = "（遠慮がちに体重を預けながら、腕を絡めてきた）"
"1010406-137" = "[ns] \"れ、レイジョ？\""
"1010406-138-レイジョ" = "先生……？"
"1010406-139-レイジョ" = "私を守ってくれるのではありませんでしたか？"
"1010406-140-レイジョ" = "……今日が終わるまでは。"
"1010406-142" = "（この日の帰り道は……）"
"1010406-143" = "（なぜか、いつもより長く感じた）"
