[translation]
"10032030-1" = "第3話;怪しい奴ら"
"10032030-20-アル" = "……なっ！"
"10032030-24-アル" = "何なのよ、これぇーーー！！"
"10032030-26-ムツキ" = "あはははは！アルちゃん、すっごくいい反応！"
"10032030-27-ムツキ" = "そんなの「怪しい奴ら」に決まってるじゃん？#n爆弾まで大量に見つかるなんて！"
"10032030-28-カヨコ" = "正確には「リストに載っていない身元不明の奴ら」ね。#nアランチーノ以外の勢力。"
"10032030-29-カヨコ" = "もしかすると、テロリストかライバル組織かもしれない。"
"10032030-30-カヨコ" = "……それより、軽く回った程度でこれだけの数が出てくるなんて、後どのくらい残ってるのやら……"
"10032030-31-アル" = "ど、ど、どうしてみんな落ち着いていられるの！？"
"10032030-32-アル" = "これだけのテロリストと爆弾が見つかったのよ！？#nどう考えてもおかしくない！？"
"10032030-33-アル" = "そもそもオペラハウスは劇を見る場所であって、誰かに危害を加えるための場所じゃないわよ！？"
"10032030-34" = "[s1] \"え、今さら……！？\"\n[s2] \"一応、自覚はあったんだね……\""
"10032030-37-アル" = "か、からかってる場合じゃないでしょ、先生！"
"10032030-38-アル" = "まずは、どうして爆弾なんて設置したのか聞き出さないと！！"
"10032030-39-工作員A" = "う、うっ……！どうして分かったんだ？#n完璧に隠していたはずなのに……！"
"10032030-40-工作員B" = "専門家でもなければ、発見できない位置だったのに……一体どうやって？"
"10032030-44-カヨコ" = "運が悪かったね、こっちにも爆弾の専門家が居るからさ。"
"10032030-45-ムツキ" = "ハルカちゃんは、普段から数えきれないほどの爆弾を設置してるからね。#n場所を特定するのなんて、朝飯前だよ？"
"10032030-46-ハルカ" = "へ、へへっ……えへへへっ……"
"10032030-47-ムツキ" = "むしろ、こっちは別に探すつもりじゃなかったのに、こんな見つかっちゃうなんて……#nちょっとツメが甘いんじゃない～？"
"10032030-53-工作員A" = "そ、そんなバカな……！"
"10032030-54-工作員B" = "私たちを邪魔するってことは……お前たち、アランチーノの部下か！？"
"10032030-60-カヨコ" = "どこ向いて喋ってるの？まずは、こっちの質問に答える。"
"10032030-61-工作員B" = "ひぃぃぃっ！？"
"10032030-62-工作員B" = "し、知らない！本当に！！#nただ、命令されたんだ……アランチーノを[ruby=や]殺[/ruby]れって……！"
"10032030-63-カヨコ" = "……なるほど。つまり依頼されたってことね？"
"10032030-64-カヨコ" = "でも、爆弾だと無関係な人まで巻き添えになる。それに爆音で周囲の目を集めてしまうでしょう。"
"10032030-65-カヨコ" = "なのに、爆弾を使う理由なんてある？方法なら他にも色々あるのに。"
"10032030-66-工作員B" = "使わない理由も無いだろ？#nこれが一番確実だと思っただけだ。"
"10032030-67-工作員B" = "それに無関係の人が巻き込まれたところで、私たちの知ったことじゃないからな！"
"10032030-72-カヨコ" = "……確実に始末したかったわけね。"
"10032030-73-カヨコ" = "……あんた達の他は？どれくらい残ってる？"
"10032030-74-工作員A" = "さ、さあ……詳しくは知らんが、それらしき奴は何人か……"
"10032030-78-工作員A" = "そ、そうか……！お前たちも依頼を引き受けたんだな！？"
"10032030-79-工作員A" = "き、急に襲いかかってきたから、アランチーノ側かと思ってたが……#n聞いてくれ、私たちは敵じゃない！"
"10032030-80-工作員A" = "だから離してくれ！#n……そ、そうだ！手を組もう！お前たちにとっても、悪くない話じゃないか？"
"10032030-81-工作員A" = "ここで揉めてたって意味は無いだろう……#nお、おい！そこの変なの、お前がリーダーだろ？何とか言ってくれよ！"
"10032030-82-工作員A" = "いいから、まずはこれを外し……"
"10032030-87-工作員A" = "はず、し……"
"10032030-93-工作員A" = "ひぐっ……！？"
"10032030-98" = "[ns4] \"……気絶しちゃった。\"\n[ns5] \"……容赦ないね。\""
"10032030-103-ハルカ" = "い……"
"10032030-104-ハルカ" = "今、なんて言いました……？"
"10032030-105-ハルカ" = "アル様に向かって「おい」……？「変なの」……？"
"10032030-106-ハルカ" = "お前なんかがアル様によくもそんな暴言を……"
"10032030-107-ハルカ" = "許せません……"
"10032030-108-ハルカ" = "許せません許せません許せません許せません許せません……！！"
"10032030-115-工作員B" = "ひ、ひぃぃぃっ！？！？わ、私は何も言ってないぞ！？"
"10032030-119-アル" = "……ハルカ、もういいわ。"
"10032030-120-ハルカ" = "……！！"
"10032030-121-ハルカ" = "……は、はいっ！"
"10032030-122-アル" = "状況は大体分かったわ。#n爆弾を仕掛けて、オペラハウスごと吹き飛ばそうって算段ね……"
"10032030-123-アル" = "たしかに面白い発想だわ……手っ取り早くもある。"
"10032030-125-工作員B" = "じゃ、じゃあ……！！"
"10032030-129-アル" = "……でも、残念だったわね。"
"10032030-130-アル" = "私たち便利屋68は、あなた達のような小物と手を組まないのよ。"
"10032030-134-工作員B" = "こ、小物だと……！？"
"10032030-135-工作員B" = "デカい口叩きやがって……！"
"10032030-136-工作員B" = "たかが私たちを捕まえたくらいで調子に乗るなよ！#nこのオペラハウスに、どれだけ集まってると思う！？"
"10032030-137-工作員B" = "もし仲間たちが知れば……！"
"10032030-139-カヨコ" = "……そうだね。"
"10032030-143-カヨコ" = "なら、その前に口を封じるだけ。"
"10032030-147-工作員B" = "うぐっ……！"
"10032030-154-カヨコ" = "……続けて、社長。"
"10032030-155-アル" = "……あっ、うん。"
"10032030-156-アル" = "みんな、聞いてちょうだい。#n……ドン・アランチーノは、私たちの獲物よ。"
"10032030-157-アル" = "他の連中に譲ることも、手を組むことも論外。#nこれは私たちの仕事なんだから。"
"10032030-158-アル" = "……ターゲットが現れる前に、もう一度オペラハウスを見て回りましょう。"
"10032030-164-ムツキ" = "え～全部調べるの？大変じゃない？"
"10032030-165-カヨコ" = "連絡係から貰ったリストもあるし、不可能ではない。#n……時間は少しかかるけど。"
"10032030-171-アル" = "目的は何ひとつ変わってないわ。#n任務を遂行し、報酬を受取る。"
"10032030-172-アル" = "相手が誰であれ、社長の私の行く手を遮る者は、全員邪魔者よ。#nそして、邪魔者は排除するのみ。"
"10032030-176-アル" = "……行きましょう。"
"10032030-182-ハルカ" = "あ、アル様！私も……！！"
"10032030-188-カヨコ" = "はぁ……"
"10032030-189-カヨコ" = "……結局こうなっちゃったね、先生。"
"10032030-190-カヨコ" = "ああ言ってるけどさ、社長は……"
"10032030-191" = "[s6] \"大丈夫だよ、分かってるから。\"\n[s7] \"アルらしいね。\""
"10032030-194-ムツキ" = "くふふ……無関係な人まで巻き添えになるのは阻止したいんだろうね～さすがアルちゃん。"
"10032030-195-カヨコ" = "まあ、本当にオペラハウスが爆発したら、一般の観客も大変なことになるし。"
"10032030-196-ムツキ" = "どんどん面白くなってきたじゃん。いいね、いいね～！"
"10032030-197-カヨコ" = "というわけで、先生……"
"10032030-198-カヨコ" = "……もう少し、お願いね。"
