[translation]
"80000115-1" = "飽きのこない甘さ"
"80000115-3-ミカ" = "せ～ん～！"
"80000115-4-ミカ" = "せ～！"
"80000115-5-ミカ" = "いっ！"
"80000115-9-ミカ" = "14日、ちょっとトリニティに来てくれないかな？"
"80000115-10-ミカ" = "先生に渡したい物があるの。"
"80000115-11-ミカ" = "あ、まだ何をあげるかは秘密だから！"
"80000115-12-ミカ" = "大丈夫だよね？うん！"
"80000115-13" = "[ns] \"14日……うん、楽しみにしてるね。\""
"80000115-16-ミカ" = "う、うん？た、楽しみって？"
"80000115-17-ミカ" = "な、何のことか分かんないな～あ、あはは……"
"80000115-18-ミカ" = "あんまり期待はしないでね……？#nガッカリされたら嫌だし……"
"80000115-20" = "[ns] \"じゃあ、ミカの授業が終わる頃に行くね。\""
"80000115-23-ミカ" = "楽しみにしてるなんて言われちゃった……ど、どうしよう……！"
"80000115-24-ミカ" = "うぅっ。が、頑張らないと……！"
"80000115-29" = "トリニティ学園・正門前"
"80000115-33" = "（約束の時間になったが、ミカの姿が見えない）"
"80000115-37" = "[ns] ミカに連絡してみる。"
"80000115-42-ミカ" = "……こんな時に誰……って、えっ！？せ、先生！？"
"80000115-43-ミカ" = "あれ、今って何時……わっ、もう約束の時間！"
"80000115-44-ミカ" = "ごめんね、先生！もう少しだけ待ってて！えっと、160℃で……7分？#nうん、先生！10分後には行くから！"
"80000115-45-ミカ" = "この間に着替えて……えっ、なんで！？#nなんか焦げた匂いが……"
"80000115-53" = "[ns] \"…………だ、大丈夫？\""
"80000115-57" = "[ns] ……ミカの居場所が分かった気がする、行ってみよう。"
"80000115-62" = "第7家庭科室"
"80000115-64-ミカ" = "ゲホッ、ゲホッ……#nううぅ、チョコレートってオーブンで溶かしたらダメなんだ……知らなかった。"
"80000115-65-ミカ" = "……うん？"
"80000115-66" = "[s] \"やあ、ミカ。\""
"80000115-67-ミカ" = "せ、先生！？"
"80000115-68" = "[s] \"ミカが心配で迎えに来たよ。\""
"80000115-69-ミカ" = "し、心配してくれたんだ……#nでも、どうして私がここに居るのを……って、わわっ！ちょ、ちょっと！"
"80000115-70-ミカ" = "ストップ！それ以上こっち来ないで！"
"80000115-71" = "[s] \"……え？\""
"80000115-72-ミカ" = "さっき体育の授業があったから、汗かいちゃったし……#nまだ体操着のままだし……"
"80000115-73-ミカ" = "それに、その……顔にクリームとかチョコが付いてると思うから……"
"80000115-74" = "[s] \"気にしなくても大丈夫だよ？\""
"80000115-75-ミカ" = "せ、先生は気にしないかもだけど……"
"80000115-76-ミカ" = "私は気にするの！先生、女の子を困らせちゃダメだよっ！"
"80000115-77" = "[s] \"ご、ごめん……\""
"80000115-78-ミカ" = "ちょっとだけ隣の教室で待ってて、すぐ行くから。"
"80000115-80" = "（ミカに言われた通り、隣の教室で待つことにした）"
"80000115-92-ミカ" = "先生、お待たせ。"
"80000115-93-ミカ" = "約束の時間、守れなくてごめんね。#n体育倉庫の片付けを任されてた子の体調が悪そうだったから、代わってあげてて……"
"80000115-94-ミカ" = "待っててって連絡したのに先生が急に現れて……ちょっとビックリしちゃった。"
"80000115-95-ミカ" = "でも……せっかくなら、ちゃんと用意したかったの。"
"80000115-96" = "[s] \"後ろに隠してる、それのこと？\""
"80000115-97-ミカ" = "……うん、そう……"
"80000115-98-ミカ" = "先生にあげたくて作ったんだ。"
"80000115-99-ミカ" = "……じゃじゃ～ん☆"
"80000115-105-ミカ" = "サプライズのつもりだったのに……あはは、あっさりバレちゃってたね。"
"80000115-106-ミカ" = "今は家庭科室のオーブンしか使えないし、良い材料も手に入らなかったけど……"
"80000115-107-ミカ" = "それでも、絶対に手作りを渡したかったの。"
"80000115-108-ミカ" = "こういうのを作ったのは初めてで、コーティングのチョコレートも少し焦がしちゃったから……ちょっと味に自信は無いけど……"
"80000115-115-ミカ" = "……受け取ってもらえる、かな？"
"80000115-116" = "[s1] \"ありがとう。ミカの手作りケーキをもらえるなんて嬉しいよ。\"\n[s2] \"うん、ちゃんとサプライズだったよ。ありがとう、ミカ。\""
"80000115-123-ミカ" = "う、うん……"
"80000115-124" = "[s] \"でも、ロールケーキは飽きたんじゃなかったの？\""
"80000115-125-ミカ" = "あはは、それはそうなんだけど……"
"80000115-126-ミカ" = "いろいろ食べたおかげで、ロールケーキには詳しくなったから。#n食感とか、味の違いとか……"
"80000115-127-ミカ" = "初めてのお菓子作りだし、冒険するのもなって。#nだから、よく知ってる物を選んだの。"
"80000115-128" = "[s] \"それでロールケーキなんだね。\""
"80000115-133-ミカ" = "ねえねえ、ところで先生……どうして私の居場所が分かったの？"
"80000115-134-ミカ" = "たしか温度がどうとか言っちゃった気はするけど、オーブンが使える家庭科室なんて数十個あるし……"
"80000115-135-ミカ" = "どこの家庭科室かまでは分からなかったはずなのに……"
"80000115-136" = "[s] \"ミカの予定は全部把握してるからね。\""
"80000115-137-ミカ" = "え、ええっ？"
"80000115-138" = "[s3] \"いつもミカが授業で使ってる家庭科室だし……\"\n[s4] \"前の授業が体育だったから、運動場に近いところだと思って。\""
"80000115-141-ミカ" = "そっか……先生だから、もう驚きはしないんだけど……"
"80000115-142-ミカ" = "私のスケジュールを、全部……"
"80000115-146-ミカ" = "……えへへ。なに？もしかして、問題児だから目を離せなかったとか？"
"80000115-147-ミカ" = "……けど、それでもちょっと嬉しいかも。"
"80000115-148" = "[s5] \"ミカが頑張ってること、ちゃんと知ってるから。\"\n[s6] \"ミカの頑張りは知っているよ。応援してる。\""
"80000115-154-ミカ" = "……うん！"
