[translation]
"10020020-5-リン" = "第2エリアの「次元エンジン」前に到着しました。"
"10020020-7-モモカ" = "ん～……このパターンならそろそろ――"
"10020020-8-アユム" = "「そろそろ」……？ "
"10020020-18-モモカ" = "や、やっぱり出た……！！"
"10020020-19-アユム" = "し、シロコさんが、また姿を現しました！"
"10020020-21-ホシノ" = "待ってたよ～！！"
"10020020-22-モモカ" = "び、ビックリしたあ！？"
"10020020-23-アヤネ" = "位置を確認しました！第2エリア「次元エンジン」前です！！"
"10020020-24-セリカ" = "すぐ、そっちへ向かうわよ！#n先生、私たちが到着するまで、足止めをお願い！！"
"10020020-25-ノノミ" = "はい！シロコちゃんに会いに行きます！！"
"10020020-33-アユム" = "戦闘態勢に入ります！#n先生、指揮をお願いします！"
