[translation]
"10055040-1" = "第4話;ガイスターシップ"
"10055040-3-マコト" = "……つまり、あの大きな船が霧と共に現れたと？"
"10055040-4-チアキ" = "まさに噂の幽霊船……ですね。"
"10055040-5-チアキ" = "いつもなら心霊特集！まさに特ダネ！と喜んでるところですが……。"
"10055040-6-マコト" = "博物館にありそうなくらい古いな。"
"10055040-11-イブキ" = "イブキ、これ知ってる！ガレオン船だよね。"
"10055040-12-チアキ" = "ガレオン？あ、聞いたことあります！#nたしかオールを漕いで動かす船ですよね？"
"10055040-13-イブキ" = "ううん、それはガレー船！もっと古い船だよ！"
"10055040-14-チアキ" = "あちゃー間違えちゃったか……#nお恥ずかしや、あはは。"
"10055040-15-サツキ" = "ガレーもガレオン船も、今となっては消えてしまったものね。"
"10055040-16-チアキ" = "消えてしまった……？#nでも……。"
"10055040-17-サツキ" = "そう。本来存在するはずのない、キヴォトス中のどこの海にもない船舶。"
"10055040-18-サツキ" = "その船が私たちの前に現れた、ということよ。"
"10055040-19-チアキ" = "それってまるで……。"
"10055040-24-マコト" = "……なるほど。これが幽霊船伝説の正体か。"
"10055040-28-マコト" = "よし、決めた。"
"10055040-29-マコト" = "あれを奪って陸へ戻る。"
"10055040-33-イロハ" = "……は？"
"10055040-34-サツキ" = "ちょ、ちょっとマコトちゃん！本気！？"
"10055040-35-マコト" = "ん？何か問題でも？"
"10055040-36-サツキ" = "幽霊船よ？幽霊船！本当に幽霊がいたらどうするのよ！"
"10055040-37-マコト" = "おかしなことを言うな？#n幽霊なんて居るわけがないだろう。"
"10055040-38-マコト" = "あれ程の船なら船員もそれなりにいるはずだ。#nそして船に異常を感じたなら表に出てくるだろう。"
"10055040-39-マコト" = "しかし未だに誰も出てこない……ということは、捨てられた船なのだろう。#n幽霊船の噂だって、どうせ寂れた船を見て、好き勝手言っているだけにすぎん。"
"10055040-40-チアキ" = "うわ、マコト先輩が真顔で常識人的な発言を！？"
"10055040-41-マコト" = "それに――"
"10055040-42-マコト" = "不安なら無理についてこなくとも良い。"
"10055040-43-イロハ" = "……え？"
"10055040-44-マコト" = "言葉通りの意味だ。船に居たければ好きにするがいい。"
"10055040-45-マコト" = "こちらに来たい者だけ私の後に続け。#nこのマコト様が先導してやろう。"
"10055040-49-チアキ" = "あっ、マコト先輩！一人じゃ危ないですよ！"
"10055040-53-サツキ" = "…………。"
"10055040-54-サツキ" = "マコトちゃん、変ね。"
"10055040-55-イロハ" = "そうですか？いつもと同じだと思いますけど。#n自分勝手で、強引で……。"
"10055040-56-サツキ" = "違う。そういう話じゃないわ。"
"10055040-57-サツキ" = "マコトちゃんと私は結構似ているの。痛いことと、怖いものが大嫌いで……。#nだから、あんな危ない場所に自分から入りに行くことなんて絶対にしない。"
"10055040-58-イロハ" = "そうですね……いつもなら私に行けって言いそうなのに。"
"10055040-59-サツキ" = "……なんだか嫌な感じ。"
"10055040-60-サツキ" = "幽霊船が現れて、マコトちゃんの雰囲気がおかしくなった。"
"10055040-61-サツキ" = "まさかあの船は、精神に影響を与えて……？"
"10055040-66-イブキ" = "イブキもいくー！"
"10055040-67-イロハ" = "えっ……？でも、危険です。"
"10055040-68-イブキ" = "イブキ知ってるよ！#n私たち、実は漂遊……？漂流、してるんだよね？"
"10055040-69-イブキ" = "それでイロハ先輩もマコト先輩とケンカしてて……。"
"10055040-70-イロハ" = "イブキどうしてそれを……。"
"10055040-71-イブキ" = "イブキもみんなの役に立ちたい！"
"10055040-72-イブキ" = "イブキも万魔殿の一員、だからね！"
"10055040-77-イロハ" = "イブキ……。"
"10055040-78-イロハ" = "……分かりました。その代わり、私のそばから絶対に離れないでくださいね。"
"10055040-79-サツキ" = "ええっ！？あなた達も行くの！？"
"10055040-80-イロハ" = "ええ、まあ……やっぱり、チアキが心配なので。"
"10055040-81-サツキ" = "ちょっと！それじゃあ私一人きりじゃない！？"
"10055040-82-イロハ" = "そうなりますね？#nまあ、一人くらいは船を守ってもいいかなと。"
"10055040-83-サツキ" = "うう……！"
"10055040-87-サツキ" = "…………。"
"10055040-88-イロハ" = "いや本当に。無理してついてこなくて大丈夫ですから。"
"10055040-89-サツキ" = "待って頂戴！今考えてるから！"
"10055040-93-サツキ" = "……私も行く。"
"10055040-94-イロハ" = "えっ本当に？大丈夫ですか？"
"10055040-95-サツキ" = "こんな状況で一人でいられるわけないじゃない！#n普通の人ならそうよ！まともな人間ならそうなの！"
"10055040-96-イロハ" = "そこまでではないかと……。"
"10055040-97-イブキ" = "サツキ先輩！イブキと手繋ご～"
"10055040-103-イブキ" = "ぎゅって！ずっと手繋いでたら絶対怖くないよ！"
"10055040-104-サツキ" = "イブキちゃん……。"
"10055040-108-サツキ" = "ふう……い、いいわ。心の準備はできたわよ。#n幽霊でもなんでもかかってきなさい！"
"10055040-109-イロハ" = "だから居ませんって。幽霊が居るわけないじゃないですか。"
"10055040-110-イロハ" = "……。"
"10055040-119-イロハ" = "……結局来ちゃいましたね。"
"10055040-120-イロハ" = "マコト先輩は……。"
"10055040-126-イロハ" = "奇襲！？みんな下がってください！"
"10055040-127-？？？" = "……なんだ、お前たちだったか。"
"10055040-133-イロハ" = "マコト先輩……？"
"10055040-134-イロハ" = "今の銃撃は……？"
"10055040-135-マコト" = "ああ、私だ。"
"10055040-136-マコト" = "私はてっきり、幽霊かと……。"
"10055040-137-イロハ" = "……？さっき幽霊なんて信じてないって……。"
"10055040-138-チアキ" = "あっ、イロハちゃん！来てたんだ！"
"10055040-142-イロハ" = "ああ、まあそういうことになりました。"
"10055040-143-イロハ" = "というか、少しは引き留めてくれてもいいじゃないですか。私やサツキ先輩はともかく、先生やイブキは本当に危ないんですよ。"
"10055040-144-チアキ" = "あはは、ごめん……でもその前に銃声がさ？"
"10055040-145-チアキ" = "……？そういえばマコト先輩が銃を使ってるの、初めてかも……？"
"10055040-146-サツキ" = "じゃあ誰も居ないのよね？安全なのよね？"
"10055040-147-マコト" = "ああ、間違いない。"
"10055040-148-マコト" = "ここまで騒ぎがあったというのに誰一人出てこない……。"
"10055040-149-マコト" = "つまりこの船には……。"
"10055040-158-サツキ" = "ああ……。"
"10055040-163-イロハ" = "サツキ先輩！しっかりしてください！！"
"10055040-164-マコト" = "幽霊だと！？"
"10055040-165-マコト" = "本当に現れるとは……しかしこちらにも対策はある！"
"10055040-166-マコト" = "イロハ、「アレ」だ！！「アレ」を準備しろ！！"
"10055040-167-イロハ" = "何のことかは分かりませんが、漂流中の私たちには何もありません！！"
"10055040-172-チアキ" = "わあっ！撃ってきましたよ！？"
"10055040-173-イロハ" = "なんで幽霊が銃なんか……いや、そんなこと言っている場合じゃないです！"
"10055040-174-イロハ" = "全員元の船に戻りましょう！"
"10055040-182-イブキ" = "先輩！後ろにも幽霊のお姉ちゃんたち！"
"10055040-183-イロハ" = "えっ、いつの間に！？"
"10055040-187-サツキ" = "う、うぅん……なあに？なんだかすごく怖い夢を見たような……。"
"10055040-191-サツキ" = "……って現実！？"
"10055040-196-チアキ" = "ああっ！これでは無限ループです！"
"10055040-197-マコト" = "チアキ、サツキを支えろ！中へ逃げるぞ！イブキはこっちへ！"
"10055040-198-チアキ" = "はいっ！！サツキ先輩、お気を確かに！！"
"10055040-212" = "[ns1] \"……バキッ？\"\n[ns2] \"あ、これは終わっ……。\""
"10055040-215-チアキ" = "あっ、床が……！！#n先生、サツキ先輩！"
"10055040-220-チアキ" = "大丈夫です、掴みまし――"
"10055040-221-チアキ" = "やっぱ一人じゃ無理かも……！"
"10055040-228" = "（……そして私たちは、船底へ落ちていった）"
