[translation]
"10055030-1" = "第3話;私のいる理由、そして船は発つべく"
"10055030-3" = "[log]漂 流  6 日 目[/log]"
"10055030-6-マコト" = "何度も言わせるな。"
"10055030-7-マコト" = "対策など不要。じきにゲヘナの救助隊が到着する。"
"10055030-8-イロハ" = "そろそろ現実を見たらどうなんですか？"
"10055030-9-イロハ" = "1週間が経とうとしてるのに、救助船どころか一隻も船を見てないじゃないですか。"
"10055030-10-マコト" = "ちょうど、それに関して思い当たる節がある。"
"10055030-11-マコト" = "これは間違いなく風紀委員の仕業だ！"
"10055030-12-マコト" = "委員長の空崎ヒナは用意周到だからな。我々が遭難したという事実、そしてもしかしたら現在位置までも把握しているのかもしれない。"
"10055030-13-マコト" = "そして、我々の居場所までたどり着けないよう、捜索活動を邪魔しているのだろう。"
"10055030-14-マコト" = "抑圧と統制……それが奴らの特技だからな。"
"10055030-15-マコト" = "しかし、それも長くは続かないだろう。#nゲヘナは抑圧されればされるほど、より強く反発する。いまごろ他の生徒も感づき始めたころではないか？"
"10055030-16-マコト" = "果たして、ゲヘナに必要なリーダーは一体誰なのか？#n卑劣な暴君、空崎ヒナ？もしくは羽沼マコト様？"
"10055030-17-マコト" = "民衆は破竹の勢いで風紀委員を撃沈させ、我々の救出へと乗り出すだろう！キシシッ！"
"10055030-21-イロハ" = "……マコト先輩、今この船に残ってる物資の量を把握されていますか？"
"10055030-22-マコト" = "知るわけないだろう。"
"10055030-23-イロハ" = "じゃあ、私たちがあと何日保つかも分かりませんよね？"
"10055030-24-マコト" = "ああ。そもそも興味がない。"
"10055030-25-マコト" = "そういった、くだらないものを管理するのが、お前の仕事だろう？イロハ。"
"10055030-29-チアキ" = "あ……えっと、マコト先輩……#n今の発言はちょっと……。"
"10055030-30-イロハ" = "くだらない……？"
"10055030-32-チアキ" = "あう……イロハちゃん……。"
"10055030-36-チアキ" = "……あっ！先生。"
"10055030-37-チアキ" = "ちょうどよかったというか、そうじゃないというか……。"
"10055030-38" = "[s1] \"どうしたの？\"\n[s2] \"なんか騒がしいけど……。\""
"10055030-41-チアキ" = "えっと、なんというか……。"
"10055030-42-イロハ" = "そういうならマコト先輩がやればいいんじゃないですか？"
"10055030-43-マコト" = "愚問だ。私にはもっと重要な仕事がある。"
"10055030-44-イロハ" = "重要……？重要な仕事って何ですか？"
"10055030-45-チアキ" = "ああっ……！"
"10055030-46" = "[s3] \"何があったの？\"\n[s4] \"ケンカしちゃった？\""
"10055030-49-チアキ" = "いや二人は……いや、正確にはイロハちゃんが……。"
"10055030-50-チアキ" = "先生もご存じだとは思いますが……イロハちゃんってほら、プライバシーとかパーソナルスペースを大事にするじゃないですか。"
"10055030-51-チアキ" = "なのに何日も、小さな船の中でずっと一緒だったから……。"
"10055030-52-チアキ" = "ちょっとストレスが溜まっちゃったみたいで……。"
"10055030-53-チアキ" = "いつもならケンカする方が面倒だからって、避けるはずなのに……。"
"10055030-58-イロハ" = "……。"
"10055030-59-マコト" = "何だ？言いたいことがあるなら言えばいいだろう。"
"10055030-60-イロハ" = "もういいです。"
"10055030-61-イロハ" = "そもそも期待していないので。#n期待しなければ、落胆することもありませんし。"
"10055030-62-マコト" = "ふむ……このマコト様の行動に問題があるとでも言いたいのか？"
"10055030-63-イロハ" = "はい。いつもありますし、今もそうです。"
"10055030-67-イロハ" = "この船にいるのは私だけじゃないんです。#n先生とイブキもいます。"
"10055030-68-イロハ" = "万が一のことがあったらどうするつもりなんですか？"
"10055030-69-マコト" = "愚問だな。この私が居るのだ、万が一などない。"
"10055030-70-イロハ" = "だから今！そうなってるって言ってるんですよ！"
"10055030-74-イロハ" = "すみません、声が大きすぎました。"
"10055030-75-イロハ" = "……ちょっとイブキを見てきます。"
"10055030-80-サツキ" = "珍しいわね、イロハがマコトちゃんに怒鳴るなんて。"
"10055030-81-チアキ" = "あ、サツキ先輩……。"
"10055030-82-サツキ" = "で、どうするのマコトちゃん？"
"10055030-83-サツキ" = "しばらくイロハに何も頼めないわよ？"
"10055030-84-マコト" = "……ふん、気にすることはない。"
"10055030-85-マコト" = "放っておけば泣きながら謝罪に来るだろう。"
"10055030-86-マコト" = "それまで我々がやればいい。"
"10055030-87-サツキ" = "イロハがやってたことを？できるのかしら。"
"10055030-88-マコト" = "今までイロハ一人でできていたのだ。できないわけがない。"
"10055030-89-マコト" = "このマコト様の手にかかれば一瞬だ。"
"10055030-90-サツキ" = "そう？まあマコトちゃんがそう言うなら……。"
"10055030-95-チアキ" = "……イロハちゃん。"
"10055030-98" = "[log]漂 流  7 日 目[/log]"
"10055030-104-マコト" = "みっ……みずぅ……！"
"10055030-109" = "[ns5] \"マコト！！気をしっかり！マコトぉ――っ！！\"\n[ns6] \"ど、どうしてこんなことに……！！！\""
"10055030-113-サツキ" = "一晩でこんなに状況が悪化するなんてね……。"
"10055030-114-サツキ" = "チアキ、イロハとの交渉は？"
"10055030-115-チアキ" = "あっ、それは……。"
"10055030-120-イロハ" = "なるほど、私の説得にチアキを送ってきたんですね。"
"10055030-121-イロハ" = "申し訳ないですが、絶対やりません。"
"10055030-122-イロハ" = "マコト先輩から謝ってこない限り、絶対。"
"10055030-124-サツキ" = "えぇっ！？マコトちゃんが謝るわけないじゃない！"
"10055030-125-チアキ" = "あはは……やっぱサツキ先輩もそう思いますよね？"
"10055030-126-サツキ" = "イロハ、一体何を考えているのかしら……。"
"10055030-130-チアキ" = "あの、サツキ先輩が説得してみるのはどうでしょう？"
"10055030-131-サツキ" = "私が？イロハに催眠でもかければいいの？#nまあ、構わないけど……。"
"10055030-132-チアキ" = "ち、違いますっ！そっちじゃなくて、マコト先輩の方です！"
"10055030-133-チアキ" = "詳しくは分かりませんが、お二人は昔からの付き合いって聞きました。#nだから、その……なんとかできませんか……？"
"10055030-134-サツキ" = "そうねぇ……。"
"10055030-135-サツキ" = "でも、私がマコトちゃんを謝らせることに成功したとして……全部綺麗に片づくと思う？"
"10055030-136-サツキ" = "マコトちゃんが反省なんてするわけないし、形だけの謝罪でイロハが納得するかしら？"
"10055030-137-チアキ" = "それは……。"
"10055030-138-チアキ" = "……そうですよね。ごめんなさい、やっぱり聞かなかったことにしてください。"
"10055030-139-サツキ" = "簡単に解決するなら私だって手を貸すわ。"
"10055030-140-サツキ" = "でも、今は他にできることをすべきよ。#nマコトちゃんやイロハが落ち着くまで、私たちがなんとかしなきゃ。"
"10055030-141-サツキ" = "……まずはそうね、マコトちゃんを連れてきてもらえるかしら。#nあとは、暇そうにしてる先生もついでにね。"
"10055030-142-チアキ" = "あははっ、遊んでいるわけじゃないと思いますけどね。"
"10055030-144-マコト" = "くっ……なぜ万魔殿の議長ともあろう私が、魚なんか……！"
"10055030-148-マコト" = "うわあっ！？"
"10055030-149-チアキ" = "ああっ、魚が逃げましたサツキ先輩！"
"10055030-150-サツキ" = "きゃあっ！？ど、どうしようマコトちゃん！？気持ち悪いわ！！"
"10055030-151-サツキ" = "助けなさい先生！？いや、お願い先生！助けて頂戴！"
"10055030-159-イロハ" = "……。"
"10055030-160-イブキ" = "……イロハ先輩？"
"10055030-161-イロハ" = "あっ、すみません。ちょっと考え事を……。"
"10055030-162-イロハ" = "……ずっと中にいても、つまらないですよね。"
"10055030-163-イブキ" = "ううん。イブキ、イロハ先輩と一緒だから楽しいよ。"
"10055030-164-イロハ" = "それは、よかったです。"
"10055030-165-イブキ" = "でもイロハ先輩はあんまり楽しくなさそう。"
"10055030-166-イロハ" = "私が、ですか？"
"10055030-167-イロハ" = "……そんなはず。"
"10055030-169-イロハ" = "面倒な先輩もいなければ雑務もない。#nこうしてイブキと一緒にいるのに……。"
"10055030-170-イロハ" = "楽しくないわけ、ないじゃないですか。"
"10055030-176-マコト" = "…………。"
"10055030-182-イロハ" = "…………。"
"10055030-183-イロハ" = "ごちそうさまでした。"
"10055030-188-チアキ" = "……。"
"10055030-189-チアキ" = "イロハちゃん、このまま万魔殿をやめてしまうんでしょうか。"
"10055030-190-マコト" = "……好きにすればいい。"
"10055030-191-サツキ" = "命令すればいいんじゃない？#n行くなって。"
"10055030-192-サツキ" = "イロハは変化を好まないし、それで十分だと思うけど。"
"10055030-193-マコト" = "いや――それだけはダメだ。"
"10055030-194-マコト" = "このマコト様を敬う者は、誰であろうと自ら従うべきだ。#nそれだけは譲れない。"
"10055030-195-マコト" = "私が権威を盾に自由意志を奪っては、あの頃のゲヘナと変わらんだろう？"
"10055030-196-サツキ" = "……それもそうね。"
"10055030-197-サツキ" = "いいわ、マコトちゃんの好きにして頂戴。#n私の催眠が必要になったら言うのよ。"
"10055030-198-サツキ" = "「従う」と本気で信じさせれば、それは自由意志と変わらないのだから。"
"10055030-199-マコト" = "いいや、必要ない。去りたい者は去ればいい。#n私から言うことはない。"
"10055030-200-マコト" = "……チッ、イロハのやつ。"
"10055030-201-マコト" = "いつまで拗ねてるつもりだ……。"
"10055030-204-イロハ" = "……はぁ。"
"10055030-205-イロハ" = "私は一体何がしたいんだか。"
"10055030-206" = "[ns7] \"イロハ。\"\n[ns8] \"探したよ。\""
"10055030-209-イロハ" = "……先生。"
"10055030-210-イロハ" = "また適当なこと言って。#nこんな狭い船で、探し回る場所なんてないですよ。"
"10055030-214-イロハ" = "言いたいことは分かってます。"
"10055030-215" = "[s9] \"私の考えが読まれた……！？\"\n[s10] \"無念無想……！\""
"10055030-218-イロハ" = "あははっ、何ですかそれ。"
"10055030-219-イロハ" = "……。"
"10055030-220-イロハ" = "やっぱり先生も、私が謝ったほうがいいと思ってます？"
"10055030-221-イロハ" = "相手は、あのマコト先輩ですし……。"
"10055030-222-イロハ" = "あの人が先に謝るわけないですから……それに。"
"10055030-223-イロハ" = "……。"
"10055030-224-イロハ" = "私が謝ってようやく、色々動き出すとは思いますし。"
"10055030-225-イロハ" = "……でも。"
"10055030-229-イロハ" = "はぁぁ…………。"
"10055030-230-イロハ" = "普段と比べたら、怒るようなことでもなかったのに……。"
"10055030-231-イロハ" = "私、どうして万魔殿にいるんでしょうか。"
"10055030-235-イロハ" = "……ん？"
"10055030-236-イロハ" = "「万魔殿に入った理由」ですか？"
"10055030-237-イロハ" = "さあ。"
"10055030-238-イロハ" = "あんまり思い出せないですね。"
"10055030-239-イロハ" = "たぶん、大した理由じゃないです。#n生徒会に入ったら、楽に過ごせるかなーって。"
"10055030-240-イロハ" = "周囲からの評価も上がるんじゃないかとか、そんなものかと。"
"10055030-241-イロハ" = "……先生から見ても、可愛げのない生徒ですかね。"
"10055030-242" = "[s11] \"そうでもないよ。みんな計算しながら生きてると思うし。\"\n[s12] \"そうしない人がすごいだけで。\""
"10055030-245-イロハ" = "いつも口は上手いですよね。"
"10055030-246-イロハ" = "……すみません。先生にまでこんなことを言うつもりでは。"
"10055030-247-イロハ" = "でも、いざ万魔殿に入ってみたら……マコト先輩はあれこれうるさいし、次々と問題は起こるし。"
"10055030-248-イロハ" = "なんで入ったんだろうって思ったりもします。やってらんないですよ。"
"10055030-249-イロハ" = "はぁぁ…………。"
"10055030-250-イロハ" = "このまま、消えちゃいたい。"
"10055030-251-？？？" = "旅に出たい？"
"10055030-255-イロハ" = "え、今なんと……？"
"10055030-256-イロハ" = "何か聞こえませんでした？#n誰かの声、が……。"
"10055030-261-イロハ" = "なっ、なんですか！？"
"10055030-262-イロハ" = "大丈夫ですか先生！？"
"10055030-263" = "[s13] \"イロハこそ大丈夫？\"\n[s14] \"何が起きたんだろう？\""
"10055030-266-イロハ" = "船が何かとぶつかりました。"
"10055030-267-イロハ" = "でもさっきまで船影ひとつなかったのに……。"
"10055030-268-イロハ" = "岩礁に当たったのかもしれませんね……。"
"10055030-272-イロハ" = "ありえない……。"
"10055030-273-イロハ" = "……幽霊船？"
