[translation]
"10055140-1" = "デイ・オブ・ザ・ロブスター"
"10055140-2" = "[log]漂 流 〇 日 目[/log]"
"10055140-7" = "[ns1] \"……今頃みんなはどうしてるんだろう。\"\n[ns2] \"元気にしてるかなぁ……。\""
"10055140-10-マコト" = "朝から弱気とはらしくないな、先生よ。"
"10055140-14-マコト" = "この私が統治するネオ・ゲヘナでの生活に、何か不満でもあるのか？"
"10055140-15" = "[s] \"ネオ……ゲヘナ？\""
"10055140-16-マコト" = "ああ、今朝……私は目覚めたのだ！"
"10055140-17-マコト" = "マコト様がいるこの船こそが真のゲヘナなのだと！"
"10055140-18-マコト" = "よって、ここを「ネオ・ゲヘナ」と名付けたのだ！"
"10055140-19-マコト" = "……どうした、先生？何か言いたげな顔だな。"
"10055140-20" = "[s3] \"その考え方は大事だなと思って。\"\n[s4] \"やっぱりマコトはたくましいね。\""
"10055140-23-マコト" = "キシシッ！要は褒めているということか！"
"10055140-24-マコト" = "先生も安心してこの時間を楽しんでくれ！救助隊はじき到着する！"
"10055140-28-チアキ" = "なるほど～！"
"10055140-32-チアキ" = "海での生活にはそんな悩みがあるんですね！"
"10055140-33-チアキ" = "おや、先生！"
"10055140-34-チアキ" = "え？あ、こちらはですね――"
"10055140-35-チアキ" = "ご紹介します！取材に協力いただいている、お魚のヨナさんです！"
"10055140-36-チアキ" = "袖振り合うも他生の縁！いえ、エラ振り合うも他生の縁！"
"10055140-37-チアキ" = "この広い海で出会えた奇跡！とても他人とは思えません！"
"10055140-38-チアキ" = "そんなわけで、色々とインタビューしていたんです。"
"10055140-39-チアキ" = "先生はどうされました？"
"10055140-40" = "[s5] \"えっと……少し立ち寄っただけ。\"\n[s6] \"インタビュー……頑張ってね。\""
"10055140-43-チアキ" = "はい！ありがとうございます！！"
"10055140-44-チアキ" = "それで、巨大魚に飲み込まれた話の続きなんですが――"
"10055140-48-イロハ" = "はぁ……本当、目も当てられませんね。"
"10055140-49" = "[s7] \"イロハ！\"\n[s8] \"よかった！大丈夫だったんだ――\""
"10055140-56-イロハ" = "……どうしました？幽霊でも見たような顔して。"
"10055140-57-イロハ" = "え？これですか？"
"10055140-58-イロハ" = "見ての通り虎丸ですけど？"
"10055140-59-イロハ" = "何か問題でも？"
"10055140-63-イロハ" = "主砲、装甲、異常なし……。"
"10055140-64-イロハ" = "特に変わったところはありませんが……？"
"10055140-65-イロハ" = "先生の気のせいじゃないんですか？"
"10055140-66-イロハ" = "……じゃあ、私は見回りがあるのでこれで。"
"10055140-67-イロハ" = "いきましょう、虎丸。"
"10055140-71-イロハ" = "ブーン。"
"10055140-76-サツキ" = "……陸に戻るまで、そっとしておいた方がよさそうね。"
"10055140-77" = "[s9] \"サツキ！！\"\n[s10] \"無事だったんだね！！\""
"10055140-80-サツキ" = "その言い方だと無事じゃない人もいるように聞こえるんだけど……。"
"10055140-81-サツキ" = "今の状況を見ると、そうじゃないとは言い切れないわよね。"
"10055140-82-サツキ" = "それにしても……マコトちゃんはさておき、イロハやチアキまで……。"
"10055140-83-サツキ" = "これじゃ万魔殿の面子は丸つぶれね。"
"10055140-84" = "[s11] \"マコトはさておくんだ……。\"\n[s12] \"みんな、ストレスが溜まっちゃってるみたいだね。\""
"10055140-87-サツキ" = "そうね、私だってここまで長引くとは思ってなかったもの。"
"10055140-88-イブキ" = "せんせ～！"
"10055140-92-イブキ" = "サツキ先輩もやっほー！"
"10055140-93-サツキ" = "イブキちゃん、船の上で走ったら危ないわよ？"
"10055140-94-イブキ" = "あっ！うん、気をつける……。"
"10055140-95-サツキ" = "それで、そんなに急いでどうしたの？"
"10055140-96-イブキ" = "あのね！あっちに島があったの！"
"10055140-97-サツキ" = "まさか。この近くに島なんて……。"
"10055140-98-サツキ" = "はっ！まさか、イブキちゃんまで幻覚を！？"
"10055140-99-サツキ" = "……ん？先生？"
"10055140-100-サツキ" = "ぼーっとしてどうしたの？気を付けないと海に落ちちゃう――"
"10055140-101" = "[ns] \"り……。\""
"10055140-102-サツキ" = "り？"
"10055140-103" = "[ns] \"陸だ！！！\""
"10055140-106-サツキ" = "え！ほ、本当！？"
"10055140-107-イロハ" = "陸！？"
"10055140-108-マコト" = "なっ、本当かそれは！？"
"10055140-113-サツキ" = "……本当に、こんな大きな島があるなんて。"
"10055140-114-イロハ" = "今のところ、人の気配はないですね。無人島でなければいいのですが。"
"10055140-115-マコト" = "何を言う、イロハ！無人島の方が良いに決まっているだろう！"
"10055140-116-イロハ" = "え？"
"10055140-117-マコト" = "無人島ということは……このマコト様が、この島の最初の発見者ということになる！"
"10055140-118-マコト" = "キシシッ！今日からこの島の名前は「マコト島」だ！"
"10055140-119-イロハ" = "……どうやったらそんなポジティブ思考になれるんですか。"
"10055140-125-イブキ" = "ん？"
"10055140-126-イブキ" = "わあ～かわいいヤドカリさんだ！"
"10055140-127-チアキ" = "本当だ、かわいい！写真撮るね！"
"10055140-128-イブキ" = "いぇ～い、万魔殿ヤドカリ～！"
"10055140-129-チアキ" = "え？万魔殿ヤドカリ……？"
"10055140-130-イブキ" = "そうだよ！これはマコト先輩。こっちはサツキ先輩……。"
"10055140-131-チアキ" = "おおっ！たしかに、殻の色がマコト先輩たちの髪色と一緒！"
"10055140-132-チアキ" = "じゃあ、こっちの黒い子は万魔殿ヤドカリの書記？"
"10055140-133-イロハ" = "……なるほど、それなりに生態系は整っているんですね。"
"10055140-134-イロハ" = "つまり食料調達ができる可能性が高い、と。"
"10055140-135-イロハ" = "イブキには申し訳ないですが、この子たちも……。"
"10055140-136-マコト" = "なんだとっ！？"
"10055140-137-マコト" = "こいつを食べるというのか！？"
"10055140-138-イロハ" = "び、ビックリした……今度は何ですか。"
"10055140-139-マコト" = "何ですか、ではない！"
"10055140-140-マコト" = "食糧など言語道断！こいつは正真正銘のファイターだ！"
"10055140-141-イロハ" = "…………。"
"10055140-142-イロハ" = "……はい？"
"10055140-144-マコト" = "純真無垢な目の奥にたぎる熱い闘志……お前、タダのヤドカリではないな！？"
"10055140-145-マコト" = "お前の正体はなんだ！"
"10055140-146-イブキ" = "言え！一体なんなのだ！"
"10055140-147-サツキ" = "あら、おめでとうヤドカリさん。マコトちゃんがこんな風に褒めるなんて珍しいわよ。"
"10055140-148-イロハ" = "いやいや……。"
"10055140-149-イロハ" = "ヤドカリ一匹に、そんな大袈裟な……。"
"10055140-150-チアキ" = "あははっ！でもいつものみんなに戻ったみたいでよかった！"
"10055140-151-イロハ" = "……まあ、そうですね。落ち込んでいるよりかは。"
"10055140-152-マコト" = "分かったぞ！こいつはサメなのだ！#nたとえ体が小さかろうと、気概はサメに勝るとも劣らん！"
"10055140-153-マコト" = "今からお前は「タイガーシャーク丸」だ！"
"10055140-154-マコト" = "ヤドカリ界の頂点……。#nいやそれを飛び越え、甲殻類最強のチャンピオンになるのだ！"
"10055140-157-？？？" = "うへ～"
