[translation]
"10055070-1" = "第7話;Fools in August"
"10055070-2-トライデントの部員A" = "……今日は霧がひどいな。"
"10055070-3-トライデントの部員A" = "こんな日に見回りなんて……。"
"10055070-4-トライデントの部員B" = "まあどうせ何もないでしょ。"
"10055070-5-トライデントの部員B" = "今日は特に申請もなかったし、AISにも何もないし。"
"10055070-6-トライデントの部員B" = "適当に見て……。"
"10055070-10-トライデントの部員B" = "……んん？"
"10055070-11-トライデントの部員B" = "ちょっと、こっちに双眼鏡ちょうだい。"
"10055070-13-トライデントの部員B" = "…………。"
"10055070-15-トライデントの部員B" = "スターボードにて、報告！"
"10055070-19-？？？" = "……。"
"10055070-20-？？？" = "…………。"
"10055070-21-？？？" = "スターボード、どうしました？"
"10055070-22-？？？" = "報告を続けてください。"
"10055070-23-トライデントの部員A" = "あ、スミカちょうどいいところに！"
"10055070-24-スミカ" = "「キャプテン」です！"
"10055070-25-トライデントの部員B" = "キャプテンって、別にくじ引きで決めたのに……。"
"10055070-26-スミカ" = "キャ・プ・テン・っ！"
"10055070-27-トライデントの部員B" = "分かった分かった、キャプテン。"
"10055070-28-トライデントの部員A" = "ほんと肩書きとか好きだよね……。"
"10055070-29-スミカ" = "というか、なんで途中で報告をやめたんですか？"
"10055070-30-スミカ" = "居眠りしてて見間違えたとか……じゃないですよね？"
"10055070-31-トライデントの部員A" = "あ、そうそう。"
"10055070-36-トライデントの部員A" = "いや……でも、これって。"
"10055070-37-トライデントの部員B" = "あんたも見たでしょ？"
"10055070-38-トライデントの部員A" = "いやそうだけど……でも有り得ないじゃん？"
"10055070-39-スミカ" = "ちょっと、コソコソしないでください！"
"10055070-40-スミカ" = "このハルピュイア号で起きること全部、キャプテンは把握しないといけないんですから！！"
"10055070-45-トライデントの部員B" = "……らしいよ？"
"10055070-46-トライデントの部員A" = "えー……はあ、じゃあ言っちゃうよ？"
"10055070-50-トライデントの部員A" = "スターボードにて、報告！"
"10055070-51-トライデントの部員A" = "帆船1隻、方位010度！距離1000ヤード！"
"10055070-52-トライデントの部員A" = "真正面から本船に接近中！"
"10055070-57-スミカ" = "……あの。私のことが嫌いなのは分かりますが。"
"10055070-58-スミカ" = "部長でも副部長でもない私がキャプテンになって気に食わないのは分かります。#nでも見回りに毎回お二人が同行できるわけじゃありません。"
"10055070-59-スミカ" = "だから私は航海の安全のために、たとえ～皆さんに嫌われたと～しても！#nこの役割を担おうと……。"
"10055070-60-トライデントの部員A" = "いや、変人扱いしないで！？"
"10055070-61-トライデントの部員A" = "自分の目で確かめてよ！"
"10055070-67-スミカ" = "……いや、どうせ何もな――"
"10055070-72-スミカ" = "……？"
"10055070-73-スミカ" = "何ですかあれ？"
"10055070-78-トライデントの部員A" = "だから帆船だって。"
"10055070-79-スミカ" = "なんですか帆船って！？"
"10055070-80-トライデントの部員A" = "はあ？知らないの？昔の軍艦！大砲も載ってるやつ！"
"10055070-81-スミカ" = "そうじゃなくて！！というか1000ヤード！？目の前じゃないですか！"
"10055070-82-スミカ" = "あんな船がすぐそこにあるのに誰も気づかなかったんですか！？"
"10055070-83-トライデントの部員A" = "こんなひどい霧の中で、これ以上見えないよ。"
"10055070-84-スミカ" = "そうだ、レーダーは？レーダーはどうしたんですか！"
"10055070-85-トライデントの部員C" = "レーダーにはまだ何の信号もありません！"
"10055070-90-トライデントの部員A" = "……動力なし？無線封鎖？"
"10055070-91-トライデントの部員B" = "……軍艦って言っていたよね？"
"10055070-92-トライデントの部員A" = "つまり……大砲を装備した軍艦が、エンジンを切ったまま向かって来てるってこと？"
"10055070-93-トライデントの部員B" = "……。"
"10055070-94-トライデントの部員A" = "……キャプテン、どうする？"
"10055070-99-スミカ" = "なんでよりによって私がキャプテンの日にこんなことが？いっそのこと何も知りませんとか言っちゃう？いやでもキャプテンなのに知らないというのも責任者として……。"
"10055070-100-スミカ" = "あ、そうだ！まだ敵だと決まったわけじゃないんですよね？"
"10055070-101-スミカ" = "無線通信はどうですか？"
"10055070-102-トライデントの部員C" = "それがさっきからやってみてるけど、応答なし。"
"10055070-103-スミカ" = "サーチライトで警告は？"
"10055070-104-トライデントの部員B" = "だいぶ前からやってるけど反応なし。"
"10055070-105-トライデントの部員B" = "右に舵切ろうか？"
"10055070-106-スミカ" = "そ、それはダメです！"
"10055070-107-スミカ" = "1000ヤードしかないのに無理に舵を切って傾いたら……？それに攻撃でもされたら沈没……！悠久のハルピュイア号が私の責任によって！？それだけはダメ……！！"
"10055070-108-トライデントの部員C" = "キャプテン！音声をキャッチしました！"
"10055070-109-トライデントの部員C" = "船長帽らしきものを被った人の声です。"
"10055070-110-スミカ" = "おお！今そっちに行きます！"
"10055070-111-スミカ" = "いや、やっぱ時間ないのでデッキに流してください！"
"10055070-115-スミカ" = "まあ、どうせただの誤解だと思いますけど～"
"10055070-116-スミカ" = "だってオデュッセイアですよ？ど～このバカが海で私たちに喧嘩を売るんですか？"
"10055070-118-？？？" = "真の海賊がやることと言えば一つ！"
"10055070-119-？？？" = "キヴォトス中の金銀財宝を略奪するのだ！ヨーホホ！"
"10055070-121-トライデントの部員たち" = "…………。"
"10055070-123-スミカ" = "…………。"
"10055070-124-スミカ" = "……いや待てよ。"
"10055070-125-スミカ" = "相手は旧式の船に乗ったただの寄せ集め海賊。一方こちらは精鋭部隊トライデント。今ここで奴らを打ちのめせば当然功績は私に……！"
"10055070-126-トライデントの部員A" = "キャプテン？"
"10055070-127-スミカ" = "すぅー……はぁー……。"
"10055070-128-スミカ" = "総員、戦闘配置へ！海賊を掃討します！！"
"10055070-130-トライデントの部員たち" = "アイアイキャプテン！！"
"10055070-139-マコト" = "くそっ、海軍の奴ら、もう匂いを嗅ぎつけて！？"
"10055070-140-イロハ" = "海軍ってなんですか！？本当の海賊でもないのに！？"
"10055070-141-マコト" = "そんなことはどうだっていい！#n今マコト様の船がハチの巣にされているのだぞ！"
"10055070-142-マコト" = "やられっぱなしでたまるか！"
"10055070-143-マコト" = "諸君！これより私の指示に従って応戦する！"
"10055070-149-マコト" = "……何をしている？"
"10055070-151-海賊A" = "いや、その……戦うったって。"
"10055070-152-海賊B" = "どうやって？"
"10055070-154-マコト" = "この船には立派な大砲がついていただろう？"
"10055070-155-イロハ" = "無理です。"
"10055070-156-イロハ" = "さっき言おうとしたんですが、この船の大砲、中まで完全に錆びついてます。"
"10055070-157-イロハ" = "表面だけ綺麗にすればいいって話じゃありません。"
"10055070-158-マコト" = "……そうか、お前たちもそれを知っててじっとしていたのか。"
"10055070-160-海賊A" = "はい……実はこの船、武装はないです。"
"10055070-161-海賊B" = "それにあっしら、戦ったこともないです、キャプテン。"
"10055070-167-マコト" = "理解した。"
"10055070-168-マコト" = "お前らがどれだけ愚か者なのかをな！！"
"10055070-174-マコト" = "大砲が錆びている？それがどうした！"
"10055070-175-マコト" = "だからって船が海の藻屑になるのをただ見てるつもりか！？"
"10055070-177-海賊A" = "いやだって……。"
"10055070-178-海賊B" = "ダメなものはダメだし……。"
"10055070-180-マコト" = "できない理由か？やらない理由なのか？"
"10055070-181-マコト" = "戦ったこともないと言っていたな。なら大砲が使えるかどうかも分からないのだろう。"
"10055070-182-マコト" = "なのに使う前から諦めるだと？それでもお前らは船乗りか！？"
"10055070-183-マコト" = "気合いが足りない！そもそも火器ってもんは気合いがあればなんとかなる！"
"10055070-184-海賊A" = "いやそんなデタラメ……。"
"10055070-185-マコト" = "自分を信じられないなら私を信じろ！"
"10055070-186-マコト" = "大砲は絶対に使えるはずだ！"
"10055070-187-マコト" = "みな所定の位置に移動！装填、発射準備！"
"10055070-192-海賊A" = "……でも無理なもんは無理ですよ、キャプテン。"
"10055070-193-海賊B" = "この船の大砲は……。"
"10055070-195-マコト" = "お前らがやらないなら構わん！"
"10055070-196-マコト" = "[ruby=われわれ]万魔船[/ruby]がやる！"
"10055070-198-サツキ" = "う、うん！？私たち！？"
"10055070-199-チアキ" = "あっ、はいはい！私やってみたいです！大砲の装填！"
"10055070-200-イブキ" = "イブキも手伝う！"
"10055070-201-サツキ" = "私はやめとくわね？みんな頑張って頂戴。"
"10055070-204-イロハ" = "何をバカげた……。"
"10055070-205" = "[s] \"イロハもやらない？\""
"10055070-206-イロハ" = "……でも、やるまでずっとああなんでしょうから。"
"10055070-207-イロハ" = "あの人には目の前で見せないと。できないものはできないって。"
"10055070-208-イロハ" = "どうせ勘違いなのに。説明すればいいものを……。"
"10055070-209-イロハ" = "本当めんどくさくて、イライラする人。"
"10055070-211-チアキ" = "よいしょ、よいしょ！"
"10055070-212-イブキ" = "よいしょ、よいしょ！"
"10055070-213-イブキ" = "どう？イブキ力になれてる？"
"10055070-214-チアキ" = "はい！おかげですごく軽いです！"
"10055070-216-イロハ" = "はあ……このタイプは、まず火薬を入れればいいんでしたっけ。"
"10055070-220-イブキ" = "あっ、ダメだよ！イロハ先輩！"
"10055070-221-イブキ" = "最初は火薬袋を入れないと！"
"10055070-225-イブキ" = "あううう……！"
"10055070-226-イロハ" = "あっ、イブキ！重い物は私が持ちますから！"
"10055070-227-イブキ" = "い、イロハ先輩！ありがとう！まだイブキの力じゃ……。"
"10055070-230-イブキ" = "次は砲弾！こうやってひもの束を入れて固定して……。"
"10055070-231-イブキ" = "最後に火薬を入れて火をつけるの！"
"10055070-232-イロハ" = "おお……すごく詳しいんですね。"
"10055070-233-イブキ" = "うん！いっぱい勉強したんだ！"
"10055070-235-海賊A" = "……。"
"10055070-236-海賊B" = "……。"
"10055070-238-マコト" = "諸君、装填はできたか！"
"10055070-240-イロハ" = "はあ、一応……。"
"10055070-242-マコト" = "返事が小さい！"
"10055070-244-チアキ" = "はい、キャプテン！"
"10055070-245-イブキ" = "あとは火をつけたらドカーン！って発射するよ！"
"10055070-247-マコト" = "さすがじゃないか、素晴らしい！"
"10055070-248-マコト" = "最初の一撃は私の号令に合わせて撃つ！"
"10055070-249-マコト" = "狙うはあの忌々しい海軍どもの船！"
"10055070-251-海賊A" = "無駄だって。"
"10055070-252-海賊B" = "できるわけないのに、バッカみたい……。"
"10055070-254-マコト" = "ヨーホホ！見ているがいい！"
"10055070-255-マコト" = "このマコト様が奇跡を起こして見せよう！"
"10055070-259-マコト" = "よーい……。"
"10055070-270-マコト" = "――撃て！！！"
"10055070-273-イロハ" = "……は？"
"10055070-274-イロハ" = "そんな、あり得ない……。"
"10055070-275-チアキ" = "わあ！すごい音！"
"10055070-276-イブキ" = "イブキもやってみる！えいっ！"
"10055070-280-マコト" = "ヨーホホ！やっぱり気合いの問題だったな。"
"10055070-282-海賊A" = "……大砲が使えた？"
"10055070-283-海賊B" = "あの日以来、二度と発射されなかった大砲が……。"
"10055070-285-マコト" = "諸君、反撃はここからだ！次を装填しろ！！"
"10055070-291-海賊たち" = "アイアイ！キャプテン！！！"
