[translation]
"41020-1" = "第2話;招かれざる客"
"41020-3-ヴァルキューレの生徒A" = "のわっ！？銃弾！？"
"41020-4-ヴァルキューレの生徒B" = "ここ、間違いなく死角だよな……？どこから飛んでくるんだ？"
"41020-9-サキ" = "……甘いな。"
"41020-10-サキ" = "サーマルカメラも知らないのか、隠れても無駄だってのに。"
"41020-14-サキ" = "モエ、足止め完了！早く爆撃を！"
"41020-15-サキ" = "座標、[ruby=ヴィクターキロ] VK4[/ruby]-0-4-5！"
"41020-16-サキ" = "やれ！"
"41020-22-モエ" = "くひひ、待ちくたびれたよ！"
"41020-30-ヴァルキューレの生徒A" = "ドローンだ！？"
"41020-31-ヴァルキューレの生徒B" = "真っすぐこっちに来る、逃げろ！！"
"41020-37-カンナ" = "今の爆発は何だ！"
"41020-41-カンナ" = "アルファ分隊、応答しろ！"
"41020-43-シノン" = "ご覧いただけてますでしょうか？"
"41020-44-シノン" = "公安局、防戦一方です！"
"41020-45-マイ" = "警備局に続き、公安局までやられてしまいそうです！もうヴァルキューレで動ける部隊といえば、生活安全局くらいでしょうか……！？"
"41020-46-シノン" = "デモを行っているのはSRT特殊学園の生徒とのことでしたが、それでも圧倒的なまでに押されてしまってます。"
"41020-47-シノン" = "果たしてこの後、どうなっていくのでしょうか……！"
"41020-48-マイ" = "そうですね、何かヴァルキューレ側に秘策はあるのでしょうか！？"
"41020-49-カンナ" = "ああもう、うるさい！"
"41020-50-カンナ" = "誰の許可で撮影してる！さっさとカメラを止めろ！"
"41020-51-シノン" = "おっと、マズいですね！"
"41020-52-マイ" = "怒られる前に距離を取るとしましょうか！"
"41020-53-カンナ" = "邪魔をするな！早くどけ！"
"41020-54-カンナ" = "くそっ、クロノスか……相変わらずうるさい……！"
"41020-55-カンナ" = "とはいえ、確かにもう人員が……生活安全局のバカ共は使えないし……。"
"41020-56" = "[s] \"何だかすごい状況だね……。\""
"41020-58-カンナ" = "……何だ貴様は。"
"41020-59-カンナ" = "見て分からないのか、戦闘中だ。部外者はさっさと出ていけ。"
"41020-65" = "[ns] リンの紹介状を渡す。"
"41020-66-カンナ" = "これは、行政官の紹介状……？"
"41020-67-カンナ" = "防衛室の代わりに……「シャーレ」だと！？"
"41020-68-カンナ" = "……こ、これは大変失礼いたしました。"
"41020-69-カンナ" = "実際にお会いするのは初めてかと。"
"41020-75-カンナ" = "今回の作戦において、現場の責任者を担当しています。ヴァルキューレ警察学校の公安局長、カンナです。"
"41020-76" = "[s1] \"うん、初めまして。\"\n[s2] \"状況はどんな感じ？\""
"41020-77-カンナ" = "そうですね、見ての通りと言いますか……。"
"41020-78-カンナ" = "そうですね、見ての通りと言いますか……。"
"41020-79-カンナ" = "兵力はほとんど残っておらず、士気も底を突いています。"
"41020-80-カンナ" = "当初は数で制圧するつもりでしたが、SRTの火力はでたらめで……。"
"41020-81-カンナ" = "もう残りの人員も――"
"41020-86-キリノ" = "お待たせしました、生活安全局のキリノです！"
"41020-87-キリノ" = "もう今すぐ出動しても良いですか！？"
"41020-88-フブキ" = "……もう終わってるっぽくない？これ、もはや私たちの出番じゃないでしょ。"
"41020-90-カンナ" = "この「生活安全局」だけです。"
"41020-91-キリノ" = "あ、先生！奇遇ですね、ヴァルキューレの支援に来てくださったのですか？"
"41020-92-フブキ" = "こんな現場にまで来るなんて、相変わらず大変だねえ。"
"41020-93-キリノ" = "先生の指揮さえあれば、もう作戦は成功したも同然ですね！"
"41020-94-キリノ" = "さあ、このまま放っておくわけにはいきません！早速出動しましょう！"
"41020-95-カンナ" = "待て、勝手に動くな。お前らが出ていって何になる？"
"41020-96-カンナ" = "警備局も公安局も、ほとんどやられたんだぞ。お前たちが相手になると思っているのか？"
"41020-97-カンナ" = "そもそも、ろくな武器だって持っていないだろうに……何を根拠に勝てると？"
"41020-98-カンナ" = "……自分の腕前くらい、分かってるものだと思ったがな？"
"41020-99-キリノ" = "で、ですが、市民の方々も怖がっていますし……このまま見ているだけ、というわけには……。"
"41020-100-カンナ" = "……意欲は買おう。しかし気合だけではどうにもならない。"
"41020-101-カンナ" = "我々が他の方法を見つけるまで、とにかくここで待機していろ。"
"41020-102-キリノ" = "は、はい……。"
"41020-103-フブキ" = "ラッキー。ま、言ってることはその通りだしね。"
"41020-104" = "[s] \"ここを占拠してる生徒たちについて、何か情報とかある？\""
"41020-105-カンナ" = "はい、「SRT特殊学園」所属の1年生チーム……「RABBIT小隊」です。"
"41020-106-カンナ" = "本来ならSRTの閉校によって、ヴァルキューレの警備局に転校する予定だったのですが……。"
"41020-107-カンナ" = "何があったのか、急にこうして公園を占拠。「閉校を取り消せ」とデモを始めた、という経緯です。"
"41020-108-カンナ" = "数は少ないものの、その装備は最先端のものです。主にそれが理由で、ここまで手こずってしまい……。"
"41020-109" = "[s] \"なるほど。見ても良い範囲で、他に詳細な情報とかある？\""
"41020-110-カンナ" = "一応、連邦生徒会から提供された各生徒の資料なら……"
"41020-114-カンナ" = "ああ、顔ならあれを見た方が速いかもしれません。不本意ですが、クロノスの中継ドローンが中に入ったようなので。"
"41020-119-サキ" = "……ん？おい、何見てるんだ。[ruby=携帯式防空ミサイルシステム]MANPADS[/ruby]でも喰らいたいのか？"
"41020-120-モエ" = "くひひ……まあ、そこまで神経質になるなって。"
"41020-121-モエ" = "どうせもう戦況は覆らない。今さら撮られたって、何の問題も無いでしょ。"
"41020-122-モエ" = "どうせなら、連邦生徒会の愚かさについて喧伝でもしてあげたら良いじゃん。"
"41020-123-モエ" = "ってわけで……連邦生徒会、見てる～？"
"41020-124-モエ" = "お前らの考えが間違いだったって、そろそろ分かったんじゃないか？"
"41020-125-サキ" = "私たちがここにいる限り、SRT特殊学園は終わらない！"
"41020-127-ミヤコ" = "サキ、モエ。余計な挑発は慎んでください。"
"41020-128-ミヤコ" = "私たちに必要なのは、戦闘を通じて交渉に有利な立場を手に入れること。それ以外の何かを今行う必要はありません。"
"41020-130-モエ" = "つまんないなぁ……ミヤコはいっつも真面目なんだから。"
"41020-134-サキ" = "……ドローンの駆動音、耳障りだな。そろそろ消し飛ばすとしよう。"
"41020-138-サキ" = "弾薬も結構余ってるし……テストも兼ねて、何発かババっと撃ってみるか？"
"41020-139-モエ" = "サキ～、何か面白そうなこと考えてるじゃん？"
"41020-140-モエ" = "やっちゃう？ド派手にやっちゃう？"
"41020-141-モエ" = "どうせなら弾薬全部使って、打ち上げ花火みたいにしない？"
"41020-142-モエ" = "いやぁ、綺麗だろうなぁ……はあ、はあ……。"
"41020-143-サキ" = "それは良いんだけど……何か忘れているような気が……。"
"41020-149-ミユ" = "も、もしかしてそれ、私のこと……？"
"41020-150-ミユ" = "爆撃、私のいるところは巻き込まないでね……？"
"41020-152-モエ" = "……あ。"
"41020-153-サキ" = "わ、分かってる！忘れたわけじゃないから、心配するな！"
"41020-155-ミユ" = "そ、そっか……。"
"41020-156-ミユ" = "ところで私、もう帰っても良いかな……？相手もいなくなったし……。"
"41020-157-ミユ" = "何だかこの辺り……湿っぽいし、虫も多いし……"
"41020-158-ミユ" = "何だかその、ひとりじゃ怖くって……。"
"41020-159-サキ" = "ミユ。SRTのエリートが、たかが虫のせいで泣き言を言うな。"
"41020-160-サキ" = "いつまでもそんなことを言うなら、今からでもヴァルキューレに行けばいいだろ。"
"41020-161-サキ" = "不快なことも少ない毎日で、安穏と交通整理でもしてればいい。"
"41020-162-ミユ" = "そ、それは、その……。"
"41020-163-サキ" = "……それよりミユ、ドローンは見えてるな？"
"41020-164-サキ" = "高度が測定できたら教えてくれ、すぐに撃墜する。"
"41020-165-ミユ" = "りょ、了解……少し待ってて……。"
"41020-167-ミヤコ" = "サキ、待ってください。不要な射撃は推奨しません。今は補給も期待できない状況なので、周囲を警戒しつつ……"
"41020-168-サキ" = "うるさい！"
"41020-169-サキ" = "どうしてお前が私に命令する！？"
"41020-170-モエ" = "ま、もともと全員同じ1年生だしねぇ。"
"41020-171-モエ" = "連邦生徒会長もいないし[ruby=しがらみ]、柵も[/ruby]無くなったことだし、確かにもう命令を聞く必要も無いかなぁ。"
"41020-172-ミヤコ" = "で、ですが……。"
"41020-174-ミユ" = "……サキちゃん、座標を確認したよ。高度900m、距離2500m、方位0-3-0……"
"41020-175-サキ" = "よし、"
"41020-179-サキ" = "ターゲットロックオン。"
"41020-180-サキ" = "モエ、発射は任せた。"
"41020-181-モエ" = "いやぁ、こういう瞬間は興奮するねぇ……"
"41020-185-モエ" = "さ～て……"
"41020-186-モエ" = "ファイアー！！"
"41020-196-公安局の生徒" = "……中継ドローン、ロストしました。"
"41020-197-カンナ" = "ヴァルキューレの物じゃないとは分かっているだろうに、それでも攻撃するか……"
"41020-198-カンナ" = "雑な奴らだな……どうしてあんなやつらが、SRTに入学できたんだ？"
"41020-199" = "[s] \"元気な子たちだね。\""
"41020-200-カンナ" = "……ご冗談を、「バカ」の間違いでしょう。"
"41020-201-カンナ" = "単なるバカならまだしも、やたらと力を持ったバカです。会話もしにくく、厄介なことこの上無い。"
"41020-202-カンナ" = "こうなったら、各自治区の風紀委員会に支援を要請した方が……"
"41020-206-カンナ" = "まず、ゲヘナの風紀委員会に連絡を――"
"41020-207" = "[s3] \"……任せて、多分大丈夫。\"\n[s4] \"何とかなるかも。\""
"41020-208-カンナ" = "……はい？"
"41020-209-カンナ" = "……はい？"
"41020-210-カンナ" = "動ける人員が5人にも満たない、この状況で……？"
"41020-211" = "[s5] \"キリノ、フブキ、行こう。\"\n[s6] \"RABBIT小隊のみんなを止めに行こう。\""
"41020-214-キリノ" = "はい！……はいっ！？"
"41020-215-フブキ" = "じょ、冗談でしょ……？"
"41020-216-フブキ" = "相手はSRTだよ？"
"41020-221-カンナ" = "……すみませんが、先生。"
"41020-222-カンナ" = "彼女たちは基本的に戦闘員ではなく、平和ボケした生活安全局の所属です。"
"41020-223-カンナ" = "警備局でも、公安局でも太刀打ちできなかったんです。彼女たちだけで、制圧できるとお思いですか？"
"41020-224-カンナ" = "先生の噂は聞いていますが、こんな寄せ集めでは……。"
"41020-225-カンナ" = "エリートとそうでない生徒の間には、到底埋められない隙間があるんですよ。"
"41020-226" = "[s] \"私からしたら、みんな「生徒」に変わりは無いよ。\""
"41020-230-カンナ" = "……そうですか。"
"41020-231-カンナ" = "責任はシャーレが負うということですし……まあ、無理に止めはしません。"
"41020-235-カンナ" = "……まだ戦闘可能な者たちに告ぐ。これよりシャーレの先生の指示に従い、生活安全局の生徒をサポートせよ！"
"41020-237-フブキ" = "ちょっ、ちょっと待った！マジで！？マジで言ってる！？"
"41020-238-フブキ" = "嘘でしょ、絶対すぐやられるって！先生、正気！？"
"41020-239" = "[s7] \"正気正気。\"\n[s8] \"大丈夫、きっとできるよ。\""
"41020-240-キリノ" = "フブキ、大丈夫です！ [USERNAME]先生の指揮があるなら、何とかなります！多分！！"
"41020-241-キリノ" = "フブキ、大丈夫です！ [USERNAME]先生の指揮があるなら、何とかなります！多分！！"
"41020-242-キリノ" = "そもそも、市民の安全を守るため……この状況、放っておくわけにはいきません！"
"41020-243-フブキ" = "あーもう、計算が狂った……こんなことなら、仮病でも使っておけば……。"
"41020-244-キリノ" = "まあまあ。これで作戦を成功させたら、特別休暇とか貰えるかもしれませんし。"
"41020-245-キリノ" = "それに、警備局への転科のチャンスだって頂けるかもしれません！"
"41020-246-フブキ" = "後者はどうでも良いけど、まあ仕方ない……。"
"41020-247-フブキ" = "ちょっとだけ、試しにやってみよっか？"
"41020-248-キリノ" = "生活安全局、"
"41020-249-キリノ" = "出動します！"
