[translation]
"41025-2-サキ" = "……ん？"
"41025-3-モエ" = "どしたの？何か問題でもあった？"
"41025-4-サキ" = "何か、また兵が出てきた。"
"41025-5-サキ" = "もう誰も残ってないと思ってたけど……"
"41025-6-サキ" = "まさかとは思うが、生活安全局……？"
"41025-7-モエ" = "じゃあザコじゃん、聞いて損した。"
"41025-8-モエ" = "それくらいだったら、ミユがてきとうに処理してくれるでしょ。"
"41025-9-サキ" = "そうなんだけど、何か気になるっていうか……。"
"41025-10-サキ" = "……まあ、心配し過ぎか。"
"41025-12-ミユ" = "暗い、怖い……早く学校に帰りたい……。"
"41025-13-ミユ" = "……もう学校、閉鎖されたんだった。私が帰れる場所は……。"
"41025-14-ミユ" = "こうなったら今さらもう、ヴァルキューレにも……。"
"41025-15-ミユ" = "このまま私は、寂しく忘れられていくんだろうな……。"
"41025-16-ミユ" = "私たち、いつまでこうやって……"
"41025-20-ミユ" = "……？"
"41025-24-ミユ" = "え、煙幕弾……？"
"41025-28-ミユ" = "きゃあっ！？"
"41025-29-ミユ" = "ど、どこから……？だって相手はもう……"
"41025-30-ミユ" = "連絡も何も無かったのに……と、とにかく状況の報告を……！"
"41025-37-ミユ" = "だ、誰ですか……！？"
"41025-39-不審者" = "えーっと……"
"41025-40-不審者" = "ほら、私だよ私。RABBIT小隊の……"
"41025-41-ミユ" = "RABBIT小隊……"
"41025-42-ミユ" = "え、サキちゃん？"
"41025-44-不審者" = "そうそう！"
"41025-46-不審者" = "何か間違って煙幕弾が爆発してたみたいだから、様子を見に来たって感じ。"
"41025-47-ミユ" = "で、でもサキちゃん、さっき「持ち場から絶対離れるな」って言ってたような……？"
"41025-48-ミユ" = "それに、声が……"
"41025-50-不審者" = "あー、ちょっと煙を吸ったせいで……げほっ、げほっ！"
"41025-52-不審者" = "ま、とにかく大丈夫だよ。だから銃は一旦置いておこう？"
"41025-53-ミユ" = "（……怪しい。口調も声も、サキちゃんとは全然……）"
"41025-54-ミユ" = "（こういう時こそ、合言葉を……）"
"41025-58-ミユ" = "……「クローバー」。"
"41025-60-不審者" = "……え？"
"41025-61-ミユ" = "サキちゃんは、ちゃんと知ってるでしょ？"
"41025-62-ミユ" = "こ、答えられなかったら、すぐに撃ちます……！"
"41025-64-不審者" = "「クローバー」！"
"41025-65-ミユ" = "……え、えっ？"
"41025-67-不審者" = "何か言った？この辺雑音が多くてよく聞こえなくてさ。ところで……この言葉に対する答え、ちゃんと知ってるよね？"
"41025-68-ミユ" = "え、そ、そんな……！？"
"41025-70-不審者" = "答えられなかったら、撃っちゃうよ？"
"41025-71-ミユ" = "に、「ニンジン」！"
"41025-73-不審者" = "ふーん、なるほどね。了解。"
"41025-74-ミユ" = "え、あ、あっ……？"
"41025-76-不審者" = "心理戦で追い込まれると弱いかも……先生の言う通りだったね。"
"41025-83-フブキ" = "合言葉、教えてくれてありがと。じゃあね、ウサギの狙撃手ちゃん。"
"41025-88-ミユ" = "だ、騙された……！？"
"41025-93-サキ" = "……何だ、今の銃声？近くないか？"
"41025-94-サキ" = "まさか、ミユがやられた……？"
"41025-95-モエ" = "まっさかぁ、生活安全局でしょ？装備とかの面も含めて、ミユがやられるレベルじゃないよ。"
"41025-96-サキ" = "それはそうだろうけど……ミユとの連絡が取れない。"
"41025-100-サキ" = "行ってくる。"
"41025-101-サキ" = "モエ、支援は頼んだ。"
"41025-102-モエ" = "いや支援も何も、もう弾薬残ってないけど？"
"41025-103-サキ" = "……は、どうして？"
"41025-104-モエ" = "さっき言ったじゃん、「ド派手に」「全部使って」って。"
"41025-105-モエ" = "ドローン追撃する時に、全部パーッとね♪"
"41025-106-サキ" = "はぁ！？おまっ、嘘だろ！？"
"41025-107-モエ" = "後のことなんて考え無しに、全部一回につぎ込む……"
"41025-108-モエ" = "その火花はそりゃあ美しいよね、興奮する……はあ、はあ……。"
"41025-109-サキ" = "本当に文字通り「全部」使うやつがいるかバカ！後のこと考える必要があるだろ、今は！"
"41025-110-サキ" = "この状況で弾薬がゼロって、後はどうしたら――"
"41025-117-ミヤコ" = "今の爆発は……？"
"41025-121-ミヤコ" = "サキ、モエ、どういう状況ですか？報告を！"
"41025-125-ミヤコ" = "応答が無い……奇襲されましたか。"
"41025-126-ミヤコ" = "ですから警戒をと言ったのですが……"
"41025-127-ミヤコ" = "仕方ありません、まずは拠点を移して応戦を……"
"41025-132-キリノ" = "止まってください！"
"41025-133-キリノ" = "先生の言った通り、ここでしたか……！動かないように！"
"41025-134-キリノ" = "市民の皆さんが使う公園の占拠、そして違法な武器を用いてのデモ……"
"41025-135-キリノ" = "申し訳ありませんが、拘束させていただきます！"
"41025-136-キリノ" = "本官の指示に従い、手を上げて投降してください！"
"41025-142-ミヤコ" = "（面倒なことになりましたね……もうここまで来ていたとは）"
"41025-143-ミヤコ" = "（武装は制式拳銃だけ……恐らく、初弾は回避できるはず……）"
"41025-147-キリノ" = "う、動かないでください！本当に撃ちますよ！？"
"41025-148-ミヤコ" = "……言いなりには、なりません！"
"41025-154-キリノ" = "は、発砲します！"
"41025-164-ミヤコ" = "っ！！銃口の向きは、見えていたのに……！？"
"41025-165-ミヤコ" = "回避されること前提で、直前までわざと違う方向を……？"
"41025-166-ミヤコ" = "油断したのは、私も……でしたか……。"
"41025-171-キリノ" = "……め、命中しました！？！？"
"41025-172-キリノ" = "も、もしかして本官も、遂に射撃能力が向上したのでしょうか……？"
"41025-173-キリノ" = "やはり努力は実を結ぶもの……。"
"41025-174-キリノ" = "そして正義もまた、いつだって勝利するもの……ということですね！"
"41025-178-カンナ" = "信じられません……。"
"41025-179-カンナ" = "まさか本当に生活安全局の生徒だけで、SRTを制圧するとは……。"
"41025-180" = "[s] \"二人とも頑張ってくれたからね。\""
"41025-181-カンナ" = "なるほど……これが[USERNAME]先生のお力。その上、姿勢も謙虚と来るとは。"
"41025-182-カンナ" = "生徒たちの噂もまた、本当だったということですね。"
"41025-183-カンナ" = "……ヴァルキューレ警察学校を代表して、感謝いたします。"
"41025-192-キリノ" = "見ましたか、先生！？私の完璧な射撃！"
"41025-193-キリノ" = "まさに警備局のみなさんのような、鮮やかな一撃でした……！"
"41025-194-フブキ" = "いやー、あんな古い手法がまだ通じるとはね……。"
"41025-195-フブキ" = "ま、先生の作戦ありきとはいえ……上手くできたみたいで何より。"
"41025-196-フブキ" = "これはもう、20日分くらい特別休暇を貰えるんじゃないんかな。ふふっ……。"
"41025-198-カンナ" = "……はぁ。"
"41025-199-カンナ" = "貴様らの殊勲は認めよう。しかしそれは、私のような立場に決められるようなことではない。もっと上層部の方々の管轄だ。"
"41025-200-カンナ" = "ご苦労だった。報酬については、来月の賞罰の発表を待つように。"
"41025-202-フブキ" = "何だ、すぐ貰えるわけじゃないのか……"
"41025-203-フブキ" = "ガッカリだよ。"
"41025-204-キリノ" = "ですが来月なんてもうすぐです！もしかしたら本当に警備局に……！"
"41025-205-フブキ" = "いやー、私そっちは要らない……"
"41025-206-フブキ" = "むしろ断る……。"
"41025-211-モエ" = "あんな頭の悪そうなやつらに、私たちが……？"
"41025-212-サキ" = "お前が言うな、弾薬を一気に使い果たす、なんて相当頭の悪い行動をしたくせに。"
"41025-213-モエ" = "何言ってるのさ、一瞬の輝きより大事なものなんて無いっての！"
"41025-214-ミユ" = "もう終わりなんだ……"
"41025-215-ミユ" = "SRTも、RABBIT小隊も、私も……全部奪われて、寂しく消える運命なんだ……。"
"41025-216-ミヤコ" = "……。"
"41025-217" = "[s1] \"初めまして。\"\n[s2] \"SRT特殊学園の生徒たち……だよね？\""
"41025-218-サキ" = "……お前と話すことなんて一つも無い！"
"41025-219-サキ" = "……お前と話すことなんて一つも無い！"
"41025-220-モエ" = "何なに、冷やかし？それともバカにしに来たの？"
"41025-222-ミヤコ" = "……あなたがあの生活安全局を指揮した、「大人」ですか？"
"41025-223" = "[s] \"うん、そうだよ。\""
"41025-224-ミヤコ" = "……そうですか。あなたがあの、多くの生徒たちの悩みを解決し、生徒たちから信頼されている、超法規的捜査権を持った「シャーレの先生」……。"
"41025-228-ミヤコ" = "……先生。私たちは、あなたのような大人が一番嫌いです。"
"41025-229-サキ" = "地獄に落ちろ。"
"41025-230-モエ" = "もう二度と会わないだろうね。"
"41025-237" = "[ns] \"うーん、元気だ。\""
"41025-238-カンナ" = "気にする必要はありません。負かされたことでイライラしてるんでしょう。"
"41025-239" = "[s] \"あの子たちは、これからどうなるの？\""
"41025-240-カンナ" = "まずは取り調べです。"
"41025-241-カンナ" = "普段ならその後、ヴァルキューレが処罰を決める流れなのですが……。"
"41025-242-カンナ" = "ある程度連邦生徒会が関わりましたので、恐らくそうはなりませんね。防衛室長が処遇を決めることになるかと。"
"41025-243-カンナ" = "ご希望でしたら、取り調べの様子を見ることも可能かと思います。"
"41025-244-カンナ" = "では、ひとまずお疲れ様でした。"
"41025-250" = "次回;それぞれの事情"
