[translation]
"41050-1" = "第5話;消えない不信"
"41050-2" = "ヴァルキューレ警察学校・ロビー"
"41050-8-ミヤコ" = "あ……みんな無事でしたか。"
"41050-9-サキ" = "なんだ、ミヤコもいたのか。"
"41050-10-ミユ" = "ミヤコちゃん……。"
"41050-12-モエ" = "やーっと終わったよ……終わったんだよね？"
"41050-13-モエ" = "さっさと帰りたいんだけど、飴も無くなっちゃったし……。"
"41050-14-サキ" = "そんな悠長なことを言ってる場合か。"
"41050-15-サキ" = "私たちの処分については、これから言い渡されるんだろ？"
"41050-16-サキ" = "あの感じだと……まあ最低でも、退学くらいは覚悟しないとな。"
"41050-17-モエ" = "そんなこと言ったって、どうせSRT特殊学園はもう無いんでしょ。退学処分になったところで、何も変わらないじゃん。"
"41050-19-ミユ" = "で、でも、それが「最低」ってことは……。"
"41050-20-モエ" = "ま、もっとヤバい可能性もあるね。"
"41050-21-モエ" = "地下の怪しい施設に連れていかれて色々させられるとか、色んな実験台にさせられるとか……。"
"41050-22-ミユ" = "！？！？"
"41050-23-ミユ" = "も、もう終わりだぁ……。"
"41050-29-ミヤコ" = "すみません、私がもう少し上手くやれていたら……。"
"41050-30-ミヤコ" = "みんな、こんな目に遭わずに済んだのに……。"
"41050-31-サキ" = "……おい、どうしてお前が謝るんだ？"
"41050-32-モエ" = "なに、責任とか感じてるの？"
"41050-33-サキ" = "ミヤコ、勘違いするな。学園の閉鎖が決まったあの瞬間から、お前は小隊長でも何でもない。"
"41050-34-サキ" = "なのに、責任とか勝手に感じられても困る。別に今はそんなこと期待してないし。"
"41050-35-ミヤコ" = "それは……でも、私は……。"
"41050-36" = "[s] \"お疲れ様。\""
"41050-37-モエ" = "あ、あんたは……"
"41050-38-サキ" = "しゃ、シャーレの……？"
"41050-39-ミユ" = "ひっ……！？"
"41050-40" = "[s] \"……何かもう既にごめん。\""
"41050-42-ミヤコ" = "まだいたんですね、先生。"
"41050-43-ミヤコ" = "ヴァルキューレに何か用事ですか？"
"41050-44-ミヤコ" = "……それとも、まさかとは思いますが。私たちに用事が？"
"41050-45" = "[s] \"うん。行政委員会から、今回の処分の件について。\""
"41050-47-ミユ" = "……っ！"
"41050-48-モエ" = "ま、どんな処分でも別に構わないけど。"
"41050-49-サキ" = "……。"
"41050-53" = "[ns1] \"とりあえず、全員釈放。\"\n[ns2] \"もう自由だよ。好きなところに行っても大丈夫。\""
"41050-56-ミヤコ" = "……はい？"
"41050-57-モエ" = "……釈放？処罰は？"
"41050-58-サキ" = "待て、つまり私たちはSRTに戻れるのか？"
"41050-59" = "[s] \"いや。それはできないんだけど……。\""
"41050-60-サキ" = "何だ、喜んで損した。"
"41050-64-ミヤコ" = "公園での作戦成功……その功績の分、シャーレが処分を決めることになったということですか？"
"41050-65-ミヤコ" = "……理解しがたいですが、状況は把握しました。"
"41050-66-ミヤコ" = "それで、先生は私たちに何をさせたいのですか？"
"41050-67" = "[s] \"何と言われても……みんなは何がやりたい？\""
"41050-68-サキ" = "何でこっちに聞き返すんだ……。"
"41050-69-ミユ" = "SRTに帰れないなら、別にどこに行ったところで……。"
"41050-70-モエ" = "とりあえず私はどこかで休みたい。もうクタクタだよー……。"
"41050-71" = "[s] \"シャーレで休んでも良いし、そこで生活しても良いよ？\""
"41050-72-サキ" = "……は？"
"41050-73-モエ" = "自分のところに女子生徒たちを集めて、何をする気？"
"41050-75-ミヤコ" = "……信じられません。"
"41050-76-ミユ" = "や、やっぱり、この前のことを根に持って……"
"41050-77-モエ" = "いやー、散々ハレンチなことをさせられるんだろうな～。"
"41050-78-サキ" = "そういえばシャーレには、やたらと盗聴器が設置されてるって噂を聞いたことがある。"
"41050-79-ミユ" = "わ、私たちの生活を盗聴して、何を……！？"
"41050-80-モエ" = "普通のマンガじゃ描けないようなことを強要させられたり？"
"41050-81" = "[s3] \"しないしないしない！！\"\n[s4] \"話が変な方向に加速してる！！\""
"41050-84-ミヤコ" = "……せっかくの厚意ですが、その提案は受けられません。"
"41050-85-ミヤコ" = "私たちがシャーレで快適な生活なんて送っていては、本来の目的である「連邦生徒会への抗議」が成り立ちませんから。"
"41050-87-サキ" = "シャーレに行ったところで、ちゃんとした規律や訓練があるわけじゃないんだろ？"
"41050-88-サキ" = "一日二日ならともかく、そんな場所にずっといるのは耐えられない。"
"41050-89-モエ" = "どうせ危険物の取扱いは禁止されてるだろうし……。"
"41050-90-ミユ" = "きゅ、急に信じるのは、ちょっと……。"
"41050-91" = "[s] \"そしたら、あの公園でキャンプとかどう？\""
"41050-93-ミヤコ" = "あの公園……デモをした、あの場所ですか？"
"41050-94-サキ" = "「子ウサギ公園」か……私はそれで構わない。環境的に、SRTの野戦訓練場みたいなものだし。"
"41050-95-モエ" = "私も別に。っていうか装備類、あそこに置いてきちゃったし。"
"41050-96-ミユ" = "わ、私も……。"
"41050-98-ミヤコ" = "ある意味ではデモの続きになりますし、私たちとしてはそれで構わないのですが……。"
"41050-99-ミヤコ" = "先生は、それで良いのですか？"
"41050-100" = "[s5] \"私はもちろん大丈夫だけど……。\"\n[s6] \"みんなの方こそ、それでも大丈夫？何かできることがあれば……\""
"41050-101-ミヤコ" = "構いません。私たちは、ただ無力なだけの子どもではありませんから。"
"41050-102-ミヤコ" = "構いません。私たちは、ただ無力なだけの子どもではありませんから。"
"41050-103-ミヤコ" = "それに……あらためてになりますが、私たちは先生を信頼していません。"
"41050-104-ミヤコ" = "こうして温情をかけてもらったところで、それが変わったりもしませんので。"
"41050-105" = "[s7] \"うん、それについては大丈夫。\"\n[s8] \"みんなが辛くないなら、それに越したことは無いから。\""
"41050-110-ミヤコ" = "……変な人。"
"41050-111-ミヤコ" = "それでは……。"
"41050-112-サキ" = "次に会った時は敵だからな！"
"41050-113-モエ" = "いや、最初から敵じゃん。"
"41050-120-ミユ" = "ま、待って……！？置いていかないで……！"
"41050-122" = "次回;食料調達を始めよう"
