[translation]
"41185-2-サキ" = "[ruby=Tango]T3[/ruby]、ダウン！"
"41185-4-ミヤコ" = "確認しました、RABBIT2は次の遮蔽物まで前進を！"
"41185-5-サキ" = "了解！"
"41185-6-ミヤコ" = "それ以外の隊員は、5秒間現在地で！"
"41185-7-ミヤコ" = "3……2……1……"
"41185-12-ミヤコ" = "サキ、今です！フォックストロット投下！"
"41185-13-サキ" = "了解！閃光弾、いくぞっ！"
"41185-19-ミヤコ" = "ミユ、5時の方向にスナイパーです！"
"41185-20-ミユ" = "あ、了解……！"
"41185-21-ミユ" = "ごめん、その前にリロードする……！"
"41185-22-ミヤコ" = "了解です。サキ、援護射撃を！"
"41185-23-サキ" = "任せろ！"
"41185-34-警備局の生徒A" = "あいつら何者！？"
"41185-35-警備局の生徒A" = "くそっ、この数で圧倒できないって……どういう状況なわけ！？"
"41185-36-警備局の生徒B" = "こっちのホームで押されてるとか、意味が分からない……！"
"41185-37-警備局の生徒B" = "このままじゃエントランスまで押される！"
"41185-38-警備局の生徒A" = "大丈夫、もうすぐ警備局の増援が来るはず！"
"41185-39-警備局の生徒A" = "到着し次第、波状攻撃で押し出すよ！"
"41185-45-ミヤコ" = "……西側から多数の足音を確認。"
"41185-49-ミヤコ" = "モエ、ヴァルキューレの室温感知器はハッキングできますか？"
"41185-50-モエ" = "セキュリティ全体ならともかく、それくらいなら問題無し！"
"41185-51-ミヤコ" = "数値を操作してください、誤作動を誘発させます。"
"41185-52-モエ" = "何度にする？"
"41185-53-ミヤコ" = "摂氏900度で。"
"41185-54-モエ" = "OK！"
"41185-57-警備局の生徒A" = "なっ、水……！？"
"41185-58-警備局の生徒B" = "スプリンクラーが故障！？"
"41185-59-警備局の生徒A" = "ってことは……"
"41185-63-警備局の生徒A" = "まずい、防火扉が……！"
"41185-68-警備局の生徒B" = "自分たちの学校に閉じ込められるとか……。"
"41185-69-警備局の生徒B" = "これじゃ警備局も合流できないじゃん。"
"41185-70-警備局の生徒A" = "あ、でもこれは手動で開けられるんじゃ？"
"41185-71-警備局の生徒A" = "よし、じゃあさっさと……"
"41185-75-警備局の生徒B" = "……何これ？あいつらの忘れ物？"
"41185-76-警備局の生徒A" = "C4じゃない？何かリチウムバッテリーみたいのが付いてるけど。"
"41185-77-警備局の生徒B" = "……待って、リチウム？ってことは水に触れたら……"
"41185-81-警備局の生徒A" = "……あ。"
"41185-91-フブキ" = "ふぁ、ねっむ……。"
"41185-92-フブキ" = "全くこんな夜中に騒ぎとか……。"
"41185-93-フブキ" = "警察学校の本館に侵入するとか、大胆なやつもいたもんだ……。"
"41185-94-フブキ" = "でもどうして私たちまで……警備局の方で何とかしてくれれば良いのに……。"
"41185-95-フブキ" = "てきとうにパトロールっぽい動きでもして、さっさと帰ろっと……。"
"41185-99-フブキ" = "……何あれ？"
"41185-106-フブキ" = "……え、馬鹿にされてる？"
"41185-107-フブキ" = "にしても、何て悪質な罠……。"
"41185-108-フブキ" = "相当なバカじゃない限り、こんなのに引っ掛かるやつは――"
"41185-110-サキ" = "それ、「マスタードーナッツ」の限定ドーナッツ。しかもマシュマロ入り。"
"41185-111-フブキ" = "……マジで？"
"41185-115-フブキ" = "いっただっきま――"
"41185-120-フブキ" = "だよね～！？"
"41185-127-サキ" = "……まさか本当に行けるとはな。"
"41185-128-ミユ" = "私もどうかと思ったけど、ミヤコちゃんの命令だったし……。"
"41185-129-ミユ" = "……でも、成功だね。"
"41185-131-ミヤコ" = "まあ、私としても賭けでしたが……。"
"41185-132-ミヤコ" = "どうにかなっているのも、みんなのおかげです。"
"41185-133-ミヤコ" = "恐らく私以外の誰かが指揮を執っても、結果は同じだったと思いますが……。"
"41185-134-サキ" = "だから誤魔化すなっての。"
"41185-135-ミヤコ" = "えっ、と……すみません……？"
"41185-136-サキ" = "そうじゃない、これは明らかにミヤコが出した結果だ。他の誰かとかじゃない、誤魔化すな！"
"41185-137-サキ" = "最適解を出したのはお前だ、それは間違いないだろ？"
"41185-139-モエ" = "そうだよ、あんたの言う通りに動いた結果なんだから。"
"41185-140-ミユ" = "ミヤコちゃんのことを、信じたからこそだよ。"
"41185-141-サキ" = "まあ、今まで色々言ったのはその……悪かったよ。"
"41185-142-サキ" = "でも少なくとも今のお前は隊長だ、それは保証する。"
"41185-147-ミヤコ" = "……そうでしたか。"
"41185-148-ミヤコ" = "ですが、やはり私だけの功績ではありません。"
"41185-149-ミヤコ" = "みんなで動いてるからこそ、ですから。"
"41185-151-サキ" = "ほんっと話の通じない……。"
"41185-152-モエ" = "ま、いつも通りでしょ。"
"41185-154-ミヤコ" = "話が長くなってしまいましたね……"
"41185-155-ミヤコ" = "先を急ぎましょう！"
"41185-161-キリノ" = "止まってください！"
"41185-162-キリノ" = "まさかとは思いましたが……侵入者とは、"
"41185-163-キリノ" = "あなたたちのことでしたか！"
"41185-168-ミヤコ" = "あなたは、確か……"
"41185-169-キリノ" = "先日はお世話になりました。生活安全局のエース、キリノです！"
"41185-170-キリノ" = "こんな夜中に校舎への不法侵入など、本官は許しませんよ！"
"41185-175-サキ" = "……熱血っぽいのが来ちゃったな。"
"41185-176-ミユ" = "……ミヤコちゃん、どうする？"
"41185-178-ミヤコ" = "（先日は撃たれましたが……たしか情報だと、この方の射撃は……）"
"41185-179-ミヤコ" = "……無視します。引き続き前進。"
"41185-185-キリノ" = "え、えっ？ちょっ、どういうことですか！？"
"41185-186-キリノ" = "ほ、本当に撃ちますよ！？撃たないといけないんですけど！？"
"41185-187-キリノ" = "え、えぇぃっ……！"
"41185-196-フブキ" = "全弾命中せず、かぁ……。"
"41185-197-キリノ" = "うぅ……この間はカッコよく当てられたのに……。"
"41185-198-キリノ" = "目の前まで来た相手を、みすみす逃してしまうだなんて……。"
"41185-199-キリノ" = "……ところでフブキは、どうしてそこで段ボールを被ったまま倒れてたんです？"
"41185-200-フブキ" = "まあ、めんどくさくてって言うかなんて言うか……あんまり記憶に無い。"
"41185-206-フブキ" = "とりあえずキリノ、これ食べる？"
"41185-208" = "次回;大人の時間"
