[translation]
"41190-1" = "第19話;大人の時間"
"41190-2" = "ヴァルキューレ警察学校・屋上"
"41190-4-ミヤコ" = "こちらRABBIT1、現在時刻0100。たっ[ruby=Objective Rally Point]た今ORPに到[/ruby]着しました。"
"41190-5-ミヤコ" = "キャンプRABBIT、航空支援はまだですか？"
"41190-6-モエ" = "ごめん、ポイントが変わって色々遅くなった！"
"41190-7-モエ" = "あと5分待って！"
"41190-8-ミヤコ" = "了解です。"
"41190-9-ミヤコ" = "RABBIT2、バリケードの設置をお願いします。屋上への通路を封鎖しておきましょう。"
"41190-14-サキ" = "もうやっておいた。念のため、階段のところに地雷も撒いておいたけど……"
"41190-18-サキ" = "……早かったな。"
"41190-19-ミユ" = "も、もう扉のところまで……！？"
"41190-20-ミユ" = "これ、5分も持つかな……？"
"41190-25-モエ" = "追い詰められた屋上、閉ざされた扉、その扉を叩く人々、そして中々来ないヘリ……"
"41190-26-モエ" = "先週見たゾンビ映画と一緒だ、くひひ……。"
"41190-27-サキ" = "……一応聞くけど、それどんな結末だった？"
"41190-28-モエ" = "ヘリにぶら下がったゾンビのせいで、墜落して全滅。"
"41190-29-サキ" = "聞いた私がバカだった！"
"41190-30-ミユ" = "で、でも、ここにゾンビはいないから……"
"41190-32-？？？" = "……またしても貴様らか。"
"41190-33-ミユ" = "ぞ、ゾンビ！？"
"41190-39-カンナ" = "誰がゾンビだ。せめて公安局長と呼べ。"
"41190-40-ミヤコ" = "公安局長……！"
"41190-41-サキ" = "扉が開いてないのに、どうやってここまで？"
"41190-42-カンナ" = "建物の外壁をよじ登ってきた。"
"41190-43-サキ" = "マジかよ、10階建て超えてるぞここ……なんつー無茶を……。"
"41190-44-サキ" = "そんな訓練ヴァルキューレには無いだろうに、ハーネスも無しで？"
"41190-45-カンナ" = "犯罪者を捕まえるためなら、公安局は何でもする。"
"41190-46-カンナ" = "まさかヴァルキューレに潜入しておいて、おとなしく帰れるとは思ってないだろうな？"
"41190-50-カンナ" = "貴様らはすでに包囲されたも同然。無駄な抵抗はやめろ。"
"41190-52-ミヤコ" = "……。"
"41190-53-カンナ" = "あんな目にあったばっかりで全く懲りないとは、気は確かか？"
"41190-54-カンナ" = "今のキヴォトスは、貴様らを必要としていない。無駄な抵抗をして、迷惑をかけ続けるのはやめろ。"
"41190-55-カンナ" = "こんな犯罪まがいのことをして、今度こそ連邦生徒会から学籍データを抹消させられても――"
"41190-56-ミヤコ" = "公安局長、そちらの犯罪についてはいかがお考えですか？"
"41190-62-ミヤコ" = "公安局の取引記録を発見しました。"
"41190-63-ミヤコ" = "「子ウサギタウン」の再開発のため、放浪者たちを追い出す。その代わりにカイザーグループとの間で違法リベートが発生していた……そうですね？"
"41190-64-カンナ" = "どうして、それを……。"
"41190-65-サキ" = "そりゃ、いきなりヴァルキューレが新しい装備に変えたもんだから。何かあると思うのは自然なことだろ。"
"41190-66-ミヤコ" = "キヴォトスの治安を担当するヴァルキューレ警察学校が、私企業との取引において犯罪行為に手を染める……これは、確実に問題かと思われます。"
"41190-67-ミヤコ" = "連邦生徒会の定めた、公的な規則に従わない処理……公安局長、これをあなたが知らなかったはずがありません。"
"41190-69-ミヤコ" = "これはヴァルキューレ警察学校の理念に反する、重大な犯罪です！"
"41190-75-カンナ" = "っ……。"
"41190-76-カンナ" = "……本当に言いたい放題だな、貴様たちは。"
"41190-77-カンナ" = "公的な規則……そうだな。"
"41190-78-カンナ" = "貴様の言う通り、ヴァルキューレは公的な規則に従い、公正であるべきだろう。"
"41190-79-カンナ" = "……しかし世の中は、貴様らが思うほど公正ではない。"
"41190-80-カンナ" = "貴様らには特権がある。そしてその上で正義を論じている間に、私たちが何をしていたか知っているか。汚い現場で、どれだけ妥協に塗れながら公務を処理していたことか！"
"41190-81-カンナ" = "それが社会だ、現実だ！"
"41190-82-カンナ" = "手を汚さずに、正義を掲げ続けることなどできない！"
"41190-83-カンナ" = "貴様らのようなガキに、それが分かるか！その判断をせざるを得なかったこの気持ちが！"
"41190-87" = "[ns] \"……カンナ。\""
"41190-88-カンナ" = "この声は……"
"41190-89-カンナ" = "……先生、あなたでしたか。"
"41190-90" = "[s1] \"信念を貫くのは、大変かもしれない。それでも……\"\n[s2] \"最終的に自分の未来は、自分で判断し続けていくものだよ。\""
"41190-91-カンナ" = "それでも……自分の信念だけに従っていたら、私は全てを失ってしまう……！"
"41190-92-カンナ" = "それでも……自分の信念だけに従っていたら、私は全てを失ってしまう……！"
"41190-93-カンナ" = "こんな中途半端な立ち位置で！私には、何もできない！！"
"41190-94" = "[s] \"RABBIT小隊のみんなは、ほぼゼロからのスタートだったよ。\""
"41190-98-カンナ" = "……。"
"41190-99" = "[s] \"大丈夫。状況は大変だろうけど、辛いだろうけど。\""
"41190-101" = "[ns] \"それでも行き先は、自分で決められるよ。\""
"41190-107-サキ" = "……ふぅん、真っ当なこと言うじゃん。"
"41190-108-サキ" = "でもそうだな、最後は自分で決めていくものだ。"
"41190-109-ミユ" = "ずっと不安で、怖かったけど……"
"41190-110-モエ" = "ま、自分たちで決めたことだからね。"
"41190-111-ミヤコ" = "……ありがとうございます、先生。"
"41190-119-ミヤコ" = "公安局長。あなたが言う「正義」は、きっと間違っていないでしょう。ただ私が思うものとは、違うというだけで。"
"41190-120-ミヤコ" = "ですが、その根っこを誰かのせいにし続けていては、いつか色褪せてしまうと思います。「どんな判断をし続けてきたのか」、それがきっと……"
"41190-121-ミヤコ" = "[ruby=SRT]私たち[/ruby]と[ruby=ヴァルキューレ]、あなたの[/ruby]違いです。"
"41190-122-カンナ" = "……。"
"41190-126-モエ" = "ミヤコ、お待たせ！ポイント上空に到着した！"
"41190-127-ミヤコ" = "……来ましたか。"
"41190-128-ミヤコ" = "総員、ハーネスを準備。順番に離脱します。"
"41190-134-サキ" = "装着完了、上げて！"
"41190-135-モエ" = "しっかり捕まってなっ！"
"41190-140-ミヤコ" = "……それでは失礼します、公安局長。"
"41190-141-ミヤコ" = "次回はできれば、もっと良い形で。"
"41190-147-カンナ" = "始末書を、用意しておくとするか。"
"41190-149" = "子ウサギ公園"
"41190-153-ミヤコ" = "こちらRABBIT1、現在時刻0145。キャンプRABBITに到着。"
"41190-154-ミヤコ" = "負傷者無し、離脱者無し、「クローバー」も無事確保。"
"41190-160-ミヤコ" = "……作戦を終了します、お疲れ様でした。"
"41190-161" = "[s] \"無事で良かった、お疲れさま。\""
"41190-166-サキ" = "いやマジで疲れた、もう倒れそう……。"
"41190-167-ミユ" = "私も、"
"41190-168-ミユ" = "眠くて……もう……。"
"41190-173-サキ" = "ミユ、いくら何でも装備くらい外せ……。"
"41190-174-サキ" = "あと作戦報告書と、洗顔と、歯磨きと……。"
"41190-175-サキ" = "それから、えっと……あー、もう無理……。"
"41190-176-モエ" = "あー、疲れた……私も眠くなってきた。"
"41190-177-モエ" = "とりあえず通信機器の電源だけ落として……。"
"41190-184-ミヤコ" = "みんな、頑張りましたもんね。"
"41190-191-ミヤコ" = "……ではお伝えした通り、「クローバー」は先生にお渡しします。"
"41190-192-ミヤコ" = "事件の黒幕は分かりませんでしたが……公安局長が取り込まれたほどです、相当頭の回る方がいる気がします。"
"41190-193-ミヤコ" = "大人の世界のことはまだ分かりませんが……まだ子どもである私にできることは、一旦ここまでです。"
"41190-194-ミヤコ" = "先生、後はお願いします。"
"41190-195" = "[s] \"うん、任せて。\""
"41190-197" = "（その後、眠った生徒たちをテントの中に運んでから、シャーレに戻った）"
"41190-201" = "（……ミヤコから受け取った証拠品は、どうにかしておこう）"
"41190-203" = "次回;狐穴"
