[translation]
"10009100-1" = "後日談その3;究極の親子丼！？"
"10009100-4-親子丼職人" = "親子丼作りに一生を捧げてきたが……。"
"10009100-5-親子丼職人" = "何も浮かばない……。#n私に究極の親子丼は作れないというのか……。"
"10009100-6-親子丼職人" = "ふわふわでトロトロなだけでは、#nこれからの時代、生き抜いていくことは難しい……。"
"10009100-7-親子丼職人" = "何か新しい要素を取り入れたら変わるのだろうか……。#nそうだ！ここは一つ、はじけるようなアクセントを試してみよう！"
"10009100-12-親子丼職人" = "そうと決まったら今日は店仕舞いにして、新しいレシピの研究だ！"
"10009100-19-親子丼職人" = "よし、次は最近話題のチョコレートバーを……んんっ！#nこれだ、これこそ私が探し求めていたものだ！"
"10009100-21-親子丼職人" = "ただのチョコレートにはない、口の中ではじけるこの感覚……#nクセになりそうだ。"
"10009100-22-親子丼職人" = "これの感覚を再現できたら、新感覚の親子丼が誕生すること間違いなし！"
"10009100-23-親子丼職人" = "しかし、いったいどんな食材を使って再現したものか……。"
"10009100-24-親子丼職人" = "今までの親子丼の常識を覆すような発想……うーん。#n親子丼のことだけを考えてきた人生だから、なかなか浮かばないな……。"
"10009100-29-親子丼職人" = "そうだ、若者に意見を聞いてみよう！"
"10009100-33-親子丼職人" = "……おっ。"
"10009100-34-親子丼職人" = "そこの学生さん、"
"10009100-35-親子丼職人" = "ちょっと聞きたいことがあるんだが大丈夫かい？"
"10009100-36-スズミ" = "は、はい。#n私でお役に立てることでしたら。"
"10009100-39-スズミ" = "親子丼に刺激的なものを取り入れたい……ですか？"
"10009100-40-親子丼職人" = "そうなんだよ！最近は話題性のある料理が人気を集めてるから、親子丼にも何か刺激的な新感覚を取り入れたいと思ってな！"
"10009100-41-スズミ" = "なるほど……刺激的、かつ新感覚……。"
"10009100-42-親子丼職人" = "こう、キラッと目を引くようなものはないかな？#nお客さんが一度味わったら忘れられないような……"
"10009100-47-スズミ" = "それなら……こちらの「閃光弾風調味料」はいかがでしょうか？"
"10009100-48-親子丼職人" = "せ、閃光弾風調味料……！？キミ、それは一体！？"
"10009100-49-スズミ" = "口の中で弾けて強烈な光を発する調味料です。"
"10009100-50-スズミ" = "職人さんの希望するイメージに、これほど合うものは他にないと思います。"
"10009100-53-親子丼職人" = "（眉一つ動かさずに言っている……！）"
"10009100-54-親子丼職人" = "（そうか、これが若さか……私も親子丼作りをしている間に、ずいぶんと年をとってしまったな……）"
"10009100-56-親子丼職人" = "……本当に、これを使っても良いのだろうか。"
"10009100-57-スズミ" = "もちろんです、安全ですから。"
"10009100-58-親子丼職人" = "閃光弾風調味料、か……。"
"10009100-62-親子丼職人" = "私には思いつきもしなかった……。#nこれが時代の最先端なのだな……！"
"10009100-63-親子丼職人" = "ありがとう、学生さん！さっそく帰って新レシピを試してみるよ！"
"10009100-64-スズミ" = "いえ、こちらこそお役に立てて何よりです。"
"10009100-65-スズミ" = "それと、これをどうぞ。閃光弾です。"
"10009100-66-親子丼職人" = "閃光弾……どうして？"
"10009100-67-スズミ" = "近頃、色々と物騒ですし……念のため、備えておいた方が良いかと。"
"10009100-68-親子丼職人" = "（待てよ……？この閃光弾を、閃光弾風調味料の親子丼にサイドメニューとして加えたら……？）"
"10009100-69-親子丼職人" = "（もっと斬新なレシピに仕上がるのではっ！？）"
"10009100-70-親子丼職人" = "改めてお礼をいうよ、ありがとう……この恩は忘れない！"
"10009100-71-スズミ" = "そんな、恩だなんて大げさです。お気をつけて。"
"10009100-78-ヴァルキューレの生徒" = "もしもし？親子丼を1つお願いしたいのですが。"
"10009100-83-親子丼職人" = "はいよ、親子丼1つね。今日から親子丼のレシピをリニューアルしたんだ！"
"10009100-87-親子丼職人" = "一度食べたら絶対に忘れられないはずだから、楽しみに待っていてくれ！"
