[translation]
"10009130-1" = "後日談その6;ハッピーバレンタイン！"
"10009130-2" = "（これはワカモが先生に気持ちを伝える直前のこと――）"
"10009130-10-ワカモ" = "……。"
"10009130-30-？？？" = "そこまでです、災厄の狐。"
"10009130-36-ワカモ" = "……餌はたっぷり撒いたはずですが、まさか見つかってしまうとは。"
"10009130-40-ワカモ" = "あなたは、一体……？"
"10009130-42-ミネ" = "救護騎士団団長、[ruby=あおもり]蒼森[/ruby]ミネと申します。"
"10009130-43-ワカモ" = "救護騎士団……？"
"10009130-44-ワカモ" = "ああ……たしかトリニティの、いつも退屈そうにしているお方たち。"
"10009130-45-ワカモ" = "まさか、私の狙いに気づかれるなんて……想定外でした。"
"10009130-46-ミネ" = "狙い……？#n私はただ「救護」に駆けつけただけですが……。"
"10009130-47-ワカモ" = "あら、それでは救護騎士団の団長さんが、どのようなご用件でしょうか？"
"10009130-48-ワカモ" = "……まさか私のことを止めにきた――わけではないのでしょう？"
"10009130-49-ミネ" = "「災厄の狐」、あなたにお聞きしたいことがあります。"
"10009130-50-ワカモ" = "……？"
"10009130-54-ミネ" = "何故このような騒ぎを起こしたのですか？"
"10009130-56-ワカモ" = "……。"
"10009130-60-ワカモ" = "今日は……。"
"10009130-61-ミネ" = "――今日は？"
"10009130-62-ワカモ" = "……「バレンタインデー」ですから。#n大切な人に、自分の気持ちを伝える日。"
"10009130-63-ワカモ" = "そう――私はただ、あの方に想いを伝えたいだけ。"
"10009130-64-ワカモ" = "邪魔をしようとする者は……このワカモ、たとえ相手が誰であろうと……。"
"10009130-65-ワカモ" = "絶対に諦めません。#nすべてを破壊し、前進するのみ。"
"10009130-69-ミネ" = "バレンタインデーに、気持ちを伝える……ため？"
"10009130-70-ワカモ" = "ええ……理解されずとも構いません。"
"10009130-74-ワカモ" = "私とあの人の前に立ちはだかるのであれば、破壊するだけです。"
"10009130-75-ミネ" = "……。"
"10009130-76-ワカモ" = "さあ、お望みとあれば戦い――"
"10009130-82-ミネ" = "どうぞ、お進みください。"
"10009130-83-ワカモ" = "……どのようなおつもりで？"
"10009130-84-ワカモ" = "何を考えているかは分かりませんが、そんな子供だましは――"
"10009130-85-ミネ" = "――いいえ、これは本心です。"
"10009130-86-ミネ" = "救護騎士団が行う「救護」に、嘘や誤魔化しなど存在しませんので。"
"10009130-91-ミネ" = "今日というこの日に想いを伝える――#nそう決心したあなたを止める理由などありません。"
"10009130-92-ワカモ" = "…………。"
"10009130-97-ワカモ" = "……！"
"10009130-103-ミネ" = "あなたの行いに対する「救護」は、それが済んでからと致しましょう。"
"10009130-107-セリナ" = "団長……？#n今走っていったのってもしかして……"
"10009130-108-セリナ" = "「災厄の狐」じゃないですか！？"
"10009130-109-ハナエ" = "い、行かせて良かったんですか！？"
"10009130-111-ミネ" = "……。"
"10009130-112-ミネ" = "セリナ、ハナエ。今日が何の日か覚えていますか？"
"10009130-114-セリナ" = "そ、それはもちろん……。"
"10009130-115-ハナエ" = "はい！バレンタインデーですよね？"
"10009130-117-ミネ" = "そうです。バレンタインデーはチョコレートを渡すだけでなく、自分の想いを伝える日でもあります。"
"10009130-118-ミネ" = "たしかに騒ぎこそ起こしましたが、#n彼女の前に立ちはだかることが必ずしも正しいとは限りません。"
"10009130-119-ミネ" = "ここは道を譲って、彼女に想いを伝えさせる……。"
"10009130-123-ミネ" = "それもまた、私たちが成す「救護」の形ではないでしょうか。"
"10009130-128-ハナエ" = "で、ですが……団長！"
"10009130-132-ハナエ" = "この騒ぎは一体、どうやって収拾すれば！？"
"10009130-134-ミネ" = "ええ、そうですねハナエ。"
"10009130-135-ミネ" = "「災厄の狐」が想いを伝える事とは別に、#nまず目の前の騒動を収束させなくてはなりません。"
"10009130-136-ミネ" = "まずは――"
"10009130-147-ミネ" = "あちらで暴れている方々を「救護」いたします！"
"10009130-148-ミネ" = "「災厄の狐」の元へ向かうのは、それからでも遅くはありません。#n私たちが救護を終える頃には、あちらも事を終えているでしょう。"
"10009130-150-セリナ" = "分かりました、団長！"
"10009130-151-ハナエ" = "救急箱……注射器に包帯、添え木も……全部揃ってます！"
"10009130-152-ミネ" = "では……参りましょうか。"
"10009130-153-ミネ" = "『救護が必要な場に救護を』！"
