[translation]
"80000002-1" = "発注ミス"
"80000002-2" = "シャーレ・「エンジェル24」"
"80000002-5-ソラ" = "い、いらっしゃいませ、先生……！"
"80000002-8-ソラ" = "……あの。"
"80000002-9-ソラ" = "先生、チョコレートとか欲しくありませんか……？"
"80000002-10-ソラ" = "今エンジェル24でチョコレートをおひとつ買うと、さらに無料で一つプレゼント中なんです！"
"80000002-11-ソラ" = "両手に花（？）のチャンスですよ！"
"80000002-12" = "[s] \"い、今はちょっと……。\""
"80000002-13-ソラ" = "ですよね……。"
"80000002-14-ソラ" = "うぅ……これ、どうしましょう……。"
"80000002-15" = "[s] 何か事情がありそうなので聞いてみる。"
"80000002-16-ソラ" = "実はその、バレンタインデーということで張り切ってチョコを発注したのですが、数量を間違えてしまい……。"
"80000002-17-ソラ" = "20個くらいで良いかなと思っていたところを20箱注文してしまって……。"
"80000002-18-ソラ" = "なので仕方なく「1個無料キャンペーン」ということにしたのですが、そもそもここ、お客さんもほぼ来ないせいで……うぅ……。"
"80000002-19-ソラ" = "これが本店の方にバレたら、私はもう……。"
"80000002-20-ソラ" = "このままではお小遣いどころか、とんでもない金額の賠償金を抱えてしまうんじゃ……！？"
"80000002-21" = "[s] \"じゃあ外に出て、売りに行ってみるとかは？\""
"80000002-22-ソラ" = "え、それは……。"
"80000002-23-ソラ" = "も、もちろん、ここでただ待っているよりかは売れてくれるかもしれませんが……。"
"80000002-24-ソラ" = "こんなたくさん、売れますかね……？"
"80000002-25" = "[s1] \"きっと大丈夫。\"\n[s2] \"私も手伝うよ。\""
"80000002-26-ソラ" = "（うぅ、色々怪しい噂がある「先生」に借りを作っても大丈夫なのかな……）"
"80000002-27-ソラ" = "（うぅ、色々怪しい噂がある「先生」に借りを作っても大丈夫なのかな……）"
"80000002-28-ソラ" = "（でも他に方法も無いし、そんなに悪い人じゃない気も……しなくもない、し……）"
"80000002-29-ソラ" = "で、では……はい、よろしくお願いします！"
"80000002-31" = "（ソラと一緒に外に出て、頑張ってチョコレートを売った。）"
"80000002-38" = "（通りすがりの生徒たちが思いのほか興味を示してくれたおかげで、すぐに完売となった。）"
"80000002-40-ソラ" = "す、すごいです先生……！あんなにたくさんあったのに、こんな早く売り切れるなんて！"
"80000002-41-ソラ" = "それに、何だかトリニティやゲヘナの有名な方もいらっしゃったような……"
"80000002-42-ソラ" = "この先生、本当に一体何者なんだろう……。"
"80000002-43" = "[s] \"……？\""
"80000002-44-ソラ" = "い、いえ！何でもありません！"
"80000002-48-ソラ" = "正体はともかく、頼れるのは確か……？"
"80000002-52-ソラ" = "あの、先生。実は一つチョコが余ってまして……。"
"80000002-53-ソラ" = "よろしければ、受け取っていただけませんか？"
"80000002-58-ソラ" = "あ、いえ！お店の物を勝手にとか、うっかりとかではありません！"
"80000002-59-ソラ" = "これはその、ちゃんと自腹で買った私からのチョコレートで……。"
"80000002-60-ソラ" = "ハッピーバレンタインデー、です。"
