[translation]
"80000039-1" = "特別な日に特別な気持ちを"
"80000039-2" = "シャーレ・休憩室"
"80000039-3" = "（シャーレの休憩室で休んでいた時……）"
"80000039-4" = "[s] \"ひと段落したし、残りはまたいつか……。\""
"80000039-5" = "（諸々終わらせられたものの食事をする気力もなく、コンビニで買ったチョコレートに手を伸ばしたその瞬間）"
"80000039-9" = "[ns] \"はい、どうぞ。\""
"80000039-10-？？？" = "あ、私です。フウカです、先生。"
"80000039-11" = "[s] \"フウカ？\""
"80000039-15-フウカ" = "こ、こんにちは。"
"80000039-16" = "[s] \"今日はどうしたの？\""
"80000039-17-フウカ" = "えっと……先生、もうお食事はされましたか？"
"80000039-18-フウカ" = "あ、まだでしたか。"
"80000039-19-フウカ" = "……今手に持っていらっしゃるそれは？"
"80000039-20" = "[s] \"チョコレート。\""
"80000039-21-フウカ" = "コンビニで、自分で普通に買ってきたものです？"
"80000039-22-フウカ" = "……それではいけません！"
"80000039-23-フウカ" = "そろそろこうなる頃かと思っていました、お伺いして正解です！！"
"80000039-24" = "[s] \"えっと……？\""
"80000039-25-フウカ" = "失礼します！"
"80000039-31-フウカ" = "入れ物はこっちに、"
"80000039-35-フウカ" = "これとこれは……"
"80000039-39-フウカ" = "はい、OKです！"
"80000039-40" = "[s] \"これは……。\""
"80000039-41-フウカ" = "私が作ってきたお弁当です。"
"80000039-42-フウカ" = "いつもお仕事でお忙しいですし、そろそろまた食事が雑になってくる頃なのではないかと思っていまして。"
"80000039-43-フウカ" = "まさかいくらバレンタインデーだからって、食事をチョコレートで済ませようとするなんて……！"
"80000039-44-フウカ" = "まさか、逆にバレンタインデーだからですか？一日三食チョコレートとか……？"
"80000039-45" = "[s] \"さすがにそれは……。\""
"80000039-46-フウカ" = "そうですよね、安心しました。いくら特別な日だからって、甘いものばかり召し上がるのは健康に良くないですよ。"
"80000039-47-フウカ" = "そういうのは見逃せません！"
"80000039-48" = "[s] \"ご、ごめんなさい……。\""
"80000039-49-フウカ" = "まあ今日は、それだけの理由ではないのですが……。"
"80000039-50-フウカ" = "それに、最近あちこちでお見かけするたびに、先生が体調悪そうだなと思っていたので……。"
"80000039-51-フウカ" = "ほら、前にもお伝えしたじゃないですか？"
"80000039-52-フウカ" = "ちゃんとした手作りのごはんが食べたくなったら、いつでも私を呼んでください、と。"
"80000039-53-フウカ" = "そ、そういうことで、今日は私の方から来たんです！"
"80000039-54-フウカ" = "まずは美味しい物を食べて体力を回復させれば、大抵のことは何とかなりますから。"
"80000039-55-フウカ" = "さあ、ご飯にしましょう？"
"80000039-56" = "[s] \"ありがとう、フウカ。\""
"80000039-57-フウカ" = "いえいえ。給食部の部長として当然です。"
"80000039-58" = "[s] \"せっかくだし、一緒に食べない？\""
"80000039-59-フウカ" = "え、わ、私もですか……？"
"80000039-60-フウカ" = "食卓に向かい合って、二人きりで……？"
"80000039-61-フウカ" = "は、はいっ！せ、先生がよろしければ、ぜひ……。"
"80000039-67" = "（そうやってフウカと二人で食卓を囲んだ）"
"80000039-69" = "[ns] \"ご馳走様、すごく美味しかった。\""
"80000039-70-フウカ" = "ふふっ。お口に合ったのでしたら何よりです。"
"80000039-71-フウカ" = "あ、それからこれ……。"
"80000039-76" = "[ns] \"これ、ココア……？\""
"80000039-77-フウカ" = "はい……私からのバレンタインプレゼント、です。"
"80000039-78-フウカ" = "給食部の畑で取ったカカオを加工して、チョコレートを作ったんです。それを用いてこのココアを……。"
"80000039-79-フウカ" = "えっと、さっきもお話しましたが、今日はバレンタインデーですし……。"
"80000039-80-フウカ" = "ぜひ、温かいうちに召し上がってください。きっと今晩はよく眠れると思いますから。"
"80000039-81" = "[s] \"フウカ……！\""
"80000039-82-フウカ" = "そ、そんな涙目で……！？だ、大丈夫ですか先生！？"
"80000039-83" = "[s] \"ありがとう……あ、もしかしてこのマグカップお揃い？\""
"80000039-84-フウカ" = "そ、それはそのっ！特別な意図や意味があるわけではなく……！"
"80000039-85-フウカ" = "あ、あくまで給食部にあったものを持ってきたと言いますか……。"
"80000039-86-フウカ" = "その、本日はこれで失礼します！"
"80000039-90" = "[ns] \"フウカ……！？\""
"80000039-94-フウカ" = "あ、余ったおかずは容器に入れて、冷蔵庫にちゃんとしまってくださいね！その容器についてはまた後日！"
"80000039-95-フウカ" = "それではまた……！"
"80000039-99" = "[ns] \"う、うん、ありがと……。\""
"80000039-101" = "（慌てて（？）立ち去ったフウカからの温もりに癒されながら、ホットチョコを飲んだ）"
"80000039-103" = "[ns] \"甘くて温まる……。\""
