[translation]
"80000065-1" = "メイドらしく"
"80000065-6-アカネ" = "……あら、やはりこちらにいらっしゃいましたか。ご主人様。"
"80000065-7-アカネ" = "オフィスの方にはいらっしゃらなかったので、少しだけ探してしまいました。"
"80000065-8-アカネ" = "……ふふっ。はい、今日はバレンタインデーですからね。"
"80000065-9-アカネ" = "いつも私たちのために頑張ってくださるご主人様のために、ささやかながらご用意いたしました。"
"80000065-10-アカネ" = "えっと、この鞄の中に……"
"80000065-14-アカネ" = "……ご主人様？"
"80000065-15-アカネ" = "どうかされましたか？"
"80000065-16-アカネ" = "……緊張？どうしてです？"
"80000065-17-アカネ" = "……爆弾？"
"80000065-22-アカネ" = "ああ、なるほど……。"
"80000065-23-アカネ" = "いえ、こちらこそすみません。私の普段の行いのせいですね……。"
"80000065-24-アカネ" = "いくら私でも、このような日に爆弾は取り出しません。"
"80000065-25-アカネ" = "まあ確かに、普段からこの鞄にはC4など色々と入れていますが……。"
"80000065-26-アカネ" = "これは反省ですね。せめて今後は、ご主人様の前では少々控えるようにします。"
"80000065-27-アカネ" = "ですので、ご心配なさらなず。こうしてきちんと……"
"80000065-32-アカネ" = "チョコも、持ってきていますから。"
"80000065-33" = "[s1] \"あ、もしかして手作り……？\"\n[s2] \"アカネお手製の？\""
"80000065-34-アカネ" = "ふふっ、気が付いてくださいましたか。"
"80000065-35-アカネ" = "ふふっ、気が付いてくださいましたか。"
"80000065-36-アカネ" = "はい、そうです。特に最近は、エージェントとしての活動ばかり見せてしまっていましたが……こう見えて私は、れっきとしたメイドさんでもありますから。"
"80000065-37-アカネ" = "メイドとして、これくらいは基本的な素養です。もともと私は、お菓子作りも好きですし。"
"80000065-38-アカネ" = "ですので、こういった日も結構好きなんです。あらためてこれをご主人様に……"
"80000065-39" = "[s] \"……アカネ？\""
"80000065-40-アカネ" = "いえ、それだけでも悪くは無いのですが……"
"80000065-41-アカネ" = "今日はメイドとご主人様というより……ただ一人の生徒から、先生へ。そういった気分かもしれません。"
"80000065-42-アカネ" = "……それでも、受け取っていただけますか？"
"80000065-43" = "[s3] \"もちろん。\"\n[s4] \"アカネは、私の大事な生徒でもあるから。\""
"80000065-44-アカネ" = "あらあら……。"
"80000065-45-アカネ" = "あらあら……。"
"80000065-46-アカネ" = "ふふっ。その言葉を聞かせてくださるまで、もう少し時間がかかるかと思っていましたが……。"
"80000065-47-アカネ" = "流石ですね。何だか逆に、私の方が照れてしまいます。"
"80000065-48-アカネ" = "……ありがとうございます、先生。"
"80000065-49-アカネ" = "これからもぜひ、よろしくお願いしますね？"
"80000065-51" = "（その後アカネと一緒に、チョコレートを二人で食べながら優雅な時間を過ごした）"
"80000065-56" = "（アカネが作ったチョコレートはどんな高級品にも劣らないほど、すごく美味しかった）"
