[translation]
"80000034-1" = "それでも伝えたくて"
"80000034-2" = "（バレンタインデーの日、一日が終わりそうなタイミングでヒナから連絡が入った）"
"80000034-3" = "[ns] \"たしか、この辺だったような……。\""
"80000034-7-ヒナ" = "あ、先生……。"
"80000034-8" = "[s] \"ヒナ！\""
"80000034-9-ヒナ" = "ちょっ……！先生、声が大きい……！"
"80000034-10-ヒナ" = "静かにして。もし誰かに見られたら、騒ぎになるから……。"
"80000034-11-ヒナ" = "それに、そうなったら先生にも迷惑がかかる。"
"80000034-12" = "[s1] \"私は全然かまわないけど……。\"\n[s2] \"ヒナにかけられる迷惑なら全然ウェルカム。\""
"80000034-13-ヒナ" = "ああもう、またそうやって……。"
"80000034-14-ヒナ" = "ああもう、またそうやって……。"
"80000034-15-ヒナ" = "……まあ、今さらの話ね。"
"80000034-16-ヒナ" = "それより急に呼び出してごめん。"
"80000034-17-ヒナ" = "その……来てくれて、"
"80000034-18-ヒナ" = "ありがとう。"
"80000034-19" = "[s] \"ううん。ところでどうしよっか、見られて困るなら……\""
"80000034-25-ヒナ" = "せ、先生……！？"
"80000034-26" = "[s3] \"こうしてれば見られないかな。\"\n[s4] \"それで、今日はどうしたの？\""
"80000034-27-ヒナ" = "ち、近いっ……！それに、耳元……！？"
"80000034-28-ヒナ" = "ち、近いっ……！それに、耳元……！？"
"80000034-29-ヒナ" = "待って！"
"80000034-30" = "[s] \"……？\""
"80000034-31-ヒナ" = "そ、その、一旦落ち着いて先生……いや、落ち着くべきは私かもしれないけど……。"
"80000034-32-ヒナ" = "と、とりあえずこの距離で大丈夫だから。"
"80000034-33-ヒナ" = "それで、今日先生を呼んだのは、これ。"
"80000034-38" = "[ns] \"これって……。\""
"80000034-39-ヒナ" = "その、今日はバレンタインデーだから……せっかくだし、作ってみた。"
"80000034-40-ヒナ" = "見ての通り、"
"80000034-41-ヒナ" = "あんまり綺麗じゃないけど……。"
"80000034-42-ヒナ" = "まあ私みたいに可愛くない感じになったのは、ある意味合ってるかも……"
"80000034-43-ヒナ" = "あ、でも味は多分"
"80000034-44-ヒナ" = "ちゃんとチョコレートになってるはず。"
"80000034-45-ヒナ" = "だからその、もし良かったらこれ、受け取ってほしくて……。"
"80000034-46" = "[s] \"ヒナの、手作りのチョコレート……！？\""
"80000034-47-ヒナ" = "せ、先生！？ちょっと、興奮しすぎ……！！"
"80000034-48" = "[s] \"ヒナの手作り……家宝にしよう……。\""
"80000034-49-ヒナ" = "いや、食べてほしいのだけど……？"
"80000034-50-ヒナ" = "全くもう……。"
"80000034-51-ヒナ" = "ふふっ、そういえばこういう人だった……。"
"80000034-52-ヒナ" = "さっきまでずっと怖がってたのは、何だったんだか……。"
"80000034-53-ヒナ" = "ありがとう、先生。ちゃんと美味しく食べてね。"
"80000034-54-ヒナ" = "その、それなりに頑張ったから……。"
"80000034-55" = "[s] \"ありがとう！\""
"80000034-56-ヒナ" = "……家宝にしないで、ちゃんと食べるのよ？"
"80000034-57" = "[s] \"善処する。\""
"80000034-58-ヒナ" = "善処じゃなくって……。"
"80000034-59-ヒナ" = "まあ、それならそれで良いけど……。"
"80000034-60-ヒナ" = "……ふふっ。"
