[translation]
"80000063-1" = "その前に、その後に"
"80000063-3" = "（公園のベンチで待っていたら、約束していたハルカが走ってくるのが見えた）"
"80000063-4-ハルカ" = "も、申し訳ございません……！ご連絡があってすぐ走ってきたのですが、こんなことになってしまい、どのようにお詫びすれば良いのか……！"
"80000063-5-ハルカ" = "ま、まさかずっとここでお待ちになっていたのですが……！？そんな、私なんかのせいで先生の大事なお時間を……！！"
"80000063-6-ハルカ" = "もうこれは何で償えば……内臓とかでぜひ謝罪を……！"
"80000063-7-ハルカ" = "……え、だ、大丈夫ですか？あ……は、はい……。"
"80000063-8-ハルカ" = "と、ところで今日は、どういったご用件で……あ、いえその、問いただすだなんてそんな、分不相応なことがしたいわけでは……。"
"80000063-9-ハルカ" = "え、バレンタインデー、ですか？は、はい、そうですね……！？"
"80000063-10-ハルカ" = "準備……？あ、や、実はその、確かにあるのですが……！いえ、思い上がりだなんて滅相もございません……！"
"80000063-11-ハルカ" = "ど、どうして……？"
"80000063-12-ハルカ" = "先生は、どうしてそこまでご存じなのですか……？未来予知……！？"
"80000063-13" = "[s1] （もしくれるんだったら、大ごとになる前に収めないと……）\n[s2] （考え込み過ぎて加速しちゃう前に……）"
"80000063-14-ハルカ" = "……？"
"80000063-15-ハルカ" = "……？"
"80000063-16-ハルカ" = "……えっと、先生？"
"80000063-17-ハルカ" = "あ、ちょ、チョコレートですね！はい、ずっと大切に持ち歩いてまして……！"
"80000063-18-ハルカ" = "よ、よろしければこちらを……！！"
"80000063-23-ハルカ" = "じ、実はその、私あまり普段チョコレートを食べなくって……それで、何をお渡しすれば良いのかよく分からなかったのですが……。"
"80000063-24-ハルカ" = "えっと、所持金で払えそうな中で一番高くて、一番数字が凄そうなものを選んできました！"
"80000063-25-ハルカ" = "も、もちろん私なんかが買った物が、先生にとって価値があるのかは分かりませんが……。"
"80000063-26-ハルカ" = "いえ、本来はあったとしても、私の手に触れた瞬間にゴミになったかもしれませんし……そもそも受け取ってくれる前提だなんて失礼なことを……。"
"80000063-27" = "[s3] \"ううん、すっごく嬉しい。早く貰いたくて連絡したから。\"\n[s4] \"ハルカから貰えるってことが嬉しいよ。ありがとう。\""
"80000063-28-ハルカ" = "えっ……？"
"80000063-29-ハルカ" = "えっ……？"
"80000063-30-ハルカ" = "わ、私のを、ですか……？先生が……？"
"80000063-31-ハルカ" = "ほ、本当ですか！？あ、いえ！決して先生のことを疑うですとか、そういったことではないのですが……！"
"80000063-32-ハルカ" = "ただ、信じられなくて……その、私なんかのチョコを先生が喜んでくださるなんて、えっと……！？"
"80000063-33-ハルカ" = "わ、私はどうすれば良いのでしょうか……こんな身に余る光栄を、どうしたら……？"
"80000063-34-ハルカ" = "え、素直に受け止めてほしい……？え、で、できれば笑顔で……！？"
"80000063-38-ハルカ" = "えっ、と……こ、こうでしょうか……えへへ……。"
"80000063-39" = "[s5] \"うん、それだと私はますます嬉しい。\"\n[s6] \"うん、ハルカ可愛い！\""
"80000063-40-ハルカ" = "……！？"
"80000063-41-ハルカ" = "……！？"
"80000063-42-ハルカ" = "へ……。"
"80000063-47-ハルカ" = "えへへへ……その、こちらこそありがとうございます、先生……！"
"80000063-49" = "（その後ハルカを見送ってから、99％チョコの中にある甘味を味わった）"
