[translation]
"51010-1" = "第1話;プロローグ"
"51010-6-アラタ" = "ど、どこだ！？#nあいつは一体どこに……！"
"51010-13-魑魅一座A" = "……！"
"51010-19-魑魅一座B" = "リーダー！後ろっす！"
"51010-20-アラタ" = "ちっ、逃すか！"
"51010-26-アラタ" = "へっ！どんなもんだい！"
"51010-27-魑魅一座A" = "リーダーすごい！これなら……！"
"51010-28-魑魅一座B" = "いや、あいつはまだ……！"
"51010-41-魑魅一座たち" = "ぐ、ぐあああっ！？"
"51010-51-ナグサ" = "――ここまで。#n観念して、[ruby=すだまいちざ]魑魅一座[/ruby]。"
"51010-52-アラタ" = "なっ……あたしらは何も……！"
"51010-53-ナグサ" = "何も……？"
"51010-54-ナグサ" = "さっきまで色んな人に迷惑かけてた。"
"51010-56-魑魅一座A" = "失礼な！言いがかりだ！"
"51010-57-魑魅一座B" = "あたしらはリーダーの偉大なる計画のために、動いていただけだ！"
"51010-62-魑魅一座A" = "リーダー！例の計画を教えてやりましょうよ！"
"51010-64-魑魅一座B" = "計画を聞いたら、驚きすぎて腰抜かしても知らないかんな！"
"51010-70-ナグサ" = "……？"
"51010-71-アラタ" = "あっ、いや。なんていうか……#nそこまで持ち上げられると困るんだけど……"
"51010-72-アラタ" = "「来週のお祭り前に好き勝手暴れる計画」を始めようと……"
"51010-73-ナグサ" = "…………。"
"51010-74-アラタ" = "まあ、みんなが乗り気じゃないなら、やめようと思ってたというか……"
"51010-76-魑魅一座A" = "これぞ！我らがリーダーの完璧なる計画！"
"51010-77-魑魅一座B" = "邪魔なんかさせねぇっすよ！！"
"51010-79-アラタ" = "や、やっぱりこの計画、すごいんだな……？"
"51010-81-ナグサ" = "久しぶりに帰ってきたけど……相変わらずだね。"
"51010-82-ナグサ" = "でも、私の目に入ったからには…… "
"51010-86-ナグサ" = "これ以上、思い通りにはさせない。"
"51010-88-アラタ" = "うっ……！"
"51010-89-アラタ" = "ま、待てよ！"
"51010-90-アラタ" = "私たちの邪魔をするあんたは何者なんだ！"
"51010-91-魑魅一座A" = "ん……？"
"51010-92-魑魅一座A" = "あの水色の羽織……"
"51010-93-魑魅一座B" = "あっ、やっぱり！#nあいつ、「百花繚乱」っすよ！"
"51010-94-アラタ" = "何っ！？"
"51010-95-アラタ" = "百花繚乱ってことは――"
"51010-97-ナグサ" = "違う。"
"51010-99-アラタ" = "ま、まだ最後まで言ってないんだけど――！？"
"51010-101-ナグサ" = "あなた達の想像とは違う。"
"51010-102-ナグサ" = "これは……"
"51010-104-ナグサ" = "……ただの、コスプレだから。"
"51010-108-ナグサ" = "「アレ」を返しに来た以上……"
"51010-115-ナグサ" = "私は……もう、百花繚乱ではないのだから。"
"51010-121" = "シャーレ・執務室"
"51010-124" = "（いつも通りシャーレの仕事を片付けていると……）"
"51010-130" = "[ns] \"はい、シャーレです。\""
"51010-132-ニヤ" = "にゃはは。先生、ご無沙汰しております～"
"51010-133-ニヤ" = "いかがお過ごしでしょうか？"
"51010-134" = "[s] \"事務作業をしていたところだよ。\""
"51010-137" = "（デスクに広げられている書類はどれも、「各自治区の被害状況」や「支援予算の運用指針」など直近の出来事に関連しているものだった）"
"51010-139-ニヤ" = "なるほど～#n先日、百鬼夜行からもお送りしたアレですね。"
"51010-140-ニヤ" = "色々……ありましたからねぇ。"
"51010-145" = "[ns] \"それはそうと……一体どうしたの？\""
"51010-146-ニヤ" = "ああ、そうでしたそうでした。"
"51010-147-ニヤ" = "先生は相変わらず、お忙しそうに働かれてるみたいですし～？"
"51010-148-ニヤ" = "そんな仕事三昧の先生のために！#n私も何かお役に立てないかと思い……少し考えてみたのです。"
"51010-149" = "[s] \"お気遣いありがとう……？\""
"51010-150-ニヤ" = "んふふ……よろしければ、百鬼夜行にいらっしゃいませんか？"
"51010-151-ニヤ" = "もうすぐお祭りが開催されるんですよ。"
"51010-152-ニヤ" = "たまには息抜きするのも大事ですし、#n気分転換がてら楽しんでいただけたらな～と思いましてね。"
"51010-153-ニヤ" = "それに、こちらの近況もお伝えしておきたいですし……#nちょ～っぴり個人的なお願いもあるといいますか～"
"51010-154" = "[s] \"個人的なお願い？\""
"51010-155-ニヤ" = "ふふっ。#n百鬼夜行に来たら、愛らし～いチセにゃんをなでなでできますよ？"
"51010-160-チセ" = "にゃー？"
"51010-162-ニヤ" = "にゃははは～♪"
"51010-163-ニヤ" = "それでは、お待ちしておりますねぇ。"
"51010-169" = "[ns] \"……百鬼夜行。\""
"51010-173-クズノハ" = "「色彩」によって反転した者を元に戻す方法など、存在せぬ。"
"51010-174-クズノハ" = "其れは――死者が生き返らないのと同様に。#nこの世界の絶対的なルールである。"
"51010-175-クズノハ" = "だがそれでも……助けたい者が居ると申すのなら、"
"51010-179-クズノハ" = "――妾を訪ねてくりゃれ。"
"51010-182" = "[ns] \"もしかしたら、彼女の手がかりを得られるかも……\""
"51010-185" = "次回;思いがけない出会い（１）"
