[translation]
"51070-1" = "第7話;青春（？）少女（１）"
"51070-3" = "[ns] \"……青春って、一体どういう意味なんだろう？\""
"51070-4-ユカリ" = "ハッ！そういえば……"
"51070-5-ユカリ" = "以前、レンゲ先輩から聞いたことがありますの。"
"51070-11-レンゲ" = "そういやユカリ、お前たしか中学生の頃からウチに入りたいって言ってたよな。"
"51070-12-ユカリ" = "ええ！"
"51070-13-レンゲ" = "「あの夜の運命的な出会いがきっかけ」……だっけ？"
"51070-14-レンゲ" = "初めて聞いたとき、なんでこんなとこにわざわざ……変なヤツって思ったけど……"
"51070-15-ユカリ" = "百花繚乱はえり～とが集まった素晴らしい委員会！えり～とである[ruby=みども]身共[/ruby]には、ここしかないと決めておりましたの！"
"51070-16-レンゲ" = "まあ、たしかに……お前は中学生の頃から本っ当に毎日…… "
"51070-17-レンゲ" = "キキョウに追い返されたかと思いきや、#nケロッとして次の日も懲りずに来てたくらいだしなぁ。"
"51070-18-レンゲ" = "毎朝4時起きで鍛錬、終わって朝飯食ったらすぐ授業……放課後も鍛錬……#nこんな委員会のどこがいいんだか。"
"51070-20-ユカリ" = "それでも身共は、レンゲ先輩はもちろん他の先輩方と励む時間がとっても楽しいのです！"
"51070-21-レンゲ" = "いやまぁ……そこまで言われちゃ何も言えないけどさ。"
"51070-22-レンゲ" = "でも……一度くらい考えたことは無いのか？"
"51070-24-ユカリ" = "……？"
"51070-25-レンゲ" = "百花繚乱の活動以外で、友達と過ごす青春とか……"
"51070-26-ユカリ" = "一度もありませんわ！"
"51070-27-レンゲ" = "うわっ、即答かよ……"
"51070-28-ユカリ" = "そんなレンゲ先輩はどうですの！百花繚乱の活動はお好きですか？"
"51070-29-レンゲ" = "そうだな……アタシもキキョウと一緒に入ってから、何だかんだ楽しく過ごせてるよ。"
"51070-30-レンゲ" = "ナグサ先輩やユカリともこうして仲良くなれたし……後悔してるわけじゃないんだけど……"
"51070-35-レンゲ" = "でもたまには、こう……ありふれた青春を送れたらなーって。"
"51070-36-レンゲ" = "ふと、考える時があるんだ。#nなんていうか……文化系みたいな？"
"51070-42-ユカリ" = "――あの時は、その言葉をよく理解できませんでしたが。 "
"51070-43-ユカリ" = "身共は、あの日の会話を思い出して……考えたのです。"
"51070-44-ユカリ" = "もしかしたらレンゲ先輩は、他の部活動に入りたかったのではないか、と……#n身共の考え過ぎかもしれませんが……"
"51070-45" = "[s] \"単に「青春」に憧れてるだけじゃない？\""
"51070-49-ユカリ" = "ハッ……！？#nやはりそうなのですね！？"
"51070-50-ユカリ" = "なるほど……つまり、レンゲ先輩は今……"
"51070-51-ユカリ" = "この紙に書いてある通り、青春を謳歌する旅に……！？"
"51070-52-ユカリ" = "「青春を送るなら、やっぱり文化系だ。汗くさい百花繚乱よりも、そっちの方がずっと青春っぽいからな」と言ってたのが、まさかそこに繋がるとは！"
"51070-53" = "[s] \"出かけた先の検討がつきそうだね？\""
"51070-54-ユカリ" = "むぅ……レンゲ先輩は、いつだって先陣を切って身共たちを守ってくださっていたのに……"
"51070-55-ユカリ" = "ナグサ先輩が居なくなり、百花繚乱の活動が停止してしまった今……#nついに我慢が限界を迎え……"
"51070-59-ユカリ" = "青春への欲望が爆発してしまったのです！きっとそうですの！"
"51070-60-ユカリ" = "さ！こうしている場合ではありません！すぐに参りましょう、先生！"
"51070-66-ユカリ" = "ですが、その……"
"51070-72-ユカリ" = "どちらへ向かったら良いのでしょう？#n身共は文化部にあまり明るくなく……"
"51070-79" = "[ns] \"はいこれ、カホが文化部のリストをまとめてくれたよ。\""
"51070-80-ユカリ" = "陰陽部がりすとを作ってくださったのですか！？"
"51070-81-ユカリ" = "す、すごいです！"
"51070-82-ユカリ" = "ハッ……これが噂に聞く、陰陽部の部長や副部長さえも一目置くという、シャーレの権力……？ "
"51070-83-ユカリ" = "身共、本当はとても危険なお方と居るのでしょうか！？"
"51070-84" = "[s] \"そ、そんな事はないよ……\""
"51070-85-ユカリ" = "さあ……"
"51070-86-ユカリ" = "こちらをもとにレンゲ先輩を探しに行きましょう！"
"51070-88" = "クロレラ観察部"
"51070-90-ユカリ" = "りすとの一番上にあるのは、ここですね……"
"51070-91-ユカリ" = "では――"
"51070-95-ユカリ" = "失礼いたしますの！"
"51070-107-百鬼夜行サークル部員A" = "もしかして、見学ですか？"
"51070-108-百鬼夜行サークル部員B" = "……また？"
"51070-109" = "[s] \"こんにちは。その、私たち――\""
"51070-111-ユカリ" = "はい！レンゲ先輩を探しに来ましたの！"
"51070-113-百鬼夜行サークル部員A" = "レンゲ……？"
"51070-114-百鬼夜行サークル部員B" = "どなたのことでしょうか……？"
"51070-116-ユカリ" = "レンゲ先輩は……"
"51070-117-ユカリ" = "レンゲ先輩ですの！"
"51070-119-百鬼夜行サークル部員A" = "……へ？"
"51070-122" = "[ns] \"ユカリ、まずはレンゲの特徴を伝えないと……\""
"51070-123-ユカリ" = "あっ、そうでしたの。"
"51070-124-ユカリ" = "ええと、その、レンゲ先輩はですね……"
"51070-125-ユカリ" = "「朝練をサボったヤツはペナルティだ！」と言ったり……"
"51070-126-ユカリ" = "身共の顔に米粒がついていると、からかってきたり……"
"51070-127-ユカリ" = "そんな方ですが、暴れている魑魅一座を見つけたら、すぐに駆けつける……そんな身共が尊敬してやまない……"
"51070-132-百鬼夜行サークル部員B" = "ええと……さっぱり分からないんですが。"
"51070-134-ユカリ" = "そ、そんなぁ……！？"
"51070-135" = "[s1] \"今ユカリが伝えていたのは……\"\n[s2] \"ユカリがレンゲをどう思っているのか、だからね……\""
"51070-138-ユカリ" = "う、ううん……たしかに仰る通りですの……"
"51070-139-ユカリ" = "そうですね……レンゲ先輩は朱色の美しい髪と……"
"51070-141-百鬼夜行サークル部員A" = "朱色の髪？"
"51070-142" = "[s] \"やっぱり手当り次第に探すのは――\""
"51070-143-百鬼夜行サークル部員A" = "朱色の髪なら、少し前に体験入部したあの子じゃないかな？"
"51070-149-百鬼夜行サークル部員B" = "あ～……あの水色の羽織を着ていた？"
"51070-151-ユカリ" = "ええ、そうですわ！やはりこちらに来ていたのですね！"
"51070-152-ユカリ" = "レンゲ先輩ならきっと、この「クロレラ観察部」でもえーすとして活躍を……！"
"51070-154-百鬼夜行サークル部員A" = "なんというか……ちょっとよく分からないこと言ってたよね……"
"51070-155-百鬼夜行サークル部員B" = "「全国大会を目指して朝まで頑張るぞ！まずは体力作りから！」とか……"
"51070-156-百鬼夜行サークル部員B" = "というか、クロレラ観察に全国大会ってあったっけ？ "
"51070-157-百鬼夜行サークル部員A" = "「クロレラ観察の真髄を教えてくれ！全国でも活躍できるよう、今から準備を進めていく！」とか言ってたような……"
"51070-163" = "[ns] \"うーん、話を聞いた感じ……\""
"51070-165-ユカリ" = "……流石はレンゲ先輩！素晴らしいご活躍ですわ！"
"51070-169" = "[ns] \"か、活躍してるかな！？\""
"51070-170-ユカリ" = "レンゲ先輩は、決して妥協を許さないお方ですから！"
"51070-171-ユカリ" = "それで……お聞きしたいのですが、レンゲ先輩は今どちらへ……？"
"51070-172-百鬼夜行サークル部員A" = "あ、ここには居ませんよ。"
"51070-173-百鬼夜行サークル部員B" = "体験入部が終わった日に、たしか……"
"51070-180-レンゲ" = "くっ……すまない！！"
"51070-181-レンゲ" = "体験入部の期間中、アタシは質問してばかりだったな。#n悪い、迷惑をかけてしまった。"
"51070-186-百鬼夜行サークル部員A" = "いや、迷惑だとは思わ……"
"51070-188-レンゲ" = "……でも、おかげで気がついたんだ。"
"51070-190-百鬼夜行サークル部員B" = "ん？"
"51070-191-レンゲ" = "真剣にクロレラを観察するあんた達と違って、自分は……中途半端で、上辺しか見れていなかった。"
"51070-192-レンゲ" = "やっぱり、この部活に生涯を捧げてきたあんた達と比べたら、アタシは足元にすら及ばない。"
"51070-193-百鬼夜行サークル部員A" = "いや、生涯を捧げてはいな……"
"51070-194-レンゲ" = "だから、ごめん！！正式入部は……申し訳ないが見送らせてほしい。 "
"51070-195-レンゲ" = "でも！あんた達の熱い気持ちはしかと受け取った。クロレラ観察をこれからも応援させてほしい！"
"51070-197-レンゲ" = "全国大会に出場したら、必ず応援に行くから！"
"51070-204-百鬼夜行サークル部員A" = "――と言って、どこかに行ったよ。"
"51070-205-百鬼夜行サークル部員B" = "クロレラ観察の全国大会……"
"51070-206-百鬼夜行サークル部員B" = "まずは存在するのか調べてみようかな？"
"51070-208-ユカリ" = "……そうでしたか。"
"51070-209-ユカリ" = "どちらへ向かったかご存じだったりしますの？"
"51070-210-百鬼夜行サークル部員A" = "今は「燈籠祭」の出展準備で忙しいし……"
"51070-211-百鬼夜行サークル部員A" = "すぐ居なくなっちゃったから、それ以上のことは分からなくって。ごめんね。"
"51070-214" = "[ns] \"残念だけど一歩遅かったね。\""
"51070-215-ユカリ" = "ええ。ですが、レンゲ先輩が文化部で活動していると分かったのは収穫ですの！#n身共の予想通りですわ！"
"51070-219-ユカリ" = "方針は間違っていないようですし、次の部活へ参りましょう！"
"51070-221" = "多面指し将棋部"
"51070-223-百鬼夜行サークル部員A" = "百花繚乱の赤髪の子……？"
"51070-224-百鬼夜行サークル部員A" = "ああ、思い出した。うちの部活にも来てたよ。"
"51070-225-百鬼夜行サークル部員A" = "なんというか、変わった子だったなぁ。"
"51070-226-百鬼夜行サークル部員B" = "対戦中、苦しそうな場面で「待った」をかけようか？と声をかけたら――"
"51070-231-レンゲ" = "そ、それは……情けをかけられているのか……？"
"51070-232-レンゲ" = "くっ……だが！！"
"51070-233-百鬼夜行サークル部員B" = "そう……"
"51070-237-百鬼夜行サークル部員B" = "それなら、はい王手。"
"51070-242-レンゲ" = "参りましたっっっ！！！"
"51070-245-百鬼夜行サークル部員B" = "――ということがあったんだ。#nその後「一瞬でも揺らいでしまった自分を鍛え直したい」と言って、何度も頭を下げてから帰っていったよ。"
"51070-247-ユカリ" = "それは……なんというレンゲ先輩らしいご活躍！"
"51070-249" = "フィットネス落語部"
"51070-250-百鬼夜行サークル部員A" = "ああ。レンゲさんなら、来てたよ。"
"51070-251-百鬼夜行サークル部員B" = "私たちの落語を聞きながら、「青春の夢が膨らんだ！」と言ってくれたのは嬉しかったけど……"
"51070-252-百鬼夜行サークル部員A" = "お祭りの準備で忙しいから、今は新入部員を受け入れる余裕がなくてねぇ。#n入部は断っちゃったんだ。"
"51070-254" = "かるたバトル部"
"51070-255-百鬼夜行サークル部員A" = "ああ、そうだそうだ。そんな子も来てたね。"
"51070-256-百鬼夜行サークル部員B" = "熱い青春かるたバトルに憧れてる、とか。"
"51070-257-百鬼夜行サークル部員A" = "まあ、お祭りが近いから入部はお断りしたんだけど……"
"51070-264" = "（その後も、リストの上から順に部活を訪ねていった）"
"51070-268" = "[ns] \"お茶でも飲んで休もっか。\""
"51070-272-ユカリ" = "あっ、ありがとうございます……"
"51070-273" = "（かなりの数を回ったが、レンゲは見つけられなかった）"
"51070-274-ユカリ" = "まさかレンゲ先輩が、これほど体験入部を重ねていたとは……"
"51070-275-ユカリ" = "それにしても皆様、レンゲ先輩に対する印象が……"
"51070-276" = "[s] \"そうだね、ちょっと辛辣な……\""
"51070-277-ユカリ" = "ええ！とっても辛辣な高評価でしたわね！"
"51070-278-ユカリ" = "……へっ？言葉の使い方が違う……？ "
"51070-279-ユカリ" = "ふふっ、何を仰るのですか！ "
"51070-280-ユカリ" = "言葉とは全て、捉え方一つで変わるもの！"
"51070-281-ユカリ" = "皆様がレンゲ先輩のことを忘れずにいたのは、それだけ本気で青春に取り組んでいたからに他ありません！"
"51070-282-ユカリ" = "レンゲ先輩は、昔からよく「妥協せずに最後までやる事が大切だよ！」と仰っていましたから。"
"51070-283" = "[s] \"心からレンゲを尊敬しているんだね。\""
"51070-284-ユカリ" = "はい！身共はレンゲ先輩を心から尊敬しておりますとも！"
"51070-285-ユカリ" = "ええっと……"
"51070-289-ユカリ" = "それでは次の行き先は――"
"51070-291-？？？" = "先生……はっけーん！"
"51070-300" = "[ns] \"わわっ！？\""
"51070-304" = "[ns] \"カエデ！？\""
"51070-306-ユカリ" = "せ、先生？お怪我はありませんか！？"
"51070-307-ミモリ" = "か、カエデちゃん！？危ないじゃないですか！"
"51070-308-ツバキ" = "ふあぁ……"
"51070-309" = "[s] \"カエデにミモリ、ツバキ……？\""
"51070-312" = "次回;青春（？）少女（２）"
