[translation]
"51225-7-ユカリ" = "んん……ここは……？"
"51225-9-シュロ" = "アハッ、お目覚めですかぁ？"
"51225-10-ユカリ" = "あなたは……？"
"51225-11-シュロ" = "あらあら、ざんね～ん。#nもうお忘れなのですかぁ？"
"51225-12-シュロ" = "手前は……手前さんの代理人です。 "
"51225-13-シュロ" = "手前さんの「感情」を手前さん方に伝えるための……[ruby=怪談家]語り手[/ruby]。"
"51225-14-ユカリ" = "感情……？"
"51225-19-シュロ" = "「手前さんのその感情――そのままそ～っくり返してやりたい――そうは思いませんかぁ？」"
"51225-24-ユカリ" = "まさ、か……。 "
"51225-25-シュロ" = "ほらほら、こっちをご覧なさい？#nとてもとて～も、美しい景色でしょ？"
"51225-26-ユカリ" = "え……？"
"51225-44-ユカリ" = "これは……どうして、お祭り会場が……！"
"51225-45-シュロ" = "アハハハッ、素晴らしいでしょ？"
"51225-46-シュロ" = "ああ、ああ！なんという風流……！#n手前、と～っても気に入ってるんです。"
"51225-47-ユカリ" = "どうして……こんな非道な事を……！"
"51225-48-シュロ" = "あらあら、そんな寂しい事、言わないでくださいなぁ。"
"51225-49-シュロ" = "まるでぜ～んぶ、手前一人でやったみたいじゃないですかぁ。"
"51225-50-ユカリ" = "……え？"
"51225-51-シュロ" = "手前はただ、巫女様の感情を代わりに伝えただけですよぉ？"
"51225-52-シュロ" = "見えませんか？#n手前さんの前にいる、ソレ。"
"51225-53-シュロ" = "手前さんが吐き出した…… "
"51225-58-シュロ" = "胸の奥底から溢れた――「感情」ですよぉ？"
"51225-59-ユカリ" = "……！！"
"51225-65-ユカリ" = "あ……あ……"
"51225-66-ユカリ" = "これが……身共の……"
"51225-67-ユカリ" = "身共から、生まれた……感情？"
"51225-73-ユカリ" = "っ……！"
"51225-76-シュロ" = "見ているだけで感じとれるでしょ？ "
"51225-77-シュロ" = "その中に渦巻く煙……燃え上がる炎。"
"51225-78-シュロ" = "全身を埋め尽くす、深く鮮烈な――感情が！"
"51225-80-シュロ" = "これも……ぜ～んぶ、手前さんのおかげですよ。巫女様。"
"51225-82-ユカリ" = "身共の、おかげ……？"
"51225-84-シュロ" = "ええ、ええ。理解できます。"
"51225-85-シュロ" = "誰も私の声に耳を傾けてくれない……誰も私のことなんて分かってくれない……！"
"51225-86-シュロ" = "他人は、私の気持ちも声も願いさえも、踏みにじっていくだけ。"
"51225-87-シュロ" = "正しい選択をしなさい、と自分の願いと欲を押しつけるだけ。"
"51225-88-シュロ" = "だから――苦しかったのでしょ？疲れてしまったのでしょ？"
"51225-89-ユカリ" = "あ……う……"
"51225-91-シュロ" = "だから……ぜ～んぶ、投げ出してしまいたかったのでしょ？"
"51225-92-シュロ" = "自分の意見には耳を傾けず、取り合ってもくれない彼女らに――そんな言葉を浴びせる者に向かって――"
"51225-96" = "[log][ff4444]＜――全部燃えてしまえばいい＞[-][/log]"
"51225-98-シュロ" = "と……思ったのでしょ？"
"51225-100-ユカリ" = "み……身共は……"
"51225-102-シュロ" = "アハハハッ！"
"51225-103-シュロ" = "アレは、そんな手前さんの記憶と感情の狭間から生まれた、顔を持たない[ruby=かたしろ]形代[/ruby]。"
"51225-104-シュロ" = "名を付けるとすれば…… "
"51225-105-シュロ" = "そうですねぇ、「[ruby=むぼう]無貌[/ruby]の[ruby=かたしろ]形代[/ruby]」……とでも呼びましょかぁ。"
"51225-106-シュロ" = "アレなら手前さんの望み通り……百鬼夜行を隅々まで焼け野原にしてくれますよぉ？#nそう！美しくも儚い絶景を！"
"51225-107-シュロ" = "ええ、ええ！実に素晴らしい風流となってくれるでしょう。"
"51225-108-ユカリ" = "ああ――"
"51225-115" = "街が燃えている。"
"51225-116" = "地を這う紅蓮の炎。"
"51225-117" = "遠くから聞こえる誰かの悲鳴。"
"51225-120" = "これは全部――自分のせいだ。 "
"51225-128" = "一瞬でも自分が、あんなことを思ってしまったせいで。"
"51225-129" = "百花繚乱を夢見て、本来の責務から逃げ出して――"
"51225-133" = "……百花繚乱としての自分を描いて、その姿を演じようとしたせいで下った、罰。"
"51225-136-ユカリ" = "（……そっか）"
"51225-137-ユカリ" = "（身共のせいで……）"
"51225-140-ユカリ" = "あれは……[ruby=身　共　の　間　違　い]身共から生まれたもの[/ruby]なんだ。"
"51225-150-シュロ" = "あらあらぁ？気を失ってしまいましたかぁ。 "
"51225-151-シュロ" = "面白くないですねぇ。宴はこれからだというのに。"
"51225-152-シュロ" = "ま、構いませんか。巫女様、手前さんの役目はもう終わり。#nここからは手前の番です。"
"51225-153-シュロ" = "役者も舞台も整った――"
"51225-154-シュロ" = "ついに、コクリコ様が望んだ……"
"51225-155-シュロ" = "手前だけの「百物語」が……！"
"51225-157-シュロ" = "完成するのです――"
"51225-163" = "[ns] \"そこまでだよ、シュロ！\""
"51225-169-ナグサ" = "ユカリを、返してもらう……！"
"51225-173-シュロ" = "……興醒めですねぇ？"
"51225-177" = "次回;偽りの言葉"
