[translation]
"51230-1" = "第23話;偽りの言葉"
"51230-7-ナグサ" = "先生……！あそこ……！"
"51230-10" = "[ns] \"ユカリ！？\""
"51230-20" = "[ns] \"くっ……ここにも怪物が！\""
"51230-23-シュロ" = "ついにここまで来たんですねぇ。#nシャーレの先生……ナグサちゃん。"
"51230-25-ナグサ" = "シュロ……。"
"51230-26" = "[s] \"シュロ、そこまでだよ。\""
"51230-30-ナグサ" = "ユカリを、返してもらう。"
"51230-35-シュロ" = "は……！"
"51230-36-シュロ" = "アハッ……"
"51230-37-シュロ" = "アハハハハハハッ！！"
"51230-41-シュロ" = "ウザったいですねぇ！"
"51230-47-シュロ" = "そういえば、小耳に挟んだことがありましたねぇ。"
"51230-48-シュロ" = "シャーレの先生は、どんなことでも解決してくれる――"
"51230-49-シュロ" = "[ruby=ここ]キヴォトス[/ruby]で起こる出来事、な～んにでも首を突っ込んでいく――最高のおバカさんだって。"
"51230-50-シュロ" = "だからその正義感を振り翳して……ここに来たんですかぁ？"
"51230-51-シュロ" = "手前の「百物語」は……あと仕上げだけなのに？"
"51230-52-シュロ" = "なのになのに？ここで、邪魔を……？#n本当に、ほんっとう～に！心から笑いが出ちゃいますぅ！"
"51230-53-シュロ" = "シャーレの先生もですけどぉ……"
"51230-57-シュロ" = "ナグサちゃん、特に[ruby=てめぇ]手前[/ruby]。"
"51230-59-ナグサ" = "……っ！！"
"51230-61-シュロ" = "まさかまさか、よりによって[ruby=てめぇ]手前[/ruby]が「ユカリを返して」って……？ "
"51230-62-シュロ" = "それってぇ、自分が巫女様を助けられると思って来たってことですかぁ？#nねぇ、教えてくださいよぉナグサちゃん？"
"51230-63-シュロ" = "よくもぬけぬけと言えたもんですよねぇ……"
"51230-64-シュロ" = "もしかしてぇ、お仲間のみなさんが背中を押してくれたんですかぁ？"
"51230-65-シュロ" = "巫女様を助けられるのはあなたしかいないって、#n激励してくれたんですぅ？"
"51230-66-シュロ" = "おかしいなぁ……ご存じないんですかねぇ？"
"51230-67-シュロ" = "ナグサちゃん、[ruby=てめぇ]手前[/ruby]はアヤメを助けられなかったのにねぇ？"
"51230-72-シュロ" = "あ～……もしかしてもしかしてぇ、まだみんなに隠してるんだ？"
"51230-73-シュロ" = "大雪原で何があったのか……その真実を――"
"51230-74" = "[s] \"ナグサ、耳を貸す必要ないよ。\""
"51230-75-シュロ" = "いえいえ、ありますよぉ？#n先生だって聞いた方がいいですよぉ？"
"51230-76-シュロ" = "手前様の隣で、「後輩を助けてみせます！」な～んて顔をして駆けつけたナグサちゃんが……"
"51230-77-シュロ" = "本当は助け出す力も、気持ちも持っていない嘘つきだって……知っておいた方がいいと思いますよぉ？"
"51230-83-シュロ" = "手前はまだ覚えておりますよぉ？ナグサちゃん。"
"51230-85" = "アヤメを助けようとして失敗したあの日――"
"51230-86-シュロ" = "その手、アヤメに触れることもできなかったじゃないですかぁ。"
"51230-87-シュロ" = "ま、そもそもナグサちゃんは度量もないですしぃ？"
"51230-89-シュロ" = "アヤメの真似をするだけの子。#nアヤメの隣にいるから、優等生だと勘違いしちゃったおバカさん。"
"51230-91-シュロ" = "ええと、それでどうなったんでしたっけ？"
"51230-92-シュロ" = "そうだ！その右腕――"
"51230-93-ナグサ" = "…………やめて。"
"51230-94-シュロ" = "その腕、もう動かないんでしょ？#n全部知ってますよぉ。アヤメに伸ばしたのに拒絶されちゃった可哀相な右腕。#n黄昏に飲み込まれちゃったんだから。"
"51230-95-シュロ" = "度胸がないですもんねぇ。あとちょっとだったのに、諦めちゃったじゃないですかぁ？"
"51230-96-ナグサ" = "違う……私は……"
"51230-101-シュロ" = "まだ覚えていますよぉ？#nあの時「黄昏」に沈んでいったアヤメ――"
"51230-102-シュロ" = "「百物語」へと成り果てた彼女が、[ruby=てめぇ]手前[/ruby]に放った言葉。"
"51230-103-シュロ" = "たしかぁ――"
"51230-104-ナグサ" = "嫌……！やめて！"
"51230-106-シュロ" = "「最初からあんたを友達だと思ったことなんてない」"
"51230-112-シュロ" = "ええ、ええ。#n実に素敵な言葉でしたよぉ？"
"51230-113-シュロ" = "助けてくれるって期待したのに、何もしないナグサちゃんを見たあの子の絶望ときたら！"
"51230-114-シュロ" = "ああ……あの時のアヤメの気持ち……手前、痛いほど分かります。"
"51230-115-シュロ" = "そもそも――助けに来たのがナグサ、[ruby=てめぇ]手前[/ruby]じゃなければ。"
"51230-116-シュロ" = "もっとマシな人だったら、悲劇を阻止できたかもしれなかったですねぇ。"
"51230-117-シュロ" = "ねぇ、そうは思いませんかぁ？"
"51230-119" = "[ns] \"シュロ……！\""
"51230-123-シュロ" = "邪魔、しないでいただけますぅ？#n怪談家の[ruby=やぶき]箭吹[/ruby]シュロが話してるんですよぉ？"
"51230-135" = "[ns] \"くっ……んんっ！？\""
"51230-136-シュロ" = "いくらシャーレの先生とはいえ、#n百物語に押さえられた状態ではしゃべれませんよねぇ？"
"51230-137-シュロ" = "そこで黙っててくださいよぉ？"
"51230-139-ナグサ" = "先生……！"
"51230-140-シュロ" = "アハハッ！この悲劇は全部ぜ～んぶ、[ruby=てめぇ]手前[/ruby]のせいなんですよぉ？ナグサちゃん。"
"51230-141-シュロ" = "責任転嫁……話が飛躍してるって……？"
"51230-142-シュロ" = "アハッ！でしたらぁ、証拠を見せてあげますよぉ？"
"51230-144-シュロ" = "手前の怪書「稲生物怪録」で――"
"51230-160" = "（満点をとるのは当然で）"
"51230-161" = "（他人の役に立つのは当たり前で）"
"51230-162" = "（期待通りに在るのは義務だった）"
"51230-165-ユカリ" = "名は、勘解由小路ユカリ。"
"51230-166-ユカリ" = "百鬼夜行の中でも名高い一家、勘解由小路家の令嬢。"
"51230-167-ユカリ" = "「勘解由小路家の者としてまっすぐ在りなさい」"
"51230-168-ユカリ" = "それが私の使命であり、義務。"
"51230-169-ユカリ" = "……身共も存じております。"
"51230-170-ユカリ" = "それが身共のやるべきことだと。"
"51230-175-ユカリ" = "でも……"
"51230-176-ユカリ" = "ナグサ先輩と出会って――"
"51230-177-ユカリ" = "初めて……「やるべきこと」ではなく「やりたいこと」を教えてくれた人。"
"51230-181-ユカリ" = "身共が百花繚乱に入れば良いのです！"
"51230-188-ナグサ" = "違うよ……ユカリ。"
"51230-189-ナグサ" = "私はあなたの思うような、立派な人じゃない……"
"51230-194-ナグサ" = "私はただ……真実とは程遠い、嘘を…… "
"51230-195-ナグサ" = "みんなを騙すための仮面を被っていただけ……"
"51230-200-ナグサ" = "全部、嘘でしかなかったのに……"
"51230-211-ナグサ" = "私が、ここにいたから。"
"51230-212-ナグサ" = "アヤメのそばにいるために「ナグサ」を演じて……嘘をつき続けて……"
"51230-213-ナグサ" = "そうしたら、ユカリも百花繚乱になりたいと思うようになって……それで……"
"51230-215-シュロ" = "そうですよぉ、ナグサちゃん。ようやく気がつきましたぁ？#nナグサちゃんが手を伸ばしたものは全部ぜ～んぶ、壊れてしまうんです。"
"51230-216-シュロ" = "全部！ぜ～んぶ！[ruby=てめぇ]手前[/ruby]のせい！#nアヤメが黄昏に呑まれたのも、ユカリが「百物語」になったのもぜ～んぶ。"
"51230-221-シュロ" = "身の程知らずの[ruby=てめぇ]手前[/ruby]が、アヤメの隣にいようとしたから。"
"51230-222-シュロ" = "役者として足りてないのに演じようとしたがために舞い込んだ悲劇――"
"51230-223-シュロ" = "それをよぉ～く、肝に銘じてくださいねぇ？"
"51230-225-ナグサ" = "全部……私のせいで……私が偽りの仮面を被ったせいで……"
"51230-226-ナグサ" = "私が壊してしまった。"
"51230-227-ナグサ" = "私のせいで、ぜんぶ……"
"51230-229" = "[ns] \"……！……ナ、グサ！\""
"51230-230-シュロ" = "フン、ナグサも押さえましょか。"
"51230-239" = "[ns] \"…………！！！\""
"51230-241-シュロ" = "アハハッ！知ってますぅ？"
"51230-242-シュロ" = "心が折れたものってぇ、「怪談」に昇華しやすいんですよぉ。"
"51230-243-シュロ" = "ナグサちゃんも、手前がた～っぷり可愛がってあげますからねぇ？"
"51230-244-シュロ" = "ふう……"
"51230-245-シュロ" = "これにて一件落着、ですねぇ。"
"51230-248-シュロ" = "ふふ……あは、アハハハッ！"
"51230-249-シュロ" = "うんうん、それで十分。"
"51230-250-シュロ" = "分相応に生きて、理解してくだされば結構結構大結構。"
"51230-251-シュロ" = "すべては手前の目論見通り。"
"51230-254-シュロ" = "罵り、[ruby=いが]啀[/ruby]み合い、そして争いを生む――材料。"
"51230-255-シュロ" = "そのために、シャーレの先生をも駒として利用させていただきました。"
"51230-259-シュロ" = "ああ、ご覧ください――コクリコ様。手前の「百物語」を。"
"51230-260-シュロ" = "さあさ、全部壊れてしまいなさい。#n互いを罵り蹴落として――最後は刃を交えて、粉々になってしまえばいい。"
"51230-262-シュロ" = "これで手前は百鬼夜行を燃やし尽くす「百物語」を#n――美しい風流を完成させましたよぉ、コクリコ様。"
"51230-266-シュロ" = "後はカタシロを生み出した巫女様を回収して……"
"51230-271" = "[ns] \"……！！！\""
"51230-273-シュロ" = "っ！？"
"51230-282-シュロ" = "あらあらぁ？百物語を追い払って、どこに行くかと思えばぁ……"
"51230-283-シュロ" = "ユカリを助け出せば、この状況を変えられるとでもぉ？"
"51230-284-シュロ" = "――勘違いも甚だしい。"
"51230-285-シュロ" = "知ってますよぉ？シャーレの先生は手前どもとは違って、指一本でダメになってしまうような非力な存在だって。"
"51230-287" = "[ns] \"……！\""
"51230-292-シュロ" = "無駄だと言っているでしょうが！"
"51230-298-シュロ" = "ハァ～？何を愚かなことを？"
"51230-299-シュロ" = "もしかしてぇ――壊れちゃいました？"
"51230-300-シュロ" = "そうまでしてユカリを助け出して、一体何をするんですぅ？"
"51230-302" = "[ns] \"……はぁっ！！\""
"51230-309-シュロ" = "……理解できないですねぇ。"
"51230-310-シュロ" = "手前様もご存じでしょ？"
"51230-311-シュロ" = "会場で暴れている「無貌の形代」を生み出したのは、ユカリ。"
"51230-312-シュロ" = "手前さん方を憎み、燃やし尽くし――全てを投げ出したいと考えた張本人。 "
"51230-313-シュロ" = "そう、あなたが立派だと口にした百花繚乱の1年生なんて――最初から存在していなかったんですよぉ。"
"51230-314-シュロ" = "ユカリさえも、自分のために手前様を騙して心優しい生徒を演じていた。"
"51230-315-シュロ" = "あ～あ……ウソにウソを重ねた、ウソつきだらけ！"
"51230-316-シュロ" = "そんな、ヒロインでも何でもない彼女を……地面に這いつくばってまで、一体ぜんたい、どうして助けるんですぅ？"
"51230-317-シュロ" = "なんの価値もない嘘つきどもを、どうして――！"
"51230-318" = "[s1] \"……たしかに、嘘をついていたかもしれない。\"\n[s2] \"本音を知られるのが怖くて……\"\n[s3] \"善人を演じていたかもしれない。\""
"51230-322-シュロ" = "ええ、ええ！よぉくご存じじゃないですかぁ。"
"51230-323-シュロ" = "そう、全部ウソなんですよぉ！本心を奥底に隠して、反吐が出そうな嘘ばっかり並べ立てて――"
"51230-324" = "[s] \"……うん。\""
"51230-326" = "[ns] \"でも、それでもいいんじゃないかな？\""
"51230-330-シュロ" = "……はい？"
"51230-331" = "[s4] \"嘘をついて、いい顔して。\"\n[s5] \"そうやって演じるのは、何も悪くないよ。\""
"51230-334-シュロ" = "何を……"
"51230-335" = "[ns] \"言ってしまえば……\""
"51230-339" = "[ns] \"誰だって一度くらいはある、普通のことだからね。\""
"51230-341-シュロ" = "…………………………は？"
"51230-348" = "次回;普通のこと"
