[translation]
"32065-2-イズミ" = "マグロがーーーーー！！！"
"32065-3-ハルナ" = "ぜひお造りの形でと思ったのですが、天ぷらになってしまいましたわね……。"
"32065-4-アカリ" = "うーん、どうやら囲まれてしまったようですね★どうしましょう？"
"32065-6-ジュンコ" = "はっ、バラバラに逃げたら生存率上がるんじゃない！？"
"32065-11-アカリ" = "なるほど、良いアイデアですねジュンコさん★では足の速さ次第ですが、弱肉強食ということで♪"
"32065-16-ハルナ" = "ふふふ、そうですわね。運任せとなりそうですが、それもまたスパイスのようなもの！それでは！"
"32065-21-イズミ" = "えぇっ！？ちょ、ちょっと！待って！私だけ置いていかないで―！？"
"32065-26-イズミ" = "お、置いていかないでってばー！うわーん！もう、覚えてなさいよっ！いつか絶対仕返ししてやるんだからーーっ！！"
"32065-33-ハスミ" = "くっ、小癪な……！各自、分かれて追撃を！！"
"32065-34-正義実現委員会部員" = "はいっ！"
"32065-36-ハスミ" = "ここはトリニティ自治区！私たちから逃げるなんてことは、不可能です！"
"32065-38-ジュンコ" = "はぁ、はぁ……。"
"32065-39-ジュンコ" = "こ、ここまで来れば流石に大丈夫よね……？"
"32065-45-ジュンコ" = "……え？"
"32065-46-アカリ" = "あら、ジュンコさん……。"
"32065-47-ジュンコ" = "あ、アカリ！？ど、どうしたのそんなフラフラの状態で！？"
"32065-48-アカリ" = "まあ、端的に言いますと……無理でした★"
"32065-53-ジュンコ" = "アカリっ！？"
"32065-57-ツルギ" = "くひひっ……きひひひひ……。"
"32065-58-ジュンコ" = "……えっ？な、何っ！？鬼……！？"
"32065-60-ツルギ" = "きゃははははははぁぁっっ！！！"
"32065-61-ジュンコ" = "いやあああぁぁぁぁぁっ！？ごめんなさいぃぃぃぃぃーーーっ！？"
"32065-66" = "次回;新しい視点"
