[translation]
"32105-3-チンピラ" = "ぐあぁぁぁっ！？"
"32105-8-ハナコ" = "ふふっ。あらあら、繊細ですねぇ♡"
"32105-9-アズサ" = "先を急ごう。"
"32105-14-コハル" = "ま、待って！置いていかないでっ！？"
"32105-15-ヒフミ" = "あ、あはは……すみません、通らせてもらいますね……。"
"32105-17" = "次回;第2次特別学力試験（２）"
