[translation]
"32130-1" = "第13話;それでも"
"32130-2" = "（その後も補習授業部のみんなは、第3次特別学力試験に向けて日々努力を重ねた……）"
"32130-24" = "第4次補習授業部模試、結果――"
"32130-25" = "ハナコー100点[007eff]（合格）[-]"
"32130-26" = "アズサー82点[FF6666]（不合格）[-]"
"32130-27" = "コハルー74点[FF6666]（不合格）[-]"
"32130-28" = "ヒフミー79点[FF6666]（不合格）[-]"
"32130-53" = "第5次補習授業部模試、結果――"
"32130-54" = "ハナコー100点[007eff]（合格）[-]"
"32130-55" = "アズサー94点[007eff]（合格）[-]"
"32130-56" = "コハルー90点[007eff]（合格）[-]"
"32130-57" = "ヒフミー93点[007eff]（合格）[-]"
"32130-71" = "第6次補習授業部模試、結果――"
"32130-72" = "ハナコー100点[007eff]（合格）[-]"
"32130-73" = "アズサー91点[007eff]（合格）[-]"
"32130-74" = "コハルー83点[FF6666]（不合格）[-]"
"32130-75" = "ヒフミー89点[FF6666]（不合格）[-]"
"32130-82" = "最後の特別学力試験まで、あと6日"
"32130-85" = "最後の特別学力試験まで、あと5日"
"32130-88" = "最後の特別学力試験まで、あと4日"
"32130-91" = "最後の特別学力試験まで、あと3日"
"32130-94" = "最後の特別学力試験まで、あと2日"
"32130-97" = "最後の特別学力試験まで、あと1日"
"32130-100-ヒフミ" = "……ついに明日、ですね。"
"32130-101-ハナコ" = "はい……。"
"32130-102-アズサ" = "……。"
"32130-103-コハル" = "ま、まさかまた急に、色々と変わったりしないよね？"
"32130-107-ヒフミ" = "はい、今のところは……。"
"32130-108-ハナコ" = "そうですね。試験範囲は以前の通りですし、合格ラインも変わらず90点以上。"
"32130-109-ハナコ" = "場所はトリニティ第19分館の第32教室。本館からは離れてますが、そこまで遠くはありません。"
"32130-110-ハナコ" = "時間は午前9時からで、変わっていませんね。"
"32130-111-ハナコ" = "むしろ気になる点と言えば……昨日から本館が不自然なくらいに静かなことです。人けがピタッと無くなってしまったようで。"
"32130-112-ハナコ" = "……念のため今晩も、私の方で掲示板をずっと見ておきますね。"
"32130-113-ヒフミ" = "は、ハナコちゃんも寝た方が……。"
"32130-114-ハナコ" = "ふふっ、私は大丈夫です。それに、私にはこれくらいしかできませんし……。"
"32130-115-ヒフミ" = "そ、そんなことはありません！ハナコちゃんがすごく丁寧に勉強を教えてくれたおかげで、私もアズサちゃんもコハルちゃんも、すっごく成績が上がって……！"
"32130-116-ハナコ" = "それは、みなさんが頑張ったからですよ。"
"32130-117-ハナコ" = "何日もろくに睡眠を取れなかったのに、よく頑張ったと思います。"
"32130-118" = "[s] \"……うん、きっと大丈夫。\""
"32130-119-ヒフミ" = "はい。それでも、90点はギリギリですが……明日の試験問題が簡単だったら、きっと……。"
"32130-120-アズサ" = "……。"
"32130-121-コハル" = "……っ！そ、そんな都合の良いこと起きるわけない！私はまだまだ深夜まで勉強するから！"
"32130-122-コハル" = "100点！100点取れれば、誰も文句なんて言えないでしょ！？"
"32130-123-ヒフミ" = "こ、コハルちゃん……気持ちは分かりますが、今日はもうゆっくり休んだ方が……。"
"32130-124-ハナコ" = "そうですよ。コハルちゃんが頑張ったのはみんなが知ってます、大丈夫です。今日はもう休んで、明日に備えた方が良いと思いますよ。"
"32130-125-アズサ" = "休むのも戦略のうちだ。"
"32130-126-ハナコ" = "はい。そしてそれは、アズサちゃんも同じですよ？"
"32130-127-アズサ" = "……うん。今日くらいはゆっくり休もうと思う。"
"32130-131-ヒフミ" = "いよいよ明日……私たちの運命が決まります。"
"32130-132-アズサ" = "もし……いや、縁起の悪いことは言わないでおこう。必ず合格する。"
"32130-133-コハル" = "わ、私も！絶対に負けないんだから！"
"32130-134-ヒフミ" = "そ、そうですね。泣いても笑ってもあと一回です。頑張りましょう。"
"32130-135-ハナコ" = "はい。ここまでしっかり頑張ってきたのですから、後は最後まで最善を尽くすだけです。"
"32130-136" = "[s] \"……今までの頑張りを信じよう。きっと大丈夫。\""
"32130-137-ヒフミ" = "はいっ。"
"32130-138-ハナコ" = "そうですね。"
"32130-139-アズサ" = "うん。"
"32130-140-コハル" = "……。"
"32130-142" = "最後の特別学力試験まで、あと1日"
"32130-148-アズサ" = "……。"
"32130-153-ハナコ" = "……。"
"32130-156-？？？" = "アズサ、日程が変わった。"
"32130-157-アズサ" = "……？"
"32130-159-？？？" = "明日の午前中だ、約束の場所で命令を待て。"
"32130-160-アズサ" = "ま、待ってサオリ、明日は……。"
"32130-161-サオリ" = "何か問題が？"
"32130-162-アズサ" = "ま、まだ準備ができてない。計画よりも日程を早めるのは、リスクが大きすぎる。"
"32130-163-サオリ" = "いや、明日決行だ。これは確定事項、しっかり準備をしておけ。"
"32130-164-アズサ" = "……。"
"32130-165-サオリ" = "明日になれば、全てが変わる。私たちのアリウスにも、このトリニティにも、不可逆の大きな変化が起きることになる。"
"32130-166-サオリ" = "トリニティのティーパーティーのホスト、[ruby=きりふじ]桐藤[/ruby]ナギサのヘイローを破壊する……そのためにお前はここにいるんだ。"
"32130-167-アズサ" = "……。"
"32130-168-サオリ" = "お前の実力は信頼している。上手くやれ、[ruby=ゆりぞの]百合園[/ruby]セイアの時のように。"
"32130-169-アズサ" = "……分かった。"
"32130-170-アズサ" = "準備しておく。"
"32130-175-サオリ" = "アズサ。"
"32130-176-アズサ" = "……？"
"32130-177-サオリ" = "忘れてないだろうな、「vanitas vanitatum」。"
"32130-178-アズサ" = "……全ては虚しいもの。"
"32130-179-アズサ" = "どんな努力も、成功も、失敗も……全ては最終的に、無意味なだけ。"
"32130-180-アズサ" = "……一度だって、忘れたことはない。"
"32130-185-サオリ" = "……。"
"32130-187-ハナコ" = "……。"
"32130-189" = "次回;こくはく"
