[translation]
"1006515-1" = "初心忘るるべからず"
"1006515-2" = "（陰陽部での仕事は、思ったより順調に進んだ）"
"1006515-12-カホ" = "あっ、先生？"
"1006515-13-カホ" = "早かったですね。すみません、まだ準備が……。"
"1006515-14" = "[s1] \"思ったより早く終わっちゃって……。\"\n[s2] \"ごめんね、掃除中に。\""
"1006515-17-カホ" = "あ、いえ。掃除が長引いたのは私の不手際ですから。"
"1006515-18-カホ" = "いつもより念入りにやってしまって……。"
"1006515-19-カホ" = "時間配分を間違えてしまいましたね。"
"1006515-20-カホ" = "お見苦しいところをお見せして申し訳ありません。"
"1006515-21" = "[s3] \"いやいや、カホは悪くないよ。\"\n[s4] \"私も手伝うね。\""
"1006515-24-カホ" = "いえ、先生に手伝っていただくわけには……。"
"1006515-25-カホ" = "その……仰る通り、2人でやれば効率的ではありますが。"
"1006515-26-カホ" = "……そうですね。"
"1006515-27-カホ" = "わかりました。#nそれでは、少しだけ手伝っていただけますか？"
"1006515-30" = "（しばらく一緒に掃除していると……）"
"1006515-32-カホ" = "よいっしょっと……ここは気をつけて……。"
"1006515-36" = "[ns5] \"すごく丁寧に磨くんだね？\"\n[ns6] \"すごく大切な物なんだね。\""
"1006515-39-カホ" = "あっ、はい。"
"1006515-40-カホ" = "これは特別なもので……。"
"1006515-41-カホ" = "といっても、私にとっての、ですが。#nあまり執着しすぎるのも良くないのかもしれませんが、大切なものなんです。"
"1006515-42" = "[s] \"カホの大切なもの……ちょっと気になるかも。\""
"1006515-43-カホ" = "そうですね……ご覧になりますか？"
"1006515-44" = "[s] \"え？良いの？\""
"1006515-45-カホ" = "ええ、別に隠し立てするようなものでもありませんし。"
"1006515-46-カホ" = "はい、どうぞ。少し重いので気をつけてくださいね。"
"1006515-51" = "[ns] \"これって、百鬼夜行の生徒がカホにくれた……？\""
"1006515-55-カホ" = "はい、そうなんです。"
"1006515-56-カホ" = "あれは忘れもしない……私が陰陽部で、戦略リーダーになったばかりの頃。"
"1006515-57-カホ" = "お祭りで、商店街の皆さんのお手伝いをしていたんです。"
"1006515-58-カホ" = "まだ仕事に慣れていなくて、何ならトラブルメーカーに近かった私ですが――"
"1006515-59-カホ" = "お祭りが無事に終わった後……皆さんから、これを頂いたんです。"
"1006515-60-カホ" = "「陰陽部が手伝ってくれたおかげで今回も無事に成功した」とか、#n「手伝ってくれて助かった」とか――"
"1006515-61-カホ" = "本当に……身に余るお言葉をいただきました。"
"1006515-62-カホ" = "私自身が大したことをしたわけでもないので、少しお恥ずかしいのですが。"
"1006515-63" = "[s] \"ううん。カホならきっと最善を尽くしたんだろうし。\""
"1006515-64-カホ" = "わ、私はただ……百鬼夜行連合学院の文化が広く知られたら良いなと、その一心で……。"
"1006515-65-カホ" = "でも……この感謝状を見るたびに、胸がいっぱいになるんです。"
"1006515-66-カホ" = "ああ、私の気持ちは間違っていなかったんだって。#n少しでも皆さんに伝わってたんだなって。"
"1006515-67-カホ" = "戦略リーダーとして、やっていけるかもしれない……という自信にも繋がりました。"
"1006515-68-カホ" = "だから、あの時の気持ちを忘れないよう――こうして毎日、丁寧に拭いているんです。"
"1006515-69" = "[s] \"素敵な話だね。\""
"1006515-70-カホ" = "ふふっ、ありがとうございます。"
"1006515-74-カホ" = "これで片付けは一通り終わりましたね。"
"1006515-75-カホ" = "お手伝いありがとうございました、先生。"
"1006515-76" = "[s] \"カホの方こそお疲れ様。\""
"1006515-77-カホ" = "それでは、お茶を淹れてきますね。"
"1006515-78-カホ" = "きっと、今日のお茶の味は格別です。#n先生にこうして手伝っていただけたのですから。"
"1006515-79-カホ" = "それでは、準備しますね。"
"1006515-81" = "（その後、綺麗になった休憩室で、カホと一緒にゆっくりとお茶を飲んだ）"
