[translation]
"2002705-1" = "期待"
"2002705-2" = "（1人で悩んでないか心配になり、シロコの部屋に向かおうとしたところ……）"
"2002705-3" = "（ロビー[ruby=たたず]に佇む[/ruby]シロコの姿があった）"
"2002705-11" = "[ns1] \"……？\"\n[ns2] \"何をしてるんだろう……？\""
"2002705-22" = "[ns] シロコに付いていく。"
"2002705-28" = "[ns]（…………？）"
"2002705-30" = "[ns3] \"シロコが……\"\n[ns4] \"……消えた？\""
"2002705-33-？？？" = "…………。"
"2002705-44-？？？" = "……ん。"
"2002705-46" = "[ns] \"！？\""
"2002705-49" = "[ns5] \"ビックリした……！\"\n[ns6] \"……シロコ？\""
"2002705-54-シロコ" = "あ……"
"2002705-55-シロコ" = "ごめんね、先生。驚かせるつもりは無かったの。"
"2002705-56-シロコ" = "誰かの気配を感じて隠れてみたけど……"
"2002705-57-シロコ" = "先生だって分かったから。"
"2002705-58-シロコ" = "……ん。どこに行くのか、って……？"
"2002705-59-シロコ" = "その……特に決めてるわけでは。#nちょっと歩きたくなっただけ。"
"2002705-63-シロコ" = "えっと……ごめん。"
"2002705-64-シロコ" = "本当は……ちょっと寂しくて、また見に行きたくなったんだ。"
"2002705-65-シロコ" = "……海を。"
"2002705-66" = "[s7] \"花火を見たところ？\"\n[s8] \"バーベキューをした場所？\""
"2002705-69-シロコ" = "……うん。"
"2002705-70-シロコ" = "みんなにも声をかけるか悩んだけど……もう、夜遅いし。"
"2002705-71-シロコ" = "余計な心配をかけちゃうんじゃないかって……"
"2002705-72-シロコ" = "でも……この景色は、帰ったらもう見られないでしょ？"
"2002705-73-シロコ" = "それで、あまり眠れそうになかったから……"
"2002705-74" = "[s] \"…………。\""
"2002705-75-シロコ" = "最後にもう一度見たら、ちゃんと眠れるんじゃないかと思って。"
"2002705-76-シロコ" = "だから、ちょっとだけ……"
"2002705-80-シロコ" = "……やっぱり、こんな時間に抜け出しちゃダメかな？"
"2002705-81" = "[s9] \"一緒に行こうか、シロコ。\"\n[s10] \"それなら、同伴者が必要だね。\""
"2002705-84-シロコ" = "……！……先生も来てくれるの？"
"2002705-85-シロコ" = "……うん、行こう。"
"2002705-89-シロコ" = "……じゃあ、こっち。"
"2002705-97-シロコ" = "……着いた。"
"2002705-101-シロコ" = "ん……。"
"2002705-102" = "[s11] \"どうしたの？\"\n[s12] \"浮かない顔してるけど……。\""
"2002705-105-シロコ" = "……うん。"
"2002705-106-シロコ" = "海が……夕方に見たのとは、なんか違う……"
"2002705-107-シロコ" = "……潮の、満ち引きかな？"
"2002705-108-シロコ" = "じゃあ、あの時の景色は……"
"2002705-109-シロコ" = "もう、見られないんだね。"
"2002705-110" = "[s13] \"同じ場所でも、違って見えることがあるんだ。\"\n[s14] \"でも、もっと楽しい景色が待ってるよ。\""
"2002705-113-シロコ" = "どういう意味……？"
"2002705-114-シロコ" = "帰ったら分かる、って……？#n学校に海はないけど……"
"2002705-115-シロコ" = "大切なのは、海じゃない……？"
"2002705-116-シロコ" = "ん……難しくて、よく分からない。"
"2002705-117-シロコ" = "じゃあ……花火とか、バーベキューが無いから？"
"2002705-118-シロコ" = "……それも、違うの？"
"2002705-119-シロコ" = "なにが大切なんだろう……"
"2002705-120" = "[s15] \"それを考える時間も、大切かもしれないね。\"\n[s16] \"その時になったら、きっと分かるはずだよ。\""
"2002705-123-シロコ" = "……うーん。"
"2002705-124-シロコ" = "ごめん、先生。私にはまだ難しいかも。"
"2002705-128-シロコ" = "けど……"
"2002705-129-シロコ" = "先生の言葉だから、かな。"
"2002705-130-シロコ" = "いつか、分かる気がしてきたよ。"
"2002705-131-シロコ" = "きっと、ね。"
"2002705-132-シロコ" = "……うん、楽しみ。"
"2002705-133-シロコ" = "…………。"
"2002705-134-シロコ" = "ありがとう。今日は、2人で話せて良かった。"
"2002705-141-シロコ" = "先生……"
"2002705-143-シロコ" = "いつか、答え合わせしようね。"
