[translation]
"1300415-1" = "内緒のノート"
"1300415-2" = "（ある日、用事があって対策委員会の教室を訪れた）"
"1300415-9-ノノミ" = "ふふん～ふっふふん～"
"1300415-10" = "[ns] \"おはよう、ノノミ。\""
"1300415-15-ノノミ" = "せ、先生！？"
"1300415-16-ノノミ" = "いついらしたんですか！？"
"1300415-17-ノノミ" = "つ、ついさっきですか……ドアの音にも気づかなかったなんて……"
"1300415-18-ノノミ" = "先生がいらっしゃると知ってたら、お菓子くらい用意したのに……"
"1300415-19" = "[s] \"それで、ノノミは何をしてたの？\""
"1300415-23-ノノミ" = "えっと、その……"
"1300415-24-ノノミ" = "ひ、秘密です。"
"1300415-25" = "[s1] \"そっか、ちょっと気になったんだけど……\"\n[s2] \"きっと、何か事情があるんだよね。\""
"1300415-30-ノノミ" = "うーん、事情と言うほどではありません。"
"1300415-31-ノノミ" = "そうですね、ちょっと恥ずかしいんですけど……"
"1300415-32-ノノミ" = "先生にだけ、特別に見せちゃいますね。"
"1300415-38" = "[ns] \"何のノートなの……？\""
"1300415-39-ノノミ" = "対策委員会のみんなと、いつかやってみたいことをメモしたウィッシュリストです。"
"1300415-40-ノノミ" = "内緒のノートですから、秘密にしてくださいね？"
"1300415-41-ノノミ" = "今日は誰も教室に来ないはずだったので、こっそり見てたんです。"
"1300415-42" = "[s] \"どうしてみんなには秘密なの？\""
"1300415-43-ノノミ" = "それは……"
"1300415-44-ノノミ" = "私の目標を達成しようと、みんな助けてくれるに決まってますから。"
"1300415-45-ノノミ" = "ただでさえ借金の返済で大変なのに、負担を増やすわけにはいきません。"
"1300415-46-ノノミ" = "だから、これは私だけの内緒のノートなんです。"
"1300415-47-ノノミ" = "と言っても、先生には見られてしまいましたけど……あはは。"
"1300415-48" = "[s] \"そうだったんだ……ごめんね。\""
"1300415-49-ノノミ" = "気にしないでください。#n教室で開いている以上、いつか見られてしまうとは思っていましたから☆"
"1300415-50-ノノミ" = "この際ですし、先生も見てみませんか？"
"1300415-51" = "[s3] \"見てもいいの？\"\n[s4] \"読んでもいいの？\""
"1300415-54-ノノミ" = "もちろんです。実は、そんなに大した内容ではないので。"
"1300415-55-ノノミ" = "うんうん、ぜひ一緒に見ましょう☆"
"1300415-65-ノノミ" = "達成したものには、赤ペンで丸をつけてるんです。"
"1300415-66-ノノミ" = "一緒にスイーツを食べに行く、学校中を大掃除する……#n何気ないことも、みんなで力を合わせて達成したことも、色々ありましたね。"
"1300415-67-ノノミ" = "これを見ていると……みんなの笑顔を思い出して、とっても幸せな気持ちになるんです。"
"1300415-71-ノノミ" = "あっ……「5辛のピザにチャレンジする」なんてのもありましたね。"
"1300415-72-ノノミ" = "顔を真っ赤にしながら食べてたセリカちゃんが懐かしいです☆"
"1300415-74-ノノミ" = "それから……こっちは、まだ達成できてない目標ですね。"
"1300415-75-ノノミ" = "いつか、このリスト全部に赤い印をつけたいのですが……"
"1300415-76-ノノミ" = "一つ達成しても、今度は二つ目標ができてしまって――"
"1300415-77-ノノミ" = "どんどんリストが増えるばかりなんです。"
"1300415-78-ノノミ" = "まだ達成できてないものが、100個も……あはは、どうしましょう。"
"1300415-79" = "[s] \"むしろ、いいことじゃない？\""
"1300415-83" = "[ns5] \"それだけ、これから思い出が作れるってことだから。\"\n[ns6] \"きっと、楽しい毎日が待ってるよ。\""
"1300415-90-ノノミ" = "……そうですよね！"
"1300415-91-ノノミ" = "いつも借金の返済に悩まされていますが……"
"1300415-92-ノノミ" = "楽しい時間もいっぱいありますからね。"
"1300415-93-ノノミ" = "うんうん。リストを達成できるよう、もっと頑張ります！"
"1300415-97-ノノミ" = "せっかくですし、先生も一緒に思い出を作りませんか？"
"1300415-98" = "[s] \"もちろんだよ。\""
"1300415-99-ノノミ" = "ではまずは、スカイダイビングから！"
"1300415-100-ノノミ" = "地上から約4000メートルのフリーフォール……#n想像しただけで楽しそうですよね！"
"1300415-104" = "[ns] \"そ、それは遠慮したいかな……\""
"1300415-107-ノノミ" = "ふふっ、冗談です☆"
