[translation]
"1602-1" = "給食部のドタバタ衛生管理評価（２）"
"1602-2-イオリ" = "まずは、個々人のチェックだ。"
"1602-3-イオリ" = "各自、手を出せ。"
"1602-4-フウカ" = "はい。"
"1602-5-ジュリ" = "どうぞ。"
"1602-6-イズミ" = "衛生面なら自信あるよ！えっへん！"
"1602-7-イズミ" = "美味しく食べるためには、そういうのも大事だからね！"
"1602-8-イオリ" = "……っていうか、お前は給食部じゃないだろ。"
"1602-9-イオリ" = "まあいい。"
"1602-11-イオリ" = "ふむ、よし。全員問題はないな。"
"1602-12-イオリ" = "個人の衛生状態は良好、と。"
"1602-13-イオリ" = "次は……。"
"1602-15-イオリ" = "道具の清潔さ……良好。"
"1602-16-イオリ" = "テーブルや椅子、カーテンも清潔だな。"
"1602-17-イオリ" = "食材の賞味期限も……問題なし。"
"1602-18-イオリ" = "次……肝心の厨房か。"
"1602-21-フウカ" = "（ごくり）"
"1602-23" = "（グツグツグツグツ……）"
"1602-24-イオリ" = "ん？あれは……？"
"1602-25" = "ガタガタッ、ガタンッ、ゴトンッ……！"
"1602-26-イズミ" = "鍋がひとりでに動いてる！？"
"1602-27-フウカ" = "ジュリ、あれあなたが作ってた料理でしょ！？何をしたの！？"
"1602-28-ジュリ" = "おそらく、料理が自我を持って暴走を始めたのかと……！"
"1602-29-フウカ" = "また！？"
"1602-30-イオリ" = "……また？"
"1602-31-ジュリ" = "でも大丈夫です、先輩！"
"1602-32-ジュリ" = "こんな状況になっても対応できるよう、訓練してきましたから！"
"1602-33-ジュリ" = "衛生面と給食部の平和、そして皆さんの安全のために！"
"1602-34-ジュリ" = "私、戦います！"
"1602-35-ジュリ" = "イオリさんには負けません！"
"1602-36-フウカ" = "だからそれ何の話！？"
"1602-44-イズミ" = "うわわっ！料理が襲ってくる！？"
"1602-45-イズミ" = "そっか……私、考えたこともなかった。"
"1602-46-イズミ" = "料理は食べるものだとばかり……。"
"1602-47-イズミ" = "時には、逆に料理に食べられることもあるんだね……！"
"1602-48-イオリ" = "いや、普通無いだろ……。"
"1602-49-イオリ" = "それよりこれは、衛生問題なのか……？"
"1602-50-イオリ" = "……違う、よな？#n\nうーん……とりあえず一旦良好で……。"
"1602-55-イオリ" = "全点チェック完了……。"
"1602-56-イオリ" = "ちっ、満点だ。"
"1602-57-イズミ" = "えっへん！"
"1602-58-イオリ" = "いや、だからお前は給食部じゃなくて、美食研究会のメンバーだろ……？"
"1602-59-フウカ" = "でも、思ったより素直というか……。"
"1602-60-イオリ" = "別に私は相手を屈服させるために来たわけでも、粗探しに来たわけでもない。"
"1602-61-イオリ" = "ただ、衛生面のチェックをしに来ただけだ。"
"1602-62-イオリ" = "認めるよ、給食部の衛生面は何の問題も無い。"
"1602-63-ジュリ" = "あ……。"
"1602-64-イズミ" = "良かった良かった！"
"1602-67-イオリ" = "でも、見直したよ給食部。"
"1602-68-イオリ" = "給食への熱意、完璧な衛生管理……。"
"1602-69-イオリ" = "美味しくないのはさておき、そういったところはちゃんとしてる。"
"1602-70-イズミ" = "思い知ったか～！"
"1602-71-フウカ" = "その「さておき」の部分が大事なんだけど！っていうか、だから何であなたは給食部サイドなの！？"
"1602-72-イオリ" = "この結果を見る限り、#n前回の評価が間違ってる線の方が濃厚だな。"
"1602-73-イオリ" = "これは再考する必要がある。"
"1602-74-ジュリ" = "私、感銘を受けました。"
"1602-75-ジュリ" = "速やかで公明正大な評価、これぞ風紀委員会！"
"1602-76-ジュリ" = "今回の調査員が、イオリさんでよかったです！"
"1602-77-イオリ" = "……お世辞を言っても何も出ないぞ。"
"1602-78-イオリ" = "はあ、まあいい。とりあえず私はもう帰る。"
"1602-82-フウカ" = "（良かったぁ……無事に終わった、よね？）"
"1602-83-イオリ" = "ふう、喋りすぎたな……。"
"1602-84-イオリ" = "喉が渇いた……何か飲み物とかないか？"
"1602-85-フウカ" = "飲み物……お水でいい？"
"1602-87-ジュリ" = "あっ、でしたらちょうど良いものがありますよ！"
"1602-90-ジュリ" = "こちらどうぞ、グイっといってしまってください！"
"1602-91-イオリ" = "ん、オレンジジュースか？何にせよ、ありがたくいただく。"
"1602-92-イズミ" = "私も！私も飲みたい！"
"1602-93-ジュリ" = "ふふっ、はい。まだまだありますのでどうぞ！"
"1602-95-フウカ" = "……ん？"
"1602-96-フウカ" = "給食部で、オレンジジュースの発注なんてしてた……？"
"1602-97-ジュリ" = "あ、これは給食用ではなく。"
"1602-98-ジュリ" = "私がおもてなしのために作った、生絞りのフルーツジュースです！"
"1602-99-ジュリ" = "前回も調査員の方に差し上げたのと、同じものを！"
"1602-100-フウカ" = "……前回？"
"1602-101-フウカ" = "……。"
"1602-103-イオリ" = "前回給食部に来た調査員は、食中毒と診断された。"
"1602-105-フウカ" = "……！！"
"1602-106-フウカ" = "待っ、ストーーップ！"
"1602-107-イオリ" = "ごくっごくっ……ん？"
"1602-108-イオリ" = "……うっ！？"
"1602-111-フウカ" = "それだぁぁぁぁああああ！！"
"1602-112-ジュリ" = "あらっ？イオリさん？疲れて寝てしまったのですか？"
"1602-113-ジュリ" = "いくらなんでもここでは困ります、起きてくださ～い。"
"1602-114-フウカ" = "ど、どうしよう！？"
"1602-115-フウカ" = "このままじゃ、また評価が……！"
"1602-116-フウカ" = "ましてや今回は風紀委員だし、絶対前どころじゃない評価が……！#n給食部の予算がまた半分に……！？"
"1602-117-フウカ" = "……落ち着いてフウカ、まだ解決方法はあるはず……！"
"1602-118-フウカ" = "そ、そうだ！"
"1602-119-フウカ" = "他の風紀委員に見つかる前に、被害者をいなかったことにするとか……！"
"1602-127-イズミ" = "（ごくっ、ごくっ）"
"1602-129-イズミ" = "ぷはー、美味しい！"
"1602-131" = "（結局どうにもならず、無事目が覚めたイオリから容赦なくFランクの評価をもらった）"
"1602-132" = "給食部のドタバタ衛生管理評価"
