[translation]
"21160-1" = "第16話;あともう一歩！"
"21160-2" = "ミレニアム生徒会・差押品保管所"
"21160-5-モモイ" = "はあ、はあ、逃げ切れた……！？"
"21160-6-モモイ" = "先生、ミドリ、アリス、大丈夫！？"
"21160-7-アリス" = "HPは十分です。"
"21160-8-ミドリ" = "私も先生も、大丈夫。"
"21160-9-モモイ" = "良かった……ところで、ここが差押品保管所？何かだいぶ滅茶苦茶だけど。"
"21160-10-ミドリ" = "ガラスも割れてるし、棚も倒れてる……。"
"21160-11-ミドリ" = "カリン先輩の跳弾かな……戦闘とか爆発の余波が、ここまで届いたのかも。"
"21160-12-モモイ" = "ユウカは、もうさっきの時点でアリスが「鏡」を持ってると思い込んでるだろうから……きっと、部室の方に逃げたって考えてるはず。まさか、私たちがここに来てるとは思わないだろうね。"
"21160-13-モモイ" = "とりあえず「鏡」さえ持ち出せれば、後はヴェリタスがどうにかしてくれるはず……！"
"21160-15-ミドリ" = "あっ、見つけた、「鏡」！これさえあれば……！"
"21160-16-モモイ" = "よしっ！さあ、早く帰ろー……"
"21160-17-アリス" = "……？"
"21160-18-アリス" = "……静かに、ミュートでお願いします。"
"21160-19-モモイ" = "ん？"
"21160-21-アリス" = "……誰かがこちらに向かってきています。足音から考えて、恐らく人数は一人。"
"21160-22-モモイ" = "うーん……このままここにいて、ユウカとかメイド部がまとめて戻ってきたら困るし、一人くらいならみんなで無理やり突破しちゃおっか。"
"21160-23-アリス" = "……。"
"21160-24-ミドリ" = "ちょ、ちょっと待って。"
"21160-25-ミドリ" = "ハレ先輩から連絡が来てる。"
"21160-27" = "「逃げて、いや隠れて！早く！何としてもそこ $！#^&！@#」"
"21160-28-モモイ" = "えぇ、いったいどういうこと……？"
"21160-29-ミドリ" = "いつも冷静なハレ先輩が、どうしたんだろ。ネズミでも出たのかな。"
"21160-30-アリス" = "接近対象を確認、ミレニアムの生徒名簿を検索……対象把握。"
"21160-31-アリス" = "身長146cm、ダブルSMG、メイド服の上から龍柄のスカジャン……"
"21160-32-ミドリ" = "え……？"
"21160-33-モモイ" = "ま……まさか……！？"
"21160-35-ミドリ" = "隠れてっっ！！"
"21160-38-アリス" = "先生、お尻が出ています！"
"21160-39-ミドリ" = "は、早く！急いで！"
"21160-43-ネル" = "……。"
"21160-44-ネル" = "ふーん、もうめっちゃくちゃだな。"
"21160-45-モモイ" = "（ね、ね、ネル先輩だ！！）"
"21160-46-ミドリ" = "（な、なんで！？どうしてあの人がここに！）"
"21160-47-ネル" = "んん……？"
"21160-48-ネル" = "何か、声が聞こえたような気が……。"
"21160-49-モモイ" = "（！？）"
"21160-50-ミドリ" = "（ひいぃ……！）"
"21160-51-アリス" = "（……）"
"21160-52-アリス" = "（この人、何かが違います……）"
"21160-53-アリス" = "（恐怖……初めての感情……）"
"21160-54-アリス" = "（今この状況で、戦闘が発生した場合の成功確率……ほぼ0%……！）"
"21160-56-ネル" = "ふーん……。"
"21160-57-ネル" = "確かに気配が……机の下か？"
"21160-59" = "（ザッ……）"
"21160-61" = "（ザッ……）"
"21160-62-モモイ" = "（ど、どうしよう……！）"
"21160-63-ミドリ" = "（今度こそ終わり……！？）"
"21160-64-モモイ" = "（せ、先生！どうしよう！？）"
"21160-65-アリス" = "（すぐ目の前……もう、覗き込まれたら……！）"
"21160-68-？？？" = "あ、あの！"
"21160-69-ネル" = "あん？"
"21160-71-ユズ" = "ね、ネル先輩！大変です！"
"21160-72-モモイ" = "（！？）"
"21160-73-ミドリ" = "（ゆ、ユズちゃん！？）"
"21160-74-ネル" = "あんたは……？"
"21160-75-ユズ" = "せ、生徒会「セミナー」所属の、ユズキです。"
"21160-76-ユズ" = "戦闘ロボットが暴走したせいで今、あちこちがめちゃくちゃなんです！"
"21160-77-ユズ" = "アカネ先輩とカリン先輩が、制圧を試みていますが……。"
"21160-78-ネル" = "なんだよ、暴走か？あれを差し押さえたのなんかずいぶん前だろうに、まだ整備が終わってねえのか。"
"21160-79-ユズ" = "じょ、状況的に、助けが必要かと思い……それで、ここにいらっしゃると聞いたので……。"
"21160-80-ネル" = "はぁ、仕方ねぇな。"
"21160-81-ユズ" = "わ、わたしはここの整理をします。#nそ、その、戦闘は怖くて……経験も、あまり無いですし……。"
"21160-82-ネル" = "んなこたどうでもいいけど、それよりあんた……。"
"21160-83-ネル" = "覚えときな。戦闘で一番大事なのは、武器でも経験でもねぇ。"
"21160-84-ユズ" = "は、はい……？"
"21160-85-ネル" = "度胸だ。"
"21160-86-ネル" = "その点で、あんたに素質が無いとは思わねぇ。"
"21160-87-ネル" = "自分がどう思われてるかくらい、あたしにも分かってる。それに、あんたが結構ビビりなこともまあ分かる。それなのに、初対面でこのあたしに声をかけるなんてのは、それなりに度胸がいることだろうからな。"
"21160-88-ユズ" = "は、は、はい！あ、ありがとうございます！？"
"21160-89-ネル" = "じゃあな、またどっかで会おうぜ。"
"21160-91-ユズ" = "ふぇぇ……。"
"21160-93" = "（べたっ）"
"21160-95-ユズ" = "し、死んじゃうかと思った……。"
"21160-96-モモイ" = "ユズうぅぅぅぅぅー！！"
"21160-97-ミドリ" = "ユズちゃんすごい！おかげで命拾いしたよ！"
"21160-98-ユズ" = "ち、力になれて、良かった……。"
"21160-99-ユズ" = "そ、それより、今アリスちゃんが持ってるのが……"
"21160-102-アリス" = "はいっ。"
"21160-103-アリス" = "これが人類と世界を救う、私たちの新たな武器。"
"21160-104-アリス" = "「鏡」です！"
"21160-105-ユズ" = "や、やっと……！"
"21160-106-モモイ" = "お祝いは後にして、急ごう！ネル先輩が戻ってきたら今度こそ一巻の終わり！"
"21160-107-ユズ" = "この先には戦闘型ロボットがたくさんいる……気を付けて！"
"21160-108-ミドリ" = "そうだね、まだ任務は終わってない！"
"21160-109-ユズ" = "わたしたちの目的は「鏡」じゃなくて……「G.Bible」！早く、ヴェリタスの部室に行かなきゃ……！"
"21160-110-アリス" = "後方は私が担当します。先生、指示を！"
"21160-113" = "[ns1] \"みんなで無事に、部室まで戻ろう！\"\n[ns2] \"全員、戦闘準備！\""
"21160-116-ミドリ" = "はい！"
"21160-117-モモイ" = "絶対……無事に帰ろう！"
"21160-118-アリス" = "アリス、戦闘を始めます！"
