[translation]
"21170-1" = "第17話;終わらない戦い"
"21170-2" = "ミレニアム・校舎廊下"
"21170-3-アスナ" = "……。"
"21170-4-カリン" = "……。"
"21170-5-アカネ" = "……。"
"21170-7-ネル" = "……。"
"21170-8-ネル" = "なるほどな……。"
"21170-9-ネル" = "ゲーム開発部、か。知らねぇ部活だったが……。"
"21170-10-ネル" = "そいつらにしてやられた、ってことだな？"
"21170-11-アカネ" = "……申し訳ありません。"
"21170-12-アカネ" = "この依頼を受諾して、作戦を準備したのは私です。 "
"21170-13-アカネ" = "メイド部の名に、傷をつけてしまいました……。"
"21170-14-ネル" = "んなこたぁどうでもいい。"
"21170-15-アカネ" = "……え？"
"21170-16-ネル" = "それに、あたしがここに戻ってきた時にリオから連絡が来た。"
"21170-17-カリン" = "セミナーの……ミレニアムの生徒会長から？"
"21170-18-ネル" = "あぁ。"
"21170-19-ネル" = "依頼は撤回。無かったことに、だとよ。"
"21170-20-カリン" = "！？"
"21170-21-アカネ" = "それは、いったいなぜ……？"
"21170-22-ネル" = "あたしの知ったことかよ……けど多分、リオもヒマリも確かめてみたかったんじゃねぇのか？"
"21170-23-アカネ" = "確かめる……私たちの力を、ですか？"
"21170-24-ネル" = "逆だ。"
"21170-25-ネル" = "あの、アリスとかいう奴の方だろ。"
"21170-26-ネル" = "ま、その辺の事情は知ったこっちゃねえ。"
"21170-27-ネル" = "依頼とは関係なくなったが……"
"21170-28-ネル" = "アカネ、調べておいてくれ。"
"21170-29-アカネ" = "はい？何をですか？"
"21170-30-ネル" = "ゲーム開発部だ、関係者もまとめてな。"
"21170-31-アカネ" = "いきなり何故……リベンジ、ですか？"
"21170-32-ネル" = "その表現はなんか癪だが……まぁちっと興味があってな。"
"21170-33-ネル" = "一通り情報が洗えたら、そいつらんところに行くぞ。"
"21170-34-アカネ" = "はい、望むところです。今頃あの子たちは、メイド部に一泡吹かせたと喜んでいるはず。"
"21170-35-アカネ" = "ふふっ、次にお会いする時はどんな表情を見せてくれるのか……楽しみですね。"
"21170-38" = "ミレニアム・ゲーム開発部"
"21170-39-モモイ" = "……。"
"21170-40-ミドリ" = "……。"
"21170-41-ユズ" = "……。"
"21170-42-ユズ" = "こんなに落ち込んだのは……『テイルズ・サガ・クロニクル』のプロトタイプをアップロードした時以来……。"
"21170-46-アリス" = "あ、あの、モモイ……？"
"21170-47-モモイ" = "ふふっ、ふへへへへ、全部終わった！おしまいだぁ！！！"
"21170-50-アリス" = "み、ミドリ？その、大丈夫ですか？"
"21170-51-ミドリ" = "アリスちゃん、ごめん……今は何も話したくない気分なの……。"
"21170-54-アリス" = "えっと、ユズ――"
"21170-55-ユズ" = "怒り、破滅、腐食、絶望、虚脱……世界は今、破滅に向かって……"
"21170-57-アリス" = "あ、あの！えっと、私はあまり理解できてないのですが……"
"21170-58-アリス" = "もしかしてこの状況は、"
"21170-60-アリス" = "G.Bibleのせい、ですか？"
"21170-62-モモイ" = "……。"
"21170-63-ミドリ" = "……。"
"21170-65-アリス" = "えっと、G.Bibleは、嘘は言ってないと思いますが……。"
"21170-67-モモイ" = "そ う い う 問 題 じ ゃ な い っ ！ ！"
"21170-70-アリス" = "！？"
"21170-71-モモイ" = "いっそのこと嘘って言ってくれた方がまだマシ！"
"21170-72-モモイ" = "うああああん、終わった！私たちはもう廃部なんだ！ふえぇぇぇぇぇん！"
"21170-73-アリス" = "？？？"
"21170-75" = "ミレニアム・ゲーム開発部"
"21170-76" = "（2時間前……）"
"21170-77-マキ" = "ハ～イ、ゲーム開発部のちびっ子たち！マキちゃんからプレセントのお届けだよ！"
"21170-79-モモイ" = "遂に！"
"21170-80-マキ" = "ジャジャーン！"
"21170-82" = "G.Bible.exe……実行準備完了"
"21170-83-ミドリ" = "ようやく、G.Bibleが私たちの手に……！"
"21170-84-マキ" = "遅れてごめんねー。「鏡」をセミナーに返すことになって、その件でちょっとバタバタしちゃって。"
"21170-85-モモイ" = "ええっ、「鏡」返しちゃったの！？"
"21170-86-マキ" = "実は、ヒマリ先輩は最初から全部知ってたみたい。それくらいあげてもいいから、これからはあんまり無理しないでって。えへへっ。"
"21170-87-マキ" = "あ、それでね。G.Bibleを開いてた時にこの、＜Key＞っていうフォルダを見つけたの。"
"21170-88-モモイ" = "何これ……ケイ、って読むのかな？"
"21170-89-アリス" = "……ケイ？"
"21170-90-ミドリ" = "「キー」でしょ！お姉ちゃんは本当に高校受験合格したの！？"
"21170-93-マキ" = "実は、こっちについては何一つ分からなくって。ファイルは壊れてなさそうだけど……私たちの知ってる機械語じゃ解読できない、信じられないような構成をしてる。"
"21170-94-マキ" = "G.Bibleの方はきちんと開けたけど、こっちはちょっと見ただけじゃ何にも分からなかったの。この＜Key＞のこと、何か知ってたりする？"
"21170-95-モモイ" = "いや、私たちも全然……。"
"21170-96-ミドリ" = "……。"
"21170-97-ミドリ" = "もしかして、＜Key＞って……。"
"21170-100" = "[56cd7b]あなたはAL-1Sですか？"
"21170-103" = "ミレニアム・ゲーム開発部"
"21170-104-ミドリ" = "まさか、あの時の……？"
"21170-105-マキ" = "ふうん、何かあったの？ま、でもとりあえず今はG.Bibleの方でしょ。"
"21170-106-マキ" = "＜Key＞についてはまた今度ね。時間があったら頑張って分析してみるよ。"
"21170-107-マキ" = "じゃ、間違いなく渡したから。またね！"
"21170-109-ミドリ" = "マキちゃん、ありがとね！"
"21170-110-モモイ" = "今度会う時は、秘書を通して連絡してね！なにせ私たちは、『TSC2』で大ヒットする予定だから！"
"21170-111-マキ" = "あははっ、楽しみにしてるよ！"
"21170-113-モモイ" = "みんな、集まって！"
"21170-114-モモイ" = "あらためて……G.Bible、見よっか。"
"21170-115-モモイ" = "みんな知ってる通り、この中に何が入ってるのかについては、ほとんど誰も知らない。ただ最後にG.Bibleを見たと噂される、あるカリスマ開発者によると……"
"21170-116-モモイ" = "「ゲーム開発における秘技。みんなが知っているようで、誰も知らなかった奇跡」……って言われてる。"
"21170-117-モモイ" = "私は、それが知りたい。"
"21170-118-ミドリ" = "うん……最高のゲームを作るために。"
"21170-119-モモイ" = "そう。それが出来れば、これからもみんなでこの場所にいられる。"
"21170-120-モモイ" = "もし失敗したら……ユズは寮に戻って、会いたくもないやつらに会わなきゃいけなくなる。それに、アリスは……。"
"21170-121-ミドリ" = "……もしものことは考えたくないけど。その時はきっと先生が、シャーレが助けてくれるよ。"
"21170-124-アリス" = "シャーレ……？先生と一緒なのは、とっても嬉しいのですが……。"
"21170-125-アリス" = "アリスはもうここに……みんなと一緒には、いられないのですか？"
"21170-126-モモイ" = "……っ！"
"21170-127-モモイ" = "そんなことはない！私たちは絶対に、最高のゲームを作るんだから！"
"21170-128-モモイ" = "大丈夫、『TSC2』もアリスにとっての「神ゲー」になるよ。"
"21170-129-モモイ" = "さて、それじゃあ……。"
"21170-130-モモイ" = "始めよう、アリス！"
"21170-131-アリス" = "はい。"
"21170-132-アリス" = "G.Bible……"
"21170-133-アリス" = "起動！"
"21170-135" = "次回;G.Bible"
