[translation]
"21195-3" = "ミレニアム・旧校舎廊下"
"21195-4-モモイ" = "はぁ、はぁ……。"
"21195-5-モモイ" = "な、何とか逃げ切れた？"
"21195-6-ユズ" = "こ、これからどうする……？"
"21195-7-ミドリ" = "もうミレニアムプライスへの出品は終わってるんだし……"
"21195-8-ミドリ" = "とりあえず結果が出るまで、このまま逃げ続けよう！"
"21195-9-？？？" = "逃げ切れるとでも思ったか？"
"21195-10-ミドリ" = "！？"
"21195-12" = "（ダダダッ！）"
"21195-13-ミドリ" = "きゃぁっ！"
"21195-14-アリス" = "ミドリ！"
"21195-18-ネル" = "……。"
"21195-19-ネル" = "なるほどな。"
"21195-20-ネル" = "どうりで、いちいち良い判断だと思ったぜ。"
"21195-21-ネル" = "さっきこのチビたちを指揮したのも、ミレニアムの差押品保管所を襲撃したのも。"
"21195-22-ネル" = "あんただったか。"
"21195-23-ネル" = "先生……って呼べばいいのか？"
"21195-24-ネル" = "アカネが調査した、例の「先生」……噂は大げさじゃなかったみてぇだな……。"
"21195-25" = "[s1] \"どういう用件？リベンジ？\"\n[s2] \"チビって、身長はこっちのみんなと同じくらいじゃ……？\""
"21195-26-ネル" = "はっ！そんなくだらない理由で来るわけねぇだろうが。"
"21195-27-ネル" = "強いて言うならまずは……そこの、でこ出してるあんた。"
"21195-28-ネル" = "あの時は、よくもあたしを騙してくれたな……？"
"21195-29-ユズ" = "ひっ……！す、すみません！"
"21195-30-ネル" = "やるじゃねえか、褒めてやるぜ。"
"21195-31-ユズ" = "……え？"
"21195-32-ネル" = "怯えたふりをしてブルブル震えながら、あたしを騙すなんてな。大した演技力だ。"
"21195-33-モモイ" = "（怯えてたのは、演技じゃなかったと思うけど……多分）"
"21195-34-ネル" = "まあそれは良いとして……そっちのバカみたいにデケぇ武器持ってるあんた。"
"21195-35-ネル" = "んなこたねぇよ！あたしは3年生だぞ！？あたしの身長に言及した奴らが、最後にはどうなったか教えてやろうか！？"
"21195-36-カリン" = "……落ち着いて、リーダー。"
"21195-37-アカネ" = "なんだか最早新鮮ですね。まだネル先輩に対して、身長の話ができる人がいたなんて。"
"21195-38-ネル" = "ふぅ、ふぅ……。"
"21195-39-ネル" = "危うく冷静さを失うところだったが……まあ、こんな話はどうでも良い。おい、そこの無駄にデケぇ武器持ってるあんた。"
"21195-41-アリス" = "（キョロキョロ）"
"21195-42-ネル" = "あんただよ、あんた！"
"21195-43-アリス" = "アリスのことですか？"
"21195-44-ネル" = "そうだ、てめぇには用がある。"
"21195-45-ネル" = "C&Cに、一発食らわせてくれたらしいじゃねえか……？"
"21195-46-ネル" = "ちっと面貸せや。"
"21195-48-アリス" = "あ、アリス、このパターンは知っています。"
"21195-49-アリス" = "「私にあんなことをしたのは、あなたが初めてよ……っ」"
"21195-50-アリス" = "告白イベントですね。チビメイド様はアリスに惚れていると。スチル獲得です。"
"21195-51-ネル" = "ふ、ふっざけんなこの野郎っ！ってか、誰がチビメイド様だ！？ぶっ殺されてぇのか！？"
"21195-52-アリス" = "ひっ……！"
"21195-53-モモイ" = "こ、怖っ！！"
"21195-55-ネル" = "はぁ……。"
"21195-56-ネル" = "なかなかイラつかせてくれるじゃねぇか、まあ良い。"
"21195-57-ネル" = "誤解してるかもしれねぇから一応言っとくが、別にC&Cに一発食らわせた分の復讐ってわけじゃねぇ。"
"21195-58-ネル" = "あちこちに怪しい部分はあったが、こっちとしては正当な依頼の中での出来事だった。そっちはそっちで、あたしらを相手に目標を達成しただけだ。"
"21195-59-ネル" = "別にそこに恨みはねぇが……俄然、興味が湧いてきてな。"
"21195-60-モモイ" = "興味……？"
"21195-61-ネル" = "確認、って言った方が良いかもしれねぇが……。"
"21195-62-ネル" = "さあ、ちょっくら相手してもらおうか。"
"21195-63-ネル" = "あたしと戦って勝てたら、このまま大人しく引き下がってやる。"
"21195-64-ネル" = "お互いを理解するには、これが一番手っ取り早いからな。どうだ、難しい話じゃねえだろ？"
"21195-65-アリス" = "……。"
"21195-66-アリス" = "分かりました。"
"21195-67-ネル" = "お、やる気満々と来たか。"
"21195-68-アリス" = "一騎打ちのイベント戦闘……みたいなものですね、理解しました。"
"21195-69-ネル" = "イベ……なんつった？"
"21195-70-アリス" = "あの時は狭かったですし、「鏡」を持って帰るという使命がありましたが……"
"21195-71-アリス" = "今なら……！"
"21195-72-アリス" = "行きます、魔力充電100%……！"
"21195-74-ネル" = "ちっ、これは……！"
"21195-75-アリス" = "光よ！！"
"21195-77" = "ドカアアァァァン！！"
"21195-79-カリン" = "くっ！"
"21195-80-アスナ" = "わぉ！"
"21195-81-アカネ" = "何という威力……！"
"21195-82-アカネ" = "校舎の壁を、こうも簡単に消し飛ばすほどの……！"
"21195-85-モモイ" = "す、すごい……。"
"21195-86-ミドリ" = "こんな火力、見たことない……。"
"21195-87-アリス" = "……やったか？"
"21195-88-ミドリ" = "アリスちゃん！そのセリフは無闇に言っちゃダメ！"
"21195-89-アリス" = "あ、ネル先輩は3年生でした。言い直します。"
"21195-90-アリス" = "や、やっつけられましたか……？"
"21195-91-ミドリ" = "いや、敬語の問題じゃなくて……！"
"21195-95" = "[ns] \"まだだよ。\""
"21195-97" = "（ダダダッ！）"
"21195-98-アリス" = "うぁっ！？"
"21195-101-ネル" = "確かに、並大抵の火力じゃねぇが……。"
"21195-102-ネル" = "ただ、それだけだ。"
"21195-104-アリス" = "も、もう一度、魔力を充電……！"
"21195-106-ネル" = "遅ぇよ。"
"21195-107-アリス" = "あっ……！"
"21195-108" = "（ガッ！）"
"21195-109-アリス" = "きゃぁっ！"
"21195-111-ネル" = "てめぇの武器は確かに強い。だが引き金を引いた後、発射まで最低でもコンマ数秒はかかる。"
"21195-112-ネル" = "その上、その強すぎる火力のせいで、相手にある程度の距離まで入られたら撃てねぇ。"
"21195-113-ネル" = "爆圧に、[ruby=てめぇ]自分[/ruby]まで巻き込まれるからな。"
"21195-114-ネル" = "そしてこの間合いであたしに勝てる奴なんざ、キヴォトス全体でもそう多くは……"
"21195-115-ネル" = "……いや、一人もいねぇ。"
"21195-116-アリス" = "うぅ……。"
"21195-117-モモイ" = "アリス！"
"21195-120-ネル" = "思った以上にがっかりだったな。この程度で、あいつらがやられたとは到底……"
"21195-121-アリス" = "……。"
"21195-122-アリス" = "（ブォンッ！）"
"21195-123-ネル" = "ぐっ！"
"21195-124-ミドリ" = "銃身を、振り回した……！？"
"21195-125-ネル" = "はっ、近接戦としては悪くねぇ判断だ……けどな。"
"21195-128-ネル" = "相変わらずこの距離じゃ、あたしの方が圧倒的に有利。"
"21195-129-ネル" = "てめぇは発射しようにも、あたしに照準を合わせられねぇ。"
"21195-130-アリス" = "……照準は、必要ありません。"
"21195-131-アリス" = "行きます！"
"21195-132-ネル" = "だから無理だって……ん？"
"21195-134-ネル" = "この状況で発射準備……？おい、まさかてめぇ……！？"
"21195-135-ネル" = "あたしじゃなく……床に！？"
"21195-136-ネル" = "正気か！？そのまま撃ったらてめぇも……！"
"21195-137-アリス" = "光よ！！"
"21195-139" = "（ドカアアァァン！）"
"21195-141-ミドリ" = "アリスちゃん！うっ、煙で視界が……！"
"21195-142-モモイ" = "床がほぼ崩れて……見つけた、アリス！"
"21195-143-アリス" = "に、肉体損傷48%……後退を望みます！"
"21195-145" = "[s] \"私が背負う。\""
"21195-146-ミドリ" = "お願いします、急いで！"
"21195-147" = "（サササッ――）"
"21195-149-カリン" = "リーダー！"
"21195-150-アカネ" = "だ、大丈夫でしょうか、まさか瓦礫に巻き込まれて……。"
"21195-151-アスナ" = "さっき一瞬アリスちゃんが見えたけど、だいぶダメージ受けてたよ。今頃きっと、うちの小っちゃいリーダーもぺちゃんこに……"
"21195-153-ネル" = "……誰が小っちゃいって！？"
"21195-155-カリン" = "あっ。"
"21195-156-アスナ" = "わ～お、さすがうちのリーダー！全然ピンピンしてるじゃん！"
"21195-157-ネル" = "てめぇはいったいどっちの味方なんだよ……！"
"21195-158-カリン" = "今のアリスは戦闘力を失った状態だけど、このまま追いかける？だいぶ負傷してたし、保健室に向かってるはず。"
"21195-159-アカネ" = "はい、ミレニアムには二桁以上の保健室があるとはいえ……すぐに見つかるでしょう。"
"21195-162-ネル" = "……。"
"21195-163-ネル" = "…………。"
"21195-164-アスナ" = "リーダー？"
"21195-165-ネル" = "……ああ。"
"21195-166-ネル" = "いや、いい。追撃は無し、もう戻る。"
"21195-167-ネル" = "一通り暴れたら、すっきりしたしな。"
"21195-168-カリン" = "……。"
"21195-169-ネル" = "目的は概ね達成した。リオがゲーム開発部に興味を持つ理由も分かったし……。"
"21195-170-ネル" = "それに……"
"21195-171-アスナ" = "分かった！気になっちゃったんでしょ～、先生のこと！"
"21195-172-ネル" = "ばっ、違ぇよ！そ、そういうんじゃなくてだな……！"
"21195-173-アカネ" = "ふふ、お気持ちは分かります。でも、少々心配ですね。"
"21195-174-アカネ" = "あの子たちの体躯を見るに、先生の好みはおそらく……。"
"21195-175-カリン" = "少なくともリーダーにとっては、悪い情報じゃない。"
"21195-176-ネル" = "うるせぇ！いつまでもそういうこと言ってっとぶっ飛ばすぞ！？"
"21195-177-ネル" = "はぁ……。"
"21195-180-ネル" = "先生、それにゲーム開発部か……。"
"21195-184-ネル" = "はっ。"
"21195-185-ネル" = "楽しみにしてろよ。あたしをチビ扱いした償い、絶対にさせてやっからな。"
"21195-187-ネル" = "……思いっきり暴れたら腹減ったな。なぁ、ラーメンでも食いに行こうぜ。"
"21195-189-アカネ" = "良いですねー。"
"21195-190-アスナ" = "賛成賛成～！"
"21195-191-カリン" = "……そういえばリーダーは成長期だった。"
"21195-194-ネル" = "いい加減にしろやぁっ！！"
"21195-196" = "次回;ミレニアムプライス"
