[translation]
"10044060-1" = "第6話;死のファンミーティング"
"10044060-3-ノゾミ" = "この調子ならなんとか帳尻は合いそうかな。"
"10044060-4-ノゾミ" = "ざっくり計算だけど。"
"10044060-5-ヒカリ" = "ギリギリー。"
"10044060-7" = "[ns] \"無傷で列車に追いつけて良かったね。\""
"10044060-8-ノゾミ" = "これで後はかっ飛ばすだけ！"
"10044060-9-ノゾミ" = "……のはずだけど、なーんか忘れてる気がするんだよね。"
"10044060-14-暴走族" = "おい！あの列車だぞ！！"
"10044060-15-暴走族" = "ひゃっふー！走れ走れー！"
"10044060-16-ノゾミ" = "あー……。"
"10044060-19-暴走族ボス" = "見つけたぞ――ハイランダーのガキども！"
"10044060-20-暴走族A" = "計画通りだね、総長！"
"10044060-21-暴走族ボス" = "積荷を取り返して、今度こそうちらが配達する――"
"10044060-22-暴走族ボス" = "我ながら天才的な計画だぜ！"
"10044060-23-暴走族ボス" = "これでキヴォトス中に名を売れるはずだ！！"
"10044060-24-暴走族B" = "この業界は結果がすべてだからな！"
"10044060-26-暴走族ボス" = "我らキヴォトス・トランスポーター連盟……略して、ブロロロ疾走連合の出番だぜ！！"
"10044060-30-暴走族A" = "……ん？"
"10044060-31-暴走族ボス" = "どうした？"
"10044060-32-暴走族A" = "あ、あのヘリは！？"
"10044060-40-シノン" = "特ダネとあらば、どこにでも駆けつける！#nクロノス報道部の[ruby=かわる]川流[/ruby]シノンです！"
"10044060-41-シノン" = "続報です！今、話題の貨物列車をカメラが捉えました！#nその積荷は、キヴォトスの運命を左右するほどのモノなのだとか……！"
"10044060-42-シノン" = "すでに暴走族が集まっているようです！#nどこからニオイを嗅ぎつけてきたのでしょうか！"
"10044060-43-シノン" = "果たして、あの中には何があるのか！列車はどこに向かうのか！"
"10044060-44-シノン" = "引き続き、チャンネルはそのままで！#nクロノスチャンネルはキヴォトスの皆様に、いちはやく真実をお伝えしていきます！"
"10044060-51-アオバ" = "あ、あんな報道……私たちに恨みでもあるんでしょうか……。"
"10044060-52-ノゾミ" = "クロノスは野次馬根性だろうけど……暴走族の方はどうしてついてくるわけ？"
"10044060-53-ヒカリ" = "ピザの恨みー？"
"10044060-55-アオバ" = "わけが分からないんですけど……この件とクロノスって関係ないですよね！？"
"10044060-56-アオバ" = "こ、こんなことになってるの、半分くらいあの人たちのせいなんですけど……！"
"10044060-57-アオバ" = "い、いっそ撃ち落としてしまえば静かになるはず……。"
"10044060-58" = "[ns] \"あ、アオバ、落ち着いて！\""
"10044060-59-ノゾミ" = "起きたことはもうしょうがないじゃん？"
"10044060-60-ノゾミ" = "これからを考えないと。"
"10044060-61-アオバ" = "そ、それはそう、ですけど……。"
"10044060-62-ノゾミ" = "まっ、ノープランなんだけどね！パヒャッ！"
"10044060-63-アオバ" = "い、いい話だと思ったのに……。"
"10044060-67-ヒカリ" = "土煙ーもくもくー。"
"10044060-68-ヒカリ" = "……。"
"10044060-69-ヒカリ" = "なんか、くるー。"
"10044060-70" = "[ns] \"えっ……。\""
"10044060-72" = "[ns] \"何かがものすごいスピードで追ってくるような……？\""
"10044060-75-チンピラ" = "キャハハッ！見つけたぜ！"
"10044060-76-ヘルメット団" = "あの列車はうちらのもんだ！#nおらっ、退いた退いたーっ！！"
"10044060-81-暴走族A" = "そ、総長！なんか変なやつらまできてるけど！？"
"10044060-82-暴走族ボス" = "なっ、誰だあいつら！？まさかクロノスのニュースにつられて……？"
"10044060-83-暴走族ボス" = "くそっ！あの積荷はうちらのだぞ！"
"10044060-85-アオバ" = "にゅ、ニュースのせいで追手が増えてしまいました……！！"
"10044060-86-ノゾミ" = "バイクに、装甲車……うわぁ、戦車までいるよ？"
"10044060-87-ヒカリ" = "ちょー人気ー、死のファンミーティングー。"
"10044060-88-ノゾミ" = "相手してたら日が暮れちゃうし、このまま振り切るよ！"
"10044060-89-アオバ" = "た、ただの貨物輸送だって聞いてたのに……。"
"10044060-95-ノゾミ" = "いやぁ～、どうしよっか、これ。"
"10044060-96-ヒカリ" = "大ピンチー。"
"10044060-100-？？？" = "ワハハッ！その積荷はうちらのもんだ！"
"10044060-101-？？？" = "ひとつ残らず置いてきなぁ！！"
"10044060-106-アオバ" = "ど、どうしてこうなってしまうんですかぁっ！！"
"10044060-112-シノン" = "チャンネルをご覧の皆さん！"
"10044060-113-シノン" = "状況は混迷を極めています！走る列車！追う群衆！"
"10044060-114-シノン" = "果たして、あの列車の行方は――！#n最後まで、まばたき禁止ですよ！！"
"10044060-116-シノン" = "あれ？何か飛んできて……？"
"10044060-117-マイ" = "……ロケット砲じゃない？"
"10044060-118-シノン" = "はっ！皆さん大変です！今、ロケット砲がヘリに向かって――"
"10044060-122-シノン" = "このヘリ！？！？"
"10044060-125-シノン" = "ぎゃぁぁああああーっ！！"
"10044060-126-マイ" = "げ、言論弾圧だぁぁぁっ～！！"
"10044060-128-ノゾミ" = "パヒャヒャッ！いいねいいね！#n大胆なことするヤツもいるじゃん！"
"10044060-129-ヒカリ" = "撃ったのアオバー？"
"10044060-131-アオバ" = "ち、違います……！#n一瞬考えはしましたが撃ってません！！"
"10044060-132-アオバ" = "と、というか……向こうに撃ってるヤツいるんですけど！！あっち！！"
"10044060-134-ブラックマーケット幹部" = "クロノスにはご退場願おうか！"
"10044060-135-ブラックマーケット幹部" = "これ以上雑魚が群がるのは手間だからな！"
"10044060-139-チンピラ" = "キレイな花火だったぜ！やるじゃんか！"
"10044060-146-チンピラ" = "ぎゃふっ！"
"10044060-148-ブラックマーケット幹部" = "ふんっ！道を開けろ！あの列車は我々のものだ！！"
"10044060-154-暴走族A" = "総長、どうする！？仲間がどんどんやられてる！！"
"10044060-155-暴走族ボス" = "くそっ！うちらは配達業者なんだぞ！？"
"10044060-159-ノゾミ" = "おっ、あれはいい判断だね。先にライバルを倒すのは得点高いよ。"
"10044060-160-ヒカリ" = "優勝候補ー、ナンバーワンー。"
"10044060-161-アオバ" = "な、なに悠長なこと言ってるんですかぁ！！#n狙われてるのはこの列車なんですけど！！"
"10044060-162-ヒカリ" = "忘れてないよー？"
"10044060-163-アオバ" = "な、なんか……どんどん距離が詰まってませんか……？"
"10044060-164-アオバ" = "それにこの路線――ゲヘナの自治区を通過しますよね！？"
"10044060-165-アオバ" = "げ、ゲヘナの生徒まで加勢してきたら……#nも、もう輸送は諦めて脱出しませんか……？"
"10044060-166-ノゾミ" = "なに言ってんのさ。任務はやりきるよ。"
"10044060-167-アオバ" = "だ、だって……このままだと任務どころじゃ……！"
"10044060-168" = "[ns1] \"とりあえず落ち着いて考えてみよう。\"\n[ns2] \"打開策はあるはずだから。\""
"10044060-171-アオバ" = "うぅ……ほ、本当にそうなんでしょうか……。"
"10044060-172-アオバ" = "つ、積荷を全部奪われて、列車は破壊されて……#nさ、最後はその責任を問われて、どうせ全員で懲戒処分を受けるんです……。"
"10044060-173-ノゾミ" = "パヒャヒャッ！いい想像力じゃん！"
"10044060-174-アオバ" = "わ、笑ってる場合ですか！？"
"10044060-175-ヒカリ" = "うわーん、しくしくー。"
"10044060-176-アオバ" = "な、泣いたフリならもっと真剣にやって欲しいんですけど！"
"10044060-177-ヒカリ" = "うわーん、ばれたー。"
"10044060-179" = "[ns] \"あれ？なんか向こうの様子が……。\""
"10044060-183-ヒカリ" = "おー、ニューチャレンジャー。"
