[translation]
"10044040-1" = "第4話;何を載せて走るのか"
"10044040-2-ノゾミ" = "遅かった……。"
"10044040-3-ヒカリ" = "ここにもないー。"
"10044040-5-アオバ" = "バスにまで乗ったのに……。"
"10044040-6" = "[ns] \"ところで……。\""
"10044040-8" = "[ns] \"その列車は何を積んでるの？\""
"10044040-13-ノゾミ" = "あれ、言ってなかったっけ？"
"10044040-14-ヒカリ" = "先生にはまだー。"
"10044040-15-ノゾミ" = "そっか、そういやそうだね。"
"10044040-17-アオバ" = "い、今まで何も聞かずに手伝ってくれていたんですか……。"
"10044040-18" = "[s1] \"急ぎだって言われたから……。\"\n[s2] \"生徒の要望に応えるのが先生だからね。\""
"10044040-21-アオバ" = "ふ、不思議な人ですね……。"
"10044040-22-ノゾミ" = "パヒャヒャッ、やるじゃん先生。"
"10044040-23-ノゾミ" = "じゃあ発表しちゃおっかな！#n積荷の中身は――！"
"10044040-28-ノゾミ" = "分かんない！"
"10044040-29" = "[s] \"……え？\""
"10044040-31-ノゾミ" = "別に中身に興味ないし。"
"10044040-32-ヒカリ" = "時間通りー決まった場所に運ぶだけー。"
"10044040-33-ノゾミ" = "そ！だから知る必要もないの。"
"10044040-34" = "[s] \"た、たしかに！？\""
"10044040-36-アオバ" = "な、納得しないでください……！"
"10044040-37-アオバ" = "つ、積荷の中身くらい把握してるのが当たり前なんですけど……！"
"10044040-38-ノゾミ" = "えー、なんだっけな……教えてもらったような気はするんだけど……。"
"10044040-39-ヒカリ" = "右からー左にー聞き流しー。"
"10044040-40-アオバ" = "えぇ……本当に、なんで幹部やってられてるんですか！？"
"10044040-41-ノゾミ" = "だ～か～ら～！そんなのどうでもいいんだって！"
"10044040-42-ヒカリ" = "やることは同じだよー？"
"10044040-43-アオバ" = "じゃ、じゃあ……お二人は言われた仕事をこなすだけで満足なんですか……？"
"10044040-44-ヒカリ" = "なにか問題ー？"
"10044040-45-アオバ" = "も、問題……って言うほどじゃないんですけど……。"
"10044040-46-アオバ" = "そ、その……自分のことは、自分で決めたいじゃないですか。"
"10044040-47-ノゾミ" = "うーん、どうだろ。その気持ちも分かるけどさ。"
"10044040-48-ノゾミ" = "でも、アオバだって同じじゃん？"
"10044040-49-アオバ" = "うっ……。"
"10044040-50-ノゾミ" = "やりたくてやってるようにはあんま見えないんだよね。"
"10044040-51-アオバ" = "そ、そういうとこばっかり鋭いんですから……。"
"10044040-52-アオバ" = "ええ、その通りですよ！で、でも……！#nじ、自分のことくらい自分で決めたいじゃないですか……！"
"10044040-53-アオバ" = "こ、こんなこと言うつもりじゃなかったんですけど……と、とにかく！"
"10044040-54-アオバ" = "わ、私は……下っ端の整備士ですから。#n自分の人生を自分で決めるのは、ただの夢物語かもしれませんけど……！"
"10044040-55-アオバ" = "お、お二人は幹部……ですし。人の上に立つ存在なんでしょう！？"
"10044040-57-ヒカリ" = "上にもーもっと上はいるよー。"
"10044040-58-ノゾミ" = "そーそー。私らは、ただの中間管理職。"
"10044040-60-アオバ" = "そ、そんな……。"
"10044040-61-ノゾミ" = "まー、ぶっちゃけこの仕事も最初は退屈だと思ってたけどさ。"
"10044040-62-ノゾミ" = "何もやらなかったら、もっとつまんないじゃん？"
"10044040-63-アオバ" = "か、幹部でも同じ……？#nえ、じゃあ私は、何を目指せば……。"
"10044040-64-ヒカリ" = "テキトー、楽しければーおっけー。"
"10044040-65" = "[ns3] \"ちょっと話はそれちゃったけど……。\"\n[ns4] \"貨物の中身は知らないってことだね。\""
"10044040-68-ヒカリ" = "すごく大事なものだったと思うよー？"
"10044040-69-ヒカリ" = "中見てみるー？"
"10044040-70-アオバ" = "ぜ、絶対ダメなんですけど……。"
"10044040-71-ノゾミ" = "中身は知ってて当然なんでしょ？"
"10044040-72-アオバ" = "それとこれとは別で……か、勝手に開けるとか論外なんですけど……。"
"10044040-73-ノゾミ" = "パヒャヒャッ！バレなきゃいいの！へーきへーき！"
"10044040-74-ノゾミ" = "先生も気になるでしょー？"
"10044040-75-ノゾミ" = "え、ダメ……？つまんないのー。"
"10044040-76-アオバ" = "うぅ……もう帰りたい……。"
"10044040-84-ノゾミ" = "ヒカリ、どしたの？"
"10044040-85-ヒカリ" = "列車見つけたー今は隣の駅ー。"
"10044040-86-ノゾミ" = "え、ほんと？どうやって？"
"10044040-87-ヒカリ" = "てってれー、通信機ー。"
"10044040-88-ノゾミ" = "パヒャヒャッ！さすがヒカリ！"
"10044040-89-アオバ" = "そ、その手があったんですね……。"
"10044040-90-アオバ" = "で、でもまた発車してしまったら……。"
"10044040-91-ノゾミ" = "そうさせなきゃいいだけっしょ！ヒカリ、ちょっと貸して！"
"10044040-96-ノゾミ" = "あーあー、聞こえてる？"
"10044040-97-駅員" = "は、はい……。"
"10044040-98-ノゾミ" = "CCC[ruby=たちばな]の橘ノ[/ruby]ゾミだよ～。#nねぇねぇ、そっちに貨物列車が一本来てるよね？"
"10044040-99-ノゾミ" = "それ、ちょっと止めといてもらえる？すぐ行くからさ。"
"10044040-100-ノゾミ" = "なんかシステムエラーで勝手に発車しがちだから、ちゃんと見といてね！"
"10044040-101-駅員" = "その……当駅では、大型貨物列車を長く停車させるのは無理でして……。"
"10044040-102-駅員" = "旅客列車の運行もありますし……。"
"10044040-103-ノゾミ" = "とりあえず停車させといて！方法は任せるから！#nでないと大事件になっちゃうんだよね。"
"10044040-104-駅員" = "え？どういうことです？#nそれより……いま、クロ――"
"10044040-105-ヒカリ" = "ちょーじゅーよー。"
"10044040-106-駅員" = "はい？"
"10044040-107-ノゾミ" = "その列車には、すっっっごく大事なモノが積まれてるから――"
"10044040-108-ノゾミ" = "何があっても知られちゃいけないんだよね。"
"10044040-111-駅員" = "……。"
"10044040-112-ノゾミ" = "おーい、聞いてる？もしもーし？"
"10044040-113-アオバ" = "あ、あの……ウソみたいですけど、本当のことなので……。"
"10044040-114-駅員" = "あ……いえ、その……。"
"10044040-120-駅員" = "いま……クロノスチャンネルの取材中、でして――"
"10044040-124-マイ" = "特ダネだ！！！"
"10044040-125-シノン" = "皆さん！聞きましたか！？"
"10044040-131-シノン" = "今ここにある貨物列車に、とても大事な何かが積まれているとのことです！！"
"10044040-132-シノン" = "キヴォトスの運命を左右するほどのモノでしょうか！？"
"10044040-133-シノン" = "果たしてその正体は！？"
"10044040-134-シノン" = "クロノスが最後までお届けします！！！！"
"10044040-137" = "[ns] \"……。\""
"10044040-139-アオバ" = "あっ……えっ……。"
"10044040-143-ノゾミ" = "はは、終わったかも。"
