[translation]
"10044055-2-暴走族A" = "ば、バカな……！"
"10044055-3-暴走族B" = "こんなガキどもに負けるなんて……。"
"10044055-4-暴走族B" = "ま……まだだ！もうじき、うちらの総長が――"
"10044055-13-ノゾミ" = "パヒャヒャッ！いい指揮だったよ、先生！"
"10044055-14-アオバ" = "こ、これが先生……すごい……。"
"10044055-15-アオバ" = "でも、どうしてこの人たちは追いかけて来たんでしょうか……。"
"10044055-16-アオバ" = "ま、まさか本当にピザの恨みだけでここまで……？"
"10044055-17-ヒカリ" = "起こせば聞けるよー？"
"10044055-18-ノゾミ" = "そこまでしなくてもいいんじゃない？私らも暇じゃないし。"
"10044055-19-アオバ" = "うぅ……な、何か大変なことを見落としてる気がするんですけど……。"
"10044055-21-駅員" = "大変です！所属不明の集団が多数接近中とのこと！"
"10044055-22-駅員" = "早く出発を！線路は空けてあります！"
"10044055-23-ノゾミ" = "時間もあんまないし。出るよ！"
"10044055-24-ヒカリ" = "発車オーライー。"
"10044055-25-アオバ" = "せ、整備はなんとかしますので……。"
