[translation]
"61040-1" = "第4話;誰がための学び"
"61040-2" = "[ns]\"よし……他の準備はなんとかなったかな。\""
"61040-5-？？？" = "おかけになった番号は、現在使われておりません。#nピーッという発信音の後にご用件をどうぞ♪"
"61040-6" = "[s]\"冗談のレパートリーが増えたみたいだね。\""
"61040-7-アツコ" = "ふふっ。バレちゃった。"
"61040-8-アツコ" = "でも、知らない番号からかかってきた時には、今みたいに返すのが「正解」なこともあるんだよ。"
"61040-9-アツコ" = "もちろん、先生の番号は登録してるんだけどね。"
"61040-10-アツコ" = "それじゃあ、改めて。こんにちは、先生。"
"61040-11" = "[s]\"こんにちは。やっぱり、挨拶は大事だよね。\""
"61040-12-アツコ" = "うん、覚えててくれて嬉しい。"
"61040-13-アツコ" = "変わりなかったかって？うーん……ひとまずは？"
"61040-14-アツコ" = "相変わらず、周りの目に気をつけないといけないけど……。"
"61040-15-アツコ" = "でも、それなりに楽しいよ。#n余裕ができた時は、こっそり遊びに行ったりしてるんだ。"
"61040-16-アツコ" = "だから、うん。私たちは大丈夫。"
"61040-17-アツコ" = "それで、どうしたの？"
"61040-18" = "[s1]\"いきなり変なこと聞くんだけど……。\"\n[s2]\"試験って、どう思う？\""
"61040-21-アツコ" = "試験……？"
"61040-22-アツコ" = "ふふ。「先生」らしい質問だね。"
"61040-23-アツコ" = "いいの、謝らないで。#n皮肉とかじゃないよ。"
"61040-24-アツコ" = "試験……えっと、学んだことを評価されるもの、だよね？"
"61040-25-アツコ" = "概念としてなら知ってるけど……どうして急に？"
"61040-26" = "[s3]\"実は、もう一個聞きたいことがあって……。\"\n[s4]\"もし試験を受けられるとしたら、どうしたい？\""
"61040-29-アツコ" = "うーん……。"
"61040-30-アツコ" = "例えば、「子どもはどうやってできるのか」について、確認する試験とか？"
"61040-31-アツコ" = "そういうのなら、面白そう。"
"61040-32" = "[s]\"そういうのじゃないよ！\""
"61040-33-アツコ" = "ふふ、ごめんなさい。"
"61040-34-アツコ" = "試験を受けられるとしたら、か。#n正直……よく分からないかな。"
"61040-35-アツコ" = "考えたことも、経験したこともないから。"
"61040-36-アツコ" = "でも、まるで「普通の生徒」みたいに……。"
"61040-37-アツコ" = "何かを学んで、それをちゃんと勉強したって認めてもらえるなら……。"
"61040-38-アツコ" = "……うん。"
"61040-39-アツコ" = "私はちょっと楽しみかも。他のみんなは、聞いてみないと分からないけどね。"
"61040-40-アツコ" = "……結果が悪かったら補習になるの？"
"61040-41-アツコ" = "ふふっ。そしたら、先生が補習授業をしてくれるのかな？#nそれも含めて、悪くないと思うよ。"
"61040-42-アツコ" = "それで……急にどうしたの？"
"61040-43" = "[s]\"トリニティで、アリウスからの編入生に会ったんだ。\""
"61040-44-アツコ" = "それって……。"
"61040-48-アツコ" = "……そっか、なるほどね。"
"61040-49" = "[s]\"アツコたちのことを心配してたよ。\""
"61040-54-アツコ" = "そうだったんだ。"
"61040-55-アツコ" = "うーん……。"
"61040-56-アツコ" = "ねぇ、先生？"
"61040-57-アツコ" = "こういう話は、電話越しじゃないほうがいいと思わない？"
"61040-58" = "[s5]\"たしかに、それはそうだね。\"\n[s6]\"誰かに盗聴されるかもしれないし。\""
"61040-61-アツコ" = "うーん。"
"61040-62-アツコ" = "私は「リスク」について話してるわけじゃないんだけどな。"
"61040-63" = "[s]\"……じゃあ、どういう意味？\""
"61040-64-アツコ" = "もっと単純な話。"
"61040-65-アツコ" = "こういう大事なことは――"
"61040-66-アツコ" = "先生の顔を見ながら話したいんだ。"
"61040-67-アツコ" = "……できれば、みんなと一緒にね。"
"61040-68" = "[s7]\"……そうだね。それじゃあ、落ち合う場所はまた連絡するね。\"\n[s8]\"私を含めて4人かな？\""
"61040-71-アツコ" = "ううん。5人だよ。"
"61040-72" = "[s]\"5人……？\""
"61040-76" = "[ns9]\"そっか……分かった。\"\n[ns10]\"連絡先は分かる？\""
"61040-79-アツコ" = "うん。でも、今回は私からじゃないほうがいいかも。#n余計な心配をかけちゃうから。"
"61040-80-アツコ" = "サッちゃん、連絡が取れないわけじゃないんだ。#nふふっ、たまに会ったりもしてるんだよ？"
"61040-81-アツコ" = "それに……自分探しは終わりそうなんじゃないかなって気もするんだ。"
"61040-82" = "[s]\"ちゃんと連絡をとってるんだね。\""
"61040-83-アツコ" = "ふふっ。"
"61040-84-アツコ" = "でもね、サッちゃんの話をするとミサキがすごく難しい顔をするんだよ。"
"61040-85-アツコ" = "一番サッちゃんの話をしてるのも、ミサキなんだけどね。"
"61040-86-アツコ" = "だから、やっぱり……。"
"61040-87-アツコ" = "大事な話をするときは[ruby=みんな]アリウススクワッド[/ruby]一緒に、が良いんだ。"
"61040-88" = "[s]\"アツコ。\""
"61040-89-アツコ" = "うん？"
"61040-90" = "[s]\"頼り方が上手になったね。\""
"61040-91-アツコ" = "それは……褒められてるのかな……？"
"61040-92-アツコ" = "人を頼るのは悪いことじゃない、か。そうだね……。"
"61040-93-アツコ" = "ふふ、ありがとう、先生。"
"61040-94-アツコ" = "そう言ってもらえて嬉しいけど、ほどほどにするね。"
"61040-95-アツコ" = "自分で何もしようとしない人は、嫌われるものだから。"
"61040-96-アツコ" = "でも……今回だけ、サッちゃんの件お願いしてもいい？"
"61040-97" = "[s]\"もちろん。任せておいて。\"  "
"61040-98-アツコ" = "ふふっ、先生はいつも変わらないね。"
"61040-99-アツコ" = "……ありがとう、先生。"
"61040-100-アツコ" = "先生がいてくれて、本当に良かった。"
"61040-106-ヒヨリ" = "えっ……えぇ？"
"61040-107-ミサキ" = "何、これ……。"
"61040-108-アツコ" = "ものすごく大きい……船？"
"61040-110" = "[ns]\"……そう、だね？\""
"61040-111-ミサキ" = "なんで先生までそんな反応なの！？"
"61040-112-ヒヨリ" = "あっ！わ、私、雑誌で見たことあります！#nこれってクルーズ船……ですよね？"
"61040-113-アツコ" = "クルーズ船？"
"61040-114-ヒヨリ" = "えっと……そ、その……。"
"61040-115-ヒヨリ" = "観光のためだけに作られた、すっごく豪華な船で……。"
"61040-116-ヒヨリ" = "中にはレストランとか、遊園地みたいなのとか、温泉や、プールまであって……。"
"61040-117-ヒヨリ" = "と、とにかく何でもできちゃう夢の船らしくて……。"
"61040-118-ヒヨリ" = "だから……チケット代だけでも、びっくりするくらい高いって……#n言われてるのに……。"
"61040-122-ミサキ" = "船の中にプールがあるの？#n水の上に水があるって……変なこと考える人もいるんだね。"
"61040-123-ミサキ" = "って、いや、そんなことより。"
"61040-124-ミサキ" = "先生、早く説明して。"
"61040-125" = "[s]\"スポンサーが手配してくれたから、私もよく知らないんだ。\""
"61040-129" = "[ns]\"私も、案内された場所に来ただけなんだよね。\""
"61040-130-ヒヨリ" = "す、スポンサー……！？"
"61040-131-ヒヨリ" = "私……知ってます。#nスポンサーは悪い人だって……雑誌で見ました……。"
"61040-135-ヒヨリ" = "わ、私たち……これからデスゲームをさせられるんですね……#nそうなんですよね！？"
"61040-136-ヒヨリ" = "最後の一人になるまで戦わされて……お金持ちたちがそれを見て楽しむんです……。"
"61040-137-ヒヨリ" = "仲間同士で戦うなんて……もうダメです……#nおしまいです……うわあぁぁぁあん！"
"61040-138-ミサキ" = "それ、本当なの？"
"61040-139-アツコ" = "少し落ち着いて。先生がそんなことするはずないよ。#nそれに、もしもそんなことになったら、最初に脱落するのは先生だと思うよ？"
"61040-140-？？？" = "なんだと……？そういうことだったのか！？"
"61040-147-サオリ" = "……！？"
"61040-149-ミサキ" = "……！？"
"61040-150-ヒヨリ" = "サ、サオリ姉さん！？"
"61040-152-アツコ" = "……。"
"61040-153-アツコ" = "ふふっ。"
"61040-154-ミサキ" = "まさか、スポンサーってリーダーだったの！？"
"61040-155-サオリ" = "スポンサー？なんのことだ。#n私もただ――"
"61040-156-ミサキ" = "いや、よく考えたらありえないか。"
"61040-157-ミサキ" = "……リーダーにそんなお金あるわけないし。"
"61040-158-サオリ" = "間違いではないが……#nそう言われると辛いな……。"
"61040-159-ミサキ" = "それはそれとして、戻ってきたならリーダーは返上するから。"
"61040-160-サオリ" = "待ってくれ、私もまだ状況が――"
"61040-162-ヒヨリ" = "うわぁぁん～！サオリ姉さん～！#n私たち、最後の時まで一緒がいいです〜！"
"61040-164-アツコ" = "――ところで、先生。#n私たちに話があるんだよね？"
"61040-165-アツコ" = "私も簡単にしか聞いてないし、内容を教えてほしいな。"
"61040-166" = "[s]\"話せば長くなるんだけど――\""
"61040-168-サオリ" = "そうか……「試験」か。"
"61040-169-ミサキ" = "……。"
"61040-170-ミサキ" = "それで、先生は私たちに何をさせたいの？"
"61040-171-ミサキ" = "……いや、意見を尊重するとか、そういう曖昧な話じゃなくて。"
"61040-172-ミサキ" = "素直に話し合うのが一番手っ取り早いでしょ。"
"61040-173" = "[ns]\"そうだね。それなら……。\""
"61040-175" = "[ns]\"みんなにも、「試験」を経験してほしいと思ってるよ。\""
"61040-178-アツコ" = "……。"
"61040-179-サオリ" = "……。"
"61040-181-ヒヨリ" = "え、えぇ……？#nな、なんでみんな……何も言わないんですか……？"
"61040-182-サオリ" = "何から聞くべきか考えていたんだ。そうだな……まずは――"
"61040-183-サオリ" = "どうして「試験」の話をするのか。#nその理由を教えてほしい。"
"61040-184-ミサキ" = "は？「学園生活」を経験してほしいから……って、どういうこと？#n私たちが学園生活をするの？"
"61040-185-ミサキ" = "私たちだけじゃなくて……アリウスに残った子たちにも……？"
"61040-186-サオリ" = "先生、それはどういう意味だ……？"
"61040-188" = "（トリニティに編入した子から聞いた話を伝えた）"
"61040-190-サオリ" = "……。"
"61040-191-サオリ" = "編入した生徒も、きっと楽しいばかりではなかったのだろう。"
"61040-192-サオリ" = "どんなに周りが優しくしてくれても、それに追いつかない自分がいるはずだ。"
"61040-193-サオリ" = "無意識に他者を恐れたり、世間のやり方に馴染めなかったり。"
"61040-194" = "[s11]\"……たしかに、そういう雰囲気は感じたかな。\"\n[s12]\"よく分かってるんだね。\""
"61040-197-サオリ" = "……他人事ではないからな。"
"61040-198-アツコ" = "先生、ちょっといい？"
"61040-199-アツコ" = "「生徒の本分は学業」って、よく聞くけど……。"
"61040-200-アツコ" = "そもそも、どうして勉強しなきゃいけないの？"
"61040-201-ミサキ" = "……内容が違うだけで、アリウスにも「勉強」とか「試験」はあった。"
"61040-202-ミサキ" = "どうすればもっと上手にヘイローを壊せるか、とか……。"
"61040-203-ミサキ" = "感情をコントロールして殺意を抱けるか、とかだったけど。"
"61040-204-ヒヨリ" = "ひ、ひいぃ……。"
"61040-205-ヒヨリ" = "も、もう、そういうのは……嫌です……。"
"61040-206-アツコ" = "うん、分かるよ。みんな、同じ気持ちだよ。"
"61040-207-アツコ" = "……教えて、先生。#nどうして勉強しないといけないの？"
"61040-208-アツコ" = "試験でいい成績を取ったら、どうなるの？"
"61040-209-アツコ" = "勉強ができたら、もっと稼げるようになって安定した生活を送れるようになるの？"
"61040-210-アツコ" = "でも、少なくとも私たちにとって、それは正解にはならないと思うんだ。"
"61040-211-アツコ" = "……知ってる？"
"61040-212-アツコ" = "お金を稼ぐだけなら……アリウスで教わったことも、活かし方があるんだよ。"
"61040-213" = "[s]\"それは……どうやって？\""
"61040-215-ヒヨリ" = "え、えっと……その……。"
"61040-216-ヒヨリ" = "だ、誰かを[ruby=・   ・   ・]消して[/ruby]ほしいって依頼……とか……。"
"61040-217-ヒヨリ" = "ど、どこで知ったのかは分かりませんけど……。#n私たちのところにも……たまに、届いたりして……。"
"61040-218-ヒヨリ" = "も、もちろん！全部断ってますよ？"
"61040-219-ミサキ" = "「ヘイローを破壊する」って、私たちにとっては抽象的な表現なんだよね。"
"61040-220-ミサキ" = "だから、アリウスではあまり使わなかった。"
"61040-221-ミサキ" = "使うとすれば……「外」で話をするとき。"
"61040-222-ミサキ" = "「外」の人たちと話すとき。"
"61040-223-ミサキ" = "あとは……私たちの間で誰かをからかうとき、ぐらいかな。"
"61040-225-アツコ" = "……そうだね。"
"61040-226-アツコ" = "アリウスだと、もっと単純な言葉で表現してたの。"
"61040-230-アツコ" = "――「消す」って。"
"61040-231-アツコ" = "「外」でも結構使う言葉なんだ、ってアリウスを出てから知ったんだけど……。"
"61040-232-アツコ" = "でも……使い方は、ちょっと違ってた。"
"61040-233-ヒヨリ" = "そ、そうです……。#n「外」の人たちは……冗談で使うんですよね……。だって、本当に消すことなんて……ないですから。"
"61040-234-ミサキ" = "だけど私たちは、言葉通りの意味で使ってた。"
"61040-235-アツコ" = "……かつてのアリウスは、キヴォトスの中で一番「死」に近い場所だったんだと思う。"
"61040-236-アツコ" = "少し話がそれちゃったけど……#nだから、私たちはお金を稼ぐだけならどうとでもなるんだよ。"
"61040-237-アツコ" = "だから……先生。教えて。"
"61040-238-アツコ" = "どうして、勉強しないといけないの？"
"61040-240" = "[ns]\"それはね。\""
"61040-243" = "[ns]\"世界と戦う方法を知るためだよ。\""
"61040-245-ヒヨリ" = "……は、はい？"
"61040-246-アツコ" = "……それは、考えたことなかったかも。"
"61040-247-アツコ" = "詳しく教えてくれる？"
"61040-248" = "[s13]\"勉強は、自分の知らないことを知っていく行為なんだ。\"\n[s14]\"知らないことには、「世界そのもの」だって含まれる。\""
"61040-254-サオリ" = "それは例えば……契約書という概念を知らなければ、#nいいように利用される可能性が高くなる、ということか？"
"61040-255-サオリ" = "逆に、契約書について勉強していればリスクを最小限にできる……。"
"61040-256-サオリ" = "……なるほど。たしかにそれならば理解できる。"
"61040-257-サオリ" = "これが「勉強を通して、世界と戦う方法を知る」ということか。"
"61040-258-ミサキ" = "世界はどんな風に作られて、どうやって成り立ってるのか。"
"61040-259-ミサキ" = "自分と違う考えを持つ人がいることを知って、何が違うのかを知って。"
"61040-260-ミサキ" = "その上で、ある程度理解し合って、着地点を見つけられるようになる……#nそんな感じ？"
"61040-261-サオリ" = "「世界を知る」ほど、降りかかる危険を回避できるようになる……と。"
"61040-262-サオリ" = "つまり、知識という名の自己防衛手段、ということだな。"
"61040-263-ミサキ" = "それなら……少しは納得できる、かも。"
"61040-264-ミサキ" = "少し、だけど……。"
"61040-265-ミサキ" = "……はあ。"
"61040-267-ヒヨリ" = "そ、そうですよね……世界は、辛く苦しいことばかりですし……。"
"61040-268-ヒヨリ" = "アリウスに残ってる子たちも……#n戦う方法を知る、というのは必要なんだと思います……。"
"61040-269" = "[ns15]\"よかった。分かってくれると思ってたから……。\"\n[ns16]\"実はもう一人、連れてきてるんだ。\""
"61040-272-ミサキ" = "え？"
"61040-273-サオリ" = "待ってくれ……もしかしてその生徒が、今回のスポンサーなのか？"
"61040-277-アツコ" = "そういうことだったんだ。納得。"
"61040-278-ヒヨリ" = "え、ええと……ど、どういうことですか……？"
"61040-279-ミサキ" = "そういうのは、先に一言あってもよかったんじゃ……。"
"61040-280-ミサキ" = "いや、もういいや。はぁ……。"
"61040-281-ミサキ" = "それで、誰なの？"
"61040-282-？？？" = "こんにちは、アリウススクワッドの皆さん。"
"61040-293-ナギサ" = "本日、この集まりのスポンサーをさせていただいております。#nティーパーティーのホスト、[ruby=きりふじ]桐藤[/ruby]ナギサと申します。"
"61040-294-サオリ" = "なっ……！？"
"61040-298-アツコ" = "……なるほどね。"
"61040-300" = "次回;謝罪"
