[translation]
"10050080-1" = "第8話;古書館戦争"
"10050080-2" = "[ns] \"えっ？正義実現委員会がどうしてここを！？\""
"10050080-3-コハル" = "詳しくは分からないけど、どっかで尻尾をつかんだんじゃないの！？"
"10050080-4-コハル" = "先生に言われた通り、委員会の子たちと一緒に行動してたんだけど……。"
"10050080-13-コハル" = "……それで先生に連絡したの……。"
"10050080-14" = "[s] \"ありがとうコハル！コハル最高！\""
"10050080-15-コハル" = "そ、そうかな？えへへ……。"
"10050080-16-コハル" = "い、いや喜んでる場合じゃなくて！どうするの先生！？"
"10050080-17-コハル" = "ん？シミコさんにも連絡……？そ、そうだ！図書委員会の仕事でもあったんだった。"
"10050080-22-コハル" = "はやく……はやく出て……！"
"10050080-26-シミコ" = "こんにちは、コハルさん。どうかしましたか？"
"10050080-27-コハル" = "シミコさん！たいへん！！"
"10050080-28-シミコ" = "えっ？"
"10050080-30-シミコ" = "本当に大変なことに！？"
"10050080-31-コハル" = "だから言ったでしょ！？"
"10050080-32-シミコ" = "いえ、これはコハルさんが思っているようなレベルではありません！"
"10050080-33-コハル" = "へ？"
"10050080-34-シミコ" = "説明する時間はありません。とにかく、私は急いで古書館に向かいますので……。"
"10050080-35-シミコ" = "コハルさんはどこかに避難しててください。"
"10050080-36-シミコ" = "正義実現委員会とウイ先輩は、相性最悪そのものですから！"
"10050080-37-コハル" = "えっ？なんで私まで……？"
"10050080-38-シミコ" = "……コハルさんまで古書館に行けば巻き添えになると思います。"
"10050080-40-シミコ" = "それに最悪、密告者と思われかねません！"
"10050080-41-シミコ" = "いいですね？全部終わるまで、できるだけこの件から離れててください！"
"10050080-45-コハル" = "巻き添えに、密告者……きっと本当のことなんだろうけど……。"
"10050080-46-コハル" = "……。"
"10050080-47-コハル" = "……でも行かなきゃ。"
"10050080-48-コハル" = "だってそれが正しいから。"
"10050080-57-ウイ" = "先生……？どうしました、その顔色は。"
"10050080-58" = "[s] \"ウイ！ここにいたんだ！よく聞いて今から――\""
"10050080-62-ウイ" = "……何ですか今度は……。"
"10050080-63-ウイ" = "待ってください、先生……誰だか知りませんが、ひと言言ってきます……。"
"10050080-64" = "[s] \"あっいや、そうじゃなくて……！\""
"10050080-65-マシロ" = "[ruby=こぜき]古関[/ruby]ウイさん、いますか？正義実現委員会のマシロです。"
"10050080-66-ウイ" = "……正義実現委員会？どうして……。"
"10050080-67-マシロ" = "こんにちは、ウイ委員長。お久しぶりです。"
"10050080-68-ウイ" = "……なぜここに？"
"10050080-69-マシロ" = "はい、実は……。"
"10050080-70-マシロ" = "ここに、怪しい非公認書籍があるとのタレコミがありました！"
"10050080-71-ウイ" = "……非公認書籍？"
"10050080-72-ウイ" = "……それがどうしたのですか？"
"10050080-77-マシロ" = "はい！そういうわけで……今から古書館内を全数調査すべく、ご協力をお願いします！"
"10050080-82-ウイ" = "……え？"
"10050080-83-ウイ" = "何の調査……？"
"10050080-84-ウイ" = "いや待って……何をするって……？"
"10050080-85-ウイ" = "全数……調査？"
"10050080-86-ウイ" = "……つまり。"
"10050080-87-ウイ" = "この古書館内を？"
"10050080-88-マシロ" = "はい、そうです！"
"10050080-89-ウイ" = "それは……。"
"10050080-90-ウイ" = "今この子たちを……全部、連れていくと？"
"10050080-91-マシロ" = "……えっ？"
"10050080-92-マシロ" = "ああ、そうですね。必要によってはそうなります。"
"10050080-93-マシロ" = "どうかしましたか？"
"10050080-97-マシロ" = "そういうわけなのでご協力をお願いします！"
"10050080-98-マシロ" = "特に後ろめたいことがないのなら、断る理由はないかと――"
"10050080-99-ウイ" = "勝手なこと言うな――！！"
"10050080-103-ウイ" = "黙って聞いていれば……何ですか！？#nうちの子たちを連れていく？"
"10050080-104-ウイ" = "ここがどこだか分かって言っているんですか！？"
"10050080-105-ウイ" = "よく聞いてください。ここにあるモノに指一つ触れたら、誰だろうと手首を――"
"10050080-106-マシロ" = "い、いけません！今の発言は正義実現委員会を脅す発言で……！"
"10050080-107-マシロ" = "ふさわしくない言動です！決して許されない――"
"10050080-108-ウイ" = "それはこっちのセリフですよ！バックに誰がついてるのかも全部分かっているんですから！"
"10050080-109-ウイ" = "ティーパーティー……権力を振りかざし、隠ぺいと陰謀だらけの組織……。"
"10050080-110-ウイ" = "ついには本の調査を口実に、古書館まで自分たちのものにしようって魂胆なのでしょう！？"
"10050080-111-マシロ" = "……へっ？えっ、いや、そういうつもりでは……！"
"10050080-112-正義実現委員会部員A" = "失礼ですが、こちらは公務を行っているだけです！！"
"10050080-113-正義実現委員会部員B" = "そうです！そういう態度で出るならこっちも力で……！！"
"10050080-125-ウイ" = "皆さんよく聞いた上で、お伝えください……。"
"10050080-126-ウイ" = "私の許可なく、この子たちを外に持ち出してはいけません。#n1ページたりとも、です。"
"10050080-127-ウイ" = "つまり――"
"10050080-128-ウイ" = "どうしても持って行きたいというなら、私を倒してから持っていくがいい！"
"10050080-133-マシロ" = "……分かりました。"
"10050080-134-マシロ" = "協力する意志はないこと、たしかに理解しました。"
"10050080-135-マシロ" = "同時に、ティーパーティーの命令および正義実現委員会への脅迫と見受けましたので。"
"10050080-136-マシロ" = "これより正義実現委員会は、正義執行へと移らせていただきます。"
"10050080-137-ウイ" = "へえ、そうですか。そうこなくちゃね。"
"10050080-138-ウイ" = "……[ruby=・]久[/ruby][ruby=・]し[/ruby][ruby=・]ぶ[/ruby][ruby=・]り[/ruby]ですね。どんなもんかやってみましょうか。"
"10050080-149-マシロ" = "……いきます！！"
"10050080-154" = "[ns] \"やめてぇぇええええっ！\""
"10050080-155-シミコ" = "やめてください！！"
"10050080-156-ウイ" = "シミコ？"
"10050080-157-マシロ" = "先生？"
"10050080-158-シミコ" = "みなさん、誤解です！一つ一つちゃんと話し合いませんか！？"
"10050080-159-マシロ" = "……そ、そうなんですか？"
"10050080-164-コハル" = "先生？シミコさん？みんな大丈夫！？"
"10050080-165-正義実現委員会部員C" = "あれ？コハルさん……？どうしてここにコハルさんが。"
"10050080-166-シミコ" = "避難して、と言ったはずですが……。"
"10050080-167-コハル" = "で、でも……ダメでしょ！ダメなもんはダメなの！"
"10050080-168-ウイ" = "また人……？いったい何人来るつもりですか……？"
"10050080-169-ウイ" = "というか、シミコ！そっち側だったんですか！？"
"10050080-170-ウイ" = "内通者がいるかもと思ってたけど、あんただったとはね！ほんと、人間は誰ひとり信じちゃいけないと言うけど……。"
"10050080-179-ウイ" = "ぎぃやっ……！し、シミコ……！！"
"10050080-180-シミコ" = "先輩！！またやらかしたんですね！？#n内通者って……人の気も知らないで……！！"
"10050080-181-シミコ" = "というか、いきなり人を撃っちゃダメなのは常識ですよね！？#n今度は何人病院送りにするつもりですか……！？"
"10050080-182-ウイ" = "い、いやっ、私はただ……！！"
"10050080-183-シミコ" = "問答無用です！！"
"10050080-192-ウイ" = "ぎぃあぁぁぁっ！！"
"10050080-194-マシロ" = "あ……ええっと……。"
"10050080-195-マシロ" = "なんだか困った状況になりましたが、正義実現委員会の目的はまだ達成できていません。"
"10050080-196-マシロ" = "私たちは非公認書籍を調べなくてはいけません。ここにある可能性が高いと判断しています。"
"10050080-197-マシロ" = "非公認の書籍がトリニティで出回るのは看過できない事態……。"
"10050080-198-シミコ" = "はい、その件に関しては同意です。みなさんのことを止めたいわけではありません。"
"10050080-199-シミコ" = "つまりこれは――"
"10050080-205-タカネ" = "皆さん、申し訳ございませんでした。"
"10050080-206-ウイ" = "か、隠れているようにと言ったはず、ですが……！？"
"10050080-207-タカネ" = "はい、そうですが……やはり筋ではないと思いまして。#n結局は私たちのせいでこうなったのですから。"
"10050080-208-タカネ" = "助けていただいたのは大変感謝しておりますが、同じ学園内で争うのは求めておりませんわ。"
"10050080-209-タカネ" = "さあ、部長もこちらへ。ちゃんとお伝えすべきかと。"
"10050080-210-ヤクモ" = "あーあ。適当に忍び込めたんだし、帰りも楽できるかなと思ったんですが。"
"10050080-211-タカネ" = "……部長？"
"10050080-212-ヤクモ" = "……申し訳ございませんでした。"
"10050080-213-タカネ" = "初めまして、トリニティのみなさん。レッドウィンター連邦学園から参りました、出版部と申しますわ。"
"10050080-214-マシロ" = "出版？"
"10050080-215-コハル" = "部？"
"10050080-216-タカネ" = "ええ。今回の経緯を説明した方がよさそうですわね。"
"10050080-217-タカネ" = "実は私たち――"
"10050080-219-マシロ" = "あ……えっと……つまり。"
"10050080-220-マシロ" = "出版部のみなさんは、餓死寸前の知識解放戦線の生徒さんたちを救うために――"
"10050080-221-マシロ" = "新しい販路を開こうと、トリニティに来た、と……？"
"10050080-222-ヤクモ" = "まあ……別にあの子たちを助けたいとかじゃなく、ただお金が――"
"10050080-223-タカネ" = "部長？"
"10050080-224-ヤクモ" = "すみません……。"
"10050080-225-ヤクモ" = "しかし何といいますか、他にも……。"
"10050080-226-ヤクモ" = "我々レッドウィンターが作った文化媒体を、より多くの方々に紹介できたらな、という気持ちもありました。"
"10050080-227-ヤクモ" = "あれ、レッドウィンターではもう擦り尽くした内容だし、需要もなくて。"
"10050080-228-ヤクモ" = "それが幸運にも、トリニティで少なくない人気を博したわけで。"
"10050080-229-マシロ" = "そうですね……。"
"10050080-230-マシロ" = "私たちと図書委員が協力して出動せざるを得ないくらいの規模でしたから……。"
"10050080-231-マシロ" = "まさか、トリニティのみなさんが、あなた方を助けていたなんて……。"
"10050080-232-マシロ" = "調査が難航したのも納得しました。"
"10050080-233-ウイ" = "……そんなことがあったんだ？"
"10050080-234-シミコ" = "そうですよ、委員長。もう少し外のことにも興味を持ってください。"
"10050080-235-シミコ" = "これだって本当は、委員長の仕事だったんですから。"
"10050080-236-ウイ" = "い、いいいや……そ、そんなの、私にはちょっと荷が重すぎる……。"
"10050080-237-ヤクモ" = "ともかく。文化は巡るべきだと思っております。"
"10050080-238-ヤクモ" = "停滞した文化は、最終的に集団の足を引っ張る害悪となることでしょう。"
"10050080-239-ヤクモ" = "純粋に、稼げないですしね。"
"10050080-240-ヤクモ" = "まあ最初からそんな大義を掲げてトリニティに来たわけじゃありませんが……。"
"10050080-241-ヤクモ" = "喜んでくれる生徒さんを見て、いろいろ思うことがありましてね。"
"10050080-242-タカネ" = "あら、そうだったのですね？"
"10050080-243-ヤクモ" = "ええ……あえて話さないことで、完成に近づく物語もあるというものですし？"
"10050080-244-タカネ" = "うっ、それをここで……！"
"10050080-245-ヤクモ" = "部長の名は伊達じゃありませんので。ムフフ。"
"10050080-247-マシロ" = "しかし、許可されていない書籍、という事実に変わりはありませんが……。"
"10050080-251" = "[ns] \"図書委員会が許可しちゃダメなのかな？\""
"10050080-252-マシロ" = "図書委員会が……？"
"10050080-253-シミコ" = "……そうですね。トリニティで流通されるあらゆる書籍の責任は、図書委員会にあります。"
"10050080-254-シミコ" = "出版部のみなさんが持ち込んだこの本が、図書委員会によって許可されればもう非公認書籍ではなくなります。"
"10050080-255-シミコ" = "ただ、トリニティに合うよう多少内容の調整が入ると思いますが。"
"10050080-256-ヤクモ" = "やはり……そのレベルでしたか。"
"10050080-257-タカネ" = "薄々感じてはいましたが……。"
"10050080-262" = "[ns] \"そういった手順を踏むのも「正義」じゃないかな？\""
"10050080-263-マシロ" = "なるほど、たしかにその通りですね。"
"10050080-264-マシロ" = "正義が崩壊したような場でも、過程を踏むことで新たな「正義」を築く……。"
"10050080-265-マシロ" = "さすが先生です！勉強になりました！"
"10050080-266" = "[s] \"あっ、う、うん！そういうこと！\""
"10050080-267-シミコ" = "そういえば、委員長はどうでしたか？あの本。"
"10050080-268-ウイ" = "えっ、な、なんで私に……。"
"10050080-269-シミコ" = "もう読まれたんですよね？全部。"
"10050080-270-ウイ" = "なんで、知ってるんです……。"
"10050080-271-シミコ" = "ふふ、どれだけ委員長と一緒にいると思ってるんですか。"
"10050080-272-ウイ" = "ったく、噓もつけないんだから……。"
"10050080-273-ウイ" = "ふぅ……まあ、良い本でしたよ。私からしたら。"
"10050080-274-ウイ" = "出版部の方の本気も、作り手のみなさんの熱意もちゃんと伝わってきました。"
"10050080-275-ウイ" = "……最近は太く短い商売ばかりで、利益を追及する本が多かったのですが。#nまぁ……そういうのよりは、よかったですよ。"
"10050080-276-シミコ" = "それで、結論は？"
"10050080-277-ウイ" = "私は……いいと思う。調整も別に、いらないとは思うけど……。"
"10050080-278-ウイ" = "他の人のことは分からないから……そこはシミコに任せます。"
"10050080-279-シミコ" = "はい、分かりました。"
"10050080-280-マシロ" = "ありがとうございます、図書委員会の皆さん。では今回の件はそのように報告させていただきます！"
"10050080-281" = "[s] \"じゃあ私も一緒に行くね。ひと言添えておく。\""
"10050080-282-シミコ" = "では私も。委員長はたぶん行かないと思うので。"
"10050080-283-ウイ" = "行かない。"
"10050080-284-マシロ" = "先生やシミコさんにまでご迷惑をかけるわけには……。"
"10050080-285-マシロ" = "……。"
"10050080-286-マシロ" = "いや、では最後までどうぞよろしくお願いします。"
"10050080-287-マシロ" = "本来この件は、正義実現委員会と図書委員会、先生を含めたみんなで協力する任務でしたね。"
"10050080-288-コハル" = "無事に終わってよかった。えへへ。"
"10050080-289-マシロ" = "では解決したことですし、図書委員長公認の書籍を一読してみましょうか。"
"10050080-290-正義実現委員たち" = "はい！私たちも読んでみたいです！"
"10050080-291-コハル" = "（ごくっ……）"
"10050080-292" = "[s] （これは、もしかすると……）"
"10050080-296-マシロ" = "……！"
"10050080-297-マシロ" = "これはまたずいぶん……！"
"10050080-304-コハル" = "……。"
"10050080-305-コハル" = "ひゃぁぁっ！？！？"
"10050080-307-コハル" = "エッチなのはダメ！禁止！死刑！！！"
