[translation]
"10025105-2-ミヤコ" = "RABBIT1、[ruby=アフト]Aft[/ruby]クリア。"
"10025105-3-サキ" = "RABBIT2、[ruby=バウ]Bow[/ruby]クリア。"
"10025105-4-ミユ" = "ら、RABBIT4……[ruby=ブリッジ]Bridge[/ruby]クリア。"
"10025105-5-ミヤコ" = "船内の全敵勢力を無力化、危険要素の排除完了。"
"10025105-6-ミヤコ" = "これにて作戦を終了します。皆さん、お疲れ様でした！"
"10025105-11-モエ" = "えっ。ちょっと、私の出番は？"
"10025105-12-サキ" = "遅かったな、RABBIT3。"
"10025105-13-サキ" = "もう終わったぞ。こっちからしたら、物足りないくらいだ。"
"10025105-14-モエ" = "それを言いたいのはこっちだよ！#n船上作戦って言うから、対艦ミサイルを用意してきたのにさぁー……"
"10025105-20-モエ" = "ね、RABBIT2……このミサイル、1回だけ撃っちゃダメ？"
"10025105-21-モエ" = "1回で沈めるからさ……？"
"10025105-22-サキ" = "なに言ってんだバカ！まだ私たちも[ruby=ここ]船[/ruby]にいるんだからな！？"
"10025105-28-年老いた漁師" = "……SRT特殊学園、と言ったか？"
"10025105-29-ミヤコ" = "あ、はい……その……"
"10025105-30-ミヤコ" = "……申し訳ありません。"
"10025105-31-ミヤコ" = "調査のためとはいえ、結果的に皆さんを騙してしまう事になり――"
"10025105-32-年老いた漁師" = "いや、頭を上げてくれ。謝ってほしいわけではないんじゃ。"
"10025105-33-年老いた漁師" = "村の問題だというのに……[ruby=よそさま]他所様[/ruby]の手を借りてしまって面目ない。"
"10025105-37-ミヤコ" = "いえ……これは[ruby=やとうら]夜戸浦[/ruby]村だけの問題ではありません。"
"10025105-38-年老いた漁師" = "……と言うと？"
"10025105-39-ミヤコ" = "この村もキヴォトスの一部ですから。#n言い換えれば、ここで起きた問題はキヴォトスの問題でもあるという事。"
"10025105-40-ミヤコ" = "ですから、[ruby=ここ]キヴォトス[/ruby]で何か問題が発生したときは、#n私たちSRT特殊学園に連絡してください。"
"10025105-41-ミヤコ" = "いつだって、私たちが力になります。"
"10025105-42-年老いた漁師" = "SRT、特殊学園か……"
"10025105-43-年老いた漁師" = "……ありがとう。この恩、忘れぬよ。"
"10025105-44-ミヤコ" = "……はい！"
"10025105-50-ミヤコ" = "そうでした、こちらの容疑者の扱いですが――"
"10025105-51-ヴァルキューレの海警" = "こちらに任せていただけませんか？"
"10025105-52-ヴァルキューレの海警" = "私たちの管轄で起きた事件ですし。"
"10025105-53-ヴァルキューレの海警" = "せっかくのチャンス……と言って良いものか分かりませんが、#nこれも実績につながりますから。"
"10025105-55-ミヤコ" = "……そうですね。では、後はよろしくお願いします。"
"10025105-57-海運会社の者" = "あっ……お、おい。ちょっと待ってくれよ！"
"10025105-64-年老いた漁師" = "……[ruby=くまがい]熊谷[/ruby]、連れていけ。"
"10025105-65-年老いた漁師" = "夜戸浦流のやり方を見せてやるといい。"
"10025105-67-海運会社の者" = "ちょ、待てよ……夜戸浦流って何だよ……おい！"
"10025105-69-漁師" = "それは――"
"10025105-70-年老いた漁師" = "教えてやる必要はない……じきに分かることじゃからな。"
"10025105-72-海運会社の者" = "せ、せめて何をされるのかくらい教えてくれても……！"
"10025105-78-年老いた漁師" = "やっと分かったか？それが恐怖じゃ。"
"10025105-80-年老いた漁師" = "何をされるか分からない状況に怯え、苦しむが良い。"
"10025105-85-年老いた漁師" = "古来より恐怖とは……無知から生ずるものと言われておるからな。"
