[translation]
"1013708-1" = "とある刑事の療養"
"1013708-2" = "（風邪を引いたというコノカが心配になり、お見舞いに行くことにした）"
"1013708-6" = "[ns] \"ごめんくださいー。\""
"1013708-7-コノカ" = "うぅ……誰だよ……もう……。"
"1013708-8-コノカ" = "うちにはテレビないってば！！"
"1013708-9-コノカ" = "げほっ、応援してたチームが負けた時に壊しちゃったんだから……。"
"1013708-10-コノカ" = "今度来たら逮捕するって、げほっ、言ったと思うんだけど？"
"1013708-11" = "[s1] \"お、落ち着いて、コノカ！\"\n[s2] \"私だよ、私！\""
"1013708-14-コノカ" = "え、ええ！？"
"1013708-15-コノカ" = "先生？あ、どうぞ入ってください。鍵は開いてるっす！"
"1013708-19" = "[ns] \"鍵かけてないの！？\""
"1013708-20-コノカ" = "げほっ、泥棒入ってきたら、そのまま現行犯逮捕できるじゃないっすか。"
"1013708-21-コノカ" = "ノルマも達成できるし、色々便利なんすよ。"
"1013708-22" = "[s] \"ヴァルキューレの寮に泥棒……！？\""
"1013708-23-コノカ" = "怖いもの知らずというか、犯罪者の考えることは分からないっすからね～"
"1013708-24-コノカ" = "それより、どういったご用件で……げほっ……。"
"1013708-25" = "[s] \"風邪ひいたって聞いてお見舞いに来たよ。\""
"1013708-26-コノカ" = "どうやって知ったんすか！？"
"1013708-27" = "[s3] \"コノカがモモトークで教えてくれたから……。\"\n[s4] \"風邪引いて休むって言ってたよね？\""
"1013708-30-コノカ" = "げほっ、は、はぇ……？"
"1013708-32-コノカ" = "ああっ、げほっ……あのモモトーク。"
"1013708-33-コノカ" = "うちの子たちに送ったと思ってました……すいません。"
"1013708-34-コノカ" = "わざわざお見舞いに来てくれるなんて……申し訳ないっす。"
"1013708-35" = "[s] \"全然！むしろ喜んで行くよ。\""
"1013708-36-コノカ" = "うぅ、ありがとうございます。#nでも、ちょっと今、だいぶ意識朦朧としてて……。"
"1013708-37-コノカ" = "風邪でお見舞いきてもらうのも初めてっすし、どうすればいいのか……。"
"1013708-38" = "[s5] \"ご飯はもう食べた？\"\n[s6] \"お粥でも作ろうか？\""
"1013708-41-コノカ" = "お粥……あー、そういえばまだ何も食べてないっす。"
"1013708-42-コノカ" = "えっと……げほっ、豚骨にニンニクましまし、野菜抜き、ラー油追加でお願いします。"
"1013708-43" = "[s] \"ラーメン屋じゃないんだよ！？\""
"1013708-44-コノカ" = "はぇ？"
"1013708-47-コノカ" = "ふぅ、ごちそうさまでした。"
"1013708-48-コノカ" = "麺抜きのラーメンみたいで食べやすかったっす。#nニンニクもっと入れとけばよかった。"
"1013708-49" = "[s] \"まあ、食べられたみたいだし、これでいいのかな……？\""
"1013708-50-コノカ" = "ぐはっ、げほっ、大袈裟っすよ。"
"1013708-51-コノカ" = "ただの風邪っすから。この程度運動すれば――"
"1013708-56" = "[ns] コノカの額に手を当ててみる。"
"1013708-58-コノカ" = "！！！"
"1013708-59-コノカ" = "ひぁっ……。"
"1013708-63-コノカ" = "……げほっ。"
"1013708-64-コノカ" = "……え、ええ？"
"1013708-65" = "[s] \"熱が高いね。横になったほうがいい。\""
"1013708-66-コノカ" = "あ……。"
"1013708-67-コノカ" = "う、うん……。"
"1013708-71" = "[ns] \"どう？まだ辛い？\""
"1013708-72-コノカ" = "あ、えっと……！"
"1013708-73-コノカ" = "その……ちょっと、まだ辛いかもしれないっす。"
"1013708-74-コノカ" = "あ、あーあ、痛いー痛いなー。げほっ、げほっ。"
"1013708-75" = "[s] \"寝付くまでそばにいるから。\""
"1013708-76-コノカ" = "は、はい……。"
"1013708-77-コノカ" = "あ、それなら……ドア、閉めて……ください。"
"1013708-78-コノカ" = "いまどろぼーきても、先生のこと、守れないんで……。"
"1013708-79" = "[s] \"うん。そうだ、今日の占いでも読み上げようか？\""
"1013708-80-コノカ" = "あ、いえ。大丈夫っす。"
"1013708-81-コノカ" = "今日は最高の一日に、なってるんで。"
"1013708-83" = "（その後も、コノカの隣で看病を続けた）"
