[translation]
"102140-1" = "第14話;「トリニティ」自治区防衛（２）"
"102140-2-ハスミ" = "こちらは、おおかた片付きましたね……"
"102140-3-セイア" = "いや、まだ何かが――"
"102140-5-ナギサ" = "セイアさん……？"
"102140-6-セイア" = "避難できていない市民が居る……あれはおそらく、遺跡地帯の辺りだろうか。"
"102140-7-ハスミ" = "マシロ、遺跡地帯を確認してください。何か異変はありますか？"
"102140-8-マシロ" = "はい、先輩。今確認します―― "
"102140-12-マシロ" = "――！！遺跡の聖堂付近で、避難できていない市民と生徒を確認しました！"
"102140-13-ハスミ" = "そ、んな……！？"
"102140-28-マシロ" = "あ、あれ……？#nですが、中にいるのは……"
"102140-36-トリニティの生徒" = "うう……！"
"102140-57-コハル" = "はぁ、はぁ……"
"102140-62-コハル" = "も、もう少しでハスミ先輩と正義実現委員会が助けに来るから……#nあとちょっと……我慢……"
"102140-64-ハスミ" = "コハルが一人で……！？#nどうして……！？"
"102140-65-ミカ" = "コハルちゃんが閉じ込められてるの……？#n一体どこに！？"
"102140-66-ハスミ" = "コハルは避難誘導に投入されたはずですが……#nどこですれ違ってしまったのでしょう……いえ、私がそちらに向かいます！"
"102140-68-マシロ" = "はい、先輩！私も今から向かいます！！#nで、ですが、敵の数が多すぎます……"
"102140-69-ハスミ" = "至急、支援兵を遺跡に送ってください！"
"102140-93-コハル" = "あ、あうう……"
"102140-97-コハル" = "こ、こっち来ないで……！！"
"102140-106-コハル" = "う、うぅ……"
"102140-113-？？？" = "はいはーい！ちょ～っと失礼するね。"
"102140-116-コハル" = "へっ、か、壁が……？"
"102140-122-トリニティの生徒C" = "あれは……裏切り者のミカ！？"
"102140-123-トリニティの生徒D" = "魔女がどうしてここに……！？"
"102140-126-ミカ" = "コハルちゃんがここに居るって聞いて、ダッシュで来ちゃった☆"
"102140-127-コハル" = "あ、えっと……そ、その……ティーパーティーの……"
"102140-131-ミカ" = "コハルちゃん大丈夫？怪我は無い？#n――いや、怪我してるね。"
"102140-132-コハル" = "……あ……こ、これはちょっとした擦り傷で……"
"102140-133-ミカ" = "……そっか。"
"102140-144-ミカ" = "あなた達が、やったんだ……本当さぁ……もう……"
"102140-148-ミカ" = "……私の大切な[ruby=・   ・   ・]お友達[/ruby]に、一体何してるの？"
