[translation]
"102145-3-ハスミ" = "コハル！"
"102145-6-マシロ" = "コハルさん！大丈夫ですか？"
"102145-8-コハル" = "は、ハスミ先輩……マシロ……"
"102145-10-トリニティの生徒C" = "よかった！正義実現委員会だ！"
"102145-11-トリニティの生徒D" = "助けに来てくれたんですね！あの魔女が――"
"102145-15-ハスミ" = "……ミカ様。"
"102145-16-ミカ" = "うん。コハルちゃんは大丈夫だよ。#nちょっと怪我してるけど。"
"102145-17-ハスミ" = "……。"
"102145-18-ミカ" = "……え？なになに？#n本当に、今度は何もしてないってば☆"
"102145-19-コハル" = "そ、そうです……ハスミ先輩……#nその、この方は……私を助けてくれて……"
"102145-20-マシロ" = "行きましょう、コハルさん。"
"102145-21-コハル" = "は、はい……。"
"102145-22-ミカ" = "またね、コハルちゃん。 "
"102145-25-ハスミ" = "……助けていただき、ありがとうございます。"
"102145-26-ミカ" = "あれ、お礼を言われるとは思わなかったなぁ……"
"102145-27-ハスミ" = "……コハルを助けてくださったのは、事実ですから。"
"102145-28-ミカ" = "……まぁ、そうね。"
"102145-29-ミカ" = "じゃ、私はまだやる事があるからお先☆"
"102145-30-ミカ" = "それじゃあね、ハスミちゃん。"
"102145-34-ハスミ" = "……。"
"102145-36" = "次回;第4サンクトゥム「カタコンベ内バシリカ」"
