[translation]
"2002905-1" = "夏の海の思い出"
"2002905-2-ミモリ" = "海辺"
"2002905-5-ミモリ" = "さあ、先生……いきますよ？"
"2002905-6-ミモリ" = "せーの……！"
"2002905-14" = "[ns] \"えいっ！\""
"2002905-16-ミモリ" = "お上手です！次は……はいっ！"
"2002905-25" = "[ns] \"ほっ！\""
"2002905-27" = "（ミモリと一緒に、浜辺でビーチバレーをすることに）"
"2002905-28" = "（しばらくラリーを続けていたところ……）"
"2002905-31-ミモリ" = "きゃっ？"
"2002905-39" = "[ns] \"大丈夫！？\""
"2002905-40-ミモリ" = "はい、大丈夫です。少し足をくじいただけなので。"
"2002905-41-ミモリ" = "ふふっ、今度は私の負けですね。"
"2002905-42-ミモリ" = "……ラリーに勝ち負けはないのですか？"
"2002905-43-ミモリ" = "たしかに、仰る通りですね。ですが、どうしてでしょう。"
"2002905-44-ミモリ" = "今日の私は、勝負がしたい気分なんでしょうか？"
"2002905-45-ミモリ" = "……ふふっ。少し、休憩しませんか？"
"2002905-46-ミモリ" = "そちらのクーラーボックスで、パイナップルジュースを冷やしておきました。#nどうぞ、お飲みください。"
"2002905-53-ミモリ" = "喉が乾いてるとは思いますが、ゆっくり飲んでくださいね。#nお腹がビックリするかもしれませんから。"
"2002905-54-ミモリ" = "うーん……その表情は、もしかしてお腹が空きました？"
"2002905-55-ミモリ" = "海の家で、焼きそばでも買ってきましょうか？"
"2002905-56" = "[s1] \"ううん、そこまでしなくても大丈夫だよ。\"\n[s2] \"それに行くなら、ミモリと一緒がいいな。\""
"2002905-59-ミモリ" = "……。"
"2002905-60-ミモリ" = "も、もう。先生は、いつもそうやって……"
"2002905-61-ミモリ" = "あ、違います。先生は何も悪くないので！#nこれは、私が勝手に意……"
"2002905-62-ミモリ" = "……な、何でもありません！#nその……先生、お隣り失礼しますね！"
"2002905-66" = "（急に慌てて隣に座ってきたミモリと肩を寄せ合い、押し寄せては引いていく波の様子を眺めていた）"
"2002905-71-ミモリ" = "……。"
"2002905-72" = "[ns] \"……。\""
"2002905-73-ミモリ" = "……素敵ですね。"
"2002905-74" = "[s] \"好きなの？\""
"2002905-75-ミモリ" = "はい！？あ、海が……ですよね？"
"2002905-76-ミモリ" = "その、もちろん海も好きなのですが……#nこうして、ゆったり過ごす時間が好きと言いますか……"
"2002905-77-ミモリ" = "……ズルいです、先生は。"
"2002905-78" = "[s] \"え、どうして私が！？\""
"2002905-79-ミモリ" = "ふふっ。"
"2002905-80-ミモリ" = "先生……？"
"2002905-81" = "[s] \"どうしたの？\""
"2002905-82-ミモリ" = "わ、私を捕まえてみてください！"
"2002905-87" = "（突然ミモリが走り出した！）"
"2002905-90" = "[ns] \"み、ミモリ！？……もしかして、また勝負？\""
"2002905-91-ミモリ" = "ふふっ。こっちですよ、先生～！"
"2002905-97" = "（ミモリと一緒に砂浜を走り回った）"
"2002905-102" = "（しばらく2人で追いかけっこを楽しんでいたところ……）"
"2002905-106" = "[ns] \"うわっ！？\""
"2002905-108" = "（砂浜に足を取られて、盛大に転んでしまった……）"
"2002905-109-ミモリ" = "せ、先生！？"
"2002905-113-ミモリ" = "大丈夫ですか？すみません、私のせいで……"
"2002905-114-ミモリ" = "うぅ……そんな、泣かないでなんて言われましても……"
"2002905-115-ミモリ" = "すみません……本当にすみません、先生……"
"2002905-116" = "[s3] \"あはは、本当に大丈夫だよ。\"\n[s4] \"久しぶりに気持ち良く走れて、楽しかったよ。\""
"2002905-119-ミモリ" = "本当……ですか？"
"2002905-120-ミモリ" = "本当、ですよね？"
"2002905-121-ミモリ" = "ですが、そろそろお疲れでしょうし、追いかけっこは……"
"2002905-122-ミモリ" = "あ、そうです！今度は、海の上に浮かんで遊びませんか？"
"2002905-123-ミモリ" = "ふふっ。先生、付いてきてください♪"
"2002905-128-ミモリ" = "こうして力を抜いて、空を眺めながら……"
"2002905-129-ミモリ" = "息を深く吸うと……"
"2002905-130-ミモリ" = "水の上でぷかぷか浮かぶことができるんです。"
"2002905-131-ミモリ" = "先生も一度、やってみてください！"
"2002905-132" = "（ミモリに言われた通り、身体の力を抜いてゆっくり息を吸い込んだ）"
"2002905-137-ミモリ" = "どうでしょうか、先生？"
"2002905-138-ミモリ" = "……このまま寝てしまいそうですか？"
"2002905-139-ミモリ" = "き、気をつけてくださいね！？また海で眠ってしまっては……"
"2002905-140-ミモリ" = "……いえ。いざとなったら、私が助けるのでご安心ください。"
"2002905-141-ミモリ" = "それにしても、今日はとても気持ちが良い日ですね。"
"2002905-142-ミモリ" = "…………ふふっ、先生と2人だからでしょうか？"
"2002905-148-ミモリ" = "先生、今日はいかがでした？"
"2002905-149-ミモリ" = "……楽しんでいただけましたか？それなら良かったです。"
"2002905-150-ミモリ" = "……。"
"2002905-151" = "[s] \"ミモリ？\""
"2002905-152-ミモリ" = "……もう、こんな時間ですね。"
"2002905-153-ミモリ" = "どんなに楽しい1日だとしても、終わりは訪れるものですが……"
"2002905-154" = "[s] \"うん……そうだね。\""
"2002905-155-ミモリ" = "あの、先生……"
"2002905-156-ミモリ" = "もう少しだけで良いので、おそばに居ていただけますか？"
"2002905-157-ミモリ" = "本当に、ほんの少しだけで良いんです。"
"2002905-158" = "[s] \"それは良いんだけど、どうしたの？\""
"2002905-159-ミモリ" = "すみません、先生。"
"2002905-160-ミモリ" = "甘えているという自覚はあります。ですが……"
"2002905-161-ミモリ" = "今日という1日が、本当に楽しくて……本当に……"
"2002905-162-ミモリ" = "先生と一緒に過ごせるだけでも、私は朝からずっと嬉しい気持ちが抑えられず……"
"2002905-163" = "[s5] \"まだ今日は終わってないよ。\"\n[s6] \"私も、ミモリと一緒に過ごせて楽しかったよ。\""
"2002905-166-ミモリ" = "……ふふっ、はい。"
"2002905-167-ミモリ" = "この時間の海も……綺麗ですね。"
"2002905-168" = "[s] \"もう少し泳ごうか？\""
"2002905-172-ミモリ" = "いえ……少し、歩きませんか？"
"2002905-179" = "[wa:2250]― [log=미모리 수영복ND]このまま……[/log]"
"2002905-181" = "[wa:300]― [log=미모리 수영복ND]この時間が[wa:1550]永遠になってしまえばいいのに。[/log]"
"2002905-184" = "[wa:2350]― [log=미모리 수영복ND]このまま、[wa:1050]写真や[wa:450]絵のように[wa:1400]時が記録されて――[/log]"
"2002905-186" = "[wa:100]― [log=미모리 수영복ND]そうしたら……[/log]"
"2002905-189" = "[ns7] \"本当に、今日は楽しかったね。\"\n[ns8] \"……私も寂しくなってきたよ。\""
"2002905-190" = "[wa:500]― [log=미모리 수영복ND]先生も[wa:1300]同じ気持ち、[wa:1400]なのですか？[/log]"
"2002905-191" = "[wa:500]― [log=미모리 수영복ND]先生も[wa:1300]同じ気持ち、[wa:1400]なのですか？[/log]"
"2002905-193" = "[wa:350]― [log=미모리 수영복ND]それは……[wa:1550]なんだか、[wa:1550]照れますね。[/log]"
"2002905-196" = "[wa:1500]― [log=미모리 수영복ND]私は今日……[/log]"
"2002905-198" = "[wa:100]― [log=미모리 수영복ND]修行を忘れるくらい……[wa:1600]幸せでした。[/log]"
"2002905-201" = "[wa:1900]― [log=미모리 수영복ND]その……[wa:1650]先生。[/log]"
"2002905-204" = "[wa:950]― [log=미모리 수영복ND]いつかまた……[/log]"
"2002905-206" = "[wa:750]― [log=미모리 수영복ND]このような時間を作っていただけますでしょうか？[/log]"
"2002905-210-ミモリ" = "陽が、落ちてしまいました……#nですが、これからはお月様の時間ですよね。"
"2002905-211-ミモリ" = "……先生、明日は晴れるでしょうか？"
"2002905-212" = "[s] \"うん、きっと晴れるよ。\""
"2002905-213-ミモリ" = "ふふっ、ありがとうございます。"
"2002905-214-ミモリ" = "今日は……先生に甘えてばかりでしたね。"
"2002905-215-ミモリ" = "よろしければ、その……肩を貸していただけませんか？"
"2002905-220" = "（月の光に照らされたミモリの横顔は、何よりも美しかった）"
