[translation]
"2600703-1" = "布団の中のアヤネ"
"2600703-2" = "（心配になったので、アヤネの部屋を訪れた）"
"2600703-9" = "（返事がない）"
"2600703-13-アヤネ" = "う～ん……セリカちゃん……？"
"2600703-14-アヤネ" = "先輩たちに言われたの……？"
"2600703-15-アヤネ" = "……ごめん……あと5分だけ……。"
"2600703-19" = "（………）"
"2600703-23-アヤネ" = "……5分だけって……いったでしょ～。"
"2600703-24-アヤネ" = "セリカちゃんが起こしてもダメだよ。今日はそう決めたんだから。"
"2600703-28-アヤネ" = "セリカちゃん……今日はちょっとしつこいよ。"
"2600703-29-アヤネ" = "今日は絶対に外に出ないから……セリカちゃんが諦めて……。"
"2600703-33" = "[ns] \"……。\""
"2600703-35" = "[ns] ドアを開けて入る。"
"2600703-42" = "（ドアを開けて入ると、ベッドの上の「何か」が目に入った）"
"2600703-48" = "[ns] \"…………。\""
"2600703-49-アヤネ" = "セリカちゃん……？"
"2600703-50-アヤネ" = "たとえセリカちゃんでも……私からこの布団をはがすことはできない……。"
"2600703-51-アヤネ" = "私はこの中で睡眠を満喫するの……。"
"2600703-52-アヤネ" = "……ここは私だけの秘密基地。"
"2600703-53" = "[s] \"…………。\""
"2600703-55" = "[ns] 布団ごと揺らしてみる。"
"2600703-59-アヤネ" = "むむ……いつもより優しいけど、少し重い手つき……。"
"2600703-60-アヤネ" = "でも、この程度で基地は崩れません……私はもっと寝るんだから……！"
"2600703-61" = "[s] 布団をさらに揺らしてみる。"
"2600703-65-アヤネ" = "セリカちゃん……。"
"2600703-66-アヤネ" = "もう今日は諦めたら……。"
"2600703-67-アヤネ" = "いくら私でも……我慢の限界っていうのがあって……。"
"2600703-68" = "[s] 構わず布団を揺らしてみる。"
"2600703-73-アヤネ" = "……。"
"2600703-74-アヤネ" = "せ……りか……ちゃん……！！"
"2600703-75-アヤネ" = "もう……っ！"
"2600703-79-アヤネ" = "まったく、ちょっとは人の言うことを……！！"
"2600703-82-アヤネ" = "……聞いた……ほう……。"
"2600703-86-アヤネ" = "……が…………？"
"2600703-87" = "[s1] \"……おはよう、アヤネ。\"\n[s2] \"ごめんね、セリカじゃなくて。\""
"2600703-88-アヤネ" = "あれ……？"
"2600703-89-アヤネ" = "あれ……？"
"2600703-90-アヤネ" = "えっ……。"
"2600703-91-アヤネ" = "こ、こんにちは、先生……えっと……どうしてここに……。"
"2600703-92-アヤネ" = "えっ……モモトーク？"
"2600703-96-アヤネ" = "……あっ。"
"2600703-97-アヤネ" = "これは……寝ぼけて送っちゃったみたいですね……。"
"2600703-101-アヤネ" = "その……先生……。"
"2600703-102-アヤネ" = "これは、あの……えっと……。"
"2600703-103" = "[s3] \"……そろそろ行こうか。みんな待ってるよ。\"\n[s4] \"もうご飯できたから食べに行こう。\""
"2600703-108-アヤネ" = "……はい。"
