[translation]
"80000126-1" = "三種の神器"
"80000126-4-レイ" = "こんにちは、先生っ！"
"80000126-5" = "[s] \"や、レイ。どうしたの？\""
"80000126-6-レイ" = "それはですね、えっと……。"
"80000126-7-レイ" = "…………。"
"80000126-10-レイ" = "（うぅっ……覚悟したはずなのに！何度もトレーニングしてきたのに……！）"
"80000126-11-レイ" = "（先生の前だと、勇気がっ……！！）"
"80000126-12-レイ" = "（やっぱりイメトレじゃ……今日はもう、挨拶だけして帰――）"
"80000126-13-レイ" = "（いやいや！いくら何でもそれは！）"
"80000126-16" = "[ns] \"レイ？\""
"80000126-17-レイ" = "っ……！"
"80000126-18-レイ" = "えっと、その……あ、アレですよ、アレ。今日はその、アレじゃないですか？"
"80000126-19" = "[s] \"アレ……？\""
"80000126-20-レイ" = "っ、ば、バっ……！"
"80000126-21-レイ" = "バレンタインデー、ですっ！"
"80000126-22-レイ" = "ご、ごめんなさいっ！#nつい声が……うぅ。"
"80000126-23-レイ" = "そ、それで……こ、こちらを、作ってみたんですが……。"
"80000126-24-レイ" = "受け取ってもらえると、嬉しいですっ！"
"80000126-25" = "（チョコレートでできたグローブ？を受け取った）"
"80000126-30-レイ" = "ど、どうにかやりました……。"
"80000126-31" = "[s1] \"すごい、グローブの形だ！\"\n[s2] \"ありがとう、大切に食べるね。\""
"80000126-36-レイ" = "！！！"
"80000126-37-レイ" = "いえ、こちらこそありがとうございます！"
"80000126-38-レイ" = "……？#nあ、このチョコ、ですか……？"
"80000126-39-レイ" = "それは何と言いますか……。"
"80000126-40-レイ" = " 自分で作ったと、言えなくもないような……？"
"80000126-42" = "（気になるので、詳しく聞いてみることにする）"
"80000126-45-レイ" = "このグローブ……私が前に使ってたものと、同じ型なんです。"
"80000126-46-レイ" = "それをスキャンして、処理をしたデータを……。"
"80000126-47-レイ" = "プリンターで出力したんです。"
"80000126-48-レイ" = "つまりその、型を自分で作ったわけでは、ないのですが……。"
"80000126-49-レイ" = "一応……あとの処理は、自分で。"
"80000126-50-レイ" = "あ、でもチョコを溶かしたのと、ちゃんとピカピカに磨いたのは自分です……！"
"80000126-51-レイ" = "まぁ、それだけと言えばそれだけで……。"
"80000126-52-レイ" = "これで手作りと言えるのか……。"
"80000126-53" = "[s3] \"そこまで手の込んだチョコ、本当にありがとね。\"\n[s4] \"れっきとした「手」作りだよ。\""
"80000126-56-レイ" = "そう、ですか……？"
"80000126-57-レイ" = "へへっ……。"
"80000126-58-レイ" = "あ、実はそれから、こういうものもありまして！"
"80000126-63" = "[ns] \"バットに、ボールまで……！\""
"80000126-64-レイ" = "野球における、三種の神器ですから！"
"80000126-65-レイ" = "実際に野球……とはいかずとも、これで雰囲気はバッチリです！"
"80000126-66-レイ" = "さぁ先生、ピッチャーをお願いします……！"
"80000126-67-レイ" = "野正レイ選手、大振りの構えから……ヒット！#n打球はショートの上を越えていきました！！"
"80000126-68-レイ" = "野正選手、速い！二塁まで行けるかっ！？#nおぉっと、ピッチャーの先生が迫りくる！"
"80000126-70" = "（その後二人で、三種の神器を美味しく食べた）"
"80000126-71" = "（チョコを頬張るレイは、ずっと目を輝かせながら野球の話をしてくれた）"
