[translation]
"3403-1" = "山海経のちょっと特別な朝（３）"
"3403-3-キサキ" = "……。"
"3403-4-ココナ" = "……。"
"3403-5" = "[ns] \"これは……いったい……？\""
"3403-6-キサキ" = "[ruby=わらわ]妾の[/ruby]記憶では、ココナ教官と梅花園の園児と共に、#n朝の体操をしようという話のはずじゃが……。"
"3403-7-梅花園の園児たち" = "ココナちゃん……？門主様……？#nこれ、どういう状況ですか……？"
"3403-24-レイジョ" = "カグヤ部長……？#nどうして京劇部がここに……？"
"3403-25-カグヤ" = "玄武商会のレイジョ様と、武術研究部こそ……何故こちらに……？"
"3403-26-レイジョ" = "――奇遇ですね。"
"3403-27-カグヤ" = "ええ――浮き草の如く世を彷徨い、劇的な[ruby=かいこう]邂逅[/ruby]を果たしました。#nまさに奇遇と言えるのでしょう……。"
"3403-28-レイジョ" = "ええと、私と武術研究部は、この公園に用事があるのですが。"
"3403-29-カグヤ" = "これはこれは、京劇部もそうなのですよ……なんという運命の悪戯でしょう。"
"3403-34-レイジョ" = "私、[ruby=かやま]鹿山[/ruby]レイジョ、および武術研究部一同は、本日より門主様のカンフー練習にお供します！"
"3403-35-カグヤ" = "我々京劇部は！本日より、門主様の京劇の稽古を全身全霊で手ほどき致します！"
"3403-36-レイジョ" = "え？"
"3403-37-カグヤ" = "はい？"
"3403-42-キサキ" = "……なっ？"
"3403-44-レイジョ" = "何か語弊があるようですが……門主様は毎朝ここでカンフーの練習をしているんですよ？"
"3403-45-カグヤ" = "いいえ！門主様が励んでいらっしゃったのは京劇の稽古です。#n正確には「京劇舞踊」ですが……"
"3403-47-キサキ" = "いや、妾はただ……。"
"3403-49-レイジョ" = "変な噂を耳にしたのでは？#n残念ですが、門主様はカンフーの練習をしておりました。"
"3403-50-カグヤ" = "[ruby=きょぶん]虚聞[/ruby]に惑わされているのはレイジョ様のほうでしょう？#n門主様は、京劇の稽古に励んでおりましたよ？"
"3403-52-ココナ" = "先生……？門主様……？"
"3403-54-レイジョ" = "勘違いをしているのは京劇部のほうではありませんか！#n門主様はたしかにカンフーの練習をしていました！"
"3403-55-レイジョ" = "――この目ではっきりと見ましたから！"
"3403-57-カグヤ" = "勘違い、と申しましたか？遺憾ですね。#nしかし、門主様は間違いなく京劇の稽古をしておられました。"
"3403-58-カグヤ" = "――私[ruby=うるしばら]、漆原カ[/ruby]グヤが、そのお姿をこの目に焼き付けているのです！"
"3403-60" = "[ns] \"あ、なるほどね。\""
"3403-61-レイジョ" = "遺憾も何も！あれは紛れもなくカンフーです！"
"3403-62-レイジョ" = "門主様のあのポーズは、相手の攻撃を受け流す[ruby=かけい]化勁[/ruby]の術そのもの！"
"3403-67-レイジョ" = "あれがカンフーでなければ、今まで武芸を極めてきた私や武術研究部の皆さんは、"
"3403-68-レイジョ" = "――今まで無意味な努力をしてきたという話になってしまいますよ！？"
"3403-76-カグヤ" = "（危ない……つい「ええ、無意味です」と口にするところでした……！）"
"3403-77-カグヤ" = "これは偶然ですね――いえ、必然と申しましょうか。#n[ruby=わたくし]私[/ruby]もレイジョ様と同じことを考えておりました。"
"3403-78-カグヤ" = "この身を京劇に捧げ、毎日過酷な鍛錬を続けて参りました。#n故に、自ずと分かるものです。"
"3403-79-カグヤ" = "あれが京劇でなければ、私を含む京劇部員は……"
"3403-80-カグヤ" = "無駄な時間を費やしたことになるのでしょう！"
"3403-86-レイジョ" = "（……はっ！つい、「無駄足でしたね」と言ってしまうところだった……）"
"3403-93-レイジョ" = "ですから、あれは京劇ではありません！"
"3403-96-カグヤ" = "それはこっちの台詞です！#nあれはカンフーではありません！"
"3403-98-レイジョ" = "カンフーですっ！"
"3403-99-カグヤ" = "京劇ですっ！"
"3403-103-キサキ" = "いや、どちらでもないのじゃが……。"
"3403-104-ココナ" = "門主様、別の方もいらっしゃってますよ……？"
"3403-105-キサキ" = "なんじゃと？"
"3403-117-山海経の生徒A" = "わあ！門主様がいらしてるよ！"
"3403-118-山海経の生徒B" = "まさか本当にお目にかかれるだなんて……！"
"3403-119-山海経の生徒A" = "って、あまり馴れ馴れしくしたら玄龍門に叱られちゃうかも？"
"3403-120-山海経の生徒B" = "うーん……ま、大丈夫じゃない？"
"3403-122-ミナ" = "「太陽が昇り沈む頃には、多くの人々が倒れるだろうが……此度は我々の番になるであろう……。」"
"3403-123-ミナ" = "門主様の居られるところに私あり――[ruby=このえ]近衛[/ruby]ミナ、ついて参ります！"
"3403-128-玄龍門の構成員A" = "……別に倒れた人いなくない？"
"3403-129-玄龍門の構成員B" = "しっ！それ言ったら、本当に何人かがぶっ倒れるかもしれないぞ……。"
"3403-131-ミナ" = "我ら玄龍門！馳せ参じました！"
"3403-132-ミナ" = "門主様がカンフーをしようと、京劇をしようと……！"
"3403-133-ミナ" = "玄龍門は最後まで、門主様と共に在ります！"
"3403-138-玄龍門の構成員A" = "ま、執行部長のことは置いといて……この隙に、門主様の可愛いお姿を写真に収めてっと……。"
"3403-147-玄龍門の構成員B" = "それ、あとでちょうだい。"
"3403-148-玄龍門の構成員A" = "5000円。"
"3403-149-玄龍門の構成員B" = "え、高すぎない？"
"3403-150-ミナ" = "コラ……静粛にっ！"
"3403-151-玄龍門の構成員A&B" = "は、はいっ！"
"3403-153-ルミ" = "やれやれ、まさかあの噂が本当だったとはねぇ……。"
"3403-154-ルミ" = "よっし！後でキサキに栄養たっぷりのお菓子でも作ってあげないと！"
"3403-155-キサキ" = "これは、一体……。"
"3403-162-キサキ" = "礼を言う、先生。つい気を失うところじゃった。"
"3403-163" = "[s] \"こうなった以上、仕方ないよ。キサキ。\""
"3403-164-キサキ" = "……それは、どういう意味じゃ？"
"3403-165" = "[s] \"ここに集まってる皆の期待に応えてあげよう！\""
"3403-166-キサキ" = "……！"
"3403-167-キサキ" = "それは、そうさな。"
"3403-170-レイジョ" = "カンフー！"
"3403-171-カグヤ" = "京劇！"
"3403-173-ミナ" = "門主様～"
"3403-175-キサキ" = "あの3人の期待には応えなくても良いと思うのじゃが……。"
"3403-176-レイジョ" = "……仕方ありません。#nこうなった以上、奥の手を使うしか。"
"3403-182-カグヤ" = "ええ、私も同じことを考えておりました。#n言葉が通じないのであれば、武力行使あるのみ……！"
"3403-188-レイジョ" = "お覚悟はよろしいですか？"
"3403-189-カグヤ" = "私どもを心配する余裕があるのですね？"
"3403-190-ミナ" = "ん？どこかで揉め事のニオイが……。"
"3403-192-キサキ" = "こほん……二人とも、聞くがよい。#n妾はただ、梅花園の園児と……ばんざい体操をするために来ているのじゃぞ……？"
"3403-193-レイジョ" = "ば、ばんざい体操……ですか？#nカンフーではなく？"
"3403-194-カグヤ" = "きょ、京劇の稽古ではなかったのですか……？"
"3403-196-ミナ" = "なるほど、体操だったのですね！"
"3403-197-キサキ" = "ああ、じゃから[ruby=そなた]其方[/ruby]たちも、これ以上の争いは――"
"3403-198-レイジョ" = "いえ、門主様！体操もまた、カンフーの練習に必要となります！"
"3403-199-レイジョ" = "ですので、私たちと共にカンフーの道を歩みましょう！"
"3403-200-カグヤ" = "ええ！京劇においても鍛錬は必須です。体操はその一種！"
"3403-201-カグヤ" = "門主様！お許しいただけましたら、門主様に京劇の真髄をお教えすると誓いましょう！"
"3403-202-レイジョ" = "京劇じゃないですってば！"
"3403-203-カグヤ" = "門主様もカンフーではないと言っていますよ！"
"3403-205-梅花園の園児たち" = "門主様ぁ……うっ……あのお姉ちゃんたち、怖いよぉ……。"
"3403-206-ココナ" = "み、みんな！泣いちゃダメだよ！"
"3403-210-ココナ" = "わ、私だって……怖くて……うぅぅ……。"
"3403-215-キサキ" = "…………。"
"3403-216-キサキ" = "――やめぬか！子供たちが怖がっておるじゃろう！"
"3403-219-レイジョ" = "！？"
"3403-220-カグヤ" = "！？"
"3403-221-ミナ" = "？"
"3403-222-キサキ" = "――其方らが何を成そうとも、妾はその意志を尊重する。"
"3403-223-キサキ" = "じゃが、それが山海経の未来である子供たちを脅かしてまで、語る必要があるとは思わぬ。"
"3403-224-キサキ" = "妾に……いや、子供たちの前で述べるがよい。#n其方らの意志と、山海経の未来……どちらがより大切なのか。"
"3403-226-レイジョ" = "も、門主様、私たちはただ……！"
"3403-227-カグヤ" = "た、大変申し訳ございません！門主様！"
"3403-229-キサキ" = "其方らの意志が子供たちの糧となり、未来への導きとなるのであれば#n――妾は玄龍門の名に懸けて、其方らを擁護する。"
"3403-230-キサキ" = "しかし――"
"3403-236-キサキ" = "仮にそれが、害となるのであれば――その時は、然るべき措置をとらねばならぬ。"
"3403-239" = "[ns] \"ふたりとも、少しは落ち着いた？\""
"3403-240-レイジョ" = "申し訳ございません、門主様……。"
"3403-241-カグヤ" = "門主様……どうかお許しを……！"
"3403-242-ルミ" = "さ、ここまでにしよっか。#n子供たちも怖がってるし。"
"3403-243-キサキ" = "なんじゃルミ。其方もおったのか……？"
"3403-244-梅花園の園児たち" = "うっ……うぅぅ……。"
"3403-246-ココナ" = "門主様……。"
"3403-251-キサキ" = "……もう大丈夫じゃ。#n大きな声を上げてすまなかったの。"
"3403-252-ココナ" = "は、はい……。"
"3403-253" = "[ns] \"ココナちゃん、はいハンカチ。\""
"3403-254-ココナ" = "……！い、いいんです！私はもう立派なレディーですから、鼻水なんて……！"
"3403-255-ココナ" = "あとココナちゃんじゃなくて、ココナ教官ですっ！"
"3403-256" = "[s] \"うん、そうだねココナ教官。\""
"3403-257-ルミ" = "それじゃ、みんなで一緒に朝の体操でも始めよっか？"
"3403-258-キサキ" = "い、一緒に……？"
"3403-260-ミナ" = "門主様とご一緒なら、何であろうと構いませんっ！"
"3403-261-ミナ" = "さあ！玄龍門よ！体操の準備だ！"
"3403-262-玄龍門の構成員A" = "大体予想はしてたけど……やっぱりこうなっちゃうのか……。"
"3403-263-玄龍門の構成員B" = "体操の準備って何をすればいいの……？"
"3403-264-キサキ" = "結局、皆の前でするのか……。"
"3403-265-ルミ" = "まあ、キサキだって分かってるでしょ。"
"3403-266-ルミ" = "たまには、こういう日も必要だよ。"
"3403-267-キサキ" = "……。"
"3403-268-キサキ" = "そうさな。其方の言う通りじゃ。"
"3403-269-キサキ" = "では、朝の体操で一日を始めるとしようかの。"
"3403-274" = "[ns] \"あ、急用を思い出したので、私は先に……。\""
"3403-276-キサキ" = "どこへ行こうというのじゃ？先生。"
"3403-277-キサキ" = "其方も、一緒にやるのじゃぞ。"
"3403-278" = "[s] \"やっぱりそうなるの！？\""
"3403-280" = "（そうやって、ちょっぴり慌ただしい山海経の朝が、元気よく始まるのであった）"
"3403-281" = "（風の噂によると……）"
"3403-282" = "（その日以降、白虎公園で体操をする生徒の数が増えたとか増えなかったとか……）"
"3403-283" = "山海経のちょっと特別な朝"
