[translation]
"2004206-1" = "年賀状"
"2004206-2" = "ミレニアム・スタディーエリア内のカフェ"
"2004206-4" = "（ユウカに領収書を預けた帰り道……）"
"2004206-8" = "（悩んでいる様子のマキがいた）"
"2004206-9-マキ" = "うーん……。"
"2004206-10" = "[s1] \"マキ、何してるの？\"\n[s2] \"考え事……？\""
"2004206-13-マキ" = "あ、先生。"
"2004206-14-マキ" = "ちょうど良いところに！"
"2004206-15-マキ" = "……先生は大人だから、年賀状いっぱいもらってるよね？"
"2004206-16" = "[s3] \"大人だからって多くもらうわけじゃないけど……。\"\n[s4] \"シャーレの仕事上、それなりに届いてるよ。\""
"2004206-19-マキ" = "充分だよ！"
"2004206-20-マキ" = "じゃあ、先生が今までもらった年賀状のなかで……。"
"2004206-21-マキ" = "一番印象に残ってるものは？"
"2004206-22" = "[s] \"うーん、何だろう……。\""
"2004206-24" = "[ns] \"って、どうして急に年賀状の話を？\""
"2004206-25-マキ" = "それがね、高校生なんだからお世話になった人に年賀状を書きなさいって、チヒロ先輩が言ってて。"
"2004206-26-マキ" = "行きつけの電気屋のオーナーさんとか他の部活とかに……。"
"2004206-27-マキ" = "でも、わざわざ手紙を送るのって非効率的じゃない？"
"2004206-28-マキ" = "普段メッセでやり取りしてるのに、#nどうして新年はみんな年賀状に拘ってるの？"
"2004206-29" = "[s5] \"もちろん、その考えも分かるけど……。\"\n[s6] \"手紙だからこそ伝わる気持ちもあるんじゃないかな。\""
"2004206-32-マキ" = "……そっか、たしかにそうだよね。#nでも、どういう年賀状を作ったら良いのか分からなくってさ。"
"2004206-33-マキ" = "なかなかインスピレーションが湧いてこないんだよね。"
"2004206-34" = "[s] \"可愛いデザインの年賀状なら、お店にも売ってるよ。\""
"2004206-35-マキ" = "それはダメ！"
"2004206-36-マキ" = "普通のデザインじゃ、注目されないじゃん。"
"2004206-37-マキ" = "やるとなったら、最高の年賀状にしないと！"
"2004206-38" = "[s] \"良い心構えだね！\""
"2004206-39-マキ" = "けど、年賀状について調べても、その年の感謝を伝えるとか、ありきたりの内容しか出てこなかったの。"
"2004206-40-マキ" = "感謝を絵にするって、どうしたら良いんだろ……。"
"2004206-41-マキ" = "先生は、どういう年賀状がカッコイイと思う？"
"2004206-42" = "[s7] \"デザインに正解はないけど……。\"\n[s8] \"マキの感謝と思い出を共有するためには……。\""
"2004206-45" = "[ns] \"今年一番記憶に残ってる出来事を絵にするのはどう？\""
"2004206-46-マキ" = "うーん……。"
"2004206-47-マキ" = "……そうだ！"
"2004206-52-マキ" = "ちょっと待ってて、先生！"
"2004206-61-マキ" = "……完成！"
"2004206-62-マキ" = "どうかな、先生……？"
"2004206-63" = "[s] \"素敵なデザインだね。\""
"2004206-65" = "[ns] \"あれ、もしかして……。\""
"2004206-66-マキ" = "これはね……。"
"2004206-67-マキ" = "先生と初めて描いたグラフィティだよ。"
"2004206-68-マキ" = "今年もたくさんグラフィティを描いてきたけど……。"
"2004206-69-マキ" = "やっぱり、一番印象に残ってるのは先生と過ごした時間だから。"
"2004206-70-マキ" = "あ、いや、その……変な意味じゃなくて！"
"2004206-71-マキ" = "ただ、先生にも感謝を伝えたかったの。"
"2004206-76-マキ" = "受け取ってくれる……？#nあたしの初めての年賀状。"
"2004206-77-マキ" = "……ふふっ。#n来年もよろしくね、先生。"
