[translation]
"10045040-1" = "第4話;第三回戦：水上障害物レース"
"10045040-2" = "悲鳴あふれる船旅も、やがて終わりを迎えた。"
"10045040-4-シズコ" = "さあ、第二回戦を突破した10人の選手をご紹介します～！"
"10045040-5-シズコ" = "皆さん、大きな拍手でお迎えください！"
"10045040-15-シズコ" = "ここまで残っているということは……その実力は疑うまでもありません！#nもはや誰が優勝してもおかしくない！この先の活躍も期待してます！"
"10045040-16-シズコ" = "それでは、しばらく休憩を挟んで、第三回戦でお会いしましょう！"
"10045040-17-シズコ" = "そしてここで……皆さんに耳寄りな情報を……。#nそろそろ、お腹が空いてくる頃じゃないですか～？"
"10045040-18-シズコ" = "そんな皆さんのために百夜堂出張版、海の家が朝からオープンしております！"
"10045040-19-シズコ" = "シズコが厳選したメニューをお手頃価格で楽しめるので、ぜひお立ち寄りください！"
"10045040-20-シズコ" = "それでは、お待ちしていま～す、にゃんにゃん！"
"10045040-21-シズコ" = "ふぅ……いい仕事した～"
"10045040-24-ナグサ" = "みんな……海の家で何か食べる？"
"10045040-25-レンゲ" = "アタシはパス……今は何も食べたくない……。"
"10045040-26-ナグサ" = "実は、私も……。"
"10045040-28-ユカリ" = "命がけでしたの……。"
"10045040-29-キキョウ" = "もう思い出したくもない……。"
"10045040-31" = "[ns1] \"全員突破おめでとう！\"\n[ns2] \"さすがは百花繚乱だね！\""
"10045040-34-ユカリ" = "あ、ありがとうございます……ですの……。"
"10045040-35-キキョウ" = "先生、次の種目は何？"
"10045040-36-キキョウ" = "（何であれ、水に入るのだけは避けたいけど……）"
"10045040-37" = "[ns] \"次はみんな大好き――\""
"10045040-39" = "[log]早い者勝ち！水上障害物レース！[/log]"
"10045040-43-キキョウ" = "……一難去ってまた一難ね。"
"10045040-45-シズコ" = "決勝戦に続く最後の関門！百夜水上祭の華！#nこれを待っていた方も多いでしょう！水上障害物レースのお時間です！"
"10045040-49-シズコ" = "ルールはシンプル！10人が一斉にスタートし、ゴールを突破した2名だけが決勝戦に進出できます！"
"10045040-50-シズコ" = "今回のコースに待ち受ける障害をご紹介しましょう！"
"10045040-51-シズコ" = "ぐるぐる回る足場！"
"10045040-52-シズコ" = "水風船が降り注ぐ坂道！"
"10045040-53-シズコ" = "浮き輪の飛び石ゾーン！"
"10045040-54-シズコ" = "どこに繋がるかは運しだいの滑り台！"
"10045040-55-シズコ" = "これらの障害を突破し、ゴールを目指してください！"
"10045040-57-キキョウ" = "……はぁ。"
"10045040-58-レンゲ" = "水に濡れたくないなら、落ちなきゃいいだけだろ？"
"10045040-59-キキョウ" = "当然、そのつもり。"
"10045040-60-キキョウ" = "（……そう。無理せず、適当にやり過ごして安全にゴールを目指す。#n水に落ちなければいいんだから）"
"10045040-62" = "一方、その頃……。"
"10045040-63-スケバンリーダー" = "くそっ、どうなってるんだ！？#nあいつら全員残ってるじゃないか！"
"10045040-64-スケバンリーダー" = "このままじゃ勝ち目がない！"
"10045040-65-アラタ" = "もう諦めようぜ……決勝に進めるのは二人だけなんだぞ。"
"10045040-66-スケバンリーダー" = "私たちが勝ちゃいいだけの話だろ！なんで諦めるんだよ！"
"10045040-67-アラタ" = "お前は知らないかもしれないけど……。"
"10045040-68-アラタ" = "正直、あいつら本当に強いんだよ。"
"10045040-69-アラタ" = "それに、優しくしてくれたこともあるし……ずっと目の敵にしてるのも悪い気がするんだよな。"
"10045040-71-スケバンリーダー" = "弱気になるな！まだチャンスはある！私の計画通りにやれば勝てる！"
"10045040-72-スケバンリーダー" = "くくっ……くくく……くくくくくっ……！"
"10045040-73-アラタ" = "う、うわ……なんか悪役っぽい笑い方なんだけど……。"
"10045040-74-スケバンリーダー" = "次こそ……次こそは……！"
"10045040-76" = "そしてしばらくして……。"
"10045040-77-シズコ" = "お待ちかね、水上障害物レースを始めます！"
"10045040-82-ナグサ" = "いよいよだね……。"
"10045040-83-レンゲ" = "アタシと決勝で戦うのは誰だろうな？"
"10045040-84-ユカリ" = "一緒にゴールして、全員で決勝戦進出ですの！"
"10045040-85-キキョウ" = "そんなこと、できるわけないでしょ。"
"10045040-88-キキョウ" = "（はぁ……）"
"10045040-89-キキョウ" = "（私は自然に脱落しておくのが一番かな）"
"10045040-90-キキョウ" = "（言い訳も用意しておいたし……）"
"10045040-91-キキョウ" = "（問題は、どうやって自然に脱落するか……考えなさい、キキョウ……！）"
"10045040-92-レンゲ" = "キキョウ。#n……キキョウ？"
"10045040-93-レンゲ" = "すごい考え込んでるな……。"
"10045040-94-シズコ" = "選手の皆さん！ スタートラインにお並びくださ～い！"
"10045040-101-シズコ" = "第三回戦、水上障害物レース……！"
"10045040-102" = "[ns] \"始めっ――！！\""
"10045040-105-シズコ" = "まずトップに躍り出たのは百花繚乱の四人！"
"10045040-106-シズコ" = "ぐるぐる回る足場がその行く手を阻みます！#n果たして無事に渡れるでしょうか～？"
"10045040-107-ナグサ" = "一思いに行くのがよさそうかな。"
"10045040-108-ユカリ" = "足場の回転よりも早く駆け抜ければ問題ないですの！"
"10045040-109-レンゲ" = "いつもの鍛錬に比べれば大したことないな！"
"10045040-110-キキョウ" = "（下は見ない。下は見ない。下は見ない……！）"
"10045040-112-シズコ" = "なんと！全員が一気に飛び越えました！"
"10045040-113-イズナ" = "サササッ！イズナも負けてはいられません！ニンニン！"
"10045040-114-チセ" = "しゅ～ん。"
"10045040-115-ミモリ" = "それっ。"
"10045040-119-シズコ" = "次々と障害を突破していきます！まったく差が開きません！"
"10045040-120" = "[ns] \"さすが、ここまで残った実力者たちですね！\""
"10045040-121-スケバンリーダー" = "いいぞいいぞ……そのままだ……そのまま行け！"
"10045040-122-スケバンリーダー" = "おい、ちゃんと指示通りにやったんだろうな？"
"10045040-123-アラタ" = "えっと……一応やってはあるんだけど……。"
"10045040-125-シズコ" = "水風船が降り注ぐ坂道に先頭集団が差し掛かりました！！#n当たらないように気をつけてくださいね～！"
"10045040-128-ナグサ" = "ここも一気に――"
"10045040-133-ナグサ" = "うっ……！？"
"10045040-137-ナグサ" = "何……？これ、滑るし、ベタつく……。"
"10045040-138-レンゲ" = "この匂い……ココナッツオイルか！？"
"10045040-139-ユカリ" = "こ、これでは坂道を登れませんの……！"
"10045040-142" = "[ns] \"シズコ？みんなオイルまみれになってるけど……。\""
"10045040-143-シズコ" = "あ、あれ！？そんなはずは……！"
"10045040-144-シズコ" = "スタッフさん、確認をお願いします！"
"10045040-146-スケバンリーダー" = "上手くいったな。これで一気に差をつけられるぜ！"
"10045040-147-アラタ" = "お先っ！"
"10045040-151-レンゲ" = "な、なんだそれ！？かぎ縄なんて、どっから出したんだよ！"
"10045040-152-アラタ" = "こうなることを見越して用意しておいたのさ！"
"10045040-153-アラタ" = "お前らはそこで仲良くベタベタしてるんだな！"
"10045040-157-ユカリ" = "なっ……！自分たちが使った後は縄を切り落とすなんて……卑怯ですの！"
"10045040-158-ミモリ" = "皆さん、まずはオイルを流しましょう！"
"10045040-159-イズナ" = "イズナがお手伝いします！#nイズナ流忍法！噴水の術！"
"10045040-165-キキョウ" = "結局、濡れる運命だったのね……。"
"10045040-166-レンゲ" = "追いかけるよ！まだまだ巻き返せる！"
"10045040-170-アラタ" = "嘘だろっ！？もう追いついてきたのか！"
"10045040-171-スケバンリーダー" = "大丈夫だ！この先にも仕掛けをしておいたからな！"
"10045040-173" = "[log]次のコース！[/log]"
"10045040-175" = "[log]浮き輪の飛び石ゾーン！[/log]"
"10045040-178-スケバンリーダー" = "浮き輪に爆弾を仕掛けてある。#n知らずに踏んだら爆発して海にドボンって寸法よ！"
"10045040-179-スケバンリーダー" = "安全なのは私だけが分かるように印を付けてあるんだ！"
"10045040-180-アラタ" = "な、なら先に行けよ！どれが安全か分かんねぇから！"
"10045040-186-レンゲ" = "さっきはよくもやってくれたな。"
"10045040-189-スケバンリーダー" = "まだまだ、こんなもんじゃ――"
"10045040-195-スケバンリーダー" = "……あれ？"
"10045040-199-アラタ" = "バカ！なんでお前が踏むんだよ……！！"
"10045040-205-アラタ" = "はぁ……。"
"10045040-209-シズコ" = "あーっと、先頭を走っていた二人がリタイアです！"
"10045040-210-シズコ" = "それにしても、誰が浮き輪に爆弾なんて仕掛けたんですか！"
"10045040-211" = "[ns] \"シズコじゃないの？\""
"10045040-212-シズコ" = "私がやるわけないでしょうが！"
"10045040-215-イズナ" = "爆発する足場があるなら、踏まずに通れば問題なし！"
"10045040-216-イズナ" = "イズナ流忍法！水上走りの術！"
"10045040-220-シズコ" = "な、なんと……！イズナ選手、水の上を走っています……！"
"10045040-221" = "[s] \"イズナなら5歩くらいはいける……！\""
"10045040-223-レンゲ" = "負けてられないな！アタシだって……！"
"10045040-224-キキョウ" = "ちょっと！そんな無茶な走り方をしたら……！"
"10045040-225-レンゲ" = "たかが爆弾ごときで、アタシを止められると思うなよ！"
"10045040-229-シズコ" = "おおっ！レンゲ選手も無事に突破しました！"
"10045040-230-レンゲ" = "ほらっ、キキョウも！"
"10045040-233-キキョウ" = "（レンゲが踏んだ浮き輪なら、問題ないはず……！）"
"10045040-240-キキョウ" = "……え？"
"10045040-248-キキョウ" = "（どうしてっ！）"
"10045040-249-キキョウ" = "（な、何がどうなったの……？ 足場を踏み間違えた……？）"
"10045040-250-キキョウ" = "（こんな大事な場面で……私がミスをするなんて……）"
"10045040-251-キキョウ" = "（はっ早く……上に……）"
"10045040-252-キキョウ" = "（でも……だんだん……意識が……）"
"10045040-254-キキョウ" = "（みんな……ごめん……）"
"10045040-256-レンゲ" = "……キキョウ？"
"10045040-257-レンゲ" = "キキョウ――！！"
