[translation]
"10045005-1" = "プロローグ;百花繚乱の親睦会"
"10045005-4" = "どこまでも澄んだ青い空に、じりじりと照りつける太陽。#n夏は、ここにある。"
"10045005-5" = "これは、友情と青春が織りなす、ひと夏の物語――"
"10045005-8-キキョウ" = "何やってるんだろう、私……。"
"10045005-9-キキョウ" = "部屋で兵法書を読みながら、のんびり過ごしてるはずだったのに。"
"10045005-10-キキョウ" = "どうして海に……。"
"10045005-11-ユカリ" = "先輩方と青い海！白い雲！そして爽やかな水着！#n身共がずーっと夢見てたしちゅえーしょんですの！"
"10045005-12-ユカリ" = "さぁ！のんびりしている場合ではありません！#n早く！早く波打ち際へ参りましょう！"
"10045005-13-キキョウ" = "私は遠慮しとく。"
"10045005-17-レンゲ" = "どうしたんだよ？キキョウも乗り気だっただろ？"
"10045005-18-キキョウ" = "親睦会には賛成したけど……海に来るなんて聞いてない。"
"10045005-20-ユカリ" = "キキョウ先輩は、海がお嫌いなのでしょうか……？"
"10045005-22-キキョウ" = "そ、そんなわけないでしょ。ただ――"
"10045005-23-キキョウ" = "私は、アウトドアが苦手なだけ。"
"10045005-29-ユカリ" = "いんどあ派ですものね、キキョウ先輩。"
"10045005-30-ユカリ" = "ですがここまで来ておいて、海で遊ばないなんて言語道断、ですの！"
"10045005-36-ユカリ" = "さあキキョウ先輩！いざ、参りましょう！"
"10045005-37-キキョウ" = "はぁ……。"
"10045005-38-レンゲ" = "まあまあ、それくらいにしとこう。#n無理に連れ出すのもよくないしさ。"
"10045005-39-レンゲ" = "アタシらは先に行ってるから、気が向いたらいつでも来いよ！"
"10045005-43-ユカリ" = "お待ちしておりますの！"
"10045005-47-キキョウ" = "はぁ……。"
"10045005-51-ナグサ" = "……ごめん。他の場所にすればよかったね。"
"10045005-52-キキョウ" = "いや、みんなは海に来たがってたし。"
"10045005-53-キキョウ" = "せっかく盛り上がってるのに、私の我儘で水を差すわけにはいかないでしょ？"
"10045005-54-ナグサ" = "ふふっ。そっか。"
"10045005-55-ナグサ" = "でも、準備運動くらいはしておいたほうがいいかも。"
"10045005-56-ナグサ" = "もうすぐ始まるから。"
"10045005-57-ナグサ" = "百鬼夜行の、夏の風物詩――"
"10045005-59" = "[log=나구사 수영복][ruby=ももよすいじょうさい]百夜水上祭[/ruby][/log]"
"10045005-65-キキョウ" = "（どこで間違えたの……？）"
"10045005-66-キキョウ" = "（お祭りに参加するつもりもなかったのに……）"
"10045005-67-キキョウ" = "（そもそも、泳げない私がどうして……！）"
"10045005-72-ナグサ" = "全員当選するとは思わなかったよね。#n参加するだけでも、すごい倍率だったのに。"
"10045005-73-キキョウ" = "そう。本当に予想外……。"
"10045005-74-キキョウ" = "（私だけでも落選して欲しかった……）"
"10045005-75-ナグサ" = "キキョウ？大丈夫？何か考え事？"
"10045005-76-キキョウ" = "……秘策を練ってたの。"
"10045005-77-キキョウ" = "華麗に、絶対的な勝利を掴む策を。"
"10045005-79-ナグサ" = "……そっか。"
"10045005-80-ナグサ" = "それじゃ、楽しみにしてるね。キキョウの考えた策。"
"10045005-81-キキョウ" = "（考えないと……。#n百花繚乱の作戦参謀の名に懸けて――）"
"10045005-85-キキョウ" = "（水を怖がってるなんて、絶対バレるわけにはいかない……！）"
