[translation]
"10045030-1" = "第3話;第二回戦：暴走ジェットボート"
"10045030-3-ナグサ" = "そろそろ機嫌なおしなよ。"
"10045030-4-ナグサ" = "気分転換に何か食べる？"
"10045030-5-キキョウ" = "……今はいい。"
"10045030-6-キキョウ" = "焼き鳥は後でにする。"
"10045030-7-ナグサ" = "……焼き鳥をあげるとは言ってないよ。"
"10045030-12-ナグサ" = "もぐもぐ。"
"10045030-14-キキョウ" = "食べながら言われても説得力ないんだけど……。"
"10045030-15-キキョウ" = "……やっぱり、私にも一本ちょうだい。"
"10045030-16-キキョウ" = "少しでも体力を回復しておかないと。"
"10045030-17-キキョウ" = "（ボートの上で耐えるにはどうすれば……）"
"10045030-18-ナグサ" = "はい、どうぞ。"
"10045030-19-ユカリ" = "この焼き鳥、絶品ですの！"
"10045030-20-レンゲ" = "一応、ボートを見ておかないか？#n焼き鳥なら食べ歩きもできるし。"
"10045030-25-レンゲ" = "あれかな？"
"10045030-29-ユカリ" = "こんなに豪快なボートに乗るのは初めてですの！"
"10045030-30" = "[ns1] \"一回戦突破おめでとう。\"\n[ns2] \"みんなも下見かな？\""
"10045030-33-キキョウ" = "このボート……本当に安全なの？"
"10045030-34-キキョウ" = "水に落ちたら、すぐに助けてもらえるんでしょうね？"
"10045030-35" = "[s3] \"うん。ライフセーバーが待機してるし、\"\n[s4] \"いざという時の備えはしてあるから安心してね。\""
"10045030-38-キキョウ" = "……だといいけど。"
"10045030-39-キキョウ" = "（泳げなくてもどうにか誤魔化せそう……）"
"10045030-41-レンゲ" = "なんだよ？落ちるのが怖いのか？"
"10045030-42-キキョウ" = "そ、そんなわけないじゃない。"
"10045030-43-キキョウ" = "作戦参謀の役目は、あらゆる状況に備えること。#nそれを忘れたわけじゃないでしょう？"
"10045030-44-キキョウ" = "それに、前の試合で私たちを妨害してきた連中もそのまま残ってる。"
"10045030-45-キキョウ" = "また何か仕掛けてくるかもしれない。"
"10045030-46" = "[s5] \"それはどうだろうね。\"\n[s6] \"自分のことで精一杯じゃないかな？\""
"10045030-49-キキョウ" = "……そもそも落ちないでいるのが難しいってことね。"
"10045030-50-ユカリ" = "それなら、こういうのはいかがでしょうか？"
"10045030-51-ユカリ" = "腕を組んで、安全バーをしっかり掴む！これで安心ですわ！"
"10045030-52-レンゲ" = "おっ、楽しそうだな！いいんじゃないか？"
"10045030-53-キキョウ" = "水着で密着なんて……。#nでも、他に方法はなさそうね。"
"10045030-55-ナグサ" = "私が一番左に座って、レンゲが一番右。"
"10045030-56-ナグサ" = "ユカリとキキョウは真ん中に座るのでどうかな。"
"10045030-58-レンゲ" = "ナグサ先輩が両腕を使えるからこその作戦だね！"
"10045030-59-キキョウ" = "まだ本調子じゃないって言ってなかった？"
"10045030-60-ナグサ" = "これぐらいなら、もう大丈夫。"
"10045030-61-ナグサ" = "ふふっ、見せてあげる……黄昏の影に眠りし真の力を。"
"10045030-62-キキョウ" = "本気で心配になるからやめて……。"
"10045030-64-ユカリ" = "ともかく、これで準備は万全ですわ！二回戦も全員で突破いたしましょう！"
"10045030-66" = "しばらくして……。"
"10045030-69-シズコ" = "さぁ！第二回戦の準備が整ったようです！"
"10045030-74-シズコ" = "予告通り、今回の種目は暴走するジェットボート！"
"10045030-75-シズコ" = "30人の選手が2台のジェットボートに分かれて乗り、最後の10人が残るまで無限にダイブとドリフトが繰り返されます！"
"10045030-76-シズコ" = "運転は次第に荒く……ワイルドになっていきますので、吹っ飛ばされないよう気をつけてくださいね、にゃんにゃん！"
"10045030-80" = "[ns] \"選手一同、乗船！\""
"10045030-82-ナグサ" = "作戦は覚えてる？腕を組んで安全バーをしっかり掴むこと。"
"10045030-83-ユカリ" = "はい！もちろんですの！"
"10045030-89-シズコ" = "準備はよろしいですね～？"
"10045030-90-シズコ" = "第二回戦、暴走ジェットボート……！"
"10045030-91" = "[ns] \"始めっ――！！\""
"10045030-96-レンゲ" = "うわっ！？速っ！？"
"10045030-100-ユカリ" = "きゃあああああああああぁぁぁぁっ！！"
"10045030-101-ナグサ" = "できるだけ密着して！支えあわないと……！"
"10045030-105-キキョウ" = "こんなデタラメな……！！"
"10045030-106-レンゲ" = "キキョウ！もっとしっかりアタシの身体に掴まれ……！"
"10045030-107-キキョウ" = "あり……がとう！"
"10045030-108-キキョウ" = "れ、レンゲの背中……意外と柔らかいのね。"
"10045030-109-レンゲ" = "こっち背中じゃないんだけど！？"
"10045030-110-キキョウ" = "あ……ごめん。"
"10045030-111-レンゲ" = "謝るなよ！"
"10045030-118-ユカリ" = "きゃあああああんっ！！"
"10045030-119-キキョウ" = "きゃっ……！#nユ……ユカリ、それ、私の尻尾……！"
"10045030-120-ユカリ" = "し、失礼いたしました！#nですが身共、手を離すと落ちて――"
"10045030-121-キキョウ" = "で、でも、そこは……っ！"
"10045030-122-ユカリ" = "申し訳ないですのおおお……！！"
"10045030-123-キキョウ" = "だ、大丈夫……どうにか耐えるから……ああっ……！"
"10045030-127-ナグサ" = "みんなの力を一つに……！"
"10045030-128-キキョウ" = "こんな形で一つになりたくはなかったんだけど……！"
"10045030-129-レンゲ" = "これが青春だーっ！"
"10045030-131-シズコ" = "次々と悲鳴が上がってます……！"
"10045030-132-選手A" = "誰だよ！こんな無茶苦茶な種目を考え――ブクブクブク。"
"10045030-133-選手B" = "ぎゃああああっ！！"
"10045030-138-シズコ" = "水しぶきを上げながら、続々と脱落者が出ております！"
"10045030-139-シズコ" = "最後まで、しっかり見届けてくださいね、にゃんにゃん！"
