[translation]
"90001120-1" = "第12話;提案"
"90001120-3-トキ" = "そういえばあの時、アリスが大活躍したと聞きます。"
"90001120-4-トキ" = "私が覚えているのは、全てが終わった後にゲーム開発部の皆さんが部室に来たことくらいですが。"
"90001120-5-トキ" = "パーティの提案、2キロバイトのデータ、ロボット型のキーホルダー、適切な雰囲気、感動的なBGM――そして私がメインヒロインになるまで。"
"90001120-6-トキ" = "色々ありました。"
"90001120-7-トキ" = "……ふっ。"
"90001120-8-ヒマリ" = "前半は分かりますが……後半は何ですか？"
"90001120-9-トキ" = "言ってみただけです。"
"90001120-16-エイミ" = "（最近なんかああいうのよく言ってくる気がする……）"
"90001120-17-ヒマリ" = "あの時、ウトナピシュティムの[ruby=もとぶね]本船[/ruby]からアリスが再構築した箱舟は――アリスの「勇者の証」そのものでした。"
"90001120-18-ヒマリ" = "ふふっ。今でも私が付けた名前を覚えています。#n「光の剣：アトラ・ハシースのスーパーノヴァ」。"
"90001120-19-リオ" = "あの時は言わなかったけど……貴女のネーミングセンス、少し変じゃないかしら？"
"90001120-20-ヒマリ" = "あなたにそんなこと言われたくありません！"
"90001120-21-エイミ" = "（懲りないな、この二人は……）"
"90001120-22-ヒマリ" = "こほん。"
"90001120-23-ヒマリ" = "ですが、問題が一つ。#n私たちはアリスが具体的に何をしたのか分かっていません。"
"90001120-24-ヒマリ" = "どのようなメカニズムで、どのプロセスを経て再構築したのか……知る由もなかったのです。"
"90001120-25-リオ" = "そうね……エネルギー源は何だったのか、物質の再構築はどのように行われたのか。"
"90001120-26-リオ" = "原理も何も分からなかった。理解する時間もなかった。"
"90001120-27-リオ" = "私たちにとっては、「一瞬の出来事」だったもの。"
"90001120-28-ヒマリ" = "つまり再現が非常に難しい……あるいは不可能に近いと言えるでしょう。"
"90001120-29-ヒマリ" = "一度きりの奇跡というのは、ロマンチックではありますが。"
"90001120-30-ヒマリ" = "だからこそ、理論や学問の敵でもあります。"
"90001120-31-リオ" = "そうね。学問は再現性があるプロセスだもの。"
"90001120-32-リオ" = "その過程を理解すれば、同じ結果が出せるように作られている。"
"90001120-33-リオ" = "……。"
"90001120-34-リオ" = "私は、アリスと直接話すべきだと思うのだけれど。"
"90001120-35-ヒマリ" = "それは……アリスをここに呼ぶ、と？"
"90001120-36-リオ" = "ええ。アリスに当時を分析、再現してもらうのよ。"
"90001120-37-ヒマリ" = "……本当にそれでいいのですか？"
"90001120-38-リオ" = "それ以外に方法があるのかしら？"
"90001120-43-ヒマリ" = "……アリスを問題解決の「道具」にする、とも解釈できるのだけれど。"
"90001120-44-リオ" = "……そうね。"
"90001120-45-トキ" = "……。"
"90001120-46-エイミ" = "会長……。"
"90001120-51-ヒマリ" = "リオ、二度は言いません。#n私たちは既に一度同じような話をしていますよね。"
"90001120-52-ヒマリ" = "その時はトキが対象で、今はアリス。"
"90001120-53-ヒマリ" = "もちろん清楚な崖の上の一輪の花は、あなたが後悔しようが気にしませんが……"
"90001120-54-ヒマリ" = "同じ過ちを繰り返す様を見せられるのは……愉快なことではありません。"
"90001120-55-リオ" = "そうね……。"
"90001120-56" = "[s] \"……。\""
"90001120-60" = "[ns] \"ねえ、リオ。\""
"90001120-61-リオ" = "……な、なにかしら？"
"90001120-78" = "[ns] \"本当にアリスが必要なのかな？\""
"90001120-79-リオ" = "ごめんなさい。私も100％の確信はないの。#n……可能性の一つと思ってもらって構わないわ。"
"90001120-80-リオ" = "今の話は一旦忘れてちょうだい。#n私の考えが正しいとは限らないもの。"
"90001120-81" = "[s] \"……私がアリスとゲーム開発部に話をしてみるよ。\""
"90001120-82-リオ" = "せ、先生！？"
"90001120-83-ヒマリ" = "先生！？"
"90001120-84-エイミ" = "え、先生？どうしたの？"
"90001120-85-トキ" = "本当に大丈夫なのですか？#nそれは、捉え方によっては……。"
"90001120-90-リオ" = "この事態が……特殊だから？#nそれは……そう、だけれど……。"
"90001120-91-ヒマリ" = "アリスにその言葉を伝えるのは、先生の仕事……？"
"90001120-92" = "[s] \"その代わり、リオに提案したいことがあるんだ。\""
"90001120-93-リオ" = "私に……？"
"90001120-94" = "[s] \"リオも氷河の拠点に来てほしい。\""
"90001120-95-ヒマリ" = "！？"
"90001120-96-エイミ" = "会長が、直接！？"
"90001120-97-トキ" = "先生、それは一体……？"
"90001120-99-リオ" = "……。"
"90001120-100-リオ" = "「一緒に責任を負う姿勢」ということかしら……？"
"90001120-101" = "[s] \"その判断は、リオに任せるよ。\""
"90001120-105" = "[ns] \"リオが提案してくれたように。\""
"90001120-109" = "[ns] \"私も、提案しただけだから。\""
"90001120-110-リオ" = "……。"
"90001120-111-リオ" = "分からないわ、先生。#n私は……。"
"90001120-112-リオ" = "私にそんな資格があるのか……。#nまた、間違えてしまうのではないか……。"
"90001120-116-トキ" = "……今回リオ様は私たちを助けてくださりました。"
"90001120-118-ヒマリ" = "……。"
"90001120-123-トキ" = "私にはリオ様の言う「正しさ」がどこにあるのかよく分かりません。#n常に間違わない選択が果たして可能なのか。"
"90001120-124-トキ" = "ですが私は……リオ様にもう一度会いたいです。"
"90001120-125-トキ" = "そんな理由では、ダメなのでしょうか？"
"90001120-126-リオ" = "トキ……。"
"90001120-132-ヒマリ" = "リオ。#n今度はあなたが選ぶ番です。"
"90001120-133-ヒマリ" = "あなたの判断基準は理解しています。#nそれは文字通り「合理」といえるでしょう。"
"90001120-134-ヒマリ" = "あなたの合理的な判断の結論を教えて下さい。"
"90001120-138-リオ" = "…………。"
"90001120-139-リオ" = "そうね……通信だけでは限度がある。#nセキュリティの面でも、安全の面でも。"
"90001120-140-リオ" = "電波が妨害されてしまったら全てが狂う可能性もあるわ。#n今回もそうだったように。"
"90001120-141-リオ" = "だから、私は……。"
"90001120-142-ヒマリ" = "はい、決まりですね。"
"90001120-143-ヒマリ" = "では、私たちも氷河の拠点に向かいますので、そこで落ち合いましょう。"
"90001120-144-リオ" = "……わかっ、たわ。"
"90001120-146-エイミ" = "リオ会長……何か気になることでもあるの？"
"90001120-147-リオ" = "そういうわけでは、ないのだけれど……。"
"90001120-148-リオ" = "本当に、私が行っても良いのかしら……？"
"90001120-149-ヒマリ" = "……。"
"90001120-150-ヒマリ" = "氷河拠点の座標を送信します。#n移動手段は……まあ、あなたならとっくに用意しているのでしょう？"
"90001120-151-リオ" = "……ええ。"
"90001120-152-トキ" = "久しぶりにお会いできるのを楽しみにしております、リオ様。"
"90001120-153-リオ" = "トキ。"
"90001120-154-トキ" = "はい。いかがされましたか？"
"90001120-160-リオ" = "今までお疲れ様。#nそして……ありがとう。"
"90001120-161-トキ" = "とんでもございません。"
"90001120-164" = "（皆がそれぞれのことで忙しい中、たまたま一人の時間ができた）"
"90001120-165" = "（せっかくだから……）"
"90001120-171-アロナ" = "あれ？先生？"
"90001120-172-プラナ" = "おかえりなさい先生。どうかされましたか？"
"90001120-173-アロナ" = "え？私たちの顔が見たくなった？"
"90001120-174-アロナ" = "そ、それはとても嬉しいですけど……えへへ……。"
"90001120-175-アロナ" = "でも、何かあったなら言ってくださいね。"
"90001120-176-プラナ" = "肯定。顔色が悪いです。#nもう一度聞きますが、何かありましたか？"
"90001120-177" = "[s] \"私ってそんなに顔に出てる……？\""
"90001120-178-アロナ" = "今までどれだけ一緒にいたと思ってるんですか？"
"90001120-179-アロナ" = "顔に出さないようにしたって、私たちにはわかりますよ！"
"90001120-180-プラナ" = "肯定。今の先生は、知らないかもしれませんが。"
"90001120-181-プラナ" = "私が知っている先生は、そういう方でした。"
"90001120-182-アロナ" = "さあさあ、アロナが何でも聞きますよ！"
"90001120-183-プラナ" = "私もです。"
"90001120-184-アロナ" = "あ、はい。プラナちゃんも！"
"90001120-188" = "[ns1] \"……問題解決を生徒にお願いするのがちょっとね。\"\n[ns2] \"生徒を危険に晒すのが辛いんだ。\""
"90001120-191-アロナ" = "先生……。"
"90001120-192-プラナ" = "……。"
"90001120-193-アロナ" = "で、でも先生！"
"90001120-194-アロナ" = "先生は今までも……何度も、同じような状況を解決してきたじゃないですか！#nとか言ってみたり……えへへ。"
"90001120-209" = "[ns] \"あの時とは少し違う気がするんだ。\""
"90001120-211-アロナ" = "え？あの時は、既に起こったことを、何とかするために動いてたけど……"
"90001120-212-プラナ" = "今回は、先生のせいで生徒が危険に晒されるかもしれない、と。"
"90001120-213-プラナ" = "納得。ですが、それが最善策なのですよね？"
"90001120-216" = "[ns3] \"そうだね……。\"\n[ns4] \"でも、そのせいで生徒たちが危険な目に遭うのなら。\""
"90001120-221" = "[ns] \"私は、彼らと何が違うんだろうなって。\""
"90001120-224-アロナ" = "……。"
"90001120-225-プラナ" = "……。"
"90001120-227" = "[ns] \"あぁ、もう！急にめっちゃくちゃ強くならないかな！\""
"90001120-228-アロナ" = "せ、先生？"
"90001120-229-プラナ" = "理解不能。急にどうされたんですか、先生。"
"90001120-230" = "[s5] \"いや、その……ほら！\"\n[s6] \"空も飛べたり？バリアだって何だって、全部突破して！\""
"90001120-234" = "[ns7] \"名もなき神だのデカグラマトンだのぜーんぶ！\"\n[ns8] \"一気に解決できる能力が私にあったら良かったな……って！\""
"90001120-238-アロナ" = "ど、どうしたんですか……？"
"90001120-239-プラナ" = "混乱。理解できません。詳細な説明を要求します。"
"90001120-243" = "[ns] \"ごめん、大丈夫。言ってみただけだから。\""
"90001120-253" = "[log]生徒たちを……よろしく、お願いします。[/log]"
"90001120-259" = "[ns] \"やるしかないか……よし！\""
"90001120-261" = "[ns9] \"やれること全部やって！最後まで足掻いて！\"\n[ns10] \"それでもダメだったら！\""
"90001120-264-アロナ" = "だ、ダメだったら？"
"90001120-268" = "[ns11] \"……この話はまた今度ね！\"\n[ns12] \"まだどうなるか分からないからね！\""
"90001120-271-アロナ" = "せ、先生？本当に大丈夫……ですよね？"
"90001120-272-プラナ" = "疑問、困惑。先生のメンタルチェックを要請します。"
"90001120-273" = "[s] \"大丈夫！大丈夫！\""
"90001120-278-アロナ" = "な、撫でてくださるのは嬉しいですけど……あうぅ……。"
"90001120-279-プラナ" = "混乱。先生の意図が分かりません。"
"90001120-281" = "（そうしてずっと二人を撫でて）"
"90001120-282" = "（眠りについたのを確認してから、そっと離れた）"
"90001120-284" = "次回;出発"
