[translation]
"52085-15-ナグサ" = "はぁ、はぁ……。"
"52085-16-ナグサ" = "……まだまだ！"
"52085-21-シュロ" = "しっつこいなぁ……ナグサちゃんのくせに。"
"52085-22-シュロ" = "さっさと切り上げるつもりだったんですけどぉ――"
"52085-29-キキョウ" = "ナグサ先輩！"
"52085-30-レンゲ" = "……って、なんだよこれ！"
"52085-31-ユカリ" = "先輩！大丈夫ですの！？"
"52085-36" = "[ns] \"ナグサ、無事！？\""
"52085-37-ナグサ" = "私は大丈夫、それより花鳥風月部の怪談家が……。"
"52085-38-シュロ" = "くそっ、もう嗅ぎつけましたか。"
"52085-42-ユカリ" = "あの子……。"
"52085-43-レンゲ" = "あの時の生意気チビだ！"
"52085-48-シュロ" = "誰が生意気チビですってぇ！？ "
"52085-49-シュロ" = "くっそぉ……あと少しなのに……！"
"52085-50-シュロ" = "……しょうがないですねぇ。#nでも、手前さん方がこの地に足を踏み入れたからには、#n物語を再開する機会はまだあるはず。"
"52085-54-シュロ" = "それではそれでは、今日はこの辺りでお暇させていただきますぅ。"
"52085-59-レンゲ" = "逃がすかっ！"
"52085-60-キキョウ" = "レンゲ、ユカリ。今度こそ捕まえるよ！"
"52085-80-ユカリ" = "なんてすばしっこいんですの！"
"52085-81-レンゲ" = "くっそー、イタチかあいつは……！"
"52085-86-シュロ" = "ふふん♪#nそぉんな動きじゃ、何年かかっても手前を捕まえられませんよぉ～？"
"52085-87-シュロ" = "それではぁ、次にお会いする日ま――"
"52085-93-シュロ" = "えっ……？"
"52085-99-シュロ" = "うぎゃあああっ！"
"52085-108-？？？" = "……いいタイミングだったみたいだね。"
"52085-109-？？？" = "みんな、ケガは？"
"52085-113-ナグサ" = "うそ……。"
"52085-114-キキョウ" = "この声……。"
"52085-121-？？？" = "久しぶりだね、ナグサ。"
"52085-125-アヤメ" = "それにみんなも。会えて嬉しいよ。"
"52085-131-ナグサ" = "……アヤメっ！"
"52085-133" = "次回;百花繚乱の委員長"
