[translation]
"52135-2" = "（一方、同時刻の「彼岸邸」の前では……）"
"52135-11" = "[ns1] \"やっぱり出たか……。\"\n[ns2] \"先にこっちに来るとはね……。\""
"52135-14-アザミ" = "……付喪神！？"
"52135-15-アザミ" = "先生、私の後ろに！"
"52135-20-シュロ" = "イヒヒッ……。"
"52135-23-シュロ" = "あはっ……アハハハッ……。"
"52135-24-シュロ" = "アハハハハハハハッ！！"
"52135-25-シュロ" = "ざまぁないですぅ！コクリコ様はぜぇんぶ分かってたんですよぉ！？"
"52135-26-シュロ" = "手前らが変な模様を頼りに「彼岸邸」に来るのも、百物語は百蓮でしか倒せないことも！"
"52135-27-シュロ" = "ちょーっと手前が怖がって見せたら、先生をほっぽって散り散りになるなんて！"
"52135-28-シュロ" = "花鳥風月部を罠にかけたですってぇ？"
"52135-29-シュロ" = "蛇の口に手を突っ込んでるとも知らないでぇ！イヒヒヒッ！"
"52135-30" = "[s] \"……シュロ。\""
"52135-34-シュロ" = "何です、シャーレの先生？今になって命が惜しくなりましたぁ？"
"52135-35-シュロ" = "もう誰も助けてくれませんよぉ。"
"52135-36-シュロ" = "おとなしく黄昏に食われてくださいねぇ。[ruby=・]あ[/ruby][ruby=・]っ[/ruby][ruby=・]ち[/ruby]で、生徒たちの相談に乗ってあげてくださぁい。"
"52135-37" = "[s] \"……本当に、さっきのは演技だったの？\""
"52135-38-シュロ" = "……っ！"
"52135-39-シュロ" = "演技だって言ってるでしょ！手前が怖がってたとでも！？"
"52135-40-シュロ" = "何でも知ったようなこと言って、吐き気がする！とっとと百物語の餌になってください！"
"52135-44-シュロ" = "ほら、さっさと[ruby=や]撃[/ruby]るんですよぉ！"
"52135-55-シュロ" = "え……？"
"52135-56-シュロ" = "怪談の百物語が……手前を……？"
"52135-57-シュロ" = "う、うそ……だぁ……そんな……コクリコ様ぁ……。"
"52135-67-シュロ" = "ぐずっ……ぞんなわげないぃ……。"
"52135-73" = "[ns3] \"どういうこと……？\"\n[ns4] \"なんで百物語がシュロを撃ったの？\""
"52135-76-アザミ" = "……花鳥風月部の内輪で、何かあったのでしょうか？"
"52135-77-アザミ" = "それより、今のシュロさんは百物語を扱えないようです。"
"52135-78-アザミ" = "今、攻撃を受けたら……。"
"52135-79-アザミ" = "彼女が黄昏に……。"
"52135-80-アザミ" = "自業自得……かもしれませんが。"
"52135-81" = "[s] \"……行ってくるよ。\""
"52135-85-アザミ" = "ほ、本気ですか？"
"52135-86-アザミ" = "百物語は消えましたが、まだ危険です。"
"52135-87-アザミ" = "「彼岸邸」は敵地のままですし……。"
"52135-88-アザミ" = "あの子は、あなたを殺そうとしていたんですよ？"
"52135-89-アザミ" = "そんな無謀な――"
"52135-91" = "[ns5] \"危険な目に遭ってる子がいるなら、助けなきゃ。\"\n[ns6] \"判断はその後だよ。\""
"52135-100-アザミ" = "はは……。"
"52135-104-アザミ" = "なんとなく、そう仰ると思ってたんですけどね。"
"52135-109-シュロ" = "はぁ……はぁ……はぁ……。"
"52135-112-シュロ" = "（うそだ、うそだ、うそだ……！）"
"52135-113-シュロ" = "（ほんとに……手前は捨てられたの？）"
"52135-114-シュロ" = "（二度も失敗して、コクリコ様が怒っちゃった……？）"
"52135-115-シュロ" = "（だから百物語が、手前を……）"
"52135-116-シュロ" = "（そんなのイヤだ！コクリコ様がいなきゃ、手前はまた……）"
"52135-129-シュロ" = "やだ……やめてぇ……。"
"52135-130-シュロ" = "もう捨てられたくない……あんなとこ、戻りたくないよぉ……。"
"52135-137-シュロ" = "……と、とまれぇっ！！"
"52135-146-シュロ" = "……え？"
"52135-147" = "[s] \"間に合って……よかった。\""
"52135-148-シュロ" = "……シャーレの先生？"
"52135-149-シュロ" = "なんで飛び出して……？"
"52135-150" = "[s] \"助けにきたよ。\""
"52135-151-シュロ" = "でも……。"
"52135-152-シュロ" = "手前は……手前を殺そうとしたのに……。"
"52135-153-シュロ" = "な、なにを勘違いしてるんですかぁ！？"
"52135-154-シュロ" = "そんなことで、手前がいい子になるとでも！？"
"52135-155" = "[s7] \"危険に陥った子を助けるのに理由はいらない。\"\n[s8] \"人として、当然のことだよ。\""
"52135-160-シュロ" = "ふざけたことを……！"
"52135-161-シュロ" = "手前が、手前らとは違って銃弾一発で倒れるのくらい、知ってますよぉ！"
"52135-162-シュロ" = "なのに……なのに、自分だけじゃなく、生徒たちまで黄昏に食わせようとした敵を助けるなんてぇ！？"
"52135-163-シュロ" = "……バカなんですかぁ！？"
"52135-164" = "[s] \"大丈夫だよ、シュロちゃん。私は意外と丈夫だから。\""
"52135-168-シュロ" = "誰がシュロちゃんっ――"
"52135-169" = "[s] \"でも、やっぱり痛いね……。\""
"52135-173-シュロ" = "……は？"
"52135-181-レンゲ" = "師匠ーっ！"
"52135-186-アザミ" = "ああ、皆さんもご無事でしたか！"
"52135-187-アザミ" = "さ、先ほど百物語が現れて……。"
"52135-188-キキョウ" = "わかってる。"
"52135-189-キキョウ" = "……[USERNAME]先生は無事？"
"52135-190-アザミ" = "あの……先生は――"
"52135-191-アザミ" = "百物語に襲われたシュロさんを追っていきました……。"
"52135-195-アザミ" = "私も止めたのですが……。"
"52135-197-レンゲ" = "だからって、師匠を一人で行かせたのかよ？"
"52135-198-レンゲ" = "力ずくでも――"
"52135-204-レンゲ" = "キキョウ！？"
"52135-205-レンゲ" = "そ、そこまでしなくても……。"
"52135-206-キキョウ" = "アヤメ委員長ばかり気にしてた。"
"52135-207-キキョウ" = "どこかに花鳥風月部が潜んでるとは思ったけど……。"
"52135-211-キキョウ" = "こんな近くにいたなんてね。"
"52135-217-アザミ" = "……あはっ。"
"52135-221-アザミ" = "……どうして分かったのですか？ "
"52135-223" = "次回;花鳥風月部の怪芸家"
