[translation]
"52150-1" = "第15話;甘い夢の終わり"
"52150-7-アヤメ" = "ふあぁ……。"
"52150-12-ナグサ" = "どうしたの？あんまり寝れてない？"
"52150-13-アヤメ" = "うーん……夢を見たからかな？"
"52150-15-ナグサ" = "……悪い夢？"
"52150-16-アヤメ" = "そんなことない。いい夢だったよ。"
"52150-17-アヤメ" = "山積みの依頼もなくて、急な事件も起きたりしない、平和な世界……。"
"52150-22-ナグサ" = "じゃあ、なんでそんなに辛そうなの……？"
"52150-26-アヤメ" = "悪い夢は、覚めたら終わり……。"
"52150-27-アヤメ" = "でも、幸せな夢から覚めたら、現実と向き合わなきゃいけない。"
"52150-28-アヤメ" = "夢が恋しくなって、現実を否定したくなるのが辛い……。"
"52150-29-アヤメ" = "……って、なんかの映画で言ってた！"
"52150-31" = "いつも、アヤメの言う通りだね……。"
"52150-32" = "悪夢より、幸せな夢の方が苦しい。"
"52150-33" = "あれが夢なら……いっそ、永遠に……。"
"52150-49-？？？" = "……起きたみたいだね。"
"52150-55-ナグサ" = "……アヤメ？"
"52150-56-アヤメ" = "[ruby=・]久[/ruby][ruby=・]し[/ruby][ruby=・]ぶ[/ruby][ruby=・]り[/ruby]。ナグサ。"
"52150-57-ナグサ" = "ここは……。"
"52150-61-ナグサ" = "他のみんなは……？それに[USERNAME]先生は？"
"52150-62-アヤメ" = "大丈夫。隣の部屋にいるよ。"
"52150-63-アヤメ" = "みんな無事だよ。シャーレの先生は眠ってるけどね。"
"52150-67-ナグサ" = "今まで一緒にいたアヤメは……？"
"52150-68-ナグサ" = "それに「久しぶり」って……。"
"52150-69-アヤメ" = "「あれ」は、恐怖を餌とする百物語が作り出した何か。"
"52150-70-ナグサ" = "私はあの姿に、恐怖なんて……。"
"52150-71-アヤメ" = "そう？「あれ」はあなたの心が生んだのに。"
"52150-75-アヤメ" = "……本当は、とっくに気づいてたんでしょ？"
"52150-76-アヤメ" = "これは、いつか消えてしまう夢だって。それに、残酷な現実はすぐ目の前にあるってことも。"
"52150-78-ナグサ" = "そ、そんなこと……知らな……。"
"52150-82-アヤメ" = "もうたくさん！"
"52150-83-アヤメ" = "いつもいつもいつも言い訳して！誰かに頼って！"
"52150-84-アヤメ" = "いつまで続けるの？"
"52150-87-アヤメ" = "……ああでも、あの幻の言ったことは本当だよ？#n実際、私は限界を感じてクズノハ様を探しに行ったんだからね。"
"52150-88-アヤメ" = "「他人の欲望」に疲れてたんだ……あの時の私は。"
"52150-91-アヤメ" = "私はね、大嫌いだったんだよ……。"
"52150-92-アヤメ" = "一人じゃ何もできないからって、誰かに縋りつく連中が。"
"52150-93-アヤメ" = "偉そうに口では労うけど、また重荷を押しつけてくる奴らが。"
"52150-94-アヤメ" = "何かあると、すぐに泣き出すあんたが……。"
"52150-98-アヤメ" = "本当に、嫌いだった。"
"52150-102-アヤメ" = "でも、百花繚乱の委員長として「この現実」は守りたかった。だからクズノハ様を探しに行ったけど……そこにあったのは、何の役にも立たないおとぎ話だけ。"
"52150-103-アヤメ" = "だから、決めたの。百鬼夜行の大預言者がおとぎ話なら――#n怪書を使って、[ruby=ほんもの]現実[/ruby]にしてやるんだって。"
"52150-104-アヤメ" = "そして、私はみんなを見守る目を貰うんだ……。"
"52150-105-ナグサ" = "ダメだよ、アヤメ……きっとコクリコに騙されてるんだ。"
"52150-106-アヤメ" = "あんたには一生分からないよ。"
"52150-107-アヤメ" = "私がどんな気持ちで、みんなに笑顔を向けてたのか。"
"52150-108-ナグサ" = "そんなことない……そんなことないよ。今からでも話――"
"52150-112-アヤメ" = "よく言うよ。"
"52150-113-アヤメ" = "私から目を背けて、都合の良い「あれ」と楽しく過ごしてたくせに。"
"52150-114-ナグサ" = "アヤメ、私は……。"
"52150-115-アヤメ" = "言ったでしょ？"
"52150-116-アヤメ" = "私はあんたを――"
"52150-121" = "友達だと思ったことなんて、ない。"
"52150-126" = "次回;造花"
