[translation]
"1801-1" = "正義実現委員会はお休みです（１）"
"1801-2" = "トリニティ総合学園・近辺の廃工場"
"1801-3-トリニティの女子生徒" = "きゃぁっ！"
"1801-5-デコボコヘルメット団A" = "騒ぐな！言うことを聞かないと大変なことになるぞ！"
"1801-6-トリニティの女子生徒" = "あ、あなたたち、いったい誰ですか？何の目的でこんなことを……！"
"1801-7-デコボコヘルメット団B" = "トリニティのお嬢さんが、それを知ってどうするつもりだ？"
"1801-8-デコボコヘルメット団A" = "あんたはあの学園が身代金を支払うまで、ここで大人しく捕まってればいいんだよ。余計なことは考えるな！"
"1801-9-トリニティの女子生徒" = "が、学園と交渉を！？"
"1801-10-デコボコヘルメット団A" = "そうだ！もう連絡はしてある、あんたのところの生徒を返してほしかったら、ってね！"
"1801-11-トリニティの女子生徒" = "だ、ダメ、逃げて……いえ、逃げてください……！！"
"1801-12-デコボコヘルメット団A" = "は？"
"1801-13-デコボコヘルメット団B" = "急に何を……"
"1801-15" = "ドカアアァァン！！"
"1801-16-デコボコヘルメット団A" = "ひ、ひいいっ！？"
"1801-17-デコボコヘルメット団A" = "な、なんだ！？何が起きた！？"
"1801-19-？？？" = "くっ、くくくっ、くひっ……。"
"1801-21-？？？" = "くひひひひひひひひひ！！"
"1801-22-デコボコヘルメット団A" = "う、うわあああ！？"
"1801-23-トリニティの女子生徒" = "き、来てしまいました……！"
"1801-25-ツルギ" = "きええええええええっっっ！！！！"
"1801-28" = "救護騎士団・中央病棟"
"1801-29-ハスミ" = "……お加減はいかがですか？"
"1801-30-セリナ" = "幸いにも、こちらの生徒たちは相手方ほど酷い状態ではありませんが……。"
"1801-31-セリナ" = "何人[ruby=心的外傷後ストレス障害]かはPTSDの可[/ruby]能性がありますから……3週間ぐらいは病院で安静にしてもらった方が良いかと。"
"1801-32-ハスミ" = "……そうですか。"
"1801-33-ハナエ" = "セリナ先輩、戻りました！"
"1801-34-ハナエ" = "市外の病院まで、デコボコヘルメット団の方々をしっかり搬送してきました！"
"1801-35-ハナエ" = "みなさん飲み物の缶をぺちゃんこに潰したみたいになっちゃってましたし、処置するの大変だったんですよー。"
"1801-36-ハナエ" = "あれって、正義実現委員会のツルギさんの――"
"1801-37-セリナ" = "ハナエちゃん。"
"1801-39-ハナエ" = "あっ、す、すみません……。"
"1801-42-ハスミ" = "……では、引き続きよろしくお願いします。"
"1801-43-セリナ" = "はい、お任せください。"
"1801-45-ハスミ" = "ふぅ……。"
"1801-46-マシロ" = "お疲れ様でした、先輩。"
"1801-47-マシロ" = "次は、倒壊した建物から一緒に人質を救出してくださった「シスターフッド」にご挨拶を……。"
"1801-48-ハスミ" = "……そうでしたね。そこにも寄らなくては……。"
"1801-49-マシロ" = "その後は、損害賠償請求を処理してくれた行政室にも行かないとですね。"
"1801-50-ハスミ" = "そうですね……。"
"1801-51-マシロ" = "弾丸の使用数がかなり多かったので、部活動統括本部にも念のため報告を……。"
"1801-52-ハスミ" = "……。"
"1801-53-マシロ" = "……ある程度は、仕方のないことだと思います。被害をゼロにできるわけでは……。"
"1801-54-ハスミ" = "それはそうなのですが……。"
"1801-55-ハスミ" = "なんだかツルギが、落ち込んでいる気がしていまして……。"
"1801-56-マシロ" = "……それも、いつものことではないですか？"
"1801-57-ハスミ" = "それもそうなのですけど……。"
"1801-58-ハスミ" = "ん……？"
"1801-59-マシロ" = "どうしましたか？"
"1801-60-ハスミ" = "えっと、ティーパーティーから動画が送られてきましたね。"
"1801-61-マシロ" = "ティーパーティー！？"
"1801-63-ナギサ" = "こんにちは、正義実現委員会のみなさん。事の顛末は聞きました、お疲れ様です。"
"1801-64-ナギサ" = "救出自体は成功……ただし、人質だった生徒たちも全員が入院。"
"1801-65-ナギサ" = "その内の何人かは、任務中のツルギさんのあまりの恐ろしさを目にしてPTSDの可能性もある、と……。"
"1801-66-ナギサ" = "……。"
"1801-67-ナギサ" = "こういった状況を踏まえて、少し考えてみました。"
"1801-68-ナギサ" = "今の皆さんに必要なものは何か、と。"
"1801-69-ナギサ" = "結論としまして、やはり必要なのは「交流」かと思います。"
"1801-70-ナギサ" = "交流と言いますか、正確には常識と……心温まる、愛のある交流、でしょうか。"
"1801-71-ナギサ" = "今の正義実現委員会のみなさんに必要なのは、そういったものかなと。"
"1801-72-ナギサ" = "そこで考えつきました。明日一日、正義実現委員会はお休みにしましょう。"
"1801-73-ナギサ" = "その代わりに、学園の他の部活やサークル、委員会に参加してください。"
"1801-74-ナギサ" = "その交流によって、きっと常識や愛を理解できることでしょう。間違いありません。"
"1801-75-ナギサ" = "ふふ、楽しみですね？"
"1801-76-ナギサ" = "それでは、明日は良い一日を。"
"1801-78-ナギサ" = "あっ、ちなみにこれは強制力のある決定事項ですので。例外もありません。"
"1801-80-ハスミ" = "……。"
"1801-81-マシロ" = "……これ、どういう意味ですか？他の部活に……？"
"1801-82-ハスミ" = "はあ、またこういう……。"
