[translation]
"1007305-1" = "最後の一口まで"
"1007305-5" = "（夜の海辺に、ぼんやりと立ち尽くすウイの姿があった）"
"1007305-10-ウイ" = "……あ、先生。こちらです。"
"1007305-16-ウイ" = "こんなに早いとは。#n実はモモトークを送ってから、少し後悔していました。"
"1007305-17-ウイ" = "本当に、大した用ではないんです。#nただ、少し散歩がしたい……そう、思っただけで。"
"1007305-18-ウイ" = "……なのに、先生は二つ返事で私のところへ。"
"1007305-19-ウイ" = "その、代わりと言っては何ですが……"
"1007305-23-ウイ" = "……ご一緒に、いかがですか？"
"1007305-24" = "[s1] \"もちろん、喜んで。アメリカーノだね。\"\n[s2] ウイのカップを受け取る。"
"1007305-31" = "（アメリカーノを片手に、ウイと海辺を歩く）"
"1007305-34-ウイ" = "……聖徒会も、こんな素敵な場所をよく見つけたものです。"
"1007305-38-ウイ" = "融通の利かない、堅苦しい組織だとばかり思っていましたが……"
"1007305-39-ウイ" = "そうとは限らないのかもしれませんね。"
"1007305-40-ウイ" = "ふふっ……"
"1007305-41-ウイ" = "……？"
"1007305-42-ウイ" = "先生、どうかしましたか？そ、そんなに見つめられると……"
"1007305-43" = "[s3] \"今日のウイは、いつもより表情が柔らかいね。\"\n[s4] \"無人島にも慣れてきた？\""
"1007305-48-ウイ" = "えっと……はい。"
"1007305-49-ウイ" = "なので……勇気を出して、先生にご連絡したのです。"
"1007305-50-ウイ" = "それに……"
"1007305-51-ウイ" = "……もう、陽も落ちましたし。"
"1007305-52-ウイ" = "周りには誰もいない、静かな場所。#nこれだけ暗ければ、人目を気にする必要も、ないですから。"
"1007305-53-ウイ" = "私にとっては、これ以上ない環境です。"
"1007305-54-ウイ" = "……なんて、今のセリフだけ切り取れば、[ruby=おとぎばなし]御伽噺[/ruby]に出てくる吸血鬼のような。"
"1007305-55-ウイ" = "ふふっ。わざわざ説明しなくても、お見通しでしたよね……先生には。"
"1007305-56-ウイ" = "先生は、いろいろな生徒と面識がありますから――"
"1007305-57-ウイ" = "その中には、きっと……#n自分に自信が持てず、他人の目が気になって仕方がない小心者もいたはずです。"
"1007305-58-ウイ" = "……私が特別だとは、思っていません。"
"1007305-59" = "[s5] \"でも、ウイはウイだよ。\"\n[s6] \"小心者だとは思わないかな？\""
"1007305-64-ウイ" = "……そう、なんですか？"
"1007305-65-ウイ" = "なるほど……"
"1007305-66-ウイ" = "先生に言われると、自然に受け止められるような……。"
"1007305-67-ウイ" = "……それに私は、小心者というより、気難しいと言った方が近いかもしれません。"
"1007305-68-ウイ" = "いえ、別に卑下しているわけではないので。#nただ、事実には違いありませんし、その自覚はあります。"
"1007305-69-ウイ" = "意図的に、そう振る舞っている時もありますし……"
"1007305-70-ウイ" = "そうすれば、私のパーソナルスペースに入ってくる人は減りますから。"
"1007305-71-ウイ" = "……ですが、最近はどうもそれが機能していない気がして、困っています。"
"1007305-75-ウイ" = "…………。"
"1007305-76-ウイ" = "……誰、とは言いませんけれど。"
"1007305-77-ウイ" = "それとも、言葉にした方が良いでしょうか？"
"1007305-78" = "[s7] \"あはは、ウイも大変だね。\"\n[s8] \"またまた、そんなご冗談を。\""
"1007305-81-ウイ" = "……はぁ、わざとらしいですね。知ってましたけど。"
"1007305-82-ウイ" = "私としては、取り繕った会話は苦手ですし……むしろ助かるので構いませんが。"
"1007305-83-ウイ" = "先生のことですから、そばに居てくれるのにも、きっと意味があるのでしょう？"
"1007305-84-ウイ" = "おかげで私も、少し……少しずつ、変わっていけるような気がしています。"
"1007305-85-ウイ" = "……ですが、振り回されてばかりいるつもりは無いですよ。"
"1007305-86-ウイ" = "た、たまには……その、甘えたりして……"
"1007305-87-ウイ" = "……先生に、仕返しを。"
"1007305-88-ウイ" = "たとえば……こんな風に、2人だけの時間を作っていただいたり。"
"1007305-89-ウイ" = "……うぅ。"
"1007305-90-ウイ" = "よくもまぁこんな面倒くさい事を言えたもので……ああぁ……最悪……"
"1007305-91-ウイ" = "……私に捕まってしまうなんて、先生は運がありませんね。"
"1007305-92" = "[s9] \"最後まで、先生として責任を取るから。\"\n[s10] \"いつでも、そばで見守ってるよ\""
"1007305-95-ウイ" = "……はぁ。またそんなことを。"
"1007305-96-ウイ" = "こ、この話は終わりにしましょう……。"
"1007305-97-ウイ" = "はじめにも言いましたが……今日は、少し歩きたかっただけですし。"
"1007305-98-ウイ" = "そのカップ、まだ残っていますよね。"
"1007305-99-ウイ" = "何も話さなくて良いので……"
"1007305-103-ウイ" = "せめて、それを飲み終わるまでは……"
"1007305-104-ウイ" = "すこし、歩きませんか……"
"1007305-105-ウイ" = "……いいですよね？"
"1007305-109" = "[ns11] カップに口をつける。\n[ns12] 小さな歩幅で歩き出す。"
"1007305-112-ウイ" = "……ふふっ。"
"1007305-114-ウイ" = "……悪くないですね。"
