[translation]
"1203-1" = "Maid&Made（２）"
"1203-4-アカネ" = "先輩、少しじっとしててください。髪型が崩れてしまいます。"
"1203-5-ネル" = "もう何なんだよほんと……本末転倒って言うんじゃねぇのかこれ……。"
"1203-7-ネル" = "もともとは、正体を隠すためにメイド服を着てたはずじゃ……。"
"1203-8-カリン" = "そうは言っても、契約にサインをした以上は正当な依頼。私たちはそれを遂行するだけだ、仕方ない！"
"1203-9-ネル" = "……カリン、お前何か楽しそうだな？"
"1203-10-カリン" = "いや、その……まぁ。"
"1203-11-カリン" = "それはそうと、何で先輩はそんなにだらしない格好で……。"
"1203-12-ネル" = "仕方ねぇだろ。ここに来る途中、またチンピラたちがぞろぞろと……！"
"1203-13-アカネ" = "はいはい、大人しくしてくださいね～。せっかくの可愛い三つ編みが崩れちゃいますよ？"
"1203-14-ネル" = "別にしてもらわなくても、自分で出来るって言ってんだろうが、ったく……。"
"1203-18-アカネ" = "ネル先輩が自分でやると、ぐしゃぐしゃにするからダメです。今日はちゃんとしたメイドさんなんですから。"
"1203-19-アカネ" = "もうすぐ終わりますから、少しだけそのままにしててくださいね～……。"
"1203-20-アカネ" = "……先輩。せっかくなので今日くらい、スカジャンは置いておきません？"
"1203-21-ネル" = "るせぇ、これは脱がねぇよ。"
"1203-22-ネル" = "脱ぐくらいなら帰る。"
"1203-23-アカネ" = "ふふっ、分かりました。ですがやっぱりせっかくなので、髪型くらいは可愛く綺麗にしておきましょう？"
"1203-24-ネル" = "はぁ……。"
"1203-25-ネル" = "……勝手にしろ。"
"1203-26-アカネ" = "ふふっ、では遠慮なく……。"
"1203-29-アカネ" = "はい、終わりです。ふふっ、やっぱり素晴らしいですね。"
"1203-30-ネル" = "素晴らしいって何だよ、あたしはいつも通りだぞ……。"
"1203-31-カリン" = "そんなことはない。それに、いつもよりさらに綺麗になってる。"
"1203-32-アカネ" = "そうですよ。"
"1203-33-アカネ" = "普段から素敵ですが、今日は私も頑張りましたから。"
"1203-34-アカネ" = "ですがまだ未熟ですね……本当は、もう少し部長の魅力を引き出せる気がするのですが……。"
"1203-35-ネル" = "ああもう終わり！この話ストップ！"
"1203-39-ネル" = "ところでコールサイン・ゼロワン……"
"1203-40-ネル" = "じゃなくて、アスナのやつどこ行った？"
"1203-51-アスナ" = "おっ待たせー！準備はできた？"
"1203-53-ネル" = "てめぇはどこほっつき歩いてたんだよ……。"
"1203-54-アスナ" = "え、私？"
"1203-55-アスナ" = "客引きしてって言われたから、お客さん連れてきたんだよ？"
"1203-56-ネル" = "……は？"
"1203-57-カリン" = "先輩……客引きっていうのは、普通お店を開いた後にやることで……。"
"1203-62-カリン" = "って、何だかものすごい数のお客さんが……！？"
"1203-64-アカネ" = "あらあら……アスナ先輩、一体どんな手を使ったんですか？"
"1203-65-アスナ" = "え、特に何も？"
"1203-66-アスナ" = "ただメイドカフェを開きますよーって言っただけ！"
"1203-67-カリン" = "……ああ、なるほど。思い出した、他のカフェが真っ当じゃないからか……。"
"1203-68-アカネ" = "だからこうして、普通に見えるメイドカフェでもここまで殺到する、ということですか。"
"1203-69-アカネ" = "ふふっ、ある程度は覚悟していましたが……"
"1203-70-アカネ" = "今日は一日、忙しくなりそうですね？"
"1203-71-カリン" = "よし、素早く標的……"
"1203-72-カリン" = "じゃなくて、今日限定のご主人様たちを処……接客するとしよう！"
"1203-73-アカネ" = "……カリン。テンションが高いのは良いですけど、お客さんたちの前でその噛み方はやめてくださいね？"
"1203-75-ネル" = "ほんとにテンション高ぇなお前……。"
"1203-76-アスナ" = "もう準備OK？ドア開けちゃって良い？"
"1203-77-ネル" = "ちょっと待て、今更だがマジであたしも接客すんのか？「おかえりなさいませ」とか言わねぇとダメなのか！？ちょっと心の準備を――"
"1203-79-アスナ" = "始めれば何とかなるって！じゃあオープンっ！！"
"1203-85-アスナ" = "おかえりなさいませ～！！"
"1203-96" = "（それから、一週間後……）"
"1203-101-ユウカ" = "信じられない……。"
"1203-102-ユウカ" = "これ、本当に一週間で稼いだ金額……？"
"1203-103-ユウカ" = "もしかして、もっと上手くやれば……。"
"1203-107-ユウカ" = "……あ、ごめんなさい。こうしてる場合じゃないわね、まずはありがとう。"
"1203-108-ユウカ" = "依頼だったとはいえ、電気街とセミナーを代表して感謝するわ。"
"1203-109-ユウカ" = "もう全然赤字なんて問題じゃないし、これだけあれば最近のあなたたちの任務で発生した損害も補填できちゃいそう。"
"1203-110-アカネ" = "それは良かったです、だから今日はそんなに嬉しそうだったんですね。"
"1203-111-ユウカ" = "な、なによ、別に私だっていつも不機嫌ってわけじゃ……良いことには良いって言うし、助けてもらったら感謝くらいするわよ。"
"1203-112-ユウカ" = "ただ……。"
"1203-113-アカネ" = "……ただ？"
"1203-114-ネル" = "あんだよ、ちゃんとやったのにまだなんか文句あんのか？"
"1203-115-ユウカ" = "い、いやそうじゃなくて！"
"1203-116-ユウカ" = "何て言えば良いのか、その……。"
"1203-117-ユウカ" = "勿体ないって言うか、別の意味で損失っていうか……。"
"1203-118-カリン" = "……？なにか他にあるのか？"
"1203-119-ユウカ" = "えっと、じゃあ……。"
"1203-127-ユウカ" = "その、C&Cのリーダーであるネル先輩に、折り入ってご相談なのですが……"
"1203-129-ネル" = "いっ、"
"1203-130-ネル" = "何だその言い方気持ち悪ぃ……！？"
"1203-131-ユウカ" = "その、"
"1203-132-ユウカ" = "せっかくだし、可愛かったし、えっと……。"
"1203-139-ユウカ" = "……もう全員エージェントやめて、これから正式にメイドとして活動するとか、どうかしら？"
"1203-144-ネル" = "……はぁっ！？"
"1203-149-アカネ" = "……え？"
"1203-150-カリン" = "今、なんて……？"
"1203-152-ユウカ" = "その、会計を担当している身としては、このレベルの金銭的な貢献はかなり助かるって言うか……。"
"1203-153-ユウカ" = "せっかくだし、今後の他の商店街のお祭りも、ミレニアムの学園祭も……"
"1203-154-ユウカ" = "それ以前に、そもそもミレニアム専属メイドとして普段から、とか……。"
"1203-158-アカネ" = "あらあら……。"
"1203-159-カリン" = "……なるほど。"
"1203-161-ユウカ" = "ど、どう？良いと思わない？すっごく似合ってたし、悪くない話だと思うけど……？"
"1203-167-ネル" = "……。"
"1203-168-ネル" = "……………………。"
"1203-169-ユウカ" = "えっと、ネル先輩……？"
"1203-170-ネル" = "……ふ、"
"1203-175-ネル" = "ふっざけんな！！！誰がやるか！！ぶっ飛ばすぞてめぇっっっ！！？！？"
"1203-180" = "Maid&Made"
