[translation]
"10052153-8-ユズ" = "あ……うぅ……ううぅぅ……。"
"10052153-9-ユズ" = "どっ、どうすれば……！？"
"10052153-12-ミドリ" = "リオ会長！このままじゃユズちゃんが……！"
"10052153-13-モモイ" = "なにか必殺技とかないの！？"
"10052153-14-リオ" = "必殺技……。"
"10052153-18-リオ" = "ユズ！今からネオアバンギャルド君のリミッターをすべて解除するわ！#nそれと――"
"10052153-19-リオ" = "「貴女専用」の[ruby=Battle Gear]戦闘装備[/ruby]を、今インストールするわ！"
