[translation]
"10014025-10-スケバンA" = "う、ううっ……な、なんだ……"
"10014025-11-スケバンB" = "急に……不意打ち、だと……。"
"10014025-16-？？？" = "ハッハッハー！トリニティの審判者、[ruby=うざわ]宇沢[/ruby]レイサから隠れることなどできません！"
"10014025-17-スケバンA" = "あんなに恥ずかしいセリフを……最悪だ……。"
"10014025-18-スケバンB" = "しかも毎回中身違うし……さっきはみんなの騎士だって……。"
"10014025-20-スズミ" = "……支援要請を受けて駆けつけましたが、一人で全部解決してしまったのですね。"
"10014025-21-スズミ" = "まあ……これもレイサさんらしくはありますが……"
"10014025-23-レイサ" = "……あ、スズミさん！！"
"10014025-24-レイサ" = "すみません。#nどうしてもタイミングが遅れそうだったので先に入ってしまいました！"
"10014025-25-レイサ" = "ですが、スズミさんが来てくれると言ってくださったおかげで勇気が出ましたから！"
"10014025-26-レイサ" = "やっぱりスズミさんがいると違いますね！#nまさにトリニティの走る閃光弾！！"
"10014025-27-スズミ" = "そ、そうですか……。#nそれならとりあえず良かったのですが……。"
"10014025-28-スズミ" = "あと、その呼び方はもうやめてください……。#nお願いします……。"
"10014025-29-レイサ" = "あれ？#n……ところでその方は？"
"10014025-30-レイサ" = "うーん……。#n以前どこかでお会いしたことがあったような……？"
"10014025-31" = "[s1] \"やあ、レイサ。\"\n[s2] \"この前も会ったね。\""
"10014025-32-レイサ" = "……！#nやっぱりそうですよね！思い出しました！"
"10014025-33-レイサ" = "……！#nやっぱりそうですよね！思い出しました！"
"10014025-34-レイサ" = "悪党、[ruby=きょうやま]杏山[/ruby]カズサに捕まっていた方ですね？#n大丈夫でしょうか？何かされてませんか？"
"10014025-35" = "[s3] \"捕まってた？\"\n[s4] \"カズサが……悪党？\""
"10014025-36-スズミ" = "レイサさん、先に挨拶を。#nこの方はシャーレの先生です。"
"10014025-37-スズミ" = "レイサさん、先に挨拶を。#nこの方はシャーレの先生です。"
"10014025-38-レイサ" = "……え？先生？#nシャーレの？"
"10014025-39-レイサ" = "あれ、何か思い出せそうな気も……。"
"10014025-40" = "[s5] \"改めて挨拶するね。こんにちは、レイサ。\"\n[s6] \"私がシャーレの先生だよ。\""
"10014025-41-レイサ" = "あ、こんにちは……。#n私はトリニティの騎士、宇沢レイサと申します……？"
"10014025-42-レイサ" = "あ、こんにちは……。#n私はトリニティの騎士、宇沢レイサと申します……？"
"10014025-43-スズミ" = "ちょうど私たちもその件でここに。#nレイサさん、今お時間大丈夫ですか？"
"10014025-44-スズミ" = "どうも、杏山カズサさんに関して、少し誤解があるようで……"
"10014025-45-レイサ" = "……はい？"
"10014025-46-レイサ" = "誤解……って、何の事ですか？"
"10014025-50-レイサ" = "え……まさか……。"
"10014025-52-レイサ" = "もしかして……あの人、実は杏山カズサじゃなかったとか……！？"
"10014025-54-スズミ" = "いえ、そんな話ではなく……"
"10014025-55-レイサ" = "……いや！"
"10014025-56-レイサ" = "いやいやいやいや！#nそんなわけないですよ！"
"10014025-57-スズミ" = "……！？"
"10014025-58-レイサ" = "スズミさん、私の目は正確です。#nあの人は杏山カズサ本人ですよ！"
"10014025-59-レイサ" = "いくら昔と違う雰囲気だとしても、私の目を欺くことはできません。#n絶対です！"
"10014025-60-レイサ" = "そもそも、見た目では隠しきれない「獣のオーラ」が出てますから！"
"10014025-62-レイサ" = "そうじゃないですか？……先生！？#nあの人は杏山カズサですよね！？"
"10014025-63" = "[s7] \"カズサではあるけど……。\"\n[s8] \"獣……？\""
"10014025-64-レイサ" = "ほら！私の言う通りです！#n私に分からないわけがないのです！"
"10014025-65-レイサ" = "ほら！私の言う通りです！#n私に分からないわけがないのです！"
"10014025-66-レイサ" = "スズミさん、私は知っているんです。"
"10014025-69-レイサ" = "あの人は……杏山カズサは……"
"10014025-72-レイサ" = "かつて不良生徒たちを震え上がらせた神話！！"
"10014025-74-レイサ" = "泣くスケバンも泣き止むという恐怖の怪猫「キャスパリーグ」！！"
"10014025-78-レイサ" = "同時に、中学時代の私が……。"
"10014025-79-レイサ" = "唯一倒せなかった最凶のスケバン！"
"10014025-80-レイサ" = "そう……"
"10014025-81-レイサ" = "私の「宿敵」！！"
"10014025-83-スズミ" = "キャスパリーグだなんて、また大げさなあだ名を……。"
"10014025-84-スズミ" = "それよりも、レイサさん。#nまずは落ち着いて先生のお話を……。"
"10014025-85-レイサ" = "ある日突然姿を消し、誰もその行方を知らなかったというのに……！"
"10014025-86-レイサ" = "なのにまさか！！#nこんな場所で再起のチャンスを図っていたなんて……！！"
"10014025-87-レイサ" = "スズミさん！先生！！このままでは、杏山カズサが……キャスパリーグが復活してしまいます！！#n再びこの一帯が暗黒に染まってしまいますよ！！"
"10014025-88-レイサ" = "つまりこれは使命！！#n彼女を止めなければならないという、私の使命です！！"
"10014025-89-スズミ" = "待ってくださいレイサさん。#n今、先生はあなたのその考えが誤解だと言っているんです。"
"10014025-93-レイサ" = "……はい？"
"10014025-94-レイサ" = "誤解……とは、どういうことでしょうか？"
"10014025-95-レイサ" = "杏山カズサはもうスケバンでは、ない……？"
"10014025-96-レイサ" = "……えっ？"
"10014025-97-レイサ" = "今は普通に学園生活を送っている……？"
"10014025-98-レイサ" = "……杏山カズサが、ですか？"
"10014025-102-レイサ" = "……あの杏山カズサが？"
"10014025-103" = "[s9] \"うん、そのカズサが。\"\n[s10] \"あんまり信じられないかな。\""
"10014025-104-レイサ" = "そ、そんなわけありません！やっぱり……あり得ないですよ！？#n本当に……？どうして……？"
"10014025-105-レイサ" = "そ、そんなわけありません！やっぱり……あり得ないですよ！？#n本当に……？どうして……？"
"10014025-106-レイサ" = "で、でもこのようにスズミさんと先生が仰るというのは……"
"10014025-107-レイサ" = "……え……？#nあれ？あれれ……？"
"10014025-108-スズミ" = "よくわかりませんが、そんなに納得しづらいのでしょうか……。"
"10014025-109-レイサ" = "そ、そりゃあ……スズミさんは杏山カズサを知らないのですから……。"
"10014025-110-レイサ" = "あの杏山カズサですよ！？キャスパリーグですよ？"
"10014025-111-レイサ" = "誰にも止められない獣ですよ！！"
"10014025-112-レイサ" = "そんな存在が……普通に学園生活を……？"
"10014025-113" = "[s11] （レイサにとってカズサのイメージは……）\n[s12] （そんなに……獰猛なんだ）"
"10014025-114-レイサ" = "……で、ですが、他でもないお二人がそう仰るなら……。"
"10014025-115-レイサ" = "……で、ですが、他でもないお二人がそう仰るなら……。"
"10014025-116-レイサ" = "……その……。"
"10014025-117-レイサ" = "ご、ごめんなさい。#n今、正直少し混乱してて……考える時間を頂いてもいいですか……？"
"10014025-118" = "[s13] \"もちろん。いつでも連絡してね。\"\n[s14] \"ゆっくり考えて大丈夫だよ。私たちを信じて。\""
"10014025-119-レイサ" = "あ、は、はい……。"
"10014025-120-レイサ" = "あ、は、はい……。"
"10014025-121-レイサ" = "それでは、私はこれで……。"
"10014025-128-スズミ" = "……行ってしまいましたね。"
"10014025-129-スズミ" = "でも、どうにか誤解が解けたみたいで良かったですね。"
"10014025-130" = "[s] \"何か今……。\""
"10014025-132" = "[ns] \"レイサ、ちょっと元気なさそうだったね。\""
"10014025-133-スズミ" = "そうですか……？#nすみません、私にはあまり……。"
"10014025-137-スズミ" = "……先生？"
