[translation]
"10014070-1" = "第7話;我ら「放課後スイーツ団」"
"10014070-8-レイサ" = "はぁ、はぁ……。#nこれはこれは……"
"10014070-9-レイサ" = "いつも私から行ってましたから、こんなに歓迎されると少し困っちゃいますね。"
"10014070-10-レイサ" = "残念な事に、こんなにたくさんの方が私に用があるなんて初めてですから……！#nはは……"
"10014070-14-スケバンA" = "マジでしつこいな……いつまで粘る気なんだよ、こいつは！！"
"10014070-15-スケバンB" = "こんなに打たれ強いから、決闘だのなんだのやっても大丈夫だったんだな……#n純粋にすげえ。"
"10014070-16-スケバンA" = "なに関心してんだよ！しっかりしろ、敵だぞ！？"
"10014070-17-スケバンC" = "時間がねぇ。いくら郊外っつっても、ずっと騒いでたら見つかっちまう。"
"10014070-18-スケバンC" = "人が来る前にキャスパリーグの事を聞き出さねえとな！"
"10014070-19-スケバンB" = "ああ、そうだな。"
"10014070-20-スケバンB" = "お前ら銃を持て！！あいつが話すまで続けるぞ！！"
"10014070-25-レイサ" = "だから、教えられないって……言ってるのに……はは……"
"10014070-26-レイサ" = "みんなのヒーロー[ruby=うざわ]宇沢[/ruby]レイサが、キャスパリーグのために戦う日がくるなんて……#n不思議なものです。"
"10014070-27-レイサ" = "本当、長生きしてみるもんですね。"
"10014070-28-レイサ" = "――私まだ15歳ですけど。"
"10014070-29-レイサ" = "……まあ、いいでしょう。#n朝まで……勝負を続けましょうか……"
"10014070-30-レイサ" = "私、は……一日中でも、できます……からね……"
"10014070-31-？？？" = "……その割には、声に覇気がないね。"
"10014070-32-レイサ" = "……？"
"10014070-33-レイサ" = "……ん？#n空耳でしょうか……聞き覚えのある声が……。"
"10014070-34-？？？" = "だから前にも言ったじゃん。#nしつこすぎるのは微妙だって。人の話、ちゃんと覚えてよ。"
"10014070-38-レイサ" = "はは……まさか、キャスパリーグの幻聴まで聞こえるとは……"
"10014070-39-レイサ" = "私、内心かなり寂しかったみたいです……心が弱いですね。"
"10014070-40-スケバンC" = "な、何だ？誰の声だ？#nどこから聞こえてきた？"
"10014070-41-レイサ" = "……？"
"10014070-42-レイサ" = "あれ……？"
"10014070-43-スケバンA" = "あっちだ！！#n壁の後ろから今……"
"10014070-44-スケバンA" = "……？"
"10014070-50-スケバンB" = "……！！"
"10014070-51-スケバンB" = "！！！#n全員離れろ！！爆弾だ！！"
"10014070-56-スケバンA" = "ゲホ、ゲホゲホ……！#n急に爆発させやがって……！"
"10014070-57-スケバンB" = "おい！！お前ら大丈夫か？ケガは？"
"10014070-58-スケバンA" = "ああ、まあ……何とか……。"
"10014070-59-スケバンC" = "誰だよこんな事したの……！"
"10014070-62-カズサ" = "……うん、よし。"
"10014070-63-カズサ" = "ここで正解だったみたいだね。"
"10014070-64-カズサ" = "宇沢……"
"10014070-65-カズサ" = "ん……？"
"10014070-68-カズサ" = "あ……"
"10014070-69-カズサ" = "……あれ？"
"10014070-70" = "[s1] \"爆発の衝撃で気絶しちゃったみたい。\"\n[s2] \"よかった、怪我はしてないみたい。\""
"10014070-71-カズサ" = "……うん。"
"10014070-72-カズサ" = "……うん。"
"10014070-75-スケバンC" = "んだ、コラァ！なんだお前？#n今のお前の仕業か！？"
"10014070-76-スケバンB" = "ぶっ飛ばされてぇのか！？アァ！？#n何してくれてんだよ？私たちが誰か分かってんのか？ゴラァ！"
"10014070-80-スケバンB" = "ア？んだよ、こいつ。#nもしもーし！聞こえますかぁ？言葉話せない系？"
"10014070-84-スケバンB" = "……なんだ？"
"10014070-85-スケバンB" = "このちっこいの……"
"10014070-95-ナツ" = "……実に無礼だな。"
"10014070-96-ナツ" = "君らこそ、このお方が誰だか分かっているのか？"
"10014070-97-ナツ" = "このお方こそ、その爪を隠し潜伏していた暗黒街の女帝。"
"10014070-98-ナツ" = "まもなく復活を遂げ、この一帯を支配する恐怖の魔獣……"
"10014070-102-カズサ" = "……！？"
"10014070-103-カズサ" = "い、いや！ちょっと！！ナツ！#nコラ！！やめて、お願い……！"
"10014070-110-ヨシミ" = "いいよ！"
"10014070-115-ヨシミ" = "ほら、もっとやっちゃいな！"
"10014070-121-ヨシミ" = "ナツ最高ー！"
"10014070-125-ナツ" = "……恐怖の魔獣。"
"10014070-126-ナツ" = "……「キャスパリーグ」様だ！！！"
"10014070-128-スケバンA" = "キャ、キャスパリーグ……！？#nキャスパリーグだって！？本当に！？"
"10014070-129-スケバンC" = "や、やっぱり噂は本当だったんだ……#nほら見ろ！本当だって！！"
"10014070-131-ナツ" = "そして私たちは彼女の手下である「放課後スイーツ団」の四天王！！"
"10014070-132-アイリ" = "……え……？あれ？#n四天王？"
"10014070-133" = "[s3] \"私まで含めてっぽいね。\"\n[s4] \"四天王の一員……私、出世した？\""
"10014070-134-ヨシミ" = "えっ！？ちょっと！！私は違うわよ！！#n私はあいつの手下なんかじゃ……"
"10014070-135-ヨシミ" = "えっ！？ちょっと！！私は違うわよ！！#n私はあいつの手下なんかじゃ……"
"10014070-136-アイリ" = "よ、ヨシミちゃん！#nここは空気を読んで合わせてあげよう……？"
"10014070-137-ヨシミ" = "いやよ！！いくらなんでもあいつの部下扱いは無理！！"
"10014070-138" = "[s5] \"ヨシミ、カズサの顔を見て。\"\n[s6] \"あの顔を見てもそんな事いえる？\""
"10014070-139-ヨシミ" = "……顔？"
"10014070-140-ヨシミ" = "……顔？"
"10014070-141-ヨシミ" = "何の顔……"
"10014070-145-カズサ" = "ふっ……"
"10014070-146-カズサ" = "ざけないで……ほんと、やめなさいよ……！！#nマジで……！あんた達、全員……ぶっ飛ばされたいの……！？"
"10014070-150-ヨシミ" = "……。"
"10014070-151-ヨシミ" = "私たちは「放課後スイーツ団」の四天王よ！！"
"10014070-152-ヨシミ" = "諸君、先生を除いてみんなで突撃いいいー！！"
"10014070-153-ヨシミ" = "いっくわよーー！！"
"10014070-154-アイリ" = "い、いきますぅーー！？"
"10014070-155-ナツ" = "ごーごー！！"
"10014070-160" = "[ns7] \"ごーごー！\"\n[ns8] \"あ、私は後ろにいないとね。\""
"10014070-163-カズサ" = "……たち。"
"10014070-164-カズサ" = "どいつもこいつも……宇沢もスケバンも先生も……全員……"
"10014070-166-カズサ" = "後で覚悟しておいてよね……"
