[translation]
"10014040-1" = "第4話;放課後スイーツ団？"
"10014040-2" = "（……翌日）"
"10014040-3-カズサ" = "ああ、先生……来てたんだ。"
"10014040-4-カズサ" = "……それで、どうしたの？"
"10014040-5-カズサ" = "まさか、また何かあったわけじゃないよね？"
"10014040-6-カズサ" = "あ、いや。#n怒ってるとかじゃなくて、純粋に気になって……"
"10014040-7-カズサ" = "……え？"
"10014040-8-カズサ" = "解決のために「相談」を続けた方がいい……？"
"10014040-9-カズサ" = "……相談？#nそれはそうだけど……"
"10014040-10-カズサ" = "宇沢じゃなくて……私が？#n相談の対象って私なの？どうして……？"
"10014040-14-カズサ" = "うーん。まぁ、大人の先生がそう言うなら、そうなんだろうね。#nいちいち理由を聞くのも良くないと思うし。"
"10014040-15-カズサ" = "じゃあ、とりあえず座ろっか……"
"10014040-16-？？？" = "へいへ～い#nそこのかわい子ちゃん～"
"10014040-17-？？？" = "退屈そうだね～#nお姉さんたちと楽しく遊ばない～？"
"10014040-18-カズサ" = "……？"
"10014040-19" = "[ns] \"この声は……\""
"10014040-24-カズサ" = "……？"
"10014040-25-カズサ" = "……？？？"
"10014040-26-ナツ" = "ハッハッハ！#n慌ててるねぇ。なかなか可愛い顔をするじゃあないか。"
"10014040-27-アイリ" = "あ、当たり前です！#nわ、私たちは怖いですからね！ふ、不良なんですから！"
"10014040-28-ヨシミ" = "えー……これで合ってる？#n本当に大丈夫？"
"10014040-33-カズサ" = "……なに？"
"10014040-34" = "[s3] \"……？？？\"\n[s4] （不良のコスプレ……？）"
"10014040-35-カズサ" = "あ、あんた達……ここで何してるの？#n……その格好は一体？"
"10014040-36-カズサ" = "あ、あんた達……ここで何してるの？#n……その格好は一体？"
"10014040-37-アイリ" = "か、カズサちゃん！#nカズサちゃんが何者だったとしても、私たちはカズサちゃんと一緒だよ！"
"10014040-38-カズサ" = "それはありがたいけど……#nそれ以上に、今なにしてるのか聞いてるんだけど……。"
"10014040-39-カズサ" = "マジで意味わかんないんだけど。#n何なのそれ？ナツの話し方もヘンだし……。"
"10014040-40-ナツ" = "ふっふっふ……拒む必要はないのだよカズサ。"
"10014040-41-ナツ" = "これからの人生、今までとは違う世界……共に行こうじゃないか。"
"10014040-42-カズサ" = "これからの人生……？今までとは違う世界……？"
"10014040-46-ヨシミ" = "……いや、ちょっと待ってよ。#nコレ、単純に理解できてないんじゃないの？"
"10014040-47" = "[s5] \"えっと、説明してもらえるかな。\"\n[s6] \"コスプレ失敗だね……。\""
"10014040-48-ナツ" = "今日から私たちの部活は「放課後スイーツ部」から#n「放課後スイーツ団」に変えることにしたのだ。"
"10014040-49-ナツ" = "今日から私たちの部活は「放課後スイーツ部」から#n「放課後スイーツ団」に変えることにしたのだ。"
"10014040-50-アイリ" = "カズサちゃん！#n私たち、カズサちゃんが無理しないで一緒に居られるようにしたいんだ。"
"10014040-52-カズサ" = "いや、「部」が「団」に変わっただけじゃん。#nなんで急にそんな事するのさ……。"
"10014040-53-カズサ" = "一体どういう……"
"10014040-54-ヨシミ" = "ねえ、待って。これ、やっぱり理解できてなくない？"
"10014040-55-ヨシミ" = "まず、私たちの意図からちゃんと説明しないと……"
"10014040-56-？？？" = "やっぱり！！そうだと思ってました！！！"
"10014040-59" = "[ns] \"……あ。\""
"10014040-61-ヨシミ" = "……？？"
"10014040-62-アイリ" = "あれ、この声は……"
"10014040-63-ナツ" = "……聞き覚えのある。"
"10014040-65-レイサ" = "……そうだったんですね。#nやっぱりそういう事でした……！"
"10014040-66-レイサ" = "もしかしたら、本当に悔い改めてるのではないかと思ったのに……やっぱり！#nそんな事ないですよね！！"
"10014040-67-レイサ" = "あなたの邪悪な本性は、そう簡単に変わるようなものではないでしょうから！"
"10014040-68-レイサ" = "「放課後スイーツ団」……なんという恐ろしい名前！！"
"10014040-69-レイサ" = "まるでやわらかいスイーツを食べるように……#n辺り一帯を食べ尽くすという恐ろしい意味なのでしょうね！？"
"10014040-70-レイサ" = "さらに、また先生を誘拐して……！#n公権力まで掌握しようとするなんて！！"
"10014040-71-レイサ" = "やはり、あなたは再起のチャンスを窺っていた……"
"10014040-72-レイサ" = "そう、復活のために新しい組織を立ち上げたのですね[ruby=きょうやま]杏山[/ruby]カズサ！"
"10014040-73-レイサ" = "いえ……"
"10014040-74-レイサ" = "「キャスパリーグ」！！"
"10014040-78-トリニティの生徒A" = "何の話……？#nキャス……なに？"
"10014040-79-トリニティの生徒B" = "キャスパリーグって伝説のスケバンでしょ？#nあの子たちスケバンなの？"
"10014040-80-ヨシミ" = "……キャスパ……なに？"
"10014040-81-ナツ" = "誘拐……！？"
"10014040-85-ナツ" = "……カズサが！？#n先生を誘拐！？"
"10014040-86-アイリ" = "か、カズサちゃん……？#n本当なの！？"
"10014040-87-カズサ" = "いや、なに言ってんの！？"
"10014040-88" = "[s9] \"カズサ……そういうことだったの！？\"\n[s10] \"誤解というのはあっという間に大きくなってしまうもの。\""
"10014040-89-カズサ" = "アホか！あなたが呼んだんでしょうが！！"
"10014040-90-カズサ" = "先生、なに普通に解説してんの！！"
"10014040-91-カズサ" = "今ふざけてる場合じゃないんだって！#n変な噂が広まっちゃう前に早く訂正しないと……"
"10014040-92-レイサ" = "いま、先生を脅迫しましたね？"
"10014040-94-レイサ" = "大人相手にそんな態度をとれるなんて……やはり無慈悲ですね、杏山カズサ！！"
"10014040-95-カズサ" = "……くそ。#nもう遅いか。"
"10014040-96-ヨシミ" = "さっきから何言ってんの、あいつ……"
"10014040-97-ヨシミ" = "ねえ、ちょっとカズサ。#nあいつどうにかしなさいよ。あんたの友達でしょ？"
"10014040-98-カズサ" = "……いや、友達じゃないんですけど！？"
"10014040-103-レイサ" = "……許せません。#nこの地の平和のために！みんなが安心して登校できる街のために！！"
"10014040-104-レイサ" = "覚悟してください、杏山カズサ。#nそして「放課後スイーツ団」！！"
"10014040-105-レイサ" = "今度こそ、あなたたちを倒して正義を実現します！！"
"10014040-106-レイサ" = "挑戦状を受け取ってください！！"
"10014040-107-カズサ" = "いや、だからちょっと……"
"10014040-112-ナツ" = "ふっふっふ……。#nその挑戦、受けて立とう。"
"10014040-113-アイリ" = "そ、そうです！#nよく分からないですけど、これ以上カズサちゃんをいじめるのは許しません！！"
"10014040-114-アイリ" = "あなたが誰かは知りませんが……私たちも黙っていませんから！！"
"10014040-116-カズサ" = "……なに？"
"10014040-117-レイサ" = "決闘成立ですね……いいでしょう。#n覚悟してください！！"
"10014040-118-ナツ" = "私たち「放課後スイーツ団」の結束を見せてやろう！！"
"10014040-119-ナツ" = "攻撃ぃぃぃいー！！！"
"10014040-120-アイリ" = "わ、わぁー！！！"
"10014040-121-レイサ" = "とりゃああああああーっ！"
"10014040-137-カズサ" = "先生……#n私、どうすれば……"
"10014040-138" = "[s13] \"行くよ！！『放課後スイーツ団』！！\"\n[s14] \"やわらかなスイーツを食べるように、一帯を掌握してやろう！！\""
"10014040-139-カズサ" = "……。"
"10014040-140-カズサ" = "……。"
"10014040-141-カズサ" = "……私は。"
"10014040-143-カズサ" = "ああ、変われたと思っていたのは私だけで。#n結局、過去の罪が追いかけてきてるのかな……。"
