[translation]
"10014075-2-カズサ" = "はぁ、はぁ……"
"10014075-3-ヨシミ" = "も、もう……この辺でいいんじゃないの……"
"10014075-9-アイリ" = "この辺りなら大丈夫かな……？#nトリニティ自治区まで来たし……"
"10014075-10-ヨシミ" = "っていうか、逃げる必要があったの？#nほぼ勝ったようなものだったじゃん……？"
"10014075-11-カズサ" = "いや、あれ以上の時間稼ぎは本当に危ない。#nそろそろヴァルキューレのサツが来る頃だったから……"
"10014075-12-カズサ" = "あの場に残ってたら、今頃みんな捕まってただろうね。"
"10014075-13-ヨシミ" = "そ、そうなんだ……。"
"10014075-17-ヨシミ" = "……ところで「サツ」って何？"
"10014075-21-カズサ" = "……あ。"
"10014075-22" = "[s1] \"専門用語が……\"\n[s2] \"たぶん、ヴァルキューレ警察学校のことだよ。\""
"10014075-23-ヨシミ" = "ああ……警察学校の生徒の事か……。#nつか、よく先生もそんなの知ってるね。"
"10014075-24-ヨシミ" = "ああ……警察学校の生徒の事か……。#nつか、よく先生もそんなの知ってるね。"
"10014075-29-ナツ" = "そして、キャスパリーグの復活を阻止しようとした彼女らは……#n逆に一掃されてしまったのであった。"
"10014075-30-ナツ" = "ああ……世界は魔獣の復活を防ぐ事ができず、再び闇の時代へ――"
"10014075-37-カズサ" = "やめてよ！！！"
"10014075-39-カズサ" = "もう！！"
"10014075-41-カズサ" = "やめて"
"10014075-43-カズサ" = "って！！"
"10014075-45-カズサ" = "言った"
"10014075-47-カズサ" = "でしょ！"
"10014075-49-カズサ" = "サイアク！！"
"10014075-51-ナツ" = "あ、ああ～！！あああ～～～！！これ、が……"
"10014075-53-アイリ" = "あはは……"
"10014075-54-ヨシミ" = "……くくっ。"
"10014075-55" = "[s3] \"楽しそうだね、ヨシミ。\"\n[s4] \"ここ最近で一番の笑顔だよ。\""
"10014075-56-ヨシミ" = "……うん、もちろん。"
"10014075-57-ヨシミ" = "……うん、もちろん。"
"10014075-58-ヨシミ" = "今最高に楽しいから……このままでいさせて。"
"10014075-60-ヨシミ" = "……ところで、こいつはどうするの？"
"10014075-61-カズサ" = "こいつ……？#nあー……"
"10014075-67-アイリ" = "そういえば……壁を壊した時からもう気絶していましたね……"
"10014075-68-ナツ" = "うーん。戦うどころか、私たちの顔も見てないだろうね。"
"10014075-69-アイリ" = "でも幸い、特に怪我したりは……なさそうです！"
"10014075-74-カズサ" = "……そう。じゃ、気にしなくていいよ。#nまあ、適当にこの辺のベンチに寝かせておけばいいから。"
"10014075-81-アイリ" = "え、ええ！？！？#nカ、カズサちゃん！？"
"10014075-82-ヨシミ" = "いやちょっと……いくらなんでも、気絶した人をそのままベンチに放置は……"
"10014075-84-カズサ" = "……いや待って、私を信じて。#nこいつ本当に大丈夫だから。"
"10014075-85-カズサ" = "知ってて言ってる……こういうの何回も見てきてるし。#nってか、そもそもこいつ、ベンチで寝るの好きだし。"
"10014075-86-ナツ" = "なるほど……悪縁から育まれた信頼関係か。"
"10014075-88-ナツ" = "……ロマンだね。"
"10014075-89" = "[s5] \"……うん、確かに。\"\n[s6] \"今回はナツの話が正しいかもね。\""
"10014075-90-カズサ" = "もう、うるさいよ！！#n何がロマンよ……"
"10014075-91-カズサ" = "もう、うるさいよ！！#n何がロマンよ……"
"10014075-95-カズサ" = "……うーん。"
"10014075-99-ヨシミ" = "……何してんの？"
"10014075-100-アイリ" = "カズサちゃん、それ……挑戦状？#nレイサちゃんに返すの？"
"10014075-101-カズサ" = "まぁ……私が持っててもしょうがないから、持ち主に返す。#nそれだけ。"
"10014075-103-ナツ" = "なるほど。ツンデレってことか。"
"10014075-104-カズサ" = "やめろって言ったよね。"
"10014075-105-カズサ" = "はぁ、ホント疲れた……どうしてこんな事に……"
"10014075-110-ヨシミ" = "いーい腹時計を持ってらっしゃるわねぇ？"
"10014075-111-アイリ" = "みんな一晩中頑張ったからね……"
"10014075-112-ナツ" = "うむ。糖分補給が必要だな。"
"10014075-113" = "[s7] \"じゃあ、何か食べに行こうか。\"\n[s8] \"今日は先生の奢りだよ。\""
"10014075-120-放課後スイーツ部" = "……やったー！！"
