[translation]
"1009315-1" = "頑張った証ってヤツ？"
"1009315-2" = "（キララの様子が気になって、ゲヘナへ来てみたものの）"
"1009315-3" = "（生徒たちの様子はいつも通り……）"
"1009315-7" = "ブオオオオオン！"
"1009315-8-ゲヘナの生徒A" = "もっと飛ばせないの？次遅刻したらマジヤバいんだって！！"
"1009315-9-ゲヘナの生徒B" = "急がないとスクラップになっちゃうよー！"
"1009315-15" = "[ns] \"バイクなのにすごいスピードが出てたような……。\""
"1009315-17" = "[ns] \"……って、後ろにキララ乗ってなかった！？\""
"1009315-18" = "（バイクが向かった方へと急いだ）"
"1009315-20" = "廃紙倉庫の前"
"1009315-21-キララ" = "はぁ……やっと着いたー！"
"1009315-22-キララ" = "みんな、ありがとね♪"
"1009315-23-ゲヘナの生徒A" = "気にしないでよ。あたし達もこっちに用があったわけだし。"
"1009315-24-ゲヘナの生徒A" = "キララちゃんのお願いだもんね。"
"1009315-25-ゲヘナの生徒B" = "探し物、見つかるといいね！"
"1009315-26-キララ" = "ほんっとありがとう！また今度お礼させて！"
"1009315-27-ゲヘナの生徒A" = "いいって。んじゃ、あたし達はここで！"
"1009315-31-キララ" = "うーん……とりあえず来てみたけど……どうしよ。"
"1009315-32-倉庫の管理人" = "おや？キララちゃん。どうしたんだい？"
"1009315-33-キララ" = "あっ！管理人さん！こんにちは！"
"1009315-34-倉庫の管理人" = "こんにちは。今日も元気だねぇ。#nそれで、どうしてこんなところに？"
"1009315-35-キララ" = "それがね……。"
"1009315-36-倉庫の管理人" = "……なるほど。部屋の片付けで外に出しておいた箱を回収されちゃったのか。"
"1009315-37-キララ" = "そうなの！！"
"1009315-38-キララ" = "しかも、超大事なノートが入ってて……どこいっちゃったんだろ。"
"1009315-39-倉庫の管理人" = "災難だったねぇ……。"
"1009315-40-倉庫の管理人" = "そういうことなら……。"
"1009315-44-倉庫の管理人" = "はい、今回だけ特別だよ。"
"1009315-45-倉庫の管理人" = "古紙倉庫を開けとくから、好きなだけ探しな！"
"1009315-46-キララ" = "えっ！？いいの！？"
"1009315-47-倉庫の管理人" = "早くしないと回収者がきちまうよ！"
"1009315-48-キララ" = "うんっ！管理人さん、ありがと！！"
"1009315-60-キララ" = "はぁ……。"
"1009315-61-キララ" = "見つからないよぉ……。"
"1009315-62" = "[s] \"何を探してるの？\""
"1009315-63-キララ" = "勉強の時に使ってた、フツーのリングノートなんだけど……。"
"1009315-64-キララ" = "考えてみたらフツーじゃないかも？表紙はあたしが魂込めてデコったし！"
"1009315-65" = "[s] \"たしかに、センスが光る表紙だね。\""
"1009315-66-キララ" = "えっ？"
"1009315-71-キララ" = "それそれ！それだよーっ！！"
"1009315-72-キララ" = "マジありがと、先生！！"
"1009315-73-キララ" = "……。"
"1009315-78-キララ" = "――って、先生っ！？なんでここにいるの！？"
"1009315-79-キララ" = "え？モモトーク？#nまさかアレ見てきてくれたの？"
"1009315-80-キララ" = "うわっ……めちゃくちゃ迷惑かけちゃった感じじゃん！？"
"1009315-81-キララ" = "マジごめん！先生！"
"1009315-82" = "[s1] \"それにしてもこのノート……。\"\n[s2] \"なんだか見覚えがあるような……。\""
"1009315-85-キララ" = "でしょでしょ！ていうか見覚えあるはずだよ♪"
"1009315-86-キララ" = "だって、先生と二人で勉強したときに使ってたノートなんだもん！"
"1009315-87" = "[s] \"あの時の……！\""
"1009315-88-キララ" = "まぁ、ぶっちゃけ最後のページまで埋めてるし、捨ててもいいんだけど……。"
"1009315-89-キララ" = "数式を覚えるために何回も書いた跡とか……#n悩みながら解いたときの記憶とか……。"
"1009315-90-キララ" = "……色んな思い出が詰まってるから捨てるなんて無理！"
"1009315-91" = "[ns] ノートのページをめくる。"
"1009315-97" = "（ノートには様々な数式や問題を解いた跡が残されている）"
"1009315-98" = "（どれほど一生懸命取り組んだのかが、はっきりと伝わってくるようだった）"
"1009315-100" = "[ns] \"ほんとに頑張ってたんだね、キララ。\""
"1009315-101-キララ" = "そんな風に改めて褒められると照れるかも。えへへっ♪"
"1009315-102-キララ" = "でも、あたしめちゃくちゃ頭いいってわけじゃないし、努力しないと人並みになれないんだよね。#nだから頑張って当然っていうか？"
"1009315-103" = "[s] \"人並みができる人は意外と少ないんだよ……。\""
"1009315-104-キララ" = "えっ、そうなの？マジ？"
"1009315-105-キララ" = "なんか自信ついてきたかも♪"
"1009315-107" = "（キララと話しながらノートを眺めていると……）"
"1009315-114" = "（そのうちに、とあるページが目に留まった）"
"1009315-116" = "[ns] \"これは……落書き？\""
"1009315-117-キララ" = "あっ！"
"1009315-118-キララ" = "こ、これはっ……！"
"1009315-119" = "[s3] \"勉強中に描く絵って――\"\n[s4] \"なんであんなに楽しいんだろうね？\""
"1009315-125-キララ" = "先生も分かってくれる？"
"1009315-126-キララ" = "なんか、問題解いてる時ってやたら集中できるんだよね！"
"1009315-127-キララ" = "それに、余白に描くしかないから――"
"1009315-128" = "[s] \"細かく描き込んじゃうんだよね！\""
"1009315-129-キララ" = "ねー！"
"1009315-130-キララ" = "意外！先生も同じようなことしてたんだ。"
"1009315-131-キララ" = "うちらって、結構似てるとこあるんだね♪"
"1009315-132" = "[s] \"あれ、このページのって……似顔絵？\""
"1009315-136" = "[ns] \"どこかで見たことあるような……。\""
"1009315-137-キララ" = "へ？似顔絵……？"
"1009315-138-キララ" = "……。"
"1009315-139-キララ" = "……あ。"
"1009315-140-キララ" = "ああっ……！"
"1009315-145" = "（キララが突然ノートを持っていった）"
"1009315-150-キララ" = "え、えっと、その、あ、あたし……。"
"1009315-154-キララ" = "あ、ありがとね！それじゃ！！！！"
"1009315-159" = "（キララは脱兎のごとく駆け出し、どこかへ行ってしまった）"
"1009315-160" = "（その頬は真っ赤に染まっていた）"
