[translation]
"1000405-1" = "大人とか子供とか"
"1000405-2" = "ゲヘナ郊外・小さなショッピングモール"
"1000405-6-ヒナ" = "……えっと。"
"1000405-7-ヒナ" = "こ、こんにちは……？"
"1000405-8" = "[s1] \"昼から会えるのすごく新鮮！\"\n[s2] \"青空の下のヒナちゃん！\""
"1000405-9-ヒナ" = "そんな、大袈裟な……。"
"1000405-10-ヒナ" = "そんな、大袈裟な……。"
"1000405-11-ヒナ" = "人を夜中にしか出てこないお化けみたいに……。"
"1000405-12-ヒナ" = "お昼に会うって約束したんだから、仕方ない。"
"1000405-13" = "[s] \"風紀委員会のお仕事は大丈夫？\""
"1000405-14-ヒナ" = "……大丈夫、私だって24時間365日仕事してるわけじゃないし。"
"1000405-15-ヒナ" = "スケジュールさえ調整できれば、3時間くらい捻出できる。"
"1000405-16" = "[s3] \"……3時間？\"\n[s4] \"少なくない？\""
"1000405-17-ヒナ" = "……？"
"1000405-18-ヒナ" = "……？"
"1000405-19-ヒナ" = "え、少ない……そう……？"
"1000405-20-ヒナ" = "別に、それくらいで十分かと思ってたけど……ショッピングだけ、だし。"
"1000405-21" = "[s] \"ううん、ありがとね。じゃあ行こう！\""
"1000405-22-ヒナ" = "あ、うん……。"
"1000405-24" = "（ヒナと一緒にショッピングモールに入った）"
"1000405-27-ヒナ" = "（人が少ない……）"
"1000405-28-ヒナ" = "（先生、多分私のためにこういう場所を……）"
"1000405-29-ヒナ" = "（本当に、この人は……）"
"1000405-30-ヒナ" = "……それで、大事な用事ってなに？"
"1000405-31" = "[s5] \"特にこれ以上は何もないよ？\"\n[s6] \"デートって大事な用事じゃない？\""
"1000405-32-ヒナ" = "……はぁ。"
"1000405-33-ヒナ" = "……はぁ。"
"1000405-34-ヒナ" = "そういうことね……何となくそうかもとは思ってたけど。"
"1000405-36" = "キャラクター系のアクセサリーショップ"
"1000405-37-ヒナ" = "アクセサリー……。"
"1000405-38-ヒナ" = "変な動物のデザインがたくさん……。"
"1000405-39-ヒナ" = "……？いや、特に気に入ったものとかは……。"
"1000405-40-ヒナ" = "そもそも私、こういうのはそんなに好きじゃない。"
"1000405-41-ヒナ" = "可愛いって言ってる生徒がいるのは知ってるけど、私にはよくわからない。この子たちの名前も知らないし……。"
"1000405-42-ヒナ" = "えっと、じゃあ別のところに……。"
"1000405-44" = "ゲームセンター"
"1000405-45-ヒナ" = "ゲームセンター……。"
"1000405-46-ヒナ" = "ううん、あんまり来たことない。興味も無かったし。"
"1000405-47-ヒナ" = "五月蠅くて、ギラギラしてて、人が多い……。"
"1000405-48-ヒナ" = "こういうのが好きな人がいるってことは理解してる。ただ私の好みじゃないってだけ。"
"1000405-49-ヒナ" = "……いいの？じゃあ、別のところに……。"
"1000405-51" = "アパレルショップ"
"1000405-52-ヒナ" = "これ、ストリートファッション系って言うんだっけ……。"
"1000405-53-ヒナ" = "週末とかに、こういう派手な服を着る生徒たちが多いのは知ってる……。"
"1000405-54-ヒナ" = "……何か気になるもの？"
"1000405-55-ヒナ" = "……別に。"
"1000405-56-ヒナ" = "いらないものをわざわざ買う必要無いし。"
"1000405-57-ヒナ" = "制服があるんだから、私服なんてそんなに必要ない。"
"1000405-58" = "[s7] \"買わなくてもいいから、好みとか聞きたいな。\"\n[s8] \"この中だったらどういうのが好き？\""
"1000405-59-ヒナ" = "……？"
"1000405-60-ヒナ" = "……？"
"1000405-61-ヒナ" = "えっと……。"
"1000405-62-ヒナ" = "ん……。"
"1000405-64-ヒナ" = "うーん……。"
"1000405-66-ヒナ" = "……ごめん。"
"1000405-67-ヒナ" = "特に、どれも……。"
"1000405-69" = "ショッピングモール・ファミレス"
"1000405-70" = "（休憩がてら、近くのファミレスに入った）"
"1000405-71-ヒナ" = "……。"
"1000405-72-ヒナ" = "………。"
"1000405-73-ヒナ" = "…………。"
"1000405-74" = "[s] \"どうしたの？\""
"1000405-75-ヒナ" = "え……？"
"1000405-76-ヒナ" = "い、いや……その、先生が期待してたのは、こういうのじゃなかったんじゃないかなって……。"
"1000405-77-ヒナ" = "私が……なんか、ダメにしちゃってるというか……。"
"1000405-78-ヒナ" = "ごめん、つまらない人間で……自覚はしてるんだけど。"
"1000405-79" = "[s9] \"そういうのも個性じゃない？\"\n[s10] \"それもヒナらしくて良いと思う。\""
"1000405-82-ヒナ" = "……。"
"1000405-83-ヒナ" = "（本当に、この人は……）"
"1000405-84-ヒナ" = "（またそうやって優しいことを……）"
"1000405-85-店員" = "ご注文は如何しますか？"
"1000405-86-ヒナ" = "あ……私はコーヒーを、砂糖とかミルク無しのブラックで。"
"1000405-87-ヒナ" = "先生は……ん？"
"1000405-88-ヒナ" = "どうしたの、先生？"
"1000405-89-ヒナ" = "[s11] \"ヒナは大人っぽいなって。\"\n[s12] \"相変わらず大人の舌だなって。\""
"1000405-90-ヒナ" = "……大人？"
"1000405-91-ヒナ" = "……大人？"
"1000405-92-ヒナ" = "……。"
"1000405-93-ヒナ" = "ふふっ、何を言うかと思ったら。大人なのは先生でしょう。"
"1000405-94-ヒナ" = "私はまだ……背も小さくて、文句ばっかりで、可愛げもない子供。"
"1000405-96-ヒナ" = "（あなたの、そういう気遣いが大人っぽいところ……）"
"1000405-97-ヒナ" = "（そこに対して思うところがある時点で、まだまだ私は子供……）"
"1000405-100-ヒナ" = "今日も私のせいでつまらなくしちゃったし……そんな無理に振舞わなくても……。"
"1000405-101" = "[s13] \"無理してないよ、ヒナの笑顔も見られたし。\"\n[s14] \"今日はすごく楽しかった。\""
"1000405-102-ヒナ" = "……。"
"1000405-103-ヒナ" = "……。"
"1000405-104-ヒナ" = "……そ、そう。ならいいけど……。"
"1000405-108-店員" = "（いちゃついてないで、早くもう一人の方の注文を……）"
