[translation]
"1005806-1" = "「救護」の在り方"
"1005806-6" = "（ミネの力を借りて、素早く仕事を片付けられた）"
"1005806-7-ミネ" = "これで今日の作業は、一通り終わったようですね。"
"1005806-8" = "[s] \"ミネは書類仕事も得意なんだね。\""
"1005806-9-ミネ" = "いえ、それほどでも。"
"1005806-10-ミネ" = "私も救護騎士団では責任者の立場にありますので、書類と付き合う機会もそれなりにあるからかもしれません。"
"1005806-11-ミネ" = "思いがけずに得られたスキルのひとつですね。"
"1005806-12" = "[s] \"今日はミネの「救護」のおかげで助かったよ。\""
"1005806-16-ミネ" = "……！"
"1005806-17-ミネ" = "なるほど、これもまたひとつの「救護」の在り方……！"
"1005806-18-ミネ" = "ありがとうございます、先生。大変勉強になりました。"
"1005806-19" = "[s] （ちょっとくらい笑ってもらえるかなと思って言ったんだけど……）"
"1005806-23-ミネ" = "……失礼しました、私のですね。"
"1005806-24" = "[s] \"出てもらって大丈夫だよ。\""
"1005806-25-ミネ" = "はい、ありがとうございます。"
"1005806-30-ミネ" = "こちら救護騎士団です。救護のご用命でしょうか？"
"1005806-36-緊迫した声" = "た、助けてください！道に迷って……！"
"1005806-37-緊迫した声" = "あの森です……「キヴォトスの樹海」です！"
"1005806-38-ミネ" = "「キヴォトスの樹海」ですね？"
"1005806-39-ミネ" = "もう少し詳しい状況をご説明いただけませんか？"
"1005806-40-緊迫した声" = "分からないんです……"
"1005806-41-緊迫した声" = "視界が暗くて遠くも見えず、どれも似たような木ばかりで……。"
"1005806-45-緊迫した声" = "……で……し……。"
"1005806-50-ミネ" = "もしもし……聞こえていますか！？"
"1005806-54-ミネ" = "電話が切れてしまいました……。"
"1005806-58-ミネ" = "先生、これは一刻の猶予もありません。"
"1005806-59" = "[s] \"何が起きてるの……！？\""
"1005806-60-ミネ" = "「キヴォトスの樹海」で、誰かが救護の手を求めています！"
"1005806-61-ミネ" = "大至急向かわねば！"
"1005806-62" = "[s] \"「キヴォトスの樹海」……？\""
"1005806-63-ミネ" = "はい、聞いたことはありませんか？"
"1005806-64-ミネ" = "「キヴォトスの樹海」は、一度入ったら抜け出せないと有名な場所……。"
"1005806-65-ミネ" = "その森に入るとGPSが機能しなくなったり、方位磁石が異常な動きをしたり……。"
"1005806-66-ミネ" = "一度でも道に迷ってしまうと出られなくなってしまう場所として、恐れられているのです。"
"1005806-67" = "[s] \"それはもう立入禁止にした方が良いんじゃ……！？\""
"1005806-68-ミネ" = "すでに案内板などで、むやみに立ち入らないよう警告は出されておりますが……。"
"1005806-69-ミネ" = "禁止されているからこそ、興味を持つ者が後を絶たず……。"
"1005806-70-ミネ" = "目的は人それぞれです。それこそSNSに投稿するためだったり、肝試しだったり、あるいは単純な好奇心から「キヴォトスの樹海」に足を踏み入れる人たちも見受けられます。"
"1005806-71-ミネ" = "先ほど私のところに届いた電話の主も、きっとそのうちの一人でしょう。"
"1005806-72-ミネ" = "先生、本日はありがとうございました。"
"1005806-73-ミネ" = "私は急ぎますので、お先に失礼いたします。"
"1005806-83" = "[ns] \"ちょっと待って……！\""
"1005806-97-ミネ" = "しかし、先生まで「キヴォトスの樹海」に来ていただかなくても……。"
"1005806-98" = "[s1] \"今日はミネに助けてもらったから、お互いさまってことで。\"\n[s2] \"ミネも大切な生徒だし、一人で危険な場所には行かせられないよ。\""
"1005806-101-ミネ" = "大切な、生徒……。"
"1005806-102-ミネ" = "ふふっ、そうでしたね。私自身の立場をすっかり忘れていました。"
"1005806-103-ミネ" = "つまり私と一緒に「救護」活動を担っていただける、ということですね。"
"1005806-104-ミネ" = "やはり今からでも、救護騎士団の臨時顧問になっていただくのはいかがでしょうか？"
"1005806-105" = "[s] \"そういえば前、そんな話もあったね……。\""
"1005806-106-ミネ" = "ええ。"
"1005806-107-ミネ" = "何度でも申し上げますが、先生は素晴らしい「救護」の才能と精神をお持ちですので。"
"1005806-111-ミネ" = "とにかく、今は先を急ぐとしましょうか。"
"1005806-112-ミネ" = "……実は「キヴォトスの樹海」に訪れるのは、私も初めてのことなのです。"
"1005806-113-ミネ" = "思っていたよりも、緊張しております……。"
"1005806-114" = "[s] \"ミネでも緊張するんだね。\""
"1005806-115-ミネ" = "……私も「大切な」生徒だと言っていただいたから、かもしれません。"
"1005806-116-ミネ" = "すみません、こんな時に。そんなに慌てなくても大丈夫ですよ。"
"1005806-117-ミネ" = "では、参りましょう！"
"1005806-122-ミネ" = "先生、足元の木にお気をつけください！"
"1005806-127-ミネ" = "これで大丈夫ですね。"
"1005806-128-ミネ" = "もう少し資源を大切に……？"
"1005806-132-ミネ" = "確かに、それもそうですね。"
"1005806-136-ミネ" = "引き続き足元に注意しながら進みましょう。"
"1005806-139-ミネ" = "遊歩道を外れてから結構な時間歩いてきましたが……人の痕跡が見当たりませんね。"
"1005806-140-ミネ" = "……色々と不安になってきましたが、私たちに救護を要請した生徒もきっと同じ気持ちでしょう。"
"1005806-147-ミネ" = "先生は大丈夫ですか？"
"1005806-151-ミネ" = "日陰で助かりましたが、足元も悪いのでご無理なさらず。"
"1005806-155-ミネ" = "かなり奥深くまで来ましたね……。"
"1005806-156-ミネ" = "しかしGPSが機能しないというのは、やはり単なる噂だったようです。"
"1005806-160-ミネ" = "とはいえ、バッテリーも減ってきてしまいました……。"
"1005806-161-ミネ" = "予備の分を持ってくるべきでしたね。"
"1005806-162-ミネ" = "……ありがとうございます。そうですね、急な出動であれば準備が心許ないのはよくあることです。今は最善を尽くしましょう。"
"1005806-164" = "（結局夜になっても、手がかりは見つからず……）"
"1005806-166-ミネ" = "……。"
"1005806-167-ミネ" = "こんな時間になってしまいましたね。"
"1005806-168-ミネ" = "申し訳ありません、先生。救護となると、周りが見えなくなってしまうようで……。"
"1005806-169-ミネ" = "やはり、先生を勢いで巻き込んでしまわない方が良かったかもしれません。"
"1005806-170" = "[s3] \"ううん、私がついてきたんだから気にしないで。\"\n[s4] \"その気持ちの真っすぐさは、ミネの良い所だよ。\""
"1005806-176-ミネ" = "……ありがとうございます、先生。"
"1005806-181-ミネ" = "あちらに休めそうな場所がありますね。"
"1005806-182-ミネ" = "少し休憩を取りませんか？シャーレを出てから、ずっと歩き詰めでしたから。"
"1005806-189-ミネ" = "先生はこちらの切り株に……"
"1005806-190-ミネ" = "落ち葉はどかしましたので、どうぞ。"
"1005806-195" = "[wa:400]― 先生、[wa:1200]大丈夫ですか？"
"1005806-197" = "― お怪我などは[wa:700]ありませんか？"
"1005806-200" = "[wa:500]― 夜の空気は[wa:1450]気持ちが良いですね……。"
"1005806-203" = "― 草の香りに、[wa:1400]川のせせらぎ……"
"1005806-205" = "― 心が落ち着きます。"
"1005806-208" = "[wa:350]― ……どうされましたか？"
"1005806-210" = "― 眩しい…[wa:1400]ですか…？"
"1005806-213" = "[wa:50]― ふふ、[wa:1800]確かに[wa:1200]そうかもしれませんね。"
"1005806-216" = "[wa:400]― 落ち着かないようでしたら、[wa:1600]私にもたれたり"
"1005806-218" = "― 膝でお休みいただいても[wa:1500]構いませんよ。"
"1005806-221" = "― ご心配[wa:400]なさらないでください。"
"1005806-224" = "― たとえ何があっても、"
"1005806-226" = "[wa:100]― 私が必ず[wa:1300]先生をお守りしますので。"
"1005806-229" = "（ミネの膝を借りて、少しのあいだ休ませてもらった）"
"1005806-235-ミネ" = "なんとか入り口まで戻ってこられました……。"
"1005806-239-ミネ" = "バッテリーも、まだ何とか……。"
"1005806-240" = "[s] \"ミネの方は、疲れてない？\""
"1005806-241-ミネ" = "私は大丈夫です。むしろ先生にはなれないことをさせてしまい……。"
"1005806-242-ミネ" = "いつかきちんと「顧問」になっていただいたら、こういうことも増えるかもしれませんが……ふふっ。"
"1005806-247-ミネ" = "もしかして、あの生徒から……？"
"1005806-251-緊迫した声" = "た、助けてください！森で迷ってるんです……！"
"1005806-252-緊迫した声" = "あの「キヴォトスの樹海」です！"
"1005806-253-ミネ" = "あらためてですが、もう少し詳しい状況をご説明いただけませんか？"
"1005806-254-緊迫した声" = "ですが、何も分からなくて……"
"1005806-255-緊迫した声" = "とにかく、木がたくさんあることしか……。"
"1005806-256-ミネ" = "今「キヴォトスの樹海」にいます、少しでもヒントをいただければ。"
"1005806-260-緊迫した声" = "えっ、嘘だろ！？"
"1005806-261-緊迫した声" = "まじで行ったのかよ、やべぇな！"
"1005806-266-チンピラ１" = "イタ電すればあの救護騎士団を動かせるとか、もっと早く思いつけば良かったな！"
"1005806-267-チンピラ２" = "ははっ、相当迷ったんじゃないの？"
"1005806-268-チンピラ１" = "そもそも本当だったところで、あそこで人探しは無理だろ！"
"1005806-273-ミネ" = "……。"
"1005806-274" = "[ns] \"えっと……ミネ？\""
"1005806-275-ミネ" = "三つ、過ちがあります。"
"1005806-276-ミネ" = "一つ目、いくら私でも二度目は様々な可能性を考えるということ。"
"1005806-277-ミネ" = "二つ目、いたずら電話であることを失念してしまったこと。"
"1005806-278-ミネ" = "三つ目、あまりこういった方法を乱用すべきではないのですが……"
"1005806-279-ミネ" = "いくつかの条件があるとはいえ、「救護騎士団は逆探知の権限がある」と知らなかったこと。"
"1005806-280-ミネ" = "先生。"
"1005806-281-ミネ" = "これより私は、「救護」を必要としている方の元へ参ろうと思います。"
"1005806-282-ミネ" = "誰かが道を誤ってしまったとき……。"
"1005806-283-ミネ" = "正しい道を示すことも、私たちが行うべき「救護」です。"
"1005806-284-ミネ" = "先生も、そう思いませんか？"
"1005806-288" = "[ns5] \"えっと……ほどほどにね？\"\n[ns6] \"手加減してあげてね……。\""
"1005806-291-ミネ" = "ご理解いただき、ありがとうございます。"
"1005806-292-ミネ" = "それでは申し訳ありませんが、お先に失礼します。また後日。"
"1005806-293-ミネ" = "救護騎士団、参ります！#n『救護が必要な場に救護を』！"
"1005806-299" = "（その後、ミネは猛烈なスピードでどこかへ消えていった）"
"1005806-303" = "（いたずら電話の犯人たちの顛末については、ミネのみぞ知る……）"
