[translation]
"10002070-1" = "第7話;海の家（１）"
"10002070-2-ヒフミ" = "……。"
"10002070-3-ヒフミ" = "と、とにかく二番目までは終えられましたね……。"
"10002070-4-アズサ" = "ペースは悪くない。次のミッションを始めよう。"
"10002070-5-アズサ" = "できるだけ早く終わらせて、最初の目的通り普通に海を楽しむとしよう。"
"10002070-6-ヒフミ" = "そ、そうですね……。"
"10002070-7" = "[s1] （うーん……）\n[s2] （もうすでに、それなりに楽しんでる気がするけど……）"
"10002070-8-アズサ" = "それでヒフミ、次のミッションは？"
"10002070-9-アズサ" = "それでヒフミ、次のミッションは？"
"10002070-14-ヒフミ" = "えっと、「海の家」にしましょうか。ただ普通に行って、食事をしているところを撮れば良さそうです。"
"10002070-15-ヒフミ" = "海といえば色んなものが美味しいですし、定番のお楽しみの一つですよね。"
"10002070-16-ヒフミ" = "実は事前に調べておいたのですが、この[ruby=むいがはま]無為ヶ浜[/ruby]には有名なお店があるそうで……"
"10002070-17-ヒフミ" = "あ、ここですね。"
"10002070-19" = "海の家"
"10002070-21-ヒフミ" = "えっと、失礼します……！"
"10002070-27-イズミ" = "ん？……あれ、先生！？"
"10002070-28" = "[s3] \"どうしてイズミがここに……？\"\n[s4] \"イズミもご飯食べに来たの？\""
"10002070-29-イズミ" = "ちょっと事情があって、今はここで働いてるの！"
"10002070-30-イズミ" = "ちょっと事情があって、今はここで働いてるの！"
"10002070-31-イズミ" = "店主さんがちょっと寝込んじゃって。それで今日一日、代わりにね！"
"10002070-32-イズミ" = "まさかこんなところで先生に会うなんて、ビックリした―！"
"10002070-34-ヒフミ" = "えっと、先生のお知り合いの方ですか？"
"10002070-35-マシロ" = "どこかで見たような……ゲヘナ？いや、まさか……"
"10002070-36-ツルギ" = "……？"
"10002070-37" = "[s] 全力で誤魔化す。"
"10002070-40-マシロ" = "なるほど、先生のお知り合いでしたか。一瞬変に気を張ってしまって、失礼しました。"
"10002070-41-イズミ" = "よく分かんないけど気にしないで！さあ、せっかく来てくれたんだし、私の新作を味わっていってよ！"
"10002070-42" = "[s5] \"イズミの新作！？\"\n[s6] \"まさか、店主さんが寝込んでるのって……！\""
"10002070-43-イズミ" = "そっちのみんなも座って座って！"
"10002070-44-イズミ" = "そっちのみんなも座って座って！"
"10002070-45-イズミ" = "ここのメニューは何でも美味しいから、期待してて良いよ！ちょっとだけなら割引もしてあげる！"
"10002070-49-アズサ" = "なるほど、"
"10002070-50-アズサ" = "じゃあありがたく。"
"10002070-51-マシロ" = "それではお言葉に甘えて……。"
"10002070-52-マシロ" = "先輩も、こちらへどうぞ。"
"10002070-58" = "[ns] \"えっと、みんな、その……。\""
"10002070-59-ヒフミ" = "ありがとうございます！えっと、どれにしましょう……！"
"10002070-60" = "[s] \"ちょっと話を聞いてほしいんだけど……。\""
"10002070-61-ヒフミ" = "先生、どうかしましたか？"
"10002070-62-マシロ" = "あ、メニューの名前がすごく斬新ですね。"
"10002070-63-マシロ" = "「牡蠣氷」「チョコミント焼きそば」「練乳冷やし中華」「なまこジュースのチョコレートがけ」……"
"10002070-64-マシロ" = "ユニークですね、良いセンスです。"
"10002070-65" = "[s] \"ユニークっていうか、多分それ文字通りっていうか……。\""
"10002070-66-ヒフミ" = "……？どういうことですか？"
"10002070-67-イズミ" = "みんなそろそろ選んだ？"
"10002070-68-イズミ" = "ご注文をどうぞー！"
"10002070-72-マシロ" = "では、私はこの「牡蠣氷」というのを。"
"10002070-73-マシロ" = "先輩は何にしますか？"
"10002070-75-ツルギ" = "……「チョコミント焼きそば」。"
"10002070-76-ヒフミ" = "では、私は「なまこジュースのチョコレートがけ」」で……！"
"10002070-81-アズサ" = "「練乳冷やし中華」。"
"10002070-83-イズミ" = "オーダー承りましたー！"
"10002070-84-イズミ" = "「牡蠣氷」「チョコミント焼きそば」「なまこジュースのチョコレートがけ」「練乳冷やし中華」を一つずつね！牡蠣シロップはまだあったかな……まあ多分大丈夫！"
"10002070-85" = "[s] \"ちょっ、ちょっと待って……！\""
"10002070-86-イズミ" = "あ、先生は何を食べるの？"
"10002070-87-イズミ" = "私に作れそうなものなら、何でも作ってあげるよ？"
"10002070-88-イズミ" = "どうする？何が良い？"
"10002070-89" = "[s] \"わ、私は……っ！！\""
"10002070-90" = "（ッダァン！！）"
"10002070-91-ヒフミ" = "……え？"
"10002070-93" = "（ダダダダダッ！ダダダダダンッ！！）"
"10002070-94-イズミ" = "ふえぇっ！？"
"10002070-95-イズミ" = "お、お店が襲撃されてる！？何で、どうして！？"
"10002070-96-？？？" = "「どうして」だと……！？"
"10002070-97-？？？" = "本気で言っているのか、このバイオテロリストめ！！"
"10002070-98" = "[s] \"この声は……。\""
"10002070-102-チンピラB" = "許さない……"
"10002070-103-チンピラB" = "許さないぞ！"
"10002070-104-チンピラA" = "お前たちのせいで、あたしらのヘッドは今でもトイレから離れられない！"
"10002070-106-ヒフミ" = "ま、またスケバンの方々が……！？"
"10002070-107-チンピラB" = "自信満々に出してきたと思って油断した……くそっ、お前の料理のせいで……！！！"
"10002070-108-チンピラB" = "こんなお店、ぶっ壊しちまった方がキヴォトスのためだ！いくぞ！"
"10002070-109-ヒフミ" = "え、えっと、状況がよく掴めないのですが……？"
"10002070-110-チンピラA" = "問答無用！！"
"10002070-112-チンピラA" = "おら、やっちまえ！！"
"10002070-113" = "（ダダダダダッ！ダララッ！ドカアァァン！！）"
"10002070-114-イズミ" = "あああっ！！私の……じゃないけど、お店が！！！"
"10002070-115-イズミ" = "待って待って！ここ私のお店じゃないから余計にダメだって！うわああん！！"
"10002070-116-アズサ" = "……よく分からないけど、応戦した方が良い？"
"10002070-117-マシロ" = "食べ物を粗末にするなどという、とんでもない悪の行い……見過ごすわけには行きません！"
"10002070-118-マシロ" = "さあ、正義の鉄槌を！"
"10002070-124-ヒフミ" = "え、ちょっ、これ何度目ですか！？"
