[translation]
"10040060-1" = "第6話;ウィットネス・コユキ！"
"10040060-4-コユキ" = "ここ、ですね……。"
"10040060-5-コタマ" = "もう使われてない地下通路のひとつです。"
"10040060-6-コタマ" = "監視カメラや侵入検知システム等は設置されてません。#nセミナーの管轄範囲内ではありますが、感知できない場所です。"
"10040060-7-コユキ" = "そ、そうなんですね……うぅ。"
"10040060-8-コユキ" = "暗いしひと気もなくて、なんか怖いなぁ……。"
"10040060-9-コユキ" = "こんな場所があったなんて……。"
"10040060-10-ハレ" = "セキュリティシステムを避けて逃げられるのは、ここしかないからね。"
"10040060-11-コユキ" = "それは分かってます……けど、なんか、その……。"
"10040060-15-コユキ" = "や、やっぱりいいです。#nたぶん気のせいですから……。"
"10040060-17-ハレ" = "……？"
"10040060-18-コタマ" = "そこを進んでください。もたもたしていられません。"
"10040060-19-コタマ" = "ただ……ここから先、私たちは支援できそうにありません。"
"10040060-20" = "[s1] \"どういうこと？\"\n[s2] \"通信の問題とか？\""
"10040060-23-コタマ" = "はい、電波の届かない場所なので。"
"10040060-24-コタマ" = "多少入り組んではいますが、迷子になるほどではないので。#nさきほどお話したとおりに進めば問題ないでしょう。"
"10040060-25-ハレ" = "反対側に着いたら、地下道があるんだ。"
"10040060-26-ハレ" = "マキにそこで待機してるように連絡しておいたから、一緒に脱出して。"
"10040060-28-コユキ" = "それはそうと……本当に真っ暗ですね。これじゃあ、転んじゃいそうですけど？"
"10040060-29-コユキ" = "怪我したら大変ですし……電気をつけちゃダメですか？"
"10040060-30-コタマ" = "すぐ見つかってしまいますよ……。"
"10040060-31" = "[s3] \"でも怪我したら危ないから……\"\n[s4] \"なんとかつけられないかな。\""
"10040060-34-コタマ" = "……先生まで？"
"10040060-35-ハレ" = "うーん。灯りならつくと思うけど、問題はその後だよね。"
"10040060-36-ハレ" = "電力を使うと、制御室に通知が行く。#nつまり、位置がバレちゃう。"
"10040060-37-ハレ" = "もちろん、捕まえる前に逃げ切っちゃえば良いんだけど……。"
"10040060-38-ハレ" = "先生、どうする？"
"10040060-39-ハレ" = "……本当につけて良いの？"
"10040060-40-ハレ" = "誰にも怪我してほしくないから……？"
"10040060-44-ハレ" = "……分かった。"
"10040060-45-コタマ" = "先生らしいですね、仕方ありません。"
"10040060-46-コタマ" = "右の壁を曲がると、すぐにスイッチがあります。"
"10040060-47-コタマ" = "ですが先ほどお話したとおり、向こうはすぐ気づくはずです。#n可能な限り素早く脱出してください。"
"10040060-48-コユキ" = "わかってますよ！みっぎの壁～♪みっぎの壁～♪"
"10040060-49-コユキ" = "ありましたぁ～！"
"10040060-54-コユキ" = "……あれ？"
"10040060-55-コユキ" = "なにか起動したような音が……。"
"10040060-61-コユキ" = "な、なんですかこれ～！？なんでこんな音がするんですか～！？"
"10040060-62-コタマ" = "これは……。"
"10040060-63-コタマ" = "ドローンです……！"
"10040060-64-コユキ" = "えええええええ！？"
"10040060-65" = "[ns5] \"最初からバレてたの！？\"\n[ns6] \"先回りされてるなんて……。\""
"10040060-68-ハレ" = "と、とりあえずそこから出ないと……！"
"10040060-69-ハレ" = "急いで逃げて……！"
