[translation]
"10040070-1" = "第7話;オニの特権"
"10040070-3-？？？" = "――――"
"10040070-4-？？？" = "――――せい。"
"10040070-5-？？？" = "――――――――"
"10040070-6-？？？" = "――――せん――せい。"
"10040070-7-？？？" = "――――先生。"
"10040070-8-ノア" = "――先生、何か考え事ですか？"
"10040070-9" = "[ns1] \"あ、ううん。\"\n[ns2] \"ただ今日起きたことを振り返ってたんだ。\""
"10040070-12-ノア" = "ふふっ、そうでしたか。"
"10040070-13-ノア" = "暗いので、足もとには気をつけてくださいね。"
"10040070-14-ノア" = "皆さん、先生を待ってるんですよ。"
"10040070-15-ノア" = "よければ、転ばないよう手をつなぎませんか？"
"10040070-16-ノア" = "はい、どうぞ。"
"10040070-17-ノア" = "ふふっ、冗談です。#nでもおかげで、先生の珍しい表情に出会えました。"
"10040070-18-ノア" = "その顔を目にしたのは、私だけなんですね。#n待ってる皆さんに、少しだけ申し訳ないです。"
"10040070-19-ノア" = "でも、そうですね……。"
"10040070-20-ノア" = "先生を捕まえた「オニ」の特権と考えれば……悪い気はしないのかも？"
"10040070-21-ノア" = "ふふっ。少し浮かれて見えますか？#nたしかに、そうなのかもしれません。"
"10040070-22-ノア" = "……どうしました？"
"10040070-23-ノア" = "いつから気づいていたのかが、聞きたいんですね？"
"10040070-24-ノア" = "それはですねえ……。"
"10040070-25-ノア" = "先生を残したまま、#nコユキちゃんが逃げ出した時から、です。"
"10040070-26" = "[s3] \"ほとんど最初から……！？\"\n[s4] \"全部知ってたうえで、あんな仕打ちを……！？\""
"10040070-29-ノア" = "ふふっ、そこはお互い様だと思いますよ？"
"10040070-30-ノア" = "だって、コユキちゃんのためとはいえ……。"
"10040070-31-ノア" = "……先生も、素直に出てきてくれなかったのですから。"
"10040070-36-ノア" = "なんて、ごめんなさい。#n少し意地悪な言い方でしたね。"
"10040070-37-ノア" = "もちろん、ほかならぬ先生のことですから、#n事情があることはわかってました。"
"10040070-38-ノア" = "でも、やっぱり……。"
"10040070-39-ノア" = "コユキちゃんも先生も楽しそうだったので。"
"10040070-40-ノア" = "水を差したくなかったんです。"
"10040070-41-ノア" = "コユキちゃんを捕まえた後になってからですけど、#nユウカちゃんも概ね事情には気付いたみたいですよ。"
"10040070-42-ノア" = "ふふっ。先生がどう感じたか分かりませんが……。"
"10040070-43-ノア" = "コユキちゃんたちとのオニごっこ、私は楽しかったですよ。"
"10040070-44-ノア" = "皆さんが息を合わせて助けあう姿や慌てた様子も見られましたし。"
"10040070-45-ノア" = "こんな機会は、そうそうないでしょうから。"
"10040070-46-ノア" = "だから……。"
"10040070-47-ノア" = "つい、捕まえるのが惜しくなってしまったんです。"
"10040070-48-ノア" = "ふふっ。いま「じゃあ、またやろう」と言いかけましたね。#nそうじゃないんです。わかりますよね。"
"10040070-49-ノア" = "……なんて、ごめんなさい。私の話ばかりになってしまいました。"
"10040070-50-ノア" = "先生はどうでしたか？#n私が聞くのも変ですが、ちゃんと楽しめました？"
"10040070-51" = "[s5] \"……スリル満点だったよ。\"\n[s6] \"こういう感覚、久しぶりかも。\""
"10040070-54-ノア" = "そうでしたか。良かった。#nご不快でしたら、申し訳ないと思っていたので。"
"10040070-55-ノア" = "……どうしました？"
"10040070-56-ノア" = "コユキちゃんが意味深な発言を？"
"10040070-57-ノア" = "……具体的にお聞かせいただけますか？"
"10040070-58" = "[s7] \"ずっと見られている気がするって。\"\n[s8] \"ノアの視線を感じていたのかも。\""
"10040070-61-ノア" = "なるほど……。"
"10040070-62-ノア" = "さすが、コユキちゃんですね……。"
"10040070-63-ノア" = "気付かれないように動いたつもりでしたが、勘がいいんでしょうね。"
"10040070-64-ノア" = "まあ、当然のことかもしれません。#nコユキちゃんは……。"
"10040070-68-ノア" = "……いえ、なんでもないです。"
"10040070-69-ノア" = "話が長くなってしまうので、ふふっ。"
"10040070-70" = "[s9] \"……えっ？\"\n[s10] \"気になるような……。\""
"10040070-73-ノア" = "まあまあ。それより先生、そろそろ到着です。"
"10040070-74-ノア" = "……皆さん、お待ちかねですよ。"
"10040070-84-マキ" = "え、刺しちゃうの？そこでいいの？"
"10040070-85-コタマ" = "統計を踏まえると、そこは良くないのでは……。"
"10040070-86-ユウカ" = "独立試行だから、どこを刺しても同じなのはそうだけど……。"
"10040070-87" = "[ns11] \"……みんな集まってるね。\"\n[ns12] \"盛り上がってるみたいだね。\""
"10040070-90-コユキ" = "あ～もう！私の番なんですから、[ruby=がいや]外野[/ruby]は静かにしててください！！"
"10040070-91-チヒロ" = "なんでもいいから、早めにお願い。"
"10040070-92-コユキ" = "言われなくともやりますよ～！#nここが大丈夫なら、私の勝ち……！"
"10040070-93-コユキ" = "そぉれえええええ！！"
"10040070-98-コユキ" = "ああああー！なんでぇぇえええ！！こんなのクソゲーです！！"
"10040070-103" = "（次のゲームから参加して、みんなと一緒に楽しんだ）"
"10040070-104-ユウカ" = "……あ、しまった。"
"10040070-105-コユキ" = "あ～！もう何やってるんですか！！"
"10040070-111-コユキ" = "ちょ、ああああああ！！"
"10040070-112" = "（……その後、三連敗したコユキは、涙を流しながらしばらく不貞腐れていた）"
"10040070-114" = "（……数時間後）"
"10040070-117-ノア" = "もうこんな時間……日付も変わっちゃいますね。"
"10040070-118-ノア" = "コユキちゃんは……寝てしまいましたか。"
"10040070-119-ノア" = "カウントダウンするって言ってたのに。ふふっ。"
"10040070-120-ノア" = "無理に起こすのも可愛そうですし……。"
"10040070-121-ノア" = "仕方ないので、あとは起きている方だけで――"
"10040070-122-ノア" = "……？"
"10040070-123-ノア" = "まあ……。"
"10040070-130" = "[ns13] \"……みんな寝てるね。\"\n[ns14] \"誰も起きてないみたい。\""
"10040070-133-ノア" = "あらあら……。"
"10040070-134-ノア" = "コユキちゃんやマキちゃんはともかく……ちょっと意外ですね。"
"10040070-135-ノア" = "ヴェリタスの皆さんやユウカちゃんまで……。"
"10040070-136-ノア" = "はしゃいでましたし、そのせいでしょうか？"
"10040070-137" = "[s15] \"普段遅くまでがんばってるし……。\"\n[s16] \"こういう時くらい寝かせてあげよう。\""
"10040070-140-ノア" = "ええ、そうですね。"
"10040070-141-ノア" = "ですが、がんばっているのは先生もなのでは……？"
"10040070-142-ノア" = "……もしかしてですが。"
"10040070-143-ノア" = "私が起きているから、でしょうか……。"
"10040070-144-ノア" = "先生は、そういうところで気をつかう方ですもんね。"
"10040070-145-ノア" = "……あら、違いましたか？"
"10040070-146-ノア" = "ふふっ、本当ですか？そうじゃないと言い切れます？"
"10040070-147-ノア" = "そんなに必死に否定されると、余計に怪しく思えてきちゃいますよ。"
"10040070-151-ノア" = "冗談です。ふふっ。"
"10040070-152-ノア" = "ちゃ～んと、信じてますよ。"
"10040070-153-ノア" = "さて、私も寝てしまう前に……。"
"10040070-157" = "[ns17] \"……ノア？\"\n[ns18] \"どこに行くの？\""
"10040070-160-ノア" = "もうすぐ日付が変わってしまいますから。#n新年のカウントダウンをしようと思いまして。"
"10040070-161-ノア" = "でも、皆さんを起こしたら申し訳ないですし……。"
"10040070-162-ノア" = "場所を移した方がいいかなと。"
"10040070-170-ノア" = "……先生は、こんな時間に女の子を一人で出歩かせたりしませんよね？"
