[translation]
"10040080-1" = "第8話;年を越しても同じ日を"
"10040080-3-ノア" = "……ここにしましょうか。"
"10040080-7-ノア" = "まだ灯りがこんなに……もう遅い時間なのに。"
"10040080-8-ノア" = "夜遅くまで研究している生徒が多いので、#nミレニアムではいつものことなのですが……。"
"10040080-10-ノア" = "今日は特に、明るく感じます。#n年越しで起きている方が多いからでしょうか。"
"10040080-11-ノア" = "でも不思議です。#n年が変わっても、明日が変わるわけではないのに。"
"10040080-12-ノア" = "それでも多くの方が、年の終わりを見届けて、#n新しい年の始まりを祝うんですよね。"
"10040080-13-ノア" = "もしかすると、特に理由なんてないのかも。"
"10040080-14-ノア" = "親しい人と一緒に遊んだり、ご飯を食べたりしたいだけで……。"
"10040080-15-ノア" = "年越しのお祝いは、その口実に過ぎない……#nいわば、建前なのかもしれません。"
"10040080-16-ノア" = "誰もが抱くとても単純な想いが、そうさせるのでしょうか。"
"10040080-17-ノア" = "楽しい時間を過ごしたいだとか……。"
"10040080-18-ノア" = "誰かと一緒に過ごして、その思い出を残したいだとか……。"
"10040080-19-ノア" = "あるいは――"
"10040080-22-ノア" = "……誰かに自分を刻みつけたい、とか。"
"10040080-23-ノア" = "ふふっ、なんだか回りくどいですね。"
"10040080-24-ノア" = "そんなことしてたら、単純だった想いがこんがらがってしまいそうです。"
"10040080-25-ノア" = "……なんて、こんなこと言えた義理じゃないですよね。"
"10040080-26-ノア" = "私だって、回りくどいことばかりしてますから。今日だけで、何度も。"
"10040080-27" = "[ns1] \"回りくどいのが許せなかったり？\"\n[ns2] \"何か気になってるみたいだね？\""
"10040080-30-ノア" = "……う～ん、そうですね。"
"10040080-31-ノア" = "人と良好な関係を築くうえで、多少必要なことはわかっています。"
"10040080-32-ノア" = "それに回りくどいやりとりをしていても、人は真意を察しあうことができますから。"
"10040080-33-ノア" = "だから、虚飾だなんて悪く言うつもりはありません。"
"10040080-34-ノア" = "例えばユウカちゃんやコユキちゃんにだって#n回りくどいところはあります。#nけど、考えていることはわかりやすいですよね。"
"10040080-35-ノア" = "ミレニアムの他の子たちだってそうです。"
"10040080-36-ノア" = "一見、回りくどさの権化に見えるリオ会長だって……ちゃんと考えがわかります。"
"10040080-37-ノア" = "……どうしました？"
"10040080-38-ノア" = "ノア自身はどうなの、ですか？"
"10040080-39-ノア" = "ふふっ。それを訊いちゃいますか。"
"10040080-40-ノア" = "そうですね……。"
"10040080-45-ノア" = "私は――"
"10040080-46-ノア" = "ご存知のとおり、こういう[ruby=たち]性質[/ruby]ですから。#n本音とは裏腹に、分かりにくいとよく言われちゃいます。"
"10040080-47-ノア" = "……ダメですね。今の発言すら、回りくどかったですよね。"
"10040080-48-ノア" = "ですが、これでよくわかったのではないでしょうか？"
"10040080-51" = "[ns] \"うん。\""
"10040080-53" = "[ns3] \"でも、私は気にしすぎなくていいと思うよ。\"\n[ns4] \"たとえノアがどんなに回りくどくても……。\"\n[ns5] \"本当の気持ちが変わるわけじゃないから。\""
"10040080-57-ノア" = "そう……ですね。"
"10040080-58-ノア" = "ふふっ。"
"10040080-59-ノア" = "……改めて、腑に落ちました。"
"10040080-60-ノア" = "やっぱりこれですよね。皆さんが先生と話したがる理由って。"
"10040080-61-ノア" = "変に回りくどい話し方をする必要がなくて、#nとても楽な気持ちでいられますもんね。"
"10040080-62-ノア" = "……それに、無理をして素直になる必要もないですから。"
"10040080-66-ノア" = "もしかして、ですが――"
"10040080-67-ノア" = "先生は、お見通しなのでしょうか？#n分かりにくいと言われる私が、こんな時間まで#nご一緒させていただいている理由を。"
"10040080-68-ノア" = "分かっていてなお、付き合ってくれている……ということですよね。"
"10040080-69-ノア" = "こんな真夜中に、同じ夜の光に照らされて、#n年越しの大事な時間を共にする、その意味を。"
"10040080-70-ノア" = "このまま先生とふたりきりでいても――"
"10040080-71-ノア" = "問題は……ないのですね？"
"10040080-72-ノア" = "本当に、いいんですか？"
"10040080-73-ノア" = "もしかすると……。"
"10040080-74-ノア" = "良くないことを考えているかもしれませんよ？"
"10040080-75" = "[s6] \"それって、さっき言ってた建前なんじゃないかな。\"\n[s7] \"本当の気持ちが大事なんだったよね。\""
"10040080-78-ノア" = "…………ふふっ。"
"10040080-79-ノア" = "こんなだから、分かりにくいと言われてしまうんですよね。#nきっとこれが、[ruby=うしお]生塩[/ruby]ノアの限界なんです。"
"10040080-80-ノア" = "でも先生には私の……#n言えないでいる本当の気持ちが、分かるんですよね。"
"10040080-81-ノア" = "……代わりに、言葉にしていただけませんか、先生？"
"10040080-85" = "[ns] \"うん。\""
"10040080-87" = "[ns8] \"ノアだって、私の生徒なんだから。\"\n[ns9] \"気をつかったりしなくていいんだよ。\""
"10040080-90-ノア" = "…………。"
"10040080-91-ノア" = "……………………。"
"10040080-92-ノア" = "……ふぅ。"
"10040080-93-ノア" = "ありがとうございます、先生。"
"10040080-102-ノア" = "そう言ってくれると思っていました。"
"10040080-106-ノア" = "そして……あけましておめでとうございます、先生。"
"10040080-107-ノア" = "これからも――"
"10040080-111-ノア" = "私たちのことを、よろしくお願いしますね。"
"10040080-121-ノア" = "……先生。"
"10040080-126-ノア" = "今日のことは、秘密ですからね。ふふっ。"
"10040080-128" = "（その後、ノアと一緒に散らかった反省部屋を整理した）"
"10040080-129" = "（そしてノアが寝たことを確認してから、シャーレに帰ったのだった）"
"10040080-131" = "（……翌日の午後）"
"10040080-132-ユウカ" = "せ～ん～せ～い～！！"
"10040080-133" = "[s10] \"ちょっと、休ませて……。\"\n[s11] \"もうこれ以上は、無理……。\""
"10040080-136-ユウカ" = "なに言ってるんですか！？#nまだこんなに溜まってるんですから、ダメです！"
"10040080-137-ユウカ" = "みんなで助けに来てあげたんですから、頑張ってください！"
"10040080-138-マキ" = "そうだよ～。#n着替える時間ももらえないまま、連れてこられたんだから。"
"10040080-139-ハレ" = "サポートするって言ったのは、こういう意味じゃなかったのに……。"
"10040080-141-コタマ" = "…………。"
"10040080-142-コタマ" = "ここなら……。"
"10040080-143-チヒロ" = "コタマ、ストップ。"
"10040080-144-コタマ" = "……っ。"
"10040080-146-コユキ" = "うぅっ……ここでもパスワード解析させられるなんて。"
"10040080-147-コユキ" = "私に自由はないんですかぁ……。"
"10040080-148-ノア" = "……ふふっ。#n昨日はあんなに静かだったのに、もう元気いっぱいなんですね。"
"10040080-149-コユキ" = "し、静か……？"
"10040080-150-コユキ" = "ハチャメチャしてたはずなのに……。"
"10040080-151-ユウカ" = "コユキ！手が止まってるわよ！"
"10040080-152-コユキ" = "うあぁぁ！不幸だあぁぁ！"
"10040080-153-ユウカ" = "みんなも分かってるわよね？#n先生の年末調整が終わるまで帰さないんだから！"
"10040080-154-ユウカ" = "キリキリ手を動かしなさい！！"
"10040080-155-一同" = "はーい。"
"10040080-156-ユウカ" = "先生も！！一番頑張らなきゃいけないのは先生なんですからね！？"
"10040080-157" = "[s12] \"はい……。\"\n[s13] \"私のせいで……みんなごめんね。\""
"10040080-164-ノア" = "……。"
"10040080-165-ノア" = "……ふふっ。"
"10040080-170-ノア" = "本当に……いつもと変わらない一日が来ましたね。"
"10040080-171" = "秘密のミッドナイトパーティー～オニの手は鐘と共に～"
