[translation]
"10016085-2-ミレニアムの選手A" = "騎馬戦が終わったら、残りの大きな競技は学園対抗リレーくらいだよね？"
"10016085-3-ミレニアムの選手B" = "うん、そうだよ。#n総合優勝に大きな影響があるような競技はほぼ終わったし。"
"10016085-4-ミレニアムの選手A" = "まさか万年最下位争いをしていたミレニアムが、総合優勝を狙える位置にいるなんて……。#n今回の[ruby=こうりんたいさい]晄輪大祭[/ruby]は例年と違って、ちょっと変なところが多いよね。"
"10016085-5-ミレニアムの選手B" = "聞いた話だけど、シャーレの先生が運動を苦手とする生徒たちも楽しめるように、競技の内容を調整してくれたんだって……そのおかげかな？"
"10016085-6-ミレニアムの選手A" = "騎馬戦の優勝候補筆頭だったゲヘナとトリニティが、予選で早々にぶつかり合っていなくなったのも大きいね。"
"10016085-7-ミレニアムの選手A" = "今なら百鬼夜行程度、私たちでも勝てるはず……！"
"10016085-8-ミレニアムの選手B" = "よし！次の騎馬戦もこの勢いで、ミレニアムの総合優勝を――"
"10016085-9-ミレニアムの選手B" = "ん？あれは一体……。"
"10016085-19-イズナ" = "さささっ！これで準備は完璧ですね！"
"10016085-20-イズナ" = "ハスミ殿のお力を借りて完成した忍法……築城の術！"
"10016085-21-ツクヨ" = "ほ、本当に大丈夫でしょうか……？"
"10016085-22-ツクヨ" = "だいぶ不安定ですし、ちょっと押されたら、すぐ倒れちゃいそうですけど……。"
"10016085-23-チセ" = "ゆ～らゆら～"
"10016085-24-ハスミ" = "大丈夫です。左右のお二人には、大切な役割がありますから。"
"10016085-25-ハスミ" = "カエデさんとイズナさんは横と後ろから接近する敵に気を配って、チセさんに場所を報告してください。"
"10016085-26-イズナ" = "索敵の任ですね……分かりました！"
"10016085-27-カエデ" = "それなら任せて！#n飛んでくカブトムシを追いかけるのに比べたら簡単なんだから！"
"10016085-28-ミレニアムの選手A" = "なんか百鬼夜行にすごい変な騎馬がいるんだけど……。"
"10016085-29-ミレニアムの選手B" = "ちょっと押したらすぐに崩れちゃいそうだね……"
"10016085-30-ミレニアムの選手B" = "よし！まず最初にあいつから倒しちゃおっか！"
"10016085-31-ミレニアムの選手A" = "合点承知！行くよ！"
"10016085-35-イズナ" = "チセ殿！北北東から敵が接近中です！"
"10016085-36-ツクヨ" = "う、うあぁ……も、もう始まったんですか……？"
"10016085-42-ミレニアムの選手A" = "お、大きい……！？"
"10016085-43-ミレニアムの選手A" = "遠くで見た時は分からなかったけど……これじゃあどうやっても手が届かないよ！"
"10016085-48-ミレニアムの選手B" = "だ、大丈夫！体当たりで騎馬の重心を崩せば……！"
"10016085-50-チセ" = "ぼうし～"
"10016085-51-チセ" = "げっと～。"
"10016085-52-ミレニアムの選手A" = "えっ、いつの間に！？"
"10016085-53-ミレニアムの選手B" = "くぅ！勝てると思ったのに！"
"10016085-55-イズナ" = "流石はチセ殿ですね！電光石火の如くでした！"
"10016085-56-カエデ" = "ふっふーん！チセ先輩は百鬼夜行・カルタ最強決定戦のチャンピオンだからね！"
"10016085-57-カエデ" = "腕の動きなら誰にも負けないよ！"
"10016085-59-ハスミ" = "騎手は敵に狙われる危険な役割ですが、それはつまり敵の帽子を奪う重要な存在でもあるということ……。"
"10016085-60-ハスミ" = "両翼のバランスこそ少し不安定ですが、騎手にチセさんをお任せして正解でしたね。"
"10016085-61-カエデ" = "チセ先輩、右から来るよ！"
"10016085-65-ミレニアムの選手" = "隙を突いて、奇襲をかければ――"
"10016085-71-チセ" = "ふたつめ～"
"10016085-72-ミレニアムの選手" = "ダメかっ……！"
"10016085-74-シノン" = "ミレニアム対百鬼夜行の騎馬戦決勝ですが、何とも不思議な光景です！"
"10016085-75-シノン" = "百鬼夜行のチセ選手が、開始早々ミレニアムから帽子を2つ奪い取りました！"
"10016085-76-シノン" = "体勢こそアンバランスですが、まるで砦のような防御力を前にミレニアムの騎馬は太刀打ちできず各個撃破されています！"
"10016085-77-シノン" = "まだまだ熾烈な総合優勝争いをしているミレニアムとしては、負けられない1戦となりそうですね！#nさあ、この決勝戦を制するのは果たしてどちらの学園でしょうか！"
"10016085-79-ミレニアムの選手" = "このままじゃ百鬼夜行にまるで歯が立たないよ……。"
"10016085-80-ミレニアムの選手" = "マキ！助けて！！"
"10016085-81-マキ" = "ん、私？"
"10016085-82-マキ" = "いや～私はハレ先輩の代わりに出場してるだけだよ？"
"10016085-83-マキ" = "それに私も特別運動が得意ってわけじゃないし……"
"10016085-84-ミレニアムの選手" = "でも、マキはあの「ヴェリタス」のハッカーなんでしょ？"
"10016085-85-ミレニアムの選手" = "何かヴェリタスの技術で対抗できたりしない？"
"10016085-89-マキ" = "え～……チヒロ先輩にバレたらまた怒られるんだけど……。"
"10016085-90-マキ" = "そこまでいうなら……まぁ、仕方ないよね。"
"10016085-91-マキ" = "ハレ先輩から借りた、この「アテナ3号」を使うよ！"
"10016085-93-カエデ" = "うぅ……いつの間にか百鬼夜行の騎馬は私たちだけ……。"
"10016085-94-カエデ" = "それなのに、まだ相手の騎馬が3つも残ってるよ！"
"10016085-95-ツクヨ" = "私たちが取った帽子を数えると……1つ、2つ……えっと……。"
"10016085-96-ツクヨ" = "の、残りの騎馬は1つのはずです！"
"10016085-97-イズナ" = "……あれ？数が合いませんよ？#nややっ、これは一体どういうことでしょう？"
"10016085-102-マキ" = "あはは、やっと気付いたの？"
"10016085-103-マキ" = "これは私たちの騎馬を投影したホログラム映像だよ！"
"10016085-104-マキ" = "「アテナ3号」に新しく搭載されたホログラム投射機能を使って、ダミーを生成したんだ！"
"10016085-105-マキ" = "いひひ～、どれが本物か見分けられるかな？"
"10016085-107-カエデ" = "なにそれ！競技中に道具を使うなんて反則じゃないの！？"
"10016085-108-ハスミ" = "……残念ながら、そもそも道具を使う生徒の想定をしていないので、反則とは言えません。"
"10016085-109-ハスミ" = "規定上、騎馬戦の競技中に銃や爆弾の使用は禁止されています。#nですが、ホログラムの使用を禁止するとは書かれていませんので……。"
"10016085-110-ハスミ" = "しかし、まさかそんな方法があるなんて……。#n次回の晄輪大祭ではホログラム関連の規定を追加する必要がありそうですね。"
"10016085-111-イズナ" = "同時に二つの分身を生み出すとは……流石ミレニアムですね！#n最後まで油断できません！"
"10016085-112-ハスミ" = "向こうは本物を見分ける時間を与えないためにも、すぐに仕掛けてくるはずです。"
"10016085-113-ハスミ" = "イズナさん、ツクヨさん。お二人の特技をお見せする時です！"
"10016085-114-ツクヨ" = "わ、私たちの特技、ですか……？"
"10016085-115-ハスミ" = "はい……それは――忍術です。"
"10016085-116-イズナ" = "……！#nはい！忍術です！"
"10016085-117-マキ" = "……忍術？それってマジックみたいなものだよね？#nなんか面白そうじゃん！"
"10016085-118-マキ" = "それじゃあ、ミレニアムのホログラムと百鬼夜行の忍術――どちらが相手の目を欺けるか勝負だね！"
"10016085-119-マキ" = "さぁさぁ、三方向から同時に攻めるよー！"
"10016085-123-ツクヨ" = "うぅ……。"
"10016085-124-ツクヨ" = "つ、ツクヨ流忍術！"
"10016085-129-マキ" = "……捕まえたっ！#nこれでミレニアムの勝――"
"10016085-133-マキ" = "あれ？なんでこんなところにキツネのぬいぐるみが……？"
"10016085-134-マキ" = "帽子はどこに……？"
"10016085-139-チセ" = "――こっち。"
"10016085-140-マキ" = "う、うわっ！そっちにいたの！？"
"10016085-147-マキ" = "うぅ、やられちゃった……。"
"10016085-148-チセ" = "……これで最後。"
"10016085-149-カエデ" = "やったぁ！チセ先輩ならできるって信じてたよ！"
"10016085-150-ツクヨ" = "あぅ……もう少しで落としちゃうところでした……。"
"10016085-152-イズナ" = "さすがツクヨ殿！空蝉の術をあの一瞬で完璧に再現するとは……イズナ感激です！"
"10016085-153-イズナ" = "チセ殿とキツネのぬいぐるみをすり替えるタイミングが少しでも遅れていたら、#nきっと帽子を取られていました！"
"10016085-155-チセ" = "たかいたか～い、面白かった。"
"10016085-156-ツクヨ" = "は、はは……ま、またできる自信はないです……。"
"10016085-157-ツクヨ" = "そ、それよりチセ先輩……髪が抜けそうなんですが……そろそろ離していただけると……。"
"10016085-159-シノン" = "チセ選手、曲芸のような動きを見せて、見事マキ選手の帽子を奪いました！"
"10016085-160-シノン" = "先ほどの攻防でミレニアム最後の騎馬が落ちたので……"
"10016085-161-シノン" = "百鬼夜行チームの勝利です！"
"10016085-163-ハスミ" = "……よし！"
"10016085-167-ハスミ" = "こほん……私らしくありませんね。#n少し冷静さを欠いておりました。"
"10016085-171-イズナ" = "ハスミ殿、ハスミ殿～！イズナ、頑張りました～！"
"10016085-172-イズナ" = "この勝利は全て、ハスミ殿が考えてくださった奇策のおかげです！"
"10016085-173-ハスミ" = "はい。ずっと見ていましたよ。#n皆さん、本当に素晴らしい活躍でした。"
"10016085-174-ツクヨ" = "部長が倒れちゃった時は、もうダメだと思ってたのに……"
"10016085-175-ツクヨ" = "わ、私みたいな存在にも役割をくださって……。"
"10016085-176-ツクヨ" = "本当に、本当にありがとうございます……うぅ、うわ～ん……。"
"10016085-177-ハスミ" = "もちろんお役に立てたのは光栄ですが、皆さんの頑張りがあってこそですから。"
"10016085-178-イズナ" = "ハスミ殿に感謝です！#nそれにイズナ、とっても楽しかったです！"
"10016085-179-イズナ" = "学園こそ違いますが、力を合わせて長所を活かし、見事勝利を手にした瞬間は……"
"10016085-180-イズナ" = "まるで柴犬ワン蔵監督の作品に登場する主人公のような気分でした！"
"10016085-181-イズナ" = "またハスミ殿と一緒に競技がしたいです！"
"10016085-182-ハスミ" = "ですが……私はトリニティの生徒ですよ……？"
"10016085-183-ハスミ" = "次は敵として戦うことになるかもしれません。"
"10016085-184-イズナ" = "それでも大丈夫ですっ！"
"10016085-185-イズナ" = "ハスミ殿と一緒にできるなら、敵でも味方でも関係ありません！#nきっと楽しいです！えへへっ。"
"10016085-186-カエデ" = "そうそう！私もすっごく楽しかったよ！"
"10016085-187-ツクヨ" = "わ、私も楽しかったです……！"
"10016085-191-ハスミ" = "ふふ、そうですか。それは良かったです。"
"10016085-192-ハスミ" = "……だからといって、手加減はしませんよ？"
"10016085-193-ハスミ" = "トリニティの生徒として、競技では常にベストを尽くしますからね。"
"10016085-195-イズナ" = "はいっ、イズナも全力で戦います！"
"10016085-196-ツクヨ" = "ぜ、ぜひ、お願いします！"
"10016085-197-カエデ" = "にひひっ、またね～！"
