[translation]
"2006106-1" = "しがらみ"
"2006106-2" = "（カスミの指定した場所に向かった）"
"2006106-7" = "（カスミが誰かと険悪なムードで話している）"
"2006106-8" = "（……見たことない制服の生徒だ）"
"2006106-10-正体不明の生徒" = "[ruby=きぬがわ]鬼怒川[/ruby]カスミ……抜け出せたと思ったか？"
"2006106-14-カスミ" = "そちらの顔色をうかがわなきゃならんのか？"
"2006106-15-正体不明の生徒" = "違うとでも？"
"2006106-17" = "[ns] \"カスミ。\""
"2006106-21-カスミ" = "先生？なぜここに……。"
"2006106-22-カスミ" = "……ああ、私が呼んだのだったな。"
"2006106-24-正体不明の生徒" = "……先生？"
"2006106-29-正体不明の生徒" = "今日は運が良かったな、鬼怒川カスミ。"
"2006106-30-カスミ" = "今日は？[ruby=・]い[/ruby][ruby=・]つ[/ruby][ruby=・]も[/ruby]と間違えているぞ。"
"2006106-32-正体不明の生徒" = "だが気をつけることだ。ボーデンザッツはいつだって見ている。"
"2006106-33-カスミ" = "あんなどん底からか？好きにすればいいさ。"
"2006106-44-カスミ" = "先生、すまない！"
"2006106-45-カスミ" = "呼び出しておいて悪いが、都合が悪くなってしまった。日を改めてくれるか？"
"2006106-46" = "[s] \"大丈夫？\""
"2006106-47-カスミ" = "もちろん。"
"2006106-51-カスミ" = "とにかく、早く帰ってくれ。本当にすまない！"
"2006106-53" = "（カスミに強く促され、その場を後にした）"
