[translation]
"2006106-1" = "しがらみ"
"2006106-2" = "（カスミの指定した場所に向かった）"
"2006106-3" = "（カスミが誰かと険悪なムードで話している）"
"2006106-4" = "（……見たことない制服の生徒だ）"
"2006106-5-正体不明の生徒" = "[ruby=きぬがわ]鬼怒川[/ruby]カスミ……抜け出せたと思ったか？"
"2006106-6-カスミ" = "そちらの顔色をうかがわなきゃならんのか？"
"2006106-7-カスミ" = "違うとでも？"
"2006106-8" = "[ns] \"カスミ。\""
"2006106-9-カスミ" = "先生？なぜここに……。"
"2006106-10-カスミ" = "……ああ、私が呼んだのだったな。"
"2006106-11-正体不明の生徒" = "……先生？"
"2006106-12-正体不明の生徒" = "今日は運が良かったな、鬼怒川カスミ。"
"2006106-13-カスミ" = "今日は？[ruby=・]い[/ruby][ruby=・]つ[/ruby][ruby=・]も[/ruby]と間違えているぞ。"
"2006106-14-正体不明の生徒" = "だが気をつけることだ。ボーデンザッツはいつだって見ている。"
"2006106-15-カスミ" = "あんなどん底からか？好きにすればいいさ。"
"2006106-16-カスミ" = "先生、すまない！"
"2006106-17-カスミ" = "呼び出しておいて悪いが、都合が悪くなってしまった。日を改めてくれるか？"
"2006106-18" = "[s] \"大丈夫？\""
"2006106-19-カスミ" = "もちろん。"
"2006106-20-カスミ" = "とにかく、早く帰ってくれ。本当にすまない！"
"2006106-21" = "（カスミに強く促され、その場を後にした）"
