[translation]
"2006103-1" = "適切な温度について"
"2006103-2" = "[ns] \"ふぅ……。\""
"2006103-3-カスミ" = "お、上がったか。"
"2006103-4-カスミ" = "堪能してもらえたかね？"
"2006103-5" = "[s1] \"良い湯加減だったよ。\"\n[s2] \"最高だった……。\""
"2006103-6-カスミ" = "そうかそうか。みんなにも言ってやってくれ。喜ぶだろうからな。"
"2006103-7-カスミ" = "にしても、ここに温泉を作ったのは正解だった。道路を潰した甲斐があったな！"
"2006103-8" = "[s] \"……なんて？\""
"2006103-9-カスミ" = "ああ、気にする必要は無い。温泉はぬる湯より――"
"2006103-10-温泉開発部の部員" = "部長、大変！風紀委員が来た！！"
"2006103-11-カスミ" = "うん？計算通りなら、まだ2時間程度の猶予はあったはずだが……。"
"2006103-12-カスミ" = "ちっ、見回りのスケジュールが変わったのか？ツイてないな。"
"2006103-13-カスミ" = "……致し方あるまい。"
"2006103-14-カスミ" = "温泉で体もほぐれたことだ。ひとっ走りいこうじゃあないか！"
"2006103-15" = "[s] \"ええっ！？\""
"2006103-16-カスミ" = "ハーハッハッハッハ！あっさり捕まってしまったな！"
"2006103-17" = "[s3] \"どうして私まで……。\"\n[s4] \"なんでこんなことに……。\""
"2006103-18-カスミ" = "心配しなくとも大丈夫さ。"
"2006103-19-カスミ" = "私はともかく、先生の潔白はすぐ明らかになるだろうからな。"
"2006103-20-カスミ" = "私とて長居するつもりはないがね。"
"2006103-21-カスミ" = "にしても、よもや先生と一緒に放り込まれる日が来るとは。"
"2006103-22-カスミ" = "人生とは予想外なことばかりだ。"
"2006103-23-カスミ" = "まあ、これもまた醍醐味か。"
"2006103-24-カスミ" = "……先生？"
"2006103-25-カスミ" = "さっきから静かだが……。"
"2006103-26-カスミ" = "……もしや怒っているのか？"
"2006103-27-カスミ" = "弱ったな……今回ばかりは弁解の余地が……。"
"2006103-28-カスミ" = "強いて言えば、ちゃんと確認せず連行した風紀委員にも多少なり非は――"
"2006103-29" = "[s5] \"あ、違う違う。\"\n[s6] \"なんか、この間とカスミの印象が変わった気がして。\""
"2006103-30-カスミ" = "何の話だ？"
"2006103-31-カスミ" = "変わった……私が？"
"2006103-32-カスミ" = "……ああ、なるほど。それは少し違うな。"
"2006103-33-カスミ" = "[ruby=・]私[/ruby][ruby=・]は[/ruby]変わっていない。至っていつも通りだ。"
"2006103-34-カスミ" = "温泉のためなら何だってする、爆破と開発をこよなく愛する狂人。"
"2006103-35-カスミ" = "……そうだろう？"
"2006103-36" = "[s7] \"どっちが素なの？\"\n[s8] \"カスミの本心は？\""
"2006103-37-カスミ" = "有利な方さ！"
"2006103-38-カスミ" = "……そんな目で見ないでくれたまえ。どう思われるかに興味は無いのだよ。#n大事なのは、どう思わせるか、だ。"
"2006103-39-カスミ" = "先生といる時は大人しくしている方が円満に終わりやすい。"
"2006103-40-カスミ" = "しかし残念ながらほとんどの場合……。"
"2006103-41-カスミ" = "だから、そうだな……大人しく捕まったと思わせておいて――"
"2006103-42-カスミ" = "げほっ、げほっ……！"
"2006103-43-カスミ" = "思いの外ホコリが舞うな。次は別の方法にしよう。"
"2006103-44-温泉開発部の部員A" = "助けに来たよ！"
"2006103-45-温泉開発部の部員A" = "しばらく隠れてたら、みんなどっか行っちゃったの！部長の言う通りだったね！"
"2006103-46-カスミ" = "そりゃあ本隊がまだだからな。陽動を仕掛ければ釣られてくれるだろうさ。"
"2006103-47-カスミ" = "……それで、何を話していたのだったか。"
"2006103-48-カスミ" = "ああ、そうだ。#n温泉は熱いに越したことは無いってことさ。"
