[translation]
"2006105-1" = "温泉街のカリスマ"
"2006105-2" = "（カスミが送ってくれた場所へ向かった）"
"2006105-3" = "（宿を潜伏場所にしているのかと思いきや……）"
"2006105-4-カスミ" = "先生、こっちだ！"
"2006105-5-カスミ" = "複雑な道だっただろう？迷わなかったか？"
"2006105-6-カスミ" = "ん？どうした、キョトンとして。"
"2006105-7" = "[s1] \"ここ、ブラックマーケットだよね……？\"\n[s2] \"思ってたのと違うというか……。\""
"2006105-8-カスミ" = "なるほど。"
"2006105-9-カスミ" = "その予想は正解だ。最近はここを間借りしている。"
"2006105-10-カスミ" = "なにぶん、お尋ね者の身だからな。のほほんと普通の宿になど泊まれんよ。"
"2006105-11-カスミ" = "とはいえ路上で寝ているわけではないから、その辺は安心してくれ。"
"2006105-12-カスミ" = "ここにはここのルールがあるんだ。"
"2006105-13-カスミ" = "それにブラックマーケットは……いや、厳密には違うな。"
"2006105-14-カスミ" = "多くの者がここを「ブラックマーケット」と呼ぶが、その実は名もない路地裏にすぎない。"
"2006105-15-カスミ" = "人が集まれば、日の当たらぬ場所もできるものだ。#nこれまで先生が訪れた場所にもそれなりに――"
"2006105-16-カスミ" = "ん、無駄話が過ぎたな。"
"2006105-17-カスミ" = "せっかく先生の時間をもらっているのだから、有意義に使わなくては！"
"2006105-18-カスミ" = "では行こうか。"
"2006105-19-カスミ" = "む？行き先？ああ、まだ言っていなかったか。"
"2006105-20-カスミ" = "温泉開発部の部長が動くんだ。"
"2006105-21-カスミ" = "何をするかなんて決まっているだろう？"
"2006105-22-丁寧なブラックマーケットの商人" = "……はい、仲介人への確認は済んでおります。"
"2006105-23-丁寧なブラックマーケットの商人" = "[ruby=きぬがわ]鬼怒川[/ruby]カスミ様、ご本人に間違いありませんね。#n早速取引を始められればと思うのですが……。"
"2006105-24-丁寧なブラックマーケットの商人" = "そちらの大人は？"
"2006105-25-カスミ" = "ああ、気にしなくていい。"
"2006105-26-丁寧なブラックマーケットの商人" = "取引に同席させるおつもりで……？"
"2006105-27-カスミ" = "ん？聞こえなかったか？"
"2006105-28-カスミ" = "気にしなくていいと言ったんだ。"
"2006105-29-丁寧なブラックマーケットの商人" = "……失礼しました。#nでは取引に移りましょう。"
"2006105-30-丁寧なブラックマーケットの商人" = "ご希望の資材はすぐにでも手配可能です。#nただ少々数が多く……納品にはバージ船が必要になるかと。"
"2006105-31-カスミ" = "であれば決行は夜だな？"
"2006105-32-丁寧なブラックマーケットの商人" = "はい。日時と場所に制限がありますが、そちらは――"
"2006105-33" = "（カスミは商人と密かなやりとりを交わした）"
"2006105-34-カスミ" = "……ふむ、こんなところか。良い取引になったな。#nこっちには知り合いが居なかったものでね。助かったよ。"
"2006105-35-丁寧なブラックマーケットの商人" = "こちらこそ、カスミ様とご縁を持てて嬉しく思います。今後ともご贔屓に。"
"2006105-36-カスミ" = "もちろんだとも。"
"2006105-37-カスミ" = "では先生、次へ行こうか。"
"2006105-38" = "[s3] \"えっと……。\"\n[s4] \"何の取引だったの？\""
"2006105-39-カスミ" = "変な物ではないさ。"
"2006105-40-カスミ" = "温泉開発には資材が必要だろう？"
"2006105-41-カスミ" = "もちろん、いつもは普通のルートを使っている。#n毎度こんなことをしていては財布が持たんからな。"
"2006105-42-カスミ" = "しかし今回は風紀委員会に全部没収されてしまったんだ。"
"2006105-43-カスミ" = "そんな状況で、いつものルートを使うわけにはいかないだろう？"
"2006105-44-カスミ" = "だから[ruby=・]存[/ruby][ruby=・]在[/ruby][ruby=・]し[/ruby][ruby=・]な[/ruby][ruby=・]い[/ruby][ruby=・]お[/ruby][ruby=・]金[/ruby]で[ruby=・]存[/ruby][ruby=・]在[/ruby][ruby=・]し[/ruby][ruby=・]な[/ruby][ruby=・]い[/ruby][ruby=・]物[/ruby]を買うのさ。"
"2006105-45-カスミ" = "我々は社会のために働いているというのに、風紀委員会は頭が固くていけないな。#nハーハッハッハッハ！"
"2006105-46" = "[s5] \"社会のため……？\"\n[s6] \"本当に資材だけなんだよね？\""
"2006105-47-カスミ" = "先生に嘘をついて何になる。"
"2006105-48-カスミ" = "はたまた……ブラックマーケットに来るような生徒という時点で、#n先生からすればアウトなのやもしれんがね。"
"2006105-49-カスミ" = "ん？そこは別に……？え、ああ、そうか……。"
"2006105-50-カスミ" = "いや、普通ではないのでは……？"
"2006105-51-カスミ" = "まあいい！次の場所へ行こう！"
"2006105-52-クールなブラックマーケットの商人" = "よお！何してんだ、こんなとこで。"
"2006105-53-クールなブラックマーケットの商人" = "[ruby=あね]姐[/ruby]さん、風紀委員会に捕まったんじゃなかったのか？"
"2006105-54-カスミ" = "すぐ出られたんだ。私のような模範囚も珍しいだろうな。"
"2006105-55-クールなブラックマーケットの商人" = "ぷはっ！言うことがクールだねぇ！"
"2006105-56-カスミ" = "どうだ？最近は。"
"2006105-57-クールなブラックマーケットの商人" = "いつも通りだよ。不発弾やら薬莢を拾ったり、ちょいと建材を拝借したり。#nガラクタの山で生きているようなもんさ。"
"2006105-58-クールなブラックマーケットの商人" = "まっ、それが生業なんだけどよ。#nんで、今日は何が欲しいんだ？"
"2006105-59-カスミ" = "見てもらった方が早い。ほら、リストだ。"
"2006105-60-クールなブラックマーケットの商人" = "ひゅーっ、さっすが羽振りがいいねえ！待ってな。すぐ用意する。"
"2006105-61-カスミ" = "頼むよ。"
"2006105-62-クールなブラックマーケットの商人" = "で……どうだ、考えてくれたか？"
"2006105-63-カスミ" = "む？"
"2006105-64-クールなブラックマーケットの商人" = "例の事業だよ。今もあちこちから連絡来てんだ。相当稼げるぞ？"
"2006105-65-カスミ" = "やらないと前に言ったはずだ。"
"2006105-66-クールなブラックマーケットの商人" = "良い腕持ってんのに勿体ねぇ……。"
"2006105-67-クールなブラックマーケットの商人" = "なんで訳わからんもんにハマって……。"
"2006105-68-カスミ" = "ん？"
"2006105-69-クールなブラックマーケットの商人" = "温泉なんてカネにならないだろ？姐さんならもっとデカい――"
"2006105-70-カスミ" = "あのなぁ。"
"2006105-71-カスミ" = "――喋りすぎだな？"
"2006105-72-クールなブラックマーケットの商人" = "お、おぉ……わりぃ。"
"2006105-73-クールなブラックマーケットの商人" = "怖がることないじゃないか。"
"2006105-74-カスミ" = "私たちはビジネスパートナーだろう？ほら、笑って笑って。"
"2006105-75-クールなブラックマーケットの商人" = "あ、う、うん。そうだな。"
"2006105-76-カスミ" = "話を戻すんだが――"
"2006105-77" = "（その後もカスミの「買い物」に付き合った）"
"2006105-78-カスミ" = "今日は世話になったな。これで次の開発も首尾よく進むだろう。"
"2006105-79-カスミ" = "……先生？どうかしたか？"
"2006105-80" = "[s7] \"いや、最近つくづく思うけど……。\"\n[s8] \"カスミはいろんな顔を持ってるんだね。\""
"2006105-81-カスミ" = "有利だからな。"
"2006105-82-カスミ" = "「私」というツールを使わない手はないのさ。"
"2006105-83" = "[s] \"それでいいの？\""
"2006105-84-カスミ" = "というと？"
"2006105-85" = "[s9] \"みんなに合わせるってことは……。\"\n[s10] \"いつも本心じゃないってことだよね。\""
"2006105-86" = "[ns11] \"大変そうだなって思って。\"\n[ns12] \"それで心配してる。\""
"2006105-87-カスミ" = "心配、か。"
"2006105-88-カスミ" = "それを[ruby=・]先[/ruby][ruby=・]生[/ruby]に言われてしまうと反論できないな。"
"2006105-89-カスミ" = "私の理解が正しければ――"
"2006105-90-カスミ" = "先生の前では本音をさらけ出していい。#nそんな心温まる励ましだと受け取ったが、合っているか？"
"2006105-91-カスミ" = "……お望みとあらば実践してみようか。"
"2006105-92" = "[wa:1900]― [log=카스미 수영복]知っているだろう？[/log]"
"2006105-93" = "― [log=카스미 수영복]この辺りは[wa:600]治安が悪いんだ。[/log]"
"2006105-94" = "― [log=카스미 수영복]ひと一人消えた程度じゃ、[wa:2160]誰も気づかない。[/log]"
"2006105-95" = "[wa:750]― [log=카스미 수영복]詰めが甘いよ、[wa:1640]先生。[/log]"
"2006105-96" = "― [log=카스미 수영복]一を識って、[wa:880]二を知らず、[wa:1030]だ。[/log]"
"2006105-97" = "[wa:580]― [log=카스미 수영복]先生が私を[wa:1320]助けようとすればするほど……[/log]"
"2006105-98" = "― [log=카스미 수영복]私にとって、[wa:2090]良い手駒となる。[/log]"
"2006105-99" = "[wa:540]― [log=카스미 수영복]そして――[wa:1250]そういうものであればあるほど、[/log]"
"2006105-100" = "― [log=카스미 수영복]手に入れたくなるというのが[wa:1390]人の性だ。[/log]"
"2006105-101" = "[wa:510]― [log=카스미 수영복]私の本性が[wa:1490]知りたいと言っていただろう……？[/log]"
"2006105-102" = "― [log=카스미 수영복]感想はいかがかな？[/log]"
"2006105-103" = "― [log=카스미 수영복]引き返したいと言っても――[wa:2970]もう遅いがね。[/log]"
"2006105-104" = "[wa:1900]― [log=카스미 수영복]……サプラーイズ！[/log]"
"2006105-105" = "― [log=카스미 수영복]それっぽかっただろう？[/log]"
"2006105-106" = "― [log=카스미 수영복]そう怖い顔をしないでくれ。[wa:2610]冗談だよ。[/log]"
"2006105-107-カスミ" = "こんなこともあり得るということだ。"
"2006105-108-カスミ" = "いつもニコニコしているからといって、その実とんでもない闇を抱えていないとも限らないのだよ。"
"2006105-109-カスミ" = "……下手に踏み込むと痛い目をみるかもしれんぞ？"
"2006105-110-カスミ" = "まあ、私は見た目通りだがね！ハーハッハッハッハ！"
