[translation]
"10036005-1" = "プロローグ"
"10036005-4-ブラックマーケット暴力団A" = "あいつ、どこに逃げやがった？"
"10036005-5-ブラックマーケット暴力団B" = "チッ、手こずらせやがって……！"
"10036005-11-ブラックマーケット暴力団B" = "いたぞ！撃て！"
"10036005-17-ブラックマーケット暴力団A" = "やったか！？"
"10036005-26-ブラックマーケット暴力団B" = "ぐっ……。"
"10036005-31-サオリ" = "……これで終わりだな。"
"10036005-35-サオリ" = "ブツはもらっていく。"
"10036005-39-サオリ" = "これが依頼の品だ。"
"10036005-40-ヘルメット団幹部" = "まさか、本当に成功させるとは……。"
"10036005-41-ヘルメット団幹部" = "よくやってくれたな！"
"10036005-42-ヘルメット団幹部" = "難しい依頼だったと思うが……どうやって成功させたんだ？"
"10036005-43-サオリ" = "特別なことは何もしていない。"
"10036005-48-サオリ" = "事前に対象の調査を徹底しただけだ。"
"10036005-49-サオリ" = "敵の戦力や配置、建物の構造を把握していれば、#n任務の成功率は自ずと上がる。"
"10036005-50-ヘルメット団幹部" = "……すごいな。"
"10036005-51-サオリ" = "……そろそろ報酬を。"
"10036005-52-ヘルメット団幹部" = "あぁ、ここにある。"
"10036005-56-サオリ" = "いち、に、さん……間違いないな。"
"10036005-57-サオリ" = "だが……。"
"10036005-59-ヘルメット団幹部" = "足りなかったか？#n何回か数えたから、間違いはないはずだが……。"
"10036005-60-サオリ" = "いや、額に問題はない……。"
"10036005-65-サオリ" = "（装備や弾薬の補充をしたら、食費を切り詰めても一週間しか……）"
"10036005-66-サオリ" = "（もっと実入りの良い仕事を探さなければ……）"
"10036005-70-ヘルメット団幹部" = "もしかして、金に困ってるのか？"
"10036005-71-ヘルメット団幹部" = "仕事の紹介なら、いくらでもしてやれるぞ。"
"10036005-72-サオリ" = "ほ、本当か？"
"10036005-73-ヘルメット団幹部" = "もちろんだ、それだけの腕があるなら安心して任せられる。#nやってみるか？"
"10036005-74-サオリ" = "ああ……頼む。"
"10036005-75-ヘルメット団幹部" = "直近で頼みたい案件なんだが……"
"10036005-76-ヘルメット団幹部" = "もうじき、「ヘルメット団総連合会」が開催されるのは知ってるか？"
"10036005-77-サオリ" = "……「総連合会」？"
"10036005-78-ヘルメット団幹部" = "そうだ。#n幹部の私が言うのもアレだが、今までのヘルメット団は大した組織じゃなかった。"
"10036005-79-ヘルメット団幹部" = "しかし、最近は事情が変わってきていてな。"
"10036005-80-ヘルメット団幹部" = "矯正局から危険な奴らが脱獄したから、#n組織を急ピッチで強化しなきゃいけなくなって……"
"10036005-81-ヘルメット団幹部" = "っと、話が逸れたな。"
"10036005-82-ヘルメット団幹部" = "総連合会は、全ヘルメット団員が集まる親睦会みたいなものだ。#nお祭りと言っても良いかもしれないな。"
"10036005-84-サオリ" = "……そこで何をすれば良い？"
"10036005-85-ヘルメット団幹部" = "実は……。"
"10036005-86-ヘルメット団幹部" = "今度の総連合会に、ブラックマーケットで有名なDJを招待したのさ。"
"10036005-87-ヘルメット団幹部" = "しかし、護衛が務まるようなヤツが見つからなくてな。"
"10036005-88-ヘルメット団幹部" = "どうだ、やってみないか？"
"10036005-89-サオリ" = "護衛か……。"
"10036005-90-サオリ" = "……いや、今の私は仕事を選んでいる場合じゃない。"
"10036005-91-サオリ" = "その仕事、引き受けさせてくれ。"
"10036005-92-ヘルメット団幹部" = "よし、決まりだ。#n総連合会は三日後、「アウトロービーチ」で行なわれる。"
"10036005-96-サオリ" = "……ビーチ、だと？"
