[translation]
"10036100-1" = "第10話;Yo DJ Pump This Party"
"10036100-2-ミサキ" = "ステージの修理はこれで終わり。"
"10036100-3-アツコ" = "DJの機材は無事みたい。"
"10036100-4-ヒヨリ" = "か、観客席も準備完了です……！"
"10036100-8-サオリ" = "わざわざ手伝う必要は……。"
"10036100-9-アツコ" = "ううん、お祭りはみんなで楽しむものだからね。"
"10036100-13-ヘルメット団員A" = "準備完了だ！"
"10036100-14-ヘルメット団員A" = "チッ、逃げやがって……。"
"10036100-15-ヘルメット団員A" = "ま、邪魔者は消えたことだし、#nこれで思いっきりDJステージを楽しめるぜ！"
"10036100-16-ヘルメット団員B" = "えっと……そのことなんだけど。"
"10036100-17-ヘルメット団員B" = "DJステージは……中止になった。"
"10036100-22-サオリ&アツコ&ミサキ&ヒヨリ" = "え……？"
"10036100-24-ヘルメット団員B" = "銃撃戦の途中で、DJ B.o.Bがどこかに行ったんだ。"
"10036100-25-ヘルメット団員B" = "「許してくれえええ」って叫びながら……。"
"10036100-26-ヘルメット団員B" = "今頃、どこにいるのかさっぱり分からなくてな。"
"10036100-27-アツコ" = "みんな、DJステージを楽しみにしてたのに……。"
"10036100-28-ヒヨリ" = "……や、やっぱり終わりです！"
"10036100-29-ヒヨリ" = "DJステージなんて贅沢、私たちに許されるわけないんですね！"
"10036100-30-ヒヨリ" = "もう波の音でも聞きながら、砂浜を眺めるしか……。"
"10036100-31-ヒヨリ" = "そのうちに気づいたら波に流されて、どこかの無人島へ……。"
"10036100-32-ヒヨリ" = "「無人島で生き延びる術」の最新号を読んでいれば……！#nうわぁぁぁあああん！"
"10036100-33" = "[s] \"落ち着いて、ヒヨリ。\""
"10036100-38-ヘルメット団員A" = "……シャーレの先生？"
"10036100-39-ヘルメット団員A" = "何か方法でもあるのか？"
"10036100-40" = "[s] \"DJステージを中止する必要はないと思う。\""
"10036100-41-ヘルメット団員B" = "まぁ、機材は揃ってるが……。"
"10036100-42-ヘルメット団員B" = "肝心なDJの人が不在だろ？"
"10036100-43" = "[s] \"それなら心配ないよ。\""
"10036100-47-サオリ" = "先生、どうしたんだ？"
"10036100-48" = "[s] \"ここに、DJ B.o.Bの一番弟子がいるからね！\""
"10036100-49-サオリ" = "！？"
"10036100-50-サオリ" = "ま、まさか私にDJを……！？"
"10036100-55" = "[ns1] 三人にサインを送る。\n[ns2] みんなの顔を見て頷く。"
"10036100-58-アツコ&ミサキ&ヒヨリ" = "……！"
"10036100-59-アツコ" = "サッちゃんのDJ、見てみたい。"
"10036100-60-ヒヨリ" = "そ、そうです！#nせっかくのイベントなのに、中止だなんて悲しいじゃないですか……。"
"10036100-61-ミサキ" = "……私も何か言ったほうが良いのかな。"
"10036100-62" = "[s] \"ミサキもDJステージ、楽しみにしてたよね？\""
"10036100-63-ミサキ" = "ちょっ……！"
"10036100-64-ミサキ" = "はぁ……#nまぁ、お祭りのメインイベントだし、中止になったらもったいないでしょ。"
"10036100-66-サオリ" = "しかし……私にDJのステージ経験はない。"
"10036100-67-サオリ" = "みんなに楽しんでもらえるとは……。"
"10036100-68" = "[s] \"大事なのは、楽しませたいっていう気持ちだよ。\""
"10036100-69-サオリ" = "……。"
"10036100-70-サオリ" = "なるほど……。"
"10036100-71-サオリ" = "楽しませたい気持ち、か。"
"10036100-75-サオリ" = "……まだ、よく分からない。"
"10036100-76" = "[s] \"そっか……。\""
"10036100-77-サオリ" = "……ただ。"
"10036100-78-サオリ" = "私は……。"
"10036100-79-サオリ" = "あのステージの感覚を、もう一度感じたいんだ。"
"10036100-80-サオリ" = "やってみようと思う。"
"10036100-81-サオリ" = "いや、必ずやり遂げてみせる。"
"10036100-83-ミサキ" = "リーダーがDJって、想像できないね。"
"10036100-84-ヒヨリ" = "サオリ姉さんが音楽を……。"
"10036100-85-ヒヨリ" = "途中で失敗したら、機材に銃を打ったりしないでしょうか……？"
"10036100-86-アツコ" = "ううん、きっと上手くいく。"
"10036100-88-アツコ" = "サッちゃんは、答えを見つけたみたいだから。"
"10036100-92-司会者" = "さあさあ、大変お待たせいたしました！"
"10036100-93-司会者" = "ここ「アウトロービーチ」は、再び盛り上がってきました！"
"10036100-94-司会者" = "皆さん、準備は良いですか？"
"10036100-95-司会者" = "それでは――ミュージック・スタート！"
"10036100-98" = "#video;11009"
