[translation]
"10036095-5-スケバンA" = "うっ……！"
"10036095-11-アケミ" = "きゃぁ！痛いですわね！"
"10036095-12-サオリ" = "ここまでだ、伝説のスケバン。"
"10036095-13-サオリ" = "降参する気になったか？"
"10036095-14-サオリ" = "それとも、まだ戦えると？"
"10036095-15-アケミ" = "私の戦いは、ここまでですの……？"
"10036095-16-アケミ" = "あなたたち、いったい何者で？"
"10036095-20-サオリ" = "私たちは……。"
"10036095-26-？？？" = "そこまでにしなさい、アケミ。"
"10036095-27" = "[ns] （……誰だ？）"
"10036095-29-ニヤニヤ教授" = "ここが引き際です。"
"10036095-30-アケミ" = "わ、私は……まだ戦えますわ！"
"10036095-32-ニヤニヤ教授" = "ほむ、強がりは良くないですよ。"
"10036095-33-ニヤニヤ教授" = "長らく矯正局に収監されていたせいで、腕が鈍っているのでしょう？"
"10036095-34-ニヤニヤ教授" = "そんな状態で戦いを続けたら……。"
"10036095-35-ニヤニヤ教授" = "再び、矯正局入りする可能性も。#nそれは望ましくありません。"
"10036095-36-ニヤニヤ教授" = "――なにせ、[ruby=・   ・   ・   ・   ・   ・   ・   ・   ・   ・   ・   ・]せっかく脱獄させた七囚人[/ruby]の一人なんですから。"
"10036095-37-ニヤニヤ教授" = "あなたを今、ここで失うわけにはいかないのです。"
"10036095-38-ニヤニヤ教授" = "さぁ、早く部下を連れて離れなさい。"
"10036095-40-アケミ" = "に、ニヤニヤ教授……。"
"10036095-41" = "[s] （ニヤニヤ教授……？）"
"10036095-47-ニヤニヤ教授" = "……では、失礼。"
"10036095-53-アケミ" = "……ふんっ。"
"10036095-54-アケミ" = "ここは、あなたのアドバイスに従っておきますわ！"
"10036095-55-アケミ" = "ヘルメット団の皆さん、これでお別れとしましょう！"
"10036095-56-アケミ" = "それと、そこのムササビさん？#n貴方の顔は覚えておきましたよ。"
"10036095-57-アケミ" = "次に戦う時は、一切手加減いたしませんわ。"
"10036095-58-アケミ" = "いつか、必ず決着をつけるとしましょう！"
"10036095-59-アケミ" = "それでは、撤退しますわよ！"
"10036095-60-スケバン一同" = "はいっ！"
"10036095-64-ヘルメット団員A" = "急にどうしたんだ、あいつら……。"
"10036095-65-ヘルメット団員B" = "逃がすな、追いかけるぞ！"
"10036095-72-ヒヨリ" = "も、ものすごいスピードで逃げていきました……。"
"10036095-73" = "[s1] \"ビックリしたね。\"\n[s2] \"追いかけるのはやめておこう。\""
"10036095-78" = "[ns] \"それより……。\""
"10036095-81-サオリ" = "……。"
"10036095-82-アツコ" = "……。"
"10036095-83-ミサキ" = "リーダー。"
"10036095-84-ヒヨリ" = "サオリ姉さん……。"
"10036095-88-サオリ&アツコ" = "あの……！"
"10036095-93-サオリ" = "アツコ……お祭りは、どうだった？"
"10036095-94-アツコ" = "……楽しかった。"
"10036095-95-アツコ" = "サッちゃんは？"
"10036095-96-サオリ" = "……私も、楽しかった。"
"10036095-98-サオリ" = "まさか……ずっと互いに様子を伺っていたとはな。"
"10036095-99-サオリ" = "DJ B.o.Bの態度が急に変わった時も、#n水鉄砲大会で優勝した時も。"
"10036095-100-ヒヨリ" = "屋台のご飯が、全部サオリ姉さんの奢りだったなんて……#nしかも、スケバンの襲撃を阻止したのは……。"
"10036095-101-ミサキ" = "……先生は全部知ってたんだ。"
"10036095-102" = "[s3] \"あはは……さ、サプライズってことで。\"\n[s4] \"それぞれ事情があるみたいだったから……。\""
"10036095-105-サオリ" = "[USERNAME]先生のことは責めない。"
"10036095-106-サオリ" = "先生には、秘密にしてくれと言ったからな。"
"10036095-107-サオリ" = "ただ約束を守ってくれていただけだ。"
"10036095-108-ミサキ" = "まぁ、それは分かってるけど……。"
"10036095-109-アツコ" = "……じゃあ、私たちがお祭りを楽しめたのは、#n先生のおかげ、だね。"
"10036095-110" = "[s] \"それは、みんなが頑張ったからだよ。\""
"10036095-111-サオリ" = "礼を言う、先生。"
"10036095-112-アツコ" = "ありがとう。"
"10036095-114-サオリ&アツコ" = "私たちの夏を、守ってくれて。"
