[translation]
"2600803-1" = "結局、何のためでしたっけ？"
"2600803-6" = "（待ち合わせ場所へと歩いていくと、シズコの姿を見かけた）"
"2600803-7-シズコ" = "……あ、先生？"
"2600803-8-シズコ" = "ずいぶん早かったですね。"
"2600803-9-シズコ" = "なるほど……そんなに私と会いたかったんですね？"
"2600803-10" = "[s] \"シズコも待ち合わせの時間より早いし、もしかして私に会いたかった？\""
"2600803-11-シズコ" = "そ、そんなことありませんが！？"
"2600803-12" = "[s] \"それはそれで辛い……。\""
"2600803-13-シズコ" = "挑発し返しておいて、落ち込まないでくださいよ！？"
"2600803-14-シズコ" = "まったくもう……！先生は大人なのに……。"
"2600803-15-シズコ" = "本当に、何と言うか……。"
"2600803-16" = "[s] \"……何かあったの？\""
"2600803-17-シズコ" = "雑談という体だったんですから、普通もう少し遠回りに来ません！？"
"2600803-18-シズコ" = "まったく、先生はやはり予想を超えてくるというか……。"
"2600803-19-シズコ" = "まあ、だからこそ……かもしれませんが。"
"2600803-21-シズコ" = "……先生が以前仰った通りでした。"
"2600803-22-シズコ" = "各所のフランチャイズ店を見て回ってみたのですが……"
"2600803-23-シズコ" = "お客さんの反応が、芳しくなくて……"
"2600803-24" = "[s] \"なるほど……どの辺りが気になった？\""
"2600803-26-シズコ" = "これはその、私がそう感じたというだけですが……。"
"2600803-27-シズコ" = "おそらく、味の問題では無さそうです。"
"2600803-28-シズコ" = "それに、居心地の問題でも無いような気がします。"
"2600803-29-シズコ" = "お客さんたちの様子を見る限りは、そうなのですが……"
"2600803-31-シズコ" = "ううっ、何なんでしょう本当に……！"
"2600803-32-シズコ" = "何というかその……"
"2600803-33-シズコ" = "百夜堂らしさが感じられないと言いますか……！"
"2600803-34-シズコ" = "何かこう、むしゃくしゃします！"
"2600803-35" = "[s] \"ちょ、ちょっと落ち着こう。\""
"2600803-36-シズコ" = "落ち着いてなどいられません！"
"2600803-37-シズコ" = "これはピンチです、 大ピンチなんです！"
"2600803-39-シズコ" = "このままでは、各地の店舗で少しずつ……"
"2600803-40-シズコ" = "少しずつ、お客さんの信頼が失われてしまいます！"
"2600803-41-シズコ" = "こうなってしまうと、後は早いものです。"
"2600803-42-シズコ" = "噂は広がり、フォローもままならず！"
"2600803-43-シズコ" = "最終的にはそう……"
"2600803-44-シズコ" = "百夜堂、消失の危機です！"
"2600803-45-シズコ" = "そ、そんなことになったら……！"
"2600803-46" = "[s] \"大丈夫！\""
"2600803-48-シズコ" = "な、何が大丈夫なんですか！？"
"2600803-49" = "[s] \"大丈夫であってほしいなって気持ちは、ある……！\""
"2600803-50-シズコ" = "何の慰めにもなってないじゃないですか！うわあああん！"
"2600803-51" = "[s] \"ところで、シズコ。\""
"2600803-53" = "[s] \"何かこう忘れてるというか、頭の隅に追いやってるというか。\""
"2600803-54-シズコ" = "……？どういうことですか？"
"2600803-55-シズコ" = "私の、所属……？それは、お祭り運営委員会ですが……？"
"2600803-56-シズコ" = "そもそもこの百夜堂の仕事も、元はと言えばお祭り資金の用意と準備のためであって……"
"2600803-57-シズコ" = "……はい。まあもちろん大変ですし、面倒だと思わないわけではないです。"
"2600803-58-シズコ" = "それに加えて、フランチャイズ化…… "
"2600803-59-シズコ" = "まあ、大変な状況ではありますね。"
"2600803-60-シズコ" = "理由……？まあそれはやはり、結局のところ……"
"2600803-61-シズコ" = "私は、お祭りが好きだから……でしょうか。"
"2600803-62" = "[s] \"それもあるだろうけど、多分……\""
"2600803-64" = "[s] \"シズコは、人の笑顔が好きなんじゃないかな？\""
"2600803-68-シズコ" = "そう、ですね……。"
"2600803-70-シズコ" = "色々あった結果、最終的に無事お祭りが開けた時……。"
"2600803-77-シズコ" = "百夜堂に来たお客さんが、笑顔で「ありがとう」と言ってくれた時……。"
"2600803-84-シズコ" = "みんなと一緒に、頑張ってる時……。"
"2600803-86-シズコ" = "……それと比べれば私の頑張りなんて、ちっぽけなものですから。"
"2600803-87" = "[s] \"今回の収益とかも、そうだったんじゃないかな。\""
"2600803-88-シズコ" = "……はい。"
"2600803-89-シズコ" = "少なくとも、優先順位は間違っていたかもしれません。"
"2600803-90-シズコ" = "私にとって何が重要なのかを……"
"2600803-91-シズコ" = "夏の雰囲気に酔いしれて…… "
"2600803-92-シズコ" = "魔が差したというか、何と言うか……"
"2600803-93-シズコ" = "せっかくの夏だし、水着姿だしって。先生の前で、カッコいいところを……"
"2600803-94-シズコ" = "……はっ！？"
"2600803-95" = "[s] \"シズコ……？\""
"2600803-96-シズコ" = "い、いえ！"
"2600803-97-シズコ" = "ち、違うんです！今のは夏の魔物です！"
"2600803-98-シズコ" = "先生にだけは見せたくなかったというか、その……！"
"2600803-99-シズコ" = "い、今のも忘れてください！今すぐに！"
"2600803-107-チンピラA" = "おいおいいちゃついてんじゃねーよ。"
"2600803-108-チンピラB" = "お前ら、あたしらのこと知らないのか？"
"2600803-109-チンピラB" = "こちとら、先日からこの島の支配者だぜ？つまりはご主人様なんだから、もてなしてもらわないとなぁ！"
"2600803-111-シズコ" = "……はぁ。"
"2600803-113-チンピラA" = "あん？ため息なんかつきやがって……。"
"2600803-114-チンピラB" = "あたしらを見下すようなら、"
"2600803-115-チンピラB" = "容赦はしな――"
"2600803-116-チンピラB" = "（なあ、代わりに喧嘩してくれね？あたし無理なんだけど）"
"2600803-117-チンピラA" = "（いやあたしも今まで勝ったことねーし！こういうのはとにかく勢いで行くんだよ！）"
"2600803-119-シズコ" = "まあ、ちょうど良かったわ。"
"2600803-123-シズコ" = "招かれざるお客様は、強制退出！"
"2600803-124-シズコ" = "勢いでさっきの記憶が無くなるほど、全力でやってあげるわ！"
"2600803-132-チンピラA" = "痛たたたたたたっ！おい、何言ってんだこいつ！？八つ当たりじゃね！？"
"2600803-133-チンピラB" = "こ、降参！降参するから！もう止めてくれ！"
"2600803-134-シズコ" = "うるさい！こちとら冷やかしお断りなのよ！"
"2600803-140" = "（そうして暴れ始めたシズコを何とか宥め、リゾートへと戻るのだった）"
