[translation]
"1001503-1" = "アリスクエスト～そして伝説へ～"
"1001503-2-アリス" = "今日は冒険に行くのにピッタリの日ですね。"
"1001503-3-アリス" = "そういえば、アリスはレベルアップしたので、幾つか新しい機能が解放されました。"
"1001503-4" = "[s1] \"どんな機能？\"\n[s2] \"例えば？\""
"1001503-5-アリス" = "アイテム探索です。"
"1001503-6-アリス" = "アイテム探索です。"
"1001503-7-アリス" = "実際にお見せしましょう。"
"1001503-11" = "[s3] \"ア、アリス！？何をしてるの！？\"\n[s4] \"なんでいきなりゴミ箱をひっくり返したの！？\""
"1001503-12-アリス" = "こうするとアイテムが手に入ります。"
"1001503-13-アリス" = "こうするとアイテムが手に入ります。"
"1001503-14" = "[s5] \"……！？\"\n[s6] \"どういうこと！？\""
"1001503-15-アリス" = "……？知らないのですか？"
"1001503-16-アリス" = "……？知らないのですか？"
"1001503-17-アリス" = "こういったところからは、アイテムが拾えるんですよ。前にやったRPGでもそうでしたし、その前にやった横スクロールアクションゲームでもそうでした。"
"1001503-18-アリス" = "あっ、ゴミの中に回復アイテムが！"
"1001503-19-アリス" = "見てください、先生。アリスは「誰かの食べかけのハンバーガー」を発見しました！"
"1001503-20" = "[s7] \"アリス、それはダメ！\"\n[s8] \"それ食べたら体力が減るやつ！\""
"1001503-21-アリス" = "……そうなのですか？"
"1001503-22-アリス" = "……そうなのですか？"
"1001503-23-アリス" = "……ダメージを受けてしまう、ということですね。アリスも苦しいのは嫌です。"
"1001503-24-アリス" = "ここで回復魔法を無駄遣いはできませんし……。"
"1001503-25-アリス" = "これは放置して、出発するとしましょう。"
"1001503-26" = "[s] \"うん、じゃあどこに行こっか？\""
"1001503-27-アリス" = "今日は、アリスが普段行かない場所に行ってみたいです。"
"1001503-28-アリス" = "もちろん、先生も一緒に来てくれますよね？"
"1001503-29" = "[s9] 放っておけないから一緒に行く。\n[s10] 不安だから一緒に行く。"
"1001503-30-アリス" = "それでは出発です！"
"1001503-31-アリス" = "それでは出発です！"
"1001503-33" = "ミレニアム・外郭地区"
"1001503-34-アリス" = "……気がつけば、こんなところまで来てしまいました。"
"1001503-35-アリス" = "道が分からなくなってしまいましたね……ここはどこでしょうか？"
"1001503-36" = "[s11] \"人けのないところだね……。\"\n[s12] \"こういうところには大抵チンピラが……。\""
"1001503-43-チンピラ１" = "カモはっけーん！"
"1001503-44-チンピラ２" = "ケケケケッ！"
"1001503-45-アリス" = "！！"
"1001503-46" = "[s13] \"来ると思った！\"\n[s14] \"お決まりの展開！\""
"1001503-47-チンピラ１" = "何だか財布の厚そうなやつらじゃねえか、ラッキーだなぁ？"
"1001503-48-チンピラ１" = "何だか財布の厚そうなやつらじゃねえか、ラッキーだなぁ？"
"1001503-49-チンピラ２" = "ケケケッ、有り金全部出さないと痛い目見るぞ？"
"1001503-50-アリス" = "……？"
"1001503-51-アリス" = "……。"
"1001503-52-アリス" = "理解しました、フィールドで遭遇するモンスターですね。"
"1001503-53-アリス" = "（ガチャッ！）"
"1001503-54-チンピラ１" = "は？"
"1001503-55-チンピラ２" = "な、なんだ、あの武器は？"
"1001503-56-アリス" = "それでは、全力で行きます！"
"1001503-57" = "[s] \"ちょっ、アリス待っ――\""
"1001503-58-アリス" = "――――――光よ！"
"1001503-60" = "（チュドオオオオオオオオォォォォン！）"
"1001503-63" = "（チンピラたちがまるで潰されたペットボトルみたいに、地面に転がっていた）"
"1001503-65-アリス" = "……？"
"1001503-66-アリス" = "……おかしいです、先生。倒したのに経験値が入りません。"
"1001503-67-アリス" = "それに、報酬も出てきませんね。"
"1001503-68-アリス" = "あ、コインは手動で回収するタイプのシステムなのでしょうか。"
"1001503-69" = "[s15] \"いやいやいや、待ってアリス！\"\n[s16] \"それじゃアリスの方がチンピラだよ！？\""
"1001503-73" = "（倒れたチンピラのポケットを漁ろうとするアリスを、どうにかして引き留めた）"
