[translation]
"10011025-2-チンピラA" = "ぐあぁっ！？"
"10011025-7-チンピラB" = "な、なんだこいつら……。"
"10011025-9-チンピラB" = "って、よく見たらシャーレの先生じゃねぇか！"
"10011025-10-チンピラA" = "それってあの、「酷い目に遭いたくなかったら近寄るな」って言われてるあの！？"
"10011025-11" = "[s] \"どこからそんなお話が……。\""
"10011025-12-チンピラA" = "くそっ、本気でヤバい奴だ！逃げろ！"
"10011025-17" = "[ns] \"出所が気になる……ところでツクヨ、お疲れ様。大丈夫？\""
"10011025-18-ツクヨ" = "せ、先生ーーーーー！"
"10011025-20" = "[ns] \"そろそろ落ち着いた？\""
"10011025-21-ツクヨ" = "ありがとうございます、先生……。"
"10011025-22-ツクヨ" = "その、お手数をかけて、すみません……。"
"10011025-23" = "[s1] \"ううん、こっちこそかわせなくてごめんね。\"\n[s2] \"むしろありがとう。\""
"10011025-26-ツクヨ" = "……。"
"10011025-27-ツクヨ" = "私、こうして身体ばっかり大きいせいで……。"
"10011025-28-ツクヨ" = "よく、目を付けられる、と言いますか……。"
"10011025-29-ツクヨ" = "その、助けていただき、ありがとう、ございます……。"
"10011025-30" = "[s] \"気に病むことじゃないと思うよ。じゃあ行こうか。\""
"10011025-31-ツクヨ" = "はいっ……！"
"10011025-38-ツクヨ" = "……。"
"10011025-45-ツクヨ" = "……。"
"10011025-46" = "[s] \"……私の顔に、何か付いてる？\""
"10011025-47-ツクヨ" = "あ、いえ、そうではなく……！"
"10011025-48-ツクヨ" = "すみません、その、変に見つめてしまって……。"
"10011025-49" = "[s] \"ううん、気にしないで。単にどうしたのかなって。\""
"10011025-50-ツクヨ" = "えっと、それはですね……"
"10011025-51-ツクヨ" = "あの……"
"10011025-52-ツクヨ" = "何と言いますか……"
"10011025-53-ツクヨ" = "イズナちゃんの「主殿」がどんな方なのか、"
"10011025-54-ツクヨ" = "ずっと気になってて……。"
"10011025-55" = "[s] \"ああ、なるほど。\""
"10011025-56-ツクヨ" = "イズナちゃん、忍術研究部に入って以来、"
"10011025-58-ツクヨ" = "ずっと言ってるんです……"
"10011025-59-ツクヨ" = "「主殿のために、キヴォトスいちの忍者になります！」って。"
"10011025-60-ツクヨ" = "あ、そのたびに部長が、「一応聞くけど、変な人に騙されたりしてない？」とも……。"
"10011025-61" = "[s] \"あー……。\""
"10011025-62-ツクヨ" = "あ、いえ！先生が怪しいですとか、そういったわけではなく……！"
"10011025-63-ツクヨ" = "えっと、会う前は少しだけ、頭をよぎらなかったわけではないのですが……。"
"10011025-66-ツクヨ" = "イズナちゃんがそれを言う時、いつも笑顔で……。"
"10011025-67-ツクヨ" = "私も会ってみたいなって、思って、たので……。"
"10011025-68" = "[s3] \"なるほど。直接会ってみてどう？\"\n[s4] \"どんな感じの印象だった？\""
"10011025-72-ツクヨ" = "えっと、その、決して悪い感じでは無くて……！"
"10011025-73-ツクヨ" = "突然の訪問、だったのに……拒絶されたり、しませんでしたし……。"
"10011025-74" = "[s] \"なるほど？\""
"10011025-75-ツクヨ" = "怒られたりもしませんでしたし……"
"10011025-76-ツクヨ" = "「忍者」って言っても、笑ったり、しなくて……。"
"10011025-77-ツクヨ" = "陰陽部のところに行ったときは、私たちのために、あんなことを言ってくれて……。"
"10011025-78-ツクヨ" = "びっくり、しました。"
"10011025-79-ツクヨ" = "こういう人もいるんだな、って。"
"10011025-80-ツクヨ" = "だから、嬉しかったんです。"
"10011025-81-ツクヨ" = "イズナちゃんも、部長も、喜んでると思います。"
"10011025-82" = "[s] \"三人とも、仲良しだね。\""
"10011025-83-ツクヨ" = "あ……"
"10011025-84-ツクヨ" = "は、はいっ！"
"10011025-85-ツクヨ" = "最初は私も、ここにいて良いのかなって、すごく、心配でしたが……。"
"10011025-86-ツクヨ" = "イズナちゃんのことも、好きですし、部長も、尊敬してます。"
"10011025-87-ツクヨ" = "こんな、ただ身体が大きいだけの私に……"
"10011025-90-ミチル" = "あなたがツクヨ？"
"10011025-95-ツクヨ" = "こんな、私でも……"
"10011025-96-ツクヨ" = "とにかく、その、頑張りたいんです！"
"10011025-97-ツクヨ" = "忍者の鉄則に則って、私も、負けないように……！"
"10011025-101-ツクヨ" = "上手く行ってるかは、怪しいですが……。"
"10011025-102-ツクヨ" = "とにかく、まずは。今日の公演を……！"
"10011025-103" = "[s5] \"……そっか。\"\n[s6] \"ツクヨならきっとできるよ。\""
"10011025-106-ツクヨ" = "は、はい、ありがとうございます……！"
"10011025-109-イズナ" = "あ、ツクヨ殿ー！"
"10011025-110-ミチル" = "二人とも遅い～、もう待ちくたびれたよー。"
"10011025-111-ツクヨ" = "あ、お待たせ、しました……！"
