[translation]
"10011070-1" = "第7話;第四関門：トリックハウス"
"10011070-6-カエデ" = "はいはーい！第四関門へようこそ！！"
"10011070-7-カエデ" = "ここは罠や仕掛けがいっぱいの「トリックハウス」！この渦巻映画村でも、かなり有名なアトラクションの一つだよ！"
"10011070-8-ミチル" = "つまり……忍者屋敷？"
"10011070-9-カエデ" = "それはよく分かんない！！"
"10011070-10-カエデ" = "とにかく、「第四関門」はこのトリックハウス！担当は私、[ruby=いさみ]勇美[/ruby]カエデ15歳！趣味はカブトムシ集めだよ！"
"10011070-11" = "[s] \"やっぱりカエデもいたんだね。\""
"10011070-12-カエデ" = "ふっふっふっ……まあね！ちなみにお姫様を誘拐した悪党は、この屋敷の中に逃げた……らしいよ！多分！"
"10011070-13-カエデ" = "そして、この関門でのルールは簡単！"
"10011070-15-カエデ" = "このトリックハウスの中に入って、"
"10011070-18-カエデ" = "ゴールに辿り着けば"
"10011070-21-カエデ" = "OK！"
"10011070-23-カエデ" = "でも、中にはたくさんの試練があるから、一筋縄じゃ行かないよ！"
"10011070-24-ミチル" = "よっし、分かりやすい！トリックハウスでも忍者屋敷でも、何でもかかってこいだよ！"
"10011070-25-ツクヨ" = "あ、部長……！？"
"10011070-26-イズナ" = "部長、事前に攻略方法の相談などは……！"
"10011070-27-ミチル" = "大丈夫大丈夫、進めば何とかなるよ！"
"10011070-28-ミチル" = "基本的に観光客向けなんだし、そんなに難しいのは無いはず……！"
"10011070-32-カエデ" = "あっ！まだ説明の途中なのに！"
"10011070-38-ミチル" = "……え？"
"10011070-39" = "[s] \"ミチル、危なっ……！？\""
"10011070-46-ニヤ" = "にゃはは。次々と襲ってくる試練、それに立ち向かっていく少女たち……。"
"10011070-47-ニヤ" = "そして、その横には……。"
"10011070-48-ニヤ" = "ふふっ……まあ期待はあったけど、なるほど。"
"10011070-49-ニヤ" = "うんうん、面白いねぇ。"
"10011070-50-カホ" = "ニヤ様、これは一体どういう状況ですか……！？"
"10011070-51-ニヤ" = "んー？どうしたの、カホ？"
"10011070-52-カホ" = "お姫様を誘拐する役の方から、ご連絡がありました。「自分たちの出番はいつなのか」、と……。"
"10011070-53-カホ" = "これが本当だとしたら、今イブキさんを誘拐しているのは一体……？"
"10011070-54-ニヤ" = "あらまぁ、それはおかしいねぇ？"
"10011070-55-ニヤ" = "どういうことなんだろうね～？"
"10011070-56-カホ" = "またこういう流れですか……今回は何のために……。"
"10011070-60-カホ" = "とにかく、後は私の方で動きますので。"
"10011070-65-ニヤ" = "全く、相変わらず真面目だねぇ♪"
"10011070-69-ニヤ" = "はてさて、この先はどうなるかな～？"
"10011070-70-ニヤ" = "今までは何とかなってたけど、そろそろ問題が顕在化してもおかしくない……。"
"10011070-71-ニヤ" = "さて、そんな彼女たちのために、どんな答えを導くのか……。"
"10011070-72-ニヤ" = "期待しとりますよ、先生♪"
"10011070-81-ニヤ" = "ということで忍術研究部のみなさん、今度の公演はよろしくお願いしますね～♪"
"10011070-87-魑魅一座のリーダー" = "では行動を開始する。迅速に進め、邪魔者は処理せよ……行くぞ、「魑魅一座・気まぐれ流」！"
"10011070-93-百鬼夜行の生徒B" = "眠り姫って、あの修行部の部長でしょ？すごいけど、そもそも「忍術研究部」ってあんまり聞いたこと無いような……。"
"10011070-94-百鬼夜行の生徒B" = "……にしても変わった名前だね。"
"10011070-102-ミチル" = "（千載一遇のチャンス……）"
"10011070-103-ミチル" = "（一気にイメージアップして、堂々と正式な部活になって……）"
"10011070-104-ミチル" = "（イズナとツクヨの前でしっかりと胸を張れるようになる、大事なチャンス……！）"
"10011070-105-ミチル" = "（だから私は、絶対に……！）"
"10011070-114-ミチル" = "あれ、ここは……？"
"10011070-115" = "[s] \"あ、起きた？罠が発動して、ここに落ちちゃったみたい。\""
"10011070-116-ミチル" = "……罠？"
"10011070-117-ミチル" = "ってことは、やっぱりこれ忍者屋敷じゃん！"
"10011070-118-ミチル" = "はっ！こんなことしてる場合じゃない……先生殿、早くここから抜け出――"
"10011070-119" = "[s1] \"ごめん、ちょっと待ってもらえる？\"\n[s2] \"足、くじいちゃったみたいで……。\""
"10011070-122-ミチル" = "足、ってことは……ここへ落ちた時に……？"
"10011070-123-ミチル" = "もしかして、私が無傷なのって……先生殿が……？"
"10011070-124-ミチル" = "私が……ひとりで勝手に、走り出したせいで……。"
"10011070-125" = "[s] \"ミチルのせいじゃないよ、大丈夫。\""
"10011070-130-ミチル" = "……。"
"10011070-131" = "[s] \"ミチル？\""
"10011070-132-ミチル" = "……私の、せいで。"
"10011070-133-ミチル" = "私のせいで、全部台無しに……ど、どうしよう……！ごめん、ごめん、先生殿……！！"
"10011070-142" = "[ns] \"少し落ち着いた？\""
"10011070-143-ミチル" = "ぐすっ……うん。"
"10011070-144" = "[s3] \"さっきの「台無しに」っていうのは……。\"\n[s4] \"どういうことか、聞いても良い？\""
"10011070-147-ミチル" = "最初から……全部、私のわがままだった。"
"10011070-148-ミチル" = "あの子……イブキが誘拐された時、本当ならすぐ通報するべきだった。"
"10011070-149-ミチル" = "すぐに陰陽部とか百花繚乱に連絡してれば、多分解決してた……。"
"10011070-150-ミチル" = "私が、自分の我儘を……。"
"10011070-151" = "[s] \"正式な部活になるために？\""
"10011070-152-ミチル" = "……！"
"10011070-153-ミチル" = "うん……。"
"10011070-154-ミチル" = "忍者のことを広めたいのは本当。でも他の生徒たちに話したところで、それを笑わずに受け入れてくれるか、すごく怖い……"
"10011070-155-ミチル" = "だからこの機に、とにかく先に、正式な部活になりたかった。"
"10011070-156-ミチル" = "推薦状無しに、正式な認可が貰えるかもしれないなんて……こんなチャンス、二度と無いかもしれない。だから、何とかして成功させたかった。"
"10011070-161-ミチル" = "あんなに純粋な憧れを持ったイズナと、"
"10011070-162-ミチル" = "何も知らなかったのに巻き込んじゃったツクヨ……私は、あのふたりに対する責任がある。"
"10011070-164-ミチル" = "あなたがツクヨ？"
"10011070-165-ツクヨ" = "！！"
"10011070-166-ミチル" = "もし良かったら……忍術研究部に入らない？"
"10011070-168-ミチル" = "二人に胸を張れる、そんな先輩になりたかった……。"
"10011070-169-ミチル" = "最悪の場合……このまま公演が失敗して、チャンスが無くなるだけならまだ良い。"
"10011070-173-ミチル" = "でも私が通報を躊躇ったせいで……魑魅一座に誘拐されたあの子は、"
"10011070-175-ミチル" = "今も泣いてるかもしれない。辛い目に、遭ってるかもしれない。"
"10011070-177-ミチル" = "全部、私のせいで……。"
"10011070-178-ミチル" = "もしこれが世間に知られたら、イズナもツクヨも、何もしてないのに後ろ指を指されるかもしれない。「忍術研究部」に関わってたってだけで。"
"10011070-179-ミチル" = "私の我儘のせいで、たくさんの人に迷惑が掛かってる。"
"10011070-180-ミチル" = "イズナも、ツクヨも……"
"10011070-181-ミチル" = "全部知ったら、きっとガッカリすると思う。全部、私が怖がってたせいで、こんなことに……。"
"10011070-182-ミチル" = "私は、もう……"
"10011070-183" = "[s] \"……足、治ったかも！！\""
"10011070-184-ミチル" = "せ、先生殿！？今、すごい真面目な話をしてたんだけど！？"
"10011070-185-ミチル" = "アニメでよくある、メインヒロインが大事な悩みを暴露する9話か10話あたりのシーンだったんだけど！！？"
"10011070-186-ミチル" = "それをそんな、軽く……！"
"10011070-187-ミチル" = "もう泣いちゃいそうだよ！いやもう半分くらい泣いてるけど……！じゃなくて！"
"10011070-188" = "[s] \"「申請書」を出さなかったのは、怖かったから？\""
"10011070-189-ミチル" = "……っ。"
"10011070-190-ミチル" = "そ、それはそう！正式な申請書なんて、出せるわけがないじゃん……！"
"10011070-192-ミチル" = "「忍者って何？」って、「忍術研究部って何？」って、それが普通の反応でしょ！"
"10011070-193-ミチル" = "アニメや漫画の話って思われて当然……！"
"10011070-194-ミチル" = "そんな部活の推薦書なんて、誰にも頼めない……！"
"10011070-195-ミチル" = "誰かが認めてくれるなんて、思えなかった……。"
"10011070-197-ミチル" = "下手に何かを言い出したら後ろ指を指されたり、バカにされたりするかもだし……"
"10011070-198-ミチル" = "私だけならまだしも、"
"10011070-199-ミチル" = "あの二人は……！"
"10011070-203" = "[ns5] \"そこから先は、私が勝手に同意できることじゃないかな。\"\n[ns6] \"その答えを知ってるのは、あの二人だけじゃないかな。\""
"10011070-207-ミチル" = "せ、先生殿……？"
"10011070-208" = "[s] \"さて、そろそろ行こっか。後悔先に立たずって言うからね。\""
"10011070-209-ミチル" = "……うん。"
"10011070-210-ミチル" = "とりあえず、ここを抜け出さないと。"
"10011070-214-ミチル" = "……ありがとう、先生殿。"
"10011070-215" = "[s] \"どういたしまして……あ、ちょっとメイクよれてるよ。\""
"10011070-216-ミチル" = "ぬあぁっ！？"
"10011070-217-ミチル" = "い、今の流れから、普通レディーにそんなこと言う！？"
"10011070-218-ミチル" = "全くもう……。"
"10011070-219-미치루01" = "とにかく何の話をするにせよ、ここを抜け出さないと始まらないかー……。"
"10011070-220-ミチル" = "でもこれ、てきとうに進んだところで……。"
"10011070-224-ミチル" = "……あれ？"
"10011070-225" = "[s] \"どうしたの？\""
"10011070-226-ミチル" = "この廊下、この間取り、"
"10011070-227-ミチル" = "見たことある……。"
"10011070-228-ミチル" = "もしかしてこれ、「かまぼこ突風伝」……？"
"10011070-229-ミチル" = "分かる、全部覚えてる……！"
"10011070-230-ミチル" = "先生殿、こっち！"
"10011070-231" = "[ns] \"うん、行こう。\""
"10011070-252-ミチル" = "やっぱりこれ、「かまぼこ突風伝」の忍者屋敷そのままだ……！"
"10011070-253-ミチル" = "っていうかこれ、著作権的に大丈夫なの！？"
"10011070-254" = "[s] \"観光地にはよくあるよね。もしかしたらコラボしてるとか……。\""
"10011070-255-ミチル" = "うう、後で担当者を問い詰めないと！でもそれより……"
"10011070-256-カエデ" = "あっ、お疲れ様ー！"
"10011070-257" = "[s] \"あれ、カエデ？\""
"10011070-258-カエデ" = "もー。ふたりともルール説明が終わる前に行っちゃうから、困っちゃったよ。"
"10011070-259-カエデ" = "さて、じゃあ今さらだけどあらためてルール説明！"
"10011070-260-カエデ" = "このトリックハウスを抜けた人には、挑戦権が与えられるの！"
"10011070-262-ミチル" = "挑戦権……？"
"10011070-263-カエデ" = "そう、挑戦権！つまり……"
"10011070-269-カエデ" = "私カエデに対して、挑戦を申し込める権利だよ！"
"10011070-270-カエデ" = "私に勝てたら晴れてクリア！それじゃあ行っくよー！"
"10011070-271-ミチル" = "結局そうなるんじゃん！？"
"10011070-272" = "[s] \"まあ、そういうものだよね。\""
