[translation]
"10011090-1" = "第9話;[ruby=少女]忍者[/ruby]の鉄則"
"10011090-7-魑魅一座B" = "何すかこれ、全部めちゃくちゃじゃないっすか！"
"10011090-8-魑魅一座A" = "ニヤニヤ教授の作戦が、なぜ……！"
"10011090-14-ニヤ" = "にゃははっ！みんな頑張ってますか～？"
"10011090-15-ニヤ" = "ますます激しくなる追撃戦……"
"10011090-16-ニヤ" = "それもそろそろ終盤です！さあ、どうなるんでしょう～！"
"10011090-21-魑魅一座A" = "くそっ、陰陽部め……！"
"10011090-22-魑魅一座のリーダー" = "ちっ、最初から「交流会を混乱させて要望を飲ませる」なんてのが甘かったか！"
"10011090-23-魑魅一座のリーダー" = "こうなったら、直接行って銃弾をぶち込んでやる！"
"10011090-24-魑魅一座のリーダー" = "行くぞ、陰陽部のところに突撃だ！"
"10011090-25-魑魅一座A" = "ま、マジか！？"
"10011090-26-魑魅一座B" = "なるほど、それでこそリーダーっす！"
"10011090-31-イズナ" = "魑魅一座、発見です！"
"10011090-34-魑魅一座A" = "なっ、戦車だと！？"
"10011090-35-魑魅一座B" = "ど、どうするんすか！？"
"10011090-39-魑魅一座のリーダー" = "……城門の前にある橋を、爆弾で吹き飛ばす。"
"10011090-41-魑魅一座A" = "お、ナイスアイディア！そうすれば追って来られないはず！"
"10011090-42-魑魅一座B" = "派手に吹っ飛ばすっすよー！"
"10011090-49-ツクヨ" = "い、今の爆発は……！？"
"10011090-50-ミチル" = "やばっ！橋が吹き飛ばされてない！？"
"10011090-51-イズナ" = "おおおっ！イズナ、こういうのドラマで見たことあります！追撃戦の王道ですね！"
"10011090-55" = "[ns] \"イロハ、どうしよっか？\""
"10011090-56-イロハ" = "橋を破壊して、追撃を振り切ろうと……。"
"10011090-57-イロハ" = "……甘いですね。"
"10011090-58-ミチル" = "え、何！？なんで余裕なの！？"
"10011090-59-イロハ" = "先生も、それ以外の皆さんも。しっかり捕まっててください。"
"10011090-60" = "[s] \"まさか……。\""
"10011090-78-イロハ" = "足場が無いから何なんですか。"
"10011090-79-イロハ" = "これくらいで、諦めるわけないでしょう。"
"10011090-84-ミチル" = "何言ってんの！？ねぇ！？"
"10011090-87-イロハ" = "必要なのは、速度――"
"10011090-88-イロハ" = "砲身を後ろ側に回してください、発射準備を。"
"10011090-89-イロハ" = "発砲の衝撃で飛び越えます。"
"10011090-92-ミチル" = "それ本当に行けるかなぁ！？"
"10011090-95-イロハ" = "大丈夫です、映画で見ましたから。"
"10011090-96-イロハ" = "気合入れてください……！"
"10011090-102-ミチル" = "のああああああぁぁぁぁぁっ！！？！？"
