[translation]
"10011095-8-イズナ" = "い、イズナ、もうヘロヘロです……。"
"10011095-9-ツクヨ" = "戦車って、あんなに怖いもの、だったんですね……。"
"10011095-10-カエデ" = "うぇ、もう疲れたぁ……。"
"10011095-15-イロハ" = "先生……イブキのこと、どうか……。"
"10011095-24" = "[ns] \"……ミチル、立てる？\""
"10011095-25-ミチル" = "う、うん。何とか……。"
"10011095-26" = "[s] \"残ったのは、私たちだけかな。\""
"10011095-27-ミチル" = "……"
"10011095-38-ミチル" = "行こう、先生殿。約束を、果たすために……！"
"10011095-45-魑魅一座A" = "到着だ！陰陽部の部長はどこだ……！？"
"10011095-46-魑魅一座B" = "どこっすか！？"
"10011095-51-ニヤ" = "にゃはは、お疲れ様～。"
"10011095-52-魑魅一座のリーダー" = "なっ、映像投影！？"
"10011095-53-ニヤ" = "さあ、公演も遂に大詰め。最後の最後に笑うのは、一体誰なのでしょう～？"
"10011095-58-ミチル" = "はぁ、はぁ……。"
"10011095-59-ミチル" = "ふう……。"
"10011095-60-ミチル" = "お姫様、返してもらうよ……！"
"10011095-65-ミチル" = "（とは言ってみた、ものの……）"
"10011095-66" = "[s] \"頑張ろう、ミチル。\""
"10011095-67-ミチル" = "（……ってあれ、先生殿が妙案をくれるとかじゃない感じ！？）"
"10011095-68-ミチル" = "（うっ……つまり基本的に私ひとりで、）"
"10011095-69-ミチル" = "（魑魅一座を相手する……？）"
"10011095-71-魑魅一座のリーダー" = "ええいっ、それ以上近づくな！"
"10011095-76-魑魅一座のリーダー" = "この姫を、投げ落とされたくなかったらな……！"
"10011095-80-ニヤ" = "おおっと、白熱してまいりました～！"
"10011095-81-ニヤ" = "筋書き通りなんでしょうが、あの発言はＯＫなのでしょうか～？"
"10011095-82-魑魅一座のリーダー" = "ああもう、筋書きだとか何だとか、うるさいぞ陰陽部……！"
"10011095-84-ミチル" = "（いやいやいや何もできないじゃん！？イブキちゃんを落とされるわけにはいかないし、私なんかじゃもう無理……！）"
"10011095-85-ミチル" = "（よく考えてみたらここまで来れたのだって、みんなのおかげで……私はただ勢いに任せて、ここまで来ただけ……）"
"10011095-86-ミチル" = "（こんな時に限って、何の役にも立たない……！）"
"10011095-87-ミチル" = "（あんなに大口叩いたのに！正式な部活にって言ったのに！ツクヨに、イズナに、あれだけ励ましてもらったのに……！）"
"10011095-90-ニヤ" = "おおっと、どうやらあの挑戦者……何かを悩んでいるようですねぇ？"
"10011095-92-ミチル" = "（ああもう五月蠅いなぁ！？悩むに決まってるじゃん！こんな、一歩間違えたら全部終わりの状況で）"
"10011095-93-ミチル" = "（……足だって震えるし、心臓も破裂しそうだってば！）"
"10011095-94-ミチル" = "（こんなことになって……あんな、電気が消えるだけで怖がってたイブキちゃんも、きっと怖くて震えてるはず……）"
"10011095-95-イブキ" = "忍者の、おねえちゃん？"
"10011095-96-ミチル" = "あ、イブキ……！"
"10011095-97-イブキ" = "やっぱり忍者のおねえちゃんだ！イブキ、ちゃんとおとなしくしてたよ！"
"10011095-98-ミチル" = "って、全然泣いてない……？"
"10011095-99-イブキ" = "？？？"
"10011095-100-ミチル" = "え、いや、誘拐されたんだし、すごく怖かったんじゃないかなーって……"
"10011095-101-イブキ" = "全然そんなこと無いよ！だって――"
"10011095-107-イブキ" = "「何があっても絶対助けに行くって」、約束してくれたから！"
"10011095-108-ミチル" = "……！"
"10011095-110-ツクヨ" = "私たち、約束したじゃないですか……！「何があっても絶対助けに行く」って！"
"10011095-115-ミチル" = "……っ！"
"10011095-118-魑魅一座のリーダー" = "と、止まれ！下手に動いたら、この子の安全は保障しないぞ！？"
"10011095-119-魑魅一座のリーダー" = "う、嘘じゃないからな！？それ以上来たら、本当に……！"
"10011095-125-魑魅一座A" = "あっ"
"10011095-127" = "[ns] \"イブキ！危ない！\""
"10011095-132-ミチル" = "（間に合ええぇぇぇぇっ！！）"
"10011095-133-ミチル" = "（せぇ、のっ……！）"
"10011095-135-ミチル" = "ミチル流忍法っ！！"
"10011095-138-ミチル" = "捕まえたっ！！"
"10011095-139" = "[s] \"ミチル、ナイス！待ってて、すぐに引き上げる！\""
"10011095-140-イブキ" = "あははっ！イブキ捕まっちゃったー！"
"10011095-141-ミチル" = "うん！もう大丈夫、あとは先生殿に引き上げてもらえれば……"
"10011095-145-ミチル" = "……え゛"
"10011095-149-ミチル" = "うぎゃあああっ！？お、落ちる落ちる落ちる！？"
"10011095-150-ツクヨ" = "イズナちゃん……！！"
"10011095-151-イズナ" = "はい、ツクヨ殿！"
"10011095-163-ツクヨ" = "ま、間に合いました……！"
"10011095-164-イズナ" = "主殿！お助けいたします！"
"10011095-165" = "[s] \"みんな、ありがとう……。\""
"10011095-167-ミチル" = "し、死ぬかと思ったあぁぁぁぁ……！！"
"10011095-168-ミチル" = "あ、イブキ大丈夫！？"
"10011095-169-イブキ" = "うん！忍者のおねえちゃんたち、助けてくれてありがとう！"
"10011095-170-ミチル" = "……良かった。"
"10011095-172-ツクヨ" = "はい、約束、しましたから……忍者の鉄則、です！"
"10011095-173-イズナ" = "忍術研究部、大勝利ですね！ニンニン！"
"10011095-175-魑魅一座A" = "これは、えっと……。"
"10011095-176-魑魅一座B" = "全部終わりぽいっすね。"
"10011095-177-魑魅一座のリーダー" = "くっ、まだだ！このまま失敗に終わるわけには……！"
"10011095-179-イロハ" = "……そこの方々。"
"10011095-184-イロハ" = "イブキを巻き込んだ罪は、重いですよ。"
"10011095-186-魑魅一座" = "ひいいっ！？"
