[translation]
"10011010-1" = "第1話;交流会スタート！"
"10011010-4" = "[ns] \"約束の場所はたしか……\""
"10011010-5-イズナ" = "あっ、部長！主殿を発見しました！"
"10011010-9-ミチル" = "お、先生殿ー！こっちこっちー！"
"10011010-10-ツクヨ" = "おはよう、ござい、ます……。"
"10011010-11" = "[s] \"みんな、おはよう。準備は大丈夫？\""
"10011010-12-ミチル" = "もっちろん！"
"10011010-13-イズナ" = "イズナも全力で準備しました！具体的には心の鍛錬のようなものを！"
"10011010-14-ツクヨ" = "私も、今朝、胃腸薬を、飲んできましたので……。"
"10011010-15-ミチル" = "もーツクヨったら、そんなに緊張しなくても大丈夫！"
"10011010-16" = "[s] \"何だかミチルは、前にあった時よりも元気だね。\""
"10011010-17-ミチル" = "ん、そう見える？……まあ、ちょっとテンションは高いかも。"
"10011010-18-ミチル" = "この交流会をしっかり手伝ったら、正式な部活になれるかもだし。"
"10011010-19-ミチル" = "そう思ったら、ついテンション上がっちゃって……頑張らないとね！"
"10011010-20-ツクヨ" = "百鬼夜行とゲヘナ学園の、交流会だなんて……。"
"10011010-21-ツクヨ" = "こんなの、初めてで……ドキドキ、しています……。"
"10011010-22" = "[s] \"まさか、そんなことになるなんてね。\""
"10011010-26" = "（一週間前、カホに連れられて陰陽部を訪れた）"
"10011010-30" = "[ns] \"荘厳な空間だ……。\""
"10011010-31-ミチル" = "ゆ、油断しちゃダメだよ先生殿！相手はなんたって、あの陰陽部の部長！実質的に生徒会長みたいなものだし！"
"10011010-32-ツクヨ" = "噂で、聞いたことが、あります……陰陽部の部長は、話術だけで魂を抜くことができる、と……。"
"10011010-33-イズナ" = "主殿、ご心配なく！主殿の安全は、このイズナが守りますので！"
"10011010-34-カホ" = "……何か誤解されているようですね。"
"10011010-38-チセ" = "あれ……お客さん？"
"10011010-43-カホ" = "あら、チセちゃん。"
"10011010-44-ミチル" = "……え？"
"10011010-48" = "[ns] \"……チセ？\""
"10011010-52-チセ" = "煙霧から"
"10011010-53-チセ" = "突然出会いて"
"10011010-54-チセ" = "驚いて"
"10011010-55-チセ" = "……元気だった？"
"10011010-56" = "[s] \"あ、うん。元気だよ。\""
"10011010-57-ミチル" = "ふぉぉ……！ち、チセ様の俳句を、生で……！"
"10011010-58-カホ" = "うぅ、チセちゃん可愛い……。"
"10011010-59" = "[s] \"チセは相変わらず、人気者なんだね……。\""
"10011010-60-カホ" = "……こほん、失礼しました。"
"10011010-61-カホ" = "ニヤ様、お客様がお見えになりましたよ。"
"10011010-70-ニヤ" = "あらあらあら～。"
"10011010-77-ニヤ" = "ふぅん、ほぉ……。"
"10011010-85-ニヤ" = "ふむふむ。"
"10011010-86-ニヤ" = "顔はだいぶ好み、むしろストライク……いや、逆にアウト？"
"10011010-88-ニヤ" = "とはいえ、まあ……面白そうではあるね。"
"10011010-89" = "[s] \"……？\""
"10011010-90-カホ" = "ニヤ様、失礼ですよ。"
"10011010-91-ニヤ" = "にゃはは、相変わらずカホは固いんだから。"
"10011010-92-ニヤ" = "おっほん。"
"10011010-97-ニヤ" = "私の名前は[ruby=あまち]天地[/ruby]ニヤ、陰陽部の部長をしとる。ん？態度がでかいって？そんなこと無いよ、むしろ逆。"
"10011010-98-ニヤ" = "器が小さすぎるから、態度が大きく見えるだけ。実際にはかな～り偉い人なんでね。いやそれにしてもまあ、お会いできて嬉しいですねぇ、シャーレの先生♪"
"10011010-99" = "[s] \"こちらこそ。会えて嬉しいよ、ニヤ。\""
"10011010-100-ニヤ" = "にゃはは、真面目なリアクションだあ。"
"10011010-101-ニヤ" = "なるほどなるほど、これがシャーレの先生……。"
"10011010-102-ニヤ" = "噂なら、耳にタコができるくらい聞いとりますよ。連邦生徒会長の失踪以後、各所で大活躍されている……と。"
"10011010-103" = "[s] \"ちょっとした手助けをしてるだけだよ。\""
"10011010-104-ニヤ" = "それはちょうど良い。でしたら、私たちの手助けもしてもらえます？"
"10011010-105-ニヤ" = "さて、そのためにどこから説明したものか……先生は私たち「陰陽部」について、どこまでご存じです？"
"10011010-106" = "[s1] \"百鬼夜行の生徒会みたいなもの、って聞いた気が……。\"\n[s2] \"確か行政的な役割を担ってるとか……？\""
"10011010-109-ニヤ" = "んふふ……間違ってはいませんが、ちょっぴり認識がズレとるかもしれませんねぇ。"
"10011010-110-カホ" = "この百鬼夜行連合学院は、数多くの連合で構成されている学校……。"
"10011010-111-カホ" = "……そういうこともあってここには、いわゆる「生徒会」みたいな「頂点に位置する組織」みたいなものは存在しないんですよ。"
"10011010-112" = "[s] \"じゃあ陰陽部は……？\""
"10011010-113-ニヤ" = "にゃはは、上には立たんよ。そうじゃなく一歩引いた立ち位置で、百鬼夜行の歴史と伝統を支える存在であり、それゆえに尊敬を集めている側面がある……"
"10011010-119-ニヤ" = "まあ組織が大きくなると、こういう役割は必要でしょう。ただそれだけのこと。"
"10011010-120" = "[s] \"なるほど……。\""
"10011010-121-ニヤ" = "まあ実体としては、アイドルみたいなもんだったりするんですよ、公演をやったり、占いの放送をしたり。"
"10011010-122-ニヤ" = "にゃはは、チセなんか特に大人気だもんね～？"
"10011010-123-チセ" = "ね～？"
"10011010-124-チセ" = "……そうだっけ？"
"10011010-125-カホ" = "ニヤ様、本題を。"
"10011010-126-ニヤ" = "もう、カホったらヤキモチ焼いちゃってー……もちろんカホにも、隠れファンはいっぱいいるんよ？"
"10011010-127-カホ" = "に、ニヤ様……！"
"10011010-128-ニヤ" = "にゃはは。"
"10011010-129-ニヤ" = "さて、単刀直入に申し上げましょう。"
"10011010-131-ニヤ" = "一週間後……私たち「百鬼夜行連合学院」と「ゲヘナ学園」との間で、交流会が予定されてるんです。"
"10011010-132" = "[s] \"ゲヘナ？\""
"10011010-134-ニヤ" = "ええ、"
"10011010-136-ニヤ" = "ゲヘナ学園のトップ『万魔殿』の皆さんに快諾を貰いまして。"
"10011010-138-ニヤ" = "ゲヘナの皆さんを、「百鬼夜行渦巻映画村」に招待することになったんです。"
"10011010-139-ニヤ" = "さらに今回は特別に……"
"10011010-140-ニヤ" = "我々陰陽部が誇る公演、「[ruby=わらくひめ]和楽姫[/ruby]」を行う予定でして。"
"10011010-141" = "[s] \"和楽姫……？\""
"10011010-143-ミチル" = "先生殿まさか、和楽姫をご存じでない！？"
"10011010-144-ミチル" = "渦巻映画村には色んなアトラクションがあるんだけど、その中でもトップレベルに人気なんだよ！"
"10011010-145-ミチル" = "それに何と言っても、「和楽姫」の主人公はチセ様！あの百鬼夜行最高峰のアイドルであるチセ様の愛らしさがここまでかというほど堪能できる、素晴らしいアトラクション……！"
"10011010-146-チセ" = "……？"
"10011010-147-カホ" = "ミチルさん、少々声のトーンを……。"
"10011010-148-ニヤ" = "んふふ、見てくれてたんですねぇ♪"
"10011010-149-ニヤ" = "え～っとたしか……ルンルンさん、でしたっけ？"
"10011010-150-ミチル" = "ミチルだよ！誰がルンルンだ！"
"10011010-154-ミチル" = "（ってやばっ！）"
"10011010-155-ミチル" = "（陰陽部に向かって叫んじゃった……！）"
"10011010-157-ニヤ" = "ふふっ……特に今回の「和楽姫」は、特に気合を入れて準備したイベントなんですが……。"
"10011010-158-ニヤ" = "一つだけ、心配ごとがありまして。"
"10011010-159" = "[s] \"心配ごと？\""
"10011010-164-ニヤ" = "はい。先生もご存知の通り、ゲヘナの方々はすごく自由奔放です。なので万が一でも……"
"10011010-171-ニヤ" = "本当に万が一、億が一のお話ではあるんですが～……何か予想外の事態が発生して、#n「和楽姫」の公演中に何かが起きてしまったら……"
"10011010-172-ニヤ" = "それはもう、すごく楽しそう……ではなく。"
"10011010-173-ニヤ" = "困るかもしれないな～と、思いまして。"
"10011010-175-ニヤ" = "というわけで無事に公演を終えるためにも、シャーレにお力を貸していただきたいなと。いかがでしょう？"
"10011010-176" = "[s] \"うん、協力させてもらおうかな。\""
"10011010-177-ミチル" = "先生殿！？"
"10011010-178" = "[s] \"その代わりってわけじゃないけど、一つ提案があって。\""
"10011010-179-ニヤ" = "……あら、何でしょう？"
"10011010-180" = "[s3] \"その件を手伝うために、忍術研究部の力を借りようかなって。\"\n[s4] \"公演が無事成功したら、忍術研究部のことを認めてもらえないかな？\""
"10011010-183-ニヤ" = "忍術研究部、ねぇ……？"
"10011010-184-ミチル" = "ちょっ、先生殿……！急にそんなこと言われても……！"
"10011010-185-カホ" = "お言葉ですが先生、それは正式な手続きが必要で……"
"10011010-187" = "[ns] \"どうかな？\""
"10011010-191-ニヤ" = "ふむ、忍術研究部……あまり知らん部活ですねぇ？"
"10011010-192-ニヤ" = "なるほど、忍者を研究する部活で、まだ正式な認可が下りていないと。"
"10011010-193-ニヤ" = "んふふ。それはまた、どうしてなんでしょうねぇ……？"
"10011010-194-カホ" = "……これまで忍術研究部から、「正式な部活動としての申請書」を頂いたことはありません。"
"10011010-198-カホ" = "その申請に必要な書類は、「部としての実績証明書」が1部。そして「活動に関する他の部活からの保証書」が3部。"
"10011010-202-カホ" = "忍術研究部の皆さんの場合、前者は普段から運営している「少女忍法帖ミチルっち」チャンネルや、先日の「コミセン」で提出されていた忍術の同人誌などで問題無いはずですが……"
"10011010-204-ミチル" = "ど、どうしてカホがそんなこと知ってるのさ！？"
"10011010-205-カホ" = "しかし、他の部活からの保証書だけがありません。"
"10011010-206-カホ" = "それさえあれば、申請は可能ですが……？"
"10011010-207" = "[s] \"そうなの？\""
"10011010-208-ミチル" = "でも、その……中々忍者の孤高さを理解してくれる人がいないっていうか……。"
"10011010-209-ミチル" = "その、キヴォトスで忍者って文化が根付くには、まだ準備が必要っていうか……。"
"10011010-210-ミチル" = "あとはその、個人的な事情っていうか……。"
"10011010-211-ミチル" = "……。"
"10011010-212-ニヤ" = "にゃはは、まあ良いでしょう。吞むとしましょうか。"
"10011010-213-カホ" = "ニヤ様、またそうやって……！"
"10011010-214-ミチル" = "えっ、ほんと！？"
"10011010-215-ニヤ" = "まあまあカホったら、これくらい大丈夫よ。"
"10011010-216-ニヤ" = "公演が無事成功して、"
"10011010-217-ニヤ" = "交流会[ruby=つつが]が恙な[/ruby]く終わるなら……ね。"
"10011010-218" = "[s] \"ありがとう、ニヤ。\""
"10011010-219-ニヤ" = "にゃははっ、どういたしまして。ということで忍術研究部のみなさん、今度の公演はよろしくお願いしますね～♪"
"10011010-220-イズナ" = "そうとなれば……！"
"10011010-221-ツクヨ" = "部長……！"
"10011010-222-ミチル" = "え、あ、うん……。"
"10011010-228-ミチル" = "も、もちろん、大船に乗ったつもりでどーんと任せてよね！ぜ、全力で、成功に導いてみせるから……！"
"10011010-229-カホ" = "全く、ニヤ様は……。"
"10011010-230-チセ" = "♪"
"10011010-231-ニヤ" = "にゃはは……まあ、お手並み拝見と参りましょうか？"
"10011010-233-ミチル" = "……というわけで！早速現場に移動するとしよう！目指せ、公演の成功！"
"10011010-238-イズナ＆ツクヨ" = "はいっ！"
"10011010-239" = "[s] \"よし、頑張ろう！\""
