[translation]
"22010-1" = "第1話;密やかなる会談"
"22010-10" = "ミレニアム・セミナー執務室"
"22010-12-ヒマリ" = "あら……超天才清楚系病弱美少女の来訪を、#n電気もつけずに迎えるなんて……。"
"22010-13-ヒマリ" = "来客をもてなす気がこれっぽっちも無いという点、#nとてもあなたらしいとは思いますけど……。"
"22010-14-ヒマリ" = "ですが、暗い部屋でモニターをつけていると目が悪くなりますよ？"
"22010-18-ヒマリ" = "――リオ。"
"22010-25-リオ" = "万全を期しているだけよ――この会談を外部に知られてはならないもの。"
"22010-26-リオ" = "そのためであれば、この程度問題ではないわ。"
"22010-27-リオ" = "この訪問はデータベースには残らない。#nつまり、記録上私たちは会ってなどいない事になっている。"
"22010-28-リオ" = "すべては――これから話す内容の機密を守るため。"
"22010-29-ヒマリ" = "リオったら、真面目なんですから……#n「貴女は私の姉なの？」くらいの軽口を返せないと、ユーモアからは程遠いですよ。"
"22010-30-ヒマリ" = "今のだって、超天才清楚系病弱美少女の軽い冗談なんですから。#nふふ。"
"22010-31-リオ" = "……貴女は私の姉ではないわ。#n急にそんな非合理的な話をするなんて……どうしたの、ヒマリ。"
"22010-32-ヒマリ" = "……ええ、ええ。そうでした。#nあなたはそういう人でしたね。"
"22010-33-ヒマリ" = "ユーモアを解さずに「合理」だなんて……あなたの好きな表現でしたね、それ。"
"22010-34-リオ" = "好悪の話ではないのだけれど……事実でしょう？"
"22010-35-リオ" = "この会合が秘匿されている事くらいは、あなたも理解しているものだと思っていたのだけれど。"
"22010-36-ヒマリ" = "それはどうでしょう？#n――そもそも、人目を気にするのであれば、他の場所にすれば良かったのでは？"
"22010-38-リオ" = "……他の場所？"
"22010-39-ヒマリ" = "ええ、例えば……"
"22010-41-ヒマリ" = "誰かさんがこっそり作っている――"
"22010-42-ヒマリ" = "[ruby=悪趣味]「セーフハウス」[/ruby]……とか？"
"22010-44-リオ" = "……。"
"22010-46-リオ" = "……本題に入りましょう。"
"22010-47-ヒマリ" = "あらあら、話を逸らすつもりですか？#nふふ……ええ、構いませんが。"
"22010-52-リオ" = "まず、お互いの認識のすり合わせを。"
"22010-54-リオ" = "前回、「鏡」を巡ってミレニアム生が起こした一連の騒動――"
"22010-55-リオ" = "それは私たちが共に仕掛けたことだったわね。"
"22010-61-ヒマリ" = "ええ。私が「鏡」という手段を用意し、リオが「C&C」という危機を提供する――。"
"22010-62-ヒマリ" = "珍しく、一つの目的のためにあなたと私が協力した事でした。"
"22010-64-ヒマリ" = "そう――[ruby=AL-1S]アリス[/ruby]の正体を明かすために。"
"22010-70-リオ" = "あれから随分と経つけれど……#n解釈の結論は出たかしら？"
"22010-71-ヒマリ" = "もちろんです。"
"22010-73-ヒマリ" = "アリスの正体……#nそれは――"
"22010-74-ヒマリ" = "無名の司祭が崇拝する「オーパーツ」であり――"
"22010-75-リオ" = "――遥か昔の記録に存在する、"
"22010-79-リオ" = "「名もなき神々の王女」。"
"22010-81-ヒマリ" = "……。"
"22010-82-リオ" = "……。"
"22010-83-リオ" = "そう……同じ解釈になったようね。"
"22010-88-リオ" = "つまり……「あの存在」の本質は……。"
"22010-89-ヒマリ" = "ええ。アリス、あの子は――"
"22010-93" = "「世界を終焉に導く兵器」"
"22010-94" = "「『かわいい後輩』ですよね♪」"
"22010-100-リオ" = "……？"
"22010-101-ヒマリ" = "……あら。"
"22010-102-リオ" = "……あなたは一体、何を言っているの？"
"22010-103-ヒマリ" = "リオこそ、一体何を言っているのですか……？"
"22010-104-リオ" = "……。"
"22010-105-ヒマリ" = "……。"
"22010-111-リオ" = "……そう。じゃあ、私たちの同盟はここで終わりという事ね。"
"22010-112-ヒマリ" = "そうですね。#n同盟ではなく、休戦でしたが……。"
"22010-113-リオ" = "………………。"
"22010-114-ヒマリ" = "……………………。"
"22010-122-ヒマリ" = "ああ、これが噂の……最近あなたが作っているおもちゃですね。"
"22010-126-リオ" = "同盟を解除した以上、貴女をこのまま帰すわけにはいかないわ。"
"22010-128-ヒマリ" = "まぁ……そうでしょうね。#nあなたならそうすると思っていました。"
"22010-135-リオ" = "ッ……！？#n私のオフィスが……ハッキングされた……！？"
"22010-136-ヒマリ" = "あらあら……ビッグシスターの部屋は無敵だとでも？"
"22010-137-リオ" = "AMAS、ヒマリを捕らえなさい……！"
"22010-138-ヒマリ" = "ふふ、病弱美少女に不可能なんてないんですよ。"
"22010-144-リオ" = "（AMASの全個体が、動作を停止した……？）"
"22010-145-リオ" = "（まさか、照明システムがダウンした瞬間に……！？#n　あの一瞬でこれだけの規模のハッキングを……？）"
"22010-146-リオ" = "（……感心してる場合じゃない。ドローンの制御権を復旧させないと）"
"22010-163-リオ" = "ん、なんで照明システムが反応……。"
"22010-168-リオ" = "うっ……！"
"22010-173-リオ" = "ヒマリは……"
"22010-179-リオ" = "……そう、抜け出したのね。"
"22010-180-リオ" = "さすがはヴェリタスの部長……。"
"22010-181-リオ" = "できることなら、味方にしておきたかったけれど……"
"22010-182-リオ" = "本当に、残念よ。"
"22010-184-リオ" = "はぁ……非合理的なこの方法だけは、選びたくなかったのに――"
"22010-193-ヒマリ" = "自分と意見が違うと気づくや否や、躊躇いなく行動するその姿……"
"22010-194-ヒマリ" = "久々に見ましたが……相変わらずですね、リオ。"
"22010-195-ヒマリ" = "まぁ、超天才病弱美少女の私には無意味ですが♪"
"22010-196-ヒマリ" = "さてさて……これでリオより先に……"
"22010-203-ヒマリ" = "ん……？"
"22010-211-ヒマリ" = "くっ……！？#nあなたは……だれ……？"
"22010-219-ヒマリ" = "あなたは……"
"22010-220-ヒマリ" = "まさか……5番目のC&C……"
"22010-228" = "次回;ゲーム開発部の平凡な日常"
