[translation]
"22100-1" = "第10話;残酷な真実（２）"
"22100-15-ネル" = "んなザコで足止めになるわけねぇだろうがよ！"
"22100-19-リオ" = "――さすがネル。AMAS程度では、貴方を止められないというわけね。"
"22100-20-リオ" = "こんな事はしたくなかったけれど――"
"22100-22-リオ" = "……トキ。"
"22100-23-トキ" = "イエス、マム。"
"22100-24-リオ" = "「武装」の使用を許可します。"
"22100-26-トキ" = "承知しました。"
"22100-31-トキ" = "準備完了。「モード2」に移行します。"
"22100-32-ネル" = "はぁ？何をゴチャゴチャと――"
"22100-42-ミドリ" = "あれ？服が……"
"22100-43" = "[ns] \"……「姿」が変わった？\""
"22100-45-トキ" = "……！"
"22100-54-ネル" = "そっちか！？"
"22100-69-ネル" = "逃すか……！"
"22100-82-ネル" = "チッ、クソ……当たんねぇ……"
"22100-83-ミドリ" = "あ、あっという間に消えちゃった……。"
"22100-89-ネル" = "てめぇ、一体どこに………"
"22100-91-ユズ" = "ネル先輩、後ろ……！"
"22100-92-ネル" = "……何？"
"22100-106-ネル" = "ぐあっ！！？"
"22100-107" = "[s] \"ネルがあっという間に……\""
"22100-109-ミドリ" = "気づいたら……突然、現れて……"
"22100-110-ユズ" = "あ、あうぅ………"
"22100-115-ネル" = "クソッ！離せ！？ぶっ壊されてぇのか！？"
"22100-116-トキ" = "そうやって暴れたら、曲がってはいけない方向に腕が曲がりますよ、先輩。"
"22100-117-トキ" = "みなさんも、下手に動かないでくださいね。#n無駄な抵抗はおすすめしません。"
"22100-119-ミドリ" = "……うっ！"
"22100-120-ユズ" = "……！"
"22100-123" = "[ns] \"それは、一体……。\""
"22100-124-リオ" = "私の作った特殊武装よ。"
"22100-125-リオ" = "――こんな所で出すつもりはなかったのだけれど。"
"22100-126-リオ" = "さあ、AMAS。#nアリスを回収しなさい。"
"22100-136-ミドリ" = "！！"
"22100-137-ユズ" = "ちょ、ちょっと待っ……！"
"22100-139-リオ" = "下手に動かない方がいい。"
"22100-145-リオ" = "無関係な子を傷つけたくない。"
"22100-151-ミドリ＆ユズ" = "（ビクッ！）"
"22100-154" = "[ns] \"やめて、リオ。\""
"22100-157-リオ" = "――それは私のセリフよ。"
"22100-158-リオ" = "私も対立などしたくないわ。"
"22100-159-リオ" = "貴方と敵対する気も、憎まれる気もない。"
"22100-160-リオ" = "むしろ、貴方に聞きたいくらい。"
"22100-161-リオ" = "こういった事態に於いて、シャーレの先生、"
"22100-166-リオ" = "大人である貴方が真っ先に動くべきなのではなくて？"
"22100-167" = "[s] \"……それは、どういう？\""
"22100-168-リオ" = "子供より感情に支配されず、#n冷静に状況を判断できる――"
"22100-169-リオ" = "そういった大人である貴方が動くべきだったのでは？"
"22100-170" = "[s] \"生徒を傷つけるなんて………。\""
"22100-171-リオ" = "――いつまでそんな寝言を吐き続けるつもりなの！"
"22100-172" = "[s] \"……！！\""
"22100-173-リオ" = "――勘違いしないでちょうだい、先生。"
"22100-176-リオ" = "「アレ」は生命体ではないの――貴方が背負うべき生徒ではない。"
"22100-177-リオ" = "もし、そう感じるのであれば、それは「エライザ効果」に過ぎない。"
"22100-178-リオ" = "「アレ」はこの世界を終焉へと至らせる恐るべき兵器。"
"22100-181-リオ" = "[ruby=アリス]アレ[/ruby]とキヴォトスの全生徒を秤にかけろと問われたら、答えは明白でしょう？"
"22100-182-リオ" = "……それでもなお、貴方が動かないというのなら。"
"22100-183-リオ" = "アリスのヘイローは私の手で破壊する。#n準備は既に整っているわ。"
"22100-189-リオ" = "……。"
"22100-190-ミドリ" = "違う……。"
"22100-191-ミドリ" = "違うよ！アリスちゃんは兵器なんかじゃない！"
"22100-192-ミドリ" = "アリスちゃんは……勇者だよ！#nだって――"
"22100-193-ミドリ" = "アリスちゃんは、光の剣を……勇者の証である「スーパーノヴァ」を持っているもの！"
"22100-195-リオ" = "光の剣……エンジニア部が作ったあのおもちゃ？"
"22100-196-リオ" = "そう……貴方たちがそう言うのなら……"
"22100-197-リオ" = "そうね。"
"22100-205" = "[ns] \"スーパーノヴァの電源が……消えた？\""
"22100-206-ミドリ" = "……！"
"22100-207-リオ" = "これでいいかしら？"
"22100-208-リオ" = "光の剣はもうないわ。"
"22100-209-リオ" = "これで証明は終わり。"
"22100-210-アリス" = "アリスの、剣が……ゆうしゃの、あかしが………"
"22100-211-アリス" = "あ、う……うぅ……"
"22100-217-アリス" = "ミドリ……ユズ………"
"22100-223-ネル" = "くそっ！離せ！"
"22100-224-ネル" = "おい、チビ！じっとしてないで、反撃しろよ！"
"22100-226-トキ" = "………"
"22100-227-アリス" = "ネル先輩…………"
"22100-230-アリス" = "先生…………"
"22100-231" = "[s] \"……アリス。\""
"22100-232-アリス" = "……！！"
"22100-239-アリス" = "…………モモイ。"
"22100-240-アリス" = "ぜんぶ……アリスが、いるから……？"
"22100-245-アリス" = "アリスが「魔王」だから……おきた、ことですか？"
"22100-246-リオ" = "……。"
"22100-247-アリス" = "アリスが……ここにいたら……#n同じことが……"
"22100-248-アリス" = "…………"
"22100-249-アリス" = "…………アリスが。"
"22100-250-アリス" = "………………アリスが、勇者じゃないなら……。"
"22100-255-アリス" = "………そう、ですね。"
"22100-261" = "[ns] \"アリス……？\""
"22100-266-アリス" = "はい……アリス、すべて理解しました。"
"22100-267-アリス" = "…………アリスが消えるとします。"
"22100-268-ミドリ" = "ダメ！アリスちゃん！"
"22100-269-ユズ" = "アリ、ス……ちゃん……。"
"22100-270-ネル" = "なっ……チビ、てめぇ……！"
"22100-275" = "[ns] \"その必要はないよ、アリス。\""
"22100-279-アリス" = "いいえ、大丈夫です。"
"22100-280-アリス" = "アリスは……先生に怪我させたくないです。"
"22100-281-アリス" = "アリスは……。"
"22100-291-アリス" = "ミドリもユズも、ネル先輩も、他のみんなも……。"
"22100-292-アリス" = "怪我、させたくないです。"
"22100-293-アリス" = "……モモイが、アリスのせいで怪我したとき……胸がとても痛かったです。"
"22100-294-アリス" = "どうして……なんでこんな事になってしまったのか、アリスにはよく分かりません。"
"22100-297-アリス" = "でも、それでも……その話を、聞いて……やっと、理解しました。"
"22100-298-アリス" = "すべては……アリスのせいで起きたということを……"
"22100-299-アリス" = "アリスがこのままずっといたら……"
"22100-300-アリス" = "いつか……皆が怪我してしまう。"
"22100-301" = "[s] \"リオの言葉を鵜呑みにしなくていい。ちゃんと話し合おう、アリス。\""
"22100-302-アリス" = "先生……心配しなくても大丈夫です。"
"22100-305-アリス" = "大丈夫です。アリスは生命体ではないのですから。"
"22100-306-アリス" = "アリスは、ミレニアムの生徒ではないから。#nいなくなっても、大丈夫です。"
"22100-307-アリス" = "アリスは……勇者、ではないから………"
"22100-308-アリス" = "アリスは………だい……じょうぶです。"
"22100-313-アリス" = "先生、今までありがとうございました。"
"22100-314-アリス" = "みんな、アリスと一緒に冒険してくれて、ありがとうございました。"
"22100-315-アリス" = "アリスは………"
"22100-319-アリス" = "今まで本当に幸せ……でした。"
"22100-329-リオ" = "それでは――失礼するわ。"
"22100-330-リオ" = "もしも――先生が、私の行動や言動に傷ついたのであれば……"
"22100-331-リオ" = "すべてが終わった後、改めて謝罪をさせてちょうだい。"
"22100-332-リオ" = "では、また――"
"22100-338" = "（リオとアリスが完全にその場を去るまで、）"
"22100-342" = "（AMASに制圧された私たちは、指一本動かす事もできず――）"
"22100-347" = "（そうして、ただただ無力感に打ちひしがれる私たちの前から――）"
"22100-352" = "（――アリスは、姿を消した）"
"22100-358" = "次回;そんな事どうでもいいの！"
