[translation]
"22120-1" = "第12話;作戦会議"
"22120-2-ユウカ" = "会長が、アリスちゃんを……？"
"22120-3" = "[s] \"うん……それで、ユウカならリオの居場所を知ってるかなと思って。\""
"22120-4-ノア" = "最近、何か裏で進めている気配はありましたけど……。"
"22120-5-ノア" = "そんなコトになってしまっていたんですね……。#n少し、ショックです。"
"22120-6-ユウカ" = "会長……一体何を企んでいるのかしら。"
"22120-7-ユウカ" = "アリスちゃんを"
"22120-8-ユウカ" = "誘拐して――"
"22120-9-ユウカ" = "その上ヘイローを破壊……？"
"22120-10-ユウカ" = "……意味が分からないわよ！"
"22120-11-ノア" = "普段から突飛な行動をされる方ではありましたが……。"
"22120-12-ユウカ" = "ノア！これはそういう次元の話じゃないわ！"
"22120-13-ユウカ" = "前々から何を考えてるか分からなかったけど……"
"22120-14-ユウカ" = "いくら会長だとしても……やっていい事と悪い事があるのよ！"
"22120-18-ハレ" = "……仮にも自分の先輩なのに、容赦ないね。"
"22120-19-モモイ" = "でしょ？#nま、そういうとこがユウカらしいよね！"
"22120-20-ノア" = "あら、うふふ♪#n信頼されてるんですね、ユウカちゃん。"
"22120-21-ユウカ" = "……ん？どういうこと？"
"22120-22" = "[s1] \"……ユウカ、ノア、お願い。\"\n[s2] \"リオがアリスをどこへ連れて行ったのか、調べてほしいんだ。\""
"22120-23-ユウカ" = "分かりました。セミナー内部の情報を確認してみます。#nリオ会長の痕跡が残っていると思いますので。"
"22120-24-ユウカ" = "分かりました。セミナー内部の情報を確認してみます。#nリオ会長の痕跡が残っていると思いますので。"
"22120-26-ユウカ" = "任せてください！全力をあげて協力します！"
"22120-28-ユウカ" = "リオ会長がアリスちゃんを連れて行った先が分かりました！ "
"22120-29-ユウカ" = "先生のお話を聞いて、まさかとは思ったのですが……。"
"22120-30-ユウカ" = "まさか本当にセミナーの予算を横領していたなんて……。"
"22120-31-ノア" = "本当にショックです……そんな事される方だったなんて。"
"22120-32" = "[s] \"えっと、どういう事？\""
"22120-33-ユウカ" = "その……セミナーのデータベースから、削除された#n――意図的に隠蔽されたような痕跡があるデータを調べたところ……"
"22120-34-ノア" = "予算の一部に不透明な流れを発見。#nそれを追跡することに成功しました。"
"22120-35-ユウカ" = "そうやって追っていった先がここです……今、画面に映します！"
"22120-41" = "[ns] \"これは……都市？\""
"22120-42-ユウカ" = "データベース上から消去された資料を復元したところ――#nとある都市のデータを見つけたんです。"
"22120-43-ユウカ" = "コードネーム[ruby=Eridu]「エリドゥ」[/ruby]。"
"22120-44-ユウカ" = "リオ会長が秘密裏に建設していた……"
"22120-45-ユウカ" = "「終焉に備えるための要塞都市」だそうです。"
"22120-46" = "[s] \"要塞都市「エリドゥ」……。\""
"22120-47-ユウカ" = "一体……いつの間にこんな規模の都市を……。"
"22120-48-ユウカ" = "お金の流れを隠す事だって難しかったでしょうに……。"
"22120-50-アカネ" = "あ……。"
"22120-51-アカネ" = "もしかして……#n先日のコユキさんの一件と関係があるのでは……？"
"22120-52-ユウカ" = "あっ！"
"22120-53-ユウカ" = "コーユーキーー！！"
"22120-54" = "[s] \"どうして都市を作ったんだろう？\""
"22120-55-ノア" = "リオ会長は、ご自身がやると決めた事に関して絶対に迷いません。"
"22120-56-ノア" = "合理的な判断を――時には重大な決断が必要な場面でも何ら迷うことはなく、#n目標達成のためであれば、ブルドーザーみたいに強引に事を進めてしまう。"
"22120-57-ノア" = "そうして危険を排除し、キヴォトスの終焉を防ぐべく奔走した結果できたのが……"
"22120-58-ノア" = "あの要塞都市、「エリドゥ」なのでしょう。"
"22120-59-ユウカ" = "アリスちゃんは、「エリドゥ」の中心部にあるタワーに連れて行かれた可能性が高いわ。"
"22120-61-モモイ" = "そこに……アリスが……"
"22120-62-ユウカ" = "「エリドゥ」の座標をお伝えしますね。"
"22120-63-ノア" = "立場上、私たちがお手伝いできるのはここまでですが……"
"22120-64-ユウカ" = "お願いします……リオ会長を止めて、アリスちゃんを連れ帰ってきてください！"
"22120-65" = "[s] \"うん、任せて。\""
"22120-71-ウタハ" = "エリドゥの座標は確認できたけど、問題は潜入方法だね。"
"22120-72-ウタハ" = "会長ならきっと、対侵入者用の防御システムを構築してるだろうから。"
"22120-73-ウタハ" = "何の準備もなく接近したら……"
"22120-74-ウタハ" = "エリドゥが何故「要塞都市」と呼ばれているのか、#n身をもって知ることになるだろうね。"
"22120-76-モモイ" = "じゃ、じゃあどうすればいいの！？"
"22120-77-ミドリ" = "近づくことも難しいなんて……。"
"22120-79-ウタハ" = "――それはあくまで、「普通に接近した場合」の話だよ。"
"22120-81-ウタハ" = "……私たちエンジニア部は別のルートを知ってるんだ。"
"22120-82" = "[s] \"別のルート……？\""
"22120-83-ウタハ" = "都市建設の「人手」だけだったら、#nリオ会長のドローンで事足りるだろうけど……"
"22120-84-ウタハ" = "「資材」となると話は変わってくる。無から有は作れないからね。"
"22120-85-ヒビキ" = "ミレニアム自治区の郊外には、輸送用の無人列車がたくさんある……。"
"22120-86-ウタハ" = "都市建設の資材をミレニアムから運んでいたと仮定するのなら、#nその路線のどれかがエリドゥと繋がってる可能性が高い。"
"22120-87-モモイ" = "じゃあ、路線さえ分かれば……！"
"22120-88-ウタハ" = "ああ。エリドゥに行けるよ。"
"22120-89-ミドリ" = "で、でも、路線はいっぱいありますよね……？#n一体、どうやって探せばいいんですか！？"
"22120-90-ウタハ" = "ああ。なので、その辺りをエンジニア部がサポートしようじゃないか。"
"22120-91" = "[s] \"ウタハ、私たちはリオと戦う事になるよ。それなのに……\""
"22120-92-ウタハ" = "どうして協力するのかって？"
"22120-93-ウタハ" = "決まっているさ。"
"22120-94-ウタハ" = "リオ会長は、勝手に[ruby=  ・    ・    ・    ・    ・    ・    ・    ・    ・    ・    ・    ・  ]エンジニア部最大の発明品[/ruby]を奪っていったからね。"
"22120-95-モモイ" = "最大の発明品……？"
"22120-96-ミドリ" = "アリスの「スーパーノヴァ」……。"
"22120-97-ウタハ" = "ご明察。うちのデータ実測を邪魔するなんて、それは越権行為に他ならないよ。#n事実上、エンジニア部に向けた宣戦布告ってわけさ。#nこれはエンジニア部の部長として、到底看過することはできなくてね……"
"22120-98-ヒビキ" = "ウタハ先輩の恥ずかしがり屋……"
"22120-99-モモイ" = "え、えっと、一体どういう話、なの？"
"22120-100-コトリ" = "ええ！私が説明しましょう！#nウタハ先輩の論理の流れは次の通りです！"
"22120-101-コトリ" = "友達を助けに行きたいけど、それを口にするにはちょっと恥ずかしい……#nそうだ、いっそ物を奪われた事を口実にしてしまおう……！"
"22120-103-ウタハ" = "ちょっと、コトリ。"
"22120-108-コトリ" = "うっ、ううっ！？"
"22120-109-ウタハ" = "しーっ。"
"22120-110-コトリ" = "（こくりこくり！！）"
"22120-113-ウタハ" = "……よし、これで秘密は守られた。"
"22120-114" = "[s] \"ごめん……何一つ守られてないと思うけど。\""
"22120-115-ウタハ" = "……守られたんだよ。"
"22120-116" = "[s] \"え、う、うん……。\""
"22120-117-ウタハ" = "コホン……というわけで、私たちエンジニア部も手伝うよ。"
"22120-118-ヒビキ" = "うん。"
"22120-119-コトリ" = "えへん！お任せください！"
"22120-124" = "（そうして、アリスの居場所も、そこまで向かう手段も見つかったと思われたものの――）"
"22120-126" = "[ns] \"……次は、アリスをどうやって連れ戻すかだね。\""
"22120-127-アカネ" = "ええ。要塞都市と呼ぶくらいですから……#nリオ会長には万全の備えがあるのでしょう。"
"22120-128-ウタハ" = "都市のセキュリティはもちろん、#n防御システムもかなりのレベルだと思うよ。"
"22120-129-ハレ" = "それに……要塞都市をどうにかしても、まだ問題が残ってる。"
"22120-130" = "[s] \"そうだね……要塞都市はおまけにすぎない。\""
"22120-132-コタマ" = "話を聞く限り、リオ会長の護衛をしているメイドが一番の障害ですね。"
"22120-133-ネル" = "…………。"
"22120-134-ミドリ" = "トキさん……でしたよね？"
"22120-135-ミドリ" = "あの時の……彼女の動き……"
"22120-136-ミドリ" = "まるで……。"
"22120-137-ユズ" = "うん――まるで「チートプレイヤー」……みたいだったね。"
"22120-141-ネル" = "あたしらに必要なのは作戦だな。"
"22120-147" = "[ns] \"ネルが「作戦」って……言った！？\""
"22120-148-モモイ" = "ね、ネル先輩。大丈夫？熱とかない？"
"22120-149-ミドリ" = "もしかして、大けがをした反動で……？"
"22120-150-ネル" = "あぁ？何の話だ？"
"22120-151-カリン" = "……任務モードの部長だ。"
"22120-152-アスナ" = "そうそう！仕事モードになった部長はと～っても真面目なんだから！"
"22120-153-アカネ" = "ふふっ、実はそうなんです。"
"22120-155-モモイ" = "な、なるほど……！"
"22120-156-ハレ" = "うーん、ネル先輩……。#nどういう意味か聞いてもいいかな？"
"22120-157-ネル" = "無事要塞都市に着いたとしても、だ。#nそこがリオの領域である以上、あたしらの動きは丸見えだ。"
"22120-158-ネル" = "誰が何言おうが、あいつは「ビッグシスター」だからよ。"
"22120-159" = "[s] \"どういう意味……？\""
"22120-160-ネル" = "単純な話だよ。あれこれ浅知恵こねくりまわす暇があるんだったら、#n初っ端から突っ込んだ方がいいって事だ。"
"22120-161-アカネ" = "ですが部長、それこそリオ会長の思うツボでは……"
"22120-162-ネル" = "だから作戦が必要つってんだよ。"
"22120-163-ネル" = "――正確には陽動作戦か。"
"22120-164" = "[s] \"陽動作戦……？\""
"22120-165-ネル" = "このゲームの勝利条件は単純明快だ。"
"22120-166-ネル" = "「あたしらがやられる前に、[ruby=アリス]あのチビ[/ruby]を救い出す」"
"22120-167-ネル" = "あたしらC&Cが正面から突っ込んで騒ぎを起こしてやる。#nそうしたら、リオはもちろんトキ、あいつもあたしらの相手せざるを得ないだろ？"
"22120-168-ネル" = "その間にお前たちがチビを救え。#nどうだ？簡単な話だろ？"
"22120-170-ユズ" = "アリスを救ったら……"
"22120-171-ミドリ" = "私たちの勝利……！"
"22120-172-モモイ" = "でもネル先輩、大丈夫ですか？#n相手はあの「チートプレイヤー」だし……"
"22120-174-ネル" = "あ？あたしを誰だと思ってやがる。"
"22120-175-ネル" = "あいつには一杯食わされたからな。#n次会ったらやり返してやるって決めてたんだよ。"
"22120-176-ネル" = "後はそれを実行するだけだ。"
"22120-177-カリン" = "分かった、従おう。"
"22120-178-アスナ" = "うんうん！私たちに任せて♪"
"22120-179-アカネ" = "ふふっ、精一杯頑張りますね。"
"22120-180-ユズ" = "（……たしかに、あの時と違ってC&Cが全員いるのなら……#n突破できる可能性は高い……）"
"22120-181-アカネ" = "それではこれで決まりですね。#n正面は部長と一緒に私たちC&Cが担当いたします。"
"22120-182-ウタハ" = "後方から潜入するのはその他、ゲーム開発部と私たち……そして先生かな？"
"22120-183-ハレ" = "私たちヴェリタスは遠隔で支援するね。"
"22120-184-マキ" = "防衛システムのハッキングは私たちに任せて！"
"22120-185-コタマ" = "完璧にやり遂げてみせます。"
"22120-187-モモイ" = "よし、じゃあこれで行こっか！"
"22120-188" = "[s] \"うん。\""
"22120-189-モモイ" = "目標は「要塞都市エリドゥ」の中央タワー！#nアリスが連れて行かれた場所！"
"22120-190-モモイ" = "勝手に家出したアリスを！"
"22120-191-モモイ" = "私たちの手で連れ戻すんだよ！"
"22120-195" = "[ns] \"それじゃあ、これより――\""
"22120-204" = "[ns] \"――作戦開始！\""
"22120-206" = "次回;ビッグシスター"
