[translation]
"22135-3-アスナ" = "やっほ～！"
"22135-12-アスナ" = "あははっ！どんどん爆発してく！"
"22135-13-カリン" = "これで30台目……。"
"22135-17-カリン" = "……終わりが見えない。"
"22135-18-アカネ" = "ええ、想定より数が多いですね。"
"22135-19-アカネ" = "まぁ、そのおかげで「派手に暴れて騒ぎを起こす」という陽動の目的は達成できていますが……。"
"22135-23-カリン" = "……！#nそっちか！"
"22135-33-アカネ" = "あら。"
"22135-34-アスナ" = "わぁ！すご～い！"
"22135-35-カリン" = "……お出ましだな。"
"22135-41-トキ" = "お待ちしておりました、先輩方。"
"22135-44-トキ" = "C&C所属、コールサインゼロフォー。#n[ruby=あすま]飛鳥馬[/ruby]トキ、ご挨拶申し上げます。"
"22135-46" = "次回;要塞都市エリドゥ"
