[translation]
"22140-1" = "第14話;要塞都市エリドゥ"
"22140-2-アカネ" = "思ったより早く現れてくれましたね。"
"22140-3-カリン" = "私たちがここに来る事は最初からお見通しだったというわけだ。"
"22140-5-トキ" = "はい。リオ様はすべて把握されておいでです。"
"22140-6-トキ" = "C&Cの判断も、その動きも――"
"22140-7-トキ" = "そしてもちろん――先生のねらいも、全て。"
"22140-8-トキ" = "ですので、僭越ながら申し上げます。#n――これ以上の抵抗は無意味です。大人しく投降をお願い致します。"
"22140-9-カリン" = "ほう……なるほど。"
"22140-10-アスナ" = "う～ん、それはちょっと難しいかなぁ？"
"22140-20-トキ" = "……！？"
"22140-21-アスナ" = "わっ、ビックリした！"
"22140-22-アカネ" = "あら、この程度では相手にもなりませんか。"
"22140-23-カリン" = "あ、アカネ……？"
"22140-24-トキ" = "……[ruby=むろかさ]室笠[/ruby]アカネ先輩。"
"22140-25-トキ" = "……戦闘では爆発物を利用した広域制圧を得意とする――"
"22140-26-トキ" = "――C&Cの要注意人物。"
"22140-27-アカネ" = "ふふ、初対面の後輩にそう言われると少し照れくさいですね。"
"22140-28-アカネ" = "先程のは、あくまでも挨拶のつもりだったのですが……。"
"22140-29-トキ" = "……。"
"22140-30-アカネ" = "はじめまして後輩さん。#nトキ……でしたね？"
"22140-31-アカネ" = "先日は部長が大変お世話になったと伺いました。"
"22140-32-アカネ" = "それに……投降しろという丁寧なご勧告まで頂くなんて……。"
"22140-33-アカネ" = "ふふ、あなたがリオ会長のボディーガードだということは伺っていましたが……#nまったく。"
"22140-35-アカネ" = "……C&Cを、見くびってもらっては困りますね。"
"22140-36-トキ" = "……！"
"22140-40-アカネ" = "目には目を、歯には歯を。本日はそのために来ておりますから。"
"22140-45-アカネ" = "……もちろんここで大人しく投降するのでしたら、水に流す事もできますよ？"
"22140-47-トキ" = "……それはできません。"
"22140-48-トキ" = "私はリオ様から命令を受けております。"
"22140-49-トキ" = "「指示に背いて行動しているC&Cを制圧せよ」と……。"
"22140-50-トキ" = "そのため、この場から退く事はできません。"
"22140-52-アスナ" = "ふ～ん、真面目ちゃんなんだね、トキちゃんは♪"
"22140-53-カリン" = "想定通りの反応だ。"
"22140-54-トキ" = "C&Cは秘密エージェント組織……。"
"22140-55-トキ" = "最初は、潜入によってこちらを[ruby=かくらん]撹乱[/ruby]すると踏んで、備えておりましたが……"
"22140-56-トキ" = "まさかこんな正面からいらっしゃるとは……。"
"22140-57-トキ" = "……想定外でした。#nですが、私がここにいる事もあなた方の作戦の内なのでは？"
"22140-59-カリン" = "……そうなのか？"
"22140-60-アスナ" = "あはは♪そういうのじゃないかなぁ～？"
"22140-62-アカネ" = "あら、そうですねぇ……私たちとしても想定外ですよ。"
"22140-63-トキ" = "――誤魔化そうとしても無駄です。"
"22140-64-トキ" = "すでに先輩方の思惑など分かっております。"
"22140-65-トキ" = "ネル先輩と先生がおりませんね。"
"22140-66-トキ" = "つまり、そういう作戦なのでしょう？#n先輩方は私の足止めを任されている。"
"22140-67-トキ" = "それはある意味で正しいです。リオ様の「武装」を纏った私との正面対決を避け、"
"22140-68-トキ" = "その間にミレニアムの最強戦力であるネル先輩を自由にさせる――"
"22140-69-トキ" = "それであれば、ええ……たしかに勝算はあるでしょう。"
"22140-70-ネル" = "誰に勝算があるって？"
"22140-78-アスナ" = "あははっ！遅かったじゃん部長！"
"22140-79-トキ" = "ネル……先輩が何故……ここに……？"
"22140-80-ネル" = "あぁ？んなの決まってんだろ。"
"22140-81-ネル" = "リベンジマッチだよ。"
"22140-82-トキ" = "リベンジ……？"
"22140-83-ネル" = "あたしが別行動してたら、てめぇは絶対止めに来るだろ？"
"22140-84-ネル" = "面倒なのはごめんだからよぉ。"
"22140-85-ネル" = "それなら、チビを助けに行くのは――"
"22140-86-ネル" = "てめぇを倒した「後」でも、遅くねぇって事だ。"
"22140-87-ネル" = "おい、後輩。この間はよくもやってくれたな。"
"22140-88-ネル" = "先輩に楯突いたらどうなんのか、じ～っくり教えてやるよ。"
"22140-95-トキ" = "……！！"
"22140-96-トキ" = "対応、開始。"
"22140-102-ネル" = "は！いいぜ！やってやろうじゃねーか！"
"22140-106-コトリ" = "これで……！"
"22140-107-ヒビキ" = "邪魔なドローンは、全部、倒した……！"
"22140-108" = "[ns] \"みんな、気を引き締めて！そろそろ地上だよ……！\""
"22140-114-モモイ" = "よーーし！外に出れた！"
"22140-115-ミドリ" = "それで、ここからどこに向かえばいいの？"
"22140-117-ハレ" = "アリスがいるのはおそらくエリドゥの中心部……。"
"22140-118-ハレ" = "そう、この中央にあるタワーだよ。"
"22140-119-コタマ" = "現在地からルートを算出しました。#n左手にある大通りをまっすぐ北に進めば辿り着けます。"
"22140-120" = "[ns] \"サポートありがとう。じゃあ、行こうか。"
"22140-131-モモイ" = "どいたどいたー！！"
"22140-139-ハレ" = "道はこっちでナビするから。"
"22140-140-マキ" = "どんどん行っちゃおー！GOGO～！"
"22140-142" = "次回;罠"
