[translation]
"22180-1" = "第18話;それでも越えられない壁"
"22180-13-トキ" = "……！"
"22180-14-ネル" = "遅ぇ、遅ぇ、遅ぇ……"
"22180-23-ネル" = "おせぇんだよ、後輩！"
"22180-32-トキ" = "（スピードは明らかに「武装」を使う私の方が上……なのに）"
"22180-39-トキ" = "（データは間違っていないはず――#n　リオ様の命令通り、戦場の地形を変更したというのに）"
"22180-40-トキ" = "（それでも勝敗がつかないというのは……まさか、データが間違っている？）"
"22180-41-トキ" = "（いや、これはそういう次元の問題では……）"
"22180-49-トキ" = "彼女の射程に入るたびに、データが……#nリアルタイムで更新されている……！？"
"22180-50-トキ" = "（間合いを詰められると……危険……！）"
"22180-56-トキ" = "くっ……！！"
"22180-57-トキ" = "これほどの超長距離からの……狙撃……まさか……！"
"22180-59-カリン" = "こちらコールサインゼロツー。"
"22180-60-カリン" = "……先輩の背中は任せてくれ。"
"22180-61-アスナ" = "あれ？道に迷ってたと思ったんだけどー……意外とそんな事なかった？"
"22180-62-アカネ" = "それはアスナ先輩が幸運だからですよ……普通は抜け出せません。"
"22180-64-トキ" = "要塞都市の迷路を……いとも容易く……！？"
"22180-65-トキ" = "そんな事、確率的にあり得ない……。"
"22180-66-ネル" = "ケッ！偉そうに分断だの何だの御託を並べてたクセによぉ。"
"22180-67-ネル" = "結局言葉だけだったのか？あぁ？"
"22180-68-トキ" = "……。"
"22180-72-リオ" = "トキ、一旦退きなさい。"
"22180-73-トキ" = "……！"
"22180-74-トキ" = "リオ様、私は……。"
"22180-75-リオ" = "貴女を責めているわけではないわ。#nヴェリタスの干渉で、アバンギャルド君の制御権が奪われてしまった。"
"22180-76-リオ" = "これはあくまで、私の予測不足による失敗……#nまずは撤退して、状況を立て直しましょう。"
"22180-77-トキ" = "……イエス、マム。"
"22180-78-トキ" = "――現場から離脱します。"
"22180-79-ネル" = "ハァ！？ざけんなコラ！"
"22180-88-ネル" = "おい！逃げんじゃねえ！！"
"22180-90-アスナ" = "えっ、なになに？トキちゃん行っちゃったの？"
"22180-91-カリン" = "……逃してしまったようです。"
"22180-92-ネル" = "あー！クソッ！#nこの場でケリつけたかったのに！"
"22180-94-アカネ" = "仕方ないですよ部長、想定外の交戦でしたし……"
"22180-95-アカネ" = "戦況そのものが変わってしまいましたから。"
"22180-96-アカネ" = "陽動作戦は一旦中断して……まずは先生と合流しましょう。"
"22180-97-アカネ" = "この作戦は、アリスちゃんを連れ出すためのものですからね。"
"22180-98-アカネ" = "そうですよね、部長？"
"22180-99-ネル" = "うっ……。"
"22180-100-ネル" = "……あぁ、わ～った。わ～ったって。"
"22180-101-ネル" = "うし、行くか。"
"22180-104" = "[ns] \"えっと、ここを曲がったら……次はどこに向かえばいい？\""
"22180-105-チヒロ" = "右に曲がって、直進！そこが目的地だよ。"
"22180-106-モモイ" = "よーし、行っくよ～！"
"22180-107-ミドリ" = "ここにアリスが……！"
"22180-118" = "[ns] \"ここが要塞都市「エリドゥ」の中央タワー……。\""
"22180-119-ユズ" = "アリスちゃんが……ここに……。"
"22180-120-モモイ" = "……行こう！"
"22180-121-ミドリ" = "うん！"
"22180-123-モモイ" = "え？"
"22180-125-アスナ" = "あっ！ご主人様とみんな～！#nやほやほ！"
"22180-126-アカネ" = "皆さん到着されていたのですね。"
"22180-132-モモイ" = "先輩！"
"22180-133" = "[s] \"ネル達がここにいるという事は……トキは？\""
"22180-134-ネル" = "……ぐっ！！"
"22180-135-アスナ" = "あはは、それがね～"
"22180-136-カリン" = "……はぁ。"
"22180-137-アカネ" = "残念ながら、逃げられてしまいました。"
"22180-138-ネル" = "あとちょっとでぶちのめせたのによ！"
"22180-140" = "（その後、トキとの戦いについて、アカネから一部始終を聞いた）"
"22180-142" = "[ns] \"さっきの地震はそれだったんだね……。\""
"22180-143-アカネ" = "ええ……そのせいで陽動自体の意味がなくなってしまったわけです。"
"22180-144" = "[s] \"地形が変わるなんて、普通は想像できないから仕方ないよ……。\""
"22180-145-カリン" = "先生の方も、何か起きていたように見えるが……。"
"22180-146-アスナ" = "あ、たしかに。一緒にいたエンジニア部は？"
"22180-147-モモイ" = "う～ん、何か起きていたというか……。"
"22180-148-ミドリ" = "たしかに大変といえば大変だったけど、その……。"
"22180-149" = "[s] \"強かったね、アバンギャルド君……。\""
"22180-155" = "[ns] \"チヒロ、このタワーにアリスがいるの？\""
"22180-156-チヒロ" = "その……会長が言ってたんだよね？#nアリスのヘイローを破壊するって。"
"22180-157-チヒロ" = "そのためには、相応の施設が必要なんじゃないかな。"
"22180-158-チヒロ" = "そして、ここエリドゥは全ての電力がこのタワーに集中するような構造になっている。"
"22180-159-チヒロ" = "これほどの規模の施設が、会長の手によって作られた理由……そして、会長の動機……#n答えは明白だろうね。"
"22180-160-モモイ" = "本当に……アリスがあそこに……"
"22180-161-ネル" = "つまり、後はこのバカデカいタワーを登りゃあいいんだろ？"
"22180-162" = "[s] \"そうだね、あとは登るだけ……。\""
"22180-163-チヒロ" = "ただ、残念だけど――"
"22180-171-チヒロ" = "あの会長が、門番を用意しないわけがないよね。"
"22180-175-トキ" = "お待ちしておりました、先輩方、先生。"
"22180-176" = "[s] \"やっぱり、トキが門番なんだね……。\""
"22180-177-アスナ" = "あっ！また会えたね～！トキちゃんやほ！"
"22180-178-ネル" = "あぁん？んだよ、さっきは尻尾巻いて逃げ出したくせに……"
"22180-179-ネル" = "一体どのツラ下げてあたしらの前に現れてんだ？"
"22180-180-リオ" = "作戦を変更したのは、貴女たちだけだと思って？"
"22180-181-ネル" = "……リオ。"
"22180-182-リオ" = "貴女たちが来ることを見越していくつもの計画を準備してきたけれど――"
"22180-183-リオ" = "まさか、防衛システムをすべて壊して、ここまで到達するなんて……。"
"22180-184-リオ" = "変数として機能し、私の計算を狂わせたのも、すべては――"
"22180-185-リオ" = "シャーレの先生、貴方が関わったからかしら？"
"22180-186" = "[s] \"…………リオ。\""
"22180-187-リオ" = "それならそれで構わないのよ。#n貴方が規格外の力を見せるのなら、こちらもそれ相応の切り札を出すまで。"
"22180-188-リオ" = "トキ。現時刻をもって[ruby=Abi-Eshuh]「アビ・エシュフ」[/ruby]の使用を許可するわ。"
"22180-189-トキ" = "……リオ様、それは。"
"22180-190-リオ" = "ええ、本来は「名もなき神々の王女」との戦闘用だけど……仕方ないわ。"
"22180-191-リオ" = "ここでこの子たちを阻止できなければ、すべてが無に帰してしまうのだから。"
"22180-196-トキ" = "……イエス、マム。"
"22180-197-トキ" = "パワードスーツシステム「アビ・エシュフ」へ移行します。"
"22180-198" = "[s] \"アビ……エシュフ？\""
"22180-211-ミドリ" = "この音は……。"
"22180-213-チヒロ" = "……ッ！#n上！"
"22180-217-トキ" = "呼出信号確認。"
"22180-234-みんな" = "わ、わぁっ！？一体なにっ！？"
"22180-249" = "パワードスーツシステム[wa:1000]「アビ・エシュフ」[wa:1500]起動"
"22180-254" = "戦闘、[wa:1500]開始します。"
"22180-258" = "[ns] \"………来る！\""
