[translation]
"22230-1" = "第23話;王女のためのパヴァーヌ（２）"
"22230-2-Key" = "……リソース確保失敗。システムシャットダウン。"
"22230-3-ユウカ" = "みんな、大丈夫！？"
"22230-4-モモイ" = "ユウカ……！"
"22230-5-ミドリ" = "ノア先輩！"
"22230-6-ユズ" = "こ、ここには、どうやって……？"
"22230-7-ユウカ" = "状況が普通ではないということはよくわかりました、先生！"
"22230-8-ノア" = "最初は都市の位置を伝えるだけで、手を引くつもりだったのですが……"
"22230-9-ノア" = "ふふっ、ユウカちゃんが、やっぱりそれだけじゃダメだって……#n最後まで何とかしないと。と言ってましてね？"
"22230-10" = "[s] \"さすがユウカ！タイミング完璧だったよ！\""
"22230-11-ユウカ" = "これくらい当然です。"
"22230-12-ユウカ" = "それより、会長！！"
"22230-14-リオ" = "！！"
"22230-15-ユウカ" = "セミナーの予算を横領してこんな都市を作るなんて……#n後でお説教ですよ！覚悟しておいてください！"
"22230-16-リオ" = "……ユウカ。"
"22230-20-Key" = "リソース確保プロセスエラー。#n緊急状況発生Divi:Sion電源、プロトコル実行者を保護するためエリドゥ中央タワーに集………"
"22230-24-Key" = "……邪魔者？"
"22230-25-Key" = "そんなはずは――都市内の残存兵力はゼロ。"
"22230-26-Key" = "論理エラー発生。確認のため、画面を表示します。"
"22230-35-モモイ" = "あっ、あれはまさか……！"
"22230-39" = "[ns] \"………アバンギャルド君とエンジニア部！"
"22230-40-コトリ" = "怪しい気配を事前にキャッチ！エンジニア部が華麗に復活しましたよ～！"
"22230-41-ヒビキ" = "あちこちに不思議なセンスの機械がいっぱいあるね。"
"22230-42-ウタハ" = "おそらくこれが……会長が言っていた、廃墟から溢れた脅威なのだろうね。"
"22230-43-ウタハ" = "ふふ……ならば私たちも負けていられないね。"
"22230-44-ウタハ" = "相手が廃墟から這い上がってきた怪物なら……"
"22230-45-ウタハ" = "こちらは宇宙を目指す技術者。"
"22230-52-ウタハ" = "私たちには、マキが監修したデザインセンスで武装した味方ができたところでね。"
"22230-53-コトリ" = "はい！敵の敵は味方！私たちが改造した敵も味方！です！"
"22230-54-ヒビキ" = "うん……特に、今後の宇宙戦艦でも使える火力兵器をつけたから。"
"22230-55-ウタハ" = "いくら廃墟の怪物だとしても、「アバンギャルド君Mk.2」の敵じゃあない。"
"22230-56-ウタハ" = "それでは、行こうか！突進ー！"
"22230-57-コトリ" = "はい！廃墟のザコをお掃除しちゃいましょう！"
"22230-58-ヒビキ" = "お～！"
"22230-66-モモイ" = "アバンギャルド君を改造して……宇宙戦艦を……"
"22230-67-モモイ" = "え？何言ってるの？"
"22230-68" = "[s] \"宇宙戦艦なら仕方ないよ！だってみんなのロマンだから！\""
"22230-69-ミドリ" = "えっと……先生が何をおっしゃっているのか、よく分かりません……。"
"22230-70-Key" = "理解不能。状況判断不可。"
"22230-71-Key" = "命令修正および再実行。追従者は想定外の兵力と戦闘を避け、エリドゥ中央タワーに集結……。"
"22230-72-？？？" = "申し訳ありませんが、その子たちはここまで来られませんよ。#nタワーの入口でしたら、エイミとC&Cのメンバーが塞いでおりますので。"
"22230-75" = "[ns] \"えっ？ヒマリ！？なんでここに！？\""
"22230-76-ヒマリ" = "うふふっ。なんだかんだありまして～とでも言いましょうか？"
"22230-77-リオ" = "ヒマリ……貴女、逃げたんじゃ……。"
"22230-78-ヒマリ" = "逃げるだなんて……なんと寂しいことを。"
"22230-79-ヒマリ" = "この先の状況について、ある程度見当がついておりましたから。"
"22230-80-ヒマリ" = "隔離施設を抜け出した後、急いでここに来たのです。"
"22230-81-ヒマリ" = "リオのことですから……また事件を引き起こすだろうと予測していたのです。"
"22230-82-ヒマリ" = "どうですか？#nふふっ――当たりましたか？"
"22230-83-リオ" = "…………。"
"22230-84-ヒマリ" = "さて、これが＜Key＞……#n無名の司祭の「オーパーツ」を稼働させるためのトリガーAIですね。"
"22230-85-ヒマリ" = "このまま放っておけば、きっとアリスの人格は＜Key＞に置き換えられ……#n無名の司祭が望む通り「名もなき神々の王女」として覚醒することになるでしょう。"
"22230-86-ユズ" = "そ、それじゃあ……！"
"22230-87-モモイ" = "！！#nヒマリ先輩……それって……"
"22230-88-ミドリ" = "アリスちゃんは、このまま……。"
"22230-89-ヒマリ" = "もちろんそれを防ぐ方法もあります。"
"22230-90" = "[s] \"……一体、何をすればいいの？\""
"22230-91-ヒマリ" = "事態は一刻を争います……既に、無名の司祭は動き出しておりますから。"
"22230-108-ヒマリ" = "ですから、無名の司祭が到着する前に、まず私たちの手でアリスを――"
"22230-109-ヒマリ" = "＜Key＞の起動でデータベースの深部に隔離されてしまったアリスを起こすのです。"
"22230-111-ヒマリ" = "そうすれば、この事態を止める事ができるでしょう。"
"22230-115-モモイ" = "そんなこと……本当にできるの？"
"22230-116-ミドリ" = "アリスを連れ戻せるってことですか！？"
"22230-117-ヒマリ" = "できますとも。#nリオ、ダイブ設備くらいありますよね？"
"22230-118-リオ" = "ええ、あるわ。#n……でもそんな事、現実的にできるわけ……！"
"22230-119" = "[s] \"あれ？\""
"22230-120-リオ" = "危険すぎる。たとえアリスの精神世界に侵入できたとしても、#n下手すれば二度と戻って来れなくなってしまうのよ。"
"22230-121-リオ" = "そもそも、そんなこと一体誰が――"
"22230-122-ヒマリ" = "現状、アリスを連れ戻せるのはゲーム開発部と先生しかおりません。"
"22230-123-ヒマリ" = "危険が伴いますが……それ以外に方法はありません。"
"22230-125-ユズ" = "……やります。"
"22230-126-ユズ" = "アリスちゃんを……"
"22230-127-ユズ" = "連れ戻せるのなら。"
"22230-128-ヒマリ" = "ほらね？"
"22230-129-リオ" = "…………。"
"22230-130-ヒマリ" = "それでは、私が今からアリスの精神を分析して隙間を作ります。"
"22230-131-ヒマリ" = "皆さんはアリスの精神世界に入って、彼女を連れ戻してきてください。"
"22230-136" = "[ns] \"……分かった。行こう！\""
"22230-138-ヒマリ" = "ええ、それでは始めましょう。"
"22230-143-ヒマリ" = "……準備完了です。"
"22230-144-ヒマリ" = "それでは皆さん、お願いします。"
"22230-148" = "次回;自分がなりたいもの"
