[translation]
"10012015-2-セリカ" = "あいたたた……。"
"10012015-3-セリカ" = "みんな大丈夫？怪我はない？"
"10012015-4-シロコ" = "うん……アヤネも無事。"
"10012015-5-アヤネ" = "あ、ありがとうございます、シロコ先輩。"
"10012015-6-セリカ" = "せ、先生……！？先生は大丈夫なの！？"
"10012015-12-ノノミ" = "よいしょっと……みなさん無事ですよ～"
"10012015-13-ホシノ" = "うへ～……もう着いたの？起こし方が乱暴じゃない～？"
"10012015-14-アヤネ" = "ノノミ先輩！ホシノ先輩！"
"10012015-15" = "[s1] \"ありがとう。皆のおかげで無事だよ。\"\n[s2] \"心配してくれてありがとう、セリカ\""
"10012015-16-ノノミ" = "ふふっ、どういたしまして～"
"10012015-17-セリカ" = "なっ！だ、誰が心配なんか……！ただ聞いただけよ！"
"10012015-18-ホシノ" = "みんな無事でよかった。誰か怪我でもしてたら、おじさん泣いてたよ～。"
"10012015-20-シロコ" = "……幸い、水着も無事だった。"
"10012015-21-セリカ" = "この状況で気にするポイントそこ！？"
"10012015-22-セリカ" = "い、いやまぁ。着替え持ってきてないから、破れたら困るけど……。"
"10012015-23" = "[s3] \"せっかくの水着が汚れなくてよかった。\"\n[s4] \"怪我がなくてよかった。\""
"10012015-24-シロコ" = "……本当？"
"10012015-25-シロコ" = "……本当？"
"10012015-26-セリカ" = "も、もう！すぐそういう事言う……。"
"10012015-32" = "[ns] \"……アヤネ？\""
"10012015-33-アヤネ" = "な、何でもありません……！怪我人がいなくてよかったです。"
"10012015-34-アヤネ" = "とりあえず、目的の島には着きましたね。"
"10012015-35-アヤネ" = "ただ、乗ってきたヘリは……"
"10012015-36-シロコ" = "……ん。これはしばらく乗れそうにないね。"
"10012015-37-シロコ" = "修理すれば動かせるだろうけど……時間が必要。"
"10012015-38-アヤネ" = "すみません。私がもう少しうまく運転できていたら……"
"10012015-40-セリカ" = "運転とは関係なく急に壊れたんだから、アヤネちゃんが謝ることじゃないわよ。"
"10012015-41-セリカ" = "出発前の整備の時だって異常がないか何度も点検したし……"
"10012015-42-セリカ" = "それなのに急に壊れちゃったんだから……こんなの、誰の責任でもないわよ！"
"10012015-43-セリカ" = "もし責任があるとしたら売ったやつらよ。だからアヤネちゃんが気にすることじゃないわ。"
"10012015-44-アヤネ" = "そ、それは……。"
"10012015-45" = "[s5] \"セリカの言う通り、アヤネのせいじゃないよ。\"\n[s6] \"まずはリゾートへ行こう。もしかしたら修理する方法があるかもしれないし。\""
"10012015-46-アヤネ" = "先生まで……ありがとうございます。"
"10012015-47-アヤネ" = "先生まで……ありがとうございます。"
"10012015-48-アヤネ" = "リゾートに行けば……何か、方法が見つかりますよね？"
"10012015-50-ノノミ" = "うんうん！急がば回れ！です。"
"10012015-51-ノノミ" = "パンフレットによれば、ものすごくリッチで大きなリゾートらしいので、部品や整備できる人もいるかもしれません。"
"10012015-52-シロコ" = "……先生は大丈夫？さっきちょっとふらついてたけど……。"
"10012015-53" = "[s] \"大丈夫、心配しないで。\""
"10012015-55-ホシノ" = "……みんなたくましく育ったねぇ。おじさんは嬉しいよ。"
"10012015-56-ホシノ" = "ところで、せっかくの空気に水を差すようで悪いんだけどさ……。"
"10012015-57-ホシノ" = "その……みんなが言ってる「ものすごくリッチで大きなリゾート」って……"
"10012015-58-ホシノ" = "あれのこと……？"
"10012015-65-セリカ" = "何よあれーーーー！？！？！？"
"10012015-66-セリカ" = "こ、これ何？本当にここで合ってるの？"
"10012015-67-セリカ" = "ここも……。"
"10012015-69-セリカ" = "ここも……！！"
"10012015-71-セリカ" = "……全部、ただの廃墟じゃない！人っ子一人いないし！！"
"10012015-73-セリカ" = "ねえ、違う島に来たんじゃないの？本当にここなの？"
"10012015-74-シロコ" = "……いや。座標上、確かにここで合ってる。"
"10012015-75-アヤネ" = "どうみても「リゾート」と呼ぶには無理がありますが……。"
"10012015-76-アヤネ" = "これじゃあまるで……"
"10012015-78-ホシノ" = "……あ。"
"10012015-79-ホシノ" = "うへー……そっか、そういうことかぁ。"
"10012015-85-セリカ" = "な、なに？どうしたの？何か分かったの？"
"10012015-86-アヤネ" = "……えっとね、セリカちゃん。"
"10012015-87-アヤネ" = "私たちが当たったリゾート利用券……この「土地」の利用権だったみたい。"
"10012015-88-アヤネ" = "ほら、ここに小さく……「チケットを所有する者にリゾート地を利用する権利を与えるものとする。当該地の状態については保証いたしかねます」って……。"
"10012015-89-セリカ" = "ちょっと待って…………これって詐欺よね！？"
"10012015-90-セリカ" = "そんな……信じらんない……"
"10012015-91-セリカ" = "景品がお金じゃなくても前向きに……いい機会だからゆっくりしようって……"
"10012015-92-セリカ" = "そう思ったのに……どうしてこんな……。"
"10012015-93-セリカ" = "……悔しい、私たちが何したっていうのよ……。"
"10012015-94-アヤネ" = "セリカちゃん……。"
"10012015-96-ノノミ" = "…………。"
"10012015-97-セリカ" = "……くすん。"
"10012015-98" = "[s7] \"……まだ諦めるには早いよ。\"\n[s8] \"むしろ今からがスタートかもしれないよ。\""
"10012015-99-セリカ" = "……先生？"
"10012015-100-セリカ" = "……先生？"
"10012015-101-ノノミ" = "うんうん！先生の言う通りですよ、セリカちゃん！"
"10012015-102-ノノミ" = "想像とはちょっと違うけど、空気も水も綺麗な島に来たのは事実ですし！"
"10012015-103-ノノミ" = "遊ぶための道具は揃ってますから、思いっきりバカンスを楽しみましょう～！"
"10012015-104-シロコ" = "ん。持ってきた備品は全部無事だったから、ヘリから取ってくればいいよ。"
"10012015-105-シロコ" = "あと、さっき倉庫とか設備を確認してきたんだけど……状態は良好だったよ。"
"10012015-106-シロコ" = "ちょっと古くて錆びてたり、ホコリを被ってるだけだし。手入れしたら全然使える。"
"10012015-108-セリカ" = "ノノミ先輩……シロコ先輩。"
"10012015-109-アヤネ" = "……そうだよセリカちゃん。まだ諦めるには早いよ！"
"10012015-110-アヤネ" = "ここがリゾート地なことに変わりはないし……"
"10012015-111-アヤネ" = "ヘリもリゾートも、私たちが修理すればいいんだよ。"
"10012015-112-アヤネ" = "設備の修理は慣れっこだしね！前向きにいこうよ、セリカちゃん。"
"10012015-114-シロコ" = "ん。設備の補修や整備は、私たちアビドス高等学校の十八番。"
"10012015-115-ノノミ" = "うんうん！この広いリゾート地と無人島が、ぜーんぶ私たちの物になったってことですよ！"
"10012015-116-ノノミ" = "どう楽しむかは、これからの私たちにかかってるんです！"
"10012015-117-ノノミ" = "アヤネちゃんの言う通り、これから最高の休暇を過ごせばいいだけですからね☆"
"10012015-118-ホシノ" = "うへ……おじさんも頑張るかぁ。"
"10012015-120-セリカ" = "みんな……。"
"10012015-121" = "[s9] \"まだ泣くのは早いよ、セリカ。\"\n[s10] \"泣くのはいろいろ試した後でも遅くないよ。\""
"10012015-127-セリカ" = "……だ、誰が泣いてるって！？"
"10012015-128-セリカ" = "……ああもう、覚悟しなさいよ！！こうなったら思いっきり遊んでやる！！"
"10012015-129-セリカ" = "私は絶対に諦めないわよ！ここで「最高の休暇」を過ごしてやるんだから！！"
"10012015-132-一同" = "おーー！！"
