[translation]
"10012025-3-ジャブジャブヘルメット団A" = "こ、こいつらめちゃくちゃ強いじゃん！総員退却！！"
"10012025-7-ジャブジャブヘルメット団B" = "うちらが負けるなんて信じらんない！向こう二人しかいないのに！？"
"10012025-8-ラブ" = "ぐっ……うちらジャブジャブヘルメット団がやられるなんて……！"
"10012025-9-ラブ" = "強敵ってわけね……！"
"10012025-10-ラブ" = "でも諦めるわけには……！！"
"10012025-14-ラブ" = "あっ、アイタタタッ！"
"10012025-15-ラブ" = "い、痛い！痛いってば！"
"10012025-16-ラブ" = "くっそー！覚えてなさいよ！"
"10012025-17-ラブ" = "うちらがこのまま諦めると思わないでよね……！！"
"10012025-22-セリカ" = "あいつら……いったい何なの……？"
"10012025-23-セリカ" = "暴れるだけ暴れて、どっか行くなんて……。"
"10012025-24-ホシノ" = "……あ～あ。せっかく片付けたのに、振り出しに戻っちゃった。"
"10012025-25-ホシノ" = "皆になんて言おうねぇ……。"
"10012025-29-ノノミ" = "ただいま戻りましたよ～☆"
"10012025-30-セリカ" = "……先輩たち！？"
"10012025-31-ホシノ" = "ナイスタイミングだねぇ。"
"10012025-36-シロコ" = "備品は全部運び出せた。特に壊れたものもなく、無事だったよ。"
"10012025-37-アヤネ" = "セリカちゃんたちの方、お片付けは順調です……"
"10012025-39-アヤネ" = "……？"
"10012025-46-セリカ" = "ちょ、ちょっと待って！"
"10012025-47-セリカ" = "掃除は終わってる、いや終わってたのよ！先輩と先生とやってたの！"
"10012025-48-セリカ" = "終わってたんだけど、こうなってるのには理由があって……！"
"10012025-50-アヤネ" = "セリカちゃん……。"
"10012025-51-アヤネ" = "二人で片付けるには広すぎましたからね……大丈夫ですよ。"
"10012025-52-シロコ" = "……ん、今からみんなで手分けすればすぐ終わる。"
"10012025-53-セリカ" = "ほ、本当だってば！？掃除をサボってたんじゃなくて……！"
"10012025-54-ノノミ" = "まぁまぁ、今から一緒に片付ければいいんですよ。"
"10012025-55-ノノミ" = "みんなで頑張りましょう～☆"
"10012025-57-セリカ" = "本当だってばぁぁぁぁー！！"
"10012025-59" = "（その後、掃除が終わってからこれまでの事についてゆっくり説明した）"
"10012025-61-ジャブジャブヘルメット団A" = "うう、肩痛い……赤くなってるじゃん……。"
"10012025-62-ジャブジャブヘルメット団A" = "やっぱこのままじゃ厳しいよ……どうしよう隊長……？"
"10012025-63-ジャブジャブヘルメット団A" = "もう戻る……？他の島を探してみるとか……？"
"10012025-65-ラブ" = "……今、なんて？"
"10012025-67-ジャブジャブヘルメット団A" = "ひ、ひいっ……な、何も……。"
"10012025-68-ジャブジャブヘルメット団B" = "しょうがないじゃん……！今のうちらじゃ歯がたたないよ。"
"10012025-69-ジャブジャブヘルメット団B" = "それにあいつら、まだ仲間がいそうだったし……。"
"10012025-71-ラブ" = "……そうね。"
"10012025-72-ラブ" = "……じゃあ、あんま気が向かないけど……。"
"10012025-74-ラブ" = "……うちらも増員呼ぶとすっかぁ。"
