[translation]
"10012095-2-ノノミ" = "今日は本当にいろんな事がありましたね～☆"
"10012095-3-セリカ" = "せっかく一等が当たったって喜んでたのに、めちゃくちゃな事ばっか……もう嫌……。"
"10012095-5-シロコ" = "セリカ、タダより高い物はないよ。"
"10012095-6-セリカ" = "そういうシロコ先輩だって、喜んで水着を用意してたじゃん！？"
"10012095-7-シロコ" = "それはそれ、これはこれ。"
"10012095-9-ホシノ" = "でもまぁ、なんとか帰れそうでよかった、よかった。"
"10012095-10-アヤネ" = "先生も、わざわざ時間を割いていただいたのに、こんな事になってしまって……。"
"10012095-11-ホシノ" = "うへ～ここ来てからも色々あったし、先生あんま休めなかったんじゃない？"
"10012095-12" = "[s] \"ううん、私は大丈夫。\""
"10012095-13-アヤネ" = "大丈夫……ですか？"
"10012095-14" = "[s1] \"みんなで楽しく過ごせたから。\"\n[s2] \"いいバカンスだったよ。\""
"10012095-17-ノノミ" = "ふふっ……それなら良かったです☆"
"10012095-18" = "[s] \"みんなはこの夏、楽しかった？\""
"10012095-19-セリカ" = "……き、急に何よ！？"
"10012095-20-ホシノ" = "セリカちゃん恥ずかしがってる～可愛いね～"
"10012095-21-セリカ" = "うっ！ ほ、ホシノ先輩まで！"
"10012095-22-シロコ" = "……ん。あえて言うなら当然――"
"10012095-24-ノノミ" = "はい～！ と～っても楽しかったですよ☆"
"10012095-25-アヤネ" = "いろいろあったけど……みんなと、先生と一緒に過ごせましたから。"
"10012095-27-シロコ" = "ん。セリカは、どう？"
"10012095-29-セリカ" = "わ、私！？そ、そりゃあ……！"
"10012095-30-セリカ" = "と、当然、た、た、楽しかっ……。"
"10012095-31" = "[s] \"うん、じゃあ私はそろそろ帰るね。\""
"10012095-32-ホシノ" = "そっか……残念だけど、先生忙しいもんね。"
"10012095-33-アヤネ" = "それでしたら早めに動かないと……ヘリでお送りできなくなっちゃいます。"
"10012095-35-シロコ" = "私たちは片付けがあるから、明日まで残る予定。"
"10012095-36-セリカ" = "ねぇ、私の返事まだ終わってないんだけど！？"
"10012095-37-ノノミ" = "セリカちゃん、その続きは今度、帰ってからゆっ～くり伝えてもいいんですよ？"
"10012095-38-セリカ" = "ああもう！じゃあこれで終わり！"
"10012095-39-セリカ" = "終わりだから！"
"10012095-41" = "[ns] \"うん、じゃあ先に帰るね。\""
"10012095-42-アヤネ" = "はい！それでは、先生をシャーレまで送ってきますね！"
"10012095-43-ホシノ" = "いってらっしゃ～い。"
"10012095-46-ノノミ" = "……先生、短い間でしたが、リフレッシュできたでしょうか？"
"10012095-47-シロコ" = "十分だよ。元気もフル充電できたんじゃないかな。"
"10012095-48-ノノミ" = "だといいですね～"
"10012095-49-ホシノ" = "さてと。おじさんたちは、リゾートに戻って荷物をまとめますか～"
"10012095-50-セリカ" = "はぁ……帰ったら早くバイト入らなきゃ。お休みもあとちょっとだし……。"
"10012095-54-ノノミ" = "あっ「リゾート使用券」が……。"
"10012095-55-セリカ" = "あれ？ノノミ先輩、もうそれは必要ないんじゃない？"
"10012095-56-ノノミ" = "ふふっ、記念に持って帰ろうかな～と思いまして。"
"10012095-57-ノノミ" = "よいしょ。"
"10012095-59-ノノミ" = "……あら？"
"10012095-60-ホシノ" = "ノノミちゃん、どうしたの？"
"10012095-61-ノノミ" = "えっと……この、ちょうど端っこの方に……「リゾート使用権」の最終権利者の名前を見つけまして。"
"10012095-62-セリカ" = "えっ、最終権利者！？"
"10012095-63-ホシノ" = "さっき、見落としてたの？"
"10012095-64-シロコ" = "最終権利者ってことは……今回の騒動を起こした主犯？"
"10012095-65-セリカ" = "「リゾート狩り」が起こるように、穴だらけの「リゾート使用券」をばらまいた張本人ってことよね？"
"10012095-66-セリカ" = "一体誰なの！？"
"10012095-67-ホシノ" = "ちょっとそれ、見せて～"
"10012095-68-ノノミ" = "はい、どうぞ。ホシノ先輩。"
"10012095-69-ホシノ" = "ふむふむ。ローストパラダイース～リゾート投資及び運営総括……"
"10012095-70-ホシノ" = "ええと。"
"10012095-73-ホシノ" = "……うん？"
"10012095-74" = "アビドスリゾート復旧対策委員会"
