[translation]
"10012070-1" = "第7話;飛来する浮き輪"
"10012070-4" = "（……いつの間にか日が昇り、朝になっていた）"
"10012070-5" = "（横になっていた地面が段々熱をもってきて、目が覚めた）"
"10012070-6-ホシノ" = "……おっ、先生起きた～？"
"10012070-7-ホシノ" = "もうすぐお昼だよ～お寝坊さんだね。昨日遅く寝たからかな？"
"10012070-8-ホシノ" = "それとも休みの日はいつもこう？"
"10012070-9" = "[s1] \"……ホシノ？\"\n[s2] \"他のみんなは？\""
"10012070-10-ホシノ" = "まだ眠そうだねぇ～"
"10012070-11-ホシノ" = "ん？えっとね……"
"10012070-12-ホシノ" = "みんなヘリを直しに行ったんだ。結構、手間がかかる作業だからさ。"
"10012070-13-ホシノ" = "……ああ、私？"
"10012070-14-ホシノ" = "おじさんは先生を守るという重大な任務を任されたのさ。警備システムは稼働してるけど、念のため、ね。"
"10012070-15-ホシノ" = "……動きたくないからじゃないよ？"
"10012070-16-ホシノ" = "さて、先生も起きたし……。"
"10012070-17-ホシノ" = "……次は私が寝る番だね～"
"10012070-18" = "[s3] \"重大な任務は！？\"\n[s4] \"そう言うと思ってたよ。\""
"10012070-19-ホシノ" = "あはは、役割交代ってことだよ。"
"10012070-20-ホシノ" = "あはは、役割交代ってことだよ。"
"10012070-21-ホシノ" = "先生が寝てる間私が見張ってたからね、今度は先生の番。"
"10012070-22-ホシノ" = "おじさんは今からちょっと一眠りするからさ。"
"10012070-23-ホシノ" = "うへ……もう少ししたらみんなのとこに行くってことで、どうかな？"
"10012070-24-ホシノ" = "その前にみんなが来そうなときは、先に起こしてね……約束だよ、先生～"
"10012070-30-ホシノ" = "……zzz。"
"10012070-31" = "[s5] \"……おやすみ、ホシノ。\"\n[s6] \"うん。いいタイミングで起こすね。\""
"10012070-32-ホシノ" = "うんうん……ふにゃ……。"
"10012070-33-ホシノ" = "うんうん……ふにゃ……。"
"10012070-35" = "（それからしばらく、ボーっと海を眺めながらバカンスを満喫し……）"
"10012070-36" = "（お昼が近づいてきた）"
"10012070-38" = "[ns7] ホシノにそっと声をかける。\n[ns8] \"そろそろ起きる時間だよ、ホシノ。\""
"10012070-39-ホシノ" = "う～ん……先生……あと5分……5分だけ……。"
"10012070-40-ホシノ" = "う～ん……先生……あと5分……5分だけ……。"
"10012070-41" = "[s] \"ホシノ、起き……。\""
"10012070-45" = "[ns] \"……？\""
"10012070-47-SYSTEM" = "リゾート警備システムノ活性化、地域内ニ、許可サレテナイ、武装船舶ノ、動キヲ感知シマシタ。"
"10012070-48-SYSTEM" = "オ客様、ハ、速ヤカニ、屋内ニ避難シテ、クダサイ。繰リ返シマス。速ヤカニ、屋内ニ避難シテ、クダサイ。"
"10012070-49-ホシノ" = "う～ん、初めて聞くアラームだね……。"
"10012070-50-SYSTEM" = "リゾート防御システム稼動。砲門ヲ開放、シマス。"
"10012070-52-ホシノ" = "……う、うん？"
"10012070-53-ホシノ" = "……な、なに……何の音……？"
"10012070-54-ホシノ" = "……先生これ、どういう状況……？"
"10012070-55-ホシノ" = "島のあちこちから大砲とか機関銃が飛び出してるんだけど……"
"10012070-56" = "[s9] \"私にもよく分からない。\"\n[s10] \"何かが攻め込んできたみたい。\""
"10012070-57-ホシノ" = "攻め込んで……？いったい、何が……。"
"10012070-58-ホシノ" = "攻め込んで……？いったい、何が……。"
"10012070-64" = "<System Message>"
"10012070-66" = "警告。リゾート管轄、"
"10012070-69" = "<System Message>"
"10012070-70" = "警告。リゾート管轄、地域、"
"10012070-73" = "警告。リゾート管轄、地域、ガ、"
"10012070-76" = "警告。リゾート管轄、地域、ガ、攻撃サレテ、"
"10012070-79" = "警告。リゾート管轄、地域、ガ、攻撃サレテ、イマス。"
"10012070-82" = "<System Message>"
"10012070-84" = "迎撃、ヲ、"
"10012070-86" = "始メマス。"
"10012070-91-ホシノ" = "……え。"
"10012070-95-ホシノ" = "……先生、あれ見える？あの辺に……。"
"10012070-96-ホシノ" = "浮き輪……にしてはちょっと大きい？"
"10012070-97-ホシノ" = "……こっちに向かってない？"
"10012070-98-ホシノ" = "あれ……いや、あいつは……。"
"10012070-100-ホシノ" = "……あ。"
"10012070-102-？？？" = "嗚呼……やっとお会いできました！そこにいらっしゃったのですね、先生！！"
"10012070-103-？？？" = "このワカモが、あなた様をお迎えに上がりました！今しばらくの辛抱ですよ！"
"10012070-111-ホシノ" = "……わお。"
"10012070-115-アヤネ" = "あそこです！あの海辺！！"
"10012070-119-アヤネ" = "……はっ！？"
"10012070-120-アヤネ" = "あ、あれは一体どういう状況なんですか！？"
"10012070-121-アヤネ" = "どうしてホバークラフトを……！？"
"10012070-123-シロコ" = "たぶんあれが、向こうの全兵力みたいだね。"
"10012070-124-ノノミ" = "なんだかしばらく見ないなぁって思ったら……。"
"10012070-125-セリカ" = "何してんのよ、早く行かなきゃ！あのままじゃリゾート防御システムも長く持たないわよ！"
"10012070-136-アヤネ" = "も、もう崩れ始めてる……それに、あまりにも戦力の差が……。"
"10012070-137-セリカ" = "だから早く行かないと！このまま見てるだけのつもり！？"
"10012070-138-アヤネ" = "そ、そんな事は……あんな大型の機械を相手にするんです。行くならしっかり準備しないと……！"
"10012070-147-アヤネ" = "……大型の機械？"
"10012070-148-シロコ" = "……アヤネ？"
"10012070-149-アヤネ" = "そういえば……大型の機械ならこちらにもあります！"
"10012070-150-アヤネ" = "まだ完全に直ったとは言えないですが……"
"10012070-151-アヤネ" = "少なくとも試してみる価値はあると思います！"
"10012070-153-セリカ" = "……えっと、アヤネちゃん？試すって、何を……。"
"10012070-154-ノノミ" = "……なるほど～☆"
"10012070-155-ノノミ" = "そういえば、私たちほとんど修理終わってましたよね？"
"10012070-156-シロコ" = "ん、良い判断。"
"10012070-157-ノノミ" = "うんうん！アヤネちゃんが朝早くから修理してくれてたおかげで、もうほとんど終わってますし。"
"10012070-158-ノノミ" = "これなら追いつくことも簡単です！"
"10012070-159-ノノミ" = "ちょうど格納庫には使える武器も多かったですし……。"
"10012070-163-ノノミ" = "修理ついでに……ちょっとだけ、手を加えてみましょうか？"
