[translation]
"10012065-1" = "第6話;真夏の夜の夢"
"10012065-5-アヤネ" = "よいしょ……っと。"
"10012065-6-アヤネ" = "ふう、これで全部運び終わりました。"
"10012065-7-セリカ" = "こっちも大体終わったわ。先生の方は？"
"10012065-8" = "[s1] \"こっちも全部終わったよ。\"\n[s2] \"イタタ、腰が……。\""
"10012065-9-セリカ" = "そこに置いといてくれたら、後は私がやるから。"
"10012065-10-セリカ" = "全然痛がってないじゃない……。"
"10012065-11-アヤネ" = "急にバーベキューパーティだなんて……"
"10012065-12-アヤネ" = "まだ修理も終わってないのに、こんなことしている場合でしょうか……？"
"10012065-14-ホシノ" = "大丈夫だよ、アヤネちゃん。"
"10012065-15-ホシノ" = "私たちもちょっとは休まないとね。ずっと掃除ばっかしてたらバカンスの意味がないじゃん？"
"10012065-16-ノノミ" = "せっかく海に来たんですから、記念撮影もしましょう☆遊ぶ時はちゃんと遊ばないとですよ～！"
"10012065-18-セリカ" = "……先輩たち、準備するのもバカンスのうちとかなんとか言ってなかったっけ。"
"10012065-20-ノノミ" = "あははは……。"
"10012065-21-ホシノ" = "もう終わった話は忘れようよ～"
"10012065-22-ホシノ" = "あと残ってるのって、ヘリの修理だけじゃん？その辺は明日やればいいしさ～"
"10012065-23-ノノミ" = "準備はこれで終わりです！"
"10012065-24-ノノミ" = "今からはバカンスの時間ですからね～☆"
"10012065-29-アヤネ" = "ヘリ……。"
"10012065-30-ノノミ" = "心配することないですよ、アヤネちゃん。"
"10012065-31-ノノミ" = "倉庫に部品もいっぱいありましたし、明日みんなでやれば大丈夫です。"
"10012065-32-シロコ" = "うん。修理に最低でも一日はかかるし、一気にやるなら今日じゃなくて明日からやった方がいい。"
"10012065-33-シロコ" = "それに、暗いところでの整備は危ないからね。明日頑張るために、今日はゆっくり羽を伸ばそう。"
"10012065-34-ノノミ" = "うんうん！これは全部必要な休息なんですよ！"
"10012065-35-アヤネ" = "ノノミ先輩、シロコ先輩……。"
"10012065-37-セリカ" = "……そういえばあの変なヤツら、あれからずっと見ないわね？"
"10012065-38-セリカ" = "警備システムのおかげなのかしら？"
"10012065-39-アヤネ" = "もしかしたら島の外に追い出されたのかも……"
"10012065-40-アヤネ" = "あの時の警備ロボットだけでも、かなりの数いましたし。"
"10012065-42-ホシノ" = "向こうも何か移動手段あるだろうし、それに乗って帰ったんじゃないかね～"
"10012065-43-ノノミ" = "わざとではなかったんですが、酷いことをしちゃったかもですね……"
"10012065-44-セリカ" = "最初に攻撃してきたのはあっちなんだし、気にすることないんじゃない？"
"10012065-45-セリカ" = "私たちは自分たちのリゾートを守っただけだし……"
"10012065-46-シロコ" = "……ん。先生も守った。"
"10012065-47-セリカ" = "そうそう！先生も守っ……！"
"10012065-48-セリカ" = "たのは、今は関係ないでしょ！？"
"10012065-49-セリカ" = "ああもう！荷物運んだならシート敷いて！私、準備してくるから！"
"10012065-53-アヤネ" = "あはは……じゃあ、私もセリカちゃんを手伝いに行ってきますね。"
"10012065-57-ホシノ" = "……うへ、青春だねぇ～"
"10012065-58" = "[s] \"じゃあ私たちも始めよっか。\""
"10012065-63-ホシノ" = "……うん、そうしよっか。"
"10012065-138" = "（楽しく時間を過ごしていたら、いつの間にか夜になっていた）"
"10012065-139" = "（疲れて眠っている対策委員会の子たちを置いて、夜の空気に当たりながら砂浜を散歩した）"
"10012065-140" = "（……。）"
"10012065-141-？？？" = "ここにいらっしゃったんですね、先生。"
"10012065-142" = "[s] \"……？\""
"10012065-143-ノノミ" = "……ジャーン！ノノミの登場、ですよ☆"
"10012065-144-ノノミ" = "ちょっとお姿が見えないと思って……何をされてたんですか？"
"10012065-145" = "[s3] \"風にあたりに来たんだ。\"\n[s4] \"ここが一番涼しいからね。\""
"10012065-146-ノノミ" = "そうなんですね～じゃあ、私も……。"
"10012065-147-ノノミ" = "そうなんですね～じゃあ、私も……。"
"10012065-153" = "[ns5] \"……ノノミ？\"\n[ns6] \"隣に！？\""
"10012065-154-ノノミ" = "ふふっ、私も涼みに来たんです。"
"10012065-155-ノノミ" = "ふふっ、私も涼みに来たんです。"
"10012065-156-ノノミ" = "ちょっと暑くて寝苦しかったですし……"
"10012065-157-ノノミ" = "他のみんなは、くたくたになってぐっすり寝てますよ。"
"10012065-158-ノノミ" = "シロコちゃんも、セリカちゃんも、アヤネちゃんも……。"
"10012065-159-ノノミ" = "そして……。"
"10012065-160" = "[s7] \"……ノノミ？\"\n[s8] \"どうしたの？\""
"10012065-161-ノノミ" = "いえ、大したことじゃないんです。"
"10012065-162-ノノミ" = "いえ、大したことじゃないんです。"
"10012065-166-ノノミ" = "ただ……こんな風に色んなことを忘れて遊べたのは初めてだなって。"
"10012065-167-ノノミ" = "私たちはいつも、学校のことで頭がいっぱいだったから……。"
"10012065-168-ノノミ" = "たまには、こうやって何も考えないではしゃぐのも、いいものですね。"
"10012065-169-ホシノ" = "……帰ったらまた学校の問題と向き合わなきゃいけないけど、こういう休暇も大事だよね～。"
"10012065-170-ノノミ" = "……あれ、ホシノ先輩？"
"10012065-178-ホシノ" = "どんな面白い話をしているのかな？二人っきりで。"
"10012065-179-ノノミ" = "あれ、さっきまで先輩、クジラを枕にしてお休みになってませんでしたか？"
"10012065-180-ホシノ" = "そそ。んで、今起きたの～。"
"10012065-181-ホシノ" = "うへ、私も暑くて目が覚めた……ってとこかな？"
"10012065-182-ノノミ" = "あはは……先輩でも寝苦しい時があるんですね……。"
"10012065-187-ホシノ" = "いい雰囲気だね～。おじさん、こういうの嫌いじゃないよ。久しぶりにのんびりできたよ。"
"10012065-188-ノノミ" = "先輩はいつものんびりしてますよ～？墜落するヘリの中でも眠れるくらい☆"
"10012065-189-ホシノ" = "ノノミちゃん、いつもよりちょっとツッコミが強くない～？"
"10012065-190-ホシノ" = "なになに～？他の子がいないから、ツッコミが強くなってるのか、それとも夏の海だからなのか。おじさん、ビックリしちゃった。"
"10012065-191-ノノミ" = "うーん……。"
"10012065-192-ノノミ" = "とりあえずは夏の海のせいってことで？"
"10012065-193-ホシノ" = "うーむ、悲しいねぇ。うちの繊細で可愛い後輩たちが、どうしてこんな風に育っちゃったのか……"
"10012065-195-ノノミ" = "うふふ、「繊細で可愛い」はお互い様じゃないですか？"
"10012065-196-ノノミ" = "バーベキューパーティの時も……いつもと違って、先輩は色々手伝ってくれましたしね。"
"10012065-201-ホシノ" = "な、夏の海って怖いね！？ノノミちゃ～ん！？"
"10012065-202-ホシノ" = "……ま、まぁおじさんがテキパキ手伝ってるのは珍しいかもだけどさ！雰囲気の影響なのかな！？"
"10012065-203-ホシノ" = "ああ、もしかしたらバーベキューセットの影響もあるかも……"
"10012065-207-ホシノ" = "元々はアビドス砂祭りで使うために買ったものだったからねぇ。"
"10012065-209-ノノミ" = "……先輩。"
"10012065-210-ホシノ" = "……ほら。"
"10012065-211-ホシノ" = "ノノミちゃんにそんな顔させちゃうから、こういう話はしないんだよ。"
"10012065-212-ホシノ" = "シロコちゃんも、アヤネちゃんも、セリカちゃんも同じ。"
"10012065-213-ホシノ" = "うちの可愛い後輩たちに余計な悩みを増やしたくないんだ。今でも十分頑張ってくれてるからね。"
"10012065-214-ノノミ" = "……でも、今は言いましたよね。"
"10012065-215-ホシノ" = "そりゃあ、今だから……真夏の夜の海だからさ。"
"10012065-216-ホシノ" = "だからノノミちゃんも……その顔はここだけにして、忘れようね。約束だぞ？"
"10012065-220-ノノミ" = "……はい、分かりました。約束です☆"
"10012065-221-ノノミ" = "……うん。"
"10012065-222-ノノミ" = "せっかくですし、もう少し続けましょう？"
"10012065-223-ノノミ" = "「ここだけ」のお話ですから。"
"10012065-224-ホシノ" = "うへ……続けるの？おじさん、そろそろ限界だよ～もうやめちゃダメ？"
"10012065-225-ノノミ" = "ダメです。次にいつこういう機会があるか分からないでしょう？"
"10012065-226-ノノミ" = "ね？先生。"
"10012065-227" = "[s9] \"そうだね。\"\n[s10] \"まあ、真夏の夜の海だからね。\""
"10012065-228-ホシノ" = "うへ～先生まで！！おじさんの味方はいないの～？"
"10012065-229-ホシノ" = "うへ～先生まで！！おじさんの味方はいないの～？"
"10012065-235" = "（その後、二人と夜中まで会話をしてそのまま眠った）"
