[translation]
"10012055-5-セリカ" = "し、死ぬかと思った、マジで……。"
"10012055-6-ノノミ" = "ギリギリでしたね☆"
"10012055-7-シロコ" = "アヤネが早く入力してくれたからなんとかなったけど、ちょっとでも遅れてたらもう止められなくなってたかも。"
"10012055-9-アヤネ" = "あはは……。"
"10012055-11-ホシノ" = "おじさんもこれだけの数を相手するの、久々だったよ～"
"10012055-12-ホシノ" = "……ありがとう、先生。おかげで助かったよ。"
"10012055-13" = "[s1] \"気にしないで。\"\n[s2] \"みんなが頑張ってくれたおかげだよ。\""
"10012055-16-アヤネ" = "警備システムの身元登録も無事終わりましたし、"
"10012055-17-アヤネ" = "ここからは安全に過ごせ……。"
"10012055-18-アヤネ" = "あれ？……何か足元に。"
"10012055-19-ジャブジャブヘルメット団たち" = "う、うぐっ……な、なんだ、一体……。"
"10012055-20-ジャブジャブヘルメット団たち" = "急にロボットが攻撃を……ぎゃあっ。"
"10012055-21-ジャブジャブヘルメット団たち" = "もう私、お家に帰る……もうこれ以上はむ～り～……。"
"10012055-25-アヤネ" = "……こんなところにもヘルメット団の人が。"
"10012055-32-ホシノ" = "……うへ。"
"10012055-34-ホシノ" = "……リゾート防御システムはすごいねぇ。"
