[translation]
"11115-2-アヤネ" = "敵、後退しています！"
"11115-3-アヤネ" = "だけどこのままでは……。"
"11115-4-シロコ" = "仲間を呼ぶつもり？いくらでも相手してあげる。"
"11115-5-ヒフミ" = "ま、待ってください！それ以上戦っちゃダメです！"
"11115-6-シロコ" = "ん？どうして？"
"11115-7-ヒフミ" = "だ、だって……ブラックマーケットで騒ぎを起こしたら、ここを管理している治安機関に見つかってしまうかもしれません！"
"11115-8-ヒフミ" = "あうう……そうなったら本当に大ごとです……まずはこの場から離れ……。"
"11115-9-ホシノ" = "ふむ……わかった。ここのことはヒフミちゃんのほうが詳しいだろうから、従おう。"
"11115-10-セリカ" = "ちぇっ、運のいいやつらめ！"
"11115-11-ヒフミ" = "こっちです！"
"11115-15" = "次回;ブラックマーケットへ（２）"
