[translation]
"11130-2" = "第13話;出動！覆面水着団（１）"
"11130-3" = "ブラックマーケット・中心街"
"11130-4-セリカ" = "はあ……しんど。"
"11130-5-ノノミ" = "もう数時間は歩きましたよね……。"
"11130-6-ホシノ" = "これはさすがに、おじさんも参ったなー。#n腰も膝も悲鳴を上げてるよー。"
"11130-7-ヒフミ" = "えっ……ホシノさんはおいくつなのですか……？"
"11130-8-セリカ" = "ほぼ同年代っ！"
"11130-9-ノノミ" = "あら！あそこにたい焼き屋さんが！"
"11130-10-ホシノ" = "あれ、ホントだー。こんなところに屋台があるなんてね。"
"11130-11-ノノミ" = "あそこでちょっとひと休みしましょうか？たい焼き、私がご馳走します！"
"11130-12-セリカ" = "えっ！？ノノミ先輩、またカード使うの！？"
"11130-13-ホシノ" = "先生の「大人のカード」もあるよ～。"
"11130-15-ノノミ" = "ううん、私が食べたいからいいんですよ☆みんなで食べましょう、ねっ？"
"11130-18-たい焼き屋店主" = "まいどー！"
"11130-19-セリカ" = "（もぐもぐ）"
"11130-20-セリカ" = "おいしい！"
"11130-21-ホシノ" = "いやぁ、ちょうど甘いモノが欲しかったところだったんだー。"
"11130-22-ヒフミ" = "（ガサッ）あはは……いただきます。"
"11130-23-シロコ" = "（ぱくっ）"
"11130-24-シロコ" = "ほら……。"
"11130-26-シロコ" = "先生も。"
"11130-27" = "[s] \"いただきます。\""
"11130-29-ノノミ" = "アヤネちゃんには、戻ったらちゃんとご馳走しますね。私たちだけでごめんなさい……。"
"11130-30-アヤネ" = "あはは。大丈夫ですよ、ノノミ先輩。私はここでお菓子とかつまんでますし……。"
"11130-31-ホシノ" = "しばしブレイクタイムだねー。"
"11130-33-ヒフミ" = "ここまで情報がないなんてありえません……妙ですね。"
"11130-34-ヒフミ" = "お探しの戦車の情報……。#n絶対どこかにあるはずなのに、#n探しても探しても出てきませんね……。"
"11130-35-ヒフミ" = "販売ルート、保管記録……#nすべて何者かが意図的に隠しているような、そんな気がします。"
"11130-36-ヒフミ" = "いくらここを牛耳っている企業でも、#nここまで徹底してブラックマーケットを統制することは不可能なはず……。"
"11130-37-シロコ" = "そんなに異常なことなの？"
"11130-38-ヒフミ" = "異常というよりかは……普通ここまでやりますか？という感じですね……。"
"11130-39-ヒフミ" = "ここに集まっている企業は、ある意味開き直って悪さをしていますから、逆に変に隠したりしないんです。"
"11130-40-ヒフミ" = "例えば、あそこのビル。あれがブラックマーケットに名を馳せる闇銀行です。"
"11130-41-セリカ" = "闇銀行？"
"11130-42-ヒフミ" = "ブラックマーケットで最も大きな銀行のひとつです。聞いた話だと、キヴォトスで行われる犯罪の15％の盗品があそこに流されているそうです……。"
"11130-43-ヒフミ" = "横領、強盗、誘拐などなど、様々な犯罪によって獲得した財貨が、違法な武器や兵器に変えられてまた他の犯罪に使われる……。"
"11130-44-ヒフミ" = "そんな悪循環が続いているのです。"
"11130-45-ノノミ" = "……そんなの、銀行が犯罪を煽っているようなものじゃないですか。"
"11130-46-ヒフミ" = "その通りです。まさに銀行も犯罪組織なのです……。"
"11130-47-シロコ" = "……。"
"11130-48-セリカ" = "ひどい！連邦生徒会は一体何やってんの？"
"11130-49-ホシノ" = "理由はいろいろあるんだろうけどねー、どこもそれなりの事情があるだろうからさ。"
"11130-50-シロコ" = "現実は、思った以上に汚れているんだね。#n私たちはアビドスばかりに気を取られすぎて、外のことをあまりにも知らな過ぎたかも……。"
"11130-53-アヤネ" = "お取込み中失礼します！そちらに武装した集団が接近中！"
"11130-54-シロコ" = "！！"
"11130-55-アヤネ" = "気付かれた様子はありませんが……#nまずは身を潜めた方が良いと思います……。"
"11130-56-ヒフミ" = "う、うわあっ！？あれは、マーケットガードです！"
"11130-57-ノノミ" = "マーケットガード？"
"11130-58-ヒフミ" = "先ほどお話しした、ここの治安機関でも最上位の組織です！"
"11130-59-ヒフミ" = "急ぎましょう！"
"11130-62-ヒフミ" = "……パトロール？護衛中のようですが……。"
"11130-63" = "（ブロロロ……）"
"11130-64-シロコ" = "トラックを護送してる……現金輸送車だね。"
"11130-65-ノノミ" = "あれ……あっちは……。"
"11130-66" = "（ブロロロ……）"
"11130-67-ノノミ" = "闇銀行に入りましたね？"
"11130-70" = "（キキーッ）"
"11130-71-銀行員" = "今月の集金です。"
"11130-72-闇銀行の行員" = "ご苦労様、早かったな。では、こちらの集金確認書類にサインを。"
"11130-74-銀行員" = "はい。（サラサラ）"
"11130-75-闇銀行の行員" = "いいでしょう。"
"11130-76-銀行員" = "では、失礼します。"
"11130-79-闇銀行の行員" = "さあ、開けてくれ。今月分の現金だ。"
"11130-80" = "（ブロロロ……）"
"11130-82-ノノミ" = "見てください……あの人……。"
"11130-83-セリカ" = "あれ……？な、何で！？#nあいつは毎月うちに来て利息を受け取っているあの銀行員……？"
"11130-84-ホシノ" = "あれ、ホントだ。"
"11130-85-ヒフミ" = "えっ！？ええっ……？"
"11130-86-シロコ" = "……どういうこと？"
"11130-87-アヤネ" = "ほ、本当ですね！車もカイザーローンのものです！"
"11130-88-アヤネ" = "今日の午前中に、利息を支払った時のあの車と同じようですが……#nなぜそれがブラックマーケットに……！？"
"11130-89-ヒフミ" = "か、カイザーローンですか！？"
"11130-90-ホシノ" = "ヒフミちゃん、知ってるの？"
"11130-91-ヒフミ" = "カイザーローンと言えば……かの有名な#nカイザーコーポレーションが運営する高利金融業者です……。"
"11130-92-シロコ" = "有名な……？マズいところなの？"
"11130-93-ヒフミ" = "あ、いえ……カイザーグループ自体は犯罪を起こしてはいません……。#nしかし合法と違法の間のグレーゾーンで上手く振舞っている多角化企業で……。"
"11130-94-ヒフミ" = "カイザーは私たちトリニティの区域にもかなり進出しているのですが、生徒たちへの悪影響を考慮し、「ティーパーティー」でも目を光らせています。"
"11130-95-ホシノ" = "「ティーパーティー」……あのトリニティの生徒会が、ね。"
"11130-96-ヒフミ" = "ところでみなさんの借金とはもしかして……アビドスはカイザーローンから融資を……？"
"11130-97-ノノミ" = "借りたのは私たちじゃないんですけどね……。"
"11130-98-ホシノ" = "話すと長くなるんだよねー。アヤネちゃん、さっき入ってった現金輸送車の走行ルート、調べられる？"
"11130-99-アヤネ" = "少々お待ちください。"
"11130-101-アヤネ" = "……ダメですね。すべてのデータをオフラインで管理しているようです。#n全然ヒットしません。"
"11130-102-ホシノ" = "だろうねー。"
"11130-103-ノノミ" = "そういえば、いつも返済は現金だけでしたよね。それはつまり……。"
"11130-104-シロコ" = "私たちが支払った現金が、ブラックマーケットの闇銀行に流れていた……？"
"11130-105-セリカ" = "じゃあ何？私たちはブラックマーケットに、犯罪資金を提供してたってこと！？"
"11130-106-アヤネ" = "……。"
"11130-107-シロコ" = "……。"
"11130-108-ホシノ" = "……。"
"11130-109-ノノミ" = "……。"
"11130-110-アヤネ" = "ま、まだそうハッキリとは……証拠も足りませんし。#nあの輸送車の動線を把握するまでは……。"
"11130-111-ヒフミ" = "……あ！さっきサインしてた集金確認の書類……。#nそれを見れば証拠になりませんか？"
"11130-112-シロコ" = "さすが。"
"11130-113-ホシノ" = "おお、そりゃナイスアイデアだねー、ヒフミちゃん。"
"11130-114-ヒフミ" = "あはは……でも考えてみたら、書類はもう銀行の中ですし……無理ですね。"
"11130-115-ヒフミ" = "ブラックマーケットでも最も強固なセキュリティを誇る銀行の中となると……。#nそれにあれだけの数のマーケットガードが目を光らせてますし……。"
"11130-116-ヒフミ" = "それ以外に輸送車の集金ルートを確認する方法は……。#nええっと……うーん……。"
"11130-117-シロコ" = "うん、"
"11130-118-シロコ" = "他に方法はないよ。"
"11130-119-ヒフミ" = "えっ？"
"11130-120-シロコ" = "ホシノ先輩、ここは例の方法しか。"
"11130-121-ホシノ" = "なるほど、あれかー。あれなのかあー。"
"11130-122-ヒフミ" = "……ええっ？"
"11130-123-ノノミ" = "あ……！！そうですね、あの方法なら！"
"11130-124-セリカ" = "何？どういうこと？……まさか、あれ？まさか、私が思ってるあの方法じゃないよね？"
"11130-125-シロコ" = "……。"
"11130-126-セリカ" = "う、嘘っ！？本気で！？"
"11130-128-ヒフミ" = "……あ、あのう。全然話が見えないんですけど……「あの方法」って何ですか？"
"11130-129-シロコ" = "残された方法はたったひとつ。"
"11130-130-シロコ" = "（スッ）"
"11130-132-シロコ" = "銀行を襲う。"
"11130-133-ヒフミ" = "はいっ！？"
"11130-134-ホシノ" = "だよねー、そういう展開になるよねー。"
"11130-135-ヒフミ" = "はいいいっ！！？？"
"11130-136-ノノミ" = "わあ☆そしたら悪い銀行をやっつけるとしましょう！"
"11130-137-ヒフミ" = "えええっ！！？？ちょ、ちょっと待ってください！"
"11130-138-セリカ" = "はあ……マジで？マジなんだよね……？"
"11130-139-セリカ" = "ふぅ、それなら……。"
"11130-140-セリカ" = "とことんまでやるしかないか！！"
"11130-141-ヒフミ" = "あ、うあ……？あわわ……？"
"11130-143-アヤネ" = "……。"
"11130-144-アヤネ" = "……はぁ、了解です。こうなったら止めても聞く耳持たないでしょうし……#nどうにかなる、はず……。"
"11130-146-シロコ" = "ごめん、ヒフミ。あなたの分の覆面は準備が無い。"
"11130-147-ホシノ" = "うへー、ってことは、#nバレたら全部トリニティのせいだって言うしかないねー。"
"11130-148-ヒフミ" = "ええっ！？そ、そんな……覆面……何で……えっと、だから……あ、あう……。"
"11130-149-ノノミ" = "それは可哀そうすぎます。"
"11130-150-ノノミ" = "ヒフミちゃん、とりあえずこれでもどうぞ☆"
"11130-151-ホシノ" = "たい焼きの紙袋？おお！それなら大丈夫そうー！"
"11130-152-ヒフミ" = "え？ちょ、ちょっと待ってください、みなさん……。"
"11130-153-ヒフミ" = "あ、あうう……。"
"11130-155" = "（ガサガサ）"
"11130-156-ヒフミ" = "あううっ……。"
"11130-157-ヒフミ" = "……。"
"11130-158-シロコ" = "ん、完璧。"
"11130-159-ノノミ" = "番号も振っておきました。ヒフミちゃんは5番です☆"
"11130-160-ホシノ" = "見た目はラスボス級じゃない？悪の根源だねー、親分だねー。"
"11130-161-ヒフミ" = "わ、私もご一緒するんですか？闇銀行の襲撃に……？"
"11130-162-ホシノ" = "さっき約束したじゃーん？ヒフミちゃん、#n今日は私たちと一緒に行動するって。"
"11130-163-ヒフミ" = "う、うああ……わ、私、もう生徒会の人たちに合わせる顔がありません……。"
"11130-164-セリカ" = "問題ないよ！私らは悪くないし！悪いのはあっち！だから襲うの！"
"11130-165-シロコ" = "それじゃあ先生。例のセリフを。"
"11130-166" = "[s] \"銀行を襲うよ！ \""
"11130-168-ノノミ" = "はいっ！出発です☆"
"11130-169-ヒフミ" = "あ、あうう……。"
"11130-170-アヤネ" = "ふぅ……では、覆面水着団。"
"11130-172" = "（スッ）"
"11130-173-アヤネ" = "出撃しましょうか。"
"11130-175" = "次回;出動！覆面水着団（２）"
