[translation]
"11190-2" = "第19話;あんたたち、許さない！"
"11190-3" = "破壊されたアビドス市街地"
"11190-4" = "（モクモク……）"
"11190-6-ムツキ" = "ゴホッ、ゴホッ……うわあ、建物がなくなっちゃったよ？"
"11190-7-カヨコ" = "ケホッ……これは一体……。"
"11190-8-ハルカ" = "（グルグル）"
"11190-10-アル" = "ゴホン、ゴホン……う、うああ……。"
"11190-13-アル" = "（な、何これ！？何が起きたの！？）"
"11190-14-ムツキ" = "……アルちゃん……マジで？マジでぶっ潰しちゃったの？"
"11190-15-アル" = "え……え？"
"11190-16-ムツキ" = "情にほだされるからって、あんなに優しくしてくれたラーメン屋さんを吹っ飛ばしたの？#nやるじゃーん！？ "
"11190-17-ムツキ" = "これぞまさに、血も涙もない大悪党！#nそんじょそこらのザコには到底できない鬼畜の所業！悪人中の悪人じゃん！"
"11190-18-アル" = "え、う？……あ？"
"11190-19-ムツキ" = "これがハードボイルドなアウトローってやつだね！！すごいよ、アルちゃん！見直したよ！"
"11190-20-アル" = "へ……あ……？……あ、あはははは！とっ、当然でしょう！#n冷酷無比！情け無用！金さえもらえればなんでもオッケー！それがうちのモットーよ！！"
"11190-21-？？？" = "そういうことだったのね！！"
"11190-25-セリカ" = "あんたたち……！！よくもこんなひどいことを！！"
"11190-26-シロコ" = "……。"
"11190-27-ノノミ" = "……。"
"11190-28-アヤネ" = "大将の無事を確認できました！幸い軽傷だったので、近くのシェルターに案内済みです！"
"11190-29-セリカ" = "……ってことは、大暴れしてもいいってことね？"
"11190-30-セリカ" = "あんたたち、許さない。ぜーったいに許さないから……！！"
"11190-32-アル" = "！？"
"11190-33-ムツキ" = "おっと、噂をすれば。"
"11190-34-カヨコ" = "……ちょっとタイミングはズレちゃったけど、どうせいつかは白黒つけないといけない相手だし。"
"11190-35-カヨコ" = "確保しておいた傭兵をこっちに呼ぶ。"
"11190-37-アル" = "……。"
"11190-38-アル" = "……そっ、そうよ！！これでわかったでしょう、アビドス！私がどんなに悪党かを！"
"11190-39-アル" = "さあ、いざ勝負！！かかってきなさいよ！"
"11190-40-ハルカ" = "私が一人残らず始末します、アル様。"
"11190-43-セリカ" = "覚悟はいい！？"
"11190-44-シロコ" = "（スチャッ）"
"11190-45-ノノミ" = "お仕置きですよー！"
"11190-49-アル" = "それはこっちのセリフよ！！真のアウトローがどういうものか、見せてあげるわ！！"
