[translation]
"11205-2-イオリ" = "な、なに？！私たちが負けただと？！"
"11205-4-シロコ" = "……。"
"11205-5-ノノミ" = "……。"
"11205-6-セリカ" = "……。"
"11205-8-チナツ" = "……。"
"11205-9" = "[s] \"久しぶり、チナツ。 \""
"11205-10-チナツ" = "先生……こんな形でお目にかかるとは……。"
"11205-11-チナツ" = "先生がそこにいらっしゃることを知った瞬間、勝ち目はないと判断して後退するべきでした……私たちの失策です。"
"11205-12-アヤネ" = "アビドス対策委員会の[ruby=おくそら]奥空[/ruby]アヤネです。所属をお願いします。"
"11205-13-イオリ" = "それは……。"
"11205-14-アコ" = "それは私から答えさせていただきます。"
"11205-15-アヤネ" = "通信……？"
"11205-16-イオリ" = "アコちゃん……？"
"11205-17-チナツ" = "アコ行政官……？"
"11205-19-アコ" = "こんにちは、アビドスの皆様。私はゲヘナ学園所属の行政官、アコと申します。"
"11205-20-アコ" = "今の状況について少し説明させていただきたいと思いますが、よろしいでしょうか？"
"11205-21-イオリ" = "アコちゃん……その……。"
"11205-22-アコ" = "イオリ。反省文のテンプレートは私の机の、左の引き出しにあります。ご存じですよね？"
"11205-23-イオリ" = "……。"
"11205-28-ハルカ" = "（ピクリ）"
"11205-29-ハルカ" = "（スッ――）"
"11205-30-ハルカ" = "……。"
"11205-31-ハルカ" = "ああ……。"
"11205-32-ハルカ" = "ああ、みんな集まってます。"
"11205-33-ハルカ" = "……チャンスですね。"
"11205-38-ハルカ" = "許さない……許さない……許さない……許さない……。"
"11205-39-ハルカ" = "許さない　許さない　許さない　許さない　許さない　許さない　許さない……#n許さない 許さない　許さない　許さない　許さない　許さない　許さない　許さない……"
