[translation]
"42050-1" = "第5話;先輩の影"
"42050-3-モエ" = "……ねえ、これってどういうこと？"
"42050-4-モエ" = "近くの[ruby=Node]ノード[/ruby]で防犯カメラをチェックしてたら、#n後ろから紙袋を被せられて……。"
"42050-6-ミユ" = "わ、私も……隠れてたら後ろから襲われて……。"
"42050-7-ミユ" = "目隠しされたままよく分からないところに投げ込まれて……コロコロ転がされて……。"
"42050-8-ミユ" = "うぅ……まだ気持ち悪い……。"
"42050-9-モエ" = "で、どうしてサキまで仲良く一緒に縛られてるわけ？#nミヤコと一緒に突入したんじゃなかったの？"
"42050-10-サキ" = "それが……私にもよく分からないんだ。"
"42050-11-サキ" = "中央通路に突入する時、頭に大きな衝撃を受けて……。"
"42050-12-サキ" = "気づいたら、こうなってた。"
"42050-13-モエ" = "つまり……私たち、拉致されたってこと？"
"42050-14-モエ" = "詳しい状況はさっぱりだけど……。"
"42050-15-サキ" = "ちっ……油断しすぎた。"
"42050-16-ミユ" = "ねえ……私たちが奇襲を掛けた相手って、違法取引をする武器商人だったよね……？"
"42050-17-ミユ" = "なら、こうして私たちを生かしてるのは、どこかに売り飛ばすためなんじゃ……？"
"42050-18-ミユ" = "研究施設に送られて新兵器の実験に使われたり……#nひらひらの服を着せられてあんなことやこんなことをされちゃうとか……。"
"42050-20-モエ" = "……最後のは違うんじゃない？"
"42050-21-サキ" = "心配するな。まだミヤコが残っている。"
"42050-22-サキ" = "きっとミヤコなら助けに来てくれるはず――"
"42050-26-ミヤコ" = "みんな、無事でしたか！？"
"42050-27-サキ" = "ミヤコ……！"
"42050-28-ミユ" = "ミヤコちゃん、助けに来てくれたんだね……！"
"42050-29-ミヤコ" = "あ……えっと……それがですね……。"
"42050-31-ミヤコ" = "……私も、捕まってしまいまして。"
"42050-32-ユキノ" = "これで4人目……全員失格。"
"42050-37-ユキノ" = "SRTのCQB試験だったら、赤点だったところだな。"
"42050-39-モエ" = "そ、その装備、まさか……。"
"42050-40-サキ" = "FOX小隊の先輩方……？#nど、どうしてここに……。"
"42050-41-オトギ" = "まあ、カンタンに言うと――後輩のために用意したドッキリってとこかな。"
"42050-42-クルミ" = "最近キヴォトスのあちこちで活躍してるって聞いたから、#n少しは成長してると思ったのに……思い違いだったみたいね。"
"42050-43-クルミ" = "知らない場所に突入する時にバックアップなしで突っ込むなんて……#n自分から「狙ってください」って言ってるようなものよ。ピクニックにでも来たつもり？"
"42050-45-ニコ" = "まあまあクルミちゃん。もう終わったんだし、その辺で。"
"42050-46-ニコ" = "彼女たちも、こういう状況は想定していなかったんだと思うよ。#nそれに、普通の傭兵や武器商人を相手にするなら、あの戦術で十分だもの。"
"42050-47-ユキノ" = "……甘い。敵が自身の想定通りに現れるとは限らないんだぞ。"
"42050-48-ミヤコ" = "……すみません。"
"42050-50-ニコ" = "と、とりあえずおやつにしよっか！#n私、おいなりさんいっぱい作ってきたんだ！"
"42050-51-ニコ" = "食べながらお話しよう、ね？"
"42050-52-ニコ" = "お互いに……積もる話がたくさんあると思うから。"
"42050-53-ミヤコ" = "……はい。"
"42050-55-クルミ" = "もう！細かいことばっか気にしすぎ。#nそんなんだから反応が遅くなるのよ。"
"42050-56-クルミ" = "さっきみたいに銃を取り回しづらい場所で、敵が違う方向から現れたらどうするの？"
"42050-57-サキ" = "……副武装に切り替えて撃つ、とか？"
"42050-58-クルミ" = "教範ではそうね。#nでも、実戦では「ストックでそのまま叩きつける」のが正解よ。"
"42050-59-クルミ" = "武装を変えるより、ストックを使った方が素早く敵に攻撃できるの。#nまぁ、敵の防護服や距離によって正解は変わるけど……"
"42050-61-サキ" = "ううっ……教範と違う実戦状況は苦手だ……。"
"42050-62-クルミ" = "そう簡単にベテランにはなれないわ。#nもっと頑張ることね。"
"42050-66-オトギ" = "うーん、この食感は……イクラかな？#n意外とおいなりさんに合うんだねぇ。"
"42050-67-クルミ" = "ちょっと、取らないでよ！後で食べようと思って残しておいたのに！"
"42050-68-オトギ" = "あはは、ごめんってば。#n後輩の前でそんなにカリカリしないでよ。"
"42050-69-オトギ" = "ほら、卵入りあげるから。"
"42050-70-クルミ" = "卵はいらない！イクラがいいの！"
"42050-72-ニコ" = "こらこら、ケンカしないの。#nおいなりさんはまだいっぱいあるんだから。"
"42050-76-ニコ" = "はい、ミユちゃんも遠慮せず食べてね。"
"42050-77-ミユ" = "わ、わわ……私なんかがこんな立派なおいなりさんを頂いていいんでしょうか……？"
"42050-78-ニコ" = "もちろん。みんなで食べようと思って作ってきたんだから。"
"42050-79-ミユ" = "あ、ありがとうございます……。"
"42050-83-ミユ" = "……お、おいしいっ！"
"42050-85-モエ" = "はあ～、ニコ先輩のおいなりさん、いつぶりだろう？"
"42050-86-モエ" = "これだけ色んな薬味がたっぷり入ったおいなりさん、どこにも売ってないよ。"
"42050-87-ニコ" = "ふふっ、ありがとう。朝早くから準備してた甲斐があるな。"
"42050-88-ニコ" = "特に、油揚げ用の煮汁は私のオリジナルレシピだからね。#nあんまり他にはないと思うよ。"
"42050-89-サキ" = "（……そういえば最近、これと似たおいなりさんを食べたような……#n　気のせいか……？）"
"42050-94-ミユ" = "あの……お聞きしたいんですが、#nどうやって私の場所を見つけたんですか？"
"42050-95-ミユ" = "自分で言うのもなんですが……結構うまく隠れていたと思うのですが……。"
"42050-97-オトギ" = "あ、もしかして君がミユ？#n偽装訓練で満点取ったって噂の！"
"42050-98-ミユ" = "ひ、ひぃっ……！？"
"42050-99-オトギ" = "ほんと、完璧な偽装だったよ！#nニコが座標を教えてくれるまで全然わかんなかったもん！"
"42050-101-ミユ" = "あ、ありがとうございます……ち、近いです……。"
"42050-102-オトギ" = "特殊なカモフラージュ装備でも使ってるの？#nスコープの倍率も気になるなぁ！"
"42050-103-ミユ" = "う、ううう…………。"
"42050-106-サキ" = "と、とにかく、武器を買ったのがFOX小隊の先輩だと分かってよかった。#nSRTの武器が悪いことに使われる事はなさそうだからな。"
"42050-107-モエ" = "だねぇ。それに先輩たちが払ったお金なら、出所を心配する必要もないし。"
"42050-111-ミヤコ" = "………。"
"42050-112-ミヤコ" = "あの、先輩方。一ついいですか？"
"42050-113-クルミ" = "ええ、もちろんよ。何でも聞いて？"
"42050-114-ミヤコ" = "……事件の時、先輩がシャーレから持ち出したのは何だったんですか？"
"42050-115-クルミ" = "ええっと……それは……"
"42050-116-ミヤコ" = "そして――SRTの閉鎖が決まった時、なぜ連邦生徒会の建物を襲ったのですか？"
"42050-117-ニコ" = "それは……。"
"42050-122-ユキノ" = "まだ君たちには教えられない。"
"42050-123-ミヤコ" = "……機密、ですか？"
"42050-124-ユキノ" = "違う。"
"42050-125-ユキノ" = "今はまだ、君たちが「我々」の味方ではないからだ。"
"42050-126-サキ" = "待ってくれ。#n私たちは同じSRT隊員じゃないのか……？"
"42050-127-ミユ" = "ど、どうしてそんな……。"
"42050-128-ユキノ" = "……一つ問おう。"
"42050-129-ユキノ" = "[ruby=・  ・]任務[/ruby]で、シャーレの先生と敵対しろと言われたらどうする？"
"42050-131-一同" = "………。"
"42050-135-ユキノ" = "そう、君たちは判断できない。"
"42050-137-ユキノ" = "武器は――自ら判断しないからこそ、価値があるのだから。"
"42050-139-ユキノ" = "困難をきわめる作戦の遂行、大変ご苦労であった。[ruby=つきゆき]月雪[/ruby]小隊長。"
"42050-140-ユキノ" = "――本日をもってRABBIT小隊は解体とする。#n各小隊員はこれより、FOX小隊の支隊として動くように。"
"42050-141-ミヤコ" = "解体……？RABBIT小隊を……？"
"42050-142-ユキノ" = "誤解をしないでほしい。"
"42050-143-ユキノ" = "我々としても、不利益を与えるつもりはない。#n月雪小隊長が持つ裁量権は尊重しよう。"
"42050-144-ユキノ" = "なに、突然の事故で後輩に背負わせた責任を、我々が再び背負うというだけの事だ。"
"42050-145-ユキノ" = "以後、困難な選択はすべて我々に任せるといい。"
"42050-146-ミヤコ" = "ですが……SRT特殊学園復活のためでしたら、私たちにも覚悟が――"
"42050-147-ユキノ" = "全員、長きに渡るキャンプで疲弊しているのでは？"
"42050-148-ミヤコ" = "………。"
"42050-149-ユキノ" = "これ以上、SRT特殊学園再建のために責任を負う必要はない。"
"42050-150-ユキノ" = "あとは我々に委ねて、各小隊員は武器としての本分を果たすように。"
"42050-151-ミヤコ" = "……私たち、RABBIT小隊は……。"
"42050-152-ユキノ" = "……さあ、月雪小隊長――決めるんだ。"
"42050-153-ユキノ" = "武器としての本分を、忘れたわけじゃないのだろう？"
"42050-154-ユキノ" = "躊躇いを抱いたまま、錆びたナイフで正義を振り翳す事ほど無様なことはない。"
"42050-155-ミヤコ" = "私、たちは……。"
"42050-157" = "[ns] \"……ちょっと待って！\""
"42050-158-オトギ" = "あれ、侵入者？"
"42050-159-クルミ" = "どうしてここが……！？"
"42050-163-ニコ" = "……[USERNAME]先生？"
"42050-164" = "[s1] \"こんにちは、FOX小隊のみんな。\"\n[s2] \"この前のいなり寿司、美味しかったよ。\""
"42050-165-サキ" = "……[USERNAME]先生？どうしてここに？"
"42050-166-ニコ" = "………。"
"42050-167-サキ" = "……[USERNAME]先生？どうしてここに？"
"42050-168-ミユ" = "ま、まさか私たちの後をつけて……？"
"42050-169" = "[s3] \"いつの間にかみんないなくなってたから……。\"\n[s4] \"街で話を聞きながら探してたんだ。\""
"42050-177-ユキノ" = "……お初にお目にかかります、[USERNAME]先生。"
"42050-178-ユキノ" = "お噂はかねがねお伺いしております。連邦生徒会長の不在でパニック状態だったキヴォトスをまとめてくださったそうですね。"
"42050-179-ユキノ" = "……SRT特殊学園を代表し、厚くお礼申し上げます。"
"42050-180" = "[s] \"どういたしまして。\""
"42050-181-ユキノ" = "ですが、月雪小隊長と話しているのはSRT特殊学園内のこと。"
"42050-182-ユキノ" = "故に、後のことは私たちにお任せ頂きたく存じます。"
"42050-183-ユキノ" = "先生は……生徒の意志を尊重する大人だとお伺いしておりますので。"
"42050-184" = "[s] \"それはもちろん。\""
"42050-186" = "[ns5] \"でも、急な話でみんなも戸惑っているみたいだから。\"\n[ns6] \"ミヤコにも、もう少し時間をくれないかな？\""
"42050-189-ユキノ" = "……かしこまりました。"
"42050-190-ユキノ" = "さすがはシャーレの先生。#nあらゆる生徒の信頼を得ている方らしい発言ですね。"
"42050-195-ユキノ" = "私たちは……あなたのような大人が――大嫌いです。"
"42050-196" = "[s] \"……そっか。\""
"42050-197-ユキノ" = "……D-Dayを控えた今、わざわざ先生と敵対する必要はない。"
"42050-198-ユキノ" = "――FOX小隊、撤収。#n各小隊員はHQに復帰し、次の作戦に備えるように。"
"42050-206-ユキノ" = "……月雪小隊長。#n今、貴官のスマホに座標を一つ送信した。"
"42050-207-ユキノ" = "私の提案に乗る気があるのなら、その場所に。"
"42050-208-ミヤコ" = "私は……。"
"42050-209-ユキノ" = "……いつかは君たちも、理解できる日が来るはずだ。"
"42050-210-ミヤコ" = "………。"
"42050-214" = "次回;後輩の苦悩"
