[translation]
"42230-1" = "第23話;失敗したクーデター"
"42230-4" = "連邦生徒会長代行執務室"
"42230-6-カヤ" = "ふふっ……遅めのブランチを楽しんだ後に飲むエスメラルダの香りは、やはり格別ですね。"
"42230-7-カヤ" = "貴重なコーヒー豆な事もあって、入手には多少手こずりましたが……今日を記念する一杯として、これくらいの贅沢は許されるでしょう。"
"42230-11-カヤ" = "さてと。そろそろ子ウサギ駅爆発のニュースが流れる頃合いですが……"
"42230-18-カヤ" = "はい、連邦生徒会長代行の[ruby=しらぬい]不知火[/ruby]カヤです。"
"42230-19-カヤ" = "あ、ジェネラル。ちょうど良いところに。"
"42230-20-カヤ" = "子ウサギ駅の件は無事に完遂しましたか？"
"42230-24-カヤ" = "……はい？FOX小隊が作戦に失敗……？"
"42230-25-カヤ" = "しかも、武装したRABBIT小隊がシャーレの先生と一緒に連邦生徒会に向かっている……？"
"42230-26-カヤ" = "そ、それはどういうことですか。もう一度説明してください。"
"42230-30-カヤ" = "先生が指揮するSRT隊員を止められなかった？#nい、一体何を言っているのですか……"
"42230-37-カヤ" = "お金を渡しているのですよ……？ "
"42230-39-カヤ" = "どんな手を使ってでも止めるべきでは！？"
"42230-51-ミヤコ" = "RABBIT1、上りの線路に到着しました。"
"42230-52-サキ" = "RABBIT2、現場の捜索完了。他に発見した脅威はなし。"
"42230-54-モエ" = "RABBIT3、さっきハイランダー鉄道学園に事故のニュースを伝えて、連邦生徒会の建物に向かう路線を封鎖しといたよ。"
"42230-55-モエ" = "これから1時間、鉄道は動かないはずだから安心して直進していいよ～！"
"42230-56-ミヤコ" = "了解です。"
"42230-57-ミヤコ" = "RABBIT2、RABBIT4。ターゲットが逃走する可能性がありますので、速やかに連邦生徒会の建物へ突入しましょう！"
"42230-59-ミユ" = "わ、わかった……！"
"42230-60-サキ" = "任せろ！"
"42230-66-ジェネラル" = "SRTのキツネどもがやられたようだな……"
"42230-67-ジェネラル" = "まともな訓練も受けていない小娘にやられるなど、特殊部隊の恥晒しだな。"
"42230-73-ジェネラル" = "カイザーSOFをここに待機させておいて助かった。"
"42230-74-ジェネラル" = "本来はキツネを相手するためのカードだが、ウサギ相手でも十全にその役割を果たしてくれるだろう。"
"42230-76-ジェネラル" = "私は、油断して失敗するようなバカとは違う――"
"42230-90-サキ" = "[ruby=タンゴー]Tango[/ruby]、ダウン！"
"42230-95-ミヤコ" = "了解、引き続き前進しましょう。"
"42230-100-ミユ" = "す、すみません……！"
"42230-110" = "[ns] \"すまない、お先に失礼するね。\""
"42230-114-ジェネラル" = "なんだ、あいつら……"
"42230-115-ジェネラル" = "人をバカにするのも程がある……"
"42230-116-ジェネラル" = "……絶対に許さないぞ、SRT！"
