[translation]
"10019010-12-セリカ" = "うわぁぁっ！出たわよ！！"
"10019010-13-ノノミ" = "さあ、走りましょう！"
"10019010-14-ホシノ" = "目標地点まで引きつけるよ～"
"10019010-21-マキ" = "エネルギー反応！？#nき、気をつけて、レーザーが来るよ！！ "
"10019010-22-セリカ" = "こ、こっちに来てるわよ！？"
"10019010-23-アヤネ" = "回避タイミングが計算できません！#n――ホシノ先輩！"
"10019010-36-ムツキ" = "うっわ、アレ直撃……？"
"10019010-37-ハルカ" = "あ、アル様……！"
"10019010-44-アル" = "……ふん。"
"10019010-45-アル" = "あの程度でやられる訳ないわ。予定通り、計画を進めるわよ。"
"10019010-46-ハルカ" = "そ、そうなんですか……？#n……そ、そうですね、分かりました！"
"10019010-47-ムツキ" = "……なるほどねぇ。#nんじゃ、引き続き前進～☆"
"10019010-51-マキ" = "うわぁああっ！？正面から食らっちゃってるよ、ヤバいって！！"
"10019010-52-アヤネ" = "……いえ、あの程度ならおそらく――"
"10019010-53-アヤネ" = "ホシノ先輩、状況はどうですか？"
"10019010-66-ホシノ" = "いやぁ、なかなか痛いねぇ～#nでもまあ、セーフかな。"
"10019010-67-ノノミ" = "うんうん、私たちは無事ですよ、アヤネちゃん。"
"10019010-68-セリカ" = "この程度、どうってことないわよ。"
"10019010-70-マキ" = "あの攻撃を、耐えた……！？ "
"10019010-71-ホシノ" = "ほんと、危ないとこだったよぉ～#n最近腰も弱ってきてるし、無理はできないんだけどなぁ……湿布代もバカにならないしさぁ～"
"10019010-72-セリカ" = "だからそんなに歳変わらないでしょうが！！"
"10019010-74-マキ" = "……すごいね、あなた達の委員長……いや、アビドスってみんな強いんだね。"
"10019010-75-セリカ" = "えっ、そうなの？ "
"10019010-76-アヤネ" = "あはは……比較するものが無いから、あまりよく分からないんですけどね……"
"10019010-80-アヤネ" = "……これで攻略準備は完了です！お疲れ様でした。"
"10019010-81-アヤネ" = "第1サンクトゥムの守護者との交戦、すぐにでも開始できます！"
"10019010-82-ホシノ" = "じゃあ、ちゃちゃっと行っちゃおっか。"
