[translation]
"90101020-1" = "第2話;カニ味魚肉ソーセージ"
"90101020-2" = "シャーレの地下、FOX小隊作戦本部"
"90101020-7-ニコ" = "FOX2、FOX3、帰還しました。"
"90101020-8-クルミ" = "ただいま～"
"90101020-13-オトギ" = "おー、お疲れ。"
"90101020-14-オトギ" = "だいぶ遅かったね。どしたの？"
"90101020-15-オトギ" = "ヴァルキューレの記録保管庫で何かあった？"
"90101020-16-クルミ" = "んー、潜入自体は問題なかったんだけど。"
"90101020-17-クルミ" = "警備局のバッジも、生徒手帳もちゃんと用意したし。"
"90101020-18-クルミ" = "でも、帰り道に生活安全局っぽい生徒に絡まれちゃったのよね。"
"90101020-19-クルミ" = "警備局じゃ見たことない顔だ、って。ほんと、目ざといなんてもんじゃないわよ。"
"90101020-20-オトギ" = "え……まさかバレたの？"
"90101020-21-クルミ" = "ううん。ニコがドーナッツの話で話題をそらしたらどうにかなった……んだけど……。"
"90101020-22-ニコ" = "話を合わせてるうちに、限定ドーナッツを一緒に買いに行く羽目になって……。"
"90101020-23-ニコ" = "HQに戻るのが遅くなりました、ごめんなさい。"
"90101020-24-オトギ" = "謝るような事じゃないって。お疲れ。"
"90101020-25-クルミ" = "あれ、ユキノは？"
"90101020-26-オトギ" = "連邦生徒会長のとこ。#nまだ戻ってないよ。"
"90101020-27-オトギ" = "夜ご飯も、そのまま済ませてくるってさ。"
"90101020-28-ニコ" = "じゃあオトギは、お夕飯まだかな？"
"90101020-29-ニコ" = "お腹空いてると思うし、すぐ用意するね。"
"90101020-30-オトギ" = "あー、大丈夫。もう食べたから。"
"90101020-31-ニコ" = "それって――"
"90101020-32-クルミ" = "「はみだしフーズ」の「カニ味魚肉ソーセージ」じゃない。#nほんと好きよね、それ。"
"90101020-33-オトギ" = "好きっていうより便利なんだよね。"
"90101020-34-オトギ" = "意外とお腹に溜まるし、日持ちするし。"
"90101020-35-オトギ" = "そんでもって食べやすい♪#nスナイパーは食事中も気配を殺さなきゃいけないから、正直助かるんだよね。"
"90101020-36-クルミ" = "まぁ、理にはかなってる……のかな……？"
"90101020-37-ニコ" = "便利だからって、それだけじゃダメだよ。成長期なんだからちゃんと食べないと。"
"90101020-38-ニコ" = "用意するから、ちょっと待ってて。"
"90101020-39-オトギ" = "はーい。"
"90101020-40-クルミ" = "ねぇ、それって結構高いんじゃないの？#nカニが入ってるんでしょ？"
"90101020-41-クルミ" = "弾代ケチっておやつ代に回してるとかじゃないよね……？"
"90101020-42-オトギ" = "そんな高くないよ。1本100円もしないし。"
"90101020-43-クルミ" = "え？カニの缶詰って安くても1000円はするのに……？#nちょっと見せて。"
"90101020-47-クルミ" = "あ。"
"90101020-48-クルミ" = "これ、カニ[ruby=・]風[/ruby][ruby=・]味[/ruby]じゃん。"
"90101020-49-オトギ" = "……え？"
"90101020-50-クルミ" = "原材料表示見て。カニ、ほとんど入ってないよ。"
"90101020-51-クルミ" = "カニエキスでそれっぽくしてるだけ。"
"90101020-52-オトギ" = "えっ……そんな……カニが入って……ない……？"
"90101020-53-オトギ" = "もうおしまいだぁ……。"
"90101020-54-クルミ" = "値段の時点で疑いなさいよ……。"
"90101020-55-クルミ" = "普通、安いなりの理由があるんだから。"
"90101020-56-ニコ" = "あ、カニといえば……。"
"90101020-57-ニコ" = "RABBIT小隊が、漁村で起きた事件を解決したらしいよ。#nそれでお礼にって質の良いエビをたくさん――"
"90101020-58-クルミ" = "ねぇ。それ、どういうこと？"
"90101020-59-ニコ" = "えっと……私たちが矯正局にいた頃に……#nD.U.でエビの供給が途切れたことがあったって――"
"90101020-60-クルミ" = "エビの話じゃなくて！"
"90101020-61-クルミ" = "こっそり連絡取ってたの？"
"90101020-62-オトギ" = "1人だけずるーい！"
"90101020-63-ニコ" = "も、もらったお手紙に返事を書いてたら、文通になっちゃって……。"
"90101020-64-ニコ" = "ほら、矯正局はスマホを使えないでしょ？#nだからミヤコちゃんがたまに手紙を送ってくれてたんだ。"
"90101020-65-クルミ" = "……ああ、そういうことね。"
"90101020-66-オトギ" = "今どき手紙って、ミヤコちゃんも真面目だねぇ。"
"90101020-67-ニコ" = "どんな時でも真っ直ぐなのが、ミヤコちゃんの良いところだと思うよ。"
"90101020-68-クルミ" = "いきすぎると短所だけどね。"
"90101020-73-ニコ" = "……そうだね。長所でもあり、短所でもあるよね。"
"90101020-74-オトギ" = "にしても……エビ、いいな～"
"90101020-75-オトギ" = "カニでも同じこと起きないかな？#n私たちがパパッと解決したら――"
"90101020-76-クルミ" = "やめなって。不謹慎すぎ。"
"90101020-77-オトギ" = "じょーだんじょーだん。そんな怖い顔しないでよ。"
"90101020-78-オトギ" = "でもそれはそれとして……カニ、食べたいなぁ。#nカニカマでも、カニ風の魚肉ソーセージでもない、本物のカニ。"
"90101020-86-ニコ" = "あっ、おかえり。"
"90101020-87-ユキノ" = "カニだ。"
"90101020-91-クルミ" = "……え？"
"90101020-95-ユキノ" = "これより、カニと戦いに行く。"
"90101020-97" = "次回;カニとドラム缶"
