[translation]
"1601802-1" = "隊長の訪問"
"1601802-3" = "[ns1] \"ラ～ブ～！！\"\n[ns2] \"ウェルカムトゥ、シャーレッ！！！！\" "
"1601802-6-ラブ" = "う、うるさいっ！いちいち声がデカいのよっ！"
"1601802-7" = "[s3] \"ラブがシャーレに来てくれた……！\"\n[s4] \"今日はラブ記念日だ！！\""
"1601802-10-ラブ" = "は、はぁっ！？き、記念日って何！！？"
"1601802-11-ラブ" = "というか、なんでロビーに？#nロビーでする仕事でもあったの？"
"1601802-12" = "[s] \"ん？オフィスから走ってきたの。\""
"1601802-13-ラブ" = "ワンコかあんたは！"
"1601802-14-ラブ" = "転んでケガしたらどうするのよ！"
"1601802-15-ラブ" = "はぁ……歓迎してくれるのはいいんだけど。"
"1601802-16-ラブ" = "先生って……その。"
"1601802-17-ラブ" = "まわりの視線とか、気にならないわけ？"
"1601802-18" = "[s5] \"私、変な格好だったかな？\"\n[s6] \"この服、一番のお気に入りなんだけど……。\""
"1601802-21-ラブ" = "そっ、そうじゃなくて！"
"1601802-22-ラブ" = "先生って、生徒のお手本にならなきゃいけないんじゃない？"
"1601802-23-ラブ" = "生徒会とか、ヴァルキューレとも付き合いがあるでしょ？"
"1601802-24-ラブ" = "だから……。"
"1601802-25-ラブ" = "うちみたいな不良と一緒にいていいのか、って話。"
"1601802-26" = "[s] \"それがどうかしたの？\""
"1601802-27-ラブ" = "いやっ、だから……。"
"1601802-28-ラブ" = "はぁ……もういいわ、先生はなんとも思ってないのね。"
"1601802-29" = "[s] \"ラブはすごくいい子だよ？\""
"1601802-30-ラブ" = "はぁっ！？"
"1601802-31" = "[s7] \"連絡する時、丁寧な言葉を使ってくれるし。\"\n[s8] \"相手の事も考えてくれるし。\"\n[s9] \"転ばないように心配してくれるし！\""
"1601802-35-ラブ" = "いっ、いきなりなにっ！？"
"1601802-36-ラブ" = "それくらい普通でしょ！うち、どれだけ性悪だと思われてるのよ！？"
"1601802-37-ラブ" = "……まあ、先生がいいならいいわ。"
"1601802-38-ラブ" = "でもさすがに、長居するのはちょっとね……。"
"1601802-39-ラブ" = "それじゃ、またね。階段では走らないのよ。"
"1601802-40-ラブ" = "お邪魔したわね。"
"1601802-41" = "[ns10] （ラブをシャーレに連れていく）\n[ns11] （シャーレにラブを連れていく）"
"1601802-45-ラブ" = "なっ、何！？"
"1601802-46" = "[s12] \"私の自慢の生徒に……。\"\n[s13] \"シャーレを案内してあげるね！\""
"1601802-49-ラブ" = "シャーレ！？い、今！？"
"1601802-50" = "[s] \"おんぶしようか？\""
"1601802-51-ラブ" = "何言ってんのバカっ！"
"1601802-52-ラブ" = "普通に案内して！"
"1601802-54" = "（そうしてラブにシャーレを案内し……）"
"1601802-55" = "（楽しい時間を過ごした）"
