[translation]
"1601803-1" = "隊長の重み"
"1601803-2" = "（ラブと一緒に商店街へ向かった）"
"1601803-3-ラブ" = "ん～……ううーーんん……。"
"1601803-4-ラブ" = "悩むなぁ……。"
"1601803-5" = "[s1] \"きな粉？みたいに見えるけど……。\"\n[s2] \"何に使うの？\""
"1601803-8-ラブ" = "きな粉じゃないわ。これはクルミの殻を砕いたもの。"
"1601803-9-ラブ" = "ヘルメット団の必需品よ。これを使って磨いていくの。"
"1601803-10-ラブ" = "ヘルメットを塗る時は、まず元の色を紙やすりで全部剥がすんだけど……。"
"1601803-11-ラブ" = "剥がした直後は表面がツルツルで光を反射するから、#n磨いて元のガサガサに戻さないといけないのよ。"
"1601803-12" = "[s] \"ツルツルなヘルメットも持ってたよね？\""
"1601803-13-ラブ" = "ええ、使い分けてるわ。"
"1601803-14-ラブ" = "戦闘の時はガサガサのツヤ消しメット、#nカッコつけたい時はツヤツヤメット……みたいにね。"
"1601803-15-ラブ" = "それで、ガサガサにするのにクルミの研磨剤を使うってわけ。"
"1601803-16-ラブ" = "問題は、粗さの番手を30番にするか50番にするかなんだけど……。"
"1601803-17" = "[s] \"全部同じじゃないの？\""
"1601803-18-ラブ" = "違うわよ！もっとよく見て！？"
"1601803-19-ラブ" = "んん……今月も金欠だし、一つに絞らないと……。"
"1601803-26-スケバンA" = "ん？"
"1601803-27-スケバンB" = "あいつ、ジャブジャブヘルメット団のリーダーじゃね？"
"1601803-28-スケバンA" = "隣にシャーレの先生もいるな。"
"1601803-29-スケバンA" = "おい！そこのオカッパ！"
"1601803-30-スケバンB" = "ヘルメット団は引退して、大人とお出かけでちゅか～？"
"1601803-34-ラブ" = "あぁ？"
"1601803-35-スケバンA" = "子分はどうしたんだ？"
"1601803-36-スケバンB" = "おい、今のうちにやっちまうか？"
"1601803-37-ラブ" = "……はぁ。"
"1601803-38-ラブ" = "先生、ちょっと失礼するわね。"
"1601803-39" = "[s] \"なんで靴下を銃に……？\""
"1601803-40-スケバンA" = "ん？どうしたアイツ。"
"1601803-41-スケバンB" = "ビビって血迷ったか？"
"1601803-42-ラブ" = "お姉さんね、いま弾代も節約しなきゃいけないの。"
"1601803-43-ラブ" = "これはチャンスよ？#n[ruby=・]お[/ruby][ruby=・]買[/ruby][ruby=・]い[/ruby][ruby=・]物[/ruby]が済んだら、とっとと失せな。"
"1601803-44-スケバンA" = "ふざけやがって……。"
"1601803-45-スケバンA" = "やっちまえ！！"
"1601803-60-スケバンB" = "ぐはっ！"
"1601803-65-スケバンA" = "銃で殴るたぁ卑怯だぞ……！"
"1601803-66-スケバンA" = "よこせ！！"
"1601803-77-スケバンA" = "靴下が滑って、銃が掴めない……っ！"
"1601803-78-ラブ" = "この靴下がすっぽ抜けたら、転んじゃうわね。"
"1601803-79-スケバンA" = "やっ、やめっ……！"
"1601803-80-ラブ" = "やめない。"
"1601803-90-ラブ" = "あー、めんどくさ。"
"1601803-91-スケバンC" = "[ruby=こまかぜ]河駒風[/ruby]ラブ！うちらの縄張りで、よくも……！！"
"1601803-92-スケバンC" = "手榴弾でもくらえ！"
"1601803-93-ラブ" = "危ないでしょ！"
"1601803-94-ラブ" = "ふんっ！"
"1601803-100-スケバンC" = "ぐあぁっ！！"
"1601803-105-ラブ" = "おっ、綺麗に飛んだわね。"
"1601803-106-スケバンD" = "他の奴らも呼んでこい！絶対捕まえてやるっ！！"
"1601803-114-スケバンY" = "つ、[ruby=つえ]強[/ruby]え……ぐぅっ。"
"1601803-115-スケバンZ" = "撤退！てったーい！！"
"1601803-119-ラブ" = "ほんっと、めんどくさい連中……。"
"1601803-120-ラブ" = "一日を棒に振っちゃったじゃない！！"
"1601803-121-ラブ" = "次は足腰立たなくしてやるわよ！"
"1601803-122-ラブ" = "はぁ……もうクタクタ。"
"1601803-123-ラブ" = "先生、大丈夫？怪我は？"
"1601803-124" = "[s3] \"大丈夫！なんともないよ！\" \n[s4] \"いつもこんな感じなの？\""
"1601803-127-ラブ" = "今日はやたらと絡んできたけど、まあ、いつも通りかしら。"
"1601803-128-ラブ" = "スケバンもだけど、ヘルメット団の内輪もめもよくあるわね。"
"1601803-129-ラブ" = "まあ、今日みたいにガツンとやっとけば、当分は静かなはずよ。"
"1601803-130" = "[s] \"ラブってすごく強いんだね！\""
"1601803-131-ラブ" = "はっ、当たり前でしょ？"
"1601803-132-ラブ" = "ヘルメット団隊長の名は伊達じゃないわ！"
"1601803-133" = "[s] \"みんなが頼れるリーダーだね！\""
"1601803-134-ラブ" = "ちょっと褒めすぎじゃない……？#nえへへっ。"
"1601803-135" = "[s] \"そして根は優しくて！\""
"1601803-136-ラブ" = "ちょっ……。"
"1601803-137" = "[s] \"とげとげの歯も可愛い！\""
"1601803-138-ラブ" = "うるさいっ！！"
"1601803-140" = "（その後、ポカポカ殴られながらラブを褒めちぎった）"
