[translation]
"34010-1" = "第1話;プロローグ"
"34010-4-？？？" = "いたぞ！！"
"34010-5-？？？" = "あっちだ！追え！！"
"34010-10-？？？" = "も、もうおしまいです……ここは行き止まりですし……。"
"34010-11-？？？" = "……反対側も。完全に包囲されてる。"
"34010-12-？？？" = "くっ……。"
"34010-19-アリウスの生徒A" = "諦めるんだな。#nこれ以上は逃げられないぞ。"
"34010-23-サオリ" = "……。"
"34010-24-ヒヨリ" = "ひ、ひっ……。"
"34010-25-アツコ" = "（スッ、ススッ……）"
"34010-26-ミサキ" = "……弾薬、ほとんど残ってないし、もう体力も限界……。"
"34010-27-ミサキ" = "リーダーの傷も大きい。このままじゃ、逃げるどころかリーダーの命が危ないよ。"
"34010-33-サオリ" = "……最後の手段ならまだ残っている。これなら……。"
"34010-34-ヒヨリ" = "ま、まさか。"
"34010-35-ミサキ" = "……ヘイローを破壊する爆弾。"
"34010-36-サオリ" = "ミサキ、ヒヨリ。私が時間を稼ぐ間に姫を連れて……ここを離れるんだ。"
"34010-37-アツコ" = "……サオリ。"
"34010-38-サオリ" = "ここを離れて……そうしたら……その次は……。"
"34010-39-サオリ" = "その……次は……。"
"34010-40-アツコ" = "サオリ。"
"34010-41-サオリ" = "……姫？"
"34010-46-アツコ" = "もういいよ。私たちは頑張った。"
"34010-47-ミサキ" = "……。"
"34010-48-ヒヨリ" = "ひ、姫ちゃん……どうしたんですか……？"
"34010-53-アツコ" = "「彼女」が求めているのは私……そうでしょう？"
"34010-54-アツコ" = "私が行くよ。だから、他のメンバーは見逃してほしい。"
"34010-55-アリウスの生徒A" = "……。"
"34010-57-サオリ" = "アツコ！？……一体何をっ！？"
"34010-59-アツコ" = "……もういいよ、サオリ。ぜんぶ、無意味だよ。"
"34010-60-アツコ" = "ここを切り抜けたその先は？一体どこに向かうの？"
"34010-61-サオリ" = "……。"
"34010-62-アツコ" = "トリニティにゲヘナ――そしてアリウスさえも私たちを追いかけてる。"
"34010-63-アツコ" = "このキヴォトスで私たちが安心できる場所はないよ。#n私達の命が尽きるまで、息を潜めて逃げ隠れる人生が続くだけ。"
"34010-64-アツコ" = "でも、それも私がいるからの話。サオリも、ミサキも、ヒヨリも。私のせいでこうなってしまったから……。"
"34010-66-アツコ" = "だから、私が終わらせる。"
"34010-68-ヒヨリ" = "ひ、姫ちゃん……。"
"34010-69-ミサキ" = "……姫。"
"34010-70-サオリ" = "……ダメだアツコ、戻ったら殺される……それくらい、分かってるだろう？"
"34010-72-アツコ" = "……今まで私は何の決定も判断もしなかった。だから、今回くらいは自分で決めたっていいでしょ？"
"34010-76-アツコ" = "約束してくれる？みんなを自由にしてくれるって。"
"34010-77-アリウスの生徒A" = "……。"
"34010-78-アリウスの生徒A" = "……少し待ってろ、マダムに確認を取る。"
"34010-82-？？？" = "ほぉ"
"34010-83-？？？" = "……なるほど、わかりました。お約束いたしましょう。"
"34010-84-アツコ" = "その名にかけて、誓って。"
"34010-85-？？？" = "名前を……？それにどれほどの意味が？"
"34010-86-アツコ" = "必ず約束を守ってほしいから。"
"34010-87-？？？" = "いいでしょう……すべての巡礼者の幻想である私「ベアトリーチェ」の名にかけて、お約束いたします。"
"34010-88-アツコ" = "……うん、約束だよ。"
"34010-93-アリウスの生徒B" = "姫様、こちらを。マダムのご指示です。勝手にマスクを外されては困ります。"
"34010-98-ベアトリーチェ" = "傷一つないよう、丁重に扱いなさい。儀式は明朝、日の出と共に始めます。"
"34010-100-アツコ" = "……元気でね。サオリ、みんな――さようなら。"
"34010-101-ミサキ" = "姫……。"
"34010-102-ヒヨリ" = "姫ちゃん……。"
"34010-107-サオリ" = "ダメだ……アツコ……。"
"34010-108-サオリ" = "私は……お前まで守れなかったら……"
"34010-109-サオリ" = "信念も……守るべきものも……全部なくなってしまったら……。"
"34010-110-サオリ" = "私は……。"
"34010-113-サオリ" = "アツコ、私は……。"
"34010-114-サオリ" = "私は一体何のために今まで……。"
"34010-118-サオリ" = "何のために……生きているんだ……？"
"34010-119-アリウスの生徒A" = "……残りのスクワッドはどうしますか？"
"34010-120-ベアトリーチェ" = "すべて始末なさい。"
"34010-121-アリウスの生徒A" = "かしこまりました。"
"34010-126-アリウスの生徒A" = "撃て。"
"34010-128-ミサキ" = "……。"
"34010-129-ヒヨリ" = "……。"
"34010-130-サオリ" = "……。"
"34010-135" = "次回;不揃いなティーパーティー"
