[translation]
"34060-1" = "第6話;折れてしまった羽"
"34060-3-ミカ" = "う、うん！連絡もらったから急いで来たよ。"
"34060-4-ミカ" = "二人っきりで話したいって……セイアちゃんらしくなくて、ちょっとビックリしたけど！"
"34060-5-ミカ" = "いつも監視してる正義実現委員会の子にも、扉の外で待っててもらってるよ。だから……。"
"34060-6-セイア" = "ミカ……。"
"34060-7-ミカ" = "セ、セイアちゃん……？あれ、顔色が……大丈夫？体も震えて……大丈夫？誰か呼んだ方が――"
"34060-8-セイア" = "……アリウス自治区に接触した時、「スクワッド」以外で他の誰かに会ったことは？"
"34060-9-ミカ" = "えっ……アリウス……?"
"34060-10-セイア" = "アリウス自治区には、本当に一度も行ったことがないのか？"
"34060-11-ミカ" = "えっと……あの、セイアちゃん……？"
"34060-12-セイア" = "ドレスを着た背の高い女性を見たことは？「スクワッド」について他に知っている情報は？"
"34060-13-ミカ" = "……え、えっと、セイアちゃん。何を……。"
"34060-14-セイア" = "ゲホ、ゲホッ……。"
"34060-15-セイア" = "君が、アリウスに接触したことによって……。"
"34060-19-ミカ" = "……。"
"34060-20-ミカ" = "あ……そ、そうだよね？私のせいで……いろいろ……。"
"34060-21-セイア" = "先生が……スクワッドに狙われている……。"
"34060-22-ミカ" = "……！?"
"34060-23-ミカ" = "……セイアちゃん、今なんて……？"
"34060-28-セイア" = "君が、先生を連れてきたから……！"
"34060-29-ミカ" = "……！！？"
"34060-30-セイア" = "……いや、君のせいではないな……済まない。"
"34060-31-セイア" = "ゲホ、ゲホゲホ……！！"
"34060-33-セイア" = "ゲホゲホゲホゲホ……！！"
"34060-34-セイア" = "（ああ……駄目だ。体が言うことを聞かない……）"
"34060-37-セイア" = "（意識が……だん……だん…………）"
"34060-41-セイア" = "……。"
"34060-42-セイア" = "……ここは？"
"34060-43-セイア" = "この建築様式……まさか、アリウス自治区の……?"
"34060-44-ベアトリーチェ" = "ええ――アリウスの「バシリカ」と呼ばれるところです。"
"34060-45-セイア" = "！！"
"34060-51-セイア" = "うっ……！！"
"34060-52-ベアトリーチェ" = "覗き見をしているネズミがいると思ったら、やはりあなたでしたか―――まさかこの至聖所まで追いかけてくるなんて。"
"34060-53-ベアトリーチェ" = "夢の中だと思って油断していたのですか？預言の大天使……いえ、[ruby=ゆりぞの]百合園[/ruby]セイア。"
"34060-54-セイア" = "……こ、ここが……あの祭壇……。"
"34060-55-ベアトリーチェ" = "ええ。他のゲマトリアも訪れたことのない秘境です。光栄に思いなさい。"
"34060-60-セイア" = "……！！！"
"34060-63-ミカ" = "セ、セイアちゃん！しっかりして！！"
"34060-64-ミカ" = "誰か！！誰か人を呼んできて！！セイアちゃんが……セイアちゃんがおかしいの！！"
"34060-65-正義実現委員会部員" = "は、はい！わ、わかりました！！"
"34060-67-セイア" = "（あれは……一体……）"
"34060-68-セイア" = "（視界に収めるだけでも……不吉な気配が……）"
"34060-69-セイア" = "（この祭壇は……一体……まさか、アレを呼ぶための……？）"
"34060-71-セイア" = "（彼女は……！）"
"34060-73-セイア" = "（……）"
"34060-74-セイア" = "（そうか、この儀式は……まさか……そんな……）"
"34060-78-セイア" = "（この女は……キヴォトスに一体どんな災禍を……招こうと……）"
"34060-80-ミカ" = "ああ……セイアちゃん、気がついた？"
"34060-81-ミカ" = "どうして……セイアちゃんがこんな目に……。"
"34060-82-ミカ" = "私は、どうすれば……セイアちゃん……どうしよう……。"
"34060-84-セイア" = "ミカ……私は君に……また同じことを……。"
"34060-85-セイア" = "すまない、ミカ……君のせいではない。これは……私が招いた失敗……。"
"34060-86-セイア" = "……先生、私の声が聞こえるなら……どうか……。"
"34060-87-セイア" = "逃げてくれ――できるだけ遠くに……アリウス自治区から離れてくれ。"
"34060-88-セイア" = "そうでなければ……先生は……。"
"34060-89-セイア" = "……先生を狙う者に……。"
"34060-90-セイア" = "先生……！！"
"34060-92" = "キヴォトスの某所・路地裏"
"34060-94" = "[ns1] （……今、セイアの声が聞こえたような）\n[ns2] （気のせいか……嫌な胸騒ぎが……）"
"34060-95" = "（発信元不明のメールを頼りにたどり着いた街は寂れており、人の気配が感じられない。）"
"34060-96" = "（発信元不明のメールを頼りにたどり着いた街は寂れており、人の気配が感じられない。）"
"34060-101" = "[ns] （誰かいる……？）"
"34060-103" = "[ns] \"サオリ……？\""
"34060-104-サオリ" = "……。"
"34060-110" = "次回;選択と決断"
