[translation]
"34105-9-ヒヨリ" = "……！！"
"34105-10-ミサキ" = "……。"
"34105-16-ミカ" = "ふふっ、やっぱりここに来ると思ってたよ。大当たり！"
"34105-17-サオリ" = "[ruby=みその]聖園[/ruby]、ミカ……。"
"34105-18-ミカ" = "悪役登場☆ってところかな！……まだ覚えててくれてたんだね？"
"34105-19-ミカ" = "会えて嬉しい……って顔じゃなさそうだけど、どうしたの？"
"34105-24-ミカ" = "そんな、魔女でも見たみたいな顔しちゃって。"
"34105-26" = "次回;追撃者"
