[translation]
"34155-3-ミカ" = "ケホ、ケホ……。"
"34155-4-サオリ" = "はぁ……ぐっ……。"
"34155-5-ミサキ" = "やっと、制圧できた……。"
"34155-6-ヒヨリ" = "う、うう……倒せたんでしょうか。"
"34155-10-ミカ" = "んんっ……痛いね……やっぱ先生がいると厄介だな……。"
"34155-11" = "[s1] \"ミカ……セイアはたぶん無事だよ。\"\n[s2] \"だからトリニティに戻って……ミカを傷つけたくない。\""
"34155-12-ミカ" = "先生……。"
"34155-13-ミカ" = "先生……。"
"34155-14-ミカ" = "ごめんね……私はいつもこんなだよね……。"
"34155-15-ミカ" = "私みたいな問題児はさ……先生に何度も心配をかける生徒は……先生の傍にいられないってことも、よく分かってる……。"
"34155-19-ミカ" = "でも……私……。"
"34155-21-ミカ" = "私……わたしには……。"
"34155-23-ミカ" = "もう、帰る場所がないの……トリニティにも……どこにも……。"
"34155-24-ミカ" = "私はトリニティの裏切り者で、みんなの敵で……#n――何度もセイアちゃんを傷つけてしまった魔女だから……。"
"34155-25-ミカ" = "学園から追い出されたら、ナギちゃんにも、大切な人たちにも……二度と会えなくなる……。"
"34155-26-ミカ" = "生徒じゃなくなったら……私みたいな問題児、先生だって、もう会ってくれないよ……。"
"34155-27-ミカ" = "私に、これ以上幸せな未来なんか訪れないってことも、よく分かってる……。"
"34155-28-ミカ" = "わ、私は……悪党だから……人殺しだから……。"
"34155-29-ミカ" = "だから……私に残っているのは[ruby= ・   ・   ・   ・   ・ ]こんなもの[/ruby]しか、ないの……。"
"34155-30-ミカ" = "なのに、あなた達は……どうして？"
"34155-31-ミカ" = "私は大切なものを全部失ったのに！#n――ぜんぶ、奪われたのに！！"
"34155-32-ミカ" = "あなた達は……どうして？"
"34155-34-サオリ" = "……。"
"34155-35-ヒヨリ" = "……。"
"34155-36-ミサキ" = "……。"
"34155-40-ミカ" = "あなた達が何の代償も支払わないで、何も奪われないでいるなんてそんなの……。"
"34155-41-ミカ" = "そんな事、許したら……私は……"
"34155-42-ミカ" = "私は……何者でもなくなってしまう……。"
"34155-43-ミカ" = "私には、何の意味も残らない……。"
"34155-44-ミカ" = "わたし……。"
"34155-45-ミカ" = "わたしは、どうしたらいいの……。"
"34155-46-ミカ" = "……。"
"34155-47-ミカ" = "スクワッドを――サオリを、そのままになんてしておけない……"
"34155-48-ミカ" = "その女が、何の代償もなく先生の庇護を受けるなんてダメ……。"
"34155-49-サオリ" = "……。"
"34155-50-ミカ" = "だから先生、私を止めないでね。"
"34155-63" = "[ns] \"ミカ！\""
"34155-64-ヒヨリ" = "い、行ってしまいました……？"
"34155-65-ミサキ" = "一体なんなの……あの女。"
"34155-66-サオリ" = "そんなに……私が憎いのか、ミカ。"
"34155-67-サオリ" = "……仕方ないのかも、しれないな。"
"34155-68-ミサキ" = "リーダーどうする？あの女、また私たちを追いかけてきそうだけど……このままバシリカに突入するのは少し危険かもしれない。"
"34155-69-ミサキ" = "アリウスに聖徒会……さらにストーカーまで……相手しきれないよ。"
"34155-70-サオリ" = "……このまま旧校舎地下の回廊を通ってバシリカに進入する。"
"34155-71-サオリ" = "彼女が何を企んでいようが構わない。行くぞ……時間がない。"
"34155-75-ヒヨリ" = "は、はい！"
"34155-79-ミサキ" = "……仕方ない、か。"
"34155-80-ミサキ" = "行こう、先生。"
"34155-85" = "[ns3] ついて行く。\n[ns4] （ミカ……）"
"34155-91" = "次回;地下回廊"
