[translation]
"34245-2-ベアトリーチェ" = "グアアアアアアッ！！"
"34245-3-ベアトリーチェ" = "何故、どうして……！！私は、私の……！！"
"34245-4-ベアトリーチェ" = "私の計画が……私の領地が……私の意識が……"
"34245-5-ベアトリーチェ" = "わたくしの……ワタクシ、ノ……"
"34245-6-ベアトリーチェ" = "グッ……アア……アァ……。"
"34245-13-サオリ" = "はあ……はあ……はあ……。"
"34245-14-ヒヨリ" = "お、おわり……ですか？"
"34245-18-ヒヨリ" = "あ！ひ、姫ちゃんは！！"
"34245-19-サオリ" = "あ、アツコ……！！"
"34245-21-ミサキ" = "まだあそこに！"
"34245-22-ヒヨリ" = "あ、あわ……は、早く姫ちゃんを降ろしましょう！"
"34245-32-ヒヨリ" = "ひ、姫ちゃん……。"
"34245-37-サオリ" = "姫……しっかりしてくれ……。"
"34245-38-ヒヨリ" = "ひ……姫ちゃん……。"
"34245-39-ミサキ" = "……外傷がひどい。血を流しすぎてる。"
"34245-40-サオリ" = "姫……アツコ……頼む、目を開けてくれ……"
"34245-41-サオリ" = "お願いだ……アツコ……目を、開けてくれ……"
"34245-42-ミサキ" = "……。"
"34245-43-ヒヨリ" = "……。"
"34245-51-アツコ" = "サオリ、ちゃん……？"
"34245-52-サオリ" = "アツコ……！！"
"34245-53-ミサキ" = "姫……。"
"34245-54-ヒヨリ" = "ひ、姫ちゃん！！気がつきましたか！？"
"34245-55-アツコ" = "うん……"
"34245-56-アツコ" = "サオリ、ヒヨリ、ミサキ……みんな、おはよう。"
"34245-66-サオリ" = "アツコ……！！！"
"34245-67-アツコ" = "あ、サオリ……？"
"34245-68-サオリ" = "良かった……本当に、よかった……。"
"34245-69-アツコ" = "う、うん……？"
"34245-70-サオリ" = "アツコ……生きていてくれて、ありがとう……#n本当に、ありがとう……。"
"34245-71-アツコ" = "……うん。"
"34245-72-サオリ" = "くっ……うぅ……"
"34245-73-アツコ" = "サオリ……泣かないで。私は大丈夫だから。"
"34245-74-アツコ" = "先生が手伝ってくれたんだね……？"
"34245-75-サオリ" = "ああ……そうだ……。"
"34245-76-サオリ" = "ありがとう、先生……。#nもう、これで大丈夫なんだな。"
"34245-79-アツコ" = "……うん。大丈夫だよ、サオリ。#nきっと全部、終わったよ。"
"34245-81" = "[ns] 倒れているベアトリーチェに近づく。"
"34245-85-ベアトリーチェ" = "く、ぐぅっ……"
"34245-86" = "[s] \"終わりだよ、ベアトリーチェ。\""
"34245-87-ベアトリーチェ" = "よくも……わ、私はまだ……まだ！"
"34245-88-ベアトリーチェ" = "たかだか儀式を妨害した程度で図に乗らないでください！"
"34245-89-ベアトリーチェ" = "まだ私にはバルバラもアリウスの兵力も無傷で残っている！#n[ruby=ミメシス]複製[/ruby]能力だって保持しているのです！！"
"34245-90-ベアトリーチェ" = "一度の勝利ごときで、終わりになど――"
"34245-92-？？？" = "いいえ、このお話はこれで終わりです。"
"34245-93" = "[ns] \"……！！\""
"34245-98-ベアトリーチェ" = "ゴルコンダ……！！"
"34245-99-ゴルコンダ" = "ああ、落ち着いてください。驚かせたなら申し訳ありません。#n私は「ゲマトリア」のゴルコンダ……。"
"34245-100-ゴルコンダ" = "――挨拶は省略するとしましょう。#nもしかしたら私たちは、以前お会いしたかもしれませんから。"
"34245-101-ゴルコンダ" = "私は戦いに来たのではありません。#nマダムを連れ戻しに来たのです。"
"34245-102-ベアトリーチェ" = "私を……！？"
"34245-103-ゴルコンダ" = "それに、戦闘で勝てる自信もありません。#n「ゲマトリア」が皆マダムのように怪物に変われるわけではないですからね。"
"34245-104-ゴルコンダ" = "ええ、マダム。これで明らかになりました。#n――先生はあなたの敵対者ではありません。これはあなたの物語ではないのです。"
"34245-105-ベアトリーチェ" = "……！！"
"34245-106-ゴルコンダ" = "あなたが起こした事件、葛藤、過程の数々……。#nそれらは「知らずとも良いもの」に格下げされました。"
"34245-107-ゴルコンダ" = "あなたは主人公どころか……先生の敵対者でもなく、#nただの「[ruby=マクガフィン]舞台装置[/ruby]」だったのです。"
"34245-108-ベアトリーチェ" = "……く……ぐぅっ……！！"
"34245-109-ゴルコンダ" = "先生……あなたが介入してしまうと、すべての概念が変わってしまいます。#n元々この物語の結末はこうではなかったはずなのです。"
"34245-110-ゴルコンダ" = "友情で苦難を乗り越え、努力で打ち勝つ物語……？#n私が望んでいたテクストはもっと文学的なものだったはずなのですが……。"
"34245-111" = "[s] \"……。\""
"34245-112-ゴルコンダ" = "ふむ……申し訳ありません。ご気分を害してしまったようですね。"
"34245-113-ゴルコンダ" = "それでは、私はマダムを連れて帰ります。#nマダム、起きてください。"
"34245-118-ベアトリーチェ" = "ゲホッ……お前は……。"
"34245-119" = "[s] \"待って……！！\""
"34245-120-ゴルコンダ" = "もしかして私の邪魔をするつもりでしょうか？#nどうかそのような決断はなさらないでください、先生。"
"34245-121-ゴルコンダ" = "たとえば……私は様々な道具を生産できます。#nあなたが持っているその「ヘイローを破壊する爆弾」も私の作品ですので。"
"34245-122" = "[s] \"……！！\""
"34245-123-ゴルコンダ" = "ああ……もちろん、それをここで爆発させたりするつもりはありません。#nあなたには効果もない上に、その実験は結局失敗だったようですから。"
"34245-124-ゴルコンダ" = "その爆弾が実際にヘイローを破壊できるかどうかを一度も確認できませんでした。私の計画は断じてそうではなかったのですが……#nまぁ、ですから、それは廃棄する予定です。"
"34245-125-ゴルコンダ" = "マダム、今回の実験は失敗です。#n帰りましょう。"
"34245-126-ベアトリーチェ" = "ゴルコンダ……！"
"34245-127-ゴルコンダ" = "失礼しました、先生。#nそれでは、また。"
"34245-134" = "次回;大切な人"
