[translation]
"10010045-1" = "第4話;スラムの要塞へ（２）"
"10010045-3-ヘルメット団A" = "な、何なんだよもうっ！"
"10010045-5-ヘルメット団B" = "良いから撤退だ！さっさと逃げるぞ！"
"10010045-11" = "（突然のことに驚いたのか、ヘルメット団は次々に逃げ出していった）"
"10010045-13-ヨシミ" = "あははっ、ざまぁないわね！"
"10010045-14-アイリ" = "ヨシミちゃん、その台詞すごいチンピラっぽい……。"
"10010045-15-カズサ" = "良いんじゃん、似合ってるし。"
"10010045-16-ヨシミ" = "あははははははっ！！一昨日来やがれってのよ！"
"10010045-20-カズサ" = "うわ、ノリノリだ……まあとりあえず、店主さんもトラックも無事に取り戻せたし。一件落着かな。"
"10010045-21-アイリ" = "先生、ありがとうございました！"
"10010045-22" = "[s1] \"ううん、みんなお疲れ様。\"\n[s2] \"あんまり怪我も無くて良かった。\""
"10010045-23-ナツ" = "あ。"
"10010045-24-ナツ" = "あ。"
"10010045-25-ナツ" = "そういえば……。"
"10010045-33-ヒナタ" = "……？"
"10010045-34-ヒナタ" = "えっと、どうかしましたか？そんなにじっと見られると……。"
"10010045-35-ナツ" = "シスターさんがちゃんと戦ってるところ、初めて見たかも。すごいね。"
"10010045-36-ヒナタ" = "す、「すごい」とは……！？"
"10010045-37-カズサ" = "すみません、悪気は無いんです。"
"10010045-38-カズサ" = "ただ、「かっこよかった」と言いたいんじゃないでしょうか。"
"10010045-39-ヨシミ" = "あっ、確かに！最初機関銃で正門をぶっ壊したところとか、スカッとしちゃった！"
"10010045-40-ナツ" = "実際、こっちの戦力のうち結構な割合を担ってたもんね。ひとりだけ戦車みたいな感じで。"
"10010045-42-ヒナタ" = "せ、戦車！？いえ、そんな、私はその……！"
"10010045-43-ヒナタ" = "……あれ。あらためて聞くとそれ、素直に誉め言葉として受け取って良いんでしょうか！？"
"10010045-44-カズサ" = "……ナツ。"
"10010045-45-ナツ" = "うん、ごめんなさい。あくまで誉め言葉のつもりだよ。"
"10010045-46-ナツ" = "まあ何にせよこれ……褒章は、シスターさんが受け取るのが良いんじゃないかな。"
"10010045-54-ヒナタ" = "えっと、これは……"
"10010045-55-ナツ" = "「ミラクル5000」、その最後のひとつ。"
"10010045-56-ナツ" = "もちろん私たちも食べたいところだけど、シスターさんは何か込み入った事情があるみたいだし。"
"10010045-57-ナツ" = "さっきまでの雄姿を見てたら、"
"10010045-58-ナツ" = "満場一致だと思うんだけど……どう？"
"10010045-60-アイリ" = "私は賛成！"
"10010045-61-カズサ" = "店主さんも解放できて、これからまた作ってもらえるだろうし。別に急ぐ理由は無いよ。"
"10010045-62-ヨシミ" = "もう5日も我慢してるんだから、あと1日くらい平気！"
"10010045-64-ヒナタ" = "み、みなさん……。"
"10010045-65-？？？" = "……いや、その必要は無い。"
"10010045-66-ヒナタ" = "……？"
"10010045-71-ヒナタ" = "えっと、あなたは……？"
"10010045-72-スイーツ屋の店主" = "……何せ、こうして解放してくれたんだからね！"
"10010045-73-スイーツ屋の店主" = "こんな状況で、店主である私が何もしないわけにはいかないさ。最近作れなくってヤキモキしてたし……。"
"10010045-77-スイーツ屋の店主" = "よし、早速今からケーキを作ろう！"
"10010045-78-スイーツ屋の店主" = "個数限定と言わず、材料の限りいくらでも作るぞ！「ミラクル5000」パーティだ！"
"10010045-87-ナツ" = "……。"
"10010045-88-ナツ" = "……にひ。"
"10010045-89-ナツ" = "これぞ「ミラクル」……だね。"
