[translation]
"10010130-1" = "第13話;イット・サーヴズ・ユー・ライト（３）"
"10010130-15-正義実現委員会部員B" = "「七転八倒団」、戦力はそれほどでも……いえ、相当弱いです！"
"10010130-16-正義実現委員会部員A" = "なら、どうしてこんな時間がかかっているのですか！"
"10010130-17-正義実現委員会部員B" = "わ、分かりません、敵が多いわけではないのですが……。"
"10010130-22-正義実現委員会部員B" = "良く見えませんが、多分裏側で治療がされてるような……ですがこの復帰スピード、普通こんなに多くの衛生兵がいるはずが……！？"
"10010130-23-マシロ" = "みなさん、目標に惑わされないでください！あまり離れてはいけません！"
"10010130-24-マシロ" = "私たちの目的はあくまで、ここ一帯の警護です！誘い出されないように！"
"10010130-26-正義実現委員たち" = "はいっ！！"
"10010130-36-ヒナタ" = "これは、一体……？"
"10010130-37-ヒナタ" = "どうしてあの方々が、ここを攻撃して……！？？"
"10010130-41-ヒナタ" = "……？この音は、車の……いえ、トラック……？"
"10010130-46-スイーツ屋の店主" = "さあ、そこのみなさん！何だか騒がしい中ですが、少々お耳をこちらへ！"
"10010130-50-ヒナタ" = "あ、あなたは……！"
"10010130-51-スイーツ屋の店主" = "こんな時だからこそ、落ち着くためにもケーキはいかがでしょうか！"
"10010130-52-スイーツ屋の店主" = "ただのケーキではありません、あの限定商品「ミラクル5000」です！今日だけは何と、無料でお配りしてしまいます！"
"10010130-53-スイーツ屋の店主" = "今ここにいるみなさんが全員食べたとしても、十分余るはずの量です。さあ、いかがですか！？"
"10010130-55-アイリ" = "ど、どうかご遠慮なさらずー！もしかすると明日からはまた、限定商品になってしまうかもしれませんのでー！"
"10010130-56-アイリ" = "もちろん、すっごく美味しいですよー！"
"10010130-58-ヒナタ" = "ほ、放課後スイーツ部のみなさんまで……！？"
"10010130-59-カズサ" = "……これ、本当に行けるのかな。ここにいるのって、結構偉い人たちなんでしょ？"
"10010130-60-カズサ" = "いくら限定の「ミラクル5000」だからって、私たちみたいに――"
"10010130-65-参列者A" = "く、ください！ずっと食べたかったんです！"
"10010130-66-参列者B" = "えぇい、どきなさい！私が先です！普段であれば、お金を積んでも中々食べられないあの「ミラクル5000」……！"
"10010130-67-参列者A" = "ちょっと、割り込みしないでください！マナーを守って！"
"10010130-68-参列者B" = "「ミラクル5000」とマナーと、どっちが大事なんですか！？"
"10010130-72-ヨシミ" = "めっちゃ食いついてるじゃん。"
"10010130-73-ヨシミ" = "ほら、さっさと手伝うわよ。"
"10010130-75-カズサ" = "……。"
"10010130-76-ナツ" = "結局誰も彼も同じ……でもそれは決して、悪いことじゃない。"
"10010130-77-ナツ" = "美味しい食べ物を食べる、それは人生そのものと言っても過言じゃない。そして何より、後悔は先に立たず！"
"10010130-78-カズサ" = "ちょっとナツ、さりげなく逃げようとしないで。"
"10010130-79-ヨシミ" = "ああもう、良いから早く来なさいよ！お客さん来てるんだから！！"
"10010130-80-カズサ&ナツ" = "はーい……。"
"10010130-82-サクラコ" = "なっ、何なんですかこの状況は……！"
"10010130-83-サクラコ" = "み、「ミラクル5000」……私だって、一度も食べたことないというのに……！"
"10010130-84-サクラコ" = "で、ですが私には、私の役割が……。"
"10010130-88" = "（……）"
"10010130-89" = "[s1] \"せっかくだし、行ってきたら？\"\n[s2] \"何かあったら、私がどうにかするから。\""
"10010130-90-サクラコ" = "こ、この声……？"
"10010130-91-サクラコ" = "こ、この声……？"
"10010130-92-サクラコ" = "……！"
"10010130-93-サクラコ" = "せ、先生！？"
"10010130-96-正義実現委員会部員A" = "報告します！「七転八倒団」、総員の退却を確認しました！こちら側の被害は軽微！"
"10010130-97-正義実現委員会部員B" = "今からでしたら、追撃できそうですが……どうしますか？"
"10010130-98-マシロ" = "いえ、やめておきましょう。繰り返しになりますが、私たちの今日の任務は「会場の警備」です。"
"10010130-99-マシロ" = "会場側からも、特に通信連絡などは無いようですし……。"
"10010130-100-マシロ" = "防衛成功です、詳しい調査はまた後にしましょう。"
"10010130-101-マシロ" = "それでは総員、元の位置へ。"
"10010130-102-正義実現委員たち" = "はいっ！！"
"10010130-107-ヒナタ" = "い、いなくなっちゃいました……。"
"10010130-108-ヒナタ" = "さっきまでの銃撃戦が嘘みたいに……あれは一体……？"
"10010130-112-ヒナタ" = "……？"
"10010130-113-ヒナタ" = "……あれ？"
"10010130-114-ヒナタ" = "せ、先生……？"
"10010130-118-ヒナタ" = "ど、どうして先生がここに……！？古書館にいらっしゃったのでは……？"
"10010130-119-ヒナタ" = "……はい？"
"10010130-120-ヒナタ" = "想像以上に重かった……？"
"10010130-121" = "[s3] \"……これ、お願いしても良い？\"\n[s4] 手に持っていたものをヒナタに渡す。"
"10010130-122-ヒナタ" = "……あ、はい。"
"10010130-123-ヒナタ" = "……あ、はい。"
"10010130-124-ヒナタ" = "それはもちろんですが、えっと……。"
"10010130-125-ヒナタ" = "あれ、これは……？"
"10010130-126-ヒナタ" = "カーマ、スートラ……？"
"10010130-127-ヒナタ" = "どうしてこれが、先生の手に……？"
"10010130-128-ヒナタ" = "経典の入れ物に、入っていたはず……。"
"10010130-129-ヒナタ" = "……？？？？"
"10010130-134-サクラコ" = "みなさんお静かに！何だか変なことになってしまいましたが、式典を再開します。"
"10010130-135-サクラコ" = "重要な席なのですから、お口周りのケーキは拭いてください！"
"10010130-139-サクラコ" = "ふぅ……では、あらためまして。"
"10010130-141-ヒナタ" = "えっと、つまり……。"
"10010130-142" = "[s] \"うん。\""
"10010130-143-ヒナタ" = "せ、先生……。"
"10010130-144" = "[s] \"……間に合って良かった。\""
"10010130-148-ヒナタ" = "……！！！！"
"10010130-150-サクラコ" = "公開します、こちらが――"
"10010130-158-サクラコ" = "公会議を通じて解釈された、古代の経典……その第4次注釈が入った物です！"
