[translation]
"2004703-1" = "離さないで"
"2004703-2" = "（海辺にやってきた。本日は晴天なり）"
"2004703-7" = "[ns] \"あの、キキョウ？\""
"2004703-9" = "[ns] \"怒ってる……？\""
"2004703-10-キキョウ" = "え……？"
"2004703-11-キキョウ" = "私が？どうして？"
"2004703-12-キキョウ" = "鼻をくすぐる潮風に、心地いい波の音、輝く海原――"
"2004703-13-キキョウ" = "海に浮かぶ先生。"
"2004703-14-キキョウ" = "この状況で、何に怒るっていうの？"
"2004703-15" = "[s] \"それなら、見てないでこっちにおいでよ。\""
"2004703-16-キキョウ" = "そ、それは……。"
"2004703-17-キキョウ" = "準備運動をしっかりしたくて。"
"2004703-18-キキョウ" = "……それだけ。"
"2004703-19" = "[s] \"パラソルの下で本を読むのが……？\""
"2004703-20-キキョウ" = "知識をつけておくのも立派な準備運動だよ。"
"2004703-21-キキョウ" = "これは水泳の基礎から応用まで、すべてのテクニックが詰まってる教本なの。"
"2004703-22-キキョウ" = "夏休みに読むべき100冊にも選ばれてる。"
"2004703-23-キキョウ" = "これさえあれば、どんな状況でも溺れることはない。"
"2004703-24" = "[s] \"案ずるより産むが易しって言うよね？\""
"2004703-25-キキョウ" = "石橋を叩いて渡るとも言うでしょ？"
"2004703-26-キキョウ" = "私は百花繚乱の作戦参謀だもの。#n想定できるリスクなら、対策するべきでしょう？"
"2004703-27" = "[s] \"今日の海は穏やかだって予報で言ってたよ。\""
"2004703-28-キキョウ" = "……急に海からダイオウイカが現れたらどうするの？"
"2004703-29-キキョウ" = "最近よく出没するらしいし。"
"2004703-30-キキョウ" = "今日だってその可能性は……。"
"2004703-31" = "[s] \"大丈夫だよ！きっと！\""
"2004703-32-キキョウ" = "大丈夫？何を根拠に……。"
"2004703-36-キキョウ" = "はぁ……あんた、そんなに私と泳ぎたいの？"
"2004703-37-キキョウ" = "……そ、そんなに頷かなくても、分かったから。"
"2004703-38-キキョウ" = "（大丈夫……教本は頭に入ってる……）"
"2004703-39-キキョウ" = "でも、入るのは腰の高さまで。"
"2004703-40-キキョウ" = "何かあってもすぐに戻れる距離を保つ。いい？"
"2004703-41-キキョウ" = "……。"
"2004703-42-キキョウ" = "……ねぇ、何か変なこと考えなかった？"
"2004703-43-キキョウ" = "水が苦手なわけじゃないからね？"
"2004703-44" = "[s3] \"変なことって例えば……？\"\n[s4] \"猫みたいでかわいい！\""
"2004703-47-キキョウ" = "……！！"
"2004703-48-キキョウ" = "い、いきなり何言ってるの！？"
"2004703-49-キキョウ" = "まったく、あんたって人は。"
"2004703-50-キキョウ" = "じゃあ――"
"2004703-54-キキョウ" = "――エスコートして。"
"2004703-55-キキョウ" = "猫は慣れない環境が苦手なんだから。"
"2004703-56-キキョウ" = "あんたがちゃんとリードするの。わかった？"
"2004703-57" = "[s5] \"じゃあ、猫用のハーネスをつけてもいい？\"\n[s6] \"離れないためにもね！\""
"2004703-60-キキョウ" = "そんなもの用意してるわけないでしょ……。"
"2004703-61" = "[s] \"あやとりの糸が代わりにならないかな？\""
"2004703-62-キキョウ" = "……ふふ、からかうのもいいけど、ちゃんと想像したほうがいいよ。"
"2004703-63-キキョウ" = "あんたにできると思うの？"
"2004703-64-キキョウ" = "糸を巻き付けられるのを、私もただ黙ってみてるわけじゃないんだけど。"
"2004703-65" = "[s] \"じゃあ、手をつなぐことで妥協しよう！\""
"2004703-66-キキョウ" = "……なるほどね。"
"2004703-67-キキョウ" = "最初に大きな要求をして、その後に小さな「本当の」要求を通す……。#nまあ、交渉としては及第点かな。"
"2004703-71-キキョウ" = "……いいよ。#nでもその代わり、絶対に離さないで。"
"2004703-76-キキョウ" = "冷たくて気持ちいい……。#n波は少し怖いけど……。"
"2004703-77-キキョウ" = "一人だったら、こんなところまで来られな――"
"2004703-78-キキョウ" = "……ちょっと、どこまで行くつもり？"
"2004703-79-キキョウ" = "私、腰下の深さまでって言ったよね。"
"2004703-80-キキョウ" = "……亀？#n近くにいるの？"
"2004703-81-キキョウ" = "それは……惹かれないことも――"
"2004703-82-キキョウ" = "いや、だから……はぁ。#n気になるなら、あんた一人で見てくれば？"
"2004703-83-キキョウ" = "……えっ。"
"2004703-84-キキョウ" = "待って、手を離さない約束でしょう？"
"2004703-85-キキョウ" = "ちゃんと握ってて。"
"2004703-90-キキョウ" = "え？ちょっと、なにを……。"
"2004703-91-キキョウ" = "きゃっ……！"
"2004703-99" = "（キキョウをお姫様抱っこして、一緒に亀を見に行った）"
"2004703-100" = "（その後も、日が暮れるまでキキョウと二人で海を楽しんだ）"
