[translation]
"62060-1" = "第6話;迷子の子ども"
"62060-3-アツコ" = "みんな、お疲れ様。"
"62060-8-ヒヨリ" = "と、とんでもない一日でしたね……。"
"62060-9-サオリ" = "ああ、たしかに。"
"62060-10-サオリ" = "だが……あの状況下で三人ともよく動いてくれた。"
"62060-11-ミサキ" = "逃亡生活には慣れてるからね。#n急に襲われることだってあったし。"
"62060-12" = "[s] \"みんな、強くなったんだね……。\""
"62060-13-ミサキ" = "別に、なりたくてなったわけじゃないんだけど。"
"62060-14-ミサキ" = "……なに？環境に背中を押されて強くなるもの……？"
"62060-15-ミサキ" = "はぁ……。#nほんと、それっぽく正論言うのやめてくれない？"
"62060-16-ヒヨリ" = "で、でも……私たちって……。"
"62060-17-ヒヨリ" = "……。"
"62060-18-ヒヨリ" = "この先も……ずっと、逃げながら生きていくんでしょうか……？"
"62060-19-サオリ" = "ヒヨリ……？"
"62060-23-ヒヨリ" = "い、いえっ！私、今の生活も好きですから！えへへ……。"
"62060-24-ヒヨリ" = "でも、やっぱり……。"
"62060-25-ヒヨリ" = "なんだか……。"
"62060-26-ヒヨリ" = "久しぶりに帰ってきたからか、変なことばっか考えちゃって……。"
"62060-27" = "[s1] \"……ごめんね。そんな思いをさせてしまって。\"\n[s2] \"アリウス分校のことは全部……。\"\n[s3] \"私の職務放棄のせいだから……。\""
"62060-33-ヒヨリ" = "えっ？そ、それってどういう……？"
"62060-34-サオリ" = "先生……？"
"62060-35-ミサキ" = "……。"
"62060-40-アツコ" = "ねえ、先生。なんでもかんでも、自分一人で背負い込もうとしないで。"
"62060-41-アツコ" = "これは私たちが、自分で選んだ道なんだから。"
"62060-42-アツコ" = "だから、もし……他の選択肢があるかもしれないって思うなら……。"
"62060-43-アツコ" = "その時は、みんなで考えよう。"
"62060-44-アツコ" = "今は、ミネさんからのお願いについて話さない？"
"62060-45" = "[s] \"「日常」のことだね。\""
"62060-46-アツコ" = "うん。アリウスの日常。"
"62060-47-ミサキ" = "たぶん……あの人が思ってるものとは、かけ離れてるんだけどね。"
"62060-48-ヒヨリ" = "い、今のアリウスの子たちにとっては……初めての経験ばっかりだと思うんです……。"
"62060-49-ヒヨリ" = "授業も……勉強も……校外学習も……。#n水を濾過できる道具とか、新しい医薬品だって……。"
"62060-51-サオリ" = "保温効果のある布団もあったな。前は破れたテントを使ってたのに。"
"62060-52-サオリ" = "あとは……栄養改善用の救援食も、ここじゃ見たことがなかった。"
"62060-53-サオリ" = "……改めて実感する。#n誰かにとっての「日常」が、別の誰かにとっては「奇跡」なのだと。"
"62060-55-アツコ" = "でも、ミネさんはそれを守ってほしいって言ってたよね？"
"62060-56-アツコ" = "「当たり前」を守ってほしい、って……。"
"62060-57-ミサキ" = "言うほど簡単じゃないでしょ、それ。"
"62060-58" = "[s4] \"そうだね。\"\n[s5] \"だからこそ、私が頑張らなきゃいけない。\""
"62060-61-ヒヨリ" = "でも……やっぱり勉強はイヤです……。"
"62060-62" = "[s] \"生徒の本分を忘れちゃダメだよ？\""
"62060-66-ヒヨリ" = "い、今のすごく「先生」っぽかったです……！"
"62060-67-ヒヨリ" = "あ、そっか……先生は元から先生でした……。"
"62060-68" = "[s6] \"ふふっ。思い出させてあげよう。\"\n[s7] \"私が「先生」だということをね。\""
"62060-73-ミサキ" = "何するつもり……？"
"62060-74" = "[s8] \"明日も、授業をやるよ。\"\n[s9] \"みんなにモモトークでお知らせしておかないと。\""
"62060-77-ミサキ" = "いい性格してるよね、先生。"
"62060-78-ミサキ" = "……何？嫌なことを繰り返し乗り越えることで、人は強くなるって？"
"62060-79-ミサキ" = "はぁ……その言葉、アリウスでもよく言われてたよ。#nもっと違う言い方をしてたけど。"
"62060-80-サオリ" = "たしかに、そうだったな……。"
"62060-81-サオリ" = "だが、アリウス式の訓練に比べれば、先生の授業の方がずっとマシだと思う。"
"62060-82-サオリ" = "私はそうだが……お前は違うのか？"
"62060-83-ミサキ" = "……そんなこと、言った覚えないんだけど。"
"62060-88-アツコ" = "ふふっ。"
"62060-89-ヒヨリ" = "えへへ……。"
"62060-94-ミサキ" = "……ねぇ、なんで私ばっかり？"
"62060-109-アリウスの生徒C" = "モモトーク……先生から？"
"62060-113-アリウスの生徒C" = "「今日は本当にお疲れ様でした」"
"62060-114-アリウスの生徒C" = "「色々なことがありましたが、変わらず明日も授業を行います」"
"62060-115-アリウスの生徒C" = "「皆さん、奮ってご参加ください」"
"62060-116-アリウスの生徒C" = "……何これ、ふざけてるの？"
"62060-117-アリウスの生徒D" = "今がどんな状況か分かってないのかな……。"
"62060-118-アリウスの生徒D" = "先輩が戻ってきたら伝えなきゃ……。"
"62060-126-アリウスの生徒C" = "あっ、先輩！さっき先生からモモトークが来て……！"
"62060-127-アリウスの生徒D" = "それで、その内容がですね――"
"62060-129-スバル" = "知ってますよ。"
"62060-131-アリウスの生徒C" = "えっ、はい？"
"62060-132-アリウスの生徒D" = "そ、そうですか……それなら、よかったです……。"
"62060-134-スバル" = "とはいえメッセージは消してしまったので、もう読めませんが。"
"62060-136-アリウスの生徒A" = "はい……？"
"62060-137-アリウスの生徒B" = "け、消しちゃったんですか……？"
"62060-142-スバル" = "何か問題でも？"
"62060-147-アリウスの生徒A" = "い、いえっ！何でもないです！"
"62060-149-スバル" = "それでは。"
"62060-150-スバル" = "もういい時間ですから、そろそろ休みましょう。"
"62060-152-アリウスの生徒C" = "……寝る、んですか？"
"62060-153-アリウスの生徒D" = "たしかに寝る時間だけど……。"
"62060-154-アリウスの生徒C" = "こんな風に何も知らないふりしてモモトーク送ってくる先生とか……。"
"62060-155-アリウスの生徒C" = "あと、一緒にいるスクワッドに……#nちょっとくらい抗議してもいいんじゃないんですか……？"
"62060-156-アリウスの生徒D" = "……マイアだって、追い出しちゃったけど。#nそれでもせめて、毛布くらいは届けてあげたほうが……。"
"62060-161-スバル" = "……。"
"62060-162-スバル" = "同じことを言わせないでください。"
"62060-164-アリウスの生徒A" = "先輩……？"
"62060-165-アリウスの生徒B" = "え……？"
"62060-172-スバル" = "さっさと――"
"62060-173-スバル" = "寝なさい。"
"62060-174-スバル" = "いいですね？"
"62060-180-アリウスの生徒C" = "……！"
"62060-181-アリウスの生徒C" = "は、はいっ！"
"62060-182-アリウスの生徒D" = "先輩も……おやすみなさいっ！"
"62060-190-スバル" = "ふぅ……。"
"62060-191-スバル" = "……。"
"62060-192-スバル" = "今日は[ruby=ここ]バシリカ[/ruby]で寝るとしましょうか。"
"62060-193-スバル" = "……。"
"62060-194-スバル" = "はぁ……この感覚は……。"
"62060-199-スバル" = "死してなお、眠れないような……あの感覚ですね……。"
"62060-209-マイア" = "……。"
"62060-210-マイア" = "どう、しよう……これから……。"
"62060-211-マイア" = "……。"
"62060-212-マイア" = "いっそ、このまま……。"
"62060-213-マイア" = "……このまま。"
"62060-215-マイア" = "消えてしまいたい……。"
"62060-221-マイア" = "モモトーク……？誰から……？"
"62060-222-マイア" = "……。"
"62060-226-マイア" = "授業……明日も……こんな時に？"
"62060-227-マイア" = "先生は、本当に……。"
"62060-228-マイア" = "……。"
"62060-229-マイア" = "うぅ……。"
"62060-232" = "机はあるし、イスも起こせば問題ない。"
"62060-233" = "教卓も黒板もある！完璧な教室じゃないかな？"
"62060-236" = "初回は短めだから大丈夫だよ。"
"62060-237" = "出席を取って、軽くガイダンスをして終わりかな。"
"62060-248-マイア" = "うぅっ……。"
"62060-249-マイア" = "……行こう。"
"62060-250-マイア" = "先生の……ところに……。"
"62060-251-マイア" = "うぅ……ひっく……。"
"62060-256-マイア" = "うわああああああん……！"
"62060-260" = "（眠れなくて、天井を見つめていた）"
"62060-261" = "（黙示録……ラッパの音……天使……言葉が頭の中を駆け巡っていく……）"
"62060-269" = "[ns] \"はーい、ちょっと待ってね。\""
"62060-279" = "[ns] \"マイア！？どうしたの？\""
"62060-280-マイア" = "こ、こんな時間にすみません……。"
"62060-281-マイア" = "本当に……本当に申し訳ないんですけど――"
"62060-282-マイア" = "ひと晩だけ……泊めていただけませんか……？"
"62060-283-マイア" = "明日には、ちゃんと……消えますから。"
"62060-284-マイア" = "二度とご迷惑はおかけしませんから……今日だけ……どうか……。"
"62060-288" = "[ns] \"いいよ。どうぞ、中に入って。\""
"62060-289-マイア" = "わわっ！？"
"62060-297" = "[ns] \"まずは手と顔を洗おうか。\""
"62060-298-マイア" = "だ、大丈夫です！大丈……夫、です……。"
"62060-303" = "（顔の腫れがひどいので、水で洗ってあげた）"
"62060-304" = "（その水を飲もうとしたので、急いで飲み物をたくさん用意した）"
"62060-305" = "（何があったのか聞こうかと思ったけど……）"
"62060-308-マイア" = "……。"
"62060-309" = "[s10] \"さ、今日はゆっくり休もう。\"\n[s11] \"寝袋は自由に使っていいからね。\""
"62060-312-マイア" = "え……？"
"62060-313-マイア" = "で、でもこれ、先生の……ですよね？"
"62060-314-マイア" = "こ、こんなに気を遣っていただかなくても……。"
"62060-315-マイア" = "って、先生！それアルミブランケットですよね……？"
"62060-316-マイア" = "だ、ダメです！それはおかしいですっ！私がそのブランケットを使います！"
"62060-317-マイア" = "えっ？それなら外で寝る……？それはもっとダメですけど！？"
"62060-321-マイア" = "はぁ……はぁ……わ、分かりまし……た……。"
"62060-322-マイア" = "寝袋、使わせてもらいます……ありがとうございます……。"
"62060-323-マイア" = "お腹……？いえっ、大丈夫ですっ！全然空いてないのでっ！"
"62060-328" = "[ns] \"ふふっ、お腹は正直だね。\""
"62060-329-マイア" = "うぅ……すみません……。"
"62060-338-マイア" = "もぐもぐ……ごくっ。"
"62060-339" = "[s] \"焦らなくて大丈夫だよ。\""
"62060-342-マイア" = "で、でも……でも……。"
"62060-343-マイア" = "これ、美味しいです。"
"62060-344-マイア" = "……本当に、美味しい……です……。"
"62060-345-マイア" = "……。"
"62060-346-マイア" = "うっ……。"
"62060-347" = "[s] \"……。\""
"62060-349" = "[ns] \"……お腹いっぱいになった？\""
"62060-350-マイア" = "はい……ありがとうございます……。"
"62060-351-マイア" = "えっ……先生、食べてすぐ寝るんですか……？"
"62060-352-マイア" = "……。"
"62060-353-マイア" = "あの……。"
"62060-354-マイア" = "何があったのか、とか……聞かないんですか……？"
"62060-355" = "[s12] \"今日はもう遅いしさ。\"\n[s13] \"ふわぁ……眠くなってきちゃった……。\""
"62060-361-マイア" = "すみません……。"
"62060-362-マイア" = "私がこんな時間に来たせいで……。"
"62060-363-マイア" = "ごめんなさ……い……。"
"62060-364-マイア" = "えっ？気にしないでいい、と言われても……だって……。"
"62060-365-マイア" = "あの、私……明日、先生が起きるまでには……消えますから……。"
"62060-366-マイア" = "……なんで、ですか。#n本当に……ここにいても……いいんですか……？"
"62060-367-マイア" = "でも、私、その……。"
"62060-368" = "[s14] \"なにも気にしなくていいんだよ。\"\n[s15] \"話だって、マイアが話したくなったら聞くからさ。\""
"62060-371-マイア" = "……。"
"62060-372-マイア" = "…………。"
"62060-373-マイア" = "ありがとうございます、先生。"
"62060-374-マイア" = "ありがとう、ござい……ます……。"
"62060-375-マイア" = "うぅっ、うぅ……。"
"62060-377" = "（よほど疲れていたのだろう。すぐに小さな寝息が聞こえてきた）"
"62060-381" = "（悲しい夢を見ているのか、時折うなされていたけれど……）"
"62060-382" = "（こういうのこそ、先生の役目なんだと思った）"
"62060-390-スバル" = "皆さん、集まっていますね？"
"62060-392-アリウスの生徒たち" = "はい！"
"62060-393-スバル" = "それでは――"
"62060-394-スバル" = "ポルタパシスへ向かいます。"
"62060-396-アリウスの生徒たち" = "はい！"
"62060-400-アリウスの生徒A" = "……本当に大丈夫かな？"
"62060-401-アリウスの生徒B" = "まだ夜明け前だよ……？#n早く寝ろって昨日言ってたのは、このため？"
"62060-402-アリウスの生徒B" = "なんでこんな早朝に……ポルタパシスのこともよく分かんないし……#nなんか不安かも……。"
"62060-403-アリウスの生徒A" = "このままついて行ったら、先生の授業に出られないよね……。"
"62060-404-アリウスの生徒B" = "というか、ポルタパシスに行って何も分からなかったらどうするの……？"
"62060-405-アリウスの生徒A" = "しっ、聞こえちゃうって！"
"62060-410-スバル" = "何か問題でも？"
"62060-416-アリウスの生徒たち" = "いえっ！なんでもありません！"
"62060-424-スバル" = "――だから、目をさましていなさい。"
"62060-428-スバル" = "その日その時が、あなたがたには分からないからである。"
"62060-437-ミサキ" = "……。"
"62060-438-アツコ" = "……。"
"62060-439-ヒヨリ" = "だ、誰も……来てないみたい……ですね？"
"62060-444-マイア" = "……。"
"62060-445-サオリ" = "これが……いわゆる「無断欠席」か？"
"62060-446" = "[s16] \"……そうだね。\"\n[s17] \"でも、全員一斉に、か……。\""
"62060-449-アツコ" = "先生、どうする？といっても、みんなが行きそうな場所の心当たりはないんだけど。"
"62060-453-アツコ" = "え？電話してみるって……誰に？"
"62060-454-アツコ" = "スバル……？"
"62060-455-アツコ" = "……分かった、お願い。"
"62060-462-ヒヨリ" = "……。"
"62060-463-ヒヨリ" = "出ない……ですか……？"
"62060-464" = "[s18] \"授業が嫌になっちゃったのかもしれないけど……。\"\n[s19] \"黙っていなくなったら心配だよね……。\""
"62060-471-マイア" = "あの、先生……。#nみんなが行った場所の心当たりが、あります。"
"62060-475-サオリ" = "分かるのか？"
"62060-476-マイア" = "はい……たぶん、みんな――"
"62060-480-マイア" = "「ポルタパシス」に向かったんだと思います……。"
"62060-484-アツコ" = "！！！"
"62060-486" = "次回;ポルタパシス（１）"
