[translation]
"62100-1" = "第10話;巣"
"62100-3-アリウスの生徒A" = "お願いです、サオリ先輩！どうかお引き取りください！"
"62100-4-アリウスの生徒B" = "私たちはここを守るよう、命令されてるんです！誰も中に入れちゃいけないって！"
"62100-6-サオリ" = "お前たちから快く思われていないことは、よく分かっている。"
"62100-7-サオリ" = "だが、対立してばかりでは何も変わらない……！"
"62100-8-サオリ" = "私たちは、スバルと話をしに来ただけなんだ！"
"62100-9-サオリ" = "そもそも、ここへの立ち入りは強く禁じられているはずじゃなかったのか？"
"62100-11-アリウスの生徒A" = "そ、そう言われても……！"
"62100-12-アリウスの生徒B" = "どうしよう……？"
"62100-13-アリウスの生徒A" = "でも、スバル先輩は……ここを守れって。"
"62100-14-アリウスの生徒B" = "あれ……？でも、陣地を作っておけって言ってたよね……？"
"62100-15-アリウスの生徒A" = "出入りさせるなって言ってたから、同じことだよね！"
"62100-16-アリウスの生徒B" = "やっぱり引き返してください！#nそうじゃないと、私たちも発砲するしか――"
"62100-21-アリウスの生徒A" = "だ、誰！？"
"62100-22-アリウスの生徒たち" = "あっ、ごめん……。#n発砲って言葉が聞こえたから、つい……。"
"62100-27-サオリ" = "……撃たれたな。"
"62100-28-ミサキ" = "うん、撃たれたね。"
"62100-29-ヒヨリ" = "なんか、そんな気はしてましたけど……。"
"62100-31-マイア" = "だ、大丈夫なんですか！？相手が多すぎるんじゃ……。"
"62100-32-アツコ" = "心配いらないよ。"
"62100-33-マイア" = "……なっ、なんでそんなに自信があるんですか！？"
"62100-35-ミサキ" = "そんなこと言われても……。"
"62100-36-アツコ" = "見せた方が早いんじゃないかな。"
"62100-37-アツコ" = "それじゃあ、先生。お願いね。"
"62100-38" = "[s] \"なんで毎回こうなっちゃうのかなぁ……。\""
"62100-39-アツコ" = "それは……。"
"62100-41-アツコ" = "これがアリウス流だから、かな。"
