[translation]
"1004202-1" = "廃墟の中のお姫様"
"1004202-2-アツコ" = "（すーっ、ごしごし）"
"1004202-3" = "[s] \"えっと……おはよう、アツコ。\""
"1004202-4-アツコ" = "（…………）"
"1004202-9-アツコ" = "……あ。"
"1004202-14-アツコ" = "ごめん、癖で。"
"1004202-15-アツコ" = "もう手話もマスクも要らないんだった。"
"1004202-16-アツコ" = "……仕切り直し。"
"1004202-17-アツコ" = "おはよう、先生。"
"1004202-18" = "[s1] \"……うん、おはよう。\"\n[s2] \"おはよう……今、夜だけど。\""
"1004202-19-アツコ" = "挨拶は大事……だから。"
"1004202-20-アツコ" = "挨拶は大事……だから。"
"1004202-21-アツコ" = "ここは放置された廃校の建物だけど、隠れるにはちょうど良いの……あと一週間くらいはここにいる予定で。"
"1004202-22-アツコ" = "みんな忙しいみたいで、どこかに行っちゃった。食べ物や飲み物は、いっぱい置いてくれたけど……。"
"1004202-23-アツコ" = "だから、こっそり先生を呼んだの。バレちゃダメ。先生は、秘密の友達。"
"1004202-24" = "[s] \"なるほど、秘密の友達……。\""
"1004202-25-アツコ" = "そう、秘密。みんなにバレると困る。良い？"
"1004202-26-アツコ" = "じゃあ、先生。何をして遊ぼうか？"
"1004202-27" = "[s] \"うーん……。\""
"1004202-28-アツコ" = "……良いこと思いついた。「学校ごっこ」。"
"1004202-29" = "[s] \"学校ごっこ？\""
"1004202-30-アツコ" = "教室で先生の授業を受ける。今までに一度も無かったから。"
"1004202-31-アツコ" = "ここも昔は学校だったみたいで、教室がある。"
"1004202-32-アツコ" = "ここに、生徒も先生もいる。"
"1004202-33-アツコ" = "行こう。"
"1004202-37" = "[ns] ついて行く。"
"1004202-41-アツコ" = "……。"
"1004202-42" = "[s] \"これはちょっと、座れそうにもないね……。\""
"1004202-43-アツコ" = "うん。雰囲気だけでも味わいたかったけど、無理そう。"
"1004202-44-アツコ" = "仕方ない。学校ごっこはやめる。"
"1004202-45-アツコ" = "うーん……他に何があるかな。"
"1004202-49-アツコ" = "……うん？"
"1004202-50-アツコ" = "先生。みんなが帰ってくるって。"
"1004202-51-アツコ" = "今日の遊びはここまで。先生がいることがバレたら、怒られるから。"
"1004202-52" = "[s] \"う、うん……。\""
"1004202-53-アツコ" = "ごめん。また今度、遊ぼうね。"
"1004202-55" = "（残念そうな顔のアツコを後にして、廃校を出た。）"
