[translation]
"1004203-1" = "真夜中の学校"
"1004203-2" = "某学園・本館の屋上"
"1004203-3-アツコ" = "おはよう、先生。"
"1004203-4" = "[s1] \"おはよう。\"\n[s2] \"おはよう、今日も既に夜だけど……。\""
"1004203-5-アツコ" = "挨拶は大事。"
"1004203-6-アツコ" = "挨拶は大事。"
"1004203-7" = "[s] \"確かに。ところでここは……。\""
"1004203-8-アツコ" = "この間見つけたの。"
"1004203-9" = "[s] \"なるほど……？\""
"1004203-10-アツコ" = "こっちのドアが開いてるから、ここから建物の中に入れる。"
"1004203-11-アツコ" = "さあ、行こう。"
"1004203-15" = "[ns3] \"ちょ、ちょっと……ま、待って、アツコ！\"\n[ns4] \"勝手に入るのは……！\""
"1004203-16-アツコ" = "……すごい。先生、早く来て。"
"1004203-17-アツコ" = "……すごい。先生、早く来て。"
"1004203-18" = "[ns] とりあえずついて行く。"
"1004203-23-アツコ" = "すごいね。他の学校って、こうなってるんだ。"
"1004203-24-アツコ" = "あれが教室？"
"1004203-28" = "[ns5] \"ま、待って！\"\n[ns6] 追いかける。"
"1004203-31-アツコ" = "……。"
"1004203-32-アツコ" = "こんな感じ、なんだね……。"
"1004203-33" = "[s] \"アツコ、勝手に学校に入ったらダメだよ。\""
"1004203-34-アツコ" = "……どうして？"
"1004203-35-アツコ" = "別に、問題を起こそうとしているわけじゃない。"
"1004203-36-アツコ" = "……でも、分かってる。見つかったら多分、怒られるだろうし……。"
"1004203-37-アツコ" = "もう少ししたら出るから、それなら良い？"
"1004203-38" = "[ns7] \"……うん、そうだね。\"\n[ns8] \"少しだけだよ？\""
"1004203-39-アツコ" = "……うん！"
"1004203-40-アツコ" = "……うん！"
"1004203-47" = "（アツコが前の席に座った。）"
"1004203-48-アツコ" = "先生、質問。"
"1004203-49" = "[s] \"……質問？\""
"1004203-50-アツコ" = "授業の中で、気になることがありました。"
"1004203-51" = "[s9] （あ………学校ごっこか）\n[s10] \"はい。アツコさん、どうぞ。\""
"1004203-52-アツコ" = "子どもって、どうやってできるの？"
"1004203-53-アツコ" = "子どもって、どうやってできるの？"
"1004203-54" = "[s] \"……。\""
"1004203-55-アツコ" = "……冗談。先生、そんなに困らないで。"
"1004203-59-アツコ" = "それじゃ、他のところにも行こう。"
"1004203-61-アツコ" = "ここは講堂？"
"1004203-62-アツコ" = "この席が全部、生徒で埋まるのかな。"
"1004203-63-アツコ" = "きっと賑やかな光景なんだろうね。"
"1004203-65-アツコ" = "ここはシャワー室かな。"
"1004203-66-アツコ" = "みんなで洗い合うの、楽しいよね。私も好き。"
"1004203-67-アツコ" = "アリウスにいる時も……みんなで一緒にシャワーを浴びる時間が、一番好きだった。"
"1004203-68-アツコ" = "じゃあ、次の場所に行こう。"
"1004203-70-アツコ" = "ここは部室、かな。"
"1004203-71-アツコ" = "小石研究部……石を集めてるのかな？……ふふっ、そんな部活もあるんだ。"
"1004203-72-アツコ" = "そっか……趣味の数だけ、部活があるんだね。"
"1004203-73" = "[s] \"アツコの趣味は？\""
"1004203-74-アツコ" = "趣味……?"
"1004203-75-アツコ" = "私は……"
"1004203-79-アツコ" = "あっ、バレちゃった！"
"1004203-80" = "[s] \"逃げよう！\""
"1004203-84" = "（アツコを連れて、急いで学校の外に出た。）"
"1004203-86-アツコ" = "……ふふ。危なかったね。"
"1004203-87-アツコ" = "でも……スリルがあって楽しかった。ね？"
"1004203-88" = "[s] \"はぁ……。\""
"1004203-89-アツコ" = "私のワガママに付き合ってくれてありがとう、先生。"
"1004203-90-アツコ" = "今日はここまで。じゃあ、また。"
