[translation]
"1007903-1" = "天性のオーラ"
"1007903-2" = "（トラブルが発生したと聞き、慌てて公園に向かうと……）"
"1007903-3" = "（近くまで来たところで、御坂の声が聞こえてきた）"
"1007903-5-御坂美琴" = "や……やめてよ、もう。"
"1007903-6-御坂美琴" = "本当に困るって。"
"1007903-7-御坂美琴" = "いい加減にしないと、流石に――"
"1007903-10" = "[ns1] \"御坂！\"\n[ns2] \"何があったの！？"
"1007903-17-御坂美琴" = "あ、先生……？"
"1007903-18-御坂美琴" = "ちょうどいいところに。"
"1007903-19-御坂美琴" = "はぁ、さっきからこの調子なのよ。#n先生からも、何か言ってくれないかしら？"
"1007903-20" = "[s3] \"まずは、みんな落ち着いて。\"\n[s4] \"何があったのか知らないけど、みんな仲良くね。\""
"1007903-24-御坂美琴" = "この人たちが、急に私の事を「お姉様」って呼んできて……"
"1007903-29" = "[ns5] \"……え？\"\n[ns6] \"ど、どういうこと……？\""
"1007903-32-御坂美琴" = "……えっと、言葉通りよ。"
"1007903-33-御坂美琴" = "……えっと、言葉通りよ。"
"1007903-34-チンピラA" = "で、でも……誰がどう見ても「お姉様」ですよね！"
"1007903-35-チンピラB" = "そうですよ！年齢なんて関係ありません！"
"1007903-36-チンピラB" = "大人の先生に対して物怖じしないところも素敵です！"
"1007903-37-御坂美琴" = "はぁ、また面倒なことに……"
"1007903-38-御坂美琴" = "……え？あぁ、ちゃんと説明してなかったわね。"
"1007903-39-御坂美琴" = "それが……詳しく説明すると長くなるんだけど……"
"1007903-40-御坂美琴" = "簡単に言うと、事故に巻き込まれそうになったところを助けたのよ……電撃で。"
"1007903-41-チンピラA" = "マジで危機一髪だったんだ！突然、工事現場から鉄骨が落ちてきて！"
"1007903-42-チンピラB" = "お姉様が不思議な力で飛ばしてくれなかったら、今頃コイツ大怪我してたはずなんですよ！"
"1007903-43-チンピラB" = "それをお姉様が、ドカーンって！！"
"1007903-47-御坂美琴" = "……とにかく。"
"1007903-48-御坂美琴" = "それから、ずっとこんな感じで……助けた理由を聞かれた時、人助けに理由なんて必要ないって答えたのも気に入られちゃった要因みたいで……"
"1007903-49-チンピラB" = "当然みたいに言ってますけど、簡単にできることじゃないですよ！？"
"1007903-50-チンピラA" = "ましてや、私たちみたいな不良を助けてくれるなんて……#n逆に罠を仕掛けられていても、おかしくないのに！"
"1007903-51-御坂美琴" = "だから、そんなの私は知らないって……"
"1007903-52-御坂美琴" = "ま、ちょっと変わった服装だなとは思ったけど、不良だなんて言われるまで分からなかったし。"
"1007903-53-チンピラA" = "相手が誰であろうと助けてくださるその精神……！"
"1007903-54-チンピラB" = "やはり、あなたはお姉様です……！！"
"1007903-58" = "[ns7] \"事件にでも巻き込まれたのかと思ったけど……\"\n[ns8] \"そうじゃなくて安心したよ。\""
"1007903-64-御坂美琴" = "いやいや！安心しないでほしいんだけど！？"
"1007903-65-御坂美琴" = "それにまだ中学生だし、高校生にお姉様って呼ばれたくないから！"
"1007903-66-チンピラA" = "だから年齢は関係ないんですってば！"
"1007903-67-チンピラB" = "そうだ、他の奴らも紹介しますよ！#nお姉様が望むなら、ここら一帯の不良を集めてきて……"
"1007903-68-御坂美琴" = "ああっ、もう！やめてって！#n誰かに聞かれでもしたら、私まで不良だと勘違いされちゃうじゃない！"
"1007903-69-御坂美琴" = "これ以上はもうやめて。警告したからね？#n次はないわよ。"
"1007903-70-チンピラA" = "うっ……流石はお姉様、まさに孤高の一匹狼だ。"
"1007903-71-チンピラB" = "た、たしかに、群がって強くなった気になるのは、私らみたいな弱い奴のやることですもんね……。"
"1007903-72-チンピラB" = "考えが甘かったです！出直してきます！！"
"1007903-73-御坂美琴" = "だから、私の話を聞きなさいってばー！！！"
"1007903-74-御坂美琴" = "先生！黙ってないで、なんとか言ってよ！#n先生が言えば聞いてくれるでしょ！？"
"1007903-78-御坂美琴" = "……先生？"
"1007903-82" = "[ns9] スマホで終わっていない仕事を確認する。\n[ns10] \"ごめん、仕事の連絡が……何か言った？\""
"1007903-85-御坂美琴" = "とぼけてんじゃないわよ！！"
"1007903-87" = "（その後……不良たちを説得し、穏便に帰ってもらった）"
"1007903-88" = "（……しつこく付きまとわないように、忠告を添えて）"
